# Local-only GNU identity checks. This is not a release-manifest fallback.
# Called only after GnuAROS.cmake's shared JSON/inventory functions exist.

function(_aros_gnu_load_local_descriptor out_json root)
    if(EXISTS "${root}/toolchain-manifest.json" OR
       IS_SYMLINK "${root}/toolchain-manifest.json")
        message(FATAL_ERROR "Local GNU compiler cannot coexist with a release manifest")
    endif()
    _aros_gnu_validate_sha256("${AROS_CROSS_TOOLCHAIN_LOCAL_SHA256}" "local descriptor SHA256")
    set(_descriptor "${root}/toolchain-local.json")
    find_program(_regular_test NAMES test PATHS /usr/bin /bin NO_DEFAULT_PATH NO_CACHE REQUIRED)
    foreach(_contract IN ITEMS "${_descriptor}" "${root}/toolchain-tools.json")
        if(IS_SYMLINK "${_contract}")
            message(FATAL_ERROR "Local GNU metadata is linked: ${_contract}")
        endif()
        execute_process(COMMAND "${_regular_test}" -f "${_contract}" RESULT_VARIABLE _regular)
        if(NOT _regular EQUAL 0)
            message(FATAL_ERROR "Local GNU metadata is not a regular file: ${_contract}")
        endif()
        file(SIZE "${_contract}" _size)
        if(_size GREATER 16777216)
            message(FATAL_ERROR "Local GNU metadata exceeds 16 MiB")
        endif()
    endforeach()
    file(SHA256 "${_descriptor}" _descriptor_sha)
    if(NOT _descriptor_sha STREQUAL AROS_CROSS_TOOLCHAIN_LOCAL_SHA256)
        message(FATAL_ERROR "Local GNU descriptor bytes changed after admission")
    endif()
    file(READ "${_descriptor}" _json)
    _aros_gnu_require_members("${_json}" "local descriptor"
        "schema;qualification;host;target_profile;target_triple;compiler;tree_sha256;tool_layout_sha256;files")
    _aros_gnu_json_string(_schema "${_json}" "local descriptor" schema)
    _aros_gnu_json_string(_qualification "${_json}" "local descriptor" qualification)
    if(NOT _schema STREQUAL "aros-local-toolchain-v1" OR
       NOT _qualification STREQUAL "local-byte-verified")
        message(FATAL_ERROR "Unsupported local GNU identity contract")
    endif()
    _aros_gnu_json_string(_host "${_json}" "local descriptor" host)
    if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
        set(_host_os macos)
    elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
        set(_host_os linux)
    else()
        message(FATAL_ERROR "Unsupported local GNU compiler host")
    endif()
    execute_process(COMMAND /usr/bin/uname -m RESULT_VARIABLE _uname_result
        OUTPUT_VARIABLE _host_cpu OUTPUT_STRIP_TRAILING_WHITESPACE TIMEOUT 5)
    if(NOT _uname_result EQUAL 0)
        message(FATAL_ERROR "Cannot determine local GNU host architecture")
    endif()
    if(_host_cpu MATCHES "^(aarch64|arm64)$")
        set(_host_cpu aarch64)
    elseif(NOT _host_os STREQUAL "linux" OR NOT _host_cpu STREQUAL "x86_64")
        message(FATAL_ERROR "Unsupported local GNU compiler host architecture")
    endif()
    if(NOT _host STREQUAL "${_host_os}-${_host_cpu}")
        message(FATAL_ERROR "Local GNU descriptor selects another host")
    endif()
    _aros_gnu_json_string(_layout_sha "${_json}" "local descriptor" tool_layout_sha256)
    _aros_gnu_validate_sha256("${_layout_sha}" "local layout SHA256")
    file(SHA256 "${root}/toolchain-tools.json" _actual_layout_sha)
    if(NOT _layout_sha STREQUAL _actual_layout_sha)
        message(FATAL_ERROR "Local GNU layout differs from its descriptor")
    endif()
    _aros_gnu_index_inventory(_digest "${_json}")
    _aros_gnu_json_string(_declared_tree_sha "${_json}" "local descriptor" tree_sha256)
    _aros_gnu_validate_sha256("${_declared_tree_sha}" "local tree SHA256")
    string(JSON _count LENGTH "${_json}" files)
    if(_count GREATER 100000)
        message(FATAL_ERROR "Local GNU inventory exceeds 100000 entries")
    endif()
    # Check every entry, not merely the executables. No extra prefix payload
    # may silently escape the selected inventory. GLOB_RECURSE does not follow
    # directory symlinks under CMP0009 NEW.
    cmake_policy(PUSH)
    cmake_policy(SET CMP0009 NEW)
    file(GLOB_RECURSE _actual_paths LIST_DIRECTORIES TRUE RELATIVE "${root}" "${root}/*")
    cmake_policy(POP)
    list(REMOVE_ITEM _actual_paths toolchain-local.json)
    list(SORT _actual_paths)
    list(LENGTH _actual_paths _actual_count)
    if(NOT _actual_count EQUAL _count)
        message(FATAL_ERROR "Local GNU prefix inventory has missing or extra entries")
    endif()
    set(_canonical_inventory "")
    string(ASCII 10 _newline)
    math(EXPR _last "${_count} - 1")
    foreach(_index RANGE 0 ${_last})
        string(JSON _relative GET "${_json}" files ${_index} path)
        list(GET _actual_paths ${_index} _actual_relative)
        if(NOT _relative STREQUAL _actual_relative OR
           _relative STREQUAL "toolchain-local.json" OR
           _relative STREQUAL "toolchain-manifest.json")
            message(FATAL_ERROR "Local GNU prefix paths differ from its inventory")
        endif()
        if(_relative MATCHES "[;\r\n]")
            message(FATAL_ERROR "Unsafe local GNU inventory pathname")
        endif()
        _aros_gnu_find_inventory_entry(_kind _mode _sha _size _link "${_digest}" "${_relative}")
        _aros_gnu_local_json_string(_mode_json "${_mode}" "mode")
        _aros_gnu_local_json_string(_path_json "${_relative}" "path '${_relative}'")
        _aros_gnu_local_json_string(_kind_json "${_kind}" "type")
        set(_canonical_entry "{\"mode\":${_mode_json},\"path\":${_path_json}")
        if(_kind STREQUAL "file")
            _aros_gnu_local_json_string(_sha_json "${_sha}" "sha256 for '${_relative}'")
            if(NOT _size MATCHES "^[0-9]+$")
                message(FATAL_ERROR "Unsupported local GNU inventory size: ${_relative}")
            endif()
            string(APPEND _canonical_entry ",\"sha256\":${_sha_json},\"size\":${_size}")
        elseif(_kind STREQUAL "symlink")
            _aros_gnu_local_json_string(_link_json "${_link}" "symlink target for '${_relative}'")
            string(APPEND _canonical_entry ",\"target\":${_link_json}")
        endif()
        string(APPEND _canonical_entry ",\"type\":${_kind_json}}")
        string(APPEND _canonical_inventory "${_canonical_entry}${_newline}")
        set(_path "${root}/${_relative}")
        if(_kind STREQUAL "symlink")
            if(NOT IS_SYMLINK "${_path}" OR NOT EXISTS "${_path}")
                message(FATAL_ERROR "Local GNU symlink is missing or dangling: ${_relative}")
            endif()
            file(READ_SYMLINK "${_path}" _actual_link)
            file(REAL_PATH "${_path}" _real)
            cmake_path(IS_PREFIX root "${_real}" NORMALIZE _inside)
            if(NOT _inside OR NOT _link STREQUAL _actual_link OR IS_ABSOLUTE "${_link}")
                message(FATAL_ERROR "Local GNU symlink differs or escapes its prefix: ${_relative}")
            endif()
        elseif(IS_SYMLINK "${_path}")
            message(FATAL_ERROR "Local GNU inventory entry became linked: ${_relative}")
        elseif(_kind STREQUAL "directory")
            if(NOT IS_DIRECTORY "${_path}")
                message(FATAL_ERROR "Local GNU directory changed type: ${_relative}")
            endif()
        else()
            execute_process(COMMAND "${_regular_test}" -f "${_path}" RESULT_VARIABLE _regular)
            if(NOT _regular EQUAL 0)
                message(FATAL_ERROR "Local GNU inventory file changed type: ${_relative}")
            endif()
            file(SHA256 "${_path}" _actual_sha)
            file(SIZE "${_path}" _actual_size)
            execute_process(COMMAND "${_regular_test}" -x "${_path}" RESULT_VARIABLE _executable)
            if(_executable EQUAL 0)
                set(_actual_mode 0755)
            else()
                set(_actual_mode 0644)
            endif()
            if(NOT _actual_sha STREQUAL _sha OR NOT _actual_size STREQUAL _size OR
               NOT _actual_mode STREQUAL _mode)
                message(FATAL_ERROR "Local GNU inventory bytes or mode changed: ${_relative}")
            endif()
        endif()
    endforeach()
    string(SHA256 _measured_tree_sha "${_canonical_inventory}")
    if(NOT _measured_tree_sha STREQUAL _declared_tree_sha)
        message(FATAL_ERROR "Local GNU tree digest differs from its inventory")
    endif()
    set(${out_json} "${_json}" PARENT_SCOPE)
endfunction()

function(_aros_gnu_local_json_string out value label)
    # Match serde_json's UTF-8 output for strings without C0/C1 controls.
    # Inventory paths and symlink targets are otherwise literal UTF-8; only
    # JSON quotes and backslashes need escaping. Fail closed if CMake cannot
    # represent a control character faithfully.
    string(HEX "${value}" _value_hex)
    string(TOLOWER "${_value_hex}" _value_hex)
    if(_value_hex MATCHES "^(..)*(0[0-9a-f]|1[0-9a-f]|7f|c2(8[0-9a-f]|9[0-9a-f]))")
        message(FATAL_ERROR "Unsupported control character in local GNU ${label}")
    endif()
    string(REPLACE "\\" "\\\\" _escaped "${value}")
    string(REPLACE "\"" "\\\"" _escaped "${_escaped}")
    set(${out} "\"${_escaped}\"" PARENT_SCOPE)
endfunction()
