cmake_minimum_required(VERSION 3.22)
get_filename_component(engine "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
set(temp "$ENV{TMPDIR}")
if(NOT temp)
    set(temp /tmp)
endif()
set(root "${temp}/aros-empty-copy-${nonce}")
if(NOT IS_ABSOLUTE "${root}" OR EXISTS "${root}" OR IS_SYMLINK "${root}")
    message(FATAL_ERROR "unsafe empty-copy fixture root")
endif()
foreach(probe IN ITEMS accepted copy-first transform-first empty-transform
        unrelated nonempty unnamed excludes override)
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${CMAKE_CURRENT_LIST_DIR}/empty-header-copy"
        -B "${root}/${probe}" "-DAROS_ENGINE_DIR=${engine}" "-DPROBE=${probe}"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
    if(probe MATCHES "^(accepted|copy-first|transform-first|empty-transform)$")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "empty-copy configure failed\n${stdout}\n${stderr}")
        endif()
        execute_process(COMMAND "${CMAKE_COMMAND}" --build "${root}/${probe}" --target sample
            RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "empty-copy endpoint failed\n${stdout}\n${stderr}")
        endif()
        if(NOT probe STREQUAL "accepted")
            file(READ "${root}/${probe}/SDK/include/transformed.h" transformed)
            if(NOT transformed STREQUAL "#define TRANSFORMED 1\n")
                message(FATAL_ERROR "joined transform was not built: ${probe}")
            endif()
            if(NOT probe STREQUAL "empty-transform")
                file(READ "${root}/${probe}/SDK/include/copied.h" copied)
                if(NOT copied STREQUAL "#define COPIED 1\n")
                    message(FATAL_ERROR "joined copy was not staged: ${probe}")
                endif()
            endif()
        endif()
    elseif(probe STREQUAL "unrelated")
        if(result EQUAL 0 OR NOT "${stderr}" MATCHES "outside header staging")
            message(FATAL_ERROR "unrelated aggregate collision was not refused\n${stdout}\n${stderr}")
        endif()
    elseif(result EQUAL 0 OR NOT "${stderr}" MATCHES "Empty include copy")
        message(FATAL_ERROR "invalid empty-copy proof ${probe} was not refused\n${stdout}\n${stderr}")
    endif()
endforeach()
message(STATUS "known-empty header endpoint and refusal probes passed")
