cmake_minimum_required(VERSION 3.22)

find_program(_cmake NAMES cmake REQUIRED)
find_program(_ninja NAMES ninja ninja-build REQUIRED)
find_program(_host_cc NAMES cc clang gcc REQUIRED)
find_program(_touch NAMES touch REQUIRED)
find_program(_mkfifo NAMES mkfifo REQUIRED)
get_filename_component(_engine_dir "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fixture_template "${CMAKE_CURRENT_LIST_DIR}/host-c-file-generator")

if(DEFINED ENV{TMPDIR} AND NOT "$ENV{TMPDIR}" STREQUAL "")
    set(_temp_base "$ENV{TMPDIR}")
else()
    set(_temp_base "/tmp")
endif()
file(MAKE_DIRECTORY "${_temp_base}")
file(REAL_PATH "${_temp_base}" _temp_base_real)
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef _suffix)
set(_root "${_temp_base_real}/aros host C file generator ${_suffix}")
file(MAKE_DIRECTORY "${_root}")
file(REAL_PATH "${_root}" _root)
set(_source "${_root}/fixture source")
set(_cache "${_root}/local cache")
file(MAKE_DIRECTORY "${_source}" "${_cache}")
file(COPY_FILE "${_fixture_template}/CMakeLists.txt" "${_source}/CMakeLists.txt")
file(COPY_FILE "${_fixture_template}/generator.c" "${_source}/generator.c")
file(COPY_FILE "${_fixture_template}/recipe.txt" "${_source}/recipe.txt")
file(REAL_PATH "${_source}" _source)
file(REAL_PATH "${_cache}" _cache)

function(_write_input directory payload out_manifest)
    file(WRITE "${directory}/payload.txt" "${payload}")
    file(SIZE "${directory}/payload.txt" _size)
    file(SHA256 "${directory}/payload.txt" _hash)
    set(${out_manifest}
        "[{\"filename\":\"payload.txt\",\"sha256\":\"${_hash}\",\"size\":${_size}}]"
        PARENT_SCOPE)
endfunction()

file(SHA256 "${_source}/recipe.txt" _recipe_hash)
set(_source_manifest "[{\"path\":\"recipe.txt\",\"sha256\":\"${_recipe_hash}\"}]")
_write_input("${_cache}" "hello" _input_manifest)

function(_configure_fixture build probe cache manifest source_manifest)
    set(_args
        -S "${_source}" -B "${build}" -G Ninja
        "-DAROS_HOST_C_FILE_GENERATOR_ENGINE=${_engine_dir}"
        "-DHCF_HOST_CC=${_host_cc}"
        "-DHCF_INPUT_DIRECTORY=${cache}"
        "-DHCF_INPUT_MANIFEST_JSON=${manifest}"
        "-DHCF_SOURCE_MANIFEST_JSON=${source_manifest}"
        "-DHCF_PROBE=${probe}")
    if(_tool_override)
        list(APPEND _args "-DHCF_TOOL_SOURCE_OVERRIDE=${_tool_override}")
    endif()
    if(_tool_sha256_override)
        list(APPEND _args "-DHCF_TOOL_SHA256_OVERRIDE=${_tool_sha256_override}")
    endif()
    if(_source_root_override)
        list(APPEND _args "-DHCF_SOURCE_ROOT_OVERRIDE=${_source_root_override}")
    endif()
    if(_output_override)
        list(APPEND _args "-DHCF_OUTPUT_OVERRIDE=${_output_override}")
    endif()
    if(_real_reference)
        list(APPEND _args "-DHCF_REAL_REFERENCE=ON")
    endif()
    execute_process(COMMAND "${_cmake}" ${_args}
        RESULT_VARIABLE _result OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
    set(_configure_result "${_result}" PARENT_SCOPE)
    set(_configure_log "${_stdout}\n${_stderr}" PARENT_SCOPE)
endfunction()

function(_build_fixture build expect_success out_log)
    set(_run_log "${_root}/generator invocations.log")
    execute_process(
        COMMAND "${_cmake}" -E env "HCF_TEST_RUN_LOG=${_run_log}"
            "${_cmake}" --build "${build}" --target host-c-fixture --parallel 2
        RESULT_VARIABLE _result OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
    set(_log "${_stdout}\n${_stderr}")
    set(${out_log} "${_log}" PARENT_SCOPE)
    if(expect_success AND NOT _result EQUAL 0)
        message(FATAL_ERROR "host C generator build failed (${_result})\n${_log}")
    elseif(NOT expect_success AND _result EQUAL 0)
        message(FATAL_ERROR "host C generator build unexpectedly succeeded\n${_log}")
    endif()
endfunction()

function(_assert_invocations expected)
    set(_run_log "${_root}/generator invocations.log")
    if(EXISTS "${_run_log}")
        file(STRINGS "${_run_log}" _lines)
    else()
        set(_lines "")
    endif()
    list(LENGTH _lines _count)
    if(NOT _count EQUAL expected)
        message(FATAL_ERROR "generator invocation count was ${_count}, expected ${expected}")
    endif()
endfunction()

function(_expect_configure_failure probe expected_text cache manifest source_manifest)
    set(_build "${_root}/configure-${probe}")
    _configure_fixture("${_build}" "${probe}" "${cache}" "${manifest}" "${source_manifest}")
    if(_configure_result EQUAL 0 OR NOT _configure_log MATCHES "${expected_text}")
        message(FATAL_ERROR
            "configure probe ${probe} was not rejected as expected; result=${_configure_result}\n${_configure_log}")
    endif()
endfunction()

set(_build "${_root}/ordinary build")
_configure_fixture("${_build}" "" "${_cache}" "${_input_manifest}" "${_source_manifest}")
if(NOT _configure_result EQUAL 0)
    message(FATAL_ERROR "fixture configure failed\n${_configure_log}")
endif()
_build_fixture("${_build}" TRUE _first_log)
set(_output "${_build}/gen/fixture-result.txt")
file(READ "${_output}" _published)
if(NOT _published STREQUAL "generated:hello\n")
    message(FATAL_ERROR "unexpected generated payload: ${_published}")
endif()
_assert_invocations(1)

_build_fixture("${_build}" TRUE _noop_log)
_assert_invocations(1)
if(NOT _noop_log MATCHES "verified output is unchanged")
    message(FATAL_ERROR "unchanged generator target did not take its no-op path\n${_noop_log}")
endif()

file(REMOVE "${_output}")
_build_fixture("${_build}" TRUE _repair_log)
if(NOT EXISTS "${_output}")
    message(FATAL_ERROR "missing generator output was not repaired")
endif()
_assert_invocations(2)

set(_published_before_refusal "generated:hello\n")
_write_input("${_cache}" "changed-without-reconfigure" _changed_manifest)
execute_process(COMMAND "${_touch}" -t 203001010000 "${_cache}/payload.txt"
    RESULT_VARIABLE _touch_result)
if(NOT _touch_result EQUAL 0)
    message(FATAL_ERROR "could not future-date mutated cached input")
endif()
_build_fixture("${_build}" FALSE _input_mutation_log)
if(NOT _input_mutation_log MATCHES "cached input changed after configuration")
    message(FATAL_ERROR "build did not reject a changed, future-dated input\n${_input_mutation_log}")
endif()
file(READ "${_output}" _after_input_refusal)
if(NOT _after_input_refusal STREQUAL _published_before_refusal)
    message(FATAL_ERROR "input refusal changed the previous output")
endif()
_assert_invocations(2)
_write_input("${_cache}" "hello" _input_manifest)

file(READ "${_source}/generator.c" _original_generator)
file(APPEND "${_source}/generator.c" "\n/* pinned-source mutation */\n")
execute_process(COMMAND "${_touch}" -t 203001010000 "${_source}/generator.c"
    RESULT_VARIABLE _touch_result)
if(NOT _touch_result EQUAL 0)
    message(FATAL_ERROR "could not future-date mutated tool source")
endif()
_build_fixture("${_build}" FALSE _source_mutation_log)
if(NOT _source_mutation_log MATCHES "TOOL_SOURCE changed after configuration")
    message(FATAL_ERROR "build did not reject a changed, future-dated tool source\n${_source_mutation_log}")
endif()
file(READ "${_output}" _after_source_refusal)
if(NOT _after_source_refusal STREQUAL _published_before_refusal)
    message(FATAL_ERROR "source refusal changed the previous output")
endif()
file(WRITE "${_source}/generator.c" "${_original_generator}")

file(READ "${_source}/recipe.txt" _original_recipe)
file(APPEND "${_source}/recipe.txt" "changed\n")
_build_fixture("${_build}" FALSE _recipe_mutation_log)
if(NOT _recipe_mutation_log MATCHES "sealed source file changed: recipe.txt")
    message(FATAL_ERROR "build did not reject a changed source manifest entry\n${_recipe_mutation_log}")
endif()
file(READ "${_output}" _after_recipe_refusal)
if(NOT _after_recipe_refusal STREQUAL _published_before_refusal)
    message(FATAL_ERROR "source-manifest refusal changed the previous output")
endif()
file(WRITE "${_source}/recipe.txt" "${_original_recipe}")
_assert_invocations(2)

# Rebuild once after restoring the sealed source so its private executable is
# newer than all build inputs before the independent corruption probe below.
_build_fixture("${_build}" TRUE _restored_source_build_log)
_assert_invocations(2)

file(READ "${_build}/private-tool-path.txt" _private_tool)
string(STRIP "${_private_tool}" _private_tool)
file(APPEND "${_private_tool}" "tamper")
execute_process(COMMAND "${_touch}" -t 203001010000 "${_private_tool}"
    RESULT_VARIABLE _touch_result)
if(NOT _touch_result EQUAL 0)
    message(FATAL_ERROR "could not future-date modified private tool")
endif()
_build_fixture("${_build}" FALSE _tool_mutation_log)
if(NOT _tool_mutation_log MATCHES "private host executable changed after compilation")
    message(FATAL_ERROR "build did not reject a future-dated, modified private tool\n${_tool_mutation_log}")
endif()
file(READ "${_output}" _after_tool_refusal)
if(NOT _after_tool_refusal STREQUAL _published_before_refusal)
    message(FATAL_ERROR "private-tool refusal changed the previous output")
endif()

set(_fail_build "${_root}/generator-failure build")
_write_input("${_cache}" "FAIL" _fail_manifest)
_configure_fixture("${_fail_build}" "" "${_cache}" "${_fail_manifest}" "${_source_manifest}")
if(NOT _configure_result EQUAL 0)
    message(FATAL_ERROR "failure fixture configure failed\n${_configure_log}")
endif()
_build_fixture("${_fail_build}" FALSE _generator_failure_log)
if(NOT _generator_failure_log MATCHES "host C generator failed")
    message(FATAL_ERROR "nonzero generator status was not rejected\n${_generator_failure_log}")
endif()
set(_fail_output "${_fail_build}/gen/fixture-result.txt")
if(EXISTS "${_fail_output}")
    message(FATAL_ERROR "failed generator published a partial output")
endif()

set(_zero_build "${_root}/zero-output build")
_write_input("${_cache}" "NO_OUTPUT" _zero_manifest)
_configure_fixture("${_zero_build}" "" "${_cache}" "${_zero_manifest}" "${_source_manifest}")
if(NOT _configure_result EQUAL 0)
    message(FATAL_ERROR "zero-output fixture configure failed\n${_configure_log}")
endif()
_build_fixture("${_zero_build}" FALSE _zero_log)
if(NOT _zero_log MATCHES "did not produce the required regular output")
    message(FATAL_ERROR "exit-zero/no-output generator was accepted\n${_zero_log}")
endif()
if(EXISTS "${_zero_build}/gen/fixture-result.txt")
    message(FATAL_ERROR "exit-zero/no-output generator published an output")
endif()

set(_extra_build "${_root}/extra-output build")
_write_input("${_cache}" "EXTRA_OUTPUT" _extra_manifest)
_configure_fixture("${_extra_build}" "" "${_cache}" "${_extra_manifest}" "${_source_manifest}")
if(NOT _configure_result EQUAL 0)
    message(FATAL_ERROR "extra-output fixture configure failed\n${_configure_log}")
endif()
_build_fixture("${_extra_build}" FALSE _extra_log)
if(NOT _extra_log MATCHES "unexpected entries")
    message(FATAL_ERROR "generator extra output was accepted\n${_extra_log}")
endif()

_write_input("${_cache}" "hello" _input_manifest)
_expect_configure_failure(traversal "unsafe generator argument" "${_cache}" "${_input_manifest}" "${_source_manifest}")
_expect_configure_failure(argument-injection "unsafe generator argument" "${_cache}" "${_input_manifest}" "${_source_manifest}")
_expect_configure_failure(owner-collision "already owned" "${_cache}" "${_input_manifest}" "${_source_manifest}")
_expect_configure_failure(owner-collision-case "already owned" "${_cache}" "${_input_manifest}" "${_source_manifest}")

set(_source_link "${_source}/generator-link.c")
file(CREATE_LINK "${_source}/generator.c" "${_source_link}" SYMBOLIC RESULT _link_result)
if(NOT _link_result STREQUAL "0")
    message(FATAL_ERROR "cannot create source symlink probe: ${_link_result}")
endif()
set(_tool_override "${_source_link}")
_expect_configure_failure(source-symlink "symlinked path component" "${_cache}" "${_input_manifest}" "${_source_manifest}")
unset(_tool_override)

execute_process(COMMAND "${_mkfifo}" "${_source}/generator-fifo.c"
    RESULT_VARIABLE _fifo_result)
if(NOT _fifo_result EQUAL 0)
    message(FATAL_ERROR "cannot create tool-source FIFO probe")
endif()
file(SHA256 "${_source}/generator.c" _safe_tool_sha)
set(_tool_override "${_source}/generator-fifo.c")
set(_tool_sha256_override "${_safe_tool_sha}")
_expect_configure_failure(tool-source-fifo "regular" "${_cache}" "${_input_manifest}" "${_source_manifest}")
unset(_tool_override)
unset(_tool_sha256_override)

set(_outside_input "${_root}/outside-input.txt")
file(WRITE "${_outside_input}" "hello")
set(_link_cache "${_root}/symlink cache")
file(MAKE_DIRECTORY "${_link_cache}")
file(CREATE_LINK "${_outside_input}" "${_link_cache}/payload.txt" SYMBOLIC RESULT _link_result)
if(NOT _link_result STREQUAL "0")
    message(FATAL_ERROR "cannot create input symlink probe: ${_link_result}")
endif()
file(SIZE "${_outside_input}" _link_size)
file(SHA256 "${_outside_input}" _link_hash)
set(_link_manifest "[{\"filename\":\"payload.txt\",\"sha256\":\"${_link_hash}\",\"size\":${_link_size}}]")
_expect_configure_failure(input-symlink "symlink" "${_link_cache}" "${_link_manifest}" "${_source_manifest}")

set(_fifo_cache "${_root}/FIFO cache")
file(MAKE_DIRECTORY "${_fifo_cache}")
execute_process(COMMAND "${_mkfifo}" "${_fifo_cache}/payload.txt"
    RESULT_VARIABLE _fifo_result)
if(NOT _fifo_result EQUAL 0)
    message(FATAL_ERROR "cannot create cached-input FIFO probe")
endif()
_expect_configure_failure(input-fifo "regular" "${_fifo_cache}" "${_input_manifest}" "${_source_manifest}")

set(_output_link_build "${_root}/output-symlink build")
file(MAKE_DIRECTORY "${_output_link_build}/gen")
file(WRITE "${_root}/output-link-target.txt" "keep\n")
file(CREATE_LINK "${_root}/output-link-target.txt"
    "${_output_link_build}/gen/fixture-result.txt" SYMBOLIC RESULT _link_result)
if(NOT _link_result STREQUAL "0")
    message(FATAL_ERROR "cannot create output symlink probe: ${_link_result}")
endif()
set(_output_override "${_output_link_build}/gen/fixture-result.txt")
_configure_fixture("${_output_link_build}" "" "${_cache}" "${_input_manifest}" "${_source_manifest}")
unset(_output_override)
if(_configure_result EQUAL 0 OR NOT _configure_log MATCHES "OUTPUT is symlinked")
    message(FATAL_ERROR "configure accepted symlinked output\n${_configure_log}")
endif()

set(_output_fifo_build "${_root}/output FIFO build")
file(MAKE_DIRECTORY "${_output_fifo_build}/gen")
execute_process(COMMAND "${_mkfifo}" "${_output_fifo_build}/gen/fixture-result.txt"
    RESULT_VARIABLE _fifo_result)
if(NOT _fifo_result EQUAL 0)
    message(FATAL_ERROR "cannot create output FIFO probe")
endif()
set(_output_override "${_output_fifo_build}/gen/fixture-result.txt")
_configure_fixture("${_output_fifo_build}" "" "${_cache}" "${_input_manifest}" "${_source_manifest}")
unset(_output_override)
if(_configure_result EQUAL 0 OR NOT _configure_log MATCHES "regular")
    message(FATAL_ERROR "configure accepted FIFO output\n${_configure_log}")
endif()

set(_runtime_build "${_root}/runtime-output-symlink build")
_configure_fixture("${_runtime_build}" "" "${_cache}" "${_input_manifest}" "${_source_manifest}")
if(NOT _configure_result EQUAL 0)
    message(FATAL_ERROR "runtime output-symlink fixture configure failed\n${_configure_log}")
endif()
_build_fixture("${_runtime_build}" TRUE _runtime_init_log)
set(_runtime_output "${_runtime_build}/gen/fixture-result.txt")
set(_runtime_link_target "${_root}/runtime-output-target.txt")
file(WRITE "${_runtime_link_target}" "keep runtime target\n")
file(RENAME "${_runtime_output}" "${_runtime_output}.saved")
file(CREATE_LINK "${_runtime_link_target}" "${_runtime_output}" SYMBOLIC RESULT _link_result)
if(NOT _link_result STREQUAL "0")
    message(FATAL_ERROR "cannot create runtime output symlink probe: ${_link_result}")
endif()
_build_fixture("${_runtime_build}" FALSE _runtime_output_link_log)
if(NOT _runtime_output_link_log MATCHES "output is symlinked")
    message(FATAL_ERROR "build accepted a symlinked output\n${_runtime_output_link_log}")
endif()
file(READ "${_runtime_link_target}" _runtime_target_content)
if(NOT _runtime_target_content STREQUAL "keep runtime target\n")
    message(FATAL_ERROR "runtime output symlink probe modified its target")
endif()

if(DEFINED ENV{AROS_TEST_P4_SOURCE} AND
   NOT "$ENV{AROS_TEST_P4_SOURCE}" STREQUAL "" AND
   DEFINED ENV{AROS_TEST_GENCTBL_INPUTS} AND
   NOT "$ENV{AROS_TEST_GENCTBL_INPUTS}" STREQUAL "")
    set(_reference_source "$ENV{AROS_TEST_P4_SOURCE}")
    file(REAL_PATH "${_reference_source}" _reference_source)
    if(IS_DIRECTORY "${_reference_source}")
        set(_reference_root "${_reference_source}")
        set(_reference_source "${_reference_root}/tools/genctbl/genctbl.c")
    else()
        get_filename_component(_reference_genctbl_dir "${_reference_source}" DIRECTORY)
        get_filename_component(_reference_tools_dir "${_reference_genctbl_dir}" DIRECTORY)
        get_filename_component(_reference_root "${_reference_tools_dir}" DIRECTORY)
    endif()
    file(REAL_PATH "${_reference_root}" _reference_root)
    file(REAL_PATH "$ENV{AROS_TEST_GENCTBL_INPUTS}" _reference_inputs)
    file(SHA256 "${_reference_source}" _reference_tool_sha)
    if(NOT _reference_tool_sha STREQUAL "91033690a36ceed218b07f9643022a29b2c548c9d1bbaf31e3958c09843d3933")
        message(FATAL_ERROR "opt-in genctbl source does not match the locked reference")
    endif()
    set(_reference_manifest "[{
        \"filename\":\"UnicodeData.txt\",\"sha256\":\"ff58e5823bd095166564a006e47d111130813dcf8bf234ef79fa51a870edb48f\",\"size\":2175362},
        {\"filename\":\"SpecialCasing.txt\",\"sha256\":\"8d5de354eef79f2395a54c9c7dcebbaf3d30fc962d0f85611ea97aa973a0c451\",\"size\":16809}
    ]")
    foreach(_reference_input IN ITEMS UnicodeData.txt SpecialCasing.txt)
        if(NOT EXISTS "${_reference_inputs}/${_reference_input}" OR
           IS_SYMLINK "${_reference_inputs}/${_reference_input}")
            message(FATAL_ERROR "opt-in genctbl input is missing or symlinked: ${_reference_input}")
        endif()
    endforeach()
    file(SIZE "${_reference_inputs}/UnicodeData.txt" _unicode_size)
    file(SHA256 "${_reference_inputs}/UnicodeData.txt" _unicode_sha)
    file(SIZE "${_reference_inputs}/SpecialCasing.txt" _special_size)
    file(SHA256 "${_reference_inputs}/SpecialCasing.txt" _special_sha)
    if(NOT _unicode_size EQUAL 2175362 OR
       NOT _unicode_sha STREQUAL "ff58e5823bd095166564a006e47d111130813dcf8bf234ef79fa51a870edb48f" OR
       NOT _special_size EQUAL 16809 OR
       NOT _special_sha STREQUAL "8d5de354eef79f2395a54c9c7dcebbaf3d30fc962d0f85611ea97aa973a0c451")
        message(FATAL_ERROR "opt-in genctbl inputs differ from the locked reference")
    endif()

    set(_reference_build "${_root}/genctbl reference build")
    set(_reference_output "${_reference_build}/gen/en_GB_ISO8859-1.c")
    set(_reference_direct_dir "${_root}/direct genctbl output")
    set(_reference_direct_tool "${_root}/direct genctbl")
    file(MAKE_DIRECTORY "${_reference_direct_dir}")
    execute_process(COMMAND "${_host_cc}" -g -Wall -Werror -Wunused -O2
        "${_reference_source}" -o "${_reference_direct_tool}"
        RESULT_VARIABLE _direct_compile_result OUTPUT_VARIABLE _direct_compile_out
        ERROR_VARIABLE _direct_compile_err)
    if(NOT _direct_compile_result EQUAL 0)
        message(FATAL_ERROR "independent genctbl compile failed\n${_direct_compile_out}\n${_direct_compile_err}")
    endif()
    execute_process(COMMAND "${_reference_direct_tool}" "${_reference_inputs}"
        "${_reference_direct_dir}" en_GB_ISO8859-1 --emit-c
        RESULT_VARIABLE _direct_run_result OUTPUT_VARIABLE _direct_run_out
        ERROR_VARIABLE _direct_run_err)
    if(NOT _direct_run_result EQUAL 0)
        message(FATAL_ERROR "independent genctbl run failed\n${_direct_run_out}\n${_direct_run_err}")
    endif()
    set(_reference_direct_output "${_reference_direct_dir}/en_GB_ISO8859-1.c")
    file(SIZE "${_reference_direct_output}" _direct_output_size)
    file(SHA256 "${_reference_direct_output}" _direct_output_sha)
    if(NOT _direct_output_size EQUAL 6180 OR
       NOT _direct_output_sha STREQUAL "7906b7ca6d758463ee1788febca54b7e0a5d864f63a6c5bb070b5f1300830209")
        message(FATAL_ERROR "independent genctbl output differs from locked reference")
    endif()

    set(_tool_override "${_reference_source}")
    set(_source_root_override "${_reference_root}")
    set(_output_override "${_reference_output}")
    set(_real_reference TRUE)
    _configure_fixture("${_reference_build}" "" "${_reference_inputs}"
        "${_reference_manifest}" "[]")
    unset(_tool_override)
    unset(_source_root_override)
    unset(_output_override)
    unset(_real_reference)
    if(NOT _configure_result EQUAL 0)
        message(FATAL_ERROR "opt-in genctbl fixture configure failed\n${_configure_log}")
    endif()
    _build_fixture("${_reference_build}" TRUE _reference_log)
    file(SIZE "${_reference_output}" _reference_output_size)
    file(SHA256 "${_reference_output}" _reference_output_sha)
    if(NOT _reference_output_size EQUAL _direct_output_size OR
       NOT _reference_output_sha STREQUAL _direct_output_sha)
        message(FATAL_ERROR "host C generator output differs from independent genctbl output")
    endif()
    execute_process(COMMAND "${_cmake}" -E compare_files
        "${_reference_output}" "${_reference_direct_output}"
        RESULT_VARIABLE _compare_result)
    if(NOT _compare_result EQUAL 0)
        message(FATAL_ERROR "host C generator output differs byte-for-byte from direct genctbl")
    endif()
    message(STATUS "opt-in genctbl reference output matches the independent build")
endif()

message(STATUS "host C file generator tests passed: no-op, repair, sealed input/source/tool checks, refusal preservation, and path/output attacks")
