cmake_minimum_required(VERSION 3.22)

if(NOT DEFINED ENGINE_DIR OR NOT EXISTS "${ENGINE_DIR}/LiteralObjects.cmake")
    message(FATAL_ERROR "ENGINE_DIR must name the CMake engine")
endif()
if(NOT DEFINED TEST_BINARY_DIR OR "${TEST_BINARY_DIR}" STREQUAL "")
    message(FATAL_ERROR "TEST_BINARY_DIR must name a fresh test root")
endif()
cmake_path(ABSOLUTE_PATH ENGINE_DIR NORMALIZE OUTPUT_VARIABLE _engine_dir)
cmake_path(ABSOLUTE_PATH TEST_BINARY_DIR NORMALIZE OUTPUT_VARIABLE _test_binary_dir)
find_program(_cmake NAMES cmake REQUIRED)

set(_fixture "${CMAKE_CURRENT_LIST_DIR}/literal-objects")
if(NOT EXISTS "${_fixture}/CMakeLists.txt")
    message(FATAL_ERROR "Literal object fixture is missing: ${_fixture}")
endif()
file(MAKE_DIRECTORY "${_test_binary_dir}")
file(REAL_PATH "${_test_binary_dir}" _test_binary_dir)
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef _suffix)
set(_test_root "${_test_binary_dir}/literal-objects-${_suffix}")
while(EXISTS "${_test_root}" OR IS_SYMLINK "${_test_root}")
    string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef _suffix)
    set(_test_root "${_test_binary_dir}/literal-objects-${_suffix}")
endwhile()
file(MAKE_DIRECTORY "${_test_root}")
file(REAL_PATH "${_test_root}" _test_root)

set(_passed 0)
set(_failed 0)
function(_literal_configure case_name should_succeed expected_message)
    string(RANDOM LENGTH 8 ALPHABET 0123456789abcdef _case_suffix)
    set(_build "${_test_root}/${case_name}-${_case_suffix}")
    execute_process(
        COMMAND "${_cmake}" -S "${_fixture}" -B "${_build}" -G Ninja
            "-DENGINE_DIR=${_engine_dir}"
            "-DLITERAL_CASE=${case_name}"
        RESULT_VARIABLE _result
        OUTPUT_VARIABLE _stdout
        ERROR_VARIABLE _stderr
        TIMEOUT 90)
    set(_log "${_stdout}\n${_stderr}")
    if(should_succeed)
        if(NOT _result STREQUAL "0")
            message(FATAL_ERROR "${case_name}: configure failed (${_result})\n${_log}")
        endif()
    else()
        if(_result STREQUAL "0")
            message(FATAL_ERROR "${case_name}: configure unexpectedly succeeded")
        endif()
        string(FIND "${_log}" "${expected_message}" _found)
        if(_found LESS 0)
            message(FATAL_ERROR "${case_name}: expected '${expected_message}'\n${_log}")
        endif()
    endif()
    set(_LITERAL_TEST_BUILD "${_build}" PARENT_SCOPE)
    if(NOT should_succeed)
        message(STATUS "${case_name}: rejected (${expected_message})")
    endif()
endfunction()

function(_literal_build build_dir label should_succeed expected_message)
    execute_process(
        COMMAND "${_cmake}" --build "${build_dir}" --target literal-objects --parallel 2
        RESULT_VARIABLE _result
        OUTPUT_VARIABLE _stdout
        ERROR_VARIABLE _stderr
        TIMEOUT 90)
    set(_log "${_stdout}\n${_stderr}")
    if(should_succeed)
        if(NOT _result STREQUAL "0")
            message(FATAL_ERROR "${label}: build failed (${_result})\n${_log}")
        endif()
    else()
        if(_result STREQUAL "0")
            message(FATAL_ERROR "${label}: build unexpectedly succeeded\n${_log}")
        endif()
        string(FIND "${_log}" "${expected_message}" _found)
        if(_found LESS 0)
            message(FATAL_ERROR "${label}: expected '${expected_message}'\n${_log}")
        endif()
    endif()
    set(_LITERAL_BUILD_LOG "${_log}" PARENT_SCOPE)
endfunction()

function(_literal_verify_target build_dir target_name label expected_message)
    execute_process(
        COMMAND "${_cmake}" --build "${build_dir}" --target "${target_name}"
        RESULT_VARIABLE _result
        OUTPUT_VARIABLE _stdout
        ERROR_VARIABLE _stderr
        TIMEOUT 90)
    set(_log "${_stdout}\n${_stderr}")
    if(_result STREQUAL "0")
        message(FATAL_ERROR "${label}: preflight unexpectedly succeeded\n${_log}")
    endif()
    string(FIND "${_log}" "${expected_message}" _found)
    if(_found LESS 0)
        message(FATAL_ERROR "${label}: expected '${expected_message}'\n${_log}")
    endif()
endfunction()

_literal_configure(outside-source FALSE "source must be a rooted .c or .cpp file")
_literal_configure(output-outside-gen FALSE "output must be one .o below AROS_BUILD_DIR/gen")
_literal_configure(source-file-symlink FALSE "symlink source path refused")
_literal_configure(source-parent-symlink FALSE "symlink source path refused")
_literal_configure(source-root-symlink FALSE "symlink source root refused")
_literal_configure(build-root-symlink FALSE "symlink build root refused")
_literal_configure(output-parent-symlink FALSE "symlink output path refused")
_literal_configure(output-file-symlink FALSE "symlink output path refused")
_literal_configure(compiler-symlink FALSE "symlink compiler driver path refused")
_literal_configure(compiler-launcher FALSE "compiler arguments and launchers are not supported")
_literal_configure(bad-response FALSE "unsafe compiler argument")
_literal_configure(bad-plugin FALSE "unsafe compiler role argument")
_literal_configure(bad-specs FALSE "unsafe compiler role argument")
_literal_configure(bad-output-role FALSE "unsafe compiler role argument")
_literal_configure(bad-semicolon FALSE "unsafe compiler argument contains a control character")
_literal_configure(bad-newline FALSE "unsafe compiler argument contains a control character")
_literal_configure(bad-missing-define FALSE "requires one safe macro name")
_literal_configure(bad-invalid-define FALSE "requires one safe macro name")
_literal_configure(bad-shell FALSE "unsafe compiler argument contains a control character")
_literal_configure(bad-dollar FALSE "unsafe compiler argument contains a control character")
_literal_configure(bad-serialization FALSE "unsafe compiler argument contains a CMake")
_literal_configure(bad-machine-option FALSE "unsafe or unsupported compiler argument")
_literal_configure(bad-cmodel FALSE "unsafe or unsupported compiler argument")
_literal_configure(external-include FALSE "outside declared source/build roots")
_literal_configure(missing-build-sysroot TRUE "")
_literal_configure(sdk-output-conflict FALSE "output already owned by sdk-existing-owner")
_literal_configure(duplicate-output FALSE "output already owned by literal-c")
_literal_configure(missing-group-object FALSE "object has no registered literal producer")
_literal_configure(group-case-alias FALSE "not the exact registered output")
_literal_configure(valid-m-options TRUE "")
_literal_configure(native-includes TRUE "")
file(GLOB _native_commands "${_LITERAL_TEST_BUILD}/CMakeFiles/aros-literal-object-*.cmake")
if(NOT _native_commands)
    message(FATAL_ERROR "native-includes: no literal command file was written")
endif()
foreach(_command IN LISTS _native_commands)
    file(READ "${_command}" _native_command)
    foreach(_root GENINCDIR SDK/include/aros/stdc SDK/include)
        string(FIND "${_native_command}" "-I${_LITERAL_TEST_BUILD}/declared-build/${_root}]==]" _found)
        if(_found LESS 0)
            message(FATAL_ERROR "native-includes: ${_command} omits -I for ${_root}\n${_native_command}")
        endif()
    endforeach()
endforeach()
_literal_configure(success TRUE "")
file(GLOB _plain_commands "${_LITERAL_TEST_BUILD}/CMakeFiles/aros-literal-object-*.cmake")
foreach(_command IN LISTS _plain_commands)
    file(READ "${_command}" _plain_command)
    if(_plain_command MATCHES "GENINCDIR")
        message(FATAL_ERROR "a build without a native contract must keep the recipe verbatim\n${_plain_command}")
    endif()
endforeach()
set(_build "${_LITERAL_TEST_BUILD}")
set(_gen "${_build}/declared-build/gen/literal")
set(_c_object "${_gen}/main.o")
set(_cpp_object "${_gen}/helper.o")
_literal_build("${_build}" initial TRUE "")
if(NOT "${_LITERAL_BUILD_LOG}" MATCHES "Compiling literal object")
    message(FATAL_ERROR "initial build did not report compilation\n${_LITERAL_BUILD_LOG}")
endif()
foreach(_path "${_c_object}" "${_cpp_object}" "${_c_object}.d" "${_cpp_object}.d")
    if(NOT EXISTS "${_path}" OR IS_SYMLINK "${_path}")
        message(FATAL_ERROR "successful compile omitted a regular output: ${_path}")
    endif()
endforeach()
file(READ "${_c_object}.d" _c_depfile)
file(READ "${_cpp_object}.d" _cpp_depfile)
if(NOT _c_depfile MATCHES "system-value[.]h" OR
   NOT _cpp_depfile MATCHES "system-value[.]h")
    message(FATAL_ERROR "compiler depfiles omit system headers required by the SDK")
endif()
file(SHA256 "${_c_object}" _c_initial_hash)
file(SHA256 "${_cpp_object}" _cpp_initial_hash)

_literal_build("${_build}" no-op TRUE "")
if("${_LITERAL_BUILD_LOG}" MATCHES "Compiling literal object")
    message(FATAL_ERROR "no-op build recompiled a literal object\n${_LITERAL_BUILD_LOG}")
endif()
file(SHA256 "${_c_object}" _c_noop_hash)
file(SHA256 "${_cpp_object}" _cpp_noop_hash)
if(NOT _c_noop_hash STREQUAL _c_initial_hash OR NOT _cpp_noop_hash STREQUAL _cpp_initial_hash)
    message(FATAL_ERROR "no-op build changed compiled object bytes")
endif()
execute_process(
    COMMAND "${_cmake}" -S "${_fixture}" -B "${_build}" -G Ninja
        "-DENGINE_DIR=${_engine_dir}" -DLITERAL_CASE=success
    RESULT_VARIABLE _reconfigure_result
    OUTPUT_VARIABLE _reconfigure_stdout
    ERROR_VARIABLE _reconfigure_stderr
    TIMEOUT 90)
if(NOT _reconfigure_result STREQUAL "0")
    message(FATAL_ERROR "no-op reconfigure failed\n${_reconfigure_stdout}${_reconfigure_stderr}")
endif()
_literal_build("${_build}" no-op-reconfigure TRUE "")
if("${_LITERAL_BUILD_LOG}" MATCHES "Compiling literal object")
    message(FATAL_ERROR "no-op reconfigure rewrote or invalidated the compiler command\n${_LITERAL_BUILD_LOG}")
endif()

file(WRITE "${_build}/source-real/value.h" "#define VALUE 19\n")
_literal_build("${_build}" header-change TRUE "")
if(NOT "${_LITERAL_BUILD_LOG}" MATCHES "Compiling literal object")
    message(FATAL_ERROR "header edit did not rebuild its consumers\n${_LITERAL_BUILD_LOG}")
endif()
file(SHA256 "${_c_object}" _c_header_hash)
file(SHA256 "${_cpp_object}" _cpp_header_hash)
if(_c_header_hash STREQUAL _c_initial_hash OR _cpp_header_hash STREQUAL _cpp_initial_hash)
    message(FATAL_ERROR "header edit did not change both dependent object outputs")
endif()
file(WRITE "${_build}/source-real/sysinclude/system-value.h" "#define SYSTEM_VALUE 29\n")
_literal_build("${_build}" system-header-change TRUE "")
if(NOT "${_LITERAL_BUILD_LOG}" MATCHES "Compiling literal object")
    message(FATAL_ERROR "system header edit did not rebuild its consumers\n${_LITERAL_BUILD_LOG}")
endif()
file(SHA256 "${_c_object}" _c_system_header_hash)
file(SHA256 "${_cpp_object}" _cpp_system_header_hash)
if(_c_system_header_hash STREQUAL _c_header_hash OR _cpp_system_header_hash STREQUAL _cpp_header_hash)
    message(FATAL_ERROR "system header edit did not change both dependent object outputs")
endif()

file(REMOVE "${_c_object}" "${_c_object}.d")
_literal_build("${_build}" missing-output-repair TRUE "")
if(NOT EXISTS "${_c_object}" OR NOT EXISTS "${_c_object}.d")
    message(FATAL_ERROR "missing object or depfile was not regenerated")
endif()

foreach(_runtime_case runtime-output-symlink runtime-parent-symlink
        runtime-root-symlink runtime-source-symlink runtime-include-symlink
        runtime-sysroot-symlink runtime-compiler-symlink runtime-source-disappeared)
    if(_runtime_case STREQUAL "runtime-sysroot-symlink" OR
       _runtime_case STREQUAL "runtime-compiler-symlink")
        _literal_configure("${_runtime_case}" TRUE "")
    else()
        _literal_configure(success TRUE "")
    endif()
    set(_runtime_build "${_LITERAL_TEST_BUILD}")
    if(_runtime_case STREQUAL "runtime-source-disappeared")
        file(RENAME "${_runtime_build}/source-real/src/main.c"
            "${_runtime_build}/source-real/src/main.saved")
        _literal_verify_target("${_runtime_build}" literal-c-check "runtime-source-disappeared"
            "source is not a regular file")
        continue()
    elseif(NOT _runtime_case STREQUAL "runtime-compiler-symlink")
        _literal_build("${_runtime_build}" "${_runtime_case}-setup" TRUE "")
    endif()
    set(_runtime_root "${_runtime_build}/declared-build")
    if(_runtime_case STREQUAL "runtime-output-symlink")
        file(RENAME "${_runtime_root}/gen/literal/main.o" "${_runtime_root}/saved-main.o")
        file(CREATE_LINK "${_runtime_root}/saved-main.o" "${_runtime_root}/gen/literal/main.o" SYMBOLIC)
        set(_expected "symlink object output")
    elseif(_runtime_case STREQUAL "runtime-parent-symlink")
        file(RENAME "${_runtime_root}/gen" "${_runtime_root}/gen-real")
        file(CREATE_LINK "${_runtime_root}/gen-real" "${_runtime_root}/gen" SYMBOLIC)
        set(_expected "symlink object output path refused")
    elseif(_runtime_case STREQUAL "runtime-root-symlink")
        file(RENAME "${_runtime_root}" "${_runtime_build}/declared-build-real")
        file(CREATE_LINK "${_runtime_build}/declared-build-real" "${_runtime_root}" SYMBOLIC)
        set(_expected "symlink build root refused")
    elseif(_runtime_case STREQUAL "runtime-include-symlink")
        file(RENAME "${_runtime_build}/source-real/sysinclude"
            "${_runtime_build}/source-real/sysinclude-real")
        file(CREATE_LINK "${_runtime_build}/source-real/sysinclude-real"
            "${_runtime_build}/source-real/sysinclude" SYMBOLIC)
        set(_expected "symlink declared -isystem path refused")
    elseif(_runtime_case STREQUAL "runtime-sysroot-symlink")
        file(RENAME "${_runtime_root}/SYS/Developer" "${_runtime_root}/SYS/Developer-real")
        file(CREATE_LINK "${_runtime_root}/SYS/Developer-real"
            "${_runtime_root}/SYS/Developer" SYMBOLIC)
        set(_expected "symlink declared --sysroot path refused")
    elseif(_runtime_case STREQUAL "runtime-compiler-symlink")
        file(RENAME "${_runtime_build}/selected-compiler-dir"
            "${_runtime_build}/selected-compiler-dir-real")
        file(CREATE_LINK "${_runtime_build}/selected-compiler-dir-real"
            "${_runtime_build}/selected-compiler-dir" SYMBOLIC)
        set(_expected "symlink compiler driver path refused")
    else()
        file(RENAME "${_runtime_build}/source-real/src" "${_runtime_build}/source-real/src-real")
        file(CREATE_LINK "${_runtime_build}/source-real/src-real"
            "${_runtime_build}/source-real/src" SYMBOLIC)
        set(_expected "symlink source path refused")
    endif()
    _literal_build("${_runtime_build}" "${_runtime_case}" FALSE "${_expected}")
endforeach()

message(STATUS "Literal object engine: 39 configure cases and 20 build/preflight checks passed")
