cmake_minimum_required(VERSION 3.22)
if(NOT ENGINE_DIR OR NOT TEST_BINARY_DIR)
    message(FATAL_ERROR "ENGINE_DIR and fresh TEST_BINARY_DIR are required")
endif()
include("${ENGINE_DIR}/ModuleMacroContract.cmake")
foreach(_form IN ITEMS full runtime-only abi-only simple)
    aros_record_module_macro(OWNER "owner-${_form}" FORM "${_form}")
    get_property(_value GLOBAL PROPERTY "AROS_MODULE_MACRO_owner-${_form}")
    if(NOT _value STREQUAL _form)
        message(FATAL_ERROR "Module macro form was not preserved")
    endif()
endforeach()
file(MAKE_DIRECTORY "${TEST_BINARY_DIR}")
foreach(_case IN ITEMS duplicate unknown missing-owner missing-form extra unsafe)
    set(_script "cmake_minimum_required(VERSION 3.22)\ninclude([==[${ENGINE_DIR}/ModuleMacroContract.cmake]==])\n")
    if(_case STREQUAL "duplicate")
        string(APPEND _script "aros_record_module_macro(OWNER mod FORM full)\naros_record_module_macro(OWNER mod FORM full)\n")
    elseif(_case STREQUAL "unknown")
        string(APPEND _script "aros_record_module_macro(OWNER mod FORM inferred)\n")
    elseif(_case STREQUAL "missing-owner")
        string(APPEND _script "aros_record_module_macro(FORM full)\n")
    elseif(_case STREQUAL "missing-form")
        string(APPEND _script "aros_record_module_macro(OWNER mod FORM)\n")
    elseif(_case STREQUAL "extra")
        string(APPEND _script "aros_record_module_macro(OWNER mod FORM full EXTRA yes)\n")
    else()
        string(APPEND _script "aros_record_module_macro(OWNER ../mod FORM full)\n")
    endif()
    set(_path "${TEST_BINARY_DIR}/${_case}.cmake")
    file(WRITE "${_path}" "${_script}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -P "${_path}"
        RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
    if(_result STREQUAL "0" OR NOT "${_out}${_err}" MATCHES "source module macro contract")
        message(FATAL_ERROR "${_case}: expected contract refusal, got ${_result}: ${_out}${_err}")
    endif()
endforeach()
message(STATUS "Module macro forms and six contract refusal probes passed")
