cmake_minimum_required(VERSION 3.22)
if(NOT ENGINE_DIR OR NOT TEST_BINARY_DIR)
    message(FATAL_ERROR "Explicit engine and fresh test binary root required")
endif()
foreach(_case IN ITEMS full simple disabled-objc missing-form abi-only ambiguous-basename missing-arch missing-arch-directory malformed-arch missing-generic missing-assembly duplicate foreign private-runtime conflicting-group)
    execute_process(COMMAND "${CMAKE_COMMAND}"
        -S "${ENGINE_DIR}/tests/module-source-groups"
        -B "${TEST_BINARY_DIR}/${_case}" -G Ninja
        "-DENGINE_DIR=${ENGINE_DIR}" "-DCASE=${_case}"
        RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err TIMEOUT 60)
    if(_case STREQUAL full OR _case STREQUAL simple OR _case STREQUAL disabled-objc)
        if(NOT _result STREQUAL "0")
            message(FATAL_ERROR "${_case}: ${_out}${_err}")
        endif()
        execute_process(COMMAND "${CMAKE_COMMAND}" --build "${TEST_BINARY_DIR}/${_case}"
            --target compiled-groups --parallel 2 RESULT_VARIABLE _build
            OUTPUT_VARIABLE _build_out ERROR_VARIABLE _build_err TIMEOUT 60)
        if(NOT _build STREQUAL "0" OR NOT EXISTS "${TEST_BINARY_DIR}/${_case}/barrier.marker")
            message(FATAL_ERROR "${_case}: source group compilation failed: ${_build_out}${_build_err}")
        endif()
        file(READ "${TEST_BINARY_DIR}/${_case}/arch-object-order.txt" _object_order)
        if(NOT "${_object_order}" MATCHES "a[.]c[.]o[^\n]*\nz[.]c[.]o" AND
           NOT "${_object_order}" MATCHES "zzz/a[.]c[.]o\n.*aaa/z[.]c[.]o")
            message(FATAL_ERROR "${_case}: multi-object expansion lost architecture order: ${_object_order}")
        endif()
    else()
        if(_case STREQUAL ambiguous-basename)
            set(_expected "ambiguous architecture object")
        elseif(_case STREQUAL missing-arch OR _case STREQUAL missing-arch-directory)
            set(_expected "unresolved architecture input")
        elseif(_case STREQUAL malformed-arch)
            set(_expected "malformed architecture declaration")
        elseif(_case STREQUAL missing-generic OR _case STREQUAL missing-assembly)
            set(_expected "unresolved declared source")
        elseif(_case STREQUAL duplicate)
            set(_expected "Duplicate KOBJ source groups")
        elseif(_case STREQUAL foreign OR _case STREQUAL private-runtime)
            set(_expected "source owner is not an active runtime module")
        elseif(_case STREQUAL conflicting-group)
            set(_expected "compilation group ARCH conflicts")
        else()
            set(_expected "missing or non-runtime source macro form")
        endif()
        if(_result STREQUAL "0" OR NOT "${_out}${_err}" MATCHES "${_expected}")
            message(FATAL_ERROR "${_case}: expected ${_expected}, got ${_result}: ${_out}${_err}")
        endif()
    endif()
endforeach()
message(STATUS "Full/simple/disabled-OBJC source groups, logical fetched stems, compile-state inheritance and twelve refusal probes passed")
