cmake_minimum_required(VERSION 3.22)

find_program(_cmake NAMES cmake REQUIRED)
find_program(_ninja NAMES ninja ninja-build REQUIRED)
find_program(_sh NAMES sh REQUIRED)
find_program(_cp NAMES cp REQUIRED)
find_program(_stat NAMES stat REQUIRED)
get_filename_component(_engine_dir "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fixture_dir "${CMAKE_CURRENT_LIST_DIR}/sdk-asset-rules")

if(DEFINED ENV{TMPDIR} AND NOT "$ENV{TMPDIR}" STREQUAL "")
    set(_temp_base "$ENV{TMPDIR}")
else()
    set(_temp_base "/tmp")
endif()
cmake_path(ABSOLUTE_PATH _temp_base NORMALIZE OUTPUT_VARIABLE _temp_base)
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef _suffix)
set(_root "${_temp_base}/aros-sdk-asset-rules-${_suffix} with spaces")
if(EXISTS "${_root}" OR IS_SYMLINK "${_root}")
    message(FATAL_ERROR "temporary SDK asset test root already exists: ${_root}")
endif()
file(MAKE_DIRECTORY "${_root}")

set(_build "${_root}/build")
function(_configure build_dir probe out_result out_log)
    execute_process(
        COMMAND "${_cmake}" -S "${_fixture_dir}" -B "${build_dir}" -G Ninja
            "-DAROS_ENGINE_DIR=${_engine_dir}"
            "-DAROS_SDK_ASSET_FIXTURE_DIR=${_fixture_dir}"
            "-DAROS_SDK_ASSET_PROBE=${probe}"
        RESULT_VARIABLE _result OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
    set(${out_result} "${_result}" PARENT_SCOPE)
    set(${out_log} "${_stdout}\n${_stderr}" PARENT_SCOPE)
endfunction()

function(_build build_dir target out_result out_log)
    execute_process(
        COMMAND "${_cmake}" --build "${build_dir}" --target "${target}" --parallel 2
        RESULT_VARIABLE _result OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
    set(${out_result} "${_result}" PARENT_SCOPE)
    set(${out_log} "${_stdout}\n${_stderr}" PARENT_SCOPE)
endfunction()

function(_expect_configure_failure probe expected_text)
    set(_probe_build "${_root}/probe-${probe}")
    _configure("${_probe_build}" "${probe}" _result _log)
    string(REGEX REPLACE "[ \t\r\n]+" " " _normalized_log "${_log}")
    if(_result EQUAL 0 OR NOT _normalized_log MATCHES "${expected_text}")
        message(FATAL_ERROR "SDK asset probe ${probe} was not refused (${_result}); expected /${expected_text}/\n${_log}")
    endif()
endfunction()

function(_expect_build_failure probe target expected_text)
    set(_probe_build "${_root}/probe-${probe}")
    _configure("${_probe_build}" "${probe}" _configure_result _configure_log)
    if(NOT _configure_result EQUAL 0)
        message(FATAL_ERROR "SDK asset probe ${probe} configure failed unexpectedly\n${_configure_log}")
    endif()
    _build("${_probe_build}" "${target}" _result _log)
    if(_result EQUAL 0 OR NOT _log MATCHES "${expected_text}")
        message(FATAL_ERROR "SDK asset probe ${probe} was not refused at build time (${_result}); expected /${expected_text}/\n${_log}")
    endif()
endfunction()

_configure("${_build}" "" _configure_result _configure_log)
if(NOT _configure_result EQUAL 0)
    message(FATAL_ERROR "SDK asset fixture configure failed\n${_configure_log}")
endif()
_build("${_build}" all-sdk-assets _build_result _build_log)
if(NOT _build_result EQUAL 0)
    message(FATAL_ERROR "SDK asset initial build failed\n${_build_log}")
endif()

set(_bin "${_build}/SYS/Developer/bin")
set(_man "${_build}/SYS/Developer/man/man1")
set(_expected "${_root}/expected")
file(MAKE_DIRECTORY "${_expected}")
execute_process(COMMAND "${_cp}" -p "${_fixture_dir}/sdk-script" "${_expected}/sdk-script"
    RESULT_VARIABLE _cp_result)
if(NOT _cp_result EQUAL 0)
    message(FATAL_ERROR "could not create shell cp reference for SDK script")
endif()
execute_process(COMMAND "${_cmake}" -E compare_files "${_bin}/sdk-script" "${_expected}/sdk-script"
    RESULT_VARIABLE _compare_result)
if(NOT _compare_result EQUAL 0)
    message(FATAL_ERROR "aros_stage_sdk_files did not stage the source script byte-for-byte")
endif()
execute_process(COMMAND "${_cmake}" -E compare_files "${_bin}/sdk-script-alias" "${_bin}/sdk-script"
    RESULT_VARIABLE _compare_result)
if(NOT _compare_result EQUAL 0)
    message(FATAL_ERROR "SDK alias differs from its registered staged producer")
endif()
execute_process(COMMAND "${_cp}" -p "${_bin}/sdk-script" "${_expected}/sdk-script-alias"
    RESULT_VARIABLE _cp_result)
if(NOT _cp_result EQUAL 0)
    message(FATAL_ERROR "could not create alias mode reference")
endif()

set(_program_output "${_bin}/registered-program")
execute_process(COMMAND "${_cmake}" -E compare_files "${_bin}/program-alias" "${_program_output}"
    RESULT_VARIABLE _compare_result)
if(NOT _compare_result EQUAL 0)
    message(FATAL_ERROR "program alias differs from its registered executable output")
endif()
execute_process(COMMAND "${_cp}" -p "${_program_output}" "${_expected}/program-alias"
    RESULT_VARIABLE _cp_result)
if(NOT _cp_result EQUAL 0)
    message(FATAL_ERROR "could not create registered-program mode reference")
endif()

execute_process(COMMAND "${_sh}" -c "echo 'SDK asset manual' > '${_expected}/sdk-assets.1'"
    RESULT_VARIABLE _echo_result)
if(NOT _echo_result EQUAL 0)
    message(FATAL_ERROR "could not create literal echo reference")
endif()
execute_process(COMMAND "${_cmake}" -E compare_files "${_man}/sdk-assets.1" "${_expected}/sdk-assets.1"
    RESULT_VARIABLE _compare_result)
if(NOT _compare_result EQUAL 0)
    message(FATAL_ERROR "literal SDK man asset differs byte-for-byte from echo reference")
endif()

function(_mode path out_mode)
    execute_process(COMMAND "${_stat}" -c %a "${path}" RESULT_VARIABLE _result
        OUTPUT_VARIABLE _mode ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT _result EQUAL 0)
        execute_process(COMMAND "${_stat}" -f %Lp "${path}" RESULT_VARIABLE _result
            OUTPUT_VARIABLE _mode ERROR_VARIABLE _stderr OUTPUT_STRIP_TRAILING_WHITESPACE)
    endif()
    if(NOT _result EQUAL 0)
        message(FATAL_ERROR "stat could not read mode for ${path}: ${_stderr}")
    endif()
    set(${out_mode} "${_mode}" PARENT_SCOPE)
endfunction()

foreach(_pair IN ITEMS
        "${_bin}/sdk-script-alias|${_expected}/sdk-script-alias"
        "${_bin}/program-alias|${_expected}/program-alias")
    string(REPLACE "|" ";" _paths "${_pair}")
    list(GET _paths 0 _actual)
    list(GET _paths 1 _reference)
    _mode("${_actual}" _actual_mode)
    _mode("${_reference}" _reference_mode)
    if(NOT _actual_mode STREQUAL _reference_mode)
        message(FATAL_ERROR "SDK alias mode differs from cp -p reference: ${_actual_mode} != ${_reference_mode}")
    endif()
endforeach()
_mode("${_man}/sdk-assets.1" _man_mode)
if(NOT _man_mode STREQUAL "644")
    message(FATAL_ERROR "literal SDK man asset mode is ${_man_mode}, expected 644")
endif()

# A second build must be a no-op; touching the local staged source must rebuild
# both the SDK-file producer and the alias. Removing the final alias must repair it.
_build("${_build}" all-sdk-assets _build_result _build_log)
if(NOT _build_result EQUAL 0 OR _build_log MATCHES "Producing SDK asset|Staging SDK files")
    message(FATAL_ERROR "unchanged SDK asset build was not a no-op\n${_build_log}")
endif()
file(WRITE "${_build}/source tree/sdk/sdk-script" "#!/bin/sh\necho changed\n")
file(CHMOD "${_build}/source tree/sdk/sdk-script" PERMISSIONS
    OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
_build("${_build}" all-sdk-assets _build_result _build_log)
if(NOT _build_result EQUAL 0)
    message(FATAL_ERROR "SDK asset incremental rebuild failed\n${_build_log}")
endif()
execute_process(COMMAND "${_cmake}" -E compare_files "${_bin}/sdk-script-alias" "${_bin}/sdk-script"
    RESULT_VARIABLE _compare_result)
if(NOT _compare_result EQUAL 0)
    message(FATAL_ERROR "updated staged producer did not propagate to its alias")
endif()
file(REMOVE "${_bin}/sdk-script-alias")
_build("${_build}" all-sdk-assets _build_result _build_log)
if(NOT _build_result EQUAL 0 OR NOT EXISTS "${_bin}/sdk-script-alias")
    message(FATAL_ERROR "deleted SDK alias was not regenerated\n${_build_log}")
endif()

# The runner rechecks both endpoints at execution time, not only while CMake is
# configuring the graph.
set(_symlink_input_build "${_root}/symlink-input-build")
_configure("${_symlink_input_build}" "" _configure_result _configure_log)
if(NOT _configure_result EQUAL 0)
    message(FATAL_ERROR "symlink-input configure failed\n${_configure_log}")
endif()
_build("${_symlink_input_build}" script-producer _build_result _build_log)
if(NOT _build_result EQUAL 0)
    message(FATAL_ERROR "symlink-input producer build failed\n${_build_log}")
endif()
file(WRITE "${_root}/outside-input" "outside input\n")
file(REMOVE "${_symlink_input_build}/SYS/Developer/bin/sdk-script")
file(CREATE_LINK "${_root}/outside-input"
    "${_symlink_input_build}/SYS/Developer/bin/sdk-script" SYMBOLIC RESULT _link_result)
if(NOT _link_result STREQUAL "0")
    message(FATAL_ERROR "could not create runtime SDK input symlink: ${_link_result}")
endif()
_build("${_symlink_input_build}" sdk-script-alias _build_result _build_log)
if(_build_result EQUAL 0 OR NOT _build_log MATCHES "crosses a symlink")
    message(FATAL_ERROR "runtime SDK input symlink was not refused\n${_build_log}")
endif()

set(_symlink_output_build "${_root}/symlink-output-build")
_configure("${_symlink_output_build}" "" _configure_result _configure_log)
if(NOT _configure_result EQUAL 0)
    message(FATAL_ERROR "symlink-output configure failed\n${_configure_log}")
endif()
_build("${_symlink_output_build}" all-sdk-assets _build_result _build_log)
if(NOT _build_result EQUAL 0)
    message(FATAL_ERROR "symlink-output baseline build failed\n${_build_log}")
endif()
file(WRITE "${_root}/outside-output" "must remain unchanged\n")
file(COPY_FILE "${_root}/outside-output" "${_root}/outside-output-before")
file(REMOVE "${_symlink_output_build}/SYS/Developer/bin/sdk-script-alias")
file(CREATE_LINK "${_root}/outside-output"
    "${_symlink_output_build}/SYS/Developer/bin/sdk-script-alias" SYMBOLIC RESULT _link_result)
if(NOT _link_result STREQUAL "0")
    message(FATAL_ERROR "could not create runtime SDK output symlink: ${_link_result}")
endif()
execute_process(COMMAND "${_cmake}" -E sleep 1)
file(WRITE "${_symlink_output_build}/source tree/sdk/sdk-script" "#!/bin/sh\necho refreshed\n")
file(CHMOD "${_symlink_output_build}/source tree/sdk/sdk-script" PERMISSIONS
    OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
_build("${_symlink_output_build}" all-sdk-assets _build_result _build_log)
if(_build_result EQUAL 0 OR NOT _build_log MATCHES "crosses a symlink")
    message(FATAL_ERROR "runtime SDK output symlink was not refused\n${_build_log}")
endif()
execute_process(COMMAND "${_cmake}" -E compare_files "${_root}/outside-output"
    "${_root}/outside-output-before" RESULT_VARIABLE _compare_result)
if(NOT _compare_result EQUAL 0)
    message(FATAL_ERROR "runtime output-symlink refusal modified the external target")
endif()

# Target output properties are sealed at registration. A later property change
# must fail during final configure validation, before Ninja sees stale paths.
set(_mutating_build "${_root}/mutating-producer-build")
_configure("${_mutating_build}" "" _configure_result _configure_log)
if(NOT _configure_result EQUAL 0)
    message(FATAL_ERROR "mutating-producer baseline configure failed\n${_configure_log}")
endif()
_build("${_mutating_build}" all-sdk-assets _build_result _build_log)
if(NOT _build_result EQUAL 0)
    message(FATAL_ERROR "mutating-producer baseline build failed\n${_build_log}")
endif()
_configure("${_mutating_build}" "mutate-producer-after-registration" _configure_result _configure_log)
if(_configure_result EQUAL 0 OR
   NOT _configure_log MATCHES "program-target: registered SDK program output changed after registration")
    message(FATAL_ERROR "mutated registered executable output was not refused during final configure validation\n${_configure_log}")
endif()

_expect_configure_failure(missing-producer "distinct SDK bin file with a producer")
_expect_configure_failure(unregistered-producer "no exact registered distinct producer")
_expect_configure_failure(ambiguous-program "competing producers")
_expect_configure_failure(case-collision "already owned")
_expect_configure_failure(duplicate-keyword "keyword NAME is repeated")
_expect_configure_failure(output-escape "dot path component")
_expect_configure_failure(input-escape "dot path component")
_expect_configure_failure(output-overlap "not one direct file")
_expect_build_failure(text-control control "control or non-ASCII byte")
_expect_configure_failure(text-operation-conflict "never both")
_expect_configure_failure(symlink-root "crosses a symlink")
_expect_configure_failure(same-producer "no exact registered distinct producer")
_expect_configure_failure(overlap-bin-contains-man "roots overlap")
_expect_configure_failure(overlap-man-contains-bin "roots overlap")
foreach(_mutation IN ITEMS configured-directory configured-name runtime-name
        runtime-configured-name configured-postfix)
    _expect_configure_failure("mutate-${_mutation}" "registered SDK program output changed after registration")
endforeach()

message(STATUS "SDK asset alias/text/program registration probes passed")
