cmake_minimum_required(VERSION 3.22)
get_filename_component(_engine "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef _suffix)
set(_root "/tmp/aros-sfd-headers-${_suffix}")
function(configure_case name success)
    set(_build "${_root}/${name}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -G Ninja
        -S "${CMAKE_CURRENT_LIST_DIR}/sfd-headers" -B "${_build}"
        "-DENGINE_DIR=${_engine}" "-DCASE=${name}"
        RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
    if(success AND NOT _result EQUAL 0)
        message(FATAL_ERROR "SFD ${name} failed: ${_out}${_err}")
    elseif(NOT success AND _result EQUAL 0)
        message(FATAL_ERROR "SFD ${name} unexpectedly configured")
    endif()
    set(BUILD "${_build}" PARENT_SCOPE)
endfunction()
function(build_case success)
    execute_process(COMMAND "${CMAKE_COMMAND}" --build "${BUILD}" --target fixture-headers
        RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
    if(success AND NOT _result EQUAL 0)
        message(FATAL_ERROR "SFD build failed: ${_out}${_err}")
    elseif(NOT success AND _result EQUAL 0)
        message(FATAL_ERROR "SFD mutated build unexpectedly passed")
    endif()
endfunction()
configure_case(good TRUE)
build_case(TRUE)
set(_output "${BUILD}/SDK/include/clib/example.h")
file(READ "${_output}" _content)
if(NOT _content STREQUAL "header clib\n")
    message(FATAL_ERROR "SFD output bytes differ")
endif()
file(SHA256 "${_output}" _before)
execute_process(COMMAND /usr/bin/touch -t 203001010000 "${_output}"
    RESULT_VARIABLE _touch_result)
if(NOT _touch_result EQUAL 0)
    message(FATAL_ERROR "SFD future-output timestamp probe could not set timestamp")
endif()
file(TIMESTAMP "${_output}" _before_time UTC)
build_case(TRUE)
file(TIMESTAMP "${_output}" _after_time UTC)
if(NOT _before_time STREQUAL _after_time)
    message(FATAL_ERROR "SFD no-op regenerated a header")
endif()
file(RENAME "${_output}" "${BUILD}/retained-header")
build_case(TRUE)
file(SHA256 "${_output}" _repaired)
if(NOT _repaired STREQUAL _before)
    message(FATAL_ERROR "SFD missing output repair differs")
endif()
file(APPEND "${BUILD}/source/unit/example.sfd" "changed\n")
build_case(FALSE)
file(SHA256 "${_output}" _after_failure)
if(NOT _after_failure STREQUAL _before)
    message(FATAL_ERROR "SFD refused input changed a retained output")
endif()
configure_case(tool-mutation TRUE)
build_case(TRUE)
file(APPEND "${BUILD}/hosttools/sfdc" "# changed tool\n")
execute_process(COMMAND /usr/bin/touch -t 200001010000 "${BUILD}/hosttools/sfdc"
    RESULT_VARIABLE _touch_result)
if(NOT _touch_result EQUAL 0)
    message(FATAL_ERROR "SFD old-mtime counterprobe could not set timestamp")
endif()
build_case(FALSE)
configure_case(class-membership TRUE)
build_case(TRUE)
file(SHA256 "${BUILD}/hosttools/sfdc" _original_tool)
file(WRITE "${BUILD}/source/tools/sfdc/Added.pl" "# added class\n")
build_case(TRUE)
file(SHA256 "${BUILD}/hosttools/sfdc" _updated_tool)
if(_original_tool STREQUAL _updated_tool)
    message(FATAL_ERROR "SFD changed class inventory did not rebuild its tool")
endif()
configure_case(no-output TRUE)
build_case(TRUE)
set(_output "${BUILD}/SDK/include/clib/example.h")
file(SHA256 "${_output}" _before)
file(WRITE "${_output}.aros-sfd-pending" "unowned stale bytes\n")
file(WRITE "${BUILD}/source/unit/example.sfd.no-output" "")
file(RENAME "${_output}" "${BUILD}/retained-header")
build_case(FALSE)
file(READ "${_output}.aros-sfd-pending" _unowned)
if(EXISTS "${_output}" OR NOT _unowned STREQUAL "unowned stale bytes\n")
    message(FATAL_ERROR "SFD absent fresh output published or clobbered an unowned file")
endif()
file(SHA256 "${BUILD}/retained-header" _retained)
if(NOT _retained STREQUAL _before)
    message(FATAL_ERROR "SFD absent fresh output changed a retained header")
endif()
foreach(_case bad-mode traversal extra-field input-symlink recipe-drift output-symlink duplicate-output)
    configure_case("${_case}" FALSE)
endforeach()
message(STATUS "SFD source binding, no-op, repair and refusals passed: ${_root}")
