cmake_minimum_required(VERSION 3.22)
# Apple's host ar otherwise timestamps its index differently across two
# independent invocations. This test-only normalization applies to both;
# the separate admitted GNU fixture verifies native AR/RANLIB bytes directly.
set(ENV{ZERO_AR_DATE} 1)
set(fixture "${CMAKE_CURRENT_LIST_DIR}/source-archives")
cmake_path(GET CMAKE_CURRENT_LIST_DIR PARENT_PATH engine)
if(DEFINED ENV{TMPDIR} AND NOT "$ENV{TMPDIR}" STREQUAL "")
    set(base "$ENV{TMPDIR}")
else()
    set(base /tmp)
endif()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef suffix)
set(root "${base}/aros-source-archives-${suffix} with spaces")
if(EXISTS "${root}" OR IS_SYMLINK "${root}")
    message(FATAL_ERROR "source archive test root already exists")
endif()
file(MAKE_DIRECTORY "${root}")
function(configure build probe)
    set(tool_arguments)
    if(DEFINED ARCHIVE_TEST_AR AND DEFINED ARCHIVE_TEST_RANLIB)
        list(APPEND tool_arguments "-DFIXTURE_AR=${ARCHIVE_TEST_AR}"
            "-DFIXTURE_RANLIB=${ARCHIVE_TEST_RANLIB}")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${fixture}" -B "${build}" -G Ninja
        "-DENGINE_DIR=${engine}" "-DPROBE=${probe}" ${tool_arguments}
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 90)
    set(result "${result}" PARENT_SCOPE)
    set(log "${stdout}\n${stderr}" PARENT_SCOPE)
endfunction()
function(build_archive build)
    execute_process(COMMAND "${CMAKE_COMMAND}" --build "${build}" --target source-archive
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 90)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "source archive build failed: ${stdout}\n${stderr}")
    endif()
endfunction()
set(build "${root}/build")
configure("${build}" "")
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "source archive configure failed: ${log}")
endif()
build_archive("${build}")
include("${build}/selected-tools.cmake")
set(archive "${build}/SYS/Developer/lib/libsource.a")
execute_process(COMMAND "${AR}" t "${archive}" RESULT_VARIABLE result OUTPUT_VARIABLE members)
string(REPLACE "__.SYMDEF SORTED\n" "" members "${members}")
if(NOT result STREQUAL "0" OR NOT members STREQUAL "two.o\none.o\n")
    message(FATAL_ERROR "source archive lost source member order: ${members}")
endif()
set(reference "${root}/reference.a")
execute_process(COMMAND "${AR}" cr "${reference}" "${build}/gen/objects/two.o"
    "${build}/gen/objects/one.o" RESULT_VARIABLE result)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "reference AR failed")
endif()
execute_process(COMMAND "${RANLIB}" "${reference}" RESULT_VARIABLE result)
execute_process(COMMAND "${CMAKE_COMMAND}" -E compare_files "${archive}" "${reference}"
    RESULT_VARIABLE comparison)
if(NOT result STREQUAL "0" OR NOT comparison STREQUAL "0")
    message(FATAL_ERROR "source archive differs from independent AR/RANLIB invocation")
endif()
file(SHA256 "${archive}" first_digest)
build_archive("${build}")
file(SHA256 "${archive}" second_digest)
if(NOT first_digest STREQUAL second_digest)
    message(FATAL_ERROR "unchanged archive invocation changed bytes")
endif()
configure("${build}" remove-member)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "reconfigure failed: ${log}")
endif()
build_archive("${build}")
execute_process(COMMAND "${AR}" t "${archive}" RESULT_VARIABLE result OUTPUT_VARIABLE members)
string(REPLACE "__.SYMDEF SORTED\n" "" members "${members}")
if(NOT result STREQUAL "0" OR NOT members STREQUAL "one.o\n")
    message(FATAL_ERROR "removed member survived fresh archive publication: ${members}")
endif()
foreach(probe unregistered duplicate flags escape collision file-collision no-contract interface-collision)
    configure("${root}/${probe}" "${probe}")
    if(result STREQUAL "0" OR NOT log MATCHES "Source archive:")
        message(FATAL_ERROR "archive refusal probe ${probe} failed: ${log}")
    endif()
endforeach()
configure("${root}/linked" link-consumer)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "archive consumer configure failed: ${log}")
endif()
# This cold invocation names only the executable. Its imported archive must
# schedule every compile and archive producer without a prior utility build.
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${root}/linked" --target consumer
    RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 90)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "archive consumer cold link failed: ${stdout}\n${stderr}")
endif()
execute_process(COMMAND "${root}/linked/consumer" RESULT_VARIABLE result TIMEOUT 10)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "archive consumer result differs from its exact object producers")
endif()
# A future-dated symlink must not bypass the check target on a no-op build.
file(RENAME "${build}/gen/objects/one.o" "${build}/gen/objects/one.saved.o")
file(CREATE_LINK "${build}/gen/objects/one.saved.o" "${build}/gen/objects/one.o" SYMBOLIC)
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${build}" --target source-archive-check
    RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 90)
if(result STREQUAL "0" OR NOT "${stdout}\n${stderr}" MATCHES "symlink")
    message(FATAL_ERROR "archive member symlink was not refused: ${stdout}\n${stderr}")
endif()
file(REMOVE "${build}/gen/objects/one.o")
file(RENAME "${build}/gen/objects/one.saved.o" "${build}/gen/objects/one.o")
file(GLOB command_files "${build}/CMakeFiles/aros-source-archive-*.cmake")
list(GET command_files 0 command_file)
file(APPEND "${command_file}" "# changed after configure\n")
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${build}" --target source-archive
    RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 90)
if(result STREQUAL "0" OR NOT "${stdout}\n${stderr}" MATCHES "changed command file refused")
    message(FATAL_ERROR "changed archive command was not refused: ${stdout}\n${stderr}")
endif()
message(STATUS "Source archive differential, order, incremental and refusal probes passed")
