//! SDK header staging from `%copy_includes` declarations.
//!
//! Modules publish their public headers through `%copy_includes` (see
//! `config/make.tmpl`). The macro copies files into two include roots: the
//! target SDK (`$(AROS_INCLUDES)`, here `SDK/include`) and the host tool
//! include tree (`$(GENINCDIR)`). Without this step, headers referenced with a
//! category prefix such as `<oop/oop.h>` or `<hidd/hidd.h>` are unreachable,
//! because the prefix is part of the `#include` and no search path can supply
//! it.
//!
//! Destination semantics follow the macro exactly:
//!
//! * With `dir=<d>`, the source directory is `<mmakefile dir>/<d>` and only the
//!   base name is kept (`$(notdir ...)`), so `rom/hidds/kbd/include/keyboard.h`
//!   becomes `<root>/hidd/keyboard.h` for `path=hidd`.
//! * Without `dir=`, the source directory is the mmakefile's own directory and
//!   the listed relative path is appended verbatim.
//!
//! No declaration in the tree overrides `compiler=` or `includedir=`, so the
//! defaults (`target`, i.e. both roots) are the only case implemented. File
//! lists come from `$(call WILDCARD, <globs>)` in the majority of cases; the
//! globs are passed through to CMake rather than expanded here, so that adding
//! a header does not require anything to be regenerated by hand.

use crate::includes::{arg_value, arg_value_quoted};
use crate::make_vars::VarScope;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::Path;

type ExternalVarLookup<'a> = Option<&'a dyn Fn(&str) -> Option<String>>;

/// A hand-written Make rule that produces a header.
///
/// These cannot be transpiled generically, because the recipe is arbitrary
/// Make (the ones in the tree rename files, run generator tools, or use pattern
/// rules). They are reported so that a rule appearing upstream is noticed here
/// rather than as a missing header somewhere else entirely.
///
/// Two kinds of destination count. A header under `$(AROS_INCLUDES)` or
/// `$(GENINCDIR)` is staged into the SDK and visible tree-wide; one under
/// `$(GENDIR)` is private to its own module. Both fail the same way when
/// missing, so both are collected, and `root` says which kind it is.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdhocHeaderRule {
    /// mmakefile that declares the rule, relative to the source root.
    pub file: String,
    /// 1-based line number of the rule.
    pub line: usize,
    /// The include root the target sits in, verbatim, e.g. `$(GENINCDIR)/`.
    pub root: String,
    /// The rule's target, with the include root stripped.
    pub dest: String,
    /// The rule's prerequisites, verbatim.
    pub prereqs: String,
}

/// A hand-written SDK-header rule whose recipe is a safe, literal copy or
/// one-line substitution.
///
/// This is intentionally narrower than arbitrary Make recipes. The parser
/// accepts exact `$<` to `$@` copies and
/// `$(SED) -e 's/^literal/literal/' $< > $@`, records the exact input/output,
/// and lets CMake own the real build-time operation. Dependencies and consumers
/// are joined later from the complete target/fetch graph.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HeaderTransformDecl {
    /// Make target which owns the generated header.
    pub name: String,
    /// Declaring mmakefile, relative to the source root.
    pub file: String,
    /// 1-based line number of the output rule.
    pub line: usize,
    /// Concrete CMake input path.
    pub input: String,
    /// Concrete CMake output path below the build tree.
    pub output: String,
    /// Exact line prefix stripped from the anchored sed expression.
    pub match_text: String,
    /// Literal replacement text.
    pub replacement: String,
    /// The recipe is an exact `$<` to `$@` copy rather than a substitution.
    #[serde(default)]
    pub copy_only: bool,
    /// Alternating literal token/replacement values for a safe template pipe.
    #[serde(default)]
    pub substitutions: Vec<String>,
    /// Direct fetch targets owning the input, filled by the graph.
    #[serde(default)]
    pub dependencies: Vec<String>,
    /// Concrete compile targets whose port source tree contains the input.
    #[serde(default)]
    pub consumers: Vec<String>,
}

/// A deterministic host-Bison rule whose generated C file is included by one
/// concrete compile target.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BisonOutputDecl {
    pub owner: String,
    pub file: String,
    pub line: usize,
    pub input: String,
    pub output: String,
}

/// What one mmakefile yielded for header staging.
#[derive(Debug, Default)]
pub struct CopyIncludesScan {
    /// Resolved `%copy_includes` declarations.
    pub decls: Vec<CopyIncludesDecl>,
    /// `%copy_includes` directives that could not be resolved.
    pub skipped: Vec<String>,
    /// Hand-written rules producing a header.
    pub adhoc: Vec<AdhocHeaderRule>,
    /// Safe literal transforms promoted from hand-written header recipes.
    pub transforms: Vec<HeaderTransformDecl>,
    /// Exact `$(BISON) -o $@ $<` generated-source rules.
    pub bison_outputs: Vec<BisonOutputDecl>,
    /// Hand-written rules under `$(GENDIR)` producing something other than a
    /// header (objects, ELF images, linker scripts). Reported only, since a
    /// missing one of these surfaces as a link or packaging failure rather
    /// than a missing include.
    pub generated_files: Vec<String>,
    /// Rules whose recipe runs an in-tree Python script to produce a file under
    /// `$(GENDIR)`.
    pub script_outputs: Vec<ScriptOutputDecl>,
    /// Rules that look like one and are not representable.
    pub skipped_script_outputs: Vec<String>,
}

/// A rule whose recipe runs an in-tree Python script to produce files under
/// `$(GENDIR)`.
///
/// `arch/all-pc/udis86/mmakefile.src:26` is the case that matters, and the only
/// one of the 21 rules in the generated-file report with this shape: the other
/// twenty are windres compiles for mingw32, the m68k-amiga ROM link chain, two
/// plain compiles into `$(GENDIR)`, the stdc Unicode tables and two copies. One
/// modelled form would not have covered them, so this one is deliberately
/// narrow and everything else stays reported.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ScriptOutputDecl {
    /// Directory of the declaring mmakefile, relative to the source root.
    pub directory: String,
    /// The file the rule declares, as a CMake path.
    pub output: String,
    /// Further files declared by the same exact multi-target rule.
    #[serde(default)]
    pub additional_outputs: Vec<String>,
    /// The script the recipe runs, as a CMake path.
    pub script: String,
    /// Literal arguments after the script, as CMake paths or plain words.
    pub arguments: Vec<String>,
    /// Run the script with its standard output captured as `output` instead of
    /// expecting the output path as one of the script arguments.
    #[serde(default)]
    pub stdout: bool,
    /// Optional working directory from an exact `cd <dir> && $(PYTHON) ...`
    /// recipe prefix.
    #[serde(default)]
    pub working_directory: Option<String>,
    /// The rule's prerequisites, as CMake paths. Order-only ones are dropped:
    /// they are directories, which CMake creates itself.
    pub depends: Vec<String>,
    /// Source stems whose Make object rules depend on this output. This covers
    /// generated headers which are included by a source but are not themselves
    /// listed in a build macro's source inventory.
    #[serde(default)]
    pub consumer_source_stems: Vec<String>,
    /// Exact simple Make targets whose prerequisite list names this output.
    #[serde(default)]
    pub consumer_targets: Vec<String>,
}

/// One resolved `%copy_includes` declaration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CopyIncludesDecl {
    /// `mmake=`: the staging target which owns these copies.
    #[serde(default = "default_copy_target")]
    pub name: String,
    /// Subdirectory under each include root (`path=`).
    pub dest: String,
    /// Source directory relative to the source root.
    pub source_dir: String,
    /// Glob patterns or explicit file names, relative to `source_dir`.
    pub patterns: Vec<String>,
    /// File names selected by the source list but deliberately not staged.
    ///
    /// MetaMake commonly expresses this as `$(filter-out name.h,$(call
    /// WILDCARD,...))`.  Retaining it separately is important for generated
    /// headers: FreeType, for example, replaces `ftoption.h` with its target
    /// configuration instead of copying the upstream default.
    #[serde(default)]
    pub excludes: Vec<String>,
    /// Whether to strip directories from the copied names (`dir=` was given).
    pub flatten: bool,
}

fn default_copy_target() -> String {
    "includes-copy".to_owned()
}

fn split_assignment(line: &str) -> Option<(&str, &str, bool)> {
    if let Some((l, r)) = line.split_once(":=") {
        return Some((l, r, false));
    }
    if let Some((l, r)) = line.split_once("+=") {
        return Some((l, r, true));
    }
    let (l, r) = line.split_once('=')?;
    if l.contains(':') || l.is_empty() {
        return None;
    }
    Some((l, r, false))
}

fn collect_local_assignments(lines: &[&str], vars: &mut HashMap<String, String>) {
    let mut pending: Option<String> = None;
    for line in lines {
        let trimmed = line.trim();
        let continues = trimmed.ends_with('\\');
        let payload = trimmed.trim_end_matches('\\').trim();
        if let Some(name) = pending.take() {
            let entry = vars.entry(name.clone()).or_default();
            if !entry.is_empty() {
                entry.push(' ');
            }
            entry.push_str(payload);
            if continues {
                pending = Some(name);
            }
            continue;
        }
        if line.starts_with('\t') || trimmed.starts_with('#') || trimmed.starts_with('%') {
            continue;
        }
        let Some((lhs, rhs, append)) = split_assignment(payload) else {
            continue;
        };
        let name = lhs.trim().to_owned();
        if name.is_empty() || name.contains(char::is_whitespace) {
            continue;
        }
        let entry = vars.entry(name.clone()).or_default();
        if append && !entry.is_empty() && !rhs.trim().is_empty() {
            entry.push(' ');
        } else if !append {
            entry.clear();
        }
        entry.push_str(rhs.trim());
        if continues {
            pending = Some(name);
        }
    }
}

/// Make variables that map onto a CMake location.
///
/// `%fetch` unpacks third-party sources under the ports directory, and a module
/// then stages their headers from there: `arch/all-native/acpica` publishes
/// `$(ACPICA_INCLUDES)/*.h` as `acpica/*.h`. Without this mapping the
/// declaration cannot be resolved and `<acpica/actypes.h>` never reaches the
/// SDK, which is what the ACPI-dependent drivers fail on.
fn map_var(name: &str) -> Option<&'static str> {
    match name {
        "SRCDIR" => Some("${CMAKE_SOURCE_DIR}"),
        "TOP" => Some("${AROS_BUILD_DIR}"),
        "PORTSDIR" => Some("${AROS_PORTS_DIR}"),
        "PORTSSOURCEDIR" => Some("${AROS_PORTS_SOURCE_DIR}"),
        // Same mapping as includes.rs: the generated per-module tree lives
        // under <build>/gen, not at the build root.
        "GENDIR" => Some("${CMAKE_BINARY_DIR}/gen"),
        "GENINCDIR" => Some("${CMAKE_BINARY_DIR}/GENINCDIR"),
        _ => None,
    }
}

/// Substitutes `$(VAR)` references from `vars`, leaving unknown ones in place.
fn substitute(
    raw: &str,
    vars: &HashMap<String, String>,
    external: ExternalVarLookup<'_>,
    depth: usize,
) -> String {
    if depth == 0 || !raw.contains("$(") {
        return raw.to_owned();
    }
    let mut out = String::with_capacity(raw.len());
    let mut rest = raw;
    while let Some(start) = rest.find("$(") {
        out.push_str(&rest[..start]);
        let Some(end) = matching_paren(rest, start + 1) else {
            out.push_str(&rest[start..]);
            return out;
        };
        let name = &rest[start + 2..end];
        // `$(call WILDCARD, ...)` is handled later, keep it verbatim.
        if name.starts_with("call ") || name.contains(' ') {
            out.push_str(&rest[start..=end]);
        } else if let Some(m) = map_var(name) {
            out.push_str(m);
        } else if let Some(v) = vars
            .get(name)
            .cloned()
            .or_else(|| external.and_then(|f| f(name)))
        {
            out.push_str(&substitute(&v, vars, external, depth - 1));
        } else {
            out.push_str(&rest[start..=end]);
        }
        rest = &rest[end + 1..];
    }
    out.push_str(rest);
    out
}

/// Finds the `)` matching the `$(` that starts at `open`, counting nesting.
fn matching_paren(text: &str, open: usize) -> Option<usize> {
    let bytes = text.as_bytes();
    let mut depth = 0usize;
    let mut i = open;
    while i < bytes.len() {
        if bytes[i] == b'(' {
            depth += 1;
        } else if bytes[i] == b')' {
            depth -= 1;
            if depth == 0 {
                return Some(i);
            }
        }
        i += 1;
    }
    None
}

/// Expands a bracket character class, e.g. `*.[hi]` into `*.h` and `*.i`.
///
/// CMake's `file(GLOB)` does not understand character classes, so they are
/// turned into separate patterns here.
fn expand_char_classes(pattern: &str) -> Vec<String> {
    let Some(open) = pattern.find('[') else {
        return vec![pattern.to_owned()];
    };
    let Some(close) = pattern[open..].find(']').map(|i| i + open) else {
        return vec![pattern.to_owned()];
    };
    let prefix = &pattern[..open];
    let suffix = &pattern[close + 1..];
    let mut out = Vec::new();
    for ch in pattern[open + 1..close].chars() {
        for tail in expand_char_classes(suffix) {
            out.push(format!("{prefix}{ch}{tail}"));
        }
    }
    if out.is_empty() {
        vec![pattern.to_owned()]
    } else {
        out
    }
}

/// Extracts the file list from an `includes=` value.
///
/// Returns `None` when the list still references a Make variable we cannot
/// resolve, which is the case for the third-party ports whose sources live
/// outside the tree.
#[derive(Debug, Default)]
struct ResolvedFileList {
    patterns: Vec<String>,
    excludes: Vec<String>,
}

fn outer_make_function<'a>(expression: &'a str, name: &str) -> Option<&'a str> {
    let prefix = format!("$({name}");
    let remainder = expression.strip_prefix(&prefix)?;
    if !remainder.chars().next().is_some_and(char::is_whitespace) {
        return None;
    }
    let end = matching_paren(expression, 1)?;
    if end + 1 != expression.len() {
        return None;
    }
    Some(expression[prefix.len()..end].trim())
}

fn split_top_level_comma(expression: &str) -> Option<(&str, &str)> {
    let mut depth = 0usize;
    for (index, ch) in expression.char_indices() {
        match ch {
            '(' => depth += 1,
            ')' => depth = depth.checked_sub(1)?,
            ',' if depth == 0 => return Some((&expression[..index], &expression[index + 1..])),
            _ => {}
        }
    }
    None
}

fn split_top_level_arguments(expression: &str) -> Option<Vec<&str>> {
    let mut depth = 0usize;
    let mut start = 0usize;
    let mut out = Vec::new();
    for (index, ch) in expression.char_indices() {
        match ch {
            '(' => depth += 1,
            ')' => depth = depth.checked_sub(1)?,
            ',' if depth == 0 => {
                out.push(expression[start..index].trim());
                start = index + 1;
            }
            _ => {}
        }
    }
    if depth != 0 {
        return None;
    }
    out.push(expression[start..].trim());
    Some(out)
}

/// Splits a Make word list without cutting whitespace inside `$(...)`.
fn split_make_words(expression: &str) -> Option<Vec<&str>> {
    let bytes = expression.as_bytes();
    let mut depth = 0usize;
    let mut start = None;
    let mut words = Vec::new();
    let mut cursor = 0usize;
    while cursor < bytes.len() {
        if bytes[cursor] == b'$' && bytes.get(cursor + 1) == Some(&b'(') {
            if start.is_none() {
                start = Some(cursor);
            }
            depth += 1;
            cursor += 2;
            continue;
        }
        if bytes[cursor] == b')' && depth > 0 {
            depth -= 1;
        } else if bytes[cursor].is_ascii_whitespace() && depth == 0 {
            if let Some(word_start) = start.take() {
                words.push(&expression[word_start..cursor]);
            }
            cursor += 1;
            continue;
        } else if start.is_none() {
            start = Some(cursor);
        }
        cursor += 1;
    }
    if depth != 0 {
        return None;
    }
    if let Some(word_start) = start {
        words.push(&expression[word_start..]);
    }
    Some(words)
}

fn apply_percent_substitution(word: &str, pattern: &str, replacement: &str) -> String {
    let Some((prefix, suffix)) = pattern.split_once('%') else {
        return if word == pattern {
            replacement.to_owned()
        } else {
            word.to_owned()
        };
    };
    let Some(stem) = word
        .strip_prefix(prefix)
        .and_then(|rest| rest.strip_suffix(suffix))
    else {
        return word.to_owned();
    };
    replacement.replace('%', stem)
}

fn resolve_file_list(
    raw: &str,
    vars: &HashMap<String, String>,
    external: ExternalVarLookup<'_>,
) -> Option<ResolvedFileList> {
    let substituted = substitute(raw, vars, external, 8);
    resolve_file_list_expression(substituted.trim(), vars, external)
}

fn resolve_file_list_expression(
    expression: &str,
    vars: &HashMap<String, String>,
    external: ExternalVarLookup<'_>,
) -> Option<ResolvedFileList> {
    for function in ["addprefix", "addsuffix"] {
        if let Some(arguments) = outer_make_function(expression, function) {
            let (affix, words) = split_top_level_comma(arguments)?;
            let affix = substitute(affix.trim(), vars, external, 8);
            if affix.contains("$(") || affix.contains(char::is_whitespace) {
                return None;
            }
            let mut resolved = resolve_file_list(words.trim(), vars, external)?;
            for list in [&mut resolved.patterns, &mut resolved.excludes] {
                for word in list {
                    *word = if function == "addprefix" {
                        format!("{affix}{word}")
                    } else {
                        format!("{word}{affix}")
                    };
                }
            }
            return Some(resolved);
        }
    }

    if let Some(arguments) = outer_make_function(expression, "filter") {
        let (raw_filters, raw_words) = split_top_level_comma(arguments)?;
        let filters = resolve_file_list(raw_filters.trim(), vars, external)?;
        let mut words = resolve_file_list(raw_words.trim(), vars, external)?;
        let matches = |word: &str| {
            filters.patterns.iter().any(|filter| {
                if let Some((prefix, suffix)) = filter.split_once('%') {
                    word.strip_prefix(prefix)
                        .and_then(|rest| rest.strip_suffix(suffix))
                        .is_some()
                } else {
                    word == filter
                }
            })
        };
        words.patterns.retain(|word| matches(word));
        words.excludes.retain(|word| matches(word));
        return Some(words);
    }

    if let Some(arguments) = outer_make_function(expression, "sort") {
        let mut resolved = resolve_file_list(arguments, vars, external)?;
        resolved.patterns.sort();
        resolved.patterns.dedup();
        resolved.excludes.sort();
        resolved.excludes.dedup();
        return Some(resolved);
    }

    // GNU Make's lowercase wildcard form is equivalent here to the AROS
    // WILDCARD wrapper: CMake receives the pattern and evaluates it against the
    // source directory. Keeping it declarative also works before a Port fetch.
    if let Some(arguments) = outer_make_function(expression, "wildcard") {
        let expanded = substitute(arguments, vars, external, 8);
        if expanded.contains("$(") {
            return None;
        }
        let mut resolved = ResolvedFileList::default();
        for pattern in expanded.split_whitespace() {
            resolved.patterns.extend(expand_char_classes(pattern));
        }
        return (!resolved.patterns.is_empty()).then_some(resolved);
    }

    if let Some(arguments) = outer_make_function(expression, "patsubst") {
        let arguments = split_top_level_arguments(arguments)?;
        if arguments.len() != 3 {
            return None;
        }
        let pattern = substitute(arguments[0], vars, external, 8);
        let replacement = substitute(arguments[1], vars, external, 8);
        if pattern.contains("$(") || replacement.contains("$(") {
            return None;
        }
        let mut resolved = resolve_file_list(arguments[2], vars, external)?;
        for list in [&mut resolved.patterns, &mut resolved.excludes] {
            for word in list.iter_mut() {
                *word = apply_percent_substitution(word, &pattern, &replacement);
            }
        }
        return Some(resolved);
    }

    if let Some(arguments) = outer_make_function(expression, "notdir") {
        let mut resolved = resolve_file_list(arguments, vars, external)?;
        for list in [&mut resolved.patterns, &mut resolved.excludes] {
            for entry in list.iter_mut() {
                *entry = entry.rsplit('/').next().unwrap_or(entry).to_owned();
            }
        }
        return Some(resolved);
    }

    if let Some(arguments) = outer_make_function(expression, "filter-out") {
        let (filters, words) = split_top_level_comma(arguments)?;
        let filters = resolve_file_list(filters.trim(), vars, external)?;
        // Pattern filters would need to be evaluated against the fetched
        // directory at build time.  Keep this deliberately bounded to the
        // literal exclusion form that the header publisher uses; anything
        // broader remains an explicit skipped declaration rather than a guess.
        if filters
            .patterns
            .iter()
            .chain(filters.excludes.iter())
            .any(|entry| entry.contains(['*', '?', '[', '%']))
        {
            return None;
        }
        let mut resolved = resolve_file_list(words.trim(), vars, external)?;
        resolved.excludes.extend(filters.patterns);
        resolved.excludes.extend(filters.excludes);
        resolved.excludes.sort();
        resolved.excludes.dedup();
        return Some(resolved);
    }

    let mut resolved = ResolvedFileList::default();
    let mut rest = expression;

    // Pull out every `$(call WILDCARD, <globs>)` group. The closing paren must
    // be matched with nesting in mind: `$(call WILDCARD, $(X)/*.h)` would
    // otherwise be cut short at the inner `)`.
    while let Some(start) = rest.find("$(call") {
        let head = &rest[..start];
        push_plain_tokens(head, &mut resolved.patterns)?;
        // `matching_paren` expects to start on the `(`.
        let end = matching_paren(rest, start + 1)?;
        let inner = &rest[start..end];
        let globs = inner.split_once(',').map_or("", |(_, g)| g);
        for g in globs.split_whitespace() {
            // The glob may itself be rooted in a variable, as in
            // `$(call WILDCARD, $(ACPICA_INCLUDES)/*.h)`. Substitute first; the
            // directory part is dropped later by the `dir=` flattening, so only
            // the trailing pattern matters.
            let g = substitute(g, vars, external, 8);
            // A Make construct that survived substitution means we cannot know
            // what this matches; skip the declaration rather than guess.
            if g.contains("$(") {
                return None;
            }
            resolved.patterns.extend(expand_char_classes(&g));
        }
        rest = &rest[end + 1..];
    }
    push_plain_tokens(rest, &mut resolved.patterns)?;

    if resolved.patterns.is_empty() {
        return None;
    }
    Some(resolved)
}

/// Adds literal file names, rejecting anything still holding a Make variable.
fn push_plain_tokens(text: &str, out: &mut Vec<String>) -> Option<()> {
    for tok in text.split_whitespace() {
        if tok.contains("$(") {
            return None;
        }
        out.extend(expand_char_classes(tok));
    }
    Some(())
}

/// Parses the header-staging directives of one `mmakefile.src`.
///
/// Returns the resolved `%copy_includes` declarations, the ones that had to be
/// skipped, and every hand-written rule that writes into an include root.
///
/// Evaluation is sequential rather than "collect all variables, then all
/// directives": several mmakefiles reassign `INCLUDE_FILES` between two
/// `%copy_includes` calls (for example `arch/all-native/acpica`), and Make
/// resolves each directive against the value in force at that point.
#[must_use]
pub fn collect_copy_includes(content: &str, rel_dir: &Path) -> CopyIncludesScan {
    collect_copy_includes_with_lookup(content, rel_dir, None)
}

/// Parses `%copy_includes` using an additional target-selected Make scope.
///
/// The declaration remains sequential: assignments in the mmakefile override
/// this fallback at the point where they occur.  The fallback supplies values
/// from source-tree configuration files included by the mmakefile, which is
/// how ports such as Mesa define their archive and source directories.
#[must_use]
pub(crate) fn collect_copy_includes_with_scope(
    content: &str,
    rel_dir: &Path,
    scope: &VarScope,
) -> CopyIncludesScan {
    let external = |name: &str| scope.raw_at(name, usize::MAX);
    collect_copy_includes_with_lookup(content, rel_dir, Some(&external))
}

fn collect_copy_includes_with_lookup(
    content: &str,
    rel_dir: &Path,
    external: ExternalVarLookup<'_>,
) -> CopyIncludesScan {
    let base = rel_dir.to_string_lossy().replace('\\', "/");
    let mmakefile = if base.is_empty() {
        "mmakefile.src".to_owned()
    } else {
        format!("{base}/mmakefile.src")
    };

    let mut vars: HashMap<String, String> = HashMap::new();
    // $(CURDIR) is the declaring mmakefile's directory. Two staging rules read
    // their sources through it, reqtools' amigaincludesforgcc tree and udis86's
    // generated itab.h, and without it the path kept the literal "$(CURDIR)"
    // and matched nothing.
    if !base.is_empty() {
        vars.insert("CURDIR".to_owned(), base.clone());
    }
    // config/make.cfg.in defines the per-mmakefile object directory this way.
    // The collector intentionally does not inline the generated global config,
    // so seed its public default here; an ordinary assignment in the source
    // file still replaces it sequentially below.
    vars.insert("OBJDIR".to_owned(), "$(GENDIR)/$(CURDIR)".to_owned());
    let mut decls = Vec::new();
    let mut skipped = Vec::new();
    let mut adhoc = Vec::new();
    let mut transforms = Vec::new();
    let mut bison_outputs = Vec::new();
    let mut generated_files = Vec::new();
    let mut script_outputs: Vec<ScriptOutputDecl> = Vec::new();
    let mut skipped_script_outputs: Vec<String> = Vec::new();

    let lines: Vec<&str> = content.lines().collect();
    let mut owner_vars = vars.clone();
    collect_local_assignments(&lines, &mut owner_vars);
    let output_owners = collect_header_output_owners(&lines, &owner_vars, external);
    let mut i = 0usize;
    // Tracks a variable assignment continued over several lines.
    let mut pending_var: Option<String> = None;

    while i < lines.len() {
        let line = lines[i];
        let line_no = i + 1;
        let trimmed = line.trim();
        let continues = trimmed.ends_with('\\');
        let payload = trimmed.trim_end_matches('\\').trim();

        if let Some(name) = pending_var.take() {
            let entry = vars.entry(name.clone()).or_default();
            if !entry.is_empty() {
                entry.push(' ');
            }
            entry.push_str(payload);
            if continues {
                pending_var = Some(name);
            }
            i += 1;
            continue;
        }

        if trimmed.starts_with('#') {
            i += 1;
            continue;
        }

        if trimmed.starts_with("%copy_includes") {
            // Join continuation lines into one directive body.
            let mut body = payload.to_owned();
            let mut j = i;
            let mut cont = continues;
            while cont {
                j += 1;
                let Some(next) = lines.get(j) else { break };
                let t = next.trim();
                cont = t.ends_with('\\');
                body.push(' ');
                body.push_str(t.trim_end_matches('\\').trim());
            }
            resolve_directive(&body, &base, &vars, external, &mut decls, &mut skipped);
            i = j + 1;
            continue;
        }

        if trimmed.starts_with('%') {
            i += 1;
            continue;
        }

        if let Some(decl) = parse_bison_output(&lines, i, &mmakefile, &base, &vars, external) {
            bison_outputs.push(decl);
            i += 1;
            continue;
        }

        // A Python pattern rule is a template, not an output. Its concrete
        // instances are selected by source inventory (and may belong to a
        // version-specific capability); never report or emit the literal `%`.
        if is_python_pattern_rule(&lines, i) {
            i += 1;
            while i < lines.len() && lines[i - 1].trim_end().ends_with('\\') {
                i += 1;
            }
            continue;
        }

        // A rule whose recipe runs an in-tree Python script. Tried before the
        // generic shape so a modelled rule is not also reported as unmodelled.
        match parse_script_output(&lines, i, &base, &vars, external) {
            Some(Ok(mut decl)) => {
                if let Some(owner) = output_owners.get(&decl.output) {
                    decl.consumer_targets.push(owner.clone());
                }
                script_outputs.push(decl);
                i += 1;
                while i < lines.len() && lines[i - 1].trim_end().ends_with('\\') {
                    i += 1;
                }
                continue;
            }
            Some(Err(reason)) => {
                skipped_script_outputs.push(reason);
                i += 1;
                while i < lines.len() && lines[i - 1].trim_end().ends_with('\\') {
                    i += 1;
                }
                continue;
            }
            None => {}
        }

        // A hand-written rule writing into an include root, e.g.
        //   $(AROS_INCLUDES)/hidd/pci.h: include/pci_hidd.h
        let rendered_rule = substitute(payload, &vars, external, 8);
        let parsed_rule = parse_adhoc_rule(payload, &mmakefile, line_no).or_else(|| {
            (rendered_rule != payload)
                .then(|| parse_adhoc_rule(&rendered_rule, &mmakefile, line_no))
                .flatten()
        });
        match parsed_rule {
            Some(ParsedRule::Header(rule)) => {
                if let Some(transform) =
                    parse_header_transform(&rule, &lines, i, &base, &vars, external, &output_owners)
                {
                    transforms.push(transform);
                } else {
                    adhoc.push(rule);
                }
                i += 1;
                continue;
            }
            Some(ParsedRule::Other(note)) => {
                generated_files.push(note);
                i += 1;
                continue;
            }
            None => {}
        }

        if let Some((lhs, rhs, append)) = split_assignment(payload) {
            let name = lhs.trim().to_owned();
            if !name.is_empty() && !name.contains(char::is_whitespace) {
                let entry = vars.entry(name.clone()).or_default();
                if append {
                    if !entry.is_empty() {
                        entry.push(' ');
                    }
                } else {
                    entry.clear();
                }
                entry.push_str(rhs.trim());
                if continues {
                    pending_var = Some(name);
                }
            }
        }

        i += 1;
    }

    CopyIncludesScan {
        decls,
        skipped,
        adhoc,
        transforms,
        bison_outputs,
        generated_files,
        script_outputs,
        skipped_script_outputs,
    }
}

fn is_python_pattern_rule(lines: &[&str], index: usize) -> bool {
    let mut rule = String::new();
    let mut cursor = index;
    loop {
        let Some(line) = lines.get(cursor) else {
            return false;
        };
        let trimmed = line.trim_end();
        rule.push_str(trimmed.trim_end_matches('\\').trim_end());
        cursor += 1;
        if !trimmed.ends_with('\\') {
            break;
        }
        rule.push(' ');
    }
    let Some((target, _)) = rule.split_once(':') else {
        return false;
    };
    target.contains('%')
        && lines[cursor..]
            .iter()
            .take_while(|line| line.starts_with('\t'))
            .any(|line| line.contains("$(PYTHON)"))
}

/// Maps a concrete generated-output token to the simple Make target which
/// owns it, for example `workbench-libs-z-geninc : $(AROS_INCLUDES)/zconf.h`.
fn collect_header_output_owners(
    lines: &[&str],
    vars: &HashMap<String, String>,
    external: ExternalVarLookup<'_>,
) -> HashMap<String, String> {
    let mut owners = HashMap::new();
    for raw in lines {
        if raw.starts_with('\t') {
            continue;
        }
        let literal = raw.trim();
        let rendered = substitute(literal, vars, external, 8);
        for line in [literal, rendered.as_str()] {
            if line.is_empty() || line.starts_with('#') || line.contains('=') {
                continue;
            }
            let Some((target, prereqs)) = line.split_once(':') else {
                continue;
            };
            let target = target.trim();
            if target.is_empty()
                || target.contains(char::is_whitespace)
                || target.contains(['$', '/', '%'])
            {
                continue;
            }
            let outputs = resolve_file_list(prereqs, vars, external).map_or_else(
                || prereqs.split_whitespace().map(str::to_owned).collect(),
                |resolved| resolved.patterns,
            );
            if outputs.is_empty()
                || !outputs.iter().all(|output| {
                    [
                        "$(AROS_INCLUDES)/",
                        "$(GENINCDIR)/",
                        "$(GENDIR)/",
                        "${AROS_SDK_INCLUDE_DIR}/",
                        "${AROS_GENINC_DIR}/",
                        "${CMAKE_BINARY_DIR}/GENINCDIR/",
                        "${CMAKE_BINARY_DIR}/gen/",
                    ]
                    .iter()
                    .any(|root| output.starts_with(root))
                })
            {
                continue;
            }
            for output in outputs {
                owners.entry(output).or_insert_with(|| target.to_owned());
            }
        }
    }
    owners
}

fn resolve_transform_path(
    raw: &str,
    base: &str,
    vars: &HashMap<String, String>,
    external: ExternalVarLookup<'_>,
    output: bool,
) -> Option<String> {
    let mut rendered = substitute(raw, vars, external, 8);
    rendered = rendered
        .replace("$(AROS_INCLUDES)", "${AROS_SDK_INCLUDE_DIR}")
        .replace("$(GENINCDIR)", "${AROS_GENINC_DIR}")
        .replace("$(GENDIR)", "${CMAKE_BINARY_DIR}/gen")
        .replace("$(SRCDIR)", "${CMAKE_SOURCE_DIR}")
        .replace("$(PORTSDIR)", "${AROS_PORTS_DIR}");
    if rendered.contains("$(") || rendered.contains(';') || rendered.contains('\n') {
        return None;
    }
    if output {
        if !rendered.starts_with("${AROS_SDK_INCLUDE_DIR}/")
            && !rendered.starts_with("${AROS_GENINC_DIR}/")
            && !rendered.starts_with("${CMAKE_BINARY_DIR}/GENINCDIR/")
            && !rendered.starts_with("${CMAKE_BINARY_DIR}/gen/")
        {
            return None;
        }
    } else if !rendered.starts_with("${") && !rendered.starts_with('/') {
        rendered = if base.is_empty() {
            format!("${{CMAKE_SOURCE_DIR}}/{rendered}")
        } else {
            format!("${{CMAKE_SOURCE_DIR}}/{base}/{rendered}")
        };
    }
    Some(rendered)
}

/// Parses a non-regex sed field up to `delimiter`, unescaping only the
/// delimiter and a literal backslash. Other backslash escapes would change
/// sed semantics and therefore make the recipe ineligible.
fn parse_literal_sed_field(chars: &[char], at: &mut usize, delimiter: char) -> Option<String> {
    let mut value = String::new();
    while *at < chars.len() {
        let ch = chars[*at];
        *at += 1;
        if ch == delimiter {
            return Some(value);
        }
        if ch == '\\' {
            let escaped = *chars.get(*at)?;
            if escaped != delimiter && escaped != '\\' {
                return None;
            }
            value.push(escaped);
            *at += 1;
        } else {
            value.push(ch);
        }
    }
    None
}

fn safe_mkdir_guard(command: &str) -> bool {
    let Some(rest) = command.strip_prefix("@$(IF) $(TEST) ! -d ") else {
        return false;
    };
    let Some((checked, rest)) = rest.split_once(" ; then $(MKDIR) ") else {
        return false;
    };
    let Some((created, tail)) = rest.split_once(" ; else $(NOP) ; fi") else {
        return false;
    };
    !checked.is_empty()
        && checked == created
        && tail.is_empty()
        && checked.chars().all(|character| {
            character.is_ascii_alphanumeric()
                || matches!(
                    character,
                    '_' | '-' | '.' | '/' | '$' | '(' | ')' | '{' | '}'
                )
        })
}

fn safe_recipe_prelude(command: &str) -> bool {
    if let Some(message) = command
        .strip_prefix("@$(ECHO) \"")
        .and_then(|value| value.strip_suffix('"'))
    {
        return !message.is_empty()
            && !message
                .chars()
                .any(|character| matches!(character, '\n' | '\r' | '`' | '$' | '\\'));
    }
    if let Some(directory) = command.strip_prefix("%mkdir_q dir=") {
        return !directory.is_empty()
            && directory.chars().all(|character| {
                character.is_ascii_alphanumeric()
                    || matches!(
                        character,
                        '_' | '-' | '.' | '/' | '$' | '(' | ')' | '{' | '}'
                    )
            });
    }
    safe_mkdir_guard(command)
}

fn literal_copy(commands: &[String]) -> bool {
    let Some((copy, prelude)) = commands.split_last() else {
        return false;
    };
    // GNU Make's leading `@` controls recipe echoing only; it is not part of
    // the command.  Both spellings therefore have the same build semantics.
    copy.strip_prefix('@').unwrap_or(copy) == "$(CP) $< $@"
        && prelude.iter().all(|command| safe_recipe_prelude(command))
}

fn split_top_level_arguments_preserving_space(expression: &str) -> Option<Vec<&str>> {
    let mut depth = 0usize;
    let mut start = 0usize;
    let mut out = Vec::new();
    for (index, ch) in expression.char_indices() {
        match ch {
            '(' => depth += 1,
            ')' => depth = depth.checked_sub(1)?,
            ',' if depth == 0 => {
                out.push(&expression[start..index]);
                start = index + 1;
            }
            _ => {}
        }
    }
    (depth == 0).then(|| {
        out.push(&expression[start..]);
        out
    })
}

fn resolve_scalar_make_expression(
    raw: &str,
    vars: &HashMap<String, String>,
    external: ExternalVarLookup<'_>,
) -> Option<String> {
    let substituted = substitute(raw, vars, external, 8);
    let expression = substituted.trim();
    if let Some(arguments) = outer_make_function(expression, "subst") {
        let arguments = split_top_level_arguments_preserving_space(arguments)?;
        if arguments.len() != 3 {
            return None;
        }
        let from = resolve_scalar_make_expression(arguments[0].trim(), vars, external)?;
        let replacement = substitute(arguments[1], vars, external, 8);
        let text = resolve_scalar_make_expression(arguments[2].trim(), vars, external)?;
        if replacement.contains("$(") {
            return None;
        }
        return Some(text.replace(&from, &replacement));
    }
    if let Some(arguments) = outer_make_function(expression, "word") {
        let arguments = split_top_level_arguments(arguments)?;
        if arguments.len() != 2 {
            return None;
        }
        let index: usize = resolve_scalar_make_expression(arguments[0], vars, external)?
            .parse()
            .ok()?;
        if index == 0 {
            return None;
        }
        let words = resolve_scalar_make_expression(arguments[1], vars, external)?;
        return Some(
            words
                .split_whitespace()
                .nth(index - 1)
                .unwrap_or("")
                .to_owned(),
        );
    }
    (!expression.contains("$(")).then(|| expression.to_owned())
}

fn literal_template_substitutions(
    commands: &[String],
    vars: &HashMap<String, String>,
    external: ExternalVarLookup<'_>,
) -> Option<Vec<String>> {
    let (recipe, prelude) = commands.split_last()?;
    if !prelude.iter().all(|command| safe_recipe_prelude(command)) {
        return None;
    }
    let pipeline = recipe
        .strip_prefix("@cat $< | $(SED) ")?
        .strip_suffix(" > $@")?;
    let mut substitutions = Vec::new();
    for expression in pipeline.split(" | $(SED) ") {
        let chars: Vec<_> = expression.strip_prefix('s')?.chars().collect();
        let delimiter = *chars.first()?;
        if delimiter.is_ascii_alphanumeric() || delimiter.is_whitespace() || delimiter == '\\' {
            return None;
        }
        let mut at = 1usize;
        let token = parse_literal_sed_field(&chars, &mut at, delimiter)?;
        let replacement = parse_literal_sed_field(&chars, &mut at, delimiter)?;
        if at != chars.len()
            || token.is_empty()
            || token
                .chars()
                .any(|ch| matches!(ch, '.' | '*' | '[' | ']' | '^' | '$' | '\\'))
        {
            return None;
        }
        let replacement = resolve_scalar_make_expression(&replacement, vars, external)?;
        if replacement.contains([';', '\n', '\r']) {
            return None;
        }
        substitutions.push(token);
        substitutions.push(replacement);
    }
    (!substitutions.is_empty()).then_some(substitutions)
}

fn literal_sed_substitution(commands: &[String]) -> Option<(String, String)> {
    let recipe = match commands {
        [sed] => sed.as_str(),
        [guard, sed] if safe_mkdir_guard(guard) => sed.as_str(),
        _ => return None,
    };
    let body = recipe.strip_prefix("@$(SED) -e 's")?;
    if body.contains('\n') {
        return None;
    }
    let chars: Vec<char> = body.chars().collect();
    let delimiter = *chars.first()?;
    if delimiter.is_ascii_alphanumeric() || delimiter.is_whitespace() || delimiter == '\\' {
        return None;
    }
    let mut at = 1usize;
    let pattern = parse_literal_sed_field(&chars, &mut at, delimiter)?;
    let replacement = parse_literal_sed_field(&chars, &mut at, delimiter)?;
    // Only an anchored, literal basic-regex pattern and no sed flags.  BRE
    // parentheses are literal; all actual metacharacters are rejected.
    let match_text = pattern.strip_prefix('^')?;
    if match_text.is_empty()
        || match_text
            .chars()
            .any(|ch| matches!(ch, '.' | '*' | '[' | ']' | '$' | '\\'))
    {
        return None;
    }
    if replacement.contains(['&', '\\']) {
        // Both have special meaning in a sed replacement and therefore are
        // not equivalent to CMake's literal replacement operation.
        return None;
    }
    let tail: String = chars[at..].iter().collect();
    if tail != "' $< > $@" {
        return None;
    }
    Some((match_text.to_owned(), replacement))
}

fn parse_header_transform(
    rule: &AdhocHeaderRule,
    lines: &[&str],
    rule_index: usize,
    base: &str,
    vars: &HashMap<String, String>,
    external: ExternalVarLookup<'_>,
    output_owners: &HashMap<String, String>,
) -> Option<HeaderTransformDecl> {
    let raw_output = format!("{}/{}", rule.root.trim_end_matches('/'), rule.dest);
    let output = resolve_transform_path(&raw_output, base, vars, external, true)?;
    let owner = output_owners
        .get(&raw_output)
        .or_else(|| output_owners.get(&output))?
        .clone();
    let mut prereqs = rule.prereqs.split_whitespace();
    let raw_input = prereqs.next()?;
    if raw_input.contains(['%', '*', '?']) || prereqs.any(|prereq| prereq.contains(['%', '*', '?']))
    {
        return None;
    }

    let mut commands = Vec::new();
    let mut command = String::new();
    for line in lines.iter().skip(rule_index + 1) {
        if !line.starts_with('\t') {
            break;
        }
        let trimmed = line.trim();
        let continued = trimmed.ends_with('\\');
        if !command.is_empty() {
            command.push(' ');
        }
        command.push_str(trimmed.trim_end_matches('\\').trim());
        if !continued {
            commands.push(std::mem::take(&mut command));
        }
    }
    if !command.is_empty() {
        return None;
    }
    let (match_text, replacement, copy_only, substitutions) =
        if let Some((match_text, replacement)) = literal_sed_substitution(&commands) {
            (match_text, replacement, false, Vec::new())
        } else if literal_copy(&commands) {
            (String::new(), String::new(), true, Vec::new())
        } else if let Some(substitutions) =
            literal_template_substitutions(&commands, vars, external)
        {
            (String::new(), String::new(), false, substitutions)
        } else {
            return None;
        };
    let input = resolve_transform_path(raw_input, base, vars, external, false)?;

    Some(HeaderTransformDecl {
        name: owner,
        file: rule.file.clone(),
        line: rule.line,
        input,
        output,
        match_text,
        replacement,
        copy_only,
        substitutions,
        dependencies: Vec::new(),
        consumers: Vec::new(),
    })
}

/// A hand-written rule, classified by what it produces.
enum ParsedRule {
    /// Produces a header, so a missing one breaks a compile.
    Header(AdhocHeaderRule),
    /// Produces something else under `$(GENDIR)`; carries a ready-to-report
    /// description.
    Other(String),
}

/// Recognises a Make rule whose target lives in one of the generated roots.
///
/// `$(GENDIR)/` is included because module-private generated headers live
/// there, for example `$(GENDIR)/$(CURDIR)/dos/errorlist.h`. Leaving it out
/// meant such a rule was silently absent and only surfaced as an undeclared
/// identifier in the module that includes it.
fn parse_adhoc_rule(line: &str, mmakefile: &str, line_no: usize) -> Option<ParsedRule> {
    const ROOTS: [&str; 7] = [
        "$(AROS_INCLUDES)/",
        "$(GENINCDIR)/",
        "$(GENDIR)/",
        "${AROS_SDK_INCLUDE_DIR}/",
        "${AROS_GENINC_DIR}/",
        "${CMAKE_BINARY_DIR}/GENINCDIR/",
        "${CMAKE_BINARY_DIR}/gen/",
    ];

    // A rule, not a variable assignment.
    let (target, prereqs) = line.split_once(':')?;
    if target.contains('=') || prereqs.starts_with('=') {
        return None;
    }
    // GNU Make target-specific variable assignment, not a file-producing
    // rule: `output.h: PRIVATE_SCRIPT := $(PYTHON) generator.py`.
    if split_assignment(prereqs.trim()).is_some() {
        return None;
    }

    // Two shapes reach an include root. The plain one names it in the target:
    //
    //     $(AROS_INCLUDES)/hidd/pci.h : include/pci_hidd.h
    //
    // A static pattern rule names it in the middle field instead, and the
    // target is a variable holding the file list:
    //
    //     $(DEST_INCLUDES) : $(AROS_INCLUDES)/% : $(SRCDIR)/$(CURDIR)/%
    //
    // workbench/network/common/include stages 81 headers that way, the whole
    // BSD socket interface, and matching only the first shape left it
    // unreported: netdb.h, netinet/in.h and proto/socket.h went missing with
    // nothing to say why.
    let (root, dest, prereqs) = if let Some(r) = ROOTS.iter().find(|r| line.starts_with(**r)) {
        (
            *r,
            target[r.len()..].trim().to_owned(),
            prereqs.trim().trim_start_matches(':').trim().to_owned(),
        )
    } else {
        let (pattern, source) = prereqs.split_once(':')?;
        let pattern = pattern.trim();
        let r = ROOTS.iter().find(|r| pattern.starts_with(**r))?;
        (
            *r,
            pattern[r.len()..].trim().to_owned(),
            format!("{} (files: {})", source.trim(), target.trim()),
        )
    };

    // $(AROS_INCLUDES) and $(GENINCDIR) are include roots, so everything
    // landing there is a header whatever its name, including pattern rules and
    // variable-named targets. $(GENDIR) holds every kind of generated file, so
    // there the suffix decides.
    let extension = Path::new(&dest)
        .extension()
        .and_then(|value| value.to_str());
    let is_private_generated = matches!(root, "$(GENDIR)/" | "${CMAKE_BINARY_DIR}/gen/");
    let is_header = !is_private_generated || matches!(extension, Some("h" | "hpp"));
    if is_header {
        return Some(ParsedRule::Header(AdhocHeaderRule {
            file: mmakefile.to_owned(),
            line: line_no,
            root: root.to_owned(),
            dest,
            prereqs,
        }));
    }

    // Rules that create a directory, or a Make dependency file, carry no build
    // output of their own. CMake creates output directories itself and tracks
    // header dependencies through the compiler, so these cannot go missing and
    // would only dilute the report.
    let is_bookkeeping = extension == Some("d")
        || !dest.contains('.')
        || dest.ends_with(".includes-generated")
        || dest.ends_with(".stubs-generated");
    if is_bookkeeping {
        return None;
    }

    Some(ParsedRule::Other(format!(
        "{root}{dest} <- {prereqs}  ({mmakefile}:{line_no})"
    )))
}

fn parse_bison_output(
    lines: &[&str],
    index: usize,
    mmakefile: &str,
    base: &str,
    vars: &HashMap<String, String>,
    external: ExternalVarLookup<'_>,
) -> Option<BisonOutputDecl> {
    let rule = lines.get(index)?.trim();
    let (raw_output, raw_input) = rule.split_once(':')?;
    let raw_output = raw_output.trim();
    let raw_input = raw_input.trim();
    if raw_output.contains(char::is_whitespace)
        || raw_input.contains(char::is_whitespace)
        || !Path::new(raw_output)
            .extension()
            .is_some_and(|extension| extension.eq_ignore_ascii_case("c"))
        || !Path::new(raw_input)
            .extension()
            .is_some_and(|extension| extension.eq_ignore_ascii_case("y"))
    {
        return None;
    }

    let commands: Vec<_> = lines
        .iter()
        .skip(index + 1)
        .take_while(|line| line.starts_with('\t'))
        .map(|line| line.trim().to_owned())
        .collect();
    if commands.as_slice()
        != [
            "@$(ECHO) Generating $(notdir $@) from $<...",
            "@$(BISON) -o $@ $<",
        ]
    {
        return None;
    }

    let output = resolve_transform_path(raw_output, base, vars, external, true)?;
    let input = resolve_transform_path(raw_input, base, vars, external, false)?;
    let owner = lines.iter().find_map(|line| {
        if line.starts_with('\t') {
            return None;
        }
        let (target, prereqs) = line.trim().split_once(':')?;
        let owner = target.trim().strip_prefix("$(")?.strip_suffix("_DEPS)")?;
        if owner.is_empty() || owner.contains(char::is_whitespace) {
            return None;
        }
        let rendered = substitute(prereqs.trim(), vars, external, 8);
        rendered
            .split_whitespace()
            .any(|prereq| prereq == output)
            .then(|| owner.to_owned())
    })?;

    Some(BisonOutputDecl {
        owner,
        file: mmakefile.to_owned(),
        line: index + 1,
        input,
        output,
    })
}

/// A rule of the shape `$(GENDIR)/... : <inputs>` whose single recipe line is
/// `$(PYTHON) <script> <args>`.
///
/// Returns `None` when the rule is not that shape, so the caller falls back to
/// reporting it, and `Err` when it is that shape and still cannot be used.
fn parse_script_output(
    lines: &[&str],
    index: usize,
    base: &str,
    vars: &HashMap<String, String>,
    external: ExternalVarLookup<'_>,
) -> Option<Result<ScriptOutputDecl, String>> {
    // The rule line continues while it ends in a backslash; the recipe starts
    // after the last continuation. The general scan does not join these, unlike
    // the %copy_includes branch, so it has to be done here.
    let mut joined = String::new();
    let mut cursor = index;
    loop {
        let line = lines.get(cursor)?;
        let trimmed = line.trim_end();
        joined.push_str(trimmed.trim_end_matches('\\').trim_end());
        cursor += 1;
        if !trimmed.ends_with('\\') {
            break;
        }
        joined.push(' ');
    }

    let (target, prereqs) = joined.split_once(':')?;
    let target = target.trim();
    if target.contains('%') {
        return None;
    }

    let recipe: Vec<&str> = lines[cursor..]
        .iter()
        .take_while(|line| line.starts_with('\t'))
        .map(|line| line.trim())
        .collect();
    // Directory creation and the exact informational status line carry no
    // generator semantics. Every other recipe still has to collapse to one
    // Python invocation.
    let commands: Vec<&str> = recipe
        .iter()
        .copied()
        .filter(|line| {
            !line.starts_with("%mkdir_q ")
                && !line.starts_with("$(Q)$(ECHO) \"Generating ")
                && !line.starts_with("@$(ECHO) Generating $@")
        })
        .collect();
    let [python_recipe] = commands.as_slice() else {
        return None;
    };
    // Do not diagnose ordinary compile/copy/sed rules merely because their
    // target contains a variable this specialised recogniser cannot resolve.
    // From here on, every error is reserved for a recipe that actually claims
    // to invoke the supported Python lane.
    if !python_recipe.contains("$(PYTHON)") {
        return None;
    }

    let resolve = |raw: &str| -> Result<String, String> {
        let value = substitute(raw, vars, external, 8);
        if value.contains("$(") {
            return Err(format!("`{raw}` does not resolve"));
        }
        if value.contains([';', '&', '|', '>', '<', '`', '"', '\'']) {
            return Err(format!("`{value}` is not a plain word"));
        }
        Ok(value)
    };

    let rendered_outputs = match resolve(target) {
        Ok(value) => value,
        Err(reason) => return Some(Err(format!("{base}: target {reason}"))),
    };
    let outputs: Vec<String> = rendered_outputs
        .split_whitespace()
        .map(str::to_owned)
        .collect();
    if outputs.is_empty()
        || outputs.iter().any(|output| {
            !output.starts_with("${AROS_BUILD_DIR}/") && !output.starts_with("${CMAKE_BINARY_DIR}/")
        })
    {
        return None;
    }
    let output = outputs[0].clone();

    // The order-only half of the prerequisites is a directory, which CMake
    // creates itself.
    let ordered = prereqs.split('|').next().unwrap_or_default();
    let mut depends = Vec::new();
    for raw in split_make_words(ordered)? {
        match resolve(raw) {
            Ok(value) => depends.extend(value.split_whitespace().map(str::to_owned)),
            Err(reason) => return Some(Err(format!("{base}: prerequisite {reason}"))),
        }
    }

    let mut command = python_recipe
        .trim_start_matches('@')
        .strip_prefix("$(Q)")
        .unwrap_or_else(|| python_recipe.trim_start_matches('@'))
        .trim();
    if let Some(without_failure) = command.strip_suffix(" || ($(RM) $@; false)") {
        command = without_failure.trim_end();
    }

    let stdout = if let Some((invocation, destination)) = command.rsplit_once('>') {
        if destination.trim() != "$@" {
            return Some(Err(format!(
                "{base}: {output} redirects Python output to unsupported `{}`",
                destination.trim()
            )));
        }
        command = invocation.trim_end();
        true
    } else {
        false
    };
    if stdout && outputs.len() != 1 {
        return Some(Err(format!(
            "{base}: stdout recipe declares {} outputs; transpiler update required",
            outputs.len()
        )));
    }

    let mut working_directory = None;
    if let Some(after_cd) = command.strip_prefix("cd ") {
        let Some((raw_directory, invocation)) = after_cd.split_once(" && ") else {
            return Some(Err(format!("{base}: malformed Python working directory")));
        };
        working_directory = match resolve(raw_directory.trim()) {
            Ok(value) => Some(value),
            Err(reason) => return Some(Err(format!("{base}: working directory {reason}"))),
        };
        command = invocation.trim();
    }

    command = command.strip_prefix("$(Q)").unwrap_or(command).trim();
    let after_python = command.strip_prefix("$(PYTHON)")?;
    let raw_words: Vec<&str> = split_make_words(after_python)?
        .into_iter()
        .filter(|word| *word != "$(PYTHON_FLAGS)")
        .collect();
    let mut expanded_words = Vec::new();
    for raw in raw_words {
        if raw == "$^" {
            expanded_words.extend(depends.iter().cloned());
            continue;
        }
        let resolved = match raw {
            "$<" => depends
                .first()
                .cloned()
                .ok_or_else(|| format!("{base}: {output} uses $< without a prerequisite")),
            "$@" => Ok(output.clone()),
            "$(dir $@)" => Ok(format!(
                "{}/",
                Path::new(&output)
                    .parent()
                    .and_then(Path::to_str)
                    .unwrap_or_default()
            )),
            _ => resolve(raw).map_err(|reason| format!("{base}: argument {reason}")),
        };
        match resolved {
            Ok(value) => expanded_words.extend(value.split_whitespace().map(str::to_owned)),
            Err(reason) => return Some(Err(reason)),
        }
    }
    let Some(script) = expanded_words.first().cloned() else {
        return Some(Err(format!("{base}: {output} has no script to run")));
    };
    let arguments = expanded_words.into_iter().skip(1).collect();

    let mut consumer_source_stems = Vec::new();
    for raw in lines {
        if raw.starts_with('\t') {
            continue;
        }
        let Some((targets, prerequisites)) = raw.trim().split_once(':') else {
            continue;
        };
        let rendered_prerequisites = substitute(prerequisites.trim(), vars, external, 8);
        if !rendered_prerequisites
            .split_whitespace()
            .any(|prerequisite| prerequisite == output)
        {
            continue;
        }
        let rendered_targets = substitute(targets.trim(), vars, external, 8);
        for target in rendered_targets.split_whitespace() {
            let path = Path::new(target);
            let is_object_dependency = path.extension().is_some_and(|extension| {
                extension.eq_ignore_ascii_case("o") || extension.eq_ignore_ascii_case("d")
            });
            if !is_object_dependency {
                continue;
            }
            if let Some(stem) = path.file_stem().and_then(|stem| stem.to_str()) {
                if !consumer_source_stems.iter().any(|known| known == stem) {
                    consumer_source_stems.push(stem.to_owned());
                }
            }
        }
    }

    Some(Ok(ScriptOutputDecl {
        directory: base.to_owned(),
        output,
        additional_outputs: outputs.into_iter().skip(1).collect(),
        script,
        arguments,
        stdout,
        working_directory,
        depends,
        consumer_source_stems,
        consumer_targets: Vec::new(),
    }))
}

/// Resolves one `%copy_includes` directive against the current variable state.
fn resolve_directive(
    body: &str,
    base: &str,
    vars: &HashMap<String, String>,
    external: ExternalVarLookup<'_>,
    decls: &mut Vec<CopyIncludesDecl>,
    skipped: &mut Vec<String>,
) {
    let name = arg_value(body, "mmake").unwrap_or_else(default_copy_target);
    let dest = arg_value(body, "path").unwrap_or_else(|| ".".to_owned());
    let dir = arg_value(body, "dir");

    let raw_includes = arg_value_quoted(body, "includes")
        .or_else(|| arg_value(body, "includes"))
        .unwrap_or_else(|| "$(INCLUDE_FILES)".to_owned());

    let Some(resolved) = resolve_file_list(&raw_includes, vars, external) else {
        skipped.push(format!("{base}: path={dest} includes={raw_includes}"));
        return;
    };

    let (source_dir, flatten) = match dir {
        Some(d) => {
            let d = substitute(&d, vars, external, 8);
            if d.starts_with("${") {
                // An absolute CMake location, e.g. a directory inside a port
                // unpacked by %fetch.
                (d, true)
            } else if d.contains('$') || d.starts_with('/') {
                skipped.push(format!("{base}: path={dest} dir={d}"));
                return;
            } else {
                (join_rel(base, &d), true)
            }
        }
        None => (base.to_owned(), false),
    };

    let patterns = if flatten {
        resolved
            .patterns
            .iter()
            .map(|p| p.rsplit('/').next().unwrap_or(p).to_owned())
            .collect()
    } else {
        resolved.patterns
    };
    let excludes = if flatten {
        resolved
            .excludes
            .iter()
            .map(|p| p.rsplit('/').next().unwrap_or(p).to_owned())
            .collect()
    } else {
        resolved.excludes
    };
    if patterns.iter().any(|p: &String| p.contains("$(")) {
        skipped.push(format!("{base}: path={dest} has an unresolved glob"));
        return;
    }

    decls.push(CopyIncludesDecl {
        name,
        dest,
        source_dir,
        patterns,
        excludes,
        flatten,
    });
}

/// Joins two source-relative path fragments, collapsing `..` segments.
fn join_rel(base: &str, add: &str) -> String {
    let mut parts: Vec<&str> = base.split('/').filter(|s| !s.is_empty()).collect();
    for seg in add.split('/') {
        match seg {
            "" | "." => {}
            ".." => {
                parts.pop();
            }
            other => parts.push(other),
        }
    }
    parts.join("/")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn wildcard_with_dir_flattens_to_basenames() {
        // rom/hidds/kbd/mmakefile.src
        let src = "INCLUDE_FILES := $(call WILDCARD, include/*.h)\n%copy_includes path=hidd dir=include\n";
        let CopyIncludesScan { decls, skipped, .. } =
            collect_copy_includes(src, &PathBuf::from("rom/hidds/kbd"));
        assert!(skipped.is_empty());
        assert_eq!(decls.len(), 1);
        assert_eq!(decls[0].dest, "hidd");
        assert_eq!(decls[0].source_dir, "rom/hidds/kbd/include");
        assert_eq!(decls[0].patterns, vec!["*.h"]);
        assert!(decls[0].flatten);
    }

    #[test]
    fn explicit_name_without_dir_keeps_relative_path() {
        // workbench/classes/zune/iconimage/mmakefile.src
        let src = "INCLUDE_FILES := iconimage.h\n%copy_includes path=zune\n";
        let CopyIncludesScan { decls, .. } =
            collect_copy_includes(src, &PathBuf::from("workbench/classes/zune/iconimage"));
        assert_eq!(decls[0].dest, "zune");
        assert_eq!(decls[0].source_dir, "workbench/classes/zune/iconimage");
        assert_eq!(decls[0].patterns, vec!["iconimage.h"]);
        assert!(!decls[0].flatten);
    }

    #[test]
    fn explicit_dot_destination_reaches_cmake_as_the_include_root() {
        let src = "INCLUDE_FILES := zlib.h\n%copy_includes mmake=z-includes path=. dir=include\n";
        let CopyIncludesScan { decls, skipped, .. } =
            collect_copy_includes(src, &PathBuf::from("workbench/libs/z"));
        assert!(skipped.is_empty());
        assert_eq!(decls.len(), 1);
        assert_eq!(decls[0].name, "z-includes");
        assert_eq!(decls[0].dest, ".");
        assert_eq!(decls[0].patterns, ["zlib.h"]);
    }

    #[test]
    fn oop_case_maps_to_sdk_prefix() {
        // rom/oop/mmakefile.src, the header that blocked 49 compilations.
        let src =
            "INCLUDE_FILES := $(call WILDCARD, include/*.h)\n%copy_includes path=oop dir=include\n";
        let CopyIncludesScan { decls, .. } = collect_copy_includes(src, &PathBuf::from("rom/oop"));
        assert_eq!(decls[0].dest, "oop");
        assert_eq!(decls[0].source_dir, "rom/oop/include");
    }

    #[test]
    fn expands_character_classes_for_cmake_glob() {
        let src = "INCLUDE_FILES := $(call WILDCARD, *.[hi] aros/*.[hi])\n%copy_includes path=x\n";
        let CopyIncludesScan { decls, .. } = collect_copy_includes(src, &PathBuf::from("d"));
        let p = &decls[0].patterns;
        assert!(p.contains(&"*.h".to_owned()));
        assert!(p.contains(&"*.i".to_owned()));
        assert!(p.contains(&"aros/*.h".to_owned()));
        assert!(p.contains(&"aros/*.i".to_owned()));
    }

    #[test]
    fn inline_include_list_is_honoured() {
        let src = "%copy_includes path=libraries includes=\"speechcore.h aros_resource.h\"\n";
        let CopyIncludesScan { decls, .. } = collect_copy_includes(src, &PathBuf::from("d"));
        assert_eq!(decls[0].patterns, vec!["speechcore.h", "aros_resource.h"]);
    }

    #[test]
    fn unresolvable_third_party_dir_is_skipped_not_guessed() {
        let src = "INCLUDE_FILES := $(call WILDCARD, *.h)\n%copy_includes path=freetype dir=$(FT2SRCDIR)/include\n";
        let CopyIncludesScan { decls, skipped, .. } =
            collect_copy_includes(src, &PathBuf::from("d"));
        assert!(decls.is_empty());
        assert_eq!(skipped.len(), 1);
        assert!(skipped[0].contains("FT2SRCDIR"));
    }

    #[test]
    fn unresolvable_include_list_is_skipped() {
        let src = "%copy_includes path=x dir=include\n";
        let CopyIncludesScan { decls, skipped, .. } =
            collect_copy_includes(src, &PathBuf::from("d"));
        assert!(
            decls.is_empty(),
            "no INCLUDE_FILES defined, nothing to copy"
        );
        assert_eq!(skipped.len(), 1);
    }

    #[test]
    fn parent_relative_dir_resolves() {
        let src = "INCLUDE_FILES := ../include/mui/BetterString_mcc.h\n%copy_includes path=mui dir=../include/mui\n";
        let CopyIncludesScan { decls, .. } =
            collect_copy_includes(src, &PathBuf::from("workbench/classes/zune/betterstring"));
        assert_eq!(decls[0].source_dir, "workbench/classes/zune/include/mui");
        assert_eq!(decls[0].patterns, vec!["BetterString_mcc.h"]);
    }

    #[test]
    fn reassigned_include_files_uses_value_in_force_at_the_directive() {
        // arch/all-native/acpica/mmakefile.src reassigns INCLUDE_FILES between
        // the two directives; Make resolves each against the current value.
        let src = "\
INCLUDE_FILES := $(call WILDCARD, include/*.h)
%copy_includes path=libraries dir=include
INCLUDE_FILES = $(call WILDCARD, $(ACPICA_INCLUDES)/*.h)
%copy_includes mmake=acpica-includes-copy path=acpica dir=$(ACPICA_INCLUDES)
";
        let CopyIncludesScan { decls, skipped, .. } =
            collect_copy_includes(src, &PathBuf::from("arch/all-native/acpica"));
        // The first directive must resolve; the second is out-of-tree.
        assert_eq!(decls.len(), 1, "decls: {decls:?}");
        assert_eq!(decls[0].dest, "libraries");
        assert_eq!(decls[0].source_dir, "arch/all-native/acpica/include");
        assert_eq!(decls[0].patterns, vec!["*.h"]);
        assert_eq!(skipped.len(), 1);
    }

    #[test]
    fn nested_parens_in_wildcard_do_not_truncate_the_glob() {
        // `$(call WILDCARD, $(X)/*.h)` must not be cut at the inner ")".
        let src = "INCLUDE_FILES := $(call WILDCARD, $(SOMEDIR)/*.h)\n%copy_includes path=x\n";
        let CopyIncludesScan { decls, skipped, .. } =
            collect_copy_includes(src, &PathBuf::from("d"));
        assert!(
            decls.is_empty(),
            "unresolved variable must not yield a pattern"
        );
        assert_eq!(skipped.len(), 1);
        assert!(
            !skipped[0].contains("*.h)"),
            "glob was truncated: {}",
            skipped[0]
        );
    }

    #[test]
    fn detects_hand_written_staging_rules() {
        // rom/hidds/pci/mmakefile.src stages a renamed header with a plain rule.
        let src = "\
$(AROS_INCLUDES)/hidd/pci.h: include/pci_hidd.h
\t$(CP) $< $(AROS_INCLUDES)/hidd/pci.h

$(GENINCDIR)/hidd/pci.h: include/pci_hidd.h
\t$(CP) $< $(GENINCDIR)/hidd/pci.h
";
        let CopyIncludesScan { adhoc, .. } =
            collect_copy_includes(src, &PathBuf::from("rom/hidds/pci"));
        assert_eq!(adhoc.len(), 2, "adhoc: {adhoc:?}");
        assert_eq!(adhoc[0].file, "rom/hidds/pci/mmakefile.src");
        assert_eq!(adhoc[0].line, 1);
        assert_eq!(adhoc[0].dest, "hidd/pci.h");
        assert_eq!(adhoc[0].prereqs, "include/pci_hidd.h");
        assert_eq!(adhoc[1].dest, "hidd/pci.h");
    }

    #[test]
    fn promotes_a_literal_anchored_sed_header_to_a_real_transform() {
        let src = r"
ARCHSRCDIR := $(PORTSDIR)/zlib/zlib
z-geninc : $(AROS_INCLUDES)/zconf.h

$(AROS_INCLUDES)/zconf.h : $(ARCHSRCDIR)/zconf.h.chr
	@$(IF) $(TEST) ! -d $(AROS_LIB)/pkgconfig ; then $(MKDIR) $(AROS_LIB)/pkgconfig ; else $(NOP) ; fi
	@$(SED) -e 's/^#if !defined(CHROMIUM_ZLIB_NO_CHROMECONF)/#if defined(ZLIB_USE_CHROMECONF)/' \
	    $< > $@
";
        let CopyIncludesScan {
            transforms, adhoc, ..
        } = collect_copy_includes(src, &PathBuf::from("workbench/libs/z"));
        assert!(adhoc.is_empty(), "promoted rule stayed adhoc: {adhoc:?}");
        assert_eq!(transforms.len(), 1, "transforms: {transforms:?}");
        let transform = &transforms[0];
        assert_eq!(transform.name, "z-geninc");
        assert_eq!(transform.input, "${AROS_PORTS_DIR}/zlib/zlib/zconf.h.chr");
        assert_eq!(transform.output, "${AROS_SDK_INCLUDE_DIR}/zconf.h");
        assert_eq!(
            transform.match_text,
            "#if !defined(CHROMIUM_ZLIB_NO_CHROMECONF)"
        );
        assert_eq!(transform.replacement, "#if defined(ZLIB_USE_CHROMECONF)");
        assert!(!transform.copy_only);
    }

    #[test]
    fn promotes_an_exact_header_copy_with_safe_prelude() {
        let src = r#"
webp-generated : $(GENDIR)/$(CURDIR)/src/webp/config.h

$(GENDIR)/$(CURDIR)/src/webp/config.h : $(SRCDIR)/$(CURDIR)/config.h $(SRCDIR)/$(CURDIR)/mmakefile.src
	@$(ECHO) "Generating src/webp/config.h ..."
	%mkdir_q dir=$(GENDIR)/$(CURDIR)/src/webp
	@$(CP) $< $@
"#;
        let CopyIncludesScan {
            transforms, adhoc, ..
        } = collect_copy_includes(src, &PathBuf::from("workbench/classes/datatypes/webp"));
        assert!(adhoc.is_empty(), "promoted copy stayed adhoc: {adhoc:?}");
        assert_eq!(transforms.len(), 1, "transforms: {transforms:?}");
        let transform = &transforms[0];
        assert!(transform.copy_only);
        assert_eq!(transform.name, "webp-generated");
        assert_eq!(
            transform.input,
            "${CMAKE_SOURCE_DIR}/workbench/classes/datatypes/webp/config.h"
        );
        assert_eq!(
            transform.output,
            "${CMAKE_BINARY_DIR}/gen/workbench/classes/datatypes/webp/src/webp/config.h"
        );
    }

    #[test]
    fn promotes_the_real_tiff_sdk_header_copies_without_recipe_echo_suppression() {
        let src = include_str!("../../../../../workbench/libs/tiff/mmakefile.src");
        let CopyIncludesScan {
            transforms, adhoc, ..
        } = collect_copy_includes(src, &PathBuf::from("workbench/libs/tiff"));

        for header in ["tiffconf.h", "tifftypes.h", "tiffinline.h"] {
            let transform = transforms
                .iter()
                .find(|transform| transform.output.ends_with(header))
                .unwrap_or_else(|| panic!("missing transform for {header}: {transforms:?}"));
            assert_eq!(transform.name, "workbench-libs-tiff-generated");
            assert!(transform.copy_only);
            assert!(transform
                .input
                .ends_with(&format!("/workbench/libs/tiff/{header}")));
        }
        assert!(
            adhoc
                .iter()
                .all(|rule| !["tiffconf.h", "tifftypes.h", "tiffinline.h"]
                    .contains(&rule.dest.as_str())),
            "TIFF copies stayed in the residual audit: {adhoc:?}"
        );
    }

    #[test]
    fn promotes_a_copy_through_a_module_private_include_variable() {
        let src = r#"
JXLGENINCDIR := $(GENDIR)/$(CURDIR)/include
$(JXLGENINCDIR)/jxl/jxl_export.h : $(SRCDIR)/$(CURDIR)/jxl_export.h
	@$(ECHO) "Generating jxl/jxl_export.h ..."
	%mkdir_q dir=$(JXLGENINCDIR)/jxl
	@$(CP) $< $@

jxl-genfiles : $(JXLGENINCDIR)/jxl/jxl_export.h
"#;
        let CopyIncludesScan {
            transforms, adhoc, ..
        } = collect_copy_includes(src, &PathBuf::from("workbench/classes/datatypes/jpegxl"));
        assert!(adhoc.is_empty(), "promoted copy stayed adhoc: {adhoc:?}");
        assert_eq!(transforms.len(), 1, "transforms: {transforms:?}");
        assert!(transforms[0].copy_only);
        assert_eq!(transforms[0].name, "jxl-genfiles");
        assert_eq!(
            transforms[0].output,
            "${CMAKE_BINARY_DIR}/gen/workbench/classes/datatypes/jpegxl/include/jxl/jxl_export.h"
        );
    }

    #[test]
    fn real_jpegxl_export_copy_is_promoted() {
        let src = include_str!("../../../../../workbench/classes/datatypes/jpegxl/mmakefile.src");
        let CopyIncludesScan {
            transforms, adhoc, ..
        } = collect_copy_includes(src, &PathBuf::from("workbench/classes/datatypes/jpegxl"));
        assert!(
            transforms.iter().any(|transform| {
                transform.copy_only && transform.output.ends_with("/jxl/jxl_export.h")
            }),
            "transforms: {transforms:?}; adhoc: {adhoc:?}"
        );
        let version = transforms
            .iter()
            .find(|transform| transform.output.ends_with("/jxl/version.h"))
            .expect("version template was not promoted");
        assert_eq!(
            version.substitutions,
            [
                "@JPEGXL_MAJOR_VERSION@",
                "0",
                "@JPEGXL_MINOR_VERSION@",
                "12",
                "@JPEGXL_PATCH_VERSION@",
                "0",
            ]
        );
    }

    #[test]
    fn promotes_exact_bison_output_and_binds_its_dependency_owner() {
        let src = r"
$(OBJDIR)/evalParser.tab.c : evalParser.y
	@$(ECHO) Generating $(notdir $@) from $<...
	@$(BISON) -o $@ $<

$(workbench-c-eval_DEPS) : $(OBJDIR)/evalParser.tab.c
";
        let scan = collect_copy_includes(src, &PathBuf::from("workbench/c"));
        assert!(
            scan.generated_files.is_empty(),
            "{:?}",
            scan.generated_files
        );
        assert_eq!(scan.bison_outputs.len(), 1, "{:?}", scan.bison_outputs);
        let output = &scan.bison_outputs[0];
        assert_eq!(output.owner, "workbench-c-eval");
        assert_eq!(output.input, "${CMAKE_SOURCE_DIR}/workbench/c/evalParser.y");
        assert_eq!(
            output.output,
            "${CMAKE_BINARY_DIR}/gen/workbench/c/evalParser.tab.c"
        );
    }

    #[test]
    fn arbitrary_sed_regex_remains_reported_as_adhoc() {
        let src = r"
x-geninc : $(AROS_INCLUDES)/x.h
$(AROS_INCLUDES)/x.h : input.h
	@$(SED) -e 's/^version=.*/version=1/' $< > $@
";
        let CopyIncludesScan {
            transforms, adhoc, ..
        } = collect_copy_includes(src, &PathBuf::from("workbench/libs/x"));
        assert!(transforms.is_empty());
        assert_eq!(adhoc.len(), 1);
        assert_eq!(adhoc[0].dest, "x.h");
    }

    #[test]
    fn sed_transform_rejects_extra_commands_suffixes_and_special_replacements() {
        let recipes = [
            "\t@$(NOP)\n\t@$(SED) -e 's/^literal/changed/' $< > $@",
            "\t@$(SED) -e 's/^literal/changed/' $< > $@ ; $(TOUCH) marker",
            "\t@$(SED) -e 's/^literal/prefix-&/' $< > $@",
            "\t@$(SED) -e 's/^literal/changed/' $< > $@\n\t@$(NOP)",
        ];
        for recipe in recipes {
            let src = format!(
                "x-geninc : $(AROS_INCLUDES)/x.h\n\
                 $(AROS_INCLUDES)/x.h : input.h\n{recipe}\n"
            );
            let CopyIncludesScan {
                transforms, adhoc, ..
            } = collect_copy_includes(&src, &PathBuf::from("workbench/libs/x"));
            assert!(transforms.is_empty(), "unsafe recipe promoted: {recipe}");
            assert_eq!(adhoc.len(), 1, "unsafe recipe disappeared: {recipe}");
        }
    }

    #[test]
    fn variable_assignment_is_not_mistaken_for_a_rule() {
        let src = "INCLUDE_FILES := a.h\n%copy_includes path=x\n";
        let CopyIncludesScan { decls, adhoc, .. } = collect_copy_includes(src, &PathBuf::from("d"));
        assert!(adhoc.is_empty());
        assert_eq!(decls.len(), 1);
    }

    #[test]
    fn stages_headers_from_a_fetched_port() {
        // The real arch/all-native/acpica declaration: the source directory is
        // rooted in $(PORTSDIR), which %fetch unpacks into.
        let src = "\
ACPICAPACKAGE      := acpica
ACPICAVERSION      := 20260408
ACPICAARCHBASE     := $(ACPICAPACKAGE)-unix-$(ACPICAVERSION)
ACPICASRCDIR       := $(PORTSDIR)/acpica/$(ACPICAARCHBASE)
ACPICA_INCLUDES    := $(ACPICASRCDIR)/source/include
INCLUDE_FILES = $(call WILDCARD, $(ACPICA_INCLUDES)/*.h)
%copy_includes mmake=acpica-includes-copy path=acpica dir=$(ACPICA_INCLUDES)
";
        let CopyIncludesScan { decls, skipped, .. } =
            collect_copy_includes(src, &PathBuf::from("arch/all-native/acpica"));
        assert!(skipped.is_empty(), "skipped: {skipped:?}");
        assert_eq!(decls.len(), 1);
        assert_eq!(decls[0].dest, "acpica");
        assert_eq!(
            decls[0].source_dir,
            "${AROS_PORTS_DIR}/acpica/acpica-unix-20260408/source/include"
        );
        assert_eq!(decls[0].patterns, vec!["*.h"]);
        assert!(decls[0].flatten);
    }

    #[test]
    fn preserves_nested_notdir_wildcards_and_literal_filter_out_for_freetype() {
        // workbench/libs/freetype2/mmakefile.src publishes a fetched header
        // tree, but deliberately generates ftoption.h instead of copying its
        // upstream default.  The source directory does not exist at configure
        // time, so the resulting glob and exclusion must remain declarative.
        let src = "\
FT2NAME := freetype
FT2VERS := 2.14.3
ARCHBASE := $(FT2NAME)-$(FT2VERS)
FT2SRCDIR := $(PORTSDIR)/$(FT2NAME)2/$(ARCHBASE)
FT2_INCLUDE_FILES := $(notdir $(call WILDCARD, $(FT2SRCDIR)/include/*.h))
%copy_includes mmake=workbench-libs-freetype-includes-copy dir=$(FT2SRCDIR)/include includes=$(FT2_INCLUDE_FILES)
FT2I_INCLUDE_FILES := $(notdir $(call WILDCARD, $(FT2SRCDIR)/include/freetype/*.h))
%copy_includes mmake=workbench-libs-freetype-includes-copy path=freetype dir=$(FT2SRCDIR)/include/freetype includes=$(FT2I_INCLUDE_FILES)
FT2OPTIONFILE := ftoption.h
FT2CONFIG_INCLUDE_FILES := $(filter-out $(FT2OPTIONFILE),$(notdir $(call WILDCARD, $(FT2SRCDIR)/include/freetype/config/*.h)))
%copy_includes mmake=workbench-libs-freetype-includes-copy path=freetype/config dir=$(FT2SRCDIR)/include/freetype/config includes=$(FT2CONFIG_INCLUDE_FILES)
FT2INT_INCLUDE_FILES := $(notdir $(call WILDCARD, $(FT2SRCDIR)/include/freetype/internal/*.h))
%copy_includes mmake=workbench-libs-freetype-includes-copy path=freetype/internal dir=$(FT2SRCDIR)/include/freetype/internal includes=$(FT2INT_INCLUDE_FILES)
FT2SVC_INCLUDE_FILES := $(notdir $(call WILDCARD, $(FT2SRCDIR)/include/freetype/internal/services/*.h))
%copy_includes mmake=workbench-libs-freetype-includes-copy path=freetype/internal/services dir=$(FT2SRCDIR)/include/freetype/internal/services includes=$(FT2SVC_INCLUDE_FILES)
";
        let CopyIncludesScan { decls, skipped, .. } =
            collect_copy_includes(src, &PathBuf::from("workbench/libs/freetype2"));

        assert!(skipped.is_empty(), "skipped: {skipped:?}");
        assert_eq!(decls.len(), 5, "decls: {decls:?}");
        assert!(decls.iter().all(|decl| {
            decl.name == "workbench-libs-freetype-includes-copy"
                && decl
                    .source_dir
                    .starts_with("${AROS_PORTS_DIR}/freetype2/freetype-2.14.3/include")
                && decl.patterns == ["*.h"]
                && decl.flatten
        }));
        let config = decls
            .iter()
            .find(|decl| decl.dest == "freetype/config")
            .expect("freetype config header group");
        assert_eq!(config.excludes, ["ftoption.h"]);
        assert!(decls
            .iter()
            .filter(|decl| decl.dest != "freetype/config")
            .all(|decl| decl.excludes.is_empty()));
    }

    #[test]
    fn resolves_gnu_wildcard_sort_and_patsubst_header_lists() {
        let src = "\
ARCHSRCDIR := $(PORTSDIR)/xz/xz-5.8.3
API_HEADERS := $(sort $(wildcard $(ARCHSRCDIR)/src/liblzma/api/lzma/*.h))
APIINCLUDE_FILES := $(patsubst $(ARCHSRCDIR)/src/liblzma/api/lzma/%,%,$(API_HEADERS))
%copy_includes mmake=lzma-includes dir=$(ARCHSRCDIR)/src/liblzma/api/lzma includes=$(APIINCLUDE_FILES) path=lzma
INCLUDE_FILES := $(wildcard include/*.h)
%copy_includes mmake=dbus-includes dir=include path=dbus
";
        let CopyIncludesScan { decls, skipped, .. } =
            collect_copy_includes(src, &PathBuf::from("workbench/libs/example"));

        assert!(skipped.is_empty(), "skipped: {skipped:?}");
        assert_eq!(decls.len(), 2);
        assert_eq!(
            decls[0].source_dir,
            "${AROS_PORTS_DIR}/xz/xz-5.8.3/src/liblzma/api/lzma"
        );
        assert_eq!(decls[0].patterns, ["*.h"]);
        assert_eq!(decls[0].dest, "lzma");
        assert_eq!(decls[1].source_dir, "workbench/libs/example/include");
        assert_eq!(decls[1].patterns, ["*.h"]);
        assert_eq!(decls[1].dest, "dbus");
    }

    #[test]
    fn module_private_generated_header_is_recorded() {
        // rom/dos/mmakefile.src:90. Before $(GENDIR) was a recognised root this
        // rule went unreported, and the missing errorlist.h surfaced as an
        // undeclared MSG_STRING_* in displayerror.c instead.
        let src = "$(GENDIR)/$(CURDIR)/dos/errorlist.h : $(SRCDIR)/$(CURDIR)/catalogs/dos.cd\n";
        let CopyIncludesScan { adhoc, .. } = collect_copy_includes(src, &PathBuf::from("rom/dos"));
        assert_eq!(adhoc.len(), 1);
        assert_eq!(adhoc[0].root, "$(GENDIR)/");
        assert_eq!(adhoc[0].dest, "$(CURDIR)/dos/errorlist.h");
    }

    #[test]
    fn non_header_under_gendir_is_reported_separately() {
        let src = "$(GENDIR)/boot/aros-amiga-m68k.elf : $(KOBJS_rom)\n";
        let CopyIncludesScan {
            adhoc,
            generated_files,
            ..
        } = collect_copy_includes(src, &PathBuf::from("arch/m68k-amiga/boot"));
        assert!(adhoc.is_empty());
        assert_eq!(generated_files.len(), 1);
        assert!(generated_files[0].contains("aros-amiga-m68k.elf"));
    }

    #[test]
    fn directory_and_dependency_rules_are_not_reported() {
        // CMake makes output directories itself and tracks header dependencies
        // through the compiler, so neither can go missing.
        let src = "\
$(GENDIR)/$(CURDIR) :
$(GENDIR)/$(CURDIR)/errorlist.d : $(GENDIR)/$(CURDIR)/errorlist.h
$(GENDIR)/$(CURDIR)/.includes-generated : $(GENMODULE)
";
        let CopyIncludesScan {
            adhoc,
            generated_files,
            ..
        } = collect_copy_includes(src, &PathBuf::from("rom/dos"));
        assert!(adhoc.is_empty(), "adhoc: {adhoc:?}");
        assert!(generated_files.is_empty(), "reported: {generated_files:?}");
    }

    #[test]
    fn target_in_an_include_root_counts_as_a_header_whatever_its_name() {
        // $(AROS_INCLUDES) is an include root, so a variable-named or pattern
        // target there is still a header. Only $(GENDIR) mixes file kinds.
        let src = "\
$(AROS_INCLUDES)/freetype/config/$(FT2OPTIONFILE) : $(FT2SRCDIR)/x
$(AROS_INCLUDES)/% : %
";
        let CopyIncludesScan {
            adhoc,
            generated_files,
            ..
        } = collect_copy_includes(src, &PathBuf::from("workbench/libs/freetype2"));
        assert_eq!(adhoc.len(), 2);
        assert!(generated_files.is_empty());
    }

    #[test]
    fn a_static_pattern_rule_into_the_sdk_is_recorded() {
        // workbench/network/common/include stages 81 headers this way, the
        // whole BSD socket interface. The include root sits in the middle
        // field, not in the target, so matching only the target missed it and
        // netdb.h, netinet/in.h and proto/socket.h went absent unreported.
        let src = "\
INCLUDES      := $(call WILDCARD, *.h arpa/*.h)
DEST_INCLUDES := $(foreach f,$(INCLUDES),$(AROS_INCLUDES)/$(f))

$(DEST_INCLUDES) : $(AROS_INCLUDES)/% : $(SRCDIR)/$(CURDIR)/%
";
        let CopyIncludesScan { adhoc, .. } =
            collect_copy_includes(src, &PathBuf::from("workbench/network/common/include"));
        assert_eq!(adhoc.len(), 1, "adhoc: {adhoc:?}");
        assert_eq!(adhoc[0].root, "$(AROS_INCLUDES)/");
        assert_eq!(adhoc[0].dest, "%");
        assert!(adhoc[0].prereqs.contains("DEST_INCLUDES"));
    }

    #[test]
    fn the_udis86_itab_rule_is_modelled_not_reported() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../..");
        let rel = "arch/all-pc/udis86";
        let content = aros_common::read_source(&root.join(rel).join("mmakefile.src")).unwrap();
        let scan = collect_copy_includes(&content, std::path::Path::new(rel));

        assert_eq!(
            scan.skipped_script_outputs.len(),
            0,
            "{:?}",
            scan.skipped_script_outputs
        );
        assert_eq!(scan.script_outputs.len(), 1, "{:?}", scan.script_outputs);
        let decl = &scan.script_outputs[0];
        assert_eq!(
            decl.output,
            "${CMAKE_BINARY_DIR}/gen/arch/all-pc/udis86/libudis86/itab.c"
        );
        assert!(
            decl.script.ends_with("scripts/ud_itab.py"),
            "{}",
            decl.script
        );
        assert_eq!(decl.arguments.len(), 2, "{:?}", decl.arguments);
        assert!(decl.arguments[0].ends_with("docs/x86/optable.xml"));
        assert!(decl.arguments[1].ends_with("gen/arch/all-pc/udis86/libudis86"));
        // The rule stays out of the unmodelled report now that it is modelled.
        assert!(
            !scan
                .generated_files
                .iter()
                .any(|note| note.contains("itab.c")),
            "{:?}",
            scan.generated_files
        );
    }

    #[test]
    fn vc4_cle_stdout_generators_are_modelled_exactly() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../..");
        let rel = "arch/arm-native/soc/broadcom/2708/hidd/vc4gallium";
        let content = aros_common::read_source(&root.join(rel).join("mmakefile.src")).unwrap();
        let external = |name: &str| match name {
            "top_builddir" => Some("$(GENDIR)/workbench/libs/mesa/20.0.8".to_owned()),
            "top_srcdir" => Some("$(PORTSDIR)/mesa/mesa-20.0.8".to_owned()),
            _ => None,
        };
        let scan =
            collect_copy_includes_with_lookup(&content, std::path::Path::new(rel), Some(&external));

        assert!(
            !scan
                .skipped_script_outputs
                .iter()
                .any(|reason| reason.contains("v3d_packet")),
            "{:?}",
            scan.skipped_script_outputs
        );
        assert_eq!(scan.script_outputs.len(), 4, "{:?}", scan.script_outputs);
        let v33 = scan
            .script_outputs
            .iter()
            .find(|declaration| declaration.output.ends_with("v3d_packet_v33_pack.h"))
            .expect("v33 generator");
        assert!(v33.stdout);
        assert_eq!(v33.arguments.last().map(String::as_str), Some("33"));
        assert!(v33.script.ends_with("/src/broadcom/cle/gen_pack_header.py"));
        assert!(v33
            .depends
            .iter()
            .any(|path| path.ends_with("v3d_packet_v33.xml")));
        assert!(v33.working_directory.is_none());
        assert!(
            !scan
                .generated_files
                .iter()
                .any(|note| note.contains("v3d_packet")),
            "{:?}",
            scan.generated_files
        );
    }

    #[test]
    fn generated_owner_resolves_addprefix_and_filter() {
        let src = r"
GENERATED := one.c two.h
ROOT := $(GENDIR)/module
owner-generated : $(addprefix $(ROOT)/,$(filter %.h,$(GENERATED)))
$(ROOT)/two.h: $(SRCDIR)/generator.py
	$(PYTHON) $< > $@
";
        let scan = collect_copy_includes(src, Path::new("module"));
        assert_eq!(scan.script_outputs.len(), 1, "{:?}", scan.script_outputs);
        assert_eq!(scan.script_outputs[0].consumer_targets, ["owner-generated"]);
    }

    #[test]
    fn aboutaros_private_python_headers_are_modelled_with_their_consumer() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../..");
        let rel = "workbench/system/AboutAROS";
        let content = aros_common::read_source(&root.join(rel).join("mmakefile.src")).unwrap();
        let scan = collect_copy_includes(&content, std::path::Path::new(rel));

        assert_eq!(scan.script_outputs.len(), 3, "{:?}", scan.script_outputs);
        assert!(scan.skipped_script_outputs.is_empty());
        for declaration in &scan.script_outputs {
            assert!(
                declaration
                    .output
                    .starts_with("${AROS_BUILD_DIR}/workbench/system/AboutAROS/"),
                "{}",
                declaration.output
            );
            assert_eq!(declaration.consumer_source_stems, ["aboutaros"]);
            assert_eq!(declaration.arguments.last(), Some(&declaration.output));
        }
    }
}
