//! SDK header staging from `%copy_includes` declarations.
//!
//! Modules publish their public headers through `%copy_includes` (see
//! `config/make.tmpl`). The macro copies files into two include roots: the
//! target SDK (`$(AROS_INCLUDES)`, here `SDK/include`) and the host tool
//! include tree (`$(GENINCDIR)`). Without this step, headers referenced with a
//! category prefix such as `<oop/oop.h>` or `<hidd/hidd.h>` are unreachable,
//! because the prefix is part of the `#include` and no search path can supply
//! it.
//!
//! Destination semantics follow the macro exactly:
//!
//! * With `dir=<d>`, the source directory is `<mmakefile dir>/<d>` and only the
//!   base name is kept (`$(notdir ...)`), so `rom/hidds/kbd/include/keyboard.h`
//!   becomes `<root>/hidd/keyboard.h` for `path=hidd`.
//! * Without `dir=`, the source directory is the mmakefile's own directory and
//!   the listed relative path is appended verbatim.
//!
//! No declaration in the tree overrides `compiler=` or `includedir=`, so the
//! defaults (`target`, i.e. both roots) are the only case implemented. File
//! lists come from `$(call WILDCARD, <globs>)` in the majority of cases; the
//! globs are passed through to CMake rather than expanded here, so that adding
//! a header does not require anything to be regenerated by hand.

use crate::includes::{arg_value, arg_value_quoted};
use crate::make_vars::VarScope;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::Path;

type ExternalVarLookup<'a> = Option<&'a dyn Fn(&str) -> Option<String>>;

/// A hand-written Make rule that produces a header.
///
/// These cannot be transpiled generically, because the recipe is arbitrary
/// Make (the ones in the tree rename files, run generator tools, or use pattern
/// rules). They are reported so that a rule appearing upstream is noticed here
/// rather than as a missing header somewhere else entirely.
///
/// Two kinds of destination count. A header under `$(AROS_INCLUDES)` or
/// `$(GENINCDIR)` is staged into the SDK and visible tree-wide; one under
/// `$(GENDIR)` is private to its own module. Both fail the same way when
/// missing, so both are collected, and `root` says which kind it is.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdhocHeaderRule {
    /// mmakefile that declares the rule, relative to the source root.
    pub file: String,
    /// 1-based line number of the rule.
    pub line: usize,
    /// The include root the target sits in, verbatim, e.g. `$(GENINCDIR)/`.
    pub root: String,
    /// The rule's target, with the include root stripped.
    pub dest: String,
    /// The rule's prerequisites, verbatim.
    pub prereqs: String,
}

/// A hand-written SDK-header rule whose recipe is a safe, literal one-line
/// substitution.
///
/// This is intentionally narrower than arbitrary Make recipes.  The parser
/// accepts only `$(SED) -e 's/^literal/literal/' $< > $@`, records the exact
/// input/output and lets CMake own the real build-time transform.  Dependencies
/// and consumers are joined later from the complete target/fetch graph.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HeaderTransformDecl {
    /// Make target which owns the generated header.
    pub name: String,
    /// Declaring mmakefile, relative to the source root.
    pub file: String,
    /// 1-based line number of the output rule.
    pub line: usize,
    /// Concrete CMake input path.
    pub input: String,
    /// Concrete CMake output path below the build tree.
    pub output: String,
    /// Exact line prefix stripped from the anchored sed expression.
    pub match_text: String,
    /// Literal replacement text.
    pub replacement: String,
    /// Direct fetch targets owning the input, filled by the graph.
    #[serde(default)]
    pub dependencies: Vec<String>,
    /// Concrete compile targets whose port source tree contains the input.
    #[serde(default)]
    pub consumers: Vec<String>,
}

/// What one mmakefile yielded for header staging.
#[derive(Debug, Default)]
pub struct CopyIncludesScan {
    /// Resolved `%copy_includes` declarations.
    pub decls: Vec<CopyIncludesDecl>,
    /// `%copy_includes` directives that could not be resolved.
    pub skipped: Vec<String>,
    /// Hand-written rules producing a header.
    pub adhoc: Vec<AdhocHeaderRule>,
    /// Safe literal transforms promoted from hand-written header recipes.
    pub transforms: Vec<HeaderTransformDecl>,
    /// Hand-written rules under `$(GENDIR)` producing something other than a
    /// header (objects, ELF images, linker scripts). Reported only, since a
    /// missing one of these surfaces as a link or packaging failure rather
    /// than a missing include.
    pub generated_files: Vec<String>,
    /// Rules whose recipe runs an in-tree Python script to produce a file under
    /// `$(GENDIR)`.
    pub script_outputs: Vec<ScriptOutputDecl>,
    /// Rules that look like one and are not representable.
    pub skipped_script_outputs: Vec<String>,
}

/// A rule whose recipe runs an in-tree Python script to produce files under
/// `$(GENDIR)`.
///
/// `arch/all-pc/udis86/mmakefile.src:26` is the case that matters, and the only
/// one of the 21 rules in the generated-file report with this shape: the other
/// twenty are windres compiles for mingw32, the m68k-amiga ROM link chain, two
/// plain compiles into `$(GENDIR)`, the stdc Unicode tables and two copies. One
/// modelled form would not have covered them, so this one is deliberately
/// narrow and everything else stays reported.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ScriptOutputDecl {
    /// Directory of the declaring mmakefile, relative to the source root.
    pub directory: String,
    /// The file the rule declares, as a CMake path.
    pub output: String,
    /// The script the recipe runs, as a CMake path.
    pub script: String,
    /// Literal arguments after the script, as CMake paths or plain words.
    pub arguments: Vec<String>,
    /// The rule's prerequisites, as CMake paths. Order-only ones are dropped:
    /// they are directories, which CMake creates itself.
    pub depends: Vec<String>,
}

/// One resolved `%copy_includes` declaration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CopyIncludesDecl {
    /// `mmake=`: the staging target which owns these copies.
    #[serde(default = "default_copy_target")]
    pub name: String,
    /// Subdirectory under each include root (`path=`).
    pub dest: String,
    /// Source directory relative to the source root.
    pub source_dir: String,
    /// Glob patterns or explicit file names, relative to `source_dir`.
    pub patterns: Vec<String>,
    /// File names selected by the source list but deliberately not staged.
    ///
    /// MetaMake commonly expresses this as `$(filter-out name.h,$(call
    /// WILDCARD,...))`.  Retaining it separately is important for generated
    /// headers: FreeType, for example, replaces `ftoption.h` with its target
    /// configuration instead of copying the upstream default.
    #[serde(default)]
    pub excludes: Vec<String>,
    /// Whether to strip directories from the copied names (`dir=` was given).
    pub flatten: bool,
}

fn default_copy_target() -> String {
    "includes-copy".to_owned()
}

fn split_assignment(line: &str) -> Option<(&str, &str, bool)> {
    if let Some((l, r)) = line.split_once(":=") {
        return Some((l, r, false));
    }
    if let Some((l, r)) = line.split_once("+=") {
        return Some((l, r, true));
    }
    let (l, r) = line.split_once('=')?;
    if l.contains(':') || l.is_empty() {
        return None;
    }
    Some((l, r, false))
}

/// Make variables that map onto a CMake location.
///
/// `%fetch` unpacks third-party sources under the ports directory, and a module
/// then stages their headers from there: `arch/all-native/acpica` publishes
/// `$(ACPICA_INCLUDES)/*.h` as `acpica/*.h`. Without this mapping the
/// declaration cannot be resolved and `<acpica/actypes.h>` never reaches the
/// SDK, which is what the ACPI-dependent drivers fail on.
fn map_var(name: &str) -> Option<&'static str> {
    match name {
        "SRCDIR" | "TOP" => Some("${CMAKE_SOURCE_DIR}"),
        "PORTSDIR" => Some("${AROS_PORTS_DIR}"),
        "PORTSSOURCEDIR" => Some("${AROS_PORTS_SOURCE_DIR}"),
        // Same mapping as includes.rs: the generated per-module tree lives
        // under <build>/gen, not at the build root.
        "GENDIR" | "OBJDIR" => Some("${CMAKE_BINARY_DIR}/gen"),
        "GENINCDIR" => Some("${CMAKE_BINARY_DIR}/GENINCDIR"),
        _ => None,
    }
}

/// Substitutes `$(VAR)` references from `vars`, leaving unknown ones in place.
fn substitute(
    raw: &str,
    vars: &HashMap<String, String>,
    external: ExternalVarLookup<'_>,
    depth: usize,
) -> String {
    if depth == 0 || !raw.contains("$(") {
        return raw.to_owned();
    }
    let mut out = String::with_capacity(raw.len());
    let mut rest = raw;
    while let Some(start) = rest.find("$(") {
        out.push_str(&rest[..start]);
        let Some(end) = matching_paren(rest, start + 1) else {
            out.push_str(&rest[start..]);
            return out;
        };
        let name = &rest[start + 2..end];
        // `$(call WILDCARD, ...)` is handled later, keep it verbatim.
        if name.starts_with("call ") || name.contains(' ') {
            out.push_str(&rest[start..=end]);
        } else if let Some(m) = map_var(name) {
            out.push_str(m);
        } else if let Some(v) = vars
            .get(name)
            .cloned()
            .or_else(|| external.and_then(|f| f(name)))
        {
            out.push_str(&substitute(&v, vars, external, depth - 1));
        } else {
            out.push_str(&rest[start..=end]);
        }
        rest = &rest[end + 1..];
    }
    out.push_str(rest);
    out
}

/// Finds the `)` matching the `$(` that starts at `open`, counting nesting.
fn matching_paren(text: &str, open: usize) -> Option<usize> {
    let bytes = text.as_bytes();
    let mut depth = 0usize;
    let mut i = open;
    while i < bytes.len() {
        if bytes[i] == b'(' {
            depth += 1;
        } else if bytes[i] == b')' {
            depth -= 1;
            if depth == 0 {
                return Some(i);
            }
        }
        i += 1;
    }
    None
}

/// Expands a bracket character class, e.g. `*.[hi]` into `*.h` and `*.i`.
///
/// CMake's `file(GLOB)` does not understand character classes, so they are
/// turned into separate patterns here.
fn expand_char_classes(pattern: &str) -> Vec<String> {
    let Some(open) = pattern.find('[') else {
        return vec![pattern.to_owned()];
    };
    let Some(close) = pattern[open..].find(']').map(|i| i + open) else {
        return vec![pattern.to_owned()];
    };
    let prefix = &pattern[..open];
    let suffix = &pattern[close + 1..];
    let mut out = Vec::new();
    for ch in pattern[open + 1..close].chars() {
        for tail in expand_char_classes(suffix) {
            out.push(format!("{prefix}{ch}{tail}"));
        }
    }
    if out.is_empty() {
        vec![pattern.to_owned()]
    } else {
        out
    }
}

/// Extracts the file list from an `includes=` value.
///
/// Returns `None` when the list still references a Make variable we cannot
/// resolve, which is the case for the third-party ports whose sources live
/// outside the tree.
#[derive(Debug, Default)]
struct ResolvedFileList {
    patterns: Vec<String>,
    excludes: Vec<String>,
}

fn outer_make_function<'a>(expression: &'a str, name: &str) -> Option<&'a str> {
    let prefix = format!("$({name}");
    let remainder = expression.strip_prefix(&prefix)?;
    if !remainder.chars().next().is_some_and(char::is_whitespace) {
        return None;
    }
    let end = matching_paren(expression, 1)?;
    if end + 1 != expression.len() {
        return None;
    }
    Some(expression[prefix.len()..end].trim())
}

fn split_top_level_comma(expression: &str) -> Option<(&str, &str)> {
    let mut depth = 0usize;
    for (index, ch) in expression.char_indices() {
        match ch {
            '(' => depth += 1,
            ')' => depth = depth.checked_sub(1)?,
            ',' if depth == 0 => return Some((&expression[..index], &expression[index + 1..])),
            _ => {}
        }
    }
    None
}

fn resolve_file_list(
    raw: &str,
    vars: &HashMap<String, String>,
    external: ExternalVarLookup<'_>,
) -> Option<ResolvedFileList> {
    let substituted = substitute(raw, vars, external, 8);
    resolve_file_list_expression(substituted.trim(), vars, external)
}

fn resolve_file_list_expression(
    expression: &str,
    vars: &HashMap<String, String>,
    external: ExternalVarLookup<'_>,
) -> Option<ResolvedFileList> {
    if let Some(arguments) = outer_make_function(expression, "notdir") {
        let mut resolved = resolve_file_list(arguments, vars, external)?;
        for list in [&mut resolved.patterns, &mut resolved.excludes] {
            for entry in list.iter_mut() {
                *entry = entry.rsplit('/').next().unwrap_or(entry).to_owned();
            }
        }
        return Some(resolved);
    }

    if let Some(arguments) = outer_make_function(expression, "filter-out") {
        let (filters, words) = split_top_level_comma(arguments)?;
        let filters = resolve_file_list(filters.trim(), vars, external)?;
        // Pattern filters would need to be evaluated against the fetched
        // directory at build time.  Keep this deliberately bounded to the
        // literal exclusion form that the header publisher uses; anything
        // broader remains an explicit skipped declaration rather than a guess.
        if filters
            .patterns
            .iter()
            .chain(filters.excludes.iter())
            .any(|entry| entry.contains(['*', '?', '[', '%']))
        {
            return None;
        }
        let mut resolved = resolve_file_list(words.trim(), vars, external)?;
        resolved.excludes.extend(filters.patterns);
        resolved.excludes.extend(filters.excludes);
        resolved.excludes.sort();
        resolved.excludes.dedup();
        return Some(resolved);
    }

    let mut resolved = ResolvedFileList::default();
    let mut rest = expression;

    // Pull out every `$(call WILDCARD, <globs>)` group. The closing paren must
    // be matched with nesting in mind: `$(call WILDCARD, $(X)/*.h)` would
    // otherwise be cut short at the inner `)`.
    while let Some(start) = rest.find("$(call") {
        let head = &rest[..start];
        push_plain_tokens(head, &mut resolved.patterns)?;
        // `matching_paren` expects to start on the `(`.
        let end = matching_paren(rest, start + 1)?;
        let inner = &rest[start..end];
        let globs = inner.split_once(',').map_or("", |(_, g)| g);
        for g in globs.split_whitespace() {
            // The glob may itself be rooted in a variable, as in
            // `$(call WILDCARD, $(ACPICA_INCLUDES)/*.h)`. Substitute first; the
            // directory part is dropped later by the `dir=` flattening, so only
            // the trailing pattern matters.
            let g = substitute(g, vars, external, 8);
            // A Make construct that survived substitution means we cannot know
            // what this matches; skip the declaration rather than guess.
            if g.contains("$(") {
                return None;
            }
            resolved.patterns.extend(expand_char_classes(&g));
        }
        rest = &rest[end + 1..];
    }
    push_plain_tokens(rest, &mut resolved.patterns)?;

    if resolved.patterns.is_empty() {
        return None;
    }
    Some(resolved)
}

/// Adds literal file names, rejecting anything still holding a Make variable.
fn push_plain_tokens(text: &str, out: &mut Vec<String>) -> Option<()> {
    for tok in text.split_whitespace() {
        if tok.contains('$') {
            return None;
        }
        out.extend(expand_char_classes(tok));
    }
    Some(())
}

/// Parses the header-staging directives of one `mmakefile.src`.
///
/// Returns the resolved `%copy_includes` declarations, the ones that had to be
/// skipped, and every hand-written rule that writes into an include root.
///
/// Evaluation is sequential rather than "collect all variables, then all
/// directives": several mmakefiles reassign `INCLUDE_FILES` between two
/// `%copy_includes` calls (for example `arch/all-native/acpica`), and Make
/// resolves each directive against the value in force at that point.
#[must_use]
pub fn collect_copy_includes(content: &str, rel_dir: &Path) -> CopyIncludesScan {
    collect_copy_includes_with_lookup(content, rel_dir, None)
}

/// Parses `%copy_includes` using an additional target-selected Make scope.
///
/// The declaration remains sequential: assignments in the mmakefile override
/// this fallback at the point where they occur.  The fallback supplies values
/// from source-tree configuration files included by the mmakefile, which is
/// how ports such as Mesa define their archive and source directories.
#[must_use]
pub(crate) fn collect_copy_includes_with_scope(
    content: &str,
    rel_dir: &Path,
    scope: &VarScope,
) -> CopyIncludesScan {
    let external = |name: &str| scope.raw_at(name, usize::MAX);
    collect_copy_includes_with_lookup(content, rel_dir, Some(&external))
}

fn collect_copy_includes_with_lookup(
    content: &str,
    rel_dir: &Path,
    external: ExternalVarLookup<'_>,
) -> CopyIncludesScan {
    let base = rel_dir.to_string_lossy().replace('\\', "/");
    let mmakefile = if base.is_empty() {
        "mmakefile.src".to_owned()
    } else {
        format!("{base}/mmakefile.src")
    };

    let mut vars: HashMap<String, String> = HashMap::new();
    // $(CURDIR) is the declaring mmakefile's directory. Two staging rules read
    // their sources through it, reqtools' amigaincludesforgcc tree and udis86's
    // generated itab.h, and without it the path kept the literal "$(CURDIR)"
    // and matched nothing.
    if !base.is_empty() {
        vars.insert("CURDIR".to_owned(), base.clone());
    }
    let mut decls = Vec::new();
    let mut skipped = Vec::new();
    let mut adhoc = Vec::new();
    let mut transforms = Vec::new();
    let mut generated_files = Vec::new();
    let mut script_outputs: Vec<ScriptOutputDecl> = Vec::new();
    let mut skipped_script_outputs: Vec<String> = Vec::new();

    let lines: Vec<&str> = content.lines().collect();
    let output_owners = collect_header_output_owners(&lines);
    let mut i = 0usize;
    // Tracks a variable assignment continued over several lines.
    let mut pending_var: Option<String> = None;

    while i < lines.len() {
        let line = lines[i];
        let line_no = i + 1;
        let trimmed = line.trim();
        let continues = trimmed.ends_with('\\');
        let payload = trimmed.trim_end_matches('\\').trim();

        if let Some(name) = pending_var.take() {
            let entry = vars.entry(name.clone()).or_default();
            if !entry.is_empty() {
                entry.push(' ');
            }
            entry.push_str(payload);
            if continues {
                pending_var = Some(name);
            }
            i += 1;
            continue;
        }

        if trimmed.starts_with('#') {
            i += 1;
            continue;
        }

        if trimmed.starts_with("%copy_includes") {
            // Join continuation lines into one directive body.
            let mut body = payload.to_owned();
            let mut j = i;
            let mut cont = continues;
            while cont {
                j += 1;
                let Some(next) = lines.get(j) else { break };
                let t = next.trim();
                cont = t.ends_with('\\');
                body.push(' ');
                body.push_str(t.trim_end_matches('\\').trim());
            }
            resolve_directive(&body, &base, &vars, external, &mut decls, &mut skipped);
            i = j + 1;
            continue;
        }

        if trimmed.starts_with('%') {
            i += 1;
            continue;
        }

        // A rule whose recipe runs an in-tree Python script. Tried before the
        // generic shape so a modelled rule is not also reported as unmodelled.
        match parse_script_output(&lines, i, &base, &vars, external) {
            Some(Ok(decl)) => {
                script_outputs.push(decl);
                i += 1;
                continue;
            }
            Some(Err(reason)) => {
                skipped_script_outputs.push(reason);
                i += 1;
                continue;
            }
            None => {}
        }

        // A hand-written rule writing into an include root, e.g.
        //   $(AROS_INCLUDES)/hidd/pci.h: include/pci_hidd.h
        match parse_adhoc_rule(payload, &mmakefile, line_no) {
            Some(ParsedRule::Header(rule)) => {
                if let Some(transform) =
                    parse_header_transform(&rule, &lines, i, &base, &vars, external, &output_owners)
                {
                    transforms.push(transform);
                } else {
                    adhoc.push(rule);
                }
                i += 1;
                continue;
            }
            Some(ParsedRule::Other(note)) => {
                generated_files.push(note);
                i += 1;
                continue;
            }
            None => {}
        }

        if let Some((lhs, rhs, append)) = split_assignment(payload) {
            let name = lhs.trim().to_owned();
            if !name.is_empty() && !name.contains(char::is_whitespace) {
                let entry = vars.entry(name.clone()).or_default();
                if append {
                    if !entry.is_empty() {
                        entry.push(' ');
                    }
                } else {
                    entry.clear();
                }
                entry.push_str(rhs.trim());
                if continues {
                    pending_var = Some(name);
                }
            }
        }

        i += 1;
    }

    CopyIncludesScan {
        decls,
        skipped,
        adhoc,
        transforms,
        generated_files,
        script_outputs,
        skipped_script_outputs,
    }
}

/// Maps a concrete generated-output token to the simple Make target which
/// owns it, for example `workbench-libs-z-geninc : $(AROS_INCLUDES)/zconf.h`.
fn collect_header_output_owners(lines: &[&str]) -> HashMap<String, String> {
    let mut owners = HashMap::new();
    for raw in lines {
        if raw.starts_with('\t') {
            continue;
        }
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') || line.contains('=') {
            continue;
        }
        let Some((target, prereqs)) = line.split_once(':') else {
            continue;
        };
        let target = target.trim();
        if target.is_empty()
            || target.contains(char::is_whitespace)
            || target.contains(['$', '/', '%'])
        {
            continue;
        }
        let mut words = prereqs.split_whitespace();
        let Some(output) = words.next() else { continue };
        if words.next().is_some()
            || !["$(AROS_INCLUDES)/", "$(GENINCDIR)/", "$(GENDIR)/"]
                .iter()
                .any(|root| output.starts_with(root))
        {
            continue;
        }
        owners
            .entry(output.to_owned())
            .or_insert_with(|| target.to_owned());
    }
    owners
}

fn resolve_transform_path(
    raw: &str,
    base: &str,
    vars: &HashMap<String, String>,
    external: ExternalVarLookup<'_>,
    output: bool,
) -> Option<String> {
    let mut rendered = substitute(raw, vars, external, 8);
    rendered = rendered
        .replace("$(AROS_INCLUDES)", "${AROS_SDK_INCLUDE_DIR}")
        .replace("$(GENINCDIR)", "${AROS_GENINC_DIR}")
        .replace("$(GENDIR)", "${CMAKE_BINARY_DIR}/gen")
        .replace("$(SRCDIR)", "${CMAKE_SOURCE_DIR}")
        .replace("$(PORTSDIR)", "${AROS_PORTS_DIR}");
    if rendered.contains("$(") || rendered.contains(';') || rendered.contains('\n') {
        return None;
    }
    if output {
        if !rendered.starts_with("${AROS_SDK_INCLUDE_DIR}/")
            && !rendered.starts_with("${AROS_GENINC_DIR}/")
            && !rendered.starts_with("${CMAKE_BINARY_DIR}/gen/")
        {
            return None;
        }
    } else if !rendered.starts_with("${") && !rendered.starts_with('/') {
        rendered = if base.is_empty() {
            format!("${{CMAKE_SOURCE_DIR}}/{rendered}")
        } else {
            format!("${{CMAKE_SOURCE_DIR}}/{base}/{rendered}")
        };
    }
    Some(rendered)
}

/// Parses a non-regex sed field up to `delimiter`, unescaping only the
/// delimiter and a literal backslash. Other backslash escapes would change
/// sed semantics and therefore make the recipe ineligible.
fn parse_literal_sed_field(chars: &[char], at: &mut usize, delimiter: char) -> Option<String> {
    let mut value = String::new();
    while *at < chars.len() {
        let ch = chars[*at];
        *at += 1;
        if ch == delimiter {
            return Some(value);
        }
        if ch == '\\' {
            let escaped = *chars.get(*at)?;
            if escaped != delimiter && escaped != '\\' {
                return None;
            }
            value.push(escaped);
            *at += 1;
        } else {
            value.push(ch);
        }
    }
    None
}

fn safe_mkdir_guard(command: &str) -> bool {
    let Some(rest) = command.strip_prefix("@$(IF) $(TEST) ! -d ") else {
        return false;
    };
    let Some((checked, rest)) = rest.split_once(" ; then $(MKDIR) ") else {
        return false;
    };
    let Some((created, tail)) = rest.split_once(" ; else $(NOP) ; fi") else {
        return false;
    };
    !checked.is_empty()
        && checked == created
        && tail.is_empty()
        && checked.chars().all(|character| {
            character.is_ascii_alphanumeric()
                || matches!(
                    character,
                    '_' | '-' | '.' | '/' | '$' | '(' | ')' | '{' | '}'
                )
        })
}

fn literal_sed_substitution(commands: &[String]) -> Option<(String, String)> {
    let recipe = match commands {
        [sed] => sed.as_str(),
        [guard, sed] if safe_mkdir_guard(guard) => sed.as_str(),
        _ => return None,
    };
    let body = recipe.strip_prefix("@$(SED) -e 's")?;
    if body.contains('\n') {
        return None;
    }
    let chars: Vec<char> = body.chars().collect();
    let delimiter = *chars.first()?;
    if delimiter.is_ascii_alphanumeric() || delimiter.is_whitespace() || delimiter == '\\' {
        return None;
    }
    let mut at = 1usize;
    let pattern = parse_literal_sed_field(&chars, &mut at, delimiter)?;
    let replacement = parse_literal_sed_field(&chars, &mut at, delimiter)?;
    // Only an anchored, literal basic-regex pattern and no sed flags.  BRE
    // parentheses are literal; all actual metacharacters are rejected.
    let match_text = pattern.strip_prefix('^')?;
    if match_text.is_empty()
        || match_text
            .chars()
            .any(|ch| matches!(ch, '.' | '*' | '[' | ']' | '$' | '\\'))
    {
        return None;
    }
    if replacement.contains(['&', '\\']) {
        // Both have special meaning in a sed replacement and therefore are
        // not equivalent to CMake's literal replacement operation.
        return None;
    }
    let tail: String = chars[at..].iter().collect();
    if tail != "' $< > $@" {
        return None;
    }
    Some((match_text.to_owned(), replacement))
}

fn parse_header_transform(
    rule: &AdhocHeaderRule,
    lines: &[&str],
    rule_index: usize,
    base: &str,
    vars: &HashMap<String, String>,
    external: ExternalVarLookup<'_>,
    output_owners: &HashMap<String, String>,
) -> Option<HeaderTransformDecl> {
    let raw_output = format!("{}/{}", rule.root.trim_end_matches('/'), rule.dest);
    let owner = output_owners.get(&raw_output)?.clone();
    let mut prereqs = rule.prereqs.split_whitespace();
    let raw_input = prereqs.next()?;
    if prereqs.next().is_some() || raw_input.contains(['%', '*', '?']) {
        return None;
    }

    let mut commands = Vec::new();
    let mut command = String::new();
    for line in lines.iter().skip(rule_index + 1) {
        if !line.starts_with('\t') {
            break;
        }
        let trimmed = line.trim();
        let continued = trimmed.ends_with('\\');
        if !command.is_empty() {
            command.push(' ');
        }
        command.push_str(trimmed.trim_end_matches('\\').trim());
        if !continued {
            commands.push(std::mem::take(&mut command));
        }
    }
    if !command.is_empty() {
        return None;
    }
    let (match_text, replacement) = literal_sed_substitution(&commands)?;
    let input = resolve_transform_path(raw_input, base, vars, external, false)?;
    let output = resolve_transform_path(&raw_output, base, vars, external, true)?;

    Some(HeaderTransformDecl {
        name: owner,
        file: rule.file.clone(),
        line: rule.line,
        input,
        output,
        match_text,
        replacement,
        dependencies: Vec::new(),
        consumers: Vec::new(),
    })
}

/// A hand-written rule, classified by what it produces.
enum ParsedRule {
    /// Produces a header, so a missing one breaks a compile.
    Header(AdhocHeaderRule),
    /// Produces something else under `$(GENDIR)`; carries a ready-to-report
    /// description.
    Other(String),
}

/// Recognises a Make rule whose target lives in one of the generated roots.
///
/// `$(GENDIR)/` is included because module-private generated headers live
/// there, for example `$(GENDIR)/$(CURDIR)/dos/errorlist.h`. Leaving it out
/// meant such a rule was silently absent and only surfaced as an undeclared
/// identifier in the module that includes it.
fn parse_adhoc_rule(line: &str, mmakefile: &str, line_no: usize) -> Option<ParsedRule> {
    const ROOTS: [&str; 3] = ["$(AROS_INCLUDES)/", "$(GENINCDIR)/", "$(GENDIR)/"];

    // A rule, not a variable assignment.
    let (target, prereqs) = line.split_once(':')?;
    if target.contains('=') || prereqs.starts_with('=') {
        return None;
    }

    // Two shapes reach an include root. The plain one names it in the target:
    //
    //     $(AROS_INCLUDES)/hidd/pci.h : include/pci_hidd.h
    //
    // A static pattern rule names it in the middle field instead, and the
    // target is a variable holding the file list:
    //
    //     $(DEST_INCLUDES) : $(AROS_INCLUDES)/% : $(SRCDIR)/$(CURDIR)/%
    //
    // workbench/network/common/include stages 81 headers that way, the whole
    // BSD socket interface, and matching only the first shape left it
    // unreported: netdb.h, netinet/in.h and proto/socket.h went missing with
    // nothing to say why.
    let (root, dest, prereqs) = if let Some(r) = ROOTS.iter().find(|r| line.starts_with(**r)) {
        (
            *r,
            target[r.len()..].trim().to_owned(),
            prereqs.trim().trim_start_matches(':').trim().to_owned(),
        )
    } else {
        let (pattern, source) = prereqs.split_once(':')?;
        let pattern = pattern.trim();
        let r = ROOTS.iter().find(|r| pattern.starts_with(**r))?;
        (
            *r,
            pattern[r.len()..].trim().to_owned(),
            format!("{} (files: {})", source.trim(), target.trim()),
        )
    };

    // $(AROS_INCLUDES) and $(GENINCDIR) are include roots, so everything
    // landing there is a header whatever its name, including pattern rules and
    // variable-named targets. $(GENDIR) holds every kind of generated file, so
    // there the suffix decides.
    let extension = Path::new(&dest)
        .extension()
        .and_then(|value| value.to_str());
    let is_header = root != "$(GENDIR)/" || matches!(extension, Some("h" | "hpp"));
    if is_header {
        return Some(ParsedRule::Header(AdhocHeaderRule {
            file: mmakefile.to_owned(),
            line: line_no,
            root: root.to_owned(),
            dest,
            prereqs,
        }));
    }

    // Rules that create a directory, or a Make dependency file, carry no build
    // output of their own. CMake creates output directories itself and tracks
    // header dependencies through the compiler, so these cannot go missing and
    // would only dilute the report.
    let is_bookkeeping = extension == Some("d")
        || !dest.contains('.')
        || dest.ends_with(".includes-generated")
        || dest.ends_with(".stubs-generated");
    if is_bookkeeping {
        return None;
    }

    Some(ParsedRule::Other(format!(
        "{root}{dest} <- {prereqs}  ({mmakefile}:{line_no})"
    )))
}

/// A rule of the shape `$(GENDIR)/... : <inputs>` whose single recipe line is
/// `$(PYTHON) <script> <args>`.
///
/// Returns `None` when the rule is not that shape, so the caller falls back to
/// reporting it, and `Err` when it is that shape and still cannot be used.
fn parse_script_output(
    lines: &[&str],
    index: usize,
    base: &str,
    vars: &HashMap<String, String>,
    external: ExternalVarLookup<'_>,
) -> Option<Result<ScriptOutputDecl, String>> {
    // The rule line continues while it ends in a backslash; the recipe starts
    // after the last continuation. The general scan does not join these, unlike
    // the %copy_includes branch, so it has to be done here.
    let mut joined = String::new();
    let mut cursor = index;
    loop {
        let line = lines.get(cursor)?;
        let trimmed = line.trim_end();
        joined.push_str(trimmed.trim_end_matches('\\').trim_end());
        cursor += 1;
        if !trimmed.ends_with('\\') {
            break;
        }
        joined.push(' ');
    }

    let (target, prereqs) = joined.split_once(':')?;
    let target = target.trim();
    if !target.starts_with("$(GENDIR)/") {
        return None;
    }

    let recipe: Vec<&str> = lines[cursor..]
        .iter()
        .take_while(|line| line.starts_with('\t'))
        .map(|line| line.trim())
        .collect();
    // `$(PYTHON)` before substitution, so the shape is what the reference
    // states rather than whatever a variable happens to expand to.
    if recipe.len() != 1 || !recipe[0].starts_with("$(PYTHON)") {
        return None;
    }

    let resolve = |raw: &str| -> Result<String, String> {
        let value = substitute(raw, vars, external, 8);
        if value.contains("$(") {
            return Err(format!("`{raw}` does not resolve"));
        }
        if value.contains([';', '&', '|', '>', '<', '`', '"', '\'']) {
            return Err(format!("`{value}` is not a plain word"));
        }
        Ok(value)
    };

    let output = match resolve(target) {
        Ok(value) => value,
        Err(reason) => return Some(Err(format!("{base}: target {reason}"))),
    };

    // The order-only half of the prerequisites is a directory, which CMake
    // creates itself.
    let ordered = prereqs.split('|').next().unwrap_or_default();
    let mut depends = Vec::new();
    for raw in ordered.split_whitespace() {
        match resolve(raw) {
            Ok(value) => depends.push(value),
            Err(reason) => return Some(Err(format!("{base}: prerequisite {reason}"))),
        }
    }

    let mut words = recipe[0]
        .strip_prefix("$(PYTHON)")
        .unwrap_or_default()
        .split_whitespace();
    let Some(raw_script) = words.next() else {
        return Some(Err(format!("{base}: {output} has no script to run")));
    };
    let script = match resolve(raw_script) {
        Ok(value) => value,
        Err(reason) => return Some(Err(format!("{base}: script {reason}"))),
    };
    let mut arguments = Vec::new();
    for raw in words {
        match resolve(raw) {
            Ok(value) => arguments.push(value),
            Err(reason) => return Some(Err(format!("{base}: argument {reason}"))),
        }
    }

    Some(Ok(ScriptOutputDecl {
        directory: base.to_owned(),
        output,
        script,
        arguments,
        depends,
    }))
}

/// Resolves one `%copy_includes` directive against the current variable state.
fn resolve_directive(
    body: &str,
    base: &str,
    vars: &HashMap<String, String>,
    external: ExternalVarLookup<'_>,
    decls: &mut Vec<CopyIncludesDecl>,
    skipped: &mut Vec<String>,
) {
    let name = arg_value(body, "mmake").unwrap_or_else(default_copy_target);
    let dest = arg_value(body, "path").unwrap_or_else(|| ".".to_owned());
    let dir = arg_value(body, "dir");

    let raw_includes = arg_value_quoted(body, "includes")
        .or_else(|| arg_value(body, "includes"))
        .unwrap_or_else(|| "$(INCLUDE_FILES)".to_owned());

    let Some(resolved) = resolve_file_list(&raw_includes, vars, external) else {
        skipped.push(format!("{base}: path={dest} includes={raw_includes}"));
        return;
    };

    let (source_dir, flatten) = match dir {
        Some(d) => {
            let d = substitute(&d, vars, external, 8);
            if d.starts_with("${") {
                // An absolute CMake location, e.g. a directory inside a port
                // unpacked by %fetch.
                (d, true)
            } else if d.contains('$') || d.starts_with('/') {
                skipped.push(format!("{base}: path={dest} dir={d}"));
                return;
            } else {
                (join_rel(base, &d), true)
            }
        }
        None => (base.to_owned(), false),
    };

    let patterns = if flatten {
        resolved
            .patterns
            .iter()
            .map(|p| p.rsplit('/').next().unwrap_or(p).to_owned())
            .collect()
    } else {
        resolved.patterns
    };
    let excludes = if flatten {
        resolved
            .excludes
            .iter()
            .map(|p| p.rsplit('/').next().unwrap_or(p).to_owned())
            .collect()
    } else {
        resolved.excludes
    };
    if patterns.iter().any(|p: &String| p.contains("$(")) {
        skipped.push(format!("{base}: path={dest} has an unresolved glob"));
        return;
    }

    decls.push(CopyIncludesDecl {
        name,
        dest,
        source_dir,
        patterns,
        excludes,
        flatten,
    });
}

/// Joins two source-relative path fragments, collapsing `..` segments.
fn join_rel(base: &str, add: &str) -> String {
    let mut parts: Vec<&str> = base.split('/').filter(|s| !s.is_empty()).collect();
    for seg in add.split('/') {
        match seg {
            "" | "." => {}
            ".." => {
                parts.pop();
            }
            other => parts.push(other),
        }
    }
    parts.join("/")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn wildcard_with_dir_flattens_to_basenames() {
        // rom/hidds/kbd/mmakefile.src
        let src = "INCLUDE_FILES := $(call WILDCARD, include/*.h)\n%copy_includes path=hidd dir=include\n";
        let CopyIncludesScan { decls, skipped, .. } =
            collect_copy_includes(src, &PathBuf::from("rom/hidds/kbd"));
        assert!(skipped.is_empty());
        assert_eq!(decls.len(), 1);
        assert_eq!(decls[0].dest, "hidd");
        assert_eq!(decls[0].source_dir, "rom/hidds/kbd/include");
        assert_eq!(decls[0].patterns, vec!["*.h"]);
        assert!(decls[0].flatten);
    }

    #[test]
    fn explicit_name_without_dir_keeps_relative_path() {
        // workbench/classes/zune/iconimage/mmakefile.src
        let src = "INCLUDE_FILES := iconimage.h\n%copy_includes path=zune\n";
        let CopyIncludesScan { decls, .. } =
            collect_copy_includes(src, &PathBuf::from("workbench/classes/zune/iconimage"));
        assert_eq!(decls[0].dest, "zune");
        assert_eq!(decls[0].source_dir, "workbench/classes/zune/iconimage");
        assert_eq!(decls[0].patterns, vec!["iconimage.h"]);
        assert!(!decls[0].flatten);
    }

    #[test]
    fn explicit_dot_destination_reaches_cmake_as_the_include_root() {
        let src = "INCLUDE_FILES := zlib.h\n%copy_includes mmake=z-includes path=. dir=include\n";
        let CopyIncludesScan { decls, skipped, .. } =
            collect_copy_includes(src, &PathBuf::from("workbench/libs/z"));
        assert!(skipped.is_empty());
        assert_eq!(decls.len(), 1);
        assert_eq!(decls[0].name, "z-includes");
        assert_eq!(decls[0].dest, ".");
        assert_eq!(decls[0].patterns, ["zlib.h"]);
    }

    #[test]
    fn oop_case_maps_to_sdk_prefix() {
        // rom/oop/mmakefile.src, the header that blocked 49 compilations.
        let src =
            "INCLUDE_FILES := $(call WILDCARD, include/*.h)\n%copy_includes path=oop dir=include\n";
        let CopyIncludesScan { decls, .. } = collect_copy_includes(src, &PathBuf::from("rom/oop"));
        assert_eq!(decls[0].dest, "oop");
        assert_eq!(decls[0].source_dir, "rom/oop/include");
    }

    #[test]
    fn expands_character_classes_for_cmake_glob() {
        let src = "INCLUDE_FILES := $(call WILDCARD, *.[hi] aros/*.[hi])\n%copy_includes path=x\n";
        let CopyIncludesScan { decls, .. } = collect_copy_includes(src, &PathBuf::from("d"));
        let p = &decls[0].patterns;
        assert!(p.contains(&"*.h".to_owned()));
        assert!(p.contains(&"*.i".to_owned()));
        assert!(p.contains(&"aros/*.h".to_owned()));
        assert!(p.contains(&"aros/*.i".to_owned()));
    }

    #[test]
    fn inline_include_list_is_honoured() {
        let src = "%copy_includes path=libraries includes=\"speechcore.h aros_resource.h\"\n";
        let CopyIncludesScan { decls, .. } = collect_copy_includes(src, &PathBuf::from("d"));
        assert_eq!(decls[0].patterns, vec!["speechcore.h", "aros_resource.h"]);
    }

    #[test]
    fn unresolvable_third_party_dir_is_skipped_not_guessed() {
        let src = "INCLUDE_FILES := $(call WILDCARD, *.h)\n%copy_includes path=freetype dir=$(FT2SRCDIR)/include\n";
        let CopyIncludesScan { decls, skipped, .. } =
            collect_copy_includes(src, &PathBuf::from("d"));
        assert!(decls.is_empty());
        assert_eq!(skipped.len(), 1);
        assert!(skipped[0].contains("FT2SRCDIR"));
    }

    #[test]
    fn unresolvable_include_list_is_skipped() {
        let src = "%copy_includes path=x dir=include\n";
        let CopyIncludesScan { decls, skipped, .. } =
            collect_copy_includes(src, &PathBuf::from("d"));
        assert!(
            decls.is_empty(),
            "no INCLUDE_FILES defined, nothing to copy"
        );
        assert_eq!(skipped.len(), 1);
    }

    #[test]
    fn parent_relative_dir_resolves() {
        let src = "INCLUDE_FILES := ../include/mui/BetterString_mcc.h\n%copy_includes path=mui dir=../include/mui\n";
        let CopyIncludesScan { decls, .. } =
            collect_copy_includes(src, &PathBuf::from("workbench/classes/zune/betterstring"));
        assert_eq!(decls[0].source_dir, "workbench/classes/zune/include/mui");
        assert_eq!(decls[0].patterns, vec!["BetterString_mcc.h"]);
    }

    #[test]
    fn reassigned_include_files_uses_value_in_force_at_the_directive() {
        // arch/all-native/acpica/mmakefile.src reassigns INCLUDE_FILES between
        // the two directives; Make resolves each against the current value.
        let src = "\
INCLUDE_FILES := $(call WILDCARD, include/*.h)
%copy_includes path=libraries dir=include
INCLUDE_FILES = $(call WILDCARD, $(ACPICA_INCLUDES)/*.h)
%copy_includes mmake=acpica-includes-copy path=acpica dir=$(ACPICA_INCLUDES)
";
        let CopyIncludesScan { decls, skipped, .. } =
            collect_copy_includes(src, &PathBuf::from("arch/all-native/acpica"));
        // The first directive must resolve; the second is out-of-tree.
        assert_eq!(decls.len(), 1, "decls: {decls:?}");
        assert_eq!(decls[0].dest, "libraries");
        assert_eq!(decls[0].source_dir, "arch/all-native/acpica/include");
        assert_eq!(decls[0].patterns, vec!["*.h"]);
        assert_eq!(skipped.len(), 1);
    }

    #[test]
    fn nested_parens_in_wildcard_do_not_truncate_the_glob() {
        // `$(call WILDCARD, $(X)/*.h)` must not be cut at the inner ")".
        let src = "INCLUDE_FILES := $(call WILDCARD, $(SOMEDIR)/*.h)\n%copy_includes path=x\n";
        let CopyIncludesScan { decls, skipped, .. } =
            collect_copy_includes(src, &PathBuf::from("d"));
        assert!(
            decls.is_empty(),
            "unresolved variable must not yield a pattern"
        );
        assert_eq!(skipped.len(), 1);
        assert!(
            !skipped[0].contains("*.h)"),
            "glob was truncated: {}",
            skipped[0]
        );
    }

    #[test]
    fn detects_hand_written_staging_rules() {
        // rom/hidds/pci/mmakefile.src stages a renamed header with a plain rule.
        let src = "\
$(AROS_INCLUDES)/hidd/pci.h: include/pci_hidd.h
\t$(CP) $< $(AROS_INCLUDES)/hidd/pci.h

$(GENINCDIR)/hidd/pci.h: include/pci_hidd.h
\t$(CP) $< $(GENINCDIR)/hidd/pci.h
";
        let CopyIncludesScan { adhoc, .. } =
            collect_copy_includes(src, &PathBuf::from("rom/hidds/pci"));
        assert_eq!(adhoc.len(), 2, "adhoc: {adhoc:?}");
        assert_eq!(adhoc[0].file, "rom/hidds/pci/mmakefile.src");
        assert_eq!(adhoc[0].line, 1);
        assert_eq!(adhoc[0].dest, "hidd/pci.h");
        assert_eq!(adhoc[0].prereqs, "include/pci_hidd.h");
        assert_eq!(adhoc[1].dest, "hidd/pci.h");
    }

    #[test]
    fn promotes_a_literal_anchored_sed_header_to_a_real_transform() {
        let src = r"
ARCHSRCDIR := $(PORTSDIR)/zlib/zlib
z-geninc : $(AROS_INCLUDES)/zconf.h

$(AROS_INCLUDES)/zconf.h : $(ARCHSRCDIR)/zconf.h.chr
	@$(IF) $(TEST) ! -d $(AROS_LIB)/pkgconfig ; then $(MKDIR) $(AROS_LIB)/pkgconfig ; else $(NOP) ; fi
	@$(SED) -e 's/^#if !defined(CHROMIUM_ZLIB_NO_CHROMECONF)/#if defined(ZLIB_USE_CHROMECONF)/' \
	    $< > $@
";
        let CopyIncludesScan {
            transforms, adhoc, ..
        } = collect_copy_includes(src, &PathBuf::from("workbench/libs/z"));
        assert!(adhoc.is_empty(), "promoted rule stayed adhoc: {adhoc:?}");
        assert_eq!(transforms.len(), 1, "transforms: {transforms:?}");
        let transform = &transforms[0];
        assert_eq!(transform.name, "z-geninc");
        assert_eq!(transform.input, "${AROS_PORTS_DIR}/zlib/zlib/zconf.h.chr");
        assert_eq!(transform.output, "${AROS_SDK_INCLUDE_DIR}/zconf.h");
        assert_eq!(
            transform.match_text,
            "#if !defined(CHROMIUM_ZLIB_NO_CHROMECONF)"
        );
        assert_eq!(transform.replacement, "#if defined(ZLIB_USE_CHROMECONF)");
    }

    #[test]
    fn arbitrary_sed_regex_remains_reported_as_adhoc() {
        let src = r"
x-geninc : $(AROS_INCLUDES)/x.h
$(AROS_INCLUDES)/x.h : input.h
	@$(SED) -e 's/^version=.*/version=1/' $< > $@
";
        let CopyIncludesScan {
            transforms, adhoc, ..
        } = collect_copy_includes(src, &PathBuf::from("workbench/libs/x"));
        assert!(transforms.is_empty());
        assert_eq!(adhoc.len(), 1);
        assert_eq!(adhoc[0].dest, "x.h");
    }

    #[test]
    fn sed_transform_rejects_extra_commands_suffixes_and_special_replacements() {
        let recipes = [
            "\t@$(NOP)\n\t@$(SED) -e 's/^literal/changed/' $< > $@",
            "\t@$(SED) -e 's/^literal/changed/' $< > $@ ; $(TOUCH) marker",
            "\t@$(SED) -e 's/^literal/prefix-&/' $< > $@",
            "\t@$(SED) -e 's/^literal/changed/' $< > $@\n\t@$(NOP)",
        ];
        for recipe in recipes {
            let src = format!(
                "x-geninc : $(AROS_INCLUDES)/x.h\n\
                 $(AROS_INCLUDES)/x.h : input.h\n{recipe}\n"
            );
            let CopyIncludesScan {
                transforms, adhoc, ..
            } = collect_copy_includes(&src, &PathBuf::from("workbench/libs/x"));
            assert!(transforms.is_empty(), "unsafe recipe promoted: {recipe}");
            assert_eq!(adhoc.len(), 1, "unsafe recipe disappeared: {recipe}");
        }
    }

    #[test]
    fn variable_assignment_is_not_mistaken_for_a_rule() {
        let src = "INCLUDE_FILES := a.h\n%copy_includes path=x\n";
        let CopyIncludesScan { decls, adhoc, .. } = collect_copy_includes(src, &PathBuf::from("d"));
        assert!(adhoc.is_empty());
        assert_eq!(decls.len(), 1);
    }

    #[test]
    fn stages_headers_from_a_fetched_port() {
        // The real arch/all-native/acpica declaration: the source directory is
        // rooted in $(PORTSDIR), which %fetch unpacks into.
        let src = "\
ACPICAPACKAGE      := acpica
ACPICAVERSION      := 20260408
ACPICAARCHBASE     := $(ACPICAPACKAGE)-unix-$(ACPICAVERSION)
ACPICASRCDIR       := $(PORTSDIR)/acpica/$(ACPICAARCHBASE)
ACPICA_INCLUDES    := $(ACPICASRCDIR)/source/include
INCLUDE_FILES = $(call WILDCARD, $(ACPICA_INCLUDES)/*.h)
%copy_includes mmake=acpica-includes-copy path=acpica dir=$(ACPICA_INCLUDES)
";
        let CopyIncludesScan { decls, skipped, .. } =
            collect_copy_includes(src, &PathBuf::from("arch/all-native/acpica"));
        assert!(skipped.is_empty(), "skipped: {skipped:?}");
        assert_eq!(decls.len(), 1);
        assert_eq!(decls[0].dest, "acpica");
        assert_eq!(
            decls[0].source_dir,
            "${AROS_PORTS_DIR}/acpica/acpica-unix-20260408/source/include"
        );
        assert_eq!(decls[0].patterns, vec!["*.h"]);
        assert!(decls[0].flatten);
    }

    #[test]
    fn preserves_nested_notdir_wildcards_and_literal_filter_out_for_freetype() {
        // workbench/libs/freetype2/mmakefile.src publishes a fetched header
        // tree, but deliberately generates ftoption.h instead of copying its
        // upstream default.  The source directory does not exist at configure
        // time, so the resulting glob and exclusion must remain declarative.
        let src = "\
FT2NAME := freetype
FT2VERS := 2.14.3
ARCHBASE := $(FT2NAME)-$(FT2VERS)
FT2SRCDIR := $(PORTSDIR)/$(FT2NAME)2/$(ARCHBASE)
FT2_INCLUDE_FILES := $(notdir $(call WILDCARD, $(FT2SRCDIR)/include/*.h))
%copy_includes mmake=workbench-libs-freetype-includes-copy dir=$(FT2SRCDIR)/include includes=$(FT2_INCLUDE_FILES)
FT2I_INCLUDE_FILES := $(notdir $(call WILDCARD, $(FT2SRCDIR)/include/freetype/*.h))
%copy_includes mmake=workbench-libs-freetype-includes-copy path=freetype dir=$(FT2SRCDIR)/include/freetype includes=$(FT2I_INCLUDE_FILES)
FT2OPTIONFILE := ftoption.h
FT2CONFIG_INCLUDE_FILES := $(filter-out $(FT2OPTIONFILE),$(notdir $(call WILDCARD, $(FT2SRCDIR)/include/freetype/config/*.h)))
%copy_includes mmake=workbench-libs-freetype-includes-copy path=freetype/config dir=$(FT2SRCDIR)/include/freetype/config includes=$(FT2CONFIG_INCLUDE_FILES)
FT2INT_INCLUDE_FILES := $(notdir $(call WILDCARD, $(FT2SRCDIR)/include/freetype/internal/*.h))
%copy_includes mmake=workbench-libs-freetype-includes-copy path=freetype/internal dir=$(FT2SRCDIR)/include/freetype/internal includes=$(FT2INT_INCLUDE_FILES)
FT2SVC_INCLUDE_FILES := $(notdir $(call WILDCARD, $(FT2SRCDIR)/include/freetype/internal/services/*.h))
%copy_includes mmake=workbench-libs-freetype-includes-copy path=freetype/internal/services dir=$(FT2SRCDIR)/include/freetype/internal/services includes=$(FT2SVC_INCLUDE_FILES)
";
        let CopyIncludesScan { decls, skipped, .. } =
            collect_copy_includes(src, &PathBuf::from("workbench/libs/freetype2"));

        assert!(skipped.is_empty(), "skipped: {skipped:?}");
        assert_eq!(decls.len(), 5, "decls: {decls:?}");
        assert!(decls.iter().all(|decl| {
            decl.name == "workbench-libs-freetype-includes-copy"
                && decl
                    .source_dir
                    .starts_with("${AROS_PORTS_DIR}/freetype2/freetype-2.14.3/include")
                && decl.patterns == ["*.h"]
                && decl.flatten
        }));
        let config = decls
            .iter()
            .find(|decl| decl.dest == "freetype/config")
            .expect("freetype config header group");
        assert_eq!(config.excludes, ["ftoption.h"]);
        assert!(decls
            .iter()
            .filter(|decl| decl.dest != "freetype/config")
            .all(|decl| decl.excludes.is_empty()));
    }

    #[test]
    fn module_private_generated_header_is_recorded() {
        // rom/dos/mmakefile.src:90. Before $(GENDIR) was a recognised root this
        // rule went unreported, and the missing errorlist.h surfaced as an
        // undeclared MSG_STRING_* in displayerror.c instead.
        let src = "$(GENDIR)/$(CURDIR)/dos/errorlist.h : $(SRCDIR)/$(CURDIR)/catalogs/dos.cd\n";
        let CopyIncludesScan { adhoc, .. } = collect_copy_includes(src, &PathBuf::from("rom/dos"));
        assert_eq!(adhoc.len(), 1);
        assert_eq!(adhoc[0].root, "$(GENDIR)/");
        assert_eq!(adhoc[0].dest, "$(CURDIR)/dos/errorlist.h");
    }

    #[test]
    fn non_header_under_gendir_is_reported_separately() {
        let src = "$(GENDIR)/boot/aros-amiga-m68k.elf : $(KOBJS_rom)\n";
        let CopyIncludesScan {
            adhoc,
            generated_files,
            ..
        } = collect_copy_includes(src, &PathBuf::from("arch/m68k-amiga/boot"));
        assert!(adhoc.is_empty());
        assert_eq!(generated_files.len(), 1);
        assert!(generated_files[0].contains("aros-amiga-m68k.elf"));
    }

    #[test]
    fn directory_and_dependency_rules_are_not_reported() {
        // CMake makes output directories itself and tracks header dependencies
        // through the compiler, so neither can go missing.
        let src = "\
$(GENDIR)/$(CURDIR) :
$(GENDIR)/$(CURDIR)/errorlist.d : $(GENDIR)/$(CURDIR)/errorlist.h
$(GENDIR)/$(CURDIR)/.includes-generated : $(GENMODULE)
";
        let CopyIncludesScan {
            adhoc,
            generated_files,
            ..
        } = collect_copy_includes(src, &PathBuf::from("rom/dos"));
        assert!(adhoc.is_empty(), "adhoc: {adhoc:?}");
        assert!(generated_files.is_empty(), "reported: {generated_files:?}");
    }

    #[test]
    fn target_in_an_include_root_counts_as_a_header_whatever_its_name() {
        // $(AROS_INCLUDES) is an include root, so a variable-named or pattern
        // target there is still a header. Only $(GENDIR) mixes file kinds.
        let src = "\
$(AROS_INCLUDES)/freetype/config/$(FT2OPTIONFILE) : $(FT2SRCDIR)/x
$(AROS_INCLUDES)/% : %
";
        let CopyIncludesScan {
            adhoc,
            generated_files,
            ..
        } = collect_copy_includes(src, &PathBuf::from("workbench/libs/freetype2"));
        assert_eq!(adhoc.len(), 2);
        assert!(generated_files.is_empty());
    }

    #[test]
    fn a_static_pattern_rule_into_the_sdk_is_recorded() {
        // workbench/network/common/include stages 81 headers this way, the
        // whole BSD socket interface. The include root sits in the middle
        // field, not in the target, so matching only the target missed it and
        // netdb.h, netinet/in.h and proto/socket.h went absent unreported.
        let src = "\
INCLUDES      := $(call WILDCARD, *.h arpa/*.h)
DEST_INCLUDES := $(foreach f,$(INCLUDES),$(AROS_INCLUDES)/$(f))

$(DEST_INCLUDES) : $(AROS_INCLUDES)/% : $(SRCDIR)/$(CURDIR)/%
";
        let CopyIncludesScan { adhoc, .. } =
            collect_copy_includes(src, &PathBuf::from("workbench/network/common/include"));
        assert_eq!(adhoc.len(), 1, "adhoc: {adhoc:?}");
        assert_eq!(adhoc[0].root, "$(AROS_INCLUDES)/");
        assert_eq!(adhoc[0].dest, "%");
        assert!(adhoc[0].prereqs.contains("DEST_INCLUDES"));
    }

    #[test]
    fn the_udis86_itab_rule_is_modelled_not_reported() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../..");
        let rel = "arch/all-pc/udis86";
        let content = aros_common::read_source(&root.join(rel).join("mmakefile.src")).unwrap();
        let scan = collect_copy_includes(&content, std::path::Path::new(rel));

        assert_eq!(
            scan.skipped_script_outputs.len(),
            0,
            "{:?}",
            scan.skipped_script_outputs
        );
        assert_eq!(scan.script_outputs.len(), 1, "{:?}", scan.script_outputs);
        let decl = &scan.script_outputs[0];
        assert_eq!(
            decl.output,
            "${CMAKE_BINARY_DIR}/gen/arch/all-pc/udis86/libudis86/itab.c"
        );
        assert!(
            decl.script.ends_with("scripts/ud_itab.py"),
            "{}",
            decl.script
        );
        assert_eq!(decl.arguments.len(), 2, "{:?}", decl.arguments);
        assert!(decl.arguments[0].ends_with("docs/x86/optable.xml"));
        assert!(decl.arguments[1].ends_with("gen/arch/all-pc/udis86/libudis86"));
        // The rule stays out of the unmodelled report now that it is modelled.
        assert!(
            !scan
                .generated_files
                .iter()
                .any(|note| note.contains("itab.c")),
            "{:?}",
            scan.generated_files
        );
    }
}
