use crate::ast::ModuleType;
use crate::graph::DependencyGraph;
use std::collections::HashSet;
use std::fmt::Write;

/// Renders one value as a quoted CMake argument.
///
/// A string-literal define such as `AROS_ARCHITECTURE="pc"` carries quotes of
/// its own. Emitted verbatim they would end the CMake string early and the
/// value would be read as several arguments, so they are escaped here. `$` is
/// left alone, since a value may legitimately reference a CMake variable.
fn cmake_arg(value: &str) -> String {
    let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

/// Generates modern CMake code from the parsed dependency graph.
#[must_use]
pub fn generate_cmake(graph: &DependencyGraph) -> String {
    let mut out = String::new();
    writeln!(out, "# Auto-generated by AROS-NG Transpiler v0.1.0").unwrap();
    writeln!(out, "# Zero-divergence dynamic target tree\n").unwrap();

    let all_targets: HashSet<&str> = graph
        .targets
        .keys()
        .chain(graph.icon_targets.keys())
        .map(String::as_str)
        .chain(graph.fetches.iter().map(|fetch| fetch.name.as_str()))
        .collect();

    // SDK header staging comes first: the copies happen at configure time, and
    // keeping them at the top of the file makes the generated output readable
    // in the same order the build needs them.
    if !graph.copy_includes.is_empty() {
        writeln!(
            out,
            "# =============================================================================\n\
             # SDK header staging (from %copy_includes)\n\
             # ============================================================================="
        )
        .unwrap();
        // Generic headers first, architecture-specific last: both land under
        // the same SDK name and the last copy wins. compiler/include ships a
        // portable asm/cpu.h that arch/<cpu>-all/include has to override, and
        // without a defined order which one survived depended on parse order.
        let mut ordered: Vec<&_> = graph.copy_includes.iter().collect();
        ordered.sort_by_key(|d| usize::from(d.source_dir.contains("/arch/")));
        for decl in ordered {
            let patterns: Vec<String> = decl.patterns.iter().map(|p| cmake_arg(p)).collect();
            writeln!(
                out,
                "aros_copy_includes(DEST \"{}\" SOURCE \"{}\" PATTERNS {}{})",
                decl.dest,
                decl.source_dir,
                patterns.join(" "),
                if decl.flatten { " FLATTEN" } else { "" }
            )
            .unwrap();
        }
        writeln!(out).unwrap();
    }

    // Third-party source fetching. Emitted before the targets so the rules
    // exist when a module wants to depend on them.
    if !graph.fetches.is_empty() {
        writeln!(
            out,
            "# =============================================================================\n\
             # Third-party source fetching (from %fetch)\n\
             # ============================================================================="
        )
        .unwrap();
        for f in &graph.fetches {
            writeln!(
                out,
                "aros_fetch_archive(NAME \"{}\" ARCHIVE \"{}\" SUFFIXES \"{}\" ORIGINS \"{}\"\n\
                 \x20   LOCATION \"{}\" DESTINATION \"{}\" PATCH_ORIGINS \"{}\" PATCHES \"{}\")",
                f.name,
                f.archive,
                f.suffixes,
                f.origins,
                f.location,
                f.destination,
                f.patch_origins,
                f.patches
            )
            .unwrap();
        }
        writeln!(out).unwrap();
    }

    // Hand-written Make rules that stage headers. These cannot be transpiled,
    // so they are declared for CMake to check against its list of rules that
    // have a static counterpart. A rule appearing upstream that nobody has
    // handled then surfaces at configure time instead of as a missing header.
    if !graph.adhoc_header_rules.is_empty() {
        writeln!(
            out,
            "# =============================================================================\n\
             # Hand-written header staging rules (need a static CMake counterpart)\n\
             # ============================================================================="
        )
        .unwrap();
        for rule in &graph.adhoc_header_rules {
            writeln!(
                out,
                "aros_adhoc_header_rule(FILE {} LINE {} ROOT {} DEST {} PREREQS {})",
                cmake_arg(&rule.file),
                rule.line,
                cmake_arg(&rule.root),
                cmake_arg(&rule.dest),
                cmake_arg(&rule.prereqs)
            )
            .unwrap();
        }
        writeln!(out).unwrap();
    }

    // 1. Concrete Module Targets. HashMap iteration is deliberately avoided:
    // reproducible generated CMake is required for meaningful comparisons,
    // and declaration order can decide which producer claims an output first.
    let mut concrete_targets: Vec<_> = graph.targets.values().collect();
    concrete_targets.sort_by(|a, b| a.mmake_name.cmp(&b.mmake_name));
    for target in concrete_targets {
        let macro_name = match target.module_type {
            ModuleType::Library => "aros_add_library",
            ModuleType::Device => "aros_add_device",
            ModuleType::Resource => "aros_add_resource",
            ModuleType::Hidd => "aros_add_hidd",
            ModuleType::Datatype => "aros_add_datatype",
            ModuleType::Gadget => "aros_add_gadget",
            ModuleType::Mcc => "aros_add_mcc",
            ModuleType::Program => "aros_add_program",
            ModuleType::ProgramGroup => "aros_add_programs",
            ModuleType::SimpleModule => "aros_add_module_simple",
            ModuleType::LinkLib => "aros_add_linklib",
            _ => "aros_add_custom_target",
        };

        // Every declaration is emitted, whatever architecture its sources belong
        // to. Restricting the emission was tempting, but a hard-coded
        // `if(AROS_TARGET_PLATFORM STREQUAL "pc")` around the declaration made
        // 46 targets disappear from the build graph entirely, so nothing could
        // report on them: they were neither built nor listed as skipped, and a
        // newly added arch/ directory would have joined them silently.
        //
        // aros_gate_arch() in cmake/AROS.cmake does the filtering instead. It
        // reads AROS_ARCH_SOURCE_DIRS, so it covers every architecture rather
        // than the four spelled out here, and it excludes the target from `all`
        // while keeping it nameable, which is what makes it possible to ask
        // whether a foreign-architecture target would build.
        writeln!(out, "{macro_name}(").unwrap();
        writeln!(out, "    TARGET {}", target.target_name).unwrap();
        writeln!(out, "    MMAKE_ID {}", target.mmake_name).unwrap();
        if !target.link_libs.is_empty() {
            let libs: Vec<String> = target.link_libs.iter().map(|l| cmake_arg(l)).collect();
            writeln!(out, "    LIBS {}", libs.join(" ")).unwrap();
        }
        if let Some(mod_type) = &target.declared_mod_type {
            writeln!(out, "    MODTYPE {}", cmake_arg(mod_type)).unwrap();
        }
        if let Some(suffix) = &target.mod_suffix {
            writeln!(out, "    MODSUFFIX {}", cmake_arg(suffix)).unwrap();
        }
        writeln!(
            out,
            "    DIRECTORY \"${{CMAKE_SOURCE_DIR}}/{}\"",
            target.dir_path.display()
        )
        .unwrap();
        if let Some(target_dir) = &target.target_dir {
            writeln!(out, "    INSTALL_DIR {}", cmake_arg(target_dir)).unwrap();
        }

        for (keyword, sources) in [
            ("SOURCES", &target.source_files),
            ("CXX_SOURCES", &target.cxx_source_files),
            ("OBJC_SOURCES", &target.objc_source_files),
            ("ASM_SOURCES", &target.asm_source_files),
        ] {
            if !sources.is_empty() {
                let quoted: Vec<String> = sources.iter().map(|source| cmake_arg(source)).collect();
                writeln!(out, "    {keyword} {}", quoted.join(" ")).unwrap();
            }
        }

        if !target.use_libs.is_empty() {
            writeln!(out, "    USELIBS {}", target.use_libs.join(" ")).unwrap();
        }

        if !target.include_dirs.is_empty() {
            let quoted: Vec<String> = target.include_dirs.iter().map(|d| cmake_arg(d)).collect();
            writeln!(out, "    INCLUDES {}", quoted.join(" ")).unwrap();
        }

        // Architecture-conditional includes are emitted as `<tag>|<path>` pairs.
        // CMake keeps the ones whose tag applies to the configured target; see
        // aros_arch_include_tags() in cmake/AROS.cmake.
        if !target.arch_includes.is_empty() {
            let pairs: Vec<String> = target
                .arch_includes
                .iter()
                .map(|(tag, dir)| cmake_arg(&format!("{tag}|{dir}")))
                .collect();
            writeln!(out, "    ARCH_INCLUDES {}", pairs.join(" ")).unwrap();
        }

        // Preprocessor state the sources depend on, from USER_CPPFLAGS /
        // USER_CFLAGS. Quoted so a value containing a CMake variable survives.
        if !target.defines.is_empty() {
            let quoted: Vec<String> = target.defines.iter().map(|d| cmake_arg(d)).collect();
            writeln!(out, "    DEFINES {}", quoted.join(" ")).unwrap();
        }
        if !target.undefines.is_empty() {
            let quoted: Vec<String> = target.undefines.iter().map(|d| cmake_arg(d)).collect();
            writeln!(out, "    UNDEFINES {}", quoted.join(" ")).unwrap();
        }
        // Architecture source overrides as "<tag>|<dir>|<f1>,<f2>,...".
        // CMake keeps the tags that apply, drops the same-named generic
        // sources and puts the architecture ones first, as the reference build
        // does (config/make.tmpl:1661).
        if !target.arch_sources.is_empty() {
            let entries: Vec<String> = target
                .arch_sources
                .iter()
                .map(|(tag, dir, files)| cmake_arg(&format!("{tag}|{dir}|{}", files.join(","))))
                .collect();
            writeln!(out, "    ARCH_SOURCES {}", entries.join(" ")).unwrap();
        }

        // Architecture-conditional flags from a make.opts, same "<tag>|<value>"
        // shape as ARCH_INCLUDES.
        if !target.arch_defines.is_empty() {
            let pairs: Vec<String> = target
                .arch_defines
                .iter()
                .map(|(tag, d)| cmake_arg(&format!("{tag}|{d}")))
                .collect();
            writeln!(out, "    ARCH_DEFINES {}", pairs.join(" ")).unwrap();
        }
        if !target.arch_compile_options.is_empty() {
            let pairs: Vec<String> = target
                .arch_compile_options
                .iter()
                .map(|(tag, o)| cmake_arg(&format!("{tag}|{o}")))
                .collect();
            writeln!(out, "    ARCH_COMPILE_OPTIONS {}", pairs.join(" ")).unwrap();
        }

        if !target.compile_options.is_empty() {
            let quoted: Vec<String> = target
                .compile_options
                .iter()
                .map(|o| cmake_arg(o))
                .collect();
            writeln!(out, "    COMPILE_OPTIONS {}", quoted.join(" ")).unwrap();
        }

        writeln!(out, ")").unwrap();
        writeln!(out).unwrap();
    }

    // Workbench .info resources. Identities are declared separately from
    // their output rules so an unresolved or architecture-empty declaration
    // remains a real, nameable target and keeps its #MM edges.
    if !graph.icon_targets.is_empty() {
        writeln!(
            out,
            "# =============================================================================\n\
             # Workbench icons (from %build_icons)\n\
             # ============================================================================="
        )
        .unwrap();

        let mut icon_targets: Vec<_> = graph.icon_targets.values().collect();
        icon_targets.sort_by(|a, b| a.mmake.cmp(&b.mmake));
        for target in icon_targets {
            writeln!(out, "aros_declare_icon_target(").unwrap();
            // Deliberately unquoted: aros-verify reads the token as written.
            writeln!(out, "    MMAKE_ID {}", target.mmake).unwrap();
            writeln!(out, "    DIRECTORY {}", cmake_arg(&target.directory)).unwrap();
            writeln!(out, ")").unwrap();
        }
        writeln!(out).unwrap();

        let mut icons: Vec<_> = graph.icons.iter().collect();
        icons.sort_by(|a, b| {
            a.srcdir
                .cmp(&b.srcdir)
                .then_with(|| a.line.cmp(&b.line))
                .then_with(|| a.dir.cmp(&b.dir))
                .then_with(|| a.mmake.cmp(&b.mmake))
                .then_with(|| a.condition.cmp(&b.condition))
        });
        for icon in icons {
            if let Some(condition) = &icon.condition {
                writeln!(out, "if({condition})").unwrap();
            }
            writeln!(out, "aros_build_icons(").unwrap();
            writeln!(out, "    MMAKE_ID {}", icon.mmake).unwrap();
            writeln!(out, "    DIRECTORY {}", cmake_arg(&icon.srcdir)).unwrap();
            writeln!(out, "    DESTINATION {}", cmake_arg(&icon.dir)).unwrap();
            writeln!(out, "    FORMAT {}", cmake_arg(&icon.fmt)).unwrap();
            if let Some(iconset) = &icon.iconset {
                writeln!(out, "    ICONSET {}", cmake_arg(iconset)).unwrap();
            }
            if !icon.icons.is_empty() {
                let values: Vec<_> = icon.icons.iter().map(|v| cmake_arg(v)).collect();
                writeln!(out, "    ICONS {}", values.join(" ")).unwrap();
            }
            if !icon.images.is_empty() {
                let values: Vec<_> = icon.images.iter().map(|v| cmake_arg(v)).collect();
                writeln!(out, "    IMAGES {}", values.join(" ")).unwrap();
            }
            writeln!(out, ")").unwrap();
            if icon.condition.is_some() {
                writeln!(out, "endif()").unwrap();
            }
            writeln!(out).unwrap();
        }
    }

    // 2. Meta-Targets derived from #MM and #MM-
    writeln!(
        out,
        "\n# ============================================================================="
    )
    .unwrap();
    writeln!(out, "# Declarative Meta-Targets (#MM and #MM-)").unwrap();
    writeln!(
        out,
        "# =============================================================================\n"
    )
    .unwrap();

    let all_metas: HashSet<&str> = graph.meta_targets.keys().map(String::as_str).collect();
    let mut meta_rules: Vec<_> = graph.meta_targets.iter().collect();
    meta_rules.sort_by_key(|(name, _)| (*name).clone());

    // Phase one declares every meta target. The old single-pass form checked
    // `if(TARGET dep)` while iterating a HashMap, so a meta dependency that was
    // declared later in the random iteration order was permanently omitted.
    for (meta_name, _) in &meta_rules {
        // `clean` and `install` are generator-provided target names which
        // CMake refuses in add_custom_target(). They remain valid dependency
        // tokens, but cannot have separately declared utility targets here.
        if !matches!(meta_name.as_str(), "clean" | "install")
            && !all_targets.contains(meta_name.as_str())
        {
            writeln!(out, "if(NOT TARGET {})", cmake_arg(meta_name)).unwrap();
            writeln!(out, "    add_custom_target({})", cmake_arg(meta_name)).unwrap();
            writeln!(out, "endif()").unwrap();
        }
    }
    writeln!(out).unwrap();

    // Phase two attaches edges after every possible endpoint exists. This also
    // runs for a meta name that is already a concrete/icon target: fourteen
    // icon targets carry their own outputs and #MM children at the same time.
    for (meta_name, deps) in &meta_rules {
        let mut valid_deps: Vec<&String> = deps
            .iter()
            .filter(|dep| {
                *dep != *meta_name
                    && (all_targets.contains(dep.as_str())
                        || all_metas.contains(dep.as_str())
                        || dep.contains("${"))
            })
            .collect();
        valid_deps.sort();
        if valid_deps.is_empty() {
            continue;
        }
        writeln!(out, "if(TARGET {})", cmake_arg(meta_name)).unwrap();
        writeln!(
            out,
            "    foreach(dep IN ITEMS {})",
            valid_deps
                .iter()
                .map(|s| cmake_arg(s))
                .collect::<Vec<_>>()
                .join(" ")
        )
        .unwrap();
        writeln!(out, "        if(TARGET \"${{dep}}\")").unwrap();
        writeln!(
            out,
            "            aros_add_target_dependency({} \"${{dep}}\")",
            cmake_arg(meta_name)
        )
        .unwrap();
        writeln!(out, "        endif()").unwrap();
        writeln!(out, "    endforeach()").unwrap();
        writeln!(out, "endif()\n").unwrap();
    }
    // Packages and the kickstart link, last: both check whether each member
    // is a configured target that produces a file, so the targets have to
    // exist by the time CMake reaches these calls.
    if !graph.packages.is_empty() {
        writeln!(
            out,
            "# ---- Packages and kickstart, from %make_package / %link_kickstart ----"
        )
        .unwrap();
        for pkg in &graph.packages {
            if pkg.resolved.is_empty() {
                continue;
            }
            let func = if pkg.is_kickstart {
                "aros_link_kickstart"
            } else {
                "aros_make_package"
            };
            writeln!(out, "{func}(").unwrap();
            writeln!(out, "    NAME {}", pkg.mmake).unwrap();
            writeln!(out, "    OUTPUT {}", cmake_arg(&pkg.output)).unwrap();
            if !pkg.arch.is_empty() {
                writeln!(out, "    ARCH {}", cmake_arg(&pkg.arch)).unwrap();
            }
            if !pkg.uselibs.is_empty() {
                let libs: Vec<String> = pkg.uselibs.iter().map(|l| cmake_arg(l)).collect();
                writeln!(out, "    USELIBS {}", libs.join(" ")).unwrap();
            }
            let ids: Vec<String> = pkg
                .resolved
                .iter()
                .map(|member| cmake_arg(&member.target))
                .collect();
            writeln!(out, "    MODULES {}", ids.join(" ")).unwrap();
            if !pkg.is_kickstart {
                let names: Vec<String> = pkg
                    .resolved
                    .iter()
                    .map(|member| cmake_arg(&member.runtime_name))
                    .collect();
                writeln!(out, "    MEMBER_NAMES {}", names.join(" ")).unwrap();
            }
            writeln!(out, ")").unwrap();
        }
        writeln!(out).unwrap();
    }

    out
}

#[cfg(test)]
mod tests {
    use super::generate_cmake;
    use crate::ast::MetaTargetRule;
    use crate::dirs::DirVars;
    use crate::fetch::FetchDecl;
    use crate::graph::DependencyGraph;
    use crate::icons::IconTarget;
    use crate::packages::{PackageDecl, ResolvedPackageMember};
    use crate::parse_mmakefile_with_dirs;
    use std::path::Path;

    fn root() -> std::path::PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../..")
    }

    fn icon(name: &str) -> IconTarget {
        IconTarget {
            mmake: name.to_owned(),
            directory: "images/icons".to_owned(),
        }
    }

    #[test]
    fn an_icon_target_can_also_receive_meta_dependencies() {
        let mut graph = DependencyGraph::new();
        graph.add_icons(vec![icon("icons"), icon("leaf")], Vec::new());
        graph.add_meta_rule(MetaTargetRule {
            name: "icons".to_owned(),
            dependencies: vec!["leaf".to_owned()],
        });

        let cmake = generate_cmake(&graph);
        assert!(cmake.contains("aros_add_target_dependency(\"icons\" \"${dep}\")"));
        assert!(!cmake.contains("add_custom_target(\"icons\")"));
    }

    #[test]
    fn fetch_targets_survive_meta_dependency_filtering() {
        let mut graph = DependencyGraph::new();
        graph.add_fetches(vec![FetchDecl {
            name: "example-fetch".to_owned(),
            archive: "example-1.0".to_owned(),
            suffixes: "tar.gz".to_owned(),
            origins: "https://example.invalid".to_owned(),
            location: "${AROS_PORTS_SOURCE_DIR}".to_owned(),
            destination: "${AROS_PORTS_DIR}".to_owned(),
            patch_origins: String::new(),
            patches: String::new(),
            dir: "external/example".to_owned(),
        }]);
        graph.add_meta_rule(MetaTargetRule {
            name: "consumer".to_owned(),
            dependencies: vec!["example-fetch".to_owned()],
        });

        let cmake = generate_cmake(&graph);
        assert!(cmake.contains("aros_fetch_archive(NAME \"example-fetch\""));
        assert!(cmake.contains("aros_add_target_dependency(\"consumer\" \"${dep}\")"));
        assert!(!cmake.contains("add_custom_target(\"example-fetch\")"));
    }

    #[test]
    fn all_meta_targets_are_declared_before_any_edges_are_attached() {
        let mut graph = DependencyGraph::new();
        graph.add_icons(vec![icon("leaf")], Vec::new());
        graph.add_meta_rule(MetaTargetRule {
            name: "parent".to_owned(),
            dependencies: vec!["child".to_owned()],
        });
        graph.add_meta_rule(MetaTargetRule {
            name: "child".to_owned(),
            dependencies: vec!["leaf".to_owned()],
        });

        let cmake = generate_cmake(&graph);
        let parent = cmake.find("add_custom_target(\"parent\")").unwrap();
        let child = cmake.find("add_custom_target(\"child\")").unwrap();
        let first_edge = cmake.find("foreach(dep IN ITEMS").unwrap();
        assert!(parent < first_edge && child < first_edge, "{cmake}");
    }

    #[test]
    fn a_dynamic_selected_iconset_dependency_is_not_filtered_out() {
        let mut graph = DependencyGraph::new();
        graph.add_meta_rule(MetaTargetRule {
            name: "workbench".to_owned(),
            dependencies: vec!["iconset-${AROS_TARGET_ICONSET}-wbench-icons".to_owned()],
        });
        let cmake = generate_cmake(&graph);
        assert!(cmake.contains("iconset-${AROS_TARGET_ICONSET}-wbench-icons"));
    }

    #[test]
    fn an_orphan_meta_target_remains_nameable_from_its_parent() {
        let mut graph = DependencyGraph::new();
        graph.add_meta_rule(MetaTargetRule {
            name: "parent".to_owned(),
            dependencies: vec!["orphan".to_owned()],
        });
        graph.add_meta_rule(MetaTargetRule {
            name: "orphan".to_owned(),
            dependencies: vec!["missing".to_owned()],
        });

        let cmake = generate_cmake(&graph);
        assert!(cmake.contains("add_custom_target(\"parent\")"));
        assert!(cmake.contains("add_custom_target(\"orphan\")"));
        assert!(cmake.contains("foreach(dep IN ITEMS \"orphan\")"));
        assert!(!cmake.contains("foreach(dep IN ITEMS \"missing\")"));
    }

    #[test]
    fn the_reserved_clean_target_is_not_redeclared() {
        let mut graph = DependencyGraph::new();
        graph.add_meta_rule(MetaTargetRule {
            name: "clean".to_owned(),
            dependencies: vec!["missing".to_owned()],
        });

        let cmake = generate_cmake(&graph);
        assert!(!cmake.contains("add_custom_target(\"clean\")"));
    }

    #[test]
    fn the_reserved_install_target_is_not_redeclared() {
        let mut graph = DependencyGraph::new();
        graph.add_meta_rule(MetaTargetRule {
            name: "install".to_owned(),
            dependencies: vec!["leaf".to_owned()],
        });
        graph.add_meta_rule(MetaTargetRule {
            name: "leaf".to_owned(),
            dependencies: Vec::new(),
        });

        let cmake = generate_cmake(&graph);
        assert!(!cmake.contains("add_custom_target(\"install\")"));
        assert!(cmake.contains("add_custom_target(\"leaf\")"));
    }

    #[test]
    fn module_output_metadata_is_emitted_for_the_cmake_builders() {
        let root = root();
        let dirs = DirVars::load(&root);
        let mut graph = DependencyGraph::new();
        for relative in [
            "developer/debug/test/library/mmakefile.src",
            "workbench/tools/SysExplorer/mmakefile.src",
            "rom/usb/classes/serialpl2303/mmakefile.src",
        ] {
            let parsed = parse_mmakefile_with_dirs(&root.join(relative), &root, &dirs).unwrap();
            assert!(
                parsed.skipped_programs.is_empty(),
                "{relative}: {:#?}",
                parsed.skipped_programs
            );
            for target in parsed.targets {
                graph.add_target(target);
            }
        }

        let cmake = generate_cmake(&graph);
        assert!(
            cmake.contains(
                "    INSTALL_DIR \"${AROS_BUILD_DIR}/SYS/Developer/Debug/Tests/Library/Libs\""
            ),
            "{cmake}"
        );
        assert!(
            cmake.contains("    INSTALL_DIR \"Tools/SysExpModules\""),
            "{cmake}"
        );
        assert!(cmake.contains("    MODTYPE \"usbclass\""), "{cmake}");
        assert!(cmake.contains("    MODSUFFIX \"class\""), "{cmake}");
        assert!(cmake.contains("    MODSUFFIX \"sysexp\""), "{cmake}");
    }

    #[test]
    fn package_member_names_align_with_modules_but_do_not_reach_kickstart() {
        let mut graph = DependencyGraph::new();
        let members = vec![
            ResolvedPackageMember {
                target: "kernel-fs-ram".to_owned(),
                runtime_name: "ram-handler".to_owned(),
            },
            ResolvedPackageMember {
                target: "kernel-log-serial".to_owned(),
                runtime_name: "serial.logger".to_owned(),
            },
        ];
        graph.add_packages(vec![
            PackageDecl {
                file: "rom/mmakefile.src".to_owned(),
                mmake: "package".to_owned(),
                output: "${AROS_BOOT_DIR}/package.pkg".to_owned(),
                members: Vec::new(),
                startup: None,
                uselibs: Vec::new(),
                is_kickstart: false,
                resolved: members.clone(),
                arch: String::new(),
            },
            PackageDecl {
                file: "arch/test/boot/mmakefile.src".to_owned(),
                mmake: "kickstart".to_owned(),
                output: "${AROS_BOOT_ARCH_DIR}/kernel".to_owned(),
                members: Vec::new(),
                startup: Some("kernel".to_owned()),
                uselibs: Vec::new(),
                is_kickstart: true,
                resolved: members,
                arch: "test".to_owned(),
            },
        ]);

        let cmake = generate_cmake(&graph);
        let package_start = cmake.find("aros_make_package(").unwrap();
        let kickstart_start = cmake.find("aros_link_kickstart(").unwrap();
        let package = &cmake[package_start..kickstart_start];
        let kickstart = &cmake[kickstart_start..];
        assert!(
            package.contains("    MODULES \"kernel-fs-ram\" \"kernel-log-serial\""),
            "{package}"
        );
        assert!(
            package.contains("    MEMBER_NAMES \"ram-handler\" \"serial.logger\""),
            "{package}"
        );
        assert!(kickstart.contains("    MODULES \"kernel-fs-ram\" \"kernel-log-serial\""));
        assert!(!kickstart.contains("MEMBER_NAMES"), "{kickstart}");
    }
}
