use crate::ast::ModuleType;
use crate::graph::DependencyGraph;
use std::fmt::Write;
use std::path::Path;

/// Generates modern CMake code from the parsed dependency graph.
#[must_use]
pub fn generate_cmake(graph: &DependencyGraph) -> String {
    let mut out = String::new();
    writeln!(out, "# Auto-generated by AROS-NG Transpiler v0.1.0").unwrap();
    writeln!(out, "# Zero-divergence dynamic target tree\n").unwrap();

    for target in graph.targets.values() {
        let macro_name = match target.module_type {
            ModuleType::Library => "aros_add_library",
            ModuleType::Device => "aros_add_device",
            ModuleType::Resource => "aros_add_resource",
            ModuleType::Hidd => "aros_add_hidd",
            ModuleType::Datatype => "aros_add_datatype",
            ModuleType::Gadget => "aros_add_gadget",
            ModuleType::Mcc => "aros_add_mcc",
            ModuleType::Program => "aros_add_program",
            ModuleType::LinkLib => "aros_add_linklib",
            _ => "aros_add_custom_target",
        };

        let dir_str = target.dir_path.to_string_lossy();
        let arch_condition = if dir_str.contains("arch/all-pc")
            || dir_str.contains("arch/x86_64-pc")
            || dir_str.contains("arch/i386-all")
        {
            Some(r#"AROS_TARGET_PLATFORM STREQUAL "pc""#)
        } else if dir_str.contains("arch/arm-native")
            || dir_str.contains("arch/aarch64-raspi")
            || dir_str.contains("arch/all-raspi")
        {
            Some(r#"AROS_TARGET_PLATFORM STREQUAL "raspi""#)
        } else if dir_str.contains("arch/m68k-amiga") || dir_str.contains("arch/m68k-all") {
            Some(r#"AROS_TARGET_ARCH STREQUAL "m68k""#)
        } else if dir_str.contains("arch/all-darwin") {
            Some(r#"AROS_TARGET_PLATFORM STREQUAL "darwin""#)
        } else {
            None
        };

        if let Some(cond) = arch_condition {
            writeln!(out, "if({cond})").unwrap();
        }

        writeln!(out, "{macro_name}(").unwrap();
        writeln!(out, "    TARGET {}", target.target_name).unwrap();
        writeln!(out, "    MMAKE_ID {}", target.mmake_name).unwrap();
        writeln!(
            out,
            "    DIRECTORY \"${{CMAKE_SOURCE_DIR}}/{}\"",
            target.dir_path.display()
        )
        .unwrap();

        if !target.source_files.is_empty() {
            writeln!(out, "    SOURCES").unwrap();
            for f in &target.source_files {
                let fname = if Path::new(f).extension().is_some_and(|ext| {
                    ext.eq_ignore_ascii_case("c") || ext.eq_ignore_ascii_case("s")
                }) {
                    f.clone()
                } else {
                    format!("{f}.c")
                };
                writeln!(out, "        {fname}").unwrap();
            }
        }

        if !target.use_libs.is_empty() {
            writeln!(out, "    LIBS").unwrap();
            for lib in &target.use_libs {
                writeln!(out, "        {lib}").unwrap();
            }
        }

        writeln!(out, ")").unwrap();

        if arch_condition.is_some() {
            writeln!(out, "endif()").unwrap();
        }
        writeln!(out).unwrap();
    }

    out
}
