use crate::ast::ModuleType;
use crate::graph::DependencyGraph;
use std::collections::HashSet;
use std::fmt::Write;

/// Generates modern CMake code from the parsed dependency graph.
#[must_use]
/// Renders one value as a quoted CMake argument.
///
/// A string-literal define such as `AROS_ARCHITECTURE="pc"` carries quotes of
/// its own. Emitted verbatim they would end the CMake string early and the
/// value would be read as several arguments, so they are escaped here. `$` is
/// left alone, since a value may legitimately reference a CMake variable.
fn cmake_arg(value: &str) -> String {
    let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

pub fn generate_cmake(graph: &DependencyGraph) -> String {
    let mut out = String::new();
    writeln!(out, "# Auto-generated by AROS-NG Transpiler v0.1.0").unwrap();
    writeln!(out, "# Zero-divergence dynamic target tree\n").unwrap();

    let all_targets: HashSet<&String> = graph.targets.keys().collect();

    // SDK header staging comes first: the copies happen at configure time, and
    // keeping them at the top of the file makes the generated output readable
    // in the same order the build needs them.
    if !graph.copy_includes.is_empty() {
        writeln!(
            out,
            "# =============================================================================\n\
             # SDK header staging (from %copy_includes)\n\
             # ============================================================================="
        )
        .unwrap();
        // Generic headers first, architecture-specific last: both land under
        // the same SDK name and the last copy wins. compiler/include ships a
        // portable asm/cpu.h that arch/<cpu>-all/include has to override, and
        // without a defined order which one survived depended on parse order.
        let mut ordered: Vec<&_> = graph.copy_includes.iter().collect();
        ordered.sort_by_key(|d| usize::from(d.source_dir.contains("/arch/")));
        for decl in ordered {
            let patterns: Vec<String> = decl.patterns.iter().map(|p| cmake_arg(p)).collect();
            writeln!(
                out,
                "aros_copy_includes(DEST \"{}\" SOURCE \"{}\" PATTERNS {}{})",
                decl.dest,
                decl.source_dir,
                patterns.join(" "),
                if decl.flatten { " FLATTEN" } else { "" }
            )
            .unwrap();
        }
        writeln!(out).unwrap();
    }

    // Third-party source fetching. Emitted before the targets so the rules
    // exist when a module wants to depend on them.
    if !graph.fetches.is_empty() {
        writeln!(
            out,
            "# =============================================================================\n\
             # Third-party source fetching (from %fetch)\n\
             # ============================================================================="
        )
        .unwrap();
        for f in &graph.fetches {
            writeln!(
                out,
                "aros_fetch_archive(NAME \"{}\" ARCHIVE \"{}\" SUFFIXES \"{}\" ORIGINS \"{}\"\n\
                 \x20   LOCATION \"{}\" DESTINATION \"{}\" PATCH_ORIGINS \"{}\" PATCHES \"{}\")",
                f.name,
                f.archive,
                f.suffixes,
                f.origins,
                f.location,
                f.destination,
                f.patch_origins,
                f.patches
            )
            .unwrap();
        }
        writeln!(out).unwrap();
    }

    // Hand-written Make rules that stage headers. These cannot be transpiled,
    // so they are declared for CMake to check against its list of rules that
    // have a static counterpart. A rule appearing upstream that nobody has
    // handled then surfaces at configure time instead of as a missing header.
    if !graph.adhoc_header_rules.is_empty() {
        writeln!(
            out,
            "# =============================================================================\n\
             # Hand-written header staging rules (need a static CMake counterpart)\n\
             # ============================================================================="
        )
        .unwrap();
        for rule in &graph.adhoc_header_rules {
            writeln!(
                out,
                "aros_adhoc_header_rule(FILE {} LINE {} ROOT {} DEST {} PREREQS {})",
                cmake_arg(&rule.file),
                rule.line,
                cmake_arg(&rule.root),
                cmake_arg(&rule.dest),
                cmake_arg(&rule.prereqs)
            )
            .unwrap();
        }
        writeln!(out).unwrap();
    }

    // 1. Concrete Module Targets
    for target in graph.targets.values() {
        let macro_name = match target.module_type {
            ModuleType::Library => "aros_add_library",
            ModuleType::Device => "aros_add_device",
            ModuleType::Resource => "aros_add_resource",
            ModuleType::Hidd => "aros_add_hidd",
            ModuleType::Datatype => "aros_add_datatype",
            ModuleType::Gadget => "aros_add_gadget",
            ModuleType::Mcc => "aros_add_mcc",
            ModuleType::Program => "aros_add_program",
            ModuleType::ProgramGroup => "aros_add_programs",
            ModuleType::SimpleModule => "aros_add_module_simple",
            ModuleType::LinkLib => "aros_add_linklib",
            _ => "aros_add_custom_target",
        };

        // Every declaration is emitted, whatever architecture its sources belong
        // to. Restricting the emission was tempting, but a hard-coded
        // `if(AROS_TARGET_PLATFORM STREQUAL "pc")` around the declaration made
        // 46 targets disappear from the build graph entirely, so nothing could
        // report on them: they were neither built nor listed as skipped, and a
        // newly added arch/ directory would have joined them silently.
        //
        // aros_gate_arch() in cmake/AROS.cmake does the filtering instead. It
        // reads AROS_ARCH_SOURCE_DIRS, so it covers every architecture rather
        // than the four spelled out here, and it excludes the target from `all`
        // while keeping it nameable, which is what makes it possible to ask
        // whether a foreign-architecture target would build.
        writeln!(out, "{macro_name}(").unwrap();
        writeln!(out, "    TARGET {}", target.target_name).unwrap();
        writeln!(out, "    MMAKE_ID {}", target.mmake_name).unwrap();
        if !target.link_libs.is_empty() {
            let libs: Vec<String> = target.link_libs.iter().map(|l| cmake_arg(l)).collect();
            writeln!(out, "    LIBS {}", libs.join(" ")).unwrap();
        }
        if let Some(suffix) = &target.mod_suffix {
            writeln!(out, "    MODTYPE {suffix}").unwrap();
        }
        writeln!(
            out,
            "    DIRECTORY \"${{CMAKE_SOURCE_DIR}}/{}\"",
            target.dir_path.display()
        )
        .unwrap();

        if !target.source_files.is_empty() {
            writeln!(out, "    SOURCES {}", target.source_files.join(" ")).unwrap();
        }

        if !target.use_libs.is_empty() {
            writeln!(out, "    USELIBS {}", target.use_libs.join(" ")).unwrap();
        }

        if !target.include_dirs.is_empty() {
            let quoted: Vec<String> = target.include_dirs.iter().map(|d| cmake_arg(d)).collect();
            writeln!(out, "    INCLUDES {}", quoted.join(" ")).unwrap();
        }

        // Architecture-conditional includes are emitted as `<tag>|<path>` pairs.
        // CMake keeps the ones whose tag applies to the configured target; see
        // aros_arch_include_tags() in cmake/AROS.cmake.
        if !target.arch_includes.is_empty() {
            let pairs: Vec<String> = target
                .arch_includes
                .iter()
                .map(|(tag, dir)| cmake_arg(&format!("{tag}|{dir}")))
                .collect();
            writeln!(out, "    ARCH_INCLUDES {}", pairs.join(" ")).unwrap();
        }

        // Preprocessor state the sources depend on, from USER_CPPFLAGS /
        // USER_CFLAGS. Quoted so a value containing a CMake variable survives.
        if !target.defines.is_empty() {
            let quoted: Vec<String> = target.defines.iter().map(|d| cmake_arg(d)).collect();
            writeln!(out, "    DEFINES {}", quoted.join(" ")).unwrap();
        }
        if !target.undefines.is_empty() {
            let quoted: Vec<String> = target.undefines.iter().map(|d| cmake_arg(d)).collect();
            writeln!(out, "    UNDEFINES {}", quoted.join(" ")).unwrap();
        }
        // Architecture source overrides as "<tag>|<dir>|<f1>,<f2>,...".
        // CMake keeps the tags that apply, drops the same-named generic
        // sources and puts the architecture ones first, as the reference build
        // does (config/make.tmpl:1661).
        if !target.arch_sources.is_empty() {
            let entries: Vec<String> = target
                .arch_sources
                .iter()
                .map(|(tag, dir, files)| cmake_arg(&format!("{tag}|{dir}|{}", files.join(","))))
                .collect();
            writeln!(out, "    ARCH_SOURCES {}", entries.join(" ")).unwrap();
        }

        // Architecture-conditional flags from a make.opts, same "<tag>|<value>"
        // shape as ARCH_INCLUDES.
        if !target.arch_defines.is_empty() {
            let pairs: Vec<String> = target
                .arch_defines
                .iter()
                .map(|(tag, d)| cmake_arg(&format!("{tag}|{d}")))
                .collect();
            writeln!(out, "    ARCH_DEFINES {}", pairs.join(" ")).unwrap();
        }
        if !target.arch_compile_options.is_empty() {
            let pairs: Vec<String> = target
                .arch_compile_options
                .iter()
                .map(|(tag, o)| cmake_arg(&format!("{tag}|{o}")))
                .collect();
            writeln!(out, "    ARCH_COMPILE_OPTIONS {}", pairs.join(" ")).unwrap();
        }

        if !target.compile_options.is_empty() {
            let quoted: Vec<String> = target
                .compile_options
                .iter()
                .map(|o| cmake_arg(o))
                .collect();
            writeln!(out, "    COMPILE_OPTIONS {}", quoted.join(" ")).unwrap();
        }

        writeln!(out, ")").unwrap();
        writeln!(out).unwrap();
    }

    // 2. Meta-Targets derived from #MM and #MM-
    writeln!(
        out,
        "\n# ============================================================================="
    )
    .unwrap();
    writeln!(out, "# Declarative Meta-Targets (#MM and #MM-)").unwrap();
    writeln!(
        out,
        "# =============================================================================\n"
    )
    .unwrap();

    let all_metas: HashSet<&String> = graph.meta_targets.keys().collect();

    for (meta_name, deps) in &graph.meta_targets {
        // Only include dependencies that exist as concrete targets or meta targets
        let valid_deps: Vec<&String> = deps
            .iter()
            .filter(|dep| all_targets.contains(dep) || all_metas.contains(dep))
            .filter(|dep| *dep != meta_name)
            .collect();

        if !valid_deps.is_empty() && !all_targets.contains(meta_name) {
            writeln!(out, "if(NOT TARGET {meta_name})").unwrap();
            writeln!(out, "    add_custom_target({meta_name})").unwrap();
            writeln!(
                out,
                "    foreach(dep IN ITEMS {})",
                valid_deps
                    .iter()
                    .map(|s| s.as_str())
                    .collect::<Vec<_>>()
                    .join(" ")
            )
            .unwrap();
            writeln!(out, "        if(TARGET ${{dep}})").unwrap();
            writeln!(out, "            add_dependencies({meta_name} ${{dep}})").unwrap();
            writeln!(out, "        endif()").unwrap();
            writeln!(out, "    endforeach()").unwrap();
            writeln!(out, "endif()\n").unwrap();
        }
    }
    // Packages and the kickstart link, last: both check whether each member
    // is a configured target that produces a file, so the targets have to
    // exist by the time CMake reaches these calls.
    if !graph.packages.is_empty() {
        writeln!(
            out,
            "# ---- Packages and kickstart, from %make_package / %link_kickstart ----"
        )
        .unwrap();
        for pkg in &graph.packages {
            if pkg.resolved.is_empty() {
                continue;
            }
            let func = if pkg.is_kickstart {
                "aros_link_kickstart"
            } else {
                "aros_make_package"
            };
            writeln!(out, "{func}(").unwrap();
            writeln!(out, "    NAME {}", pkg.mmake).unwrap();
            writeln!(out, "    OUTPUT {}", cmake_arg(&pkg.output)).unwrap();
            if !pkg.arch.is_empty() {
                writeln!(out, "    ARCH {}", cmake_arg(&pkg.arch)).unwrap();
            }
            if !pkg.uselibs.is_empty() {
                let libs: Vec<String> = pkg.uselibs.iter().map(|l| cmake_arg(l)).collect();
                writeln!(out, "    USELIBS {}", libs.join(" ")).unwrap();
            }
            let ids: Vec<String> = pkg.resolved.iter().map(|m| cmake_arg(m)).collect();
            writeln!(out, "    MODULES {}", ids.join(" ")).unwrap();
            writeln!(out, ")").unwrap();
        }
        writeln!(out).unwrap();
    }



    out
}