//! Closed model for a named aggregate which publishes a header generated by a
//! single-source host C program.
//!
//! The scanner follows only one complete ownership chain: a named NOP target,
//! its directory-only setup target, the two include-root directory rules, an
//! exact SDK copy, a stdout-producing header rule, and a host-compiled C tool.
//! Anything outside that chain remains unmodelled and is returned with the
//! aggregate owner so selected graph edges can fail closed.

use crate::dirs::DirVars;
use crate::make_expr::{evaluate_make_list, MakeExprContext};
use crate::make_vars::ConditionalTruth;
use crate::make_vars::VarScope;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Component, Path, PathBuf};

/// One fully validated host-generated header chain.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HostHeaderRuleDecl {
    /// Named Make aggregate which owns the selected graph edge.
    pub owner: String,
    /// Named directory-only dependency of `owner`.
    pub setup_owner: String,
    /// Source-root-relative C translation unit, rendered for CMake.
    pub tool_source: String,
    /// Tool executable below the generated build directory.
    pub tool_output: String,
    /// Literal flags written in the Make compile recipe.
    pub host_compile_flags: Vec<String>,
    /// The source explicitly requests `$(HOST_CFLAGS)`; CMake must provide its
    /// configured, controlled equivalent rather than silently dropping it.
    pub use_configured_host_cflags: bool,
    /// Exact source working directory used by the stdout-producing command.
    pub source_workdir: String,
    /// Header path below both include roots.
    pub header: String,
    /// Exact source-tree prerequisites of the generated header.
    pub source_prerequisites: Vec<String>,
    /// Exact two directories prepared by the setup chain.
    pub setup_directories: Vec<String>,
    /// Primary generated header under GENINCDIR.
    pub primary_output: String,
    /// Byte-for-byte SDK mirror under AROS_INCLUDES.
    pub sdk_output: String,
}

/// A related host-header candidate that is outside the closed representation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HostHeaderRuleRejection {
    /// Best available named aggregate owner.
    pub owner: String,
    /// Why the complete chain could not be represented.
    pub reason: String,
}

#[derive(Debug, Clone)]
struct Rule {
    target: String,
    prerequisites: String,
    line: usize,
    state: ConditionalTruth,
    conditional_syntax: bool,
    recipes: Vec<(String, ConditionalTruth)>,
}

#[derive(Debug)]
struct LogicalLine {
    text: String,
    source_line: usize,
}

/// Collects complete, named single-C host-header chains from joined Make text.
///
/// `line_states` uses the zero-based positions of the joined source. `None`
/// means no Make conditional interpretation is available, so candidates
/// affected by conditional syntax are rejected.
#[must_use]
pub(crate) fn collect_host_header_rules(
    content: &str,
    source_root: &Path,
    rel_dir: &Path,
    scope: &VarScope,
    dirs: &DirVars,
    line_states: Option<&[ConditionalTruth]>,
) -> (Vec<HostHeaderRuleDecl>, Vec<HostHeaderRuleRejection>) {
    let rel_dir = match safe_relative_path(rel_dir) {
        Ok(path) => path,
        Err(reason) => {
            return (
                Vec::new(),
                vec![HostHeaderRuleRejection {
                    owner: owner_hint(content),
                    reason,
                }],
            );
        }
    };
    let source_root = match source_root.canonicalize() {
        Ok(path) => path,
        Err(error) => {
            return (
                Vec::new(),
                vec![HostHeaderRuleRejection {
                    owner: owner_hint(content),
                    reason: format!("source root cannot be canonicalized: {error}"),
                }],
            );
        }
    };
    let rules = parse_rules(content, line_states);
    let mut declarations = Vec::new();
    let mut rejections = Vec::new();
    let recipe_blocks = recipe_blocks_by_target(&rules);

    for aggregate in rules
        .iter()
        .filter(|rule| is_aggregate_candidate(rule, scope))
    {
        let owner = aggregate.target.trim().to_owned();
        let reject = |reason: String| HostHeaderRuleRejection {
            owner: owner.clone(),
            reason,
        };
        if !safe_target_name(&owner) {
            rejections.push(reject(
                "aggregate does not have one safe named target".into(),
            ));
            continue;
        }
        if recipe_blocks.get(&owner).copied().unwrap_or_default() != 1 {
            rejections.push(reject(
                "aggregate has duplicate or missing recipe-bearing rule blocks".into(),
            ));
            continue;
        }
        if let Some(reason) = rule_state_problem(aggregate) {
            rejections.push(reject(reason));
            continue;
        }
        if !is_nop_rule(aggregate) {
            rejections.push(reject(
                "aggregate recipe must be the single no-op $(NOP) command".into(),
            ));
            continue;
        }

        match validate_aggregate(aggregate, &rules, &source_root, &rel_dir, scope, dirs) {
            Ok(declaration) => declarations.push(declaration),
            Err(reason) => rejections.push(reject(reason)),
        }
    }

    (declarations, rejections)
}

fn validate_aggregate(
    aggregate: &Rule,
    rules: &[Rule],
    source_root: &Path,
    rel_dir: &Path,
    scope: &VarScope,
    dirs: &DirVars,
) -> Result<HostHeaderRuleDecl, String> {
    let owner = aggregate.target.trim();
    let expanded_prerequisites =
        expand_rooted_aliases(&aggregate.prerequisites, aggregate.line, scope, 0)?;
    let prereqs = words_without_order_only(&expanded_prerequisites)?;
    if prereqs.len() != 3 {
        return Err(format!(
            "aggregate must depend on exactly one setup target and a GENINCDIR/SDK header pair; found {} prerequisites",
            prereqs.len()
        ));
    }
    let mut primary_raw = None;
    let mut sdk_raw = None;
    let mut setup_owner = None;
    for prerequisite in &prereqs {
        if let Some(header) = header_tail(prerequisite, "$(GENINCDIR)/") {
            if primary_raw
                .replace((prerequisite.to_string(), header))
                .is_some()
            {
                return Err("aggregate has more than one GENINCDIR header prerequisite".into());
            }
        } else if let Some(header) = header_tail(prerequisite, "$(AROS_INCLUDES)/") {
            if sdk_raw
                .replace((prerequisite.to_string(), header))
                .is_some()
            {
                return Err("aggregate has more than one AROS_INCLUDES header prerequisite".into());
            }
        } else if safe_target_name(prerequisite) {
            if setup_owner.replace(prerequisite.to_string()).is_some() {
                return Err("aggregate has more than one named setup prerequisite".into());
            }
        } else {
            return Err(format!(
                "aggregate prerequisite `{prerequisite}` is outside the named setup/header contract"
            ));
        }
    }
    let (primary_raw, header) = primary_raw.ok_or("aggregate has no GENINCDIR header")?;
    let (sdk_raw, sdk_header) = sdk_raw.ok_or("aggregate has no AROS_INCLUDES header")?;
    if header != sdk_header || !safe_relative_text(&header) {
        return Err("GENINCDIR and SDK header paths do not name one safe relative header".into());
    }
    if !is_header_path(&header) {
        return Err("generated output is not a header path ending in .h".into());
    }
    let setup_owner = setup_owner.ok_or("aggregate has no named directory setup prerequisite")?;

    let setup_rule = unique_rule(rules, &setup_owner)?;
    check_related_rule(setup_rule)?;
    if !setup_rule.recipes.is_empty() {
        return Err("setup owner must be a dependency-only named rule".into());
    }
    let header_parent = Path::new(&header)
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .ok_or("header must live below an include directory")?
        .to_string_lossy()
        .replace('\\', "/");
    let gen_directory = format!("$(GENINCDIR)/{header_parent}");
    let sdk_directory = format!("$(AROS_INCLUDES)/{header_parent}");
    let setup_prereqs = words_without_order_only(&setup_rule.prerequisites)?;
    if setup_prereqs != [gen_directory.as_str(), sdk_directory.as_str()]
        && setup_prereqs != [sdk_directory.as_str(), gen_directory.as_str()]
    {
        return Err("setup owner must depend on the two output parent directories".into());
    }

    let directory_rule = rules
        .iter()
        .filter(|rule| {
            target_words(&rule.target).is_some_and(|targets| {
                targets.len() == 2
                    && targets.contains(&gen_directory.as_str())
                    && targets.contains(&sdk_directory.as_str())
            })
        })
        .collect::<Vec<_>>();
    let [directory_rule] = directory_rule.as_slice() else {
        return Err("both output directories must have one shared %mkdir_q rule".into());
    };
    check_related_rule(directory_rule)?;
    if !directory_rule.prerequisites.trim().is_empty()
        || directory_rule.recipes.len() != 1
        || strip_silent(&directory_rule.recipes[0].0) != "%mkdir_q dir=$@"
    {
        return Err("output directories require one sole `%mkdir_q dir=$@` recipe".into());
    }

    let primary_output = format!("${{AROS_GENINC_DIR}}/{header}");
    let sdk_output = format!("${{AROS_SDK_INCLUDE_DIR}}/{header}");
    let copy_rule = unique_rule(rules, &sdk_raw)?;
    check_related_rule(copy_rule)?;
    if words_without_order_only(&copy_rule.prerequisites)? != [primary_raw.as_str()]
        || !is_literal_copy_recipe(copy_rule)
    {
        return Err("SDK mirror must be an exact literal `$<` to `$@` copy".into());
    }

    let header_rule = unique_rule(rules, &primary_raw)?;
    check_related_rule(header_rule)?;
    let header_prerequisites = words_without_order_only(&header_rule.prerequisites)?;
    let Some(tool_reference) = header_prerequisites.first() else {
        return Err("generated header has no host-tool prerequisite".into());
    };
    let tool_output = evaluate_one(
        tool_reference,
        header_rule.line,
        scope,
        dirs,
        source_root,
        rel_dir,
    )?;
    let tool_relative = tool_output
        .strip_prefix("${AROS_BUILD_DIR}/gen/")
        .ok_or("host tool output is not rooted below the generated build directory")?;
    if !tool_relative.starts_with(&format!(
        "{}/",
        rel_dir.to_string_lossy().replace('\\', "/")
    )) || !safe_relative_text(tool_relative)
    {
        return Err("host tool output escapes its declaring generated directory".into());
    }
    let (source_workdir, generated_arguments) =
        validate_stdout_recipe(header_rule, tool_reference, &header, rel_dir)?;
    if !generated_arguments.is_empty() {
        return Err("host header invocation accepts no arbitrary tool arguments".into());
    }
    let expected_workdir = source_workdir_for(rel_dir);
    if source_workdir != expected_workdir {
        return Err(
            "stdout command working directory is not the declaring source directory".into(),
        );
    }

    let mut source_prerequisites = Vec::new();
    for raw in header_prerequisites.iter().skip(1) {
        let expanded = evaluate_make_list(
            raw,
            &context(header_rule.line, scope, dirs, source_root, rel_dir),
        )
        .map_err(|error| format!("cannot resolve header prerequisite `{raw}`: {error}"))?;
        for item in expanded {
            let source = source_input(&item, rel_dir)?;
            validate_source_file(source_root, &source)?;
            let rendered = source_path_for(&source);
            if !source_prerequisites.contains(&rendered) {
                source_prerequisites.push(rendered);
            }
        }
    }
    if source_prerequisites.is_empty() {
        return Err("generated header has no declared source-file prerequisites".into());
    }

    let tool_rule = unique_rule(rules, tool_reference)?;
    check_related_rule(tool_rule)?;
    let tool_prerequisites = words_without_order_only(&tool_rule.prerequisites)?;
    if tool_prerequisites.len() != 1 {
        return Err("host tool must be compiled from exactly one C source".into());
    }
    let source = source_input(
        &evaluate_one(
            tool_prerequisites[0],
            tool_rule.line,
            scope,
            dirs,
            source_root,
            rel_dir,
        )?,
        rel_dir,
    )?;
    if Path::new(&source)
        .extension()
        .is_none_or(|extension| extension != "c")
    {
        return Err("host tool prerequisite is not one C source file".into());
    }
    validate_source_file(source_root, &source)?;
    if tool_rule.recipes.len() != 2 {
        return Err("host tool requires one bounded %mkdirs_q and one compile recipe".into());
    }
    let (host_compile_flags, use_configured_host_cflags) =
        validate_compile_recipe(tool_rule, tool_reference)?;
    let tool_source = source_path_for(&source);

    let tool_mkdir = format!("%mkdirs_q $(dir {tool_reference})");
    if tool_rule.recipes.len() != 2 || strip_silent(&tool_rule.recipes[0].0) != tool_mkdir {
        return Err("host tool requires one bounded %mkdirs_q and one compile recipe".into());
    }
    if !source_prerequisites.contains(&tool_source) {
        source_prerequisites.push(tool_source.clone());
    }

    let setup_directories = vec![
        format!("${{AROS_GENINC_DIR}}/{header_parent}"),
        format!("${{AROS_SDK_INCLUDE_DIR}}/{header_parent}"),
    ];
    Ok(HostHeaderRuleDecl {
        owner: owner.to_owned(),
        setup_owner,
        tool_source,
        tool_output,
        host_compile_flags,
        use_configured_host_cflags,
        source_workdir: expected_workdir,
        header,
        source_prerequisites,
        setup_directories,
        primary_output,
        sdk_output,
    })
}

fn validate_stdout_recipe(
    rule: &Rule,
    tool_reference: &str,
    header: &str,
    rel_dir: &Path,
) -> Result<(String, Vec<String>), String> {
    if rule.recipes.len() != 2 || !safe_echo_line(&rule.recipes[0].0, "$@") {
        return Err("header rule requires one bounded ECHO and one stdout command".into());
    }
    let command = strip_silent(&rule.recipes[1].0);
    let prefix = "cd $(SRCDIR)/$(CURDIR); ";
    let invocation = command
        .strip_prefix(prefix)
        .ok_or("stdout command must cd to the exact source directory")?;
    let (program, redirect) = invocation
        .split_once('>')
        .ok_or("stdout command must capture output to `$@`")?;
    if redirect.trim() != "$@" || program.contains([';', '&', '|', '<', '`']) {
        return Err("stdout command contains unsupported shell syntax or redirect".into());
    }
    let mut words = program.split_whitespace();
    if words.next() != Some(tool_reference) {
        return Err("stdout command does not invoke its declared tool prerequisite".into());
    }
    let arguments = words.map(str::to_owned).collect::<Vec<_>>();
    if arguments.iter().any(|argument| !safe_literal(argument)) {
        return Err("stdout command has non-literal tool arguments".into());
    }
    if !is_header_path(header) {
        return Err("stdout output is not a header".into());
    }
    Ok((source_workdir_for(rel_dir), arguments))
}

fn validate_compile_recipe(
    rule: &Rule,
    tool_reference: &str,
) -> Result<(Vec<String>, bool), String> {
    let compile = strip_silent(&rule.recipes[1].0);
    let words = compile.split_whitespace().collect::<Vec<_>>();
    if words.first() != Some(&"$(HOST_CC)")
        || words.len() < 5
        || words[words.len() - 2..] != ["-o", "$@"]
    {
        return Err("host tool compile recipe must be one $(HOST_CC) output command".into());
    }
    if strip_silent(&rule.recipes[0].0) != format!("%mkdirs_q $(dir {tool_reference})") {
        return Err("host tool must create only its declared output directory".into());
    }
    let Some(source_pos) = words.iter().position(|word| *word == "$<") else {
        return Err("host tool compile recipe must compile its sole C prerequisite".into());
    };
    if source_pos < 2 {
        return Err("host tool compile recipe has no explicit flags policy".into());
    }
    let mut flags = Vec::new();
    let mut use_host_cflags = false;
    for flag in &words[1..source_pos] {
        if *flag == "$(HOST_CFLAGS)" {
            if use_host_cflags {
                return Err("HOST_CFLAGS occurs more than once in the compile recipe".into());
            }
            use_host_cflags = true;
        } else if safe_literal(flag) {
            flags.push((*flag).to_owned());
        } else {
            return Err(format!(
                "compile flag `{flag}` is not a safe literal or HOST_CFLAGS"
            ));
        }
    }
    if words[source_pos + 1..] != ["-o", "$@"] {
        return Err("host tool compile recipe has arguments outside source and output".into());
    }
    Ok((flags, use_host_cflags))
}

fn is_aggregate_candidate(rule: &Rule, scope: &VarScope) -> bool {
    if !safe_target_name(rule.target.trim())
        || rule.state == ConditionalTruth::False
        || rule.recipes.is_empty()
    {
        return false;
    }
    let Ok(expanded) = expand_rooted_aliases(&rule.prerequisites, rule.line, scope, 0) else {
        return false;
    };
    let prerequisites = expanded.split_whitespace().collect::<Vec<_>>();
    if prerequisites.len() != 3 {
        return false;
    }
    let gen_header = prerequisites
        .iter()
        .find_map(|path| header_tail(path, "$(GENINCDIR)/"));
    let sdk_header = prerequisites
        .iter()
        .find_map(|path| header_tail(path, "$(AROS_INCLUDES)/"));
    let named_setup = prerequisites
        .iter()
        .filter(|path| safe_target_name(path))
        .count()
        == 1;
    gen_header.as_ref().is_some_and(|header| {
        Some(header) == sdk_header.as_ref() && is_header_path(header) && named_setup
    })
}

/// Expands only file-local aliases while preserving the three path roots this
/// scanner must classify. General expression evaluation is used for file-list
/// prerequisites; this small pass is solely for root identity in Make rules.
fn expand_rooted_aliases(
    raw: &str,
    line: usize,
    scope: &VarScope,
    depth: usize,
) -> Result<String, String> {
    if depth >= 16 {
        return Err("Make alias expansion exceeded its bounded depth".into());
    }
    let mut output = String::with_capacity(raw.len());
    let mut rest = raw;
    while let Some(start) = rest.find("$(") {
        output.push_str(&rest[..start]);
        let after = &rest[start + 2..];
        let end = matching_paren(after).ok_or("unterminated Make alias")?;
        let name = &after[..end];
        if name.is_empty() || name.contains([' ', '$']) {
            return Err(format!("unsupported Make alias `$({name})`"));
        }
        if matches!(
            name,
            "GENINCDIR" | "AROS_INCLUDES" | "GENDIR" | "SRCDIR" | "CURDIR"
        ) {
            output.push_str("$(");
            output.push_str(name);
            output.push(')');
        } else {
            if scope.conditionally_assigned_before(name, line) {
                return Err(format!(
                    "Make alias `{name}` depends on an unresolved conditional"
                ));
            }
            let value = scope
                .raw_at(name, line)
                .ok_or_else(|| format!("unresolved Make alias `{name}`"))?;
            output.push_str(&expand_rooted_aliases(&value, line, scope, depth + 1)?);
        }
        rest = &after[end + 1..];
    }
    output.push_str(rest);
    Ok(output)
}

fn matching_paren(text: &str) -> Option<usize> {
    let mut depth = 1usize;
    let bytes = text.as_bytes();
    let mut index = 0usize;
    while index < bytes.len() {
        match bytes[index] {
            b'$' if bytes.get(index + 1) == Some(&b'(') => {
                depth += 1;
                index += 1;
            }
            b')' => {
                depth -= 1;
                if depth == 0 {
                    return Some(index);
                }
            }
            _ => {}
        }
        index += 1;
    }
    None
}

fn is_nop_rule(rule: &Rule) -> bool {
    rule.recipes.len() == 1 && is_nop_command(&rule.recipes[0].0)
}

fn is_nop_command(line: &str) -> bool {
    strip_silent(line) == "$(NOP)"
}

fn is_literal_copy_recipe(rule: &Rule) -> bool {
    if rule.recipes.len() == 1 {
        return strip_silent(&rule.recipes[0].0) == "$(CP) $< $@";
    }
    rule.recipes.len() == 2
        && safe_echo_line(&rule.recipes[0].0, "$<")
        && strip_silent(&rule.recipes[1].0) == "$(CP) $< $@"
}

fn safe_echo_line(line: &str, required_placeholder: &str) -> bool {
    let command = strip_silent(line);
    let Some(message) = command.strip_prefix("$(ECHO) ") else {
        return false;
    };
    !message.is_empty()
        && message.contains(required_placeholder)
        && !message
            .replace("$<", "")
            .replace("$@", "")
            .contains([';', '&', '|', '<', '>', '`', '$'])
        && message
            .chars()
            .filter(|character| *character == '"')
            .count()
            % 2
            == 0
        && !message.contains(['\n', '\r'])
}

fn unique_rule<'a>(rules: &'a [Rule], target: &str) -> Result<&'a Rule, String> {
    let matches = rules
        .iter()
        .filter(|rule| rule.target.trim() == target && rule.state != ConditionalTruth::False)
        .collect::<Vec<_>>();
    match matches.as_slice() {
        [rule] => Ok(rule),
        [] => Err(format!("required related rule `{target}` is missing")),
        _ => Err(format!(
            "related target `{target}` has multiple rule blocks"
        )),
    }
}

fn check_related_rule(rule: &Rule) -> Result<(), String> {
    if rule.state == ConditionalTruth::Unknown
        || rule
            .recipes
            .iter()
            .any(|(_, state)| *state == ConditionalTruth::Unknown)
    {
        return Err(format!(
            "related rule `{}` is guarded by an unresolved Make conditional",
            rule.target.trim()
        ));
    }
    if rule.conditional_syntax {
        return Err(format!(
            "conditional syntax affects related rule `{}`",
            rule.target.trim()
        ));
    }
    Ok(())
}

fn rule_state_problem(rule: &Rule) -> Option<String> {
    if rule.state == ConditionalTruth::Unknown
        || rule
            .recipes
            .iter()
            .any(|(_, state)| *state == ConditionalTruth::Unknown)
    {
        return Some("aggregate owner or recipe has an unresolved conditional state".into());
    }
    rule.conditional_syntax
        .then(|| "conditional syntax affects the aggregate rule".into())
}

fn recipe_blocks_by_target(rules: &[Rule]) -> BTreeMap<String, usize> {
    let mut result = BTreeMap::new();
    for rule in rules.iter().filter(|rule| {
        rule.state != ConditionalTruth::False
            && rule
                .recipes
                .iter()
                .any(|(_, state)| *state != ConditionalTruth::False)
    }) {
        *result.entry(rule.target.trim().to_owned()).or_default() += 1;
    }
    result
}

fn parse_rules(content: &str, line_states: Option<&[ConditionalTruth]>) -> Vec<Rule> {
    let mut rules = Vec::new();
    let mut current: Option<Rule> = None;
    let mut conditional_depth = 0usize;
    for logical in logical_lines(content) {
        let state = line_states.map_or(ConditionalTruth::True, |states| {
            states
                .get(logical.source_line)
                .copied()
                .unwrap_or(ConditionalTruth::Unknown)
        });
        if logical.text.starts_with('\t') {
            if let Some(rule) = current.as_mut() {
                if rule.state == ConditionalTruth::False || state == ConditionalTruth::False {
                    continue;
                }
                if line_states.is_none() && conditional_depth > 0 {
                    rule.conditional_syntax = true;
                }
                rule.recipes.push((logical.text.trim().to_owned(), state));
            }
            continue;
        }
        let text = logical.text.trim();
        if text.is_empty() || text.starts_with('#') {
            continue;
        }
        if let Some(directive) = conditional_directive(text) {
            if line_states.is_none() {
                if let Some(rule) = current.as_mut() {
                    rule.conditional_syntax = true;
                }
            }
            match directive {
                ConditionalDirective::Open => conditional_depth += 1,
                ConditionalDirective::Branch => {}
                ConditionalDirective::Close => {
                    conditional_depth = conditional_depth.saturating_sub(1);
                }
            }
            continue;
        }
        if let Some(rule) = current.take() {
            rules.push(rule);
        }
        let Some((target, prerequisites)) = text.split_once(':') else {
            continue;
        };
        let target = target.trim();
        if target.is_empty()
            || prerequisites.starts_with([':', '='])
            || target.contains(['\\', ';'])
        {
            continue;
        }
        current = Some(Rule {
            target: target.to_owned(),
            prerequisites: prerequisites.trim().to_owned(),
            line: logical.source_line,
            state,
            conditional_syntax: line_states.is_none() && conditional_depth > 0,
            recipes: Vec::new(),
        });
    }
    if let Some(rule) = current {
        rules.push(rule);
    }
    rules
}

#[derive(Clone, Copy)]
enum ConditionalDirective {
    Open,
    Branch,
    Close,
}

fn conditional_directive(line: &str) -> Option<ConditionalDirective> {
    match line.split_whitespace().next()? {
        "ifeq" | "ifneq" | "ifdef" | "ifndef" => Some(ConditionalDirective::Open),
        "else" => Some(ConditionalDirective::Branch),
        "endif" => Some(ConditionalDirective::Close),
        _ => None,
    }
}

fn logical_lines(content: &str) -> Vec<LogicalLine> {
    let mut result = Vec::new();
    let mut pending: Option<(String, usize)> = None;
    for (source_line, physical) in content.lines().enumerate() {
        let (line, first_line) = if let Some((mut previous, first_line)) = pending.take() {
            previous.push_str(physical.trim_start());
            (previous, first_line)
        } else {
            (physical.to_owned(), source_line)
        };
        let trimmed = line.trim_end();
        if let Some(without_slash) = trimmed.strip_suffix('\\') {
            pending = Some((format!("{} ", without_slash.trim_end()), first_line));
        } else {
            result.push(LogicalLine {
                text: line,
                source_line: first_line,
            });
        }
    }
    if let Some((text, source_line)) = pending {
        result.push(LogicalLine { text, source_line });
    }
    result
}

fn evaluate_one(
    expression: &str,
    line: usize,
    scope: &VarScope,
    dirs: &DirVars,
    source_root: &Path,
    rel_dir: &Path,
) -> Result<String, String> {
    let values = evaluate_make_list(
        expression,
        &context(line, scope, dirs, source_root, rel_dir),
    )
    .map_err(|error| format!("cannot resolve Make expression `{expression}`: {error}"))?;
    if values.len() != 1 {
        return Err(format!(
            "Make expression `{expression}` expands to {} words, not one",
            values.len()
        ));
    }
    let value = values.into_iter().next().expect("one value checked");
    if value.contains([';', '\n', '\r', '\"', '\'']) {
        return Err(format!(
            "Make expression `{expression}` contains unsafe path syntax"
        ));
    }
    Ok(value)
}

const fn context<'a>(
    line: usize,
    scope: &'a VarScope,
    dirs: &'a DirVars,
    source_root: &'a Path,
    rel_dir: &'a Path,
) -> MakeExprContext<'a> {
    MakeExprContext::new(scope, dirs, line, source_root, rel_dir)
}

fn words_without_order_only(prerequisites: &str) -> Result<Vec<&str>, String> {
    let words = prerequisites
        .split('|')
        .next()
        .unwrap_or_default()
        .split_whitespace()
        .collect::<Vec<_>>();
    if prerequisites.contains('|') {
        return Err("order-only prerequisites are outside the host-header contract".into());
    }
    Ok(words)
}

fn header_tail(path: &str, root: &str) -> Option<String> {
    path.strip_prefix(root).map(str::to_owned)
}

fn is_header_path(path: &str) -> bool {
    Path::new(path)
        .extension()
        .is_some_and(|extension| extension.eq_ignore_ascii_case("h"))
}

fn target_words(target: &str) -> Option<Vec<&str>> {
    let targets = target.split_whitespace().collect::<Vec<_>>();
    (!targets.is_empty()).then_some(targets)
}

fn strip_silent(recipe: &str) -> &str {
    recipe.strip_prefix('@').unwrap_or(recipe).trim()
}

fn safe_target_name(value: &str) -> bool {
    !value.is_empty()
        && !value.starts_with('.')
        && value
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || "_.+-".contains(character))
}

fn safe_relative_text(value: &str) -> bool {
    !value.is_empty()
        && !value.starts_with('/')
        && !value.contains(['$', ';', '\\', '"', '\'', '\n', '\r'])
        && Path::new(value)
            .components()
            .all(|component| matches!(component, Component::Normal(_)))
}

fn safe_literal(value: &str) -> bool {
    !value.is_empty()
        && value
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || "_./+-=,:".contains(character))
}

fn safe_relative_path(path: &Path) -> Result<PathBuf, String> {
    if path.is_absolute()
        || path
            .components()
            .any(|component| !matches!(component, Component::Normal(_)))
    {
        return Err(format!(
            "declaring directory `{}` is not source-relative",
            path.display()
        ));
    }
    Ok(path.to_path_buf())
}

fn source_input(value: &str, rel_dir: &Path) -> Result<String, String> {
    let source_path = if let Some(path) = value.strip_prefix("${AROS_SOURCE_DIR}/") {
        path
    } else if value == "${AROS_SOURCE_DIR}" {
        return Err("source prerequisite names the source root, not a file".into());
    } else if value.starts_with("${") {
        return Err(format!(
            "source prerequisite `{value}` uses a non-source root"
        ));
    } else {
        value
    };
    let source_path = Path::new(source_path);
    if source_path.is_absolute() {
        return Err(format!("source prerequisite `{value}` is absolute"));
    }
    let relative = if value.starts_with("${AROS_SOURCE_DIR}/") {
        source_path.to_path_buf()
    } else {
        rel_dir.join(source_path)
    };
    let relative = safe_relative_path(&relative)?;
    let rendered = relative.to_string_lossy().replace('\\', "/");
    if !safe_relative_text(&rendered) {
        return Err(format!(
            "source prerequisite `{value}` is not a safe relative path"
        ));
    }
    Ok(rendered)
}

fn source_path_for(relative: &str) -> String {
    format!("${{AROS_SOURCE_DIR}}/{relative}")
}

fn source_workdir_for(rel_dir: &Path) -> String {
    if rel_dir.as_os_str().is_empty() {
        "${AROS_SOURCE_DIR}".to_owned()
    } else {
        source_path_for(&rel_dir.to_string_lossy().replace('\\', "/"))
    }
}

fn validate_source_file(source_root: &Path, relative: &str) -> Result<(), String> {
    let mut path = source_root.to_path_buf();
    for component in Path::new(relative).components() {
        let Component::Normal(component) = component else {
            return Err(format!(
                "source prerequisite `{relative}` escapes the source tree"
            ));
        };
        path.push(component);
        let metadata = fs::symlink_metadata(&path)
            .map_err(|error| format!("source prerequisite `{relative}` is missing: {error}"))?;
        if metadata.file_type().is_symlink() {
            return Err(format!(
                "source prerequisite `{relative}` crosses a symlink"
            ));
        }
    }
    if !path.is_file() {
        return Err(format!(
            "source prerequisite `{relative}` is not a regular file"
        ));
    }
    Ok(())
}

fn owner_hint(content: &str) -> String {
    content
        .lines()
        .find_map(|line| {
            let line = line.trim();
            let (target, prereqs) = line.split_once(':')?;
            (prereqs.contains("$(GENINCDIR)/") || prereqs.contains("$(AROS_INCLUDES)/"))
                .then(|| target.trim().to_owned())
        })
        .unwrap_or_else(|| "<unknown-owner>".to_owned())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::make_vars::collect_vars_with_context;
    use std::io::{self, Write};
    use std::process::Command;

    const MUI_REL: &str = "workbench/libs/muimaster";

    fn source_root() -> PathBuf {
        crate::testing::root()
    }

    fn mui_text(root: &Path) -> String {
        let text = fs::read_to_string(root.join(MUI_REL).join("mmakefile.src")).unwrap();
        crate::parser::join_continuations(&text)
    }

    fn scan(
        text: &str,
        root: &Path,
        rel_dir: &Path,
        states: Option<&[ConditionalTruth]>,
    ) -> (Vec<HostHeaderRuleDecl>, Vec<HostHeaderRuleRejection>) {
        let mut target = crate::testing::target_context("x86_64", "pc", "soft");
        target.variant = Some(String::new());
        let scope = collect_vars_with_context(text, &target);
        let dirs = DirVars::load(root);
        collect_host_header_rules(text, root, rel_dir, &scope, &dirs, states)
    }

    fn copy_header_tree(source: &Path, destination: &Path) -> io::Result<()> {
        for entry in fs::read_dir(source)? {
            let entry = entry?;
            let source_path = entry.path();
            let file_type = entry.file_type()?;
            if file_type.is_symlink() {
                continue;
            }
            let relative = source_path.strip_prefix(source).unwrap();
            let destination_path = destination.join(relative);
            if file_type.is_dir() {
                copy_header_tree(&source_path, &destination_path)?;
            } else if file_type.is_file()
                && source_path
                    .extension()
                    .is_some_and(|extension| extension.eq_ignore_ascii_case("h"))
            {
                fs::create_dir_all(destination_path.parent().unwrap())?;
                fs::copy(source_path, destination_path)?;
            }
        }
        Ok(())
    }

    #[test]
    fn actual_mui_chain_is_generic_and_expands_classincludes() {
        let root = source_root();
        let source = mui_text(&root);
        let renamed = source
            .replace("includes-libraries-mui", "renamed-public-header-owner")
            .replace("includes-mui-setup", "renamed-public-header-setup")
            .replace("BUILDINCTOOL", "HOST_HEADER_GENERATOR");
        let (declarations, rejected) = scan(&renamed, &root, Path::new(MUI_REL), None);
        assert!(rejected.is_empty(), "unexpected rejections: {rejected:#?}");
        assert_eq!(declarations.len(), 1);
        let declaration = &declarations[0];
        assert_eq!(declaration.owner, "renamed-public-header-owner");
        assert_eq!(declaration.setup_owner, "renamed-public-header-setup");
        assert_eq!(declaration.header, "libraries/mui.h");
        assert!(declaration.use_configured_host_cflags);
        assert!(declaration.host_compile_flags.is_empty());
        assert!(declaration
            .source_prerequisites
            .contains(&format!("${{AROS_SOURCE_DIR}}/{MUI_REL}/mui.h")));
        assert!(declaration
            .source_prerequisites
            .contains(&format!("${{AROS_SOURCE_DIR}}/{MUI_REL}/macros.h")));
        assert!(declaration
            .source_prerequisites
            .iter()
            .any(|input| input.contains("/classes/")));
        assert_eq!(
            declaration.primary_output,
            "${AROS_GENINC_DIR}/libraries/mui.h"
        );
        assert_eq!(
            declaration.sdk_output,
            "${AROS_SDK_INCLUDE_DIR}/libraries/mui.h"
        );
    }

    #[test]
    fn unrelated_host_compiler_and_file_rules_are_ignored() {
        let root = source_root();
        let source = "ordinary-file: input.c\n\t$(HOST_CC) $< -o $@\n";
        let (declarations, rejected) = scan(source, &root, Path::new("tools/unrelated"), None);
        assert!(declarations.is_empty());
        assert!(rejected.is_empty());
    }

    #[test]
    fn non_host_header_aggregates_are_not_claimed_by_this_capability() {
        let root = source_root();
        let source = "copy-pair: setup $(GENINCDIR)/include/public.h $(AROS_INCLUDES)/include/public.h\n\
broad-include-aggregate: $(GENINCDIR)/one.h $(AROS_INCLUDES)/one.h $(GENINCDIR)/two.h $(AROS_INCLUDES)/two.h\n\
\t@$(NOP)\n";
        let (declarations, rejected) = scan(source, &root, Path::new("unrelated"), None);
        assert!(declarations.is_empty());
        assert!(rejected.is_empty());
    }

    #[test]
    fn unsafe_compile_command_and_unresolved_source_input_reject_the_owner() {
        let root = source_root();
        let source = mui_text(&root);
        let unsafe_command = source.replace(
            "@$(HOST_CC) $(HOST_CFLAGS) $< -o $@",
            "@$(HOST_CC) $(HOST_CFLAGS) $< -o $@; touch unsafe",
        );
        let (_, rejected) = scan(&unsafe_command, &root, Path::new(MUI_REL), None);
        assert_eq!(rejected.len(), 1, "{rejected:#?}");
        assert_eq!(rejected[0].owner, "includes-libraries-mui");

        let unresolved = source.replace(
            "$(BUILDINCTOOL) mui.h macros.h $(CLASSINCLUDES)",
            "$(BUILDINCTOOL) mui.h macros.h $(CLASSINCLUDES) $(UNKNOWN_HEADER)",
        );
        let (_, rejected) = scan(&unresolved, &root, Path::new(MUI_REL), None);
        assert_eq!(rejected.len(), 1, "{rejected:#?}");
        assert!(rejected[0].reason.contains("cannot resolve"));
    }

    #[test]
    fn unknown_conditional_owner_is_rejected_and_false_owner_is_ignored() {
        let root = source_root();
        let source = mui_text(&root);
        let line_count = source.lines().count();
        let mut states = vec![ConditionalTruth::True; line_count];
        let owner_line = source
            .lines()
            .position(|line| line.starts_with("includes-libraries-mui :"))
            .unwrap();
        states[owner_line] = ConditionalTruth::Unknown;
        let (_, rejected) = scan(&source, &root, Path::new(MUI_REL), Some(&states));
        assert_eq!(rejected.len(), 1);
        assert_eq!(rejected[0].owner, "includes-libraries-mui");

        states[owner_line] = ConditionalTruth::False;
        let (declarations, rejected) = scan(&source, &root, Path::new(MUI_REL), Some(&states));
        assert!(declarations.is_empty());
        assert!(rejected.is_empty());
    }

    #[test]
    fn cmake_helper_builds_the_owner_scoped_pair() {
        if Command::new("cmake").arg("--version").output().is_err() {
            return;
        }
        let temp = tempfile::tempdir().unwrap();
        let source = temp.path().join("source");
        fs::create_dir_all(&source).unwrap();
        let tool = source.join("emit.c");
        let additional_input = source.join("dependency.h");
        fs::write(
            &tool,
            "#include <stdio.h>\nint main(void) { puts(\"#define FIXTURE_HEADER 1\"); }\n",
        )
        .unwrap();
        fs::write(&additional_input, "#define DEPENDENCY_REVISION 1\n").unwrap();
        let helper = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../aros-cmake-engine/engine/HostHeaderRules.cmake")
            .canonicalize()
            .unwrap();
        let cmake_lists = temp.path().join("CMakeLists.txt");
        let mut file = fs::File::create(&cmake_lists).unwrap();
        writeln!(
            file,
            "cmake_minimum_required(VERSION 3.24)\nproject(host_header_rules C)\nset(AROS_SOURCE_DIR \"{}\")\nset(AROS_BUILD_DIR \"${{CMAKE_BINARY_DIR}}/build\")\nset(AROS_GENINC_DIR \"${{CMAKE_BINARY_DIR}}/geninc\")\nset(AROS_SDK_INCLUDE_DIR \"${{CMAKE_BINARY_DIR}}/sdk\")\nset(AROS_HOST_CC \"${{CMAKE_C_COMPILER}}\")\nset(AROS_HOST_CFLAGS -O2 -w)\ninclude(\"{}\")\naros_host_header_rule(NAME fixture-owner SETUP_NAME fixture-setup TOOL_SOURCE \"${{AROS_SOURCE_DIR}}/emit.c\" TOOL_OUTPUT \"${{AROS_BUILD_DIR}}/gen/tool\" SOURCE_WORKDIR \"${{AROS_SOURCE_DIR}}\" HEADER fixture/header.h PRIMARY_OUTPUT \"${{AROS_GENINC_DIR}}/fixture/header.h\" SDK_OUTPUT \"${{AROS_SDK_INCLUDE_DIR}}/fixture/header.h\" USE_CONFIGURED_HOST_CFLAGS COMPILE_FLAGS -DFIXTURE=1 SOURCE_PREREQUISITES \"${{AROS_SOURCE_DIR}}/emit.c\" \"${{AROS_SOURCE_DIR}}/dependency.h\" SETUP_DIRECTORIES \"${{AROS_GENINC_DIR}}/fixture\" \"${{AROS_SDK_INCLUDE_DIR}}/fixture\")\n",
            source.display(),
            helper.display()
        )
        .unwrap();
        let configure = Command::new("cmake")
            .args(["-S", temp.path().to_str().unwrap(), "-B"])
            .arg(temp.path().join("build-tree"))
            .output()
            .unwrap();
        assert!(
            configure.status.success(),
            "{}",
            String::from_utf8_lossy(&configure.stderr)
        );
        let build = Command::new("cmake")
            .args(["--build"])
            .arg(temp.path().join("build-tree"))
            .args(["--target", "fixture-owner"])
            .output()
            .unwrap();
        assert!(
            build.status.success(),
            "{}",
            String::from_utf8_lossy(&build.stderr)
        );
        let generated = temp.path().join("build-tree/geninc/fixture/header.h");
        let copied = temp.path().join("build-tree/sdk/fixture/header.h");
        assert_eq!(fs::read(&generated).unwrap(), fs::read(&copied).unwrap());
        assert!(fs::read_to_string(generated)
            .unwrap()
            .contains("FIXTURE_HEADER 1"));
        let generated = temp.path().join("build-tree/geninc/fixture/header.h");
        let before_change = fs::metadata(&generated).unwrap().modified().unwrap();
        std::thread::sleep(std::time::Duration::from_millis(1100));
        fs::write(&additional_input, "#define DEPENDENCY_REVISION 2\n").unwrap();
        let rebuild = Command::new("cmake")
            .args(["--build"])
            .arg(temp.path().join("build-tree"))
            .args(["--target", "fixture-owner"])
            .output()
            .unwrap();
        assert!(
            rebuild.status.success(),
            "{}",
            String::from_utf8_lossy(&rebuild.stderr)
        );
        assert!(fs::metadata(generated).unwrap().modified().unwrap() > before_change);

        #[cfg(unix)]
        {
            use std::os::unix::fs::symlink;

            let generated_parent = temp.path().join("build-tree/geninc/fixture");
            let saved_parent = temp.path().join("saved-geninc-fixture");
            let outside = temp.path().join("outside-build-root");
            fs::create_dir_all(&outside).unwrap();
            fs::rename(&generated_parent, &saved_parent).unwrap();
            symlink(&outside, &generated_parent).unwrap();

            let unsafe_rebuild = Command::new("cmake")
                .args(["--build"])
                .arg(temp.path().join("build-tree"))
                .args(["--target", "fixture-owner"])
                .output()
                .unwrap();
            assert!(!unsafe_rebuild.status.success());
            let diagnostic = String::from_utf8_lossy(&unsafe_rebuild.stderr);
            assert!(
                diagnostic.contains("symlink") || diagnostic.contains("physically"),
                "expected runtime containment rejection, got: {diagnostic}"
            );
            assert!(!outside.join("header.h").exists());
        }
    }

    #[test]
    fn cmake_helper_cold_builds_the_actual_mui_generator_from_declared_inputs() {
        if Command::new("cmake").arg("--version").output().is_err() {
            return;
        }
        let root = source_root();
        let text = mui_text(&root);
        let (declarations, rejected) = scan(&text, &root, Path::new(MUI_REL), None);
        assert!(
            rejected.is_empty(),
            "unexpected source rejections: {rejected:#?}"
        );
        assert_eq!(declarations.len(), 1);
        let declaration = &declarations[0];

        let temp = tempfile::tempdir().unwrap();
        let source_copy = temp.path().join("source");
        let mut staged_inputs = declaration.source_prerequisites.clone();
        staged_inputs.push(declaration.tool_source.clone());
        staged_inputs.sort();
        staged_inputs.dedup();
        for rendered in &staged_inputs {
            let relative = rendered
                .strip_prefix("${AROS_SOURCE_DIR}/")
                .expect("source input must be rooted in AROS_SOURCE_DIR");
            let source = root.join(relative);
            let destination = source_copy.join(relative);
            fs::create_dir_all(destination.parent().unwrap()).unwrap();
            fs::copy(&source, &destination).unwrap_or_else(|error| {
                panic!(
                    "cannot stage declared source input {}: {error}",
                    source.display()
                )
            });
        }
        // buildincludes recursively reads quoted includes from the source
        // directory; stage those headers too while keeping CMake dependencies
        // restricted to the exact scanner-declared Make prerequisite list.
        copy_header_tree(&root.join(MUI_REL), &source_copy.join(MUI_REL)).unwrap();

        let helper = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../aros-cmake-engine/engine/HostHeaderRules.cmake")
            .canonicalize()
            .unwrap();
        let cmake_lists = temp.path().join("CMakeLists.txt");
        let mut file = fs::File::create(&cmake_lists).unwrap();
        writeln!(
            file,
            "cmake_minimum_required(VERSION 3.24)\nproject(actual_mui_host_header C)\nset(AROS_SOURCE_DIR \"{}\")\nset(AROS_BUILD_DIR \"${{CMAKE_BINARY_DIR}}/build\")\nset(AROS_GENINC_DIR \"${{CMAKE_BINARY_DIR}}/geninc\")\nset(AROS_SDK_INCLUDE_DIR \"${{CMAKE_BINARY_DIR}}/sdk\")\nset(AROS_HOST_CC \"${{CMAKE_C_COMPILER}}\")\nset(AROS_HOST_CFLAGS -O2 -w)\ninclude(\"{}\")\n",
            source_copy.display(),
            helper.display()
        )
        .unwrap();

        let tool_source = declaration
            .tool_source
            .strip_prefix("${AROS_SOURCE_DIR}/")
            .unwrap();
        let tool_output = declaration
            .tool_output
            .strip_prefix("${AROS_BUILD_DIR}/")
            .unwrap();
        let primary_output = declaration
            .primary_output
            .strip_prefix("${AROS_GENINC_DIR}/")
            .unwrap();
        let sdk_output = declaration
            .sdk_output
            .strip_prefix("${AROS_SDK_INCLUDE_DIR}/")
            .unwrap();
        let workdir = declaration
            .source_workdir
            .strip_prefix("${AROS_SOURCE_DIR}/")
            .unwrap();
        let setup_directories = declaration
            .setup_directories
            .iter()
            .map(|directory| {
                directory.strip_prefix("${AROS_GENINC_DIR}/").map_or_else(
                    || {
                        format!(
                            "\"${{AROS_SDK_INCLUDE_DIR}}/{}\"",
                            directory
                                .strip_prefix("${AROS_SDK_INCLUDE_DIR}/")
                                .expect("setup directory must use an include root")
                        )
                    },
                    |relative| format!("\"${{AROS_GENINC_DIR}}/{relative}\""),
                )
            })
            .collect::<Vec<_>>()
            .join(" ");
        writeln!(
            file,
            "aros_host_header_rule(\n  NAME actual-header-owner\n  SETUP_NAME actual-header-setup\n  TOOL_SOURCE \"${{AROS_SOURCE_DIR}}/{tool_source}\"\n  TOOL_OUTPUT \"${{AROS_BUILD_DIR}}/{tool_output}\"\n  SOURCE_WORKDIR \"${{AROS_SOURCE_DIR}}/{workdir}\"\n  HEADER {}\n  PRIMARY_OUTPUT \"${{AROS_GENINC_DIR}}/{primary_output}\"\n  SDK_OUTPUT \"${{AROS_SDK_INCLUDE_DIR}}/{sdk_output}\"\n  USE_CONFIGURED_HOST_CFLAGS\n  SOURCE_PREREQUISITES",
            declaration.header
        )
        .unwrap();
        for rendered in &declaration.source_prerequisites {
            let relative = rendered
                .strip_prefix("${AROS_SOURCE_DIR}/")
                .expect("source input must be rooted in AROS_SOURCE_DIR");
            writeln!(file, "    \"${{AROS_SOURCE_DIR}}/{relative}\"").unwrap();
        }
        writeln!(file, "  SETUP_DIRECTORIES {setup_directories}\n)\n").unwrap();

        let build_dir = temp.path().join("build-tree");
        let configure = Command::new("cmake")
            .args(["-S", temp.path().to_str().unwrap(), "-B"])
            .arg(&build_dir)
            .output()
            .unwrap();
        assert!(
            configure.status.success(),
            "{}",
            String::from_utf8_lossy(&configure.stderr)
        );
        let build_owner = || {
            Command::new("cmake")
                .args(["--build"])
                .arg(&build_dir)
                .args(["--target", "actual-header-owner"])
                .output()
                .unwrap()
        };
        let build = build_owner();
        assert!(
            build.status.success(),
            "{}{}",
            String::from_utf8_lossy(&build.stdout),
            String::from_utf8_lossy(&build.stderr)
        );

        let generated = build_dir.join("geninc").join(&declaration.header);
        let copied = build_dir.join("sdk").join(&declaration.header);
        let tool = build_dir.join("build").join(tool_output);
        let output = fs::read(&generated).unwrap();
        assert_eq!(output, fs::read(&copied).unwrap());
        let direct_staged = Command::new(&tool)
            .current_dir(source_copy.join(workdir))
            .output()
            .unwrap();
        assert!(direct_staged.status.success());
        assert_eq!(output, direct_staged.stdout);
        let direct_source = Command::new(&tool)
            .current_dir(root.join(MUI_REL))
            .output()
            .unwrap();
        assert!(direct_source.status.success());
        assert_eq!(output, direct_source.stdout);

        let initial_time = fs::metadata(&generated).unwrap().modified().unwrap();
        let repeated = build_owner();
        assert!(
            repeated.status.success(),
            "{}{}",
            String::from_utf8_lossy(&repeated.stdout),
            String::from_utf8_lossy(&repeated.stderr)
        );
        assert_eq!(
            fs::metadata(&generated).unwrap().modified().unwrap(),
            initial_time
        );

        let staged_mui_header = source_copy.join(MUI_REL).join("mui.h");
        assert!(
            declaration
                .source_prerequisites
                .iter()
                .any(|input| input.ends_with("/workbench/libs/muimaster/mui.h")),
            "mui.h must be a declared source prerequisite"
        );
        std::thread::sleep(std::time::Duration::from_millis(1100));
        let mut modified_header = fs::OpenOptions::new()
            .append(true)
            .open(&staged_mui_header)
            .unwrap();
        writeln!(modified_header, "\n/* staged prerequisite mutation */").unwrap();
        let rebuilt = build_owner();
        assert!(
            rebuilt.status.success(),
            "{}{}",
            String::from_utf8_lossy(&rebuilt.stdout),
            String::from_utf8_lossy(&rebuilt.stderr)
        );
        assert!(fs::metadata(&generated).unwrap().modified().unwrap() > initial_time);
        let mutated_direct = Command::new(&tool)
            .current_dir(source_copy.join(workdir))
            .output()
            .unwrap();
        assert!(mutated_direct.status.success());
        let mutated_output = fs::read(&generated).unwrap();
        assert_eq!(mutated_output, mutated_direct.stdout);
        assert_eq!(mutated_output, fs::read(&copied).unwrap());
    }
}
