//! Closed scanner for source-declared host-C header aggregates.
//!
//! The scanner recognizes one narrow shape: a `#MM <owner>` marker, a
//! dependency-only ordinary Make rule with that name, one source-local C host
//! tool, and a finite set of SDK headers written by that tool. An explicitly
//! declared `GENINCDIR` copy is recorded on its SDK header. Other Make syntax
//! is not interpreted as a producer.

use crate::dirs::DirVars;
use crate::make_expr::{evaluate_make_expr, evaluate_make_list, MakeExprContext};
use crate::make_vars::{strip_make_comment, variable_assignment, ConditionalTruth, VarScope};
use std::collections::{BTreeMap, HashSet};
use std::fs;
use std::path::{Component, Path};

const MAX_OUTPUTS: usize = 4096;
const MAX_MAKEFILE_BYTES: usize = 4 * 1024 * 1024;
const MAX_RELATIVE_PATH_BYTES: usize = 1024;

/// A source-owned aggregate of headers emitted by one local host-C tool.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HostHeaderAggregateDecl {
    /// The ordinary dependency-only Make target named by the `#MM` marker.
    pub owner: String,
    /// The executable name under `$(HOSTGENDIR)/tools/`.
    pub tool: String,
    /// The C source, relative to the selected source root.
    pub tool_source: String,
    /// Literal compiler flags from the tool's one compile recipe.
    pub host_compile_flags: Vec<String>,
    /// SDK headers generated by the tool, with optional explicit GEN mirrors.
    pub headers: Vec<HostHeaderAggregateOutput>,
}

/// One SDK header emitted by an aggregate host tool.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HostHeaderAggregateOutput {
    /// Header path relative to the SDK include root.
    pub header: String,
    /// Literal arguments passed to the host tool for this header.
    pub arguments: Vec<String>,
    /// Whether this exact SDK header also has a validated `GENINCDIR` copy.
    pub generated_mirror: bool,
}

/// A named candidate that could not be represented by the closed capability.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Rejection {
    pub owner: String,
    pub reason: String,
}

#[derive(Debug, Clone)]
struct LogicalLine {
    text: String,
    source_line: usize,
    state: ConditionalTruth,
    conditional_syntax: bool,
}

#[derive(Debug, Clone)]
struct Recipe {
    text: String,
    state: ConditionalTruth,
    conditional_syntax: bool,
}

#[derive(Debug, Clone)]
struct Rule {
    target: String,
    prerequisites: String,
    order_only: Option<String>,
    source_line: usize,
    state: ConditionalTruth,
    conditional_syntax: bool,
    inline_recipe: bool,
    recipes: Vec<Recipe>,
}

#[derive(Debug, Clone)]
struct Marker {
    owner: String,
    state: ConditionalTruth,
    conditional_syntax: bool,
    duplicate: bool,
}

#[derive(Debug)]
struct CandidateResult {
    owner: String,
    declaration: Option<HostHeaderAggregateDecl>,
    claimed_outputs: Vec<String>,
    claimed_tools: Vec<String>,
    rejection: Option<String>,
}

/// Collects source-declared host-C header aggregates from one mmakefile.
///
/// `line_states` uses zero-based line positions in the continuation-joined
/// source. A candidate marker, aggregate, or recipe in an unresolved Make
/// conditional is rejected; false branches are ignored.
#[must_use]
pub(crate) fn collect(
    content: &str,
    relative_dir: &Path,
    scope: &VarScope,
    dirs: &DirVars,
    source_root: &Path,
    line_states: Option<&[ConditionalTruth]>,
) -> (Vec<HostHeaderAggregateDecl>, Vec<Rejection>) {
    // Oversized Makefiles do not produce declarations. Candidate-level parsing
    // is deliberately bounded; the caller's general Make scanner has its own
    // diagnostics for malformed or excessive source inputs.
    if content.len() > MAX_MAKEFILE_BYTES {
        return (Vec::new(), Vec::new());
    }

    let lines = logical_lines(content, line_states);
    let rules = parse_rules(&lines);
    let markers = parse_markers(&lines);
    let candidates = candidate_markers(&markers, &rules, scope, dirs, source_root, relative_dir);
    if candidates.is_empty() {
        return (Vec::new(), Vec::new());
    }

    let relative_directory = match safe_relative_directory(relative_dir) {
        Ok(value) => value,
        Err(reason) => {
            return (
                Vec::new(),
                candidates
                    .iter()
                    .map(|marker| Rejection {
                        owner: marker.owner.clone(),
                        reason: format!("host-header aggregate source directory: {reason}"),
                    })
                    .collect(),
            );
        }
    };
    let canonical_root = match source_root.canonicalize() {
        Ok(root) if root.is_dir() => root,
        Ok(_) => {
            return rejected_candidates(&candidates, "selected source root is not a directory");
        }
        Err(error) => {
            return rejected_candidates(
                &candidates,
                &format!("selected source root cannot be canonicalized: {error}"),
            );
        }
    };

    let mut results = Vec::with_capacity(candidates.len());
    for marker in candidates {
        results.push(scan_candidate(
            &marker,
            &rules,
            scope,
            dirs,
            &canonical_root,
            relative_dir,
            &relative_directory,
        ));
    }

    // A different named aggregate cannot silently claim the same SDK or GEN
    // path, even when one candidate has another independent defect.
    let mut output_claims: BTreeMap<String, Vec<usize>> = BTreeMap::new();
    let mut tool_claims: BTreeMap<String, Vec<usize>> = BTreeMap::new();
    for (index, result) in results.iter().enumerate() {
        for output in &result.claimed_outputs {
            output_claims
                .entry(output.to_ascii_lowercase())
                .or_default()
                .push(index);
        }
        for tool in &result.claimed_tools {
            tool_claims.entry(tool.clone()).or_default().push(index);
        }
    }
    for (output, owners) in output_claims {
        let unique = owners.into_iter().collect::<HashSet<_>>();
        if unique.len() < 2 {
            continue;
        }
        for index in unique {
            reject_result(
                &mut results[index],
                format!("duplicate host-header aggregate output `{output}`"),
            );
        }
    }
    for (tool, owners) in tool_claims {
        let unique = owners.into_iter().collect::<HashSet<_>>();
        if unique.len() < 2 {
            continue;
        }
        for index in unique {
            reject_result(
                &mut results[index],
                format!("host tool `{tool}` is claimed by multiple aggregates"),
            );
        }
    }

    let mut declarations = Vec::new();
    let mut rejections = Vec::new();
    for mut result in results {
        if let Some(reason) = result.rejection.take() {
            rejections.push(Rejection {
                owner: result.owner,
                reason,
            });
        } else if let Some(declaration) = result.declaration.take() {
            declarations.push(declaration);
        }
    }
    (declarations, rejections)
}

fn candidate_markers(
    markers: &[Marker],
    rules: &[Rule],
    scope: &VarScope,
    dirs: &DirVars,
    source_root: &Path,
    relative_dir: &Path,
) -> Vec<Marker> {
    let mut candidates = Vec::new();
    let mut seen = HashSet::new();
    for marker in markers {
        if marker.state == ConditionalTruth::False
            || !safe_owner(&marker.owner)
            || !seen.insert(marker.owner.clone())
        {
            continue;
        }
        let matching = rules
            .iter()
            .filter(|rule| {
                rule.state != ConditionalTruth::False && rule.target.trim() == marker.owner
            })
            .collect::<Vec<_>>();
        if matching.iter().any(|rule| {
            aggregate_mentions_include_header(rule, scope, dirs, source_root, relative_dir)
        }) {
            let mut candidate = marker.clone();
            candidate.duplicate = markers
                .iter()
                .filter(|other| {
                    other.owner == marker.owner && other.state != ConditionalTruth::False
                })
                .count()
                > 1;
            candidates.push(candidate);
        }
    }
    candidates
}

fn aggregate_mentions_include_header(
    rule: &Rule,
    scope: &VarScope,
    dirs: &DirVars,
    source_root: &Path,
    relative_dir: &Path,
) -> bool {
    let context = MakeExprContext::new(scope, dirs, rule.source_line, source_root, relative_dir);
    let expressions = [
        &rule.prerequisites,
        rule.order_only.as_deref().unwrap_or(""),
    ];
    for expression in expressions {
        if let Ok(paths) = evaluate_make_list(expression, &context) {
            let sdk = evaluate_make_expr("$(AROS_INCLUDES)", &context).ok();
            let generated = evaluate_make_expr("$(GENINCDIR)", &context).ok();
            if paths.iter().any(|path| {
                sdk.as_deref()
                    .is_some_and(|root| header_under_root(path, root))
                    || generated
                        .as_deref()
                        .is_some_and(|root| header_under_root(path, root))
            }) {
                return true;
            }
        }
        if expression.split_whitespace().any(|word| {
            direct_header_reference(word, "$(AROS_INCLUDES)/")
                || direct_header_reference(word, "$(GENINCDIR)/")
        }) {
            return true;
        }
    }
    false
}

fn scan_candidate(
    marker: &Marker,
    rules: &[Rule],
    scope: &VarScope,
    dirs: &DirVars,
    source_root: &Path,
    relative_dir: &Path,
    relative_directory: &str,
) -> CandidateResult {
    let mut result = CandidateResult {
        owner: marker.owner.clone(),
        declaration: None,
        claimed_outputs: Vec::new(),
        claimed_tools: Vec::new(),
        rejection: None,
    };

    if marker.duplicate {
        reject_result(
            &mut result,
            "source declares the same #MM aggregate marker more than once",
        );
        return result;
    }
    if marker.state != ConditionalTruth::True || marker.conditional_syntax {
        reject_result(
            &mut result,
            "#MM aggregate marker is guarded by an unresolved Make conditional",
        );
        return result;
    }

    let owners = rules
        .iter()
        .filter(|rule| rule.state != ConditionalTruth::False && rule.target.trim() == marker.owner)
        .collect::<Vec<_>>();
    if owners.len() != 1 {
        reject_result(
            &mut result,
            if owners.is_empty() {
                "named #MM aggregate has no matching ordinary Make rule"
            } else {
                "named #MM aggregate has multiple active Make rule blocks"
            },
        );
        return result;
    }
    let owner_rule = owners[0];
    if !safe_owner(&owner_rule.target) {
        reject_result(
            &mut result,
            "aggregate owner is not a safe literal Make target",
        );
        return result;
    }
    if owner_rule.state != ConditionalTruth::True || owner_rule.conditional_syntax {
        reject_result(
            &mut result,
            "named aggregate rule is guarded by an unresolved Make conditional",
        );
        return result;
    }
    if owner_rule.inline_recipe || !owner_rule.recipes.is_empty() {
        reject_result(
            &mut result,
            "named aggregate must be dependency-only and have no recipe commands",
        );
        return result;
    }
    if owner_rule.order_only.is_some() {
        reject_result(
            &mut result,
            "named aggregate must have only ordinary prerequisites",
        );
        return result;
    }

    let owner_context = MakeExprContext::new(
        scope,
        dirs,
        owner_rule.source_line,
        source_root,
        relative_dir,
    );
    let sdk_root = match validate_configured_root(
        "$(AROS_INCLUDES)",
        &["AROS_INCLUDES", "AROS_DEVELOPER", "AROS_DIR_INCLUDE"],
        &owner_context,
        dirs,
    ) {
        Ok(root) => root,
        Err(reason) => {
            reject_result(&mut result, reason);
            return result;
        }
    };
    let raw_prerequisites = match evaluate_make_list(&owner_rule.prerequisites, &owner_context) {
        Ok(paths) => paths,
        Err(error) => {
            reject_result(
                &mut result,
                format!("cannot resolve aggregate prerequisites: {error}"),
            );
            return result;
        }
    };
    if raw_prerequisites.is_empty() {
        reject_result(&mut result, "named aggregate has no header prerequisites");
        return result;
    }
    if raw_prerequisites.len() > MAX_OUTPUTS {
        reject_result(
            &mut result,
            format!("aggregate prerequisite list exceeds {MAX_OUTPUTS} outputs"),
        );
        return result;
    }

    let mut seen_prerequisites = HashSet::new();
    let mut sdk_headers = Vec::new();
    let mut generated_headers = Vec::new();
    for prerequisite in &raw_prerequisites {
        result.claimed_outputs.push(prerequisite.clone());
        if !seen_prerequisites.insert(prerequisite.to_ascii_lowercase()) {
            reject_result(
                &mut result,
                format!("aggregate prerequisite `{prerequisite}` is listed more than once"),
            );
            return result;
        }
        if let Some(header) = relative_under_root(prerequisite, &sdk_root) {
            if !safe_header_relative(header) {
                reject_result(
                    &mut result,
                    format!("SDK prerequisite `{prerequisite}` is not a safe relative .h path"),
                );
                return result;
            }
            sdk_headers.push(header.to_owned());
            continue;
        }
        let generated_root = match validate_configured_root(
            "$(GENINCDIR)",
            &["GENINCDIR", "GENDIR"],
            &owner_context,
            dirs,
        ) {
            Ok(root) => root,
            Err(reason) => {
                reject_result(&mut result, reason);
                return result;
            }
        };
        if let Some(header) = relative_under_root(prerequisite, &generated_root) {
            if !safe_header_relative(header) {
                reject_result(
                    &mut result,
                    format!(
                        "GENINCDIR prerequisite `{prerequisite}` is not a safe relative .h path"
                    ),
                );
                return result;
            }
            generated_headers.push(header.to_owned());
            continue;
        }
        reject_result(
            &mut result,
            format!(
                "aggregate prerequisite `{prerequisite}` is not an SDK header or explicit GENINCDIR mirror"
            ),
        );
        return result;
    }
    if sdk_headers.is_empty() {
        reject_result(
            &mut result,
            "aggregate must depend on at least one SDK header output",
        );
        return result;
    }
    if sdk_headers.len() + generated_headers.len() > MAX_OUTPUTS {
        reject_result(
            &mut result,
            format!("aggregate exceeds {MAX_OUTPUTS} total outputs"),
        );
        return result;
    }
    let mut sdk_names = HashSet::new();
    for header in &sdk_headers {
        if !sdk_names.insert(header.to_ascii_lowercase()) {
            reject_result(
                &mut result,
                format!("SDK header `{header}` is listed more than once"),
            );
            return result;
        }
    }
    let mut generated_names = HashSet::new();
    for header in &generated_headers {
        if !generated_names.insert(header.to_ascii_lowercase()) {
            reject_result(
                &mut result,
                format!("GENINCDIR header `{header}` is listed more than once"),
            );
            return result;
        }
        if !sdk_names.contains(&header.to_ascii_lowercase()) {
            reject_result(
                &mut result,
                format!("GENINCDIR header `{header}` has no matching SDK prerequisite"),
            );
            return result;
        }
    }

    let mut outputs = Vec::with_capacity(sdk_headers.len());
    let mut tool_name: Option<String> = None;
    for header in &sdk_headers {
        let expected_path = format!("{sdk_root}/{header}");
        let output_rule = match unique_rule_for_path(
            &expected_path,
            rules,
            scope,
            dirs,
            source_root,
            relative_dir,
        ) {
            Ok(rule) => rule,
            Err(reason) => {
                reject_result(&mut result, format!("SDK output `{header}`: {reason}"));
                return result;
            }
        };
        let arguments = match inspect_sdk_output(
            output_rule,
            header,
            &sdk_root,
            scope,
            dirs,
            source_root,
            relative_dir,
        ) {
            Ok((name, args)) => (name, args),
            Err(reason) => {
                reject_result(&mut result, format!("SDK output `{header}`: {reason}"));
                return result;
            }
        };
        if let Some(expected) = &tool_name {
            if expected != &arguments.0 {
                reject_result(&mut result, "one aggregate must use exactly one host tool");
                return result;
            }
        } else {
            tool_name = Some(arguments.0.clone());
        }
        outputs.push(HostHeaderAggregateOutput {
            header: header.clone(),
            arguments: arguments.1,
            generated_mirror: generated_names.contains(&header.to_ascii_lowercase()),
        });
    }
    let Some(tool) = tool_name else {
        reject_result(&mut result, "aggregate has no SDK header outputs");
        return result;
    };
    result.claimed_tools.push(tool.clone());

    let host_root = match validate_configured_root(
        "$(HOSTGENDIR)",
        &["HOSTGENDIR", "HOSTDIR"],
        &owner_context,
        dirs,
    ) {
        Ok(root) => root,
        Err(reason) => {
            reject_result(&mut result, reason);
            return result;
        }
    };
    let tool_path = format!("{host_root}/tools/{tool}");
    let tool_rule =
        match unique_rule_for_path(&tool_path, rules, scope, dirs, source_root, relative_dir) {
            Ok(rule) => rule,
            Err(reason) => {
                reject_result(&mut result, format!("host tool `{tool}`: {reason}"));
                return result;
            }
        };
    let (tool_source, host_compile_flags) = match inspect_tool_rule(
        tool_rule,
        &tool,
        scope,
        dirs,
        source_root,
        relative_dir,
        relative_directory,
    ) {
        Ok(value) => value,
        Err(reason) => {
            reject_result(&mut result, format!("host tool `{tool}`: {reason}"));
            return result;
        }
    };

    let generated_root = if generated_headers.is_empty() {
        None
    } else {
        match validate_configured_root(
            "$(GENINCDIR)",
            &["GENINCDIR", "GENDIR", "TARGETDIR"],
            &owner_context,
            dirs,
        ) {
            Ok(root) => Some(root),
            Err(reason) => {
                reject_result(&mut result, reason);
                return result;
            }
        }
    };
    for header in &generated_headers {
        let path = format!("{}/{header}", generated_root.as_deref().unwrap());
        let mirror_rule =
            match unique_rule_for_path(&path, rules, scope, dirs, source_root, relative_dir) {
                Ok(rule) => rule,
                Err(reason) => {
                    reject_result(
                        &mut result,
                        format!("GENINCDIR mirror `{header}`: {reason}"),
                    );
                    return result;
                }
            };
        let mirror_context = MakeExprContext::new(
            scope,
            dirs,
            mirror_rule.source_line,
            source_root,
            relative_dir,
        );
        if let Err(reason) = inspect_mirror(
            mirror_rule,
            header,
            &sdk_root,
            generated_root.as_deref().unwrap(),
            &mirror_context,
            dirs,
        ) {
            reject_result(
                &mut result,
                format!("GENINCDIR mirror `{header}`: {reason}"),
            );
            return result;
        }
    }

    result.declaration = Some(HostHeaderAggregateDecl {
        owner: marker.owner.clone(),
        tool,
        tool_source,
        host_compile_flags,
        headers: outputs,
    });
    result
}

fn inspect_sdk_output(
    rule: &Rule,
    header: &str,
    sdk_root: &str,
    scope: &VarScope,
    dirs: &DirVars,
    source_root: &Path,
    relative_dir: &Path,
) -> Result<(String, Vec<String>), String> {
    validate_rule_active(rule)?;
    let expected_target = format!("$(AROS_INCLUDES)/{header}");
    if rule.target.trim() != expected_target {
        return Err(format!(
            "target must be written exactly as `{expected_target}`"
        ));
    }
    let context = MakeExprContext::new(scope, dirs, rule.source_line, source_root, relative_dir);
    let active_root = validate_configured_root(
        "$(AROS_INCLUDES)",
        &["AROS_INCLUDES", "AROS_DEVELOPER", "AROS_DIR_INCLUDE"],
        &context,
        dirs,
    )?;
    if active_root != sdk_root {
        return Err("SDK include root changed between aggregate and output rule".into());
    }
    let resolved_target = evaluate_make_expr(rule.target.trim(), &context)
        .map_err(|error| format!("cannot resolve target: {error}"))?;
    if resolved_target != format!("{sdk_root}/{header}") {
        return Err("target differs from the configured SDK include root".into());
    }
    let (normal, order_only) = (&rule.prerequisites, rule.order_only.as_deref());
    let tool = parse_tool_reference(normal)
        .ok_or_else(|| "must have exactly one direct HOSTGENDIR tool prerequisite".to_owned())?;
    if let Some(order_only) = order_only {
        validate_exact_parent(order_only, &context, &resolved_target)?;
    }
    validate_single_recipe(rule, "SDK header")?;
    let arguments = parse_generator_recipe(&rule.recipes[0].text, &tool)?;
    Ok((tool, arguments))
}

fn inspect_mirror(
    rule: &Rule,
    header: &str,
    sdk_root: &str,
    generated_root: &str,
    context: &MakeExprContext<'_>,
    dirs: &DirVars,
) -> Result<(), String> {
    validate_rule_active(rule)?;
    let expected_target = format!("$(GENINCDIR)/{header}");
    if rule.target.trim() != expected_target {
        return Err(format!(
            "target must be written exactly as `{expected_target}`"
        ));
    }
    let active_sdk_root = validate_configured_root(
        "$(AROS_INCLUDES)",
        &["AROS_INCLUDES", "AROS_DEVELOPER", "AROS_DIR_INCLUDE"],
        context,
        dirs,
    )?;
    if active_sdk_root != sdk_root {
        return Err("SDK include root changed between aggregate and mirror rule".into());
    }
    let active_generated_root =
        validate_configured_root("$(GENINCDIR)", &["GENINCDIR", "GENDIR"], context, dirs)?;
    if active_generated_root != generated_root {
        return Err("GENINCDIR root changed between aggregate and mirror rule".into());
    }
    let resolved_target = evaluate_make_expr(rule.target.trim(), context)
        .map_err(|error| format!("cannot resolve target: {error}"))?;
    if resolved_target != format!("{generated_root}/{header}") {
        return Err("target differs from the configured GENINCDIR root".into());
    }
    let (normal, order_only) = (&rule.prerequisites, rule.order_only.as_deref());
    let expected_source = format!("$(AROS_INCLUDES)/{header}");
    if normal.trim() != expected_source {
        return Err(format!(
            "copy prerequisite must be exactly `{expected_source}`"
        ));
    }
    let resolved_source = evaluate_make_expr(normal.trim(), context)
        .map_err(|error| format!("cannot resolve SDK copy prerequisite: {error}"))?;
    if resolved_source != format!("{sdk_root}/{header}") {
        return Err("copy prerequisite differs from the configured SDK root".into());
    }
    if let Some(order_only) = order_only {
        validate_exact_parent(order_only, context, &resolved_target)?;
    }
    validate_single_recipe(rule, "GENINCDIR copy")?;
    let words = rule.recipes[0].text.split_whitespace().collect::<Vec<_>>();
    if words.as_slice() != ["$(CP)", "$<", "$@"] {
        return Err("copy recipe must be exactly `$(CP) $< $@`".into());
    }
    Ok(())
}

fn inspect_tool_rule(
    rule: &Rule,
    tool: &str,
    scope: &VarScope,
    dirs: &DirVars,
    source_root: &Path,
    relative_dir: &Path,
    relative_directory: &str,
) -> Result<(String, Vec<String>), String> {
    validate_rule_active(rule)?;
    let expected_target = format!("$(HOSTGENDIR)/tools/{tool}");
    if rule.target.trim() != expected_target {
        return Err(format!(
            "tool target must be written exactly as `{expected_target}`"
        ));
    }
    let context = MakeExprContext::new(scope, dirs, rule.source_line, source_root, relative_dir);
    let host_root =
        validate_configured_root("$(HOSTGENDIR)", &["HOSTGENDIR", "HOSTDIR"], &context, dirs)?;
    let resolved_target = evaluate_make_expr(rule.target.trim(), &context)
        .map_err(|error| format!("cannot resolve tool target: {error}"))?;
    if resolved_target != format!("{host_root}/tools/{tool}") {
        return Err("tool target differs from the configured HOSTGENDIR root".into());
    }
    if rule.order_only.is_some() {
        return Err("tool rule may not have order-only prerequisites".into());
    }
    let source_prerequisite = rule.prerequisites.trim();
    let Some(source) = source_prerequisite.strip_prefix("$(SRCDIR)/$(CURDIR)/") else {
        return Err(
            "tool must have exactly one source-local `$(SRCDIR)/$(CURDIR)/<file>.c` prerequisite"
                .into(),
        );
    };
    if !safe_source_relative(source) {
        return Err(format!(
            "tool source `{source}` is not a safe relative .c path"
        ));
    }
    let resolved_source = evaluate_make_expr(source_prerequisite, &context)
        .map_err(|error| format!("cannot resolve source prerequisite: {error}"))?;
    if !source_prerequisite_matches(&resolved_source, relative_directory, source) {
        return Err("tool source prerequisite is not rooted in the selected source tree".into());
    }
    validate_regular_source(source_root, relative_dir, source)?;
    validate_single_recipe(rule, "host tool compile")?;
    let flags = parse_compile_recipe(&rule.recipes[0].text)?;
    Ok((source_path(relative_directory, source), flags))
}

fn unique_rule_for_path<'a>(
    expected_path: &str,
    rules: &'a [Rule],
    scope: &VarScope,
    dirs: &DirVars,
    source_root: &Path,
    relative_dir: &Path,
) -> Result<&'a Rule, String> {
    let matches = rules
        .iter()
        .filter(|rule| rule.state != ConditionalTruth::False)
        .filter(|rule| {
            let context =
                MakeExprContext::new(scope, dirs, rule.source_line, source_root, relative_dir);
            evaluate_make_expr(rule.target.trim(), &context)
                .is_ok_and(|target| target == expected_path)
        })
        .collect::<Vec<_>>();
    match matches.as_slice() {
        [rule] => Ok(*rule),
        [] => Err("has no matching Make output rule".into()),
        _ => Err("has multiple active Make output rules".into()),
    }
}

fn validate_configured_root(
    expression: &str,
    components: &[&str],
    context: &MakeExprContext<'_>,
    dirs: &DirVars,
) -> Result<String, String> {
    let active = evaluate_make_expr(expression, context)
        .map_err(|error| format!("cannot resolve include root {expression}: {error}"))?;
    let configured = dirs
        .expand(expression)
        .ok_or_else(|| format!("cannot resolve configured include root {expression}"))?;
    for component in components {
        let reference = format!("$({component})");
        let expected = dirs
            .expand(&reference)
            .ok_or_else(|| format!("cannot resolve configured include component {component}"))?;
        let actual = evaluate_make_expr(&reference, context).map_err(|error| {
            format!("cannot resolve active include component {component}: {error}")
        })?;
        if actual != expected {
            return Err(format!(
                "include root component {component} differs from its configured mapping"
            ));
        }
    }
    if active != configured {
        return Err(format!(
            "include root {expression} differs from its configured mapping"
        ));
    }
    Ok(active)
}

fn validate_rule_active(rule: &Rule) -> Result<(), String> {
    if rule.state != ConditionalTruth::True
        || rule.conditional_syntax
        || rule
            .recipes
            .iter()
            .any(|recipe| recipe.state != ConditionalTruth::True || recipe.conditional_syntax)
    {
        return Err("rule or recipe is guarded by an unresolved Make conditional".into());
    }
    if rule.inline_recipe {
        return Err("inline rule recipes are not modelled".into());
    }
    Ok(())
}

fn validate_single_recipe(rule: &Rule, kind: &str) -> Result<(), String> {
    validate_rule_active(rule)?;
    if rule.recipes.len() != 1 {
        return Err(format!("{kind} rule must have exactly one recipe command"));
    }
    Ok(())
}

fn parse_tool_reference(prerequisite: &str) -> Option<String> {
    let tool = prerequisite.trim().strip_prefix("$(HOSTGENDIR)/tools/")?;
    safe_tool(tool).then(|| tool.to_owned())
}

fn parse_generator_recipe(recipe: &str, expected_tool: &str) -> Result<Vec<String>, String> {
    let Some((invocation, redirect)) = recipe.trim().split_once('>') else {
        return Err("generator recipe must redirect stdout to `$@`".into());
    };
    if redirect.trim() != "$@" {
        return Err("generator recipe must redirect only to `$@`".into());
    }
    let words = invocation.split_whitespace().collect::<Vec<_>>();
    if words
        .first()
        .and_then(|word| parse_tool_reference(word))
        .as_deref()
        != Some(expected_tool)
    {
        return Err("generator recipe must run its direct HOSTGENDIR tool prerequisite".into());
    }
    let arguments = words
        .iter()
        .skip(1)
        .map(|word| (*word).to_owned())
        .collect::<Vec<_>>();
    if arguments.iter().any(|argument| !safe_literal(argument)) {
        return Err("generator arguments must be safe literal words".into());
    }
    Ok(arguments)
}

fn parse_compile_recipe(recipe: &str) -> Result<Vec<String>, String> {
    let command = recipe.trim();
    let command = command
        .strip_prefix('@')
        .ok_or_else(|| "compile recipe must start with `@$(HOST_CC)`".to_owned())?;
    let command = command
        .strip_prefix("$(HOST_CC)")
        .ok_or_else(|| "compile recipe must start with `@$(HOST_CC)`".to_owned())?;
    if !command.chars().next().is_some_and(char::is_whitespace) {
        return Err("compile recipe must separate HOST_CC from its literal flags".into());
    }
    let words = command.split_whitespace().collect::<Vec<_>>();
    if words.len() < 3 || words[words.len() - 3..] != ["-o", "$@", "$<"] {
        return Err("compile recipe must end exactly with `-o $@ $<`".into());
    }
    let flags = &words[..words.len() - 3];
    if flags.iter().any(|flag| !safe_compile_flag(flag)) {
        return Err("compile flags must be safe literal compiler flags".into());
    }
    Ok(flags.iter().map(|flag| (*flag).to_owned()).collect())
}

fn safe_compile_flag(flag: &str) -> bool {
    if let Some(warning) = flag.strip_prefix("-W") {
        return !warning.is_empty()
            && warning
                .chars()
                .all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '_' | '=' | '+' | '-'));
    }
    if matches!(flag, "-O0" | "-O1" | "-O2" | "-O3" | "-Os" | "-Og") {
        return true;
    }
    if let Some(standard) = flag.strip_prefix("-std=") {
        return !standard.is_empty()
            && standard
                .chars()
                .all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '_' | '+' | '-'));
    }
    if let Some(definition) = flag.strip_prefix("-D") {
        let (name, value) = definition
            .split_once('=')
            .map_or((definition, None), |(name, value)| (name, Some(value)));
        return !name.is_empty()
            && name.chars().enumerate().all(|(index, ch)| {
                ch.is_ascii_alphabetic() || ch == '_' || index > 0 && ch.is_ascii_digit()
            })
            && value.is_none_or(|value| {
                !value.is_empty()
                    && value
                        .chars()
                        .all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '_' | '+' | '-'))
            });
    }
    false
}

fn safe_literal(value: &str) -> bool {
    !value.is_empty()
        && value.chars().all(|ch| {
            ch.is_ascii_alphanumeric()
                || matches!(ch, '_' | '.' | ',' | '=' | '+' | ':' | '/' | '-')
        })
}

fn validate_exact_parent(
    expression: &str,
    context: &MakeExprContext<'_>,
    output: &str,
) -> Result<(), String> {
    let words = evaluate_make_list(expression, context)
        .map_err(|error| format!("cannot resolve order-only directory prerequisite: {error}"))?;
    if words.len() != 1 {
        return Err("order-only prerequisite must be exactly one output parent".into());
    }
    let expected = Path::new(output)
        .parent()
        .and_then(Path::to_str)
        .ok_or_else(|| "output has no valid parent directory".to_owned())?;
    if words[0] != expected {
        return Err("order-only prerequisite must be exactly the output header parent".into());
    }
    // The native generator creates the exact output parents itself. GLOB_MKDIRS
    // is therefore not emitted as a second, unproven directory behavior.
    Ok(())
}

fn header_under_root(path: &str, root: &str) -> bool {
    relative_under_root(path, root).is_some_and(safe_header_relative)
}

fn relative_under_root<'a>(path: &'a str, root: &str) -> Option<&'a str> {
    path.strip_prefix(root)
        .and_then(|tail| tail.strip_prefix('/'))
}

fn direct_header_reference(word: &str, root: &str) -> bool {
    word.strip_prefix(root).is_some_and(safe_header_relative)
}

fn safe_header_relative(value: &str) -> bool {
    safe_relative_file(value, "h")
}

fn safe_source_relative(value: &str) -> bool {
    safe_relative_file(value, "c")
}

fn safe_relative_file(value: &str, extension: &str) -> bool {
    if value.is_empty()
        || value.len() > MAX_RELATIVE_PATH_BYTES
        || value.starts_with('/')
        || value.contains([
            '\\', ';', '$', '`', '*', '?', '[', ']', '#', '\n', '\r', '\t',
        ])
        || Path::new(value).is_absolute()
        || Path::new(value)
            .extension()
            .and_then(|value| value.to_str())
            != Some(extension)
    {
        return false;
    }
    let mut count = 0usize;
    for component in Path::new(value).components() {
        let Component::Normal(component) = component else {
            return false;
        };
        let Some(component) = component.to_str() else {
            return false;
        };
        if component.is_empty()
            || !component
                .chars()
                .all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '_' | '.' | '+' | '-'))
        {
            return false;
        }
        count += 1;
    }
    count > 0
}

fn safe_owner(owner: &str) -> bool {
    let mut chars = owner.chars();
    chars.next().is_some_and(|first| {
        (first.is_ascii_alphanumeric() || first == '_')
            && chars.all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '_' | '.' | '+' | '-'))
    })
}

fn safe_tool(tool: &str) -> bool {
    let mut chars = tool.chars();
    chars.next().is_some_and(|first| {
        (first.is_ascii_alphanumeric() || matches!(first, '_' | '+' | '-'))
            && chars.all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '_' | '.' | '+' | '-'))
    })
}

fn safe_relative_directory(path: &Path) -> Result<String, String> {
    if path.is_absolute() {
        return Err("declaring directory must be source-root-relative".into());
    }
    let mut components = Vec::new();
    for component in path.components() {
        let Component::Normal(component) = component else {
            return Err("declaring directory contains a non-normal path component".into());
        };
        let component = component
            .to_str()
            .ok_or_else(|| "declaring directory is not valid UTF-8".to_owned())?;
        if component.contains(['\\', ';', '$', '`', '\n', '\r']) {
            return Err("declaring directory contains an unsafe path component".into());
        }
        components.push(component.to_owned());
    }
    Ok(components.join("/"))
}

fn validate_regular_source(
    source_root: &Path,
    relative_dir: &Path,
    source: &str,
) -> Result<(), String> {
    let mut path = source_root.to_path_buf();
    let mut components = relative_dir.components().collect::<Vec<_>>();
    components.extend(Path::new(source).components());
    let final_path = source_root.join(relative_dir).join(source);
    for component in components {
        let Component::Normal(component) = component else {
            return Err("tool source escapes the selected source tree".into());
        };
        path.push(component);
        let metadata = fs::symlink_metadata(&path)
            .map_err(|error| format!("tool source {} is missing: {error}", path.display()))?;
        if metadata.file_type().is_symlink() {
            return Err(format!("tool source crosses a symlink: {}", path.display()));
        }
        if path != final_path && !metadata.is_dir() {
            return Err(format!(
                "tool source parent is not a directory: {}",
                path.display()
            ));
        }
        if path == final_path && !metadata.is_file() {
            return Err(format!(
                "tool source is not a regular file: {}",
                path.display()
            ));
        }
    }
    Ok(())
}

fn source_prerequisite_matches(actual: &str, relative_directory: &str, source: &str) -> bool {
    if relative_directory.is_empty() {
        [
            format!("${{AROS_SOURCE_DIR}}/{source}"),
            format!("${{AROS_SOURCE_DIR}}/./{source}"),
            format!("${{AROS_SOURCE_DIR}}//{source}"),
        ]
        .iter()
        .any(|expected| actual == expected)
    } else {
        actual == format!("${{AROS_SOURCE_DIR}}/{relative_directory}/{source}")
    }
}

fn source_path(relative_directory: &str, source: &str) -> String {
    if relative_directory.is_empty() {
        source.to_owned()
    } else {
        format!("{relative_directory}/{source}")
    }
}

fn reject_result(result: &mut CandidateResult, reason: impl Into<String>) {
    if result.rejection.is_none() {
        result.rejection = Some(reason.into());
    }
    result.declaration = None;
}

fn rejected_candidates(
    candidates: &[Marker],
    reason: &str,
) -> (Vec<HostHeaderAggregateDecl>, Vec<Rejection>) {
    (
        Vec::new(),
        candidates
            .iter()
            .map(|marker| Rejection {
                owner: marker.owner.clone(),
                reason: reason.to_owned(),
            })
            .collect(),
    )
}

fn logical_lines(content: &str, states: Option<&[ConditionalTruth]>) -> Vec<LogicalLine> {
    let physical = content.lines().collect::<Vec<_>>();
    let mut output = Vec::new();
    let mut conditional_depth = 0usize;
    let mut at = 0usize;
    while at < physical.len() {
        let first = physical[at];
        let first_trimmed = first.trim();
        if is_conditional_open(first_trimmed) {
            conditional_depth += 1;
        }
        let mut text = first.to_owned();
        let source_line = at;
        let mut state = line_state(states, at);
        let mut conditional_syntax = states.is_none() && conditional_depth > 0;
        while has_unescaped_trailing_backslash(&text) && at + 1 < physical.len() {
            let trimmed = text.trim_end();
            text.truncate(trimmed.len() - 1);
            at += 1;
            state = combine_state(state, line_state(states, at));
            conditional_syntax |= states.is_none() && conditional_depth > 0;
            text.push(' ');
            text.push_str(physical[at].trim());
        }
        output.push(LogicalLine {
            text,
            source_line,
            state,
            conditional_syntax,
        });
        if is_conditional_close(first_trimmed) {
            conditional_depth = conditional_depth.saturating_sub(1);
        }
        at += 1;
    }
    output
}

fn parse_markers(lines: &[LogicalLine]) -> Vec<Marker> {
    lines
        .iter()
        .filter_map(|line| {
            let statement = line.text.trim();
            let owner = statement.strip_prefix("#MM ")?.trim();
            if !safe_owner(owner) || owner.split_whitespace().count() != 1 {
                return None;
            }
            Some(Marker {
                owner: owner.to_owned(),
                state: line.state,
                conditional_syntax: line.conditional_syntax,
                duplicate: false,
            })
        })
        .collect()
}

fn parse_rules(lines: &[LogicalLine]) -> Vec<Rule> {
    let mut rules = Vec::new();
    let mut current: Option<Rule> = None;
    for line in lines {
        if line.text.starts_with('\t') {
            if let Some(rule) = current.as_mut() {
                if line.state != ConditionalTruth::False {
                    rule.recipes.push(Recipe {
                        text: line.text.trim().to_owned(),
                        state: line.state,
                        conditional_syntax: line.conditional_syntax,
                    });
                    rule.conditional_syntax |= line.conditional_syntax;
                }
            }
            continue;
        }
        let statement = strip_make_comment(line.text.trim_end_matches('\r')).trim();
        if statement.is_empty() {
            continue;
        }
        if is_conditional_directive(statement) || variable_assignment(statement).is_some() {
            if let Some(rule) = current.take() {
                rules.push(rule);
            }
            continue;
        }
        if let Some(rule) = current.take() {
            rules.push(rule);
        }
        let Some((target, tail)) = statement.split_once(':') else {
            continue;
        };
        let (prerequisite_text, inline_recipe) = tail.split_once(';').map_or_else(
            || (tail.trim(), false),
            |(prereqs, _)| (prereqs.trim(), true),
        );
        let (prerequisites, order_only) = match prerequisite_text.split_once('|') {
            Some((normal, order_only)) => {
                (normal.trim().to_owned(), Some(order_only.trim().to_owned()))
            }
            None => (prerequisite_text.to_owned(), None),
        };
        if target.trim().is_empty() || target.contains('=') {
            continue;
        }
        current = Some(Rule {
            target: target.trim().to_owned(),
            prerequisites,
            order_only,
            source_line: line.source_line,
            state: line.state,
            conditional_syntax: line.conditional_syntax,
            inline_recipe,
            recipes: Vec::new(),
        });
    }
    if let Some(rule) = current {
        rules.push(rule);
    }
    rules
}

fn line_state(states: Option<&[ConditionalTruth]>, index: usize) -> ConditionalTruth {
    states.map_or(ConditionalTruth::True, |states| {
        states
            .get(index)
            .copied()
            .unwrap_or(ConditionalTruth::Unknown)
    })
}

const fn combine_state(left: ConditionalTruth, right: ConditionalTruth) -> ConditionalTruth {
    match (left, right) {
        (ConditionalTruth::False, _) | (_, ConditionalTruth::False) => ConditionalTruth::False,
        (ConditionalTruth::Unknown, _) | (_, ConditionalTruth::Unknown) => {
            ConditionalTruth::Unknown
        }
        _ => ConditionalTruth::True,
    }
}

fn has_unescaped_trailing_backslash(value: &str) -> bool {
    let tail = value.trim_end();
    tail.chars()
        .rev()
        .take_while(|character| *character == '\\')
        .count()
        % 2
        == 1
}

fn is_conditional_directive(line: &str) -> bool {
    is_conditional_open(line) || line == "else" || line == "endif"
}

fn is_conditional_open(line: &str) -> bool {
    ["ifeq", "ifneq", "ifdef", "ifndef"]
        .iter()
        .any(|directive| line == *directive || line.starts_with(&format!("{directive} ")))
}

fn is_conditional_close(line: &str) -> bool {
    line == "endif"
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::make_vars::collect_vars;
    use crate::testing::{root as source_tree, TempTree};
    use std::path::PathBuf;

    const CONFIG: &str = "AROS_DIR_DEVELOPER := Developer\n\
AROS_DIR_INCLUDE := include\n\
AROSDIR := $(TARGETDIR)/$(AROS_DIR_AROS)\n\
AROS_DEVELOPER := $(AROSDIR)/$(AROS_DIR_DEVELOPER)\n\
AROS_INCLUDES := $(AROS_DEVELOPER)/$(AROS_DIR_INCLUDE)\n\
GENINCDIR := $(GENDIR)/include\n\
HOSTGENDIR := $(HOSTDIR)/gen/host\n";

    struct Fixture {
        root: TempTree,
        relative_dir: PathBuf,
    }

    impl Fixture {
        fn new() -> Self {
            let root = TempTree::new();
            let relative_dir = PathBuf::from("arch/example/include");
            fs::create_dir_all(root.0.join("config")).unwrap();
            fs::write(root.0.join("config/make.cfg.in"), CONFIG).unwrap();
            fs::create_dir_all(root.0.join(&relative_dir)).unwrap();
            Self { root, relative_dir }
        }

        fn source(&self, relative: &str) {
            let path = self.root.0.join(&self.relative_dir).join(relative);
            fs::create_dir_all(path.parent().unwrap()).unwrap();
            fs::write(path, b"int main(void) { return 0; }\n").unwrap();
        }

        fn scan(
            &self,
            content: &str,
            states: Option<&[ConditionalTruth]>,
        ) -> (Vec<HostHeaderAggregateDecl>, Vec<Rejection>) {
            let scope = collect_vars(content);
            let dirs = DirVars::load(&self.root.0);
            collect(
                content,
                &self.relative_dir,
                &scope,
                &dirs,
                &self.root.0,
                states,
            )
        }
    }

    fn fixture_text(with_mirror: bool) -> String {
        let mirror = if with_mirror {
            "$(GENINCDIR)/api/example.h: $(AROS_INCLUDES)/api/example.h | $(GENINCDIR)/api\n\
\t$(CP) $< $@\n\
GLOB_MKDIRS += $(GENINCDIR)/api\n"
        } else {
            ""
        };
        format!(
            "#MM fixture-generated-headers\n\
fixture-generated-headers: $(AROS_INCLUDES)/api/example.h{}\n\
$(AROS_INCLUDES)/api/example.h: $(HOSTGENDIR)/tools/genapi | $(AROS_INCLUDES)/api\n\
\t$(HOSTGENDIR)/tools/genapi example >$@\n\
GLOB_MKDIRS += $(AROS_INCLUDES)/api\n\
$(HOSTGENDIR)/tools/genapi: $(SRCDIR)/$(CURDIR)/genapi.c\n\
\t@$(HOST_CC) -Wall -Werror -o $@ $<\n\
{}",
            if with_mirror {
                " $(GENINCDIR)/api/example.h"
            } else {
                ""
            },
            mirror
        )
    }

    #[test]
    fn recognizes_a_finite_aggregate_and_only_an_explicit_mirror() {
        let fixture = Fixture::new();
        fixture.source("genapi.c");
        let (declarations, rejections) = fixture.scan(&fixture_text(true), None);
        assert!(rejections.is_empty(), "{rejections:#?}");
        assert_eq!(declarations.len(), 1, "{declarations:#?}");
        let declaration = &declarations[0];
        assert_eq!(declaration.owner, "fixture-generated-headers");
        assert_eq!(declaration.tool, "genapi");
        assert_eq!(declaration.tool_source, "arch/example/include/genapi.c");
        assert_eq!(
            declaration.host_compile_flags,
            ["-Wall".to_owned(), "-Werror".to_owned()]
        );
        assert_eq!(declaration.headers.len(), 1);
        assert_eq!(declaration.headers[0].header, "api/example.h");
        assert_eq!(declaration.headers[0].arguments, ["example".to_owned()]);
        assert!(declaration.headers[0].generated_mirror);

        let (declarations, rejections) = fixture.scan(&fixture_text(false), None);
        assert!(rejections.is_empty(), "{rejections:#?}");
        assert_eq!(declarations.len(), 1);
        assert!(!declarations[0].headers[0].generated_mirror);
    }

    #[test]
    fn accepts_a_root_local_c_tool_with_only_make_curdir_dot_normalization() {
        let fixture = Fixture::new();
        fs::write(
            fixture.root.0.join("genapi.c"),
            b"int main(void) { return 0; }\n",
        )
        .unwrap();
        let content = fixture_text(false);
        let scope = collect_vars(&content);
        let dirs = DirVars::load(&fixture.root.0);
        let (declarations, rejections) = collect(
            &content,
            Path::new(""),
            &scope,
            &dirs,
            &fixture.root.0,
            None,
        );
        assert!(rejections.is_empty(), "{rejections:#?}");
        assert_eq!(declarations.len(), 1, "{declarations:#?}");
        assert_eq!(declarations[0].tool_source, "genapi.c");
    }

    #[test]
    fn rejects_extra_prerequisites_unsafe_recipes_and_root_overrides() {
        let fixture = Fixture::new();
        fixture.source("genapi.c");
        let base = fixture_text(false);
        for (content, expected) in [
            (
                base.replace(
                    "fixture-generated-headers: $(AROS_INCLUDES)/api/example.h",
                    "fixture-generated-headers: $(AROS_INCLUDES)/api/example.h setup",
                ),
                "not an SDK header or explicit GENINCDIR mirror",
            ),
            (
                base.replace("example >$@", "example | cat >$@"),
                "safe literal",
            ),
            (
                base.replace(
                    "@$(HOST_CC) -Wall -Werror",
                    "@$(HOST_CC) -I/private -Werror",
                ),
                "safe literal compiler flags",
            ),
            (
                base.replace(
                    "#MM fixture-generated-headers",
                    "AROS_DEVELOPER := redirected\n#MM fixture-generated-headers",
                ),
                "differs from its configured mapping",
            ),
        ] {
            let (_, rejections) = fixture.scan(&content, None);
            assert!(
                rejections
                    .iter()
                    .any(|rejection| rejection.reason.contains(expected)),
                "wanted {expected:?}; got {rejections:#?}"
            );
        }
        let bad_mirror_parent = fixture_text(true).replace(
            "$(GENINCDIR)/api/example.h: $(AROS_INCLUDES)/api/example.h | $(GENINCDIR)/api",
            "$(GENINCDIR)/api/example.h: $(AROS_INCLUDES)/api/example.h | $(GENINCDIR)/elsewhere",
        );
        let (_, rejections) = fixture.scan(&bad_mirror_parent, None);
        assert!(
            rejections
                .iter()
                .any(|rejection| rejection.reason.contains("output header parent")),
            "{rejections:#?}"
        );
    }

    #[test]
    fn rejects_unknown_conditionals_duplicate_markers_and_symlinked_sources() {
        let fixture = Fixture::new();
        fixture.source("genapi.c");
        let base = fixture_text(false);

        let guarded = format!("ifeq ($(UNKNOWN),1)\n{base}endif\n");
        let states = vec![ConditionalTruth::Unknown; guarded.lines().count()];
        let (_, rejections) = fixture.scan(&guarded, Some(&states));
        assert!(
            rejections.iter().any(|r| r.reason.contains("conditional")),
            "{rejections:#?}"
        );

        let duplicate = base.replacen(
            "#MM fixture-generated-headers",
            "#MM fixture-generated-headers\n#MM fixture-generated-headers",
            1,
        );
        let (_, rejections) = fixture.scan(&duplicate, None);
        assert!(
            rejections
                .iter()
                .any(|r| r.reason.contains("marker more than once")),
            "{rejections:#?}"
        );

        #[cfg(unix)]
        {
            use std::os::unix::fs::symlink;
            let real = fixture.root.0.join(&fixture.relative_dir).join("real.c");
            fs::write(&real, b"int generated(void) { return 0; }\n").unwrap();
            symlink(
                real,
                fixture.root.0.join(&fixture.relative_dir).join("alias.c"),
            )
            .unwrap();
            let linked = base.replace("genapi.c", "alias.c");
            let (_, rejections) = fixture.scan(&linked, None);
            assert!(
                rejections.iter().any(|r| r.reason.contains("symlink")),
                "{rejections:#?}"
            );
        }
    }

    #[test]
    fn the_two_source_tree_aggregates_keep_their_declared_output_shapes() {
        let root = source_tree();
        let mut files = Vec::new();
        for entry in fs::read_dir(root.join("arch")).unwrap() {
            let entry = entry.unwrap();
            if !entry.file_type().unwrap().is_dir() {
                continue;
            }
            let relative_dir = PathBuf::from("arch")
                .join(entry.file_name())
                .join("include");
            let path = root.join(&relative_dir).join("mmakefile.src");
            if !path.is_file() {
                continue;
            }
            let content = fs::read_to_string(path).unwrap();
            if content
                .lines()
                .any(|line| line.trim().starts_with("#MM ") && !line.trim().starts_with("#MM-"))
                && content.contains("$(HOSTGENDIR)/tools/")
            {
                files.push((relative_dir, content));
            }
        }
        let mut declarations = Vec::new();
        let mut total_outputs = 0;
        for (relative_dir, content) in files {
            let scope = collect_vars(&content);
            let dirs = DirVars::load(&root);
            let (found, rejections) = collect(&content, &relative_dir, &scope, &dirs, &root, None);
            assert!(
                rejections.is_empty(),
                "{}: {rejections:#?}",
                relative_dir.display()
            );
            total_outputs += found.iter().map(|decl| decl.headers.len()).sum::<usize>();
            declarations.extend(found);
        }
        assert_eq!(declarations.len(), 2, "{declarations:#?}");
        assert_eq!(total_outputs, 3, "{declarations:#?}");
        assert_eq!(
            declarations
                .iter()
                .filter(|declaration| declaration.headers.iter().any(|h| h.generated_mirror))
                .count(),
            1,
            "only the source-declared mirror is captured: {declarations:#?}"
        );
        assert!(declarations
            .iter()
            .all(|declaration| declaration.tool_source.ends_with("/gencall.c")));
    }
}
