//! Closed model for source-declared SFD header generation.
//!
//! Only an ordinary named Make provider, a finite set of SDK `.h` outputs,
//! and one exact host-`sfdc` invocation per output are admitted. Arbitrary
//! shell recipes and Make expansions remain outside the native graph.

use crate::dirs::DirVars;
use crate::make_expr::{evaluate_make_expr, MakeExprContext};
use crate::make_vars::{ConditionalTruth, VarScope};
use std::collections::BTreeSet;
use std::fs;
use std::path::{Component, Path};

const SDK_PREFIX: &str = "$(AROS_INCLUDES)/";
const SOURCE_PREFIX: &str = "$(SRCDIR)/$(CURDIR)/";
const SFDC: &str = "$(SFDC)";
const MODES: &[&str] = &["clib", "macros", "proto"];

/// One source SFD file and SDK header generated by `sfdc`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SfdHeaderJob {
    /// Accepted `sfdc --mode` value.
    pub mode: String,
    /// Literal target spelling taken from the Make recipe.
    pub target: String,
    /// Source-root-relative SFD input.
    pub input: String,
    /// SHA-256 digest of the input bytes.
    pub input_sha256: String,
    /// SDK include-root-relative generated header.
    pub sdk_output: String,
}

/// Complete source ownership for one named aggregate and its generated SDK headers.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SfdHeaderRuleDecl {
    /// Ordinary Make target named by the source MetaMake provider.
    pub owner: String,
    /// Source-root-relative declaring `mmakefile.src`.
    pub file: String,
    /// SHA-256 digest of the declaring file's source bytes.
    pub file_sha256: String,
    /// Every declared SDK header output and its exact source recipe.
    pub jobs: Vec<SfdHeaderJob>,
}

/// A source SFD producer that falls outside this closed model.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SfdHeaderRuleRejection {
    pub owner: String,
    pub line: usize,
    pub reason: String,
}

/// Results from scanning one continuation-joined Makefile.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct SfdHeaderRuleScan {
    pub declarations: Vec<SfdHeaderRuleDecl>,
    pub rejected: Vec<SfdHeaderRuleRejection>,
}

#[derive(Debug, Clone)]
struct LogicalLine {
    text: String,
    source_line: usize,
    state: ConditionalTruth,
    conditional_syntax: bool,
}

#[derive(Debug, Clone)]
struct RecipeLine {
    text: String,
    state: ConditionalTruth,
    conditional_syntax: bool,
}

#[derive(Debug, Clone)]
struct Rule {
    target: String,
    prerequisites: String,
    source_line: usize,
    state: ConditionalTruth,
    conditional_syntax: bool,
    recipes: Vec<RecipeLine>,
}

#[derive(Debug, Clone)]
struct ConditionalFrame {
    open_line: usize,
    plain_else_seen: bool,
}

/// Scans source-local SFD providers after the parser has collected ordinary
/// nonvirtual MetaMake provider names. Conditional positions correspond to the
/// continuation-joined source text.
pub(crate) fn collect_sfd_header_rules_with_context(
    content: &str,
    source_root: &Path,
    rel_dir: &Path,
    scope: &VarScope,
    dirs: &DirVars,
    line_states: Option<&[ConditionalTruth]>,
    providers: &[String],
) -> SfdHeaderRuleScan {
    let file = match source_relative_file(rel_dir) {
        Ok(file) => file,
        Err(reason) => {
            return fallback_rejection(content, reason);
        }
    };
    let root = match source_root.canonicalize() {
        Ok(root) => root,
        Err(error) => {
            return fallback_rejection(content, format!("source root cannot be resolved: {error}"));
        }
    };

    let (lines, control_structure_issue) = logical_lines(content, line_states);
    let rules = parse_rules(lines);
    let mut scan = SfdHeaderRuleScan::default();
    let mut candidates = BTreeSet::new();
    let include_inactive_for_malformed_file = control_structure_issue.is_some();
    for owner in providers.iter().filter(|owner| safe_target_name(owner)) {
        let owner_rules = rules
            .iter()
            .filter(|rule| {
                rule.target.trim() == owner
                    && (rule.state != ConditionalTruth::False
                        || include_inactive_for_malformed_file)
            })
            .collect::<Vec<_>>();
        for aggregate in &owner_rules {
            for output in aggregate
                .prerequisites
                .split_whitespace()
                .filter(|word| is_sdk_header_expression(word))
            {
                if rules.iter().any(|leaf| {
                    leaf.target.trim() == output
                        && (leaf.state != ConditionalTruth::False
                            || include_inactive_for_malformed_file)
                        && has_sfd_signal(leaf)
                }) {
                    candidates.insert((*owner).clone());
                    break;
                }
            }
        }
    }

    for owner in candidates {
        let owner_rules = rules
            .iter()
            .filter(|rule| {
                rule.target.trim() == owner
                    && (rule.state != ConditionalTruth::False
                        || include_inactive_for_malformed_file)
            })
            .collect::<Vec<_>>();
        let line = owner_rules.first().map_or(1, |rule| rule.source_line + 1);
        let reject = |reason: String| SfdHeaderRuleRejection {
            owner: owner.clone(),
            line,
            reason,
        };
        if let Some((issue_line, reason)) = &control_structure_issue {
            scan.rejected.push(SfdHeaderRuleRejection {
                owner: owner.clone(),
                line: *issue_line,
                reason: format!("malformed Make control structure: {reason}"),
            });
            continue;
        }
        let [aggregate] = owner_rules.as_slice() else {
            scan.rejected.push(reject(format!(
                "SFD header aggregate has {} active ordinary rules; exactly one is required",
                owner_rules.len()
            )));
            continue;
        };
        if !safe_target_name(&owner) {
            scan.rejected.push(reject(
                "aggregate owner is not one safe named target".into(),
            ));
            continue;
        }
        if aggregate.state != ConditionalTruth::True
            || aggregate.conditional_syntax
            || aggregate
                .recipes
                .iter()
                .any(|recipe| recipe.state != ConditionalTruth::True || recipe.conditional_syntax)
        {
            scan.rejected.push(reject(
                "aggregate or recipe is affected by an unresolved Make conditional".into(),
            ));
            continue;
        }
        if !aggregate.recipes.is_empty() {
            scan.rejected.push(reject(
                "SFD header aggregate must have no recipe of its own".into(),
            ));
            continue;
        }

        let raw_outputs = aggregate
            .prerequisites
            .split_whitespace()
            .collect::<Vec<_>>();
        if raw_outputs.is_empty() {
            scan.rejected.push(reject(
                "SFD header aggregate must name at least one SDK header output".into(),
            ));
            continue;
        }
        let mut outputs = Vec::with_capacity(raw_outputs.len());
        let mut seen_outputs = BTreeSet::new();
        let mut output_error = None;
        for raw in raw_outputs {
            let Some(relative) = sdk_header_relative(raw) else {
                output_error = Some(format!(
                    "aggregate prerequisite `{raw}` is not a literal $(AROS_INCLUDES)/<relative>.h path"
                ));
                break;
            };
            if !safe_relative_path(relative, ".h") {
                output_error = Some(format!("SDK header path `{relative}` is unsafe"));
                break;
            }
            if !seen_outputs.insert(relative.to_owned()) {
                output_error = Some(format!("SDK header `{relative}` is listed more than once"));
                break;
            }
            outputs.push((raw.to_owned(), relative.to_owned()));
        }
        if let Some(reason) = output_error {
            scan.rejected.push(reject(reason));
            continue;
        }

        let makefile_path = root.join(&file);
        let file_sha256 = match regular_source_sha256(&root, &makefile_path) {
            Ok(hash) => hash,
            Err(reason) => {
                scan.rejected.push(reject(format!(
                    "declaring Makefile `{file}` is unavailable or unsafe: {reason}"
                )));
                continue;
            }
        };
        let Some(configured_sdk_root) = dirs.expand("$(AROS_INCLUDES)") else {
            scan.rejected.push(reject(
                "configured $(AROS_INCLUDES) root cannot be resolved".into(),
            ));
            continue;
        };
        let configured_sfdc = match dirs.expand("$(SFDC)") {
            Some(path) if path == "${AROS_BUILD_DIR}/hosttools/sfdc" => path,
            Some(path) => {
                scan.rejected.push(reject(format!(
                    "configured $(SFDC) resolves to `{path}`, not the private host sfdc output"
                )));
                continue;
            }
            None => {
                scan.rejected.push(reject(
                    "configured $(SFDC) host tool path cannot be resolved".into(),
                ));
                continue;
            }
        };

        let mut jobs = Vec::with_capacity(outputs.len());
        let mut product_error = None;
        for (raw_output, sdk_output) in outputs {
            let output_rules = rules
                .iter()
                .filter(|rule| {
                    rule.target.trim() == raw_output && rule.state != ConditionalTruth::False
                })
                .collect::<Vec<_>>();
            let [leaf] = output_rules.as_slice() else {
                product_error = Some(if output_rules.is_empty() {
                    format!("SDK output `{sdk_output}` has no active ordinary file rule")
                } else {
                    format!(
                        "SDK output `{sdk_output}` has {} active ordinary file rules",
                        output_rules.len()
                    )
                });
                break;
            };
            if leaf.state != ConditionalTruth::True
                || leaf.conditional_syntax
                || leaf.recipes.iter().any(|recipe| {
                    recipe.state != ConditionalTruth::True || recipe.conditional_syntax
                })
            {
                product_error = Some(format!(
                    "SDK output `{sdk_output}` or its recipe is affected by an unresolved Make conditional"
                ));
                break;
            }
            let raw_inputs = leaf.prerequisites.split_whitespace().collect::<Vec<_>>();
            let [raw_input] = raw_inputs.as_slice() else {
                product_error = Some(format!(
                    "SDK output `{sdk_output}` must have exactly one SFD input prerequisite"
                ));
                break;
            };
            let Some(input_name) = local_sfd_name(raw_input) else {
                product_error = Some(format!(
                    "SDK output `{sdk_output}` input `{raw_input}` is not a local $(SRCDIR)/$(CURDIR)/<file>.sfd path"
                ));
                break;
            };
            let [recipe] = leaf.recipes.as_slice() else {
                product_error = Some(format!(
                    "SDK output `{sdk_output}` must have exactly one SFDC argv recipe"
                ));
                break;
            };
            let Some((mode, target)) = parse_sfdc_recipe(&recipe.text) else {
                product_error = Some(format!(
                    "SDK output `{sdk_output}` recipe is outside the exact `$(SFDC) --mode=<clib|macros|proto> --target=<literal> --output=$@ $<` argv form"
                ));
                break;
            };

            let make_context = MakeExprContext::new(scope, dirs, leaf.source_line, &root, rel_dir);
            let expanded_output = match evaluate_make_expr(&raw_output, &make_context) {
                Ok(path) => path,
                Err(error) => {
                    product_error =
                        Some(format!("cannot resolve SDK output `{raw_output}`: {error}"));
                    break;
                }
            };
            let expected_output = format!(
                "{}/{}",
                configured_sdk_root.trim_end_matches('/'),
                sdk_output
            );
            if expanded_output != expected_output {
                product_error = Some(format!(
                    "SDK output `{raw_output}` resolves to `{expanded_output}`, expected `{expected_output}`"
                ));
                break;
            }
            let expanded_tool = match evaluate_make_expr(SFDC, &make_context) {
                Ok(path) => path,
                Err(error) => {
                    product_error = Some(format!("cannot resolve $(SFDC): {error}"));
                    break;
                }
            };
            if expanded_tool != configured_sfdc {
                product_error = Some(format!(
                    "$(SFDC) resolves to `{expanded_tool}`, expected `{configured_sfdc}`"
                ));
                break;
            }

            let input_relative = if rel_dir.as_os_str().is_empty() || rel_dir == Path::new(".") {
                input_name.to_owned()
            } else {
                let directory = file
                    .strip_suffix("/mmakefile.src")
                    .expect("source_relative_file always returns mmakefile.src");
                format!("{directory}/{input_name}")
            };
            let input_path = root.join(&input_relative);
            let input_sha256 = match regular_source_sha256(&root, &input_path) {
                Ok(hash) => hash,
                Err(reason) => {
                    product_error = Some(format!(
                        "SFD input `{input_relative}` is unavailable or unsafe: {reason}"
                    ));
                    break;
                }
            };
            let expanded_input = match evaluate_make_expr(raw_input, &make_context) {
                Ok(path) => path,
                Err(error) => {
                    product_error =
                        Some(format!("cannot resolve SFD input `{raw_input}`: {error}"));
                    break;
                }
            };
            let expected_input = format!("${{AROS_SOURCE_DIR}}/{input_relative}");
            if expanded_input.trim_end_matches('/') != expected_input {
                product_error = Some(format!(
                    "SFD input `{raw_input}` resolves to `{expanded_input}`, expected `{expected_input}`"
                ));
                break;
            }

            jobs.push(SfdHeaderJob {
                mode,
                target,
                input: input_relative,
                input_sha256,
                sdk_output,
            });
        }
        if let Some(reason) = product_error {
            scan.rejected.push(reject(reason));
            continue;
        }

        scan.declarations.push(SfdHeaderRuleDecl {
            owner,
            file: file.clone(),
            file_sha256,
            jobs,
        });
    }

    scan
}

fn fallback_rejection(content: &str, reason: String) -> SfdHeaderRuleScan {
    if !content.contains("$(SFDC)") {
        return SfdHeaderRuleScan::default();
    }
    SfdHeaderRuleScan {
        declarations: Vec::new(),
        rejected: vec![SfdHeaderRuleRejection {
            owner: owner_hint(content),
            line: 1,
            reason,
        }],
    }
}

fn source_relative_file(rel_dir: &Path) -> Result<String, String> {
    if rel_dir.is_absolute() {
        return Err("mmakefile directory is not source-relative".into());
    }
    let mut parts = Vec::new();
    for component in rel_dir.components() {
        let Component::Normal(value) = component else {
            if matches!(component, Component::CurDir) && rel_dir == Path::new(".") {
                continue;
            }
            return Err("mmakefile directory contains traversal or a root component".into());
        };
        let Some(value) = value.to_str() else {
            return Err("mmakefile directory is not UTF-8".into());
        };
        if !safe_path_component(value) {
            return Err(format!(
                "mmakefile directory has unsafe component `{value}`"
            ));
        }
        parts.push(value.to_owned());
    }
    if parts.is_empty() {
        Ok("mmakefile.src".into())
    } else {
        Ok(format!("{}/mmakefile.src", parts.join("/")))
    }
}

fn logical_lines(
    content: &str,
    line_states: Option<&[ConditionalTruth]>,
) -> (Vec<LogicalLine>, Option<(usize, String)>) {
    let mut define_stack = Vec::<usize>::new();
    let mut conditional_stack = Vec::<ConditionalFrame>::new();
    let mut structure_issue = None;
    let mut lines = Vec::new();
    for (index, raw) in content.lines().enumerate() {
        let mut text = raw.trim_end_matches('\r').to_owned();
        let is_recipe_line = text.starts_with('\t');
        let trimmed = if is_recipe_line {
            ""
        } else {
            crate::make_vars::strip_make_comment(text.trim()).trim()
        };
        let make_word = conditional_word(trimmed);
        let define_start = is_define_start(trimmed);
        let define_end = make_word == Some("endef");
        let inside_define = !define_stack.is_empty();
        let suppressed = inside_define || define_start || define_end;

        if define_start {
            define_stack.push(index + 1);
        } else if define_end && inside_define {
            define_stack.pop();
        } else if define_end && structure_issue.is_none() {
            structure_issue = Some((index + 1, "unmatched `endef`".to_owned()));
        }

        if !suppressed {
            match make_word {
                Some("ifeq" | "ifneq" | "ifdef" | "ifndef") => {
                    conditional_stack.push(ConditionalFrame {
                        open_line: index + 1,
                        plain_else_seen: false,
                    });
                }
                Some("endif") => {
                    if conditional_stack.pop().is_none() && structure_issue.is_none() {
                        structure_issue = Some((index + 1, "unmatched `endif`".to_owned()));
                    }
                }
                Some("else") => {
                    let tail = trimmed
                        .strip_prefix("else")
                        .unwrap_or_default()
                        .trim_start();
                    if let Some(frame) = conditional_stack.last_mut() {
                        let is_else_if = conditional_word(tail).is_some_and(|word| {
                            matches!(word, "ifeq" | "ifneq" | "ifdef" | "ifndef")
                        });
                        if is_else_if {
                            if frame.plain_else_seen && structure_issue.is_none() {
                                structure_issue = Some((
                                    index + 1,
                                    "`else if...` follows a final `else`".to_owned(),
                                ));
                            }
                        } else if tail.is_empty() {
                            if frame.plain_else_seen && structure_issue.is_none() {
                                structure_issue = Some((
                                    index + 1,
                                    "duplicate `else` in one conditional".to_owned(),
                                ));
                            }
                            frame.plain_else_seen = true;
                        } else if structure_issue.is_none() {
                            structure_issue = Some((
                                index + 1,
                                format!("unsupported conditional branch `{trimmed}`"),
                            ));
                        }
                    } else if structure_issue.is_none() {
                        structure_issue = Some((index + 1, "unmatched `else`".to_owned()));
                    }
                }
                _ => {}
            }
        }
        if suppressed {
            text.clear();
        }
        lines.push(LogicalLine {
            text,
            source_line: index,
            state: line_states.map_or(ConditionalTruth::True, |states| {
                states
                    .get(index)
                    .copied()
                    .unwrap_or(ConditionalTruth::Unknown)
            }),
            conditional_syntax: line_states.is_none() && !conditional_stack.is_empty(),
        });
    }
    if structure_issue.is_none() {
        let conditional_open = conditional_stack.first().map(|frame| frame.open_line);
        let define_open = define_stack.first().copied();
        match (conditional_open, define_open) {
            (Some(line), Some(define_line)) if define_line < line => {
                structure_issue = Some((
                    define_line,
                    "missing `endef` for an open `define`".to_owned(),
                ));
            }
            (Some(line), _) => {
                structure_issue =
                    Some((line, "missing `endif` for an open conditional".to_owned()));
            }
            (None, Some(line)) => {
                structure_issue = Some((line, "missing `endef` for an open `define`".to_owned()));
            }
            (None, None) => {}
        }
    }
    (lines, structure_issue)
}

fn is_define_start(line: &str) -> bool {
    let mut words = line.split_whitespace();
    match words.next() {
        Some("define") => true,
        Some("override" | "export" | "private") => words.next() == Some("define"),
        _ => false,
    }
}

fn parse_rules(lines: Vec<LogicalLine>) -> Vec<Rule> {
    let mut rules = Vec::new();
    let mut current: Option<Rule> = None;
    for line in lines {
        if line.text.starts_with('\t') {
            if let Some(rule) = current.as_mut() {
                let both_inactive =
                    rule.state == ConditionalTruth::False && line.state == ConditionalTruth::False;
                let both_possible =
                    rule.state != ConditionalTruth::False && line.state != ConditionalTruth::False;
                if both_inactive || both_possible {
                    rule.recipes.push(RecipeLine {
                        text: line.text.trim().to_owned(),
                        state: line.state,
                        conditional_syntax: line.conditional_syntax,
                    });
                    rule.conditional_syntax |= line.conditional_syntax;
                }
            }
            continue;
        }
        let header = line.text.trim();
        if header.is_empty() || header.starts_with('#') {
            continue;
        }
        if is_conditional_directive(header) {
            if current.as_ref().is_some_and(|rule| rule.recipes.is_empty()) {
                rules.push(current.take().expect("current rule was just inspected"));
            } else if let Some(rule) = current.as_mut() {
                rule.conditional_syntax |=
                    line.conditional_syntax || line.state == ConditionalTruth::Unknown;
            }
            continue;
        }
        if let Some(rule) = current.take() {
            rules.push(rule);
        }
        let Some((target, prerequisites)) = header.split_once(':') else {
            continue;
        };
        let target = target.trim();
        if target.is_empty() || prerequisites.starts_with([':', '=']) {
            continue;
        }
        current = Some(Rule {
            target: target.to_owned(),
            prerequisites: prerequisites.trim().to_owned(),
            source_line: line.source_line,
            state: line.state,
            conditional_syntax: line.conditional_syntax,
            recipes: Vec::new(),
        });
    }
    if let Some(rule) = current {
        rules.push(rule);
    }
    rules
}

fn is_conditional_directive(line: &str) -> bool {
    matches!(
        conditional_word(line),
        Some("ifeq" | "ifneq" | "ifdef" | "ifndef" | "else" | "endif")
    )
}

fn conditional_word(line: &str) -> Option<&str> {
    line.split_whitespace().next()
}

fn is_sdk_header_expression(raw: &str) -> bool {
    raw.starts_with(SDK_PREFIX) && has_exact_extension(raw, "h")
}

fn sdk_header_relative(raw: &str) -> Option<&str> {
    raw.strip_prefix(SDK_PREFIX)
}

fn local_sfd_name(raw: &str) -> Option<&str> {
    let name = raw.strip_prefix(SOURCE_PREFIX)?;
    (safe_path_component(name) && has_exact_extension(name, "sfd")).then_some(name)
}

/// Make's suffix contract is intentionally case-sensitive (`.h` and `.sfd`
/// only), including on hosts with case-insensitive filesystems.
fn has_exact_extension(value: &str, extension: &str) -> bool {
    Path::new(value)
        .extension()
        .and_then(|extension| extension.to_str())
        == Some(extension)
}

fn parse_sfdc_recipe(raw: &str) -> Option<(String, String)> {
    let tokens = raw.split_whitespace().collect::<Vec<_>>();
    if tokens.len() != 5 {
        return None;
    }
    let [tool, mode_arg, target_arg, output_arg, input_arg] =
        [tokens[0], tokens[1], tokens[2], tokens[3], tokens[4]];
    if tool != SFDC || output_arg != "--output=$@" || input_arg != "$<" {
        return None;
    }
    let mode = mode_arg.strip_prefix("--mode=")?;
    if !MODES.contains(&mode) {
        return None;
    }
    let target = target_arg.strip_prefix("--target=")?;
    if !safe_target_name(target) {
        return None;
    }
    Some((mode.to_owned(), target.to_owned()))
}

fn has_sfd_signal(rule: &Rule) -> bool {
    rule.recipes.iter().any(|recipe| recipe.text.contains(SFDC))
        || rule.prerequisites.split_whitespace().any(|prerequisite| {
            prerequisite.starts_with(SOURCE_PREFIX) && has_exact_extension(prerequisite, "sfd")
        })
}

fn safe_target_name(value: &str) -> bool {
    !value.is_empty()
        && value
            .chars()
            .next()
            .is_some_and(|character| character.is_ascii_alphanumeric())
        && value
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || "_.+-".contains(character))
        && value != "."
        && value != ".."
}

fn safe_path_component(value: &str) -> bool {
    !value.is_empty()
        && value != "."
        && value != ".."
        && value
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || "_.+-".contains(character))
}

fn safe_relative_path(value: &str, extension: &str) -> bool {
    if !value.ends_with(extension)
        || value.starts_with('/')
        || value.contains(['\\', '$', ';', ':', '|', '"', '\'', '`'])
        || value.chars().any(char::is_whitespace)
    {
        return false;
    }
    let path = Path::new(value);
    if path.is_absolute() {
        return false;
    }
    path.components().all(|component| match component {
        Component::Normal(part) => part.to_str().is_some_and(safe_path_component),
        _ => false,
    })
}

fn regular_source_sha256(root: &Path, path: &Path) -> Result<String, String> {
    let relative = path
        .strip_prefix(root)
        .map_err(|_| format!("{} is outside the source tree", path.display()))?;
    let mut cursor = root.to_path_buf();
    for component in relative.components() {
        let Component::Normal(component) = component else {
            return Err(format!("{} has an unsafe path component", path.display()));
        };
        cursor.push(component);
        let metadata = fs::symlink_metadata(&cursor)
            .map_err(|error| format!("cannot inspect {}: {error}", cursor.display()))?;
        if metadata.file_type().is_symlink() {
            return Err(format!("{} contains a symlink", cursor.display()));
        }
    }
    let metadata = fs::symlink_metadata(path)
        .map_err(|error| format!("cannot inspect {}: {error}", path.display()))?;
    if metadata.file_type().is_symlink() || !metadata.file_type().is_file() {
        return Err(format!(
            "{} is not a regular non-symlink file",
            path.display()
        ));
    }
    let canonical = path
        .canonicalize()
        .map_err(|error| format!("cannot resolve {}: {error}", path.display()))?;
    if !canonical.starts_with(root) {
        return Err(format!("{} escapes the source tree", path.display()));
    }
    let bytes =
        fs::read(path).map_err(|error| format!("cannot read {}: {error}", path.display()))?;
    Ok(aros_common::sha256_bytes(&bytes).to_string())
}

fn owner_hint(content: &str) -> String {
    content
        .lines()
        .filter_map(|line| line.trim().strip_prefix("#MM "))
        .filter_map(|line| line.split_once(':').map(|(owner, _)| owner.trim()))
        .find(|owner| safe_target_name(owner))
        .unwrap_or("<unknown-owner>")
        .to_owned()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::make_vars::collect_vars_impl;
    use crate::parser::{join_continuations, TargetContext};
    use crate::{generate_cmake, DependencyGraph};
    use std::fs;
    use tempfile::TempDir;

    const OWNER: &str = "fixture-sdk-headers";
    const DIRECTORY: &str = "arch/example";

    fn fixture() -> TempDir {
        let root = tempfile::tempdir().expect("temporary source root");
        fs::create_dir_all(root.path().join("config")).expect("config directory");
        fs::write(
            root.path().join("config/make.cfg.in"),
            "AROS_DIR_AROS := SYS\nAROS_DIR_DEVELOPER := Developer\nAROS_DIR_INCLUDE := include\nAROSDIR := $(TARGETDIR)/$(AROS_DIR_AROS)\nAROS_DEVELOPER := $(AROSDIR)/$(AROS_DIR_DEVELOPER)\nAROS_INCLUDES := $(AROS_DEVELOPER)/$(AROS_DIR_INCLUDE)\nSFDC := $(TOOLDIR)/sfdc\n",
        )
        .expect("source directory configuration");
        fs::create_dir_all(root.path().join(DIRECTORY)).expect("fixture source directory");
        fs::write(root.path().join(DIRECTORY).join("api.sfd"), "## fixture\n")
            .expect("fixture SFD input");
        root
    }

    fn fixture_source() -> String {
        format!(
            "#MM\n{OWNER}: $(AROS_INCLUDES)/clib/api_protos.h $(AROS_INCLUDES)/proto/api.h\n\
             $(AROS_INCLUDES)/clib/api_protos.h: $(SRCDIR)/$(CURDIR)/api.sfd\n\
             \t$(SFDC) --mode=clib --target=x-test-aros --output=$@ $<\n\
             $(AROS_INCLUDES)/proto/api.h: $(SRCDIR)/$(CURDIR)/api.sfd\n\
             \t$(SFDC) --mode=proto --target=x-test-aros --output=$@ $<\n",
        )
    }

    fn scan(root: &TempDir, source: &str) -> SfdHeaderRuleScan {
        let raw_path = root.path().join(DIRECTORY).join("mmakefile.src");
        fs::write(&raw_path, source).expect("write fixture mmakefile");
        let joined = join_continuations(source);
        let target = TargetContext::default();
        let (scope, states) = collect_vars_impl(&joined, Some(&target));
        let dirs = DirVars::load(root.path());
        collect_sfd_header_rules_with_context(
            &joined,
            root.path(),
            Path::new(DIRECTORY),
            &scope,
            &dirs,
            Some(&states),
            &[OWNER.to_owned()],
        )
    }

    #[test]
    fn scans_generic_named_provider_and_emits_source_owned_jobs() {
        let root = fixture();
        let source = fixture_source();
        let scan = scan(&root, &source);
        assert!(scan.rejected.is_empty(), "{:#?}", scan.rejected);
        assert_eq!(scan.declarations.len(), 1);
        let declaration = &scan.declarations[0];
        assert_eq!(declaration.owner, OWNER);
        assert_eq!(declaration.file, "arch/example/mmakefile.src");
        assert_eq!(
            declaration.file_sha256,
            aros_common::sha256_bytes(source.as_bytes()).to_string()
        );
        assert_eq!(declaration.jobs.len(), 2);
        assert_eq!(declaration.jobs[0].mode, "clib");
        assert_eq!(declaration.jobs[0].target, "x-test-aros");
        assert_eq!(declaration.jobs[0].input, "arch/example/api.sfd");
        assert_eq!(declaration.jobs[0].sdk_output, "clib/api_protos.h");
        assert_eq!(
            declaration.jobs[0].input_sha256,
            aros_common::sha256_bytes(b"## fixture\n").to_string()
        );

        let mut graph = DependencyGraph::default();
        graph.sfd_header_rules = scan.declarations;
        let generated = generate_cmake(&graph);
        assert!(generated.contains("aros_generate_sfd_headers(\n"));
        assert!(generated.contains("FILE \"arch/example/mmakefile.src\""));
        assert!(generated.contains("JOBS\n"));
        assert!(generated.contains("\"clib|x-test-aros|arch/example/api.sfd|"));
        assert!(generated.contains("|clib/api_protos.h\""));
        assert!(!generated.contains("GENINC"));
    }

    #[test]
    fn rejects_command_drift_extra_outputs_and_traversal() {
        for (source, expected) in [
            (
                fixture_source().replace("--output=$@ $<", "--output=$@ $< --verbose"),
                "exact `$(SFDC)",
            ),
            (
                fixture_source().replace(
                    "$(AROS_INCLUDES)/proto/api.h",
                    "$(AROS_INCLUDES)/../outside.h",
                ),
                "unsafe",
            ),
            (
                fixture_source().replace(
                    "$(AROS_INCLUDES)/proto/api.h: $(SRCDIR)/$(CURDIR)/api.sfd",
                    "$(AROS_INCLUDES)/proto/api.h: $(SRCDIR)/$(CURDIR)/api.sfd $(SRCDIR)/$(CURDIR)/other.sfd",
                ),
                "exactly one SFD input",
            ),
        ] {
            let root = fixture();
            let scan = scan(&root, &source);
            assert!(scan.declarations.is_empty());
            assert_eq!(scan.rejected.len(), 1, "{:#?}", scan.rejected);
            assert!(scan.rejected[0].reason.contains(expected), "{:#?}", scan.rejected);
        }
    }

    #[test]
    fn rejects_unknown_conditionals_and_omits_false_branches() {
        let root = fixture();
        let source = format!("ifdef UNKNOWN_FLAG\n{}endif\n", fixture_source());
        let unknown_scan = scan(&root, &source);
        assert!(unknown_scan.declarations.is_empty());
        assert!(unknown_scan.rejected[0].reason.contains("conditional"));

        let root = fixture();
        let source = format!("ifeq (left,right)\n{}endif\n", fixture_source());
        let scan = scan(&root, &source);
        assert!(scan.declarations.is_empty());
        assert!(scan.rejected.is_empty(), "{:#?}", scan.rejected);
    }

    #[test]
    fn rejects_malformed_conditional_structure_on_sfd_candidates() {
        for (source, expected) in [
            (
                format!("ifeq (left,left)\n{}", fixture_source()),
                "missing `endif`",
            ),
            (format!("else\n{}", fixture_source()), "unmatched `else`"),
            (format!("endif\n{}", fixture_source()), "unmatched `endif`"),
            (
                format!("ifeq (left,right)\nelse\nelse\n{}endif\n", fixture_source()),
                "duplicate `else`",
            ),
            (format!("endef\n{}", fixture_source()), "unmatched `endef`"),
            (
                format!("{}define OPEN\n", fixture_source()),
                "missing `endef`",
            ),
        ] {
            let root = fixture();
            let scan = scan(&root, &source);
            assert!(scan.declarations.is_empty());
            assert_eq!(scan.rejected.len(), 1, "{:#?}", scan.rejected);
            assert!(
                scan.rejected[0].reason.contains(expected),
                "{:#?}",
                scan.rejected
            );
        }
    }

    #[test]
    fn define_body_rules_do_not_prove_an_active_sfd_provider() {
        let root = fixture();
        let source = format!(
            "#MM\n{OWNER}: $(AROS_INCLUDES)/proto/api.h\n\
             define OUTER\n\
             define INNER\n\
             $(AROS_INCLUDES)/proto/api.h: $(SRCDIR)/$(CURDIR)/api.sfd\n\
             \t$(SFDC) --mode=proto --target=x-test-aros --output=$@ $<\n\
             endef\n\
             endef\n"
        );
        let scan = scan(&root, &source);
        assert!(scan.declarations.is_empty());
        assert!(scan.rejected.is_empty(), "{:#?}", scan.rejected);

        let mut graph = DependencyGraph::default();
        graph.make_meta_providers.insert(OWNER.to_owned());
        let error = graph
            .selected_dependency_closure(&[OWNER.to_owned()], &TargetContext::default(), &[])
            .expect_err("a define-body recipe is not an active provider endpoint");
        assert!(error
            .to_string()
            .contains("selected nonvirtual Make provider"));
    }

    #[test]
    fn tabbed_recipe_words_are_not_make_control_directives() {
        for word in ["endif", "define UNUSED"] {
            let root = fixture();
            let source = format!("{}\t{word}\n", fixture_source());
            let scan = scan(&root, &source);
            assert!(scan.declarations.is_empty());
            assert_eq!(scan.rejected.len(), 1, "{:#?}", scan.rejected);
            assert!(scan.rejected[0]
                .reason
                .contains("exactly one SFDC argv recipe"));
            assert!(!scan.rejected[0].reason.contains("malformed Make control"));
        }
    }

    #[cfg(unix)]
    #[test]
    fn rejects_symlinked_sfd_input() {
        use std::os::unix::fs::symlink;
        let root = fixture();
        fs::write(root.path().join(DIRECTORY).join("real.sfd"), "## source\n")
            .expect("real SFD input");
        fs::remove_file(root.path().join(DIRECTORY).join("api.sfd"))
            .expect("remove original SFD input");
        symlink("real.sfd", root.path().join(DIRECTORY).join("api.sfd"))
            .expect("symlink SFD input");
        let scan = scan(&root, &fixture_source());
        assert!(scan.declarations.is_empty());
        assert!(scan.rejected[0].reason.contains("symlink"));
    }

    fn declaration(owner: &str, output: &str) -> SfdHeaderRuleDecl {
        SfdHeaderRuleDecl {
            owner: owner.to_owned(),
            file: format!("arch/example/{owner}.src"),
            file_sha256: "a".repeat(64),
            jobs: vec![SfdHeaderJob {
                mode: "proto".to_owned(),
                target: "x-test-aros".to_owned(),
                input: "arch/example/api.sfd".to_owned(),
                input_sha256: "b".repeat(64),
                sdk_output: output.to_owned(),
            }],
        }
    }

    #[test]
    fn selected_provider_has_an_endpoint_and_retains_only_its_declaration() {
        let mut graph = DependencyGraph::default();
        graph.make_meta_providers.insert(OWNER.to_owned());
        graph.sfd_header_rules = vec![
            declaration(OWNER, "proto/api.h"),
            declaration("unselected-provider", "proto/unselected.h"),
        ];
        let context = TargetContext::default();
        let selected = graph
            .selected_dependency_closure(&[OWNER.to_owned()], &context, &[])
            .expect("the selected SFD provider is a concrete endpoint");
        assert!(selected.contains(OWNER));
        graph
            .retain_native_selection(&selected, &context)
            .expect("selected owner has resolvable native endpoints");
        assert_eq!(graph.sfd_header_rules.len(), 1);
        assert_eq!(graph.sfd_header_rules[0].owner, OWNER);
    }

    #[test]
    fn selected_sfd_owners_cannot_claim_one_sdk_header_twice() {
        let mut graph = DependencyGraph::default();
        graph
            .make_meta_providers
            .extend(["provider-a".to_owned(), "provider-b".to_owned()]);
        graph.sfd_header_rules = vec![
            declaration("provider-a", "proto/shared.h"),
            declaration("provider-b", "proto/shared.h"),
        ];
        let error = graph
            .selected_dependency_closure(
                &["provider-a".to_owned(), "provider-b".to_owned()],
                &TargetContext::default(),
                &[],
            )
            .expect_err("an SDK header cannot have two source producers");
        assert!(error.to_string().contains("both produce SDK header"));
    }
}
