//! Closed source projection for the two native `%compile_q` lanes.
//!
//! This records source-level compiler arguments and finite object identities;
//! it does not create graph targets or assert that any owner is a native
//! provider. Ordinary archive owners are provenance labels only.

use crate::dirs::DirVars;
use crate::literal_objects::LiteralObjectDecl;
use crate::make_expr::{
    evaluate_make_expr, evaluate_make_list, MakeExprContext, MakeVariableLookup,
};
use crate::make_vars::{strip_make_comment, variable_assignment, ConditionalTruth, VarScope};
use crate::parser::macro_invocations;
use crate::source_archive_rules::{ArchiveMembers, SourceArchiveDecl};
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Component, Path, PathBuf};

const SOURCE_ALIAS: &str = "${AROS_SOURCE_DIR}";
const BUILD_ALIAS: &str = "${AROS_BUILD_DIR}";
const GENERATED_ALIAS: &str = "${AROS_BUILD_DIR}/gen";
const MAX_SNAPSHOT_BYTES: usize = 1_048_576;
const MAX_OBJECTS: usize = 4096;
const MAX_REJECTIONS: usize = 512;

const FILEACTIONMSG: &[&str] = &[
    "%define fileactionmsg msg= file= elipses=",
    "$(Q)$(ECHO) \"%(msg)  $(if $(filter /%,%(file)),$(if $(filter $(SRCDIR)/%,$(abspath %(file))),$(patsubst $(SRCDIR)/%,%,$(abspath %(file))),$(patsubst $(TOP)/%,%,$(abspath %(file)))),$(patsubst $(SRCDIR)/%,%,$(abspath $(SRCDIR)/$(CURDIR)/%(file)))) %(elipses)\"",
    "%end",
];
const COMPILE_Q: &[&str] = &[
    "%define compile_q cmd=\"$(strip $(TARGET_CC) $(TARGET_SYSROOT))\" opt=\"$(strip $(CFLAGS) $(CPPFLAGS))\" from=\"$<\" to=\"$@\" incextra=\"$(TOP)/$(CURDIR)\" iquote=\"$(CFLAGS_IQUOTE)\" iquote_end=\"$(CFLAGS_IQUOTE_END)\"",
    "%fileactionmsg msg=\"Compiling\" file=\"%(from)\"",
    "$(Q)$(IF) %(cmd) %(iquote) $(dir %(from)) %(iquote) %(incextra) %(iquote) $(SRCDIR)/$(CURDIR) %(iquote) . %(iquote_end) %(opt) -D__SRCFILENAME__=\"\\\"$(subst $(TOP)/,,$(subst $(SRCDIR)/,,$(abspath %(from))))\"\\\" -c %(from) -o %(to) > $(GENDIR)/cerrors 2>&1 ; then \\",
    "$(IF) $(TEST) -s $(GENDIR)/cerrors ; then \\",
    "$(ECHO) \"%(from): %(cmd) %(iquote) $(dir %(from)) %(iquote) %(incextra) %(iquote) $(SRCDIR)/$(CURDIR) %(iquote) . %(iquote_end) %(opt) -D__SRCFILENAME__=\\\"$(subst $(TOP)/,,$(subst $(SRCDIR)/,,$(abspath %(from))))\\\" -c %(from) -o %(to)\" >> $(GENDIR)/errors ; \\",
    "tee < $(GENDIR)/cerrors -a $(GENDIR)/errors ; \\",
    "else \\",
    "$(NOP) ; \\",
    "fi ; \\",
    "else \\",
    "$(ECHO) \"Compile failed: %(cmd) %(iquote) $(dir %(from)) %(iquote) %(incextra) %(iquote) $(SRCDIR)/$(CURDIR) %(iquote) . %(iquote_end) %(opt) -D__SRCFILENAME__=\\\"$(subst $(TOP)/,,$(subst $(SRCDIR)/,,$(abspath %(from))))\\\" -c %(from) -o %(to)\" 1>&2 ; \\",
    "tee < $(GENDIR)/cerrors -a $(GENDIR)/errors 1>&2 ; \\",
    "exit 1 ; \\",
    "fi",
    "%end",
];
const HIDD_STUBS: &[&str] = &[
    "%define make_hidd_stubs hidd=/A cppflags=\"$(CPPFLAGS)\" cflags=\"$(CFLAGS)\" dflags=\"$(CFLAGS)\" parenttarget=linklibs-hidd-stubs",
    "STUBS_SRC := $(addprefix $(SRCDIR)/$(CURDIR)/,$(addsuffix .c,$(STUBS)))",
    "STUBS_MEM := $(addsuffix .o,$(STUBS))",
    "STUBS_OBJ := $(addprefix $(GENDIR)/lib/hidd/,$(STUBS_MEM))",
    "STUBS_DEP := $(addprefix $(OBJDIR)/,$(addsuffix .d,$(STUBS)))",
    "#MM- %(parenttarget): hidd-%(hidd)-stubs",
    "#MM hidd-%(hidd)-stubs : includes includes-copy",
    "hidd-%(hidd)-stubs : setup $(STUBS_OBJ)",
    "$(STUBS_OBJ) : $(STUBS_SRC)",
    "%compile_q cmd=\"$(strip $(TARGET_CC) $(TARGET_SYSROOT))\" opt=\"$(strip %(cflags) %(cppflags))\" iquote=\"$(CFLAGS_IQUOTE)\" iquote_end=\"$(CFLAGS_IQUOTE_END)\"",
    "$(STUBS_DEP) : $(STUBS_SRC)",
    "%mkdepend_q flags=\"$(strip %(dflags) %(cppflags))\"",
    "setup ::",
    "%mkdirs_q $(OBJDIR) $(GENDIR)/lib/hidd",
    "#MM",
    "clean ::",
    "-@$(RM) $(OBJDIR)",
    "DEPS := $(DEPS) $(STUBS_DEP)",
    "%end",
];

/// A group of object producers projected from one source declaration.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SourceCompileGroupDecl {
    /// HIDD macro target, or the archive owner used only as provenance.
    /// Ordinary archive projections can cover a subset of the archive's
    /// members; this metadata is not a provider claim. Any later binder must
    /// prove complete member-to-producer coverage before qualifying the
    /// archive or its owner.
    pub owner: String,
    /// Parent target generated by `%make_hidd_stubs`; `None` for ordinary
    /// archive-member projections, which do not imply a separate Make owner.
    pub parent: Option<String>,
    /// Source-relative mmakefile path.
    pub file: String,
    /// One-based macro invocation or archive-rule line.
    pub line: usize,
    /// The archive whose exact member list supplied this ordinary group.
    /// `None` for HIDD stub macro groups.
    pub archive_output: Option<String>,
    /// Projected compile producers in source declaration order.
    pub objects: Vec<LiteralObjectDecl>,
}

/// A relevant source compile declaration that could not be represented.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct SourceCompileRejection {
    pub(crate) owner: String,
    pub(crate) file: String,
    pub(crate) line: usize,
    pub(crate) reason: String,
}

#[derive(Debug, Clone)]
struct PatternRule {
    line: usize,
    state: ConditionalTruth,
    target: String,
    prerequisites: String,
    order_only: Option<String>,
    inline_recipe: Option<String>,
    recipes: Vec<(String, ConditionalTruth)>,
    valid: bool,
}

/// Collects the closed `%compile_q` forms used for HIDD stub sources and
/// exact ordinary source-archive members.
///
/// The template is read as a regular source file below `source_root`; changed
/// `%compile_q`, `%fileactionmsg`, or `%make_hidd_stubs` definitions stop this
/// projection. HIDD options are read at each macro invocation. Ordinary
/// pattern-rule options use the final file scope, matching deferred Make
/// recipe expansion. `archives` must be source declarations for this same
/// joined mmakefile; only their exact member lists are considered.
#[must_use]
pub(crate) fn collect_from_snapshot(
    content: &str,
    scope: &VarScope,
    dirs: &DirVars,
    source_root: &Path,
    relative_dir: &Path,
    line_states: Option<&[ConditionalTruth]>,
    archives: &[SourceArchiveDecl],
) -> (Vec<SourceCompileGroupDecl>, Vec<SourceCompileRejection>) {
    let file = match source_file(source_root, relative_dir) {
        Ok(file) => file,
        Err(reason) => {
            return if looks_compile_relevant(content, archives) {
                (
                    Vec::new(),
                    vec![rejection("<unknown>", relative_dir, 1, reason)],
                )
            } else {
                (Vec::new(), Vec::new())
            };
        }
    };
    if content.len() > MAX_SNAPSHOT_BYTES {
        return if looks_compile_relevant(content, archives) {
            (
                Vec::new(),
                vec![rejection(
                    "<unknown>",
                    relative_dir,
                    1,
                    "joined mmakefile exceeds the source-compile scan limit",
                )],
            )
        } else {
            (Vec::new(), Vec::new())
        };
    }

    let hidd_invocations = macro_invocations(content)
        .into_iter()
        .filter(|invocation| invocation.name == "make_hidd_stubs")
        .collect::<Vec<_>>();
    let relevant_archives = archives
        .iter()
        .filter(|archive| archive.file == file)
        .filter(|archive| matches!(archive.members, ArchiveMembers::Exact(_)))
        .collect::<Vec<_>>();
    if hidd_invocations.is_empty() && relevant_archives.is_empty() {
        return (Vec::new(), Vec::new());
    }

    let source_lines = content.lines().collect::<Vec<_>>();
    let states = line_states;
    if let Some((line, name)) = local_template_macro_shadow(&source_lines) {
        return (
            Vec::new(),
            candidate_rejections(
                &format!("source locally redefines `%{name}` at line {line}"),
                relative_dir,
                &relevant_archives,
                &hidd_invocations,
                states,
            ),
        );
    }
    if let Some(reason) = role_mutation_issue(&source_lines) {
        return (
            Vec::new(),
            candidate_rejections(
                &reason,
                relative_dir,
                &relevant_archives,
                &hidd_invocations,
                states,
            ),
        );
    }

    let template = match read_make_template(source_root) {
        Ok(template) => template,
        Err(reason) => {
            return (
                Vec::new(),
                candidate_rejections(
                    &reason,
                    relative_dir,
                    &relevant_archives,
                    &hidd_invocations,
                    states,
                ),
            );
        }
    };
    if let Err(reason) = validate_template(&template) {
        return (
            Vec::new(),
            candidate_rejections(
                &format!("source `%compile_q` template is outside the closed model: {reason}"),
                relative_dir,
                &relevant_archives,
                &hidd_invocations,
                states,
            ),
        );
    }

    let lines = source_lines;
    let mut groups = Vec::new();
    let mut rejections = Vec::new();
    let mut seen_outputs = BTreeMap::<String, (String, usize)>::new();

    for invocation in hidd_invocations {
        let state = state_at(states, invocation.line);
        if state == ConditionalTruth::False {
            continue;
        }
        let macro_owner = parse_hidd_invocation(&invocation.args);
        let hidd = match macro_owner {
            Ok(hidd) if state == ConditionalTruth::True => hidd,
            Ok(hidd) => {
                rejections.push(rejection(
                    &format!("hidd-{hidd}-stubs"),
                    relative_dir,
                    invocation.line + 1,
                    "`%make_hidd_stubs` is conditional or has unknown line state",
                ));
                continue;
            }
            Err(reason) => {
                rejections.push(rejection(
                    "<unknown>",
                    relative_dir,
                    invocation.line + 1,
                    reason,
                ));
                continue;
            }
        };
        let owner = format!("hidd-{hidd}-stubs");
        match hidd_group(
            &owner,
            &file,
            invocation.line,
            scope,
            dirs,
            source_root,
            relative_dir,
        ) {
            Ok(group) => {
                if record_outputs(&group, &mut seen_outputs, &mut rejections, relative_dir) {
                    groups.push(group);
                }
            }
            Err(reason) => {
                rejections.push(rejection(&owner, relative_dir, invocation.line + 1, reason));
            }
        }
    }

    if !relevant_archives.is_empty() {
        let (pattern, pattern_error) = find_default_pattern_rule(&lines, states);
        for archive in relevant_archives {
            let owner = &archive.owner;
            let ArchiveMembers::Exact(members) = &archive.members else {
                continue;
            };
            if members.len() > MAX_OBJECTS {
                rejections.push(rejection(
                    owner,
                    relative_dir,
                    archive.line,
                    "ordinary archive exceeds the finite source-object limit",
                ));
                continue;
            }
            if let Some(reason) = &pattern_error {
                if members.iter().any(|member| {
                    member.starts_with(&format!("{GENERATED_ALIAS}/"))
                        && Path::new(member).extension().is_some_and(|ext| ext == "o")
                        && Path::new(member)
                            .strip_prefix(format!("{GENERATED_ALIAS}/{}", relative_dir.display()))
                            .is_ok()
                }) {
                    rejections.push(rejection(owner, relative_dir, archive.line, reason.clone()));
                }
                continue;
            }
            let Some(pattern_rule) = pattern.as_ref() else {
                continue;
            };
            if pattern_rule.state != ConditionalTruth::True {
                rejections.push(rejection(
                    owner,
                    relative_dir,
                    pattern_rule.line + 1,
                    "ordinary `OBJDIR/%.o : %.c` compile rule is conditional or has unknown line state",
                ));
                continue;
            }
            let mut objects = Vec::new();
            let mut failed = None;
            for member in members {
                // This is deliberately a partial projection: archive members
                // not matching this local pattern may have another producer.
                // These groups are metadata only, never provider claims. Any
                // later archive binder must establish complete coverage.
                let Some(relative_source) = object_source_relative(
                    member,
                    scope,
                    dirs,
                    source_root,
                    relative_dir,
                    pattern_rule.line,
                )
                .ok() else {
                    continue;
                };
                let source_path = match safe_source_file(source_root, &relative_source) {
                    Ok(path) => path,
                    Err(reason) => {
                        failed = Some(format!("ordinary object source `{member}`: {reason}"));
                        break;
                    }
                };
                let _ = source_path;
                let declaration = match ordinary_object(
                    member,
                    &relative_source,
                    scope,
                    dirs,
                    source_root,
                    relative_dir,
                    pattern_rule.line,
                ) {
                    Ok(declaration) => declaration,
                    Err(reason) => {
                        failed = Some(reason);
                        break;
                    }
                };
                objects.push(declaration);
            }
            if let Some(reason) = failed {
                rejections.push(rejection(owner, relative_dir, archive.line, reason));
                continue;
            }
            if objects.is_empty() {
                continue;
            }
            let group = SourceCompileGroupDecl {
                owner: owner.clone(),
                parent: None,
                file: file.clone(),
                line: archive.line,
                archive_output: Some(archive.output.clone()),
                objects,
            };
            if record_outputs(&group, &mut seen_outputs, &mut rejections, relative_dir) {
                groups.push(group);
            }
        }
    }

    rejections.truncate(MAX_REJECTIONS);
    (groups, rejections)
}

fn hidd_group(
    owner: &str,
    file: &str,
    invocation_line: usize,
    scope: &VarScope,
    dirs: &DirVars,
    source_root: &Path,
    relative_dir: &Path,
) -> Result<SourceCompileGroupDecl, String> {
    let context = MakeExprContext::new(scope, dirs, invocation_line, source_root, relative_dir);
    let stubs = evaluate_make_list("$(STUBS)", &context)
        .map_err(|error| format!("cannot resolve `%make_hidd_stubs` STUBS list: {error}"))?;
    if stubs.len() != 1 {
        return Err("`%make_hidd_stubs` is admitted only for one STUBS source because its multi-target rule uses one shared first prerequisite".into());
    }
    let mut unique = BTreeSet::new();
    let mut objects = Vec::with_capacity(stubs.len());
    for stub in stubs {
        if !safe_stem(&stub) || !unique.insert(stub.clone()) {
            return Err(format!(
                "HIDD STUBS member `{stub}` is unsafe or duplicated"
            ));
        }
        let source = source_alias(relative_dir, &format!("{stub}.c"))?;
        let source_path = safe_source_file(source_root, Path::new(source_alias_tail(&source)?))?;
        let _ = source_path;
        let output = format!("{GENERATED_ALIAS}/lib/hidd/{stub}.o");
        let arguments = compiler_arguments(
            &source,
            scope,
            dirs,
            source_root,
            relative_dir,
            invocation_line,
            true,
        )?;
        objects.push(LiteralObjectDecl {
            source,
            output,
            language: "C".into(),
            arguments,
            line: invocation_line + 1,
        });
    }
    Ok(SourceCompileGroupDecl {
        owner: owner.to_owned(),
        parent: Some("linklibs-hidd-stubs".into()),
        file: file.to_owned(),
        line: invocation_line + 1,
        archive_output: None,
        objects,
    })
}

fn ordinary_object(
    output: &str,
    source_relative: &Path,
    scope: &VarScope,
    dirs: &DirVars,
    source_root: &Path,
    relative_dir: &Path,
    rule_line: usize,
) -> Result<LiteralObjectDecl, String> {
    let source_path = source_alias(Path::new(""), &path_text(source_relative))?;
    safe_source_file(source_root, source_relative)?;
    let arguments = compiler_arguments(
        &source_path,
        scope,
        dirs,
        source_root,
        relative_dir,
        usize::MAX,
        false,
    )?;
    Ok(LiteralObjectDecl {
        source: source_path,
        output: output.to_owned(),
        language: "C".into(),
        arguments,
        line: rule_line + 1,
    })
}

fn compiler_arguments(
    source: &str,
    scope: &VarScope,
    dirs: &DirVars,
    source_root: &Path,
    relative_dir: &Path,
    line: usize,
    invocation_snapshot: bool,
) -> Result<Vec<String>, String> {
    let context = MakeExprContext::new(scope, dirs, line, source_root, relative_dir);
    let evaluate = |expression: &str| {
        evaluate_make_expr(expression, &context)
            .map_err(|error| format!("cannot resolve native `%compile_q` arguments: {error}"))
    };
    let compiler = dirs
        .expand("$(NATIVE_TARGET_CC)")
        .ok_or_else(|| "native TARGET_CC tool role was not explicitly admitted".to_owned())?;
    if compiler != "${CMAKE_C_COMPILER}" {
        return Err(format!(
            "native `%compile_q` TARGET_CC resolves to `{compiler}`, not the admitted CMake compiler role"
        ));
    }
    let sysroot = evaluate("$(strip $(TARGET_SYSROOT))")?;
    let mut arguments = Vec::new();
    if !sysroot.is_empty() {
        let expected = dirs
            .expand("$(AROS_DEVELOPER)")
            .ok_or_else(|| "configured Developer sysroot is unresolved".to_owned())?;
        if sysroot != format!("--sysroot={expected}") || !is_build_path(&expected) {
            return Err(format!(
                "native TARGET_SYSROOT `{sysroot}` is outside the admitted Developer path"
            ));
        }
        arguments.push(sysroot);
    }

    let quote = evaluate("$(strip $(CFLAGS_IQUOTE))")?;
    let quote_end = evaluate("$(strip $(CFLAGS_IQUOTE_END))")?;
    if quote != "-iquote" || !quote_end.is_empty() {
        return Err("native `%compile_q` requires exactly `CFLAGS_IQUOTE=-iquote` and an empty `CFLAGS_IQUOTE_END`".into());
    }

    let flag_line = if invocation_snapshot {
        line
    } else {
        usize::MAX
    };
    // Removing an outer `strip` wrapper for scoped flag variables preserves
    // the argument words; the final compile-flag parser normalizes whitespace
    // anyway. This also models a valid empty `$(strip $(USER_CPPFLAGS))`, for
    // which the shared Make evaluator otherwise sees an empty function name.
    let flag_lookup = |name: &str| {
        scope
            .raw_at(name, flag_line)
            .map(|raw| strip_argument(&raw).map_or_else(|| raw.clone(), str::to_owned))
    };
    let flag_lookup: &MakeVariableLookup<'_> = &flag_lookup;
    let flag_context = MakeExprContext::new(scope, dirs, flag_line, source_root, relative_dir)
        .with_lookup(flag_lookup);
    let source_dir = source.rsplit_once('/').map_or_else(
        || format!("{SOURCE_ALIAS}/"),
        |(directory, _)| format!("{directory}/"),
    );
    let build_cwd = make_working_directory(relative_dir)?;
    let include_dirs = [
        source_dir,
        build_cwd.clone(),
        source_directory(relative_dir)?,
        build_cwd,
    ];
    for include in include_dirs {
        arguments.push("-iquote".into());
        arguments.push(include);
    }

    let flags = evaluate_make_expr("$(strip $(CFLAGS) $(CPPFLAGS))", &flag_context)
        .map_err(|error| format!("cannot resolve native `%compile_q` CFLAGS/CPPFLAGS: {error}"))?;
    arguments.extend(parse_compile_flags(&flags, dirs, relative_dir)?);

    let source_relative = source
        .strip_prefix(&format!("{SOURCE_ALIAS}/"))
        .ok_or_else(|| "`%compile_q` source is outside AROS_SOURCE_DIR".to_owned())?;
    validate_source_tail(source_relative)?;
    arguments.push(format!("-D__SRCFILENAME__=\"{source_relative}\""));
    Ok(arguments)
}

fn role_mutation_issue(lines: &[&str]) -> Option<String> {
    let mut target_cc_bindings = 0usize;
    let mut target_sysroot_bindings = 0usize;
    let mut quote_bindings = 0usize;
    let mut quote_end_bindings = 0usize;
    for raw in lines {
        if raw.starts_with('\t') {
            continue;
        }
        let clean = strip_make_comment(raw).trim();
        if clean.is_empty() {
            continue;
        }
        let first = clean.split_whitespace().next().unwrap_or_default();
        if matches!(first, "include" | "-include" | "sinclude") {
            return Some("compile-capable source still has an unresolved Make include".into());
        }
        if clean.contains("$(eval") || clean.contains("${eval") || first == "eval" {
            return Some(
                "source contains Make `eval` that could mutate compiler roles or recipes".into(),
            );
        }
        if first == "define"
            || clean.starts_with("override define ")
            || clean.starts_with("export define ")
        {
            let name = clean
                .split_whitespace()
                .nth(1)
                .unwrap_or_default()
                .split(['=', ':'])
                .next()
                .unwrap_or_default();
            if matches!(
                name,
                "TARGET_CC" | "TARGET_SYSROOT" | "CFLAGS_IQUOTE" | "CFLAGS_IQUOTE_END"
            ) {
                return Some(format!("source defines compiler role `{name}` opaquely"));
            }
        }
        if first == "undefine"
            && clean.split_whitespace().nth(1).is_some_and(|name| {
                matches!(
                    name,
                    "TARGET_CC"
                        | "TARGET_SYSROOT"
                        | "CFLAGS_IQUOTE"
                        | "CFLAGS_IQUOTE_END"
                        | "NATIVE_TARGET_CC"
                )
            })
        {
            return Some("source undefines a compiler role or native compiler alias".into());
        }
        let Some((name, value, _)) = variable_assignment(clean) else {
            continue;
        };
        match name {
            "NATIVE_TARGET_CC" => {
                return Some("source locally rebinds the admitted native compiler alias".into());
            }
            "TARGET_CC" => {
                target_cc_bindings += 1;
                if value.trim() != "$(NATIVE_TARGET_CC)" {
                    return Some("source binds TARGET_CC away from `$(NATIVE_TARGET_CC)`".into());
                }
            }
            "TARGET_SYSROOT" => {
                target_sysroot_bindings += 1;
                if value.trim() != "--sysroot=$(AROS_DEVELOPER)" {
                    return Some(
                        "source binds TARGET_SYSROOT outside the configured Developer root".into(),
                    );
                }
            }
            "CFLAGS_IQUOTE" => {
                quote_bindings += 1;
                if value.trim() != "-iquote" {
                    return Some("source binds CFLAGS_IQUOTE away from `-iquote`".into());
                }
            }
            "CFLAGS_IQUOTE_END" => {
                quote_end_bindings += 1;
                if !value.trim().is_empty() {
                    return Some("source binds CFLAGS_IQUOTE_END to an unsupported value".into());
                }
            }
            _ => {}
        }
    }
    if target_cc_bindings != 1
        || target_sysroot_bindings != 1
        || quote_bindings != 1
        || quote_end_bindings != 1
    {
        return Some(
            "native compile roles need one explicit source configuration binding each".into(),
        );
    }
    None
}

fn local_template_macro_shadow(lines: &[&str]) -> Option<(usize, String)> {
    for (index, raw) in lines.iter().enumerate() {
        if raw.starts_with('\t') {
            continue;
        }
        let clean = strip_make_comment(raw).trim_start();
        let Some(rest) = clean.strip_prefix("%define") else {
            continue;
        };
        if !rest.chars().next().is_some_and(char::is_whitespace) {
            continue;
        }
        let name = rest.split_whitespace().next()?;
        if matches!(name, "compile_q" | "fileactionmsg" | "make_hidd_stubs") {
            return Some((index + 1, name.to_owned()));
        }
    }
    None
}

fn candidate_rejections(
    reason: &str,
    relative_dir: &Path,
    archives: &[&SourceArchiveDecl],
    hidd_invocations: &[crate::parser::Invocation],
    states: Option<&[ConditionalTruth]>,
) -> Vec<SourceCompileRejection> {
    let mut candidates = BTreeSet::<(String, usize)>::new();
    for archive in archives {
        candidates.insert((archive.owner.clone(), archive.line));
    }
    for invocation in hidd_invocations {
        if state_at(states, invocation.line) == ConditionalTruth::False {
            continue;
        }
        match parse_hidd_invocation(&invocation.args) {
            Ok(hidd) => {
                candidates.insert((format!("hidd-{hidd}-stubs"), invocation.line + 1));
            }
            Err(_) => {
                candidates.insert(("<unknown>".into(), invocation.line + 1));
            }
        }
    }
    if candidates.is_empty() {
        candidates.insert(("<unknown>".into(), 1));
    }
    candidates
        .into_iter()
        .map(|(owner, line)| rejection(&owner, relative_dir, line, reason))
        .collect()
}

fn parse_compile_flags(
    flags: &str,
    dirs: &DirVars,
    relative_dir: &Path,
) -> Result<Vec<String>, String> {
    let words = flags
        .split_whitespace()
        .map(str::to_owned)
        .collect::<Vec<_>>();
    if words.len() > 256 {
        return Err("native compile flag list exceeds the closed word limit".into());
    }
    let mut result = Vec::with_capacity(words.len());
    let mut index = 0usize;
    while index < words.len() {
        let word = &words[index];
        if matches!(word.as_str(), "-I" | "-iquote") {
            let value = words
                .get(index + 1)
                .ok_or_else(|| format!("compile option `{word}` has no directory"))?;
            result.push(word.clone());
            result.push(normalize_include_path(value, dirs, relative_dir)?);
            index += 2;
            continue;
        }
        if let Some(path) = word.strip_prefix("-I").filter(|path| !path.is_empty()) {
            result.push(format!(
                "-I{}",
                normalize_include_path(path, dirs, relative_dir)?
            ));
            index += 1;
            continue;
        }
        if word.starts_with('-') && safe_compile_flag(word, dirs)? {
            result.push(word.clone());
            index += 1;
            continue;
        }
        return Err(format!(
            "native compile flag `{word}` is outside the closed vocabulary"
        ));
    }
    Ok(result)
}

fn strip_argument(expression: &str) -> Option<&str> {
    let body = expression.trim().strip_prefix("$(")?.strip_suffix(')')?;
    let argument = body.strip_prefix("strip")?;
    argument
        .chars()
        .next()
        .is_some_and(char::is_whitespace)
        .then_some(argument.trim())
}

fn safe_compile_flag(word: &str, dirs: &DirVars) -> Result<bool, String> {
    if word.starts_with("--sysroot=") {
        let expected = dirs
            .expand("$(AROS_DEVELOPER)")
            .ok_or_else(|| "configured Developer sysroot is unresolved".to_owned())?;
        return Ok(word == format!("--sysroot={expected}") && is_build_path(&expected));
    }
    if let Some(path) = word.strip_prefix("-include=") {
        return Ok(is_configured_path(path));
    }
    if let Some(path) = word.strip_prefix("-include") {
        return Ok(!path.is_empty() && is_configured_path(path));
    }
    if let Some(value) = word.strip_prefix("-D").filter(|value| !value.is_empty()) {
        return Ok(safe_macro(value));
    }
    if let Some(value) = word.strip_prefix("-U").filter(|value| !value.is_empty()) {
        return Ok(safe_identifier(value));
    }
    if matches!(
        word,
        "-pipe"
            | "-pthread"
            | "-fPIC"
            | "-fpic"
            | "-fPIE"
            | "-fpie"
            | "-fno-pic"
            | "-fno-PIE"
            | "-fno-common"
            | "-fcommon"
            | "-fno-builtin"
            | "-fbuiltin"
            | "-fstrict-aliasing"
            | "-fno-strict-aliasing"
            | "-fomit-frame-pointer"
            | "-fno-omit-frame-pointer"
            | "-fstack-protector"
            | "-fstack-protector-strong"
            | "-fno-stack-protector"
            | "-g"
            | "-g0"
            | "-g1"
            | "-g2"
            | "-g3"
            | "-O0"
            | "-O1"
            | "-O2"
            | "-O3"
            | "-Os"
            | "-Og"
            | "-Oz"
            | "-Ofast"
            | "-Wall"
            | "-Werror"
    ) {
        return Ok(true);
    }
    if let Some(value) = word.strip_prefix("-W") {
        return Ok(!value.is_empty()
            && !matches!(value, "l" | "p")
            && !value.starts_with("l,")
            && !value.starts_with("p,")
            && word.len() <= 128
            && value
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || b"_-=,+".contains(&byte)));
    }
    if word.starts_with("-m") {
        return Ok(matches!(
            word,
            "-march=rv32imafc_zicsr_zifencei_zaamo_zalrsc" | "-mabi=ilp32f" | "-mcmodel=medany"
        ));
    }
    if let Some(value) = word.strip_prefix("-std=") {
        return Ok(matches!(
            value,
            "c89"
                | "c90"
                | "c99"
                | "c11"
                | "c17"
                | "c23"
                | "gnu89"
                | "gnu90"
                | "gnu99"
                | "gnu11"
                | "gnu17"
                | "gnu23"
        ));
    }
    Ok(false)
}

fn safe_macro(value: &str) -> bool {
    let (name, definition) = value.split_once('=').unwrap_or((value, ""));
    safe_identifier(name)
        && definition.len() <= 128
        && definition
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || b"_.,+/-".contains(&byte))
}

fn safe_identifier(value: &str) -> bool {
    let mut bytes = value.bytes();
    bytes
        .next()
        .is_some_and(|byte| byte.is_ascii_alphabetic() || byte == b'_')
        && bytes.all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
}

fn normalize_include_path(
    path: &str,
    dirs: &DirVars,
    relative_dir: &Path,
) -> Result<String, String> {
    if path == "." || path == "./" {
        return make_working_directory(relative_dir);
    }
    if path.starts_with("${AROS_SOURCE_DIR}") {
        return validated_rooted_path(path, SOURCE_ALIAS);
    }
    if path.starts_with("${AROS_BUILD_DIR}") {
        return validated_rooted_path(path, BUILD_ALIAS);
    }
    let _ = dirs;
    let value = path.strip_prefix("./").unwrap_or(path);
    let tail = safe_relative(value)?;
    Ok(format!(
        "{}/{}",
        make_working_directory(relative_dir)?,
        tail
    ))
}

fn object_source_relative(
    member: &str,
    scope: &VarScope,
    dirs: &DirVars,
    source_root: &Path,
    relative_dir: &Path,
    line: usize,
) -> Result<PathBuf, String> {
    let context = MakeExprContext::new(scope, dirs, line, source_root, relative_dir);
    let objdir = evaluate_make_expr("$(OBJDIR)", &context)
        .map_err(|error| format!("cannot resolve ordinary object OBJDIR: {error}"))?;
    let expected_objdir = object_directory(relative_dir)?;
    if objdir != expected_objdir {
        return Err(format!(
            "ordinary object rule OBJDIR `{objdir}` is not the configured local build CWD `{expected_objdir}`"
        ));
    }
    let prefix = format!("{objdir}/");
    let tail = member
        .strip_prefix(&prefix)
        .ok_or_else(|| "archive member is outside the local `OBJDIR/%.o` pattern".to_owned())?;
    let stem = tail
        .strip_suffix(".o")
        .ok_or_else(|| "archive member is not an object-file identity".to_owned())?;
    let safe_stem = safe_relative(stem)?;
    let mut source = relative_dir.to_path_buf();
    source.push(format!("{safe_stem}.c"));
    Ok(source)
}

fn find_default_pattern_rule(
    lines: &[&str],
    line_states: Option<&[ConditionalTruth]>,
) -> (Option<PatternRule>, Option<String>) {
    let mut candidates: Vec<PatternRule> = Vec::new();
    let mut active: Option<usize> = None;
    for (line, raw) in lines.iter().enumerate() {
        if let Some(index) = active {
            if let Some(recipe) = raw.strip_prefix('\t') {
                candidates[index]
                    .recipes
                    .push((recipe.trim().to_owned(), state_at(line_states, line)));
                continue;
            }
        }
        active = None;
        let clean = strip_make_comment(raw).trim();
        if clean.is_empty()
            || clean.starts_with('#')
            || clean.starts_with('%')
            || variable_assignment(clean).is_some()
        {
            continue;
        }
        let Some((lhs, rhs)) = clean.split_once(':') else {
            continue;
        };
        let lhs = lhs.trim();
        if !lhs.contains("OBJDIR") || !lhs.contains("%.o") {
            continue;
        }
        let double_colon = lhs.ends_with(':') || rhs.starts_with(':');
        let rhs = rhs.strip_prefix(':').unwrap_or(rhs).trim();
        let inline_recipe = rhs.split_once(';').map(|(prerequisites, recipe)| {
            (prerequisites.trim().to_owned(), recipe.trim().to_owned())
        });
        let (prerequisites, inline_recipe_text) = inline_recipe.as_ref().map_or_else(
            || (rhs.to_owned(), None),
            |(prerequisites, recipe)| (prerequisites.clone(), Some(recipe.clone())),
        );
        let (prerequisites, order_only) = match prerequisites.split_once('|') {
            Some((before, after)) => (before.trim().to_owned(), Some(after.trim().to_owned())),
            None => (prerequisites, None),
        };
        candidates.push(PatternRule {
            line,
            state: state_at(line_states, line),
            target: lhs.to_owned(),
            prerequisites,
            order_only,
            inline_recipe: inline_recipe_text,
            recipes: Vec::new(),
            valid: !double_colon,
        });
        active = Some(candidates.len() - 1);
    }
    if candidates.is_empty() {
        return (None, None);
    }
    if candidates.len() != 1 {
        return (
            None,
            Some("source has duplicate or competing `OBJDIR/%.o` pattern rules".into()),
        );
    }
    let rule = candidates.remove(0);
    if !rule.valid
        || rule.target != "$(OBJDIR)/%.o"
        || rule.prerequisites != "%.c"
        || rule.order_only.is_some()
        || rule.inline_recipe.is_some()
        || rule.recipes.len() != 1
        || rule.recipes[0].0 != "%compile_q"
        || rule.recipes[0].1 != ConditionalTruth::True
    {
        return (
            None,
            Some("ordinary object pattern must be exactly `$(OBJDIR)/%.o : %.c` with one unconditional `%compile_q` recipe".into()),
        );
    }
    (Some(rule), None)
}

fn parse_hidd_invocation(raw: &str) -> Result<String, String> {
    let fields = raw.split_whitespace().collect::<Vec<_>>();
    if fields.len() != 1 {
        return Err("`%make_hidd_stubs` accepts exactly one literal `hidd=` argument".into());
    }
    let (key, value) = fields[0]
        .split_once('=')
        .ok_or_else(|| "`%make_hidd_stubs` requires a literal `hidd=` argument".to_owned())?;
    if key != "hidd" || !safe_stem(value) {
        return Err("`%make_hidd_stubs` hidd name is unsafe or has unsupported arguments".into());
    }
    Ok(value.to_owned())
}

fn record_outputs(
    group: &SourceCompileGroupDecl,
    seen: &mut BTreeMap<String, (String, usize)>,
    rejections: &mut Vec<SourceCompileRejection>,
    relative_dir: &Path,
) -> bool {
    let mut unique = true;
    for object in &group.objects {
        if let Some((previous_owner, previous_line)) = seen.get(&object.output) {
            rejections.push(rejection(
                &group.owner,
                relative_dir,
                group.line,
                format!(
                    "compile output `{}` conflicts with `{previous_owner}` declared at line {previous_line}",
                    object.output
                ),
            ));
            unique = false;
        } else {
            seen.insert(object.output.clone(), (group.owner.clone(), group.line));
        }
    }
    unique
}

fn validate_template(template: &str) -> Result<(), String> {
    for expected in [FILEACTIONMSG, COMPILE_Q, HIDD_STUBS] {
        let name = expected[0]
            .split_whitespace()
            .nth(1)
            .ok_or_else(|| "internal template contract is malformed".to_owned())?;
        let actual = definition_lines(template, name)?;
        let expected = expected.to_vec();
        if actual != expected {
            return Err(format!(
                "`{name}` definition differs from the checked source semantics"
            ));
        }
    }
    Ok(())
}

fn definition_lines(template: &str, name: &str) -> Result<Vec<String>, String> {
    let prefix = format!("%define {name} ");
    let lines = template.lines().collect::<Vec<_>>();
    let starts = lines
        .iter()
        .enumerate()
        .filter_map(|(index, line)| line.trim_start().starts_with(&prefix).then_some(index))
        .collect::<Vec<_>>();
    if starts.len() != 1 {
        return Err(format!("`{name}` must have one source definition"));
    }
    let start = starts[0];
    let end = lines[start + 1..]
        .iter()
        .position(|line| line.trim() == "%end")
        .map(|offset| start + 1 + offset)
        .ok_or_else(|| format!("`{name}` definition has no `%end`"))?;
    Ok(lines[start..=end]
        .iter()
        .map(|line| line.trim().to_owned())
        .filter(|line| !line.is_empty())
        .collect())
}

fn read_make_template(source_root: &Path) -> Result<String, String> {
    let path = safe_source_file(source_root, Path::new("config/make.tmpl"))?;
    fs::read_to_string(path)
        .map_err(|error| format!("cannot read source `config/make.tmpl`: {error}"))
}

fn source_file(source_root: &Path, relative_dir: &Path) -> Result<String, String> {
    if relative_dir.is_absolute()
        || relative_dir
            .components()
            .any(|component| !matches!(component, Component::Normal(_)))
    {
        return Err("source compile mmakefile directory is not source-relative".into());
    }
    let source_root = source_root
        .canonicalize()
        .map_err(|error| format!("source root cannot be canonicalized: {error}"))?;
    if !source_root.is_dir() {
        return Err("source root is not a directory".into());
    }
    let mut relative = relative_dir.to_path_buf();
    relative.push("mmakefile.src");
    safe_source_file(&source_root, &relative)?;
    Ok(path_text(&relative))
}

fn safe_source_file(source_root: &Path, relative: &Path) -> Result<PathBuf, String> {
    let canonical_root = source_root
        .canonicalize()
        .map_err(|error| format!("selected source root cannot be canonicalized: {error}"))?;
    if !canonical_root.is_dir() {
        return Err("selected source root is not a directory".into());
    }
    let mut current = canonical_root.clone();
    let components = relative.components().collect::<Vec<_>>();
    if components.is_empty() {
        return Err("source path is empty".into());
    }
    for (index, component) in components.iter().enumerate() {
        let Component::Normal(name) = component else {
            return Err("source path contains a non-normal component".into());
        };
        current.push(name);
        let metadata = fs::symlink_metadata(&current).map_err(|error| {
            format!(
                "source path `{}` is unavailable: {error}",
                current.display()
            )
        })?;
        if metadata.file_type().is_symlink() {
            return Err(format!(
                "source path `{}` contains a symlink",
                current.display()
            ));
        }
        if index + 1 == components.len() {
            if !metadata.is_file() {
                return Err("source input is not a regular file".into());
            }
        } else if !metadata.is_dir() {
            return Err("source path crosses a non-directory component".into());
        }
    }
    let resolved = current
        .canonicalize()
        .map_err(|error| format!("source path cannot be canonicalized: {error}"))?;
    if !resolved.starts_with(&canonical_root) || !resolved.is_file() {
        return Err("source file is outside the selected source root or not regular".into());
    }
    Ok(resolved)
}

fn source_alias(relative_dir: &Path, tail: &str) -> Result<String, String> {
    let tail = safe_relative(tail)?;
    if relative_dir.as_os_str().is_empty() {
        Ok(format!("{SOURCE_ALIAS}/{tail}"))
    } else {
        let directory = safe_relative(&path_text(relative_dir))?;
        Ok(format!("{SOURCE_ALIAS}/{directory}/{tail}"))
    }
}

fn source_directory(relative_dir: &Path) -> Result<String, String> {
    if relative_dir.as_os_str().is_empty() {
        Ok(SOURCE_ALIAS.into())
    } else {
        Ok(format!(
            "{SOURCE_ALIAS}/{}",
            safe_relative(&path_text(relative_dir))?
        ))
    }
}

fn object_directory(relative_dir: &Path) -> Result<String, String> {
    if relative_dir.as_os_str().is_empty() {
        Ok(GENERATED_ALIAS.into())
    } else {
        Ok(format!(
            "{GENERATED_ALIAS}/{}",
            safe_relative(&path_text(relative_dir))?
        ))
    }
}

fn make_working_directory(relative_dir: &Path) -> Result<String, String> {
    if relative_dir.as_os_str().is_empty() {
        Ok(BUILD_ALIAS.into())
    } else {
        Ok(format!(
            "{BUILD_ALIAS}/{}",
            safe_relative(&path_text(relative_dir))?
        ))
    }
}

fn safe_relative(value: &str) -> Result<String, String> {
    if value.is_empty() || value.starts_with('/') || value.contains('\\') {
        return Err("path is not a non-empty slash-separated relative path".into());
    }
    let path = Path::new(value);
    if path.components().any(|component| {
        !matches!(component, Component::Normal(_))
            || !safe_component(&component.as_os_str().to_string_lossy())
    }) {
        return Err("path contains an unsafe or non-normal component".into());
    }
    Ok(path_text(path))
}

fn safe_component(value: &str) -> bool {
    !value.is_empty()
        && value != "."
        && value != ".."
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || b"._+-".contains(&byte))
}

fn safe_stem(value: &str) -> bool {
    !value.is_empty()
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || b"._+-".contains(&byte))
        && !value.contains("..")
}

fn validate_source_tail(value: &str) -> Result<(), String> {
    safe_relative(value).map(|_| ())
}

fn validated_rooted_path(value: &str, root: &str) -> Result<String, String> {
    let tail = value
        .strip_prefix(root)
        .ok_or_else(|| "include path has an unsupported configured root".to_owned())?;
    if tail.is_empty() {
        return Ok(value.to_owned());
    }
    let tail = tail
        .strip_prefix('/')
        .ok_or_else(|| "rooted include path is malformed".to_owned())?;
    Ok(format!("{root}/{}", safe_relative(tail)?))
}

fn is_configured_path(value: &str) -> bool {
    validated_rooted_path(value, SOURCE_ALIAS).is_ok()
        || validated_rooted_path(value, BUILD_ALIAS).is_ok()
}

fn is_build_path(value: &str) -> bool {
    value == BUILD_ALIAS
        || value
            .strip_prefix(&format!("{BUILD_ALIAS}/"))
            .is_some_and(|tail| safe_relative(tail).is_ok())
}

fn state_at(states: Option<&[ConditionalTruth]>, line: usize) -> ConditionalTruth {
    states
        .and_then(|states| states.get(line).copied())
        .unwrap_or(ConditionalTruth::Unknown)
}

fn rejection(
    owner: &str,
    relative_dir: &Path,
    line: usize,
    reason: impl Into<String>,
) -> SourceCompileRejection {
    let mut path = relative_dir.to_path_buf();
    path.push("mmakefile.src");
    SourceCompileRejection {
        owner: owner.to_owned(),
        file: path_text(&path),
        line,
        reason: reason.into(),
    }
}

fn looks_compile_relevant(content: &str, archives: &[SourceArchiveDecl]) -> bool {
    content.contains("%make_hidd_stubs")
        || content.contains("$(OBJDIR)/%.o")
        || archives
            .iter()
            .any(|archive| matches!(archive.members, ArchiveMembers::Exact(_)))
}

fn path_text(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

fn source_alias_tail(source: &str) -> Result<&str, String> {
    source
        .strip_prefix(&format!("{SOURCE_ALIAS}/"))
        .ok_or_else(|| "source path is outside AROS_SOURCE_DIR".into())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::make_vars::collect_vars_impl;
    use crate::parser::join_continuations;
    use crate::parser::TargetContext;
    use crate::source_archive_rules::collect_from_snapshot as collect_archives;
    use tempfile::TempDir;

    const REL: &str = "external/openurl/libopenurl";
    const SOURCE_CONFIG: &str = "TARGET_CC = $(NATIVE_TARGET_CC)\n\
TARGET_SYSROOT = --sysroot=$(AROS_DEVELOPER)\n\
TARGET_ISA_CFLAGS := -march=rv32imafc_zicsr_zifencei_zaamo_zalrsc -mabi=ilp32f -mcmodel=medany\n\
TARGET_CFLAGS := -O2 -Wall -Werror -Wno-pointer-sign -Wno-parentheses\n\
TARGET_CPPFLAGS :=\n\
CFLAGS := $(strip $(TARGET_ISA_CFLAGS) $(TARGET_CFLAGS))\n\
CPPFLAGS := $(strip $(TARGET_CPPFLAGS))\n\
CFLAGS_IQUOTE := -iquote\n\
CFLAGS_IQUOTE_END :=\n\
OBJDIR := $(GENDIR)/$(CURDIR)\n";

    struct Fixture {
        tree: TempDir,
        root: PathBuf,
        relative_dir: PathBuf,
        dirs: DirVars,
        scope: VarScope,
        states: Vec<ConditionalTruth>,
    }

    fn expected_template() -> String {
        [FILEACTIONMSG, COMPILE_Q, HIDD_STUBS]
            .into_iter()
            .flat_map(|definition| definition.iter().copied())
            .collect::<Vec<_>>()
            .join("\n")
    }

    fn fixture(relative_dir: &str, content: &str, source_files: &[&str]) -> Fixture {
        let tree = tempfile::tempdir().unwrap();
        let root = tree.path().to_path_buf();
        fs::create_dir_all(root.join("config")).unwrap();
        fs::write(
            root.join("config/make.cfg.in"),
            "AROSDIR := $(TARGETDIR)/SYS\nAROS_DIR_DEVELOPER := Developer\nAROS_DEVELOPER := $(AROSDIR)/$(AROS_DIR_DEVELOPER)\nAROS_DIR_LIB := lib\nAROS_LIB := $(AROS_DEVELOPER)/$(AROS_DIR_LIB)\n",
        )
        .unwrap();
        fs::write(root.join("config/make.tmpl"), expected_template()).unwrap();
        let relative_dir = PathBuf::from(relative_dir);
        fs::create_dir_all(root.join(&relative_dir)).unwrap();
        fs::write(root.join(&relative_dir).join("mmakefile.src"), content).unwrap();
        for source in source_files {
            let path = root.join(&relative_dir).join(source);
            fs::create_dir_all(path.parent().unwrap()).unwrap();
            fs::write(path, "/* compile fixture */\n").unwrap();
        }
        let mut dirs = DirVars::load(&root);
        dirs.bind_native_target_tool_roles();
        let (scope, states) = collect_vars_impl(content, Some(&TargetContext::default()));
        Fixture {
            tree,
            root,
            relative_dir,
            dirs,
            scope,
            states,
        }
    }

    fn archive(fixture: &Fixture, member_names: &[&str]) -> SourceArchiveDecl {
        let file = format!("{}/mmakefile.src", fixture.relative_dir.display());
        let members = member_names
            .iter()
            .map(|member| {
                format!(
                    "{GENERATED_ALIAS}/{}/{member}.o",
                    fixture.relative_dir.display()
                )
            })
            .collect();
        SourceArchiveDecl {
            owner: "linklibs-openurl-quick".into(),
            file,
            line: 20,
            owner_line: 16,
            output: "${AROS_BUILD_DIR}/SYS/Developer/lib/libopenurl.a".into(),
            members: ArchiveMembers::Exact(members),
        }
    }

    fn ordinary_source(members: &[&str], flags: &str) -> String {
        format!(
            "{SOURCE_CONFIG}CPPFLAGS := {flags}\n\
FILES := {}\n\
OBJS := $(foreach f,$(FILES),$(OBJDIR)/$(f).o)\n\
ARCHIVE := $(AROS_LIB)/libopenurl.a\n\
#MM\n\
linklibs-openurl-quick : $(ARCHIVE)\n\
$(ARCHIVE) : $(OBJS)\n\
\t%mklib_q from=$^\n\
$(OBJDIR)/%.o : %.c\n\
\t%compile_q\n",
            members.join(" ")
        )
    }

    fn hidd_source(stubs: &str, invocation: &str) -> String {
        format!("{SOURCE_CONFIG}MODNAME := serial\nSTUBS := {stubs}\n{invocation}\n")
    }

    #[test]
    fn ordinary_pattern_projects_only_exact_archive_members_in_make_cwd_order() {
        let content = ordinary_source(&["autoinit-aros"], "-I.");
        let fixture = fixture(REL, &content, &["autoinit-aros.c"]);
        let archive = archive(&fixture, &["autoinit-aros"]);
        let (groups, rejected) = collect_from_snapshot(
            &content,
            &fixture.scope,
            &fixture.dirs,
            &fixture.root,
            &fixture.relative_dir,
            Some(&fixture.states),
            &[archive],
        );
        assert!(rejected.is_empty(), "{rejected:#?}");
        assert_eq!(groups.len(), 1);
        let group = &groups[0];
        assert_eq!(group.owner, "linklibs-openurl-quick");
        assert_eq!(group.parent, None);
        assert_eq!(
            group.archive_output.as_deref(),
            Some("${AROS_BUILD_DIR}/SYS/Developer/lib/libopenurl.a")
        );
        assert_eq!(group.objects.len(), 1);
        let object = &group.objects[0];
        assert_eq!(
            object.source,
            "${AROS_SOURCE_DIR}/external/openurl/libopenurl/autoinit-aros.c"
        );
        assert_eq!(
            object.output,
            "${AROS_BUILD_DIR}/gen/external/openurl/libopenurl/autoinit-aros.o"
        );
        assert_eq!(
            object.arguments[0],
            "--sysroot=${AROS_BUILD_DIR}/SYS/Developer"
        );
        assert_eq!(
            object.arguments[1..9],
            [
                "-iquote",
                "${AROS_SOURCE_DIR}/external/openurl/libopenurl/",
                "-iquote",
                "${AROS_BUILD_DIR}/external/openurl/libopenurl",
                "-iquote",
                "${AROS_SOURCE_DIR}/external/openurl/libopenurl",
                "-iquote",
                "${AROS_BUILD_DIR}/external/openurl/libopenurl",
            ]
        );
        assert_eq!(
            &object.arguments[9..17],
            [
                "-march=rv32imafc_zicsr_zifencei_zaamo_zalrsc",
                "-mabi=ilp32f",
                "-mcmodel=medany",
                "-O2",
                "-Wall",
                "-Werror",
                "-Wno-pointer-sign",
                "-Wno-parentheses",
            ]
        );
        assert_eq!(
            object.arguments[17],
            "-I${AROS_BUILD_DIR}/external/openurl/libopenurl"
        );
        assert_eq!(
            object.arguments.last().unwrap(),
            "-D__SRCFILENAME__=\"external/openurl/libopenurl/autoinit-aros.c\""
        );

        // Independently derive TOP/CURDIR from MakeExprContext rather than
        // reusing the path helper under test.
        let make_context = MakeExprContext::new(
            &fixture.scope,
            &fixture.dirs,
            0,
            &fixture.root,
            &fixture.relative_dir,
        );
        let make_top = evaluate_make_expr("$(TOP)", &make_context).unwrap();
        let make_curdir = evaluate_make_expr("$(CURDIR)", &make_context).unwrap();
        assert_eq!(
            format!("{make_top}/{make_curdir}"),
            "${AROS_BUILD_DIR}/external/openurl/libopenurl"
        );
        assert_ne!(
            format!("{make_top}/{make_curdir}"),
            object.source.rsplit_once('/').unwrap().0
        );
        assert!(fixture.tree.path().is_dir());
    }

    #[test]
    fn hidd_macro_projects_source_owner_parent_and_invocation_flags() {
        let content = hidd_source("serial_stubs", "%make_hidd_stubs hidd=serial");
        let fixture = fixture("workbench/hidds/serial", &content, &["serial_stubs.c"]);
        let (groups, rejected) = collect_from_snapshot(
            &content,
            &fixture.scope,
            &fixture.dirs,
            &fixture.root,
            &fixture.relative_dir,
            Some(&fixture.states),
            &[],
        );
        assert!(rejected.is_empty(), "{rejected:#?}");
        assert_eq!(groups.len(), 1);
        assert_eq!(groups[0].owner, "hidd-serial-stubs");
        assert_eq!(groups[0].parent.as_deref(), Some("linklibs-hidd-stubs"));
        assert_eq!(groups[0].archive_output, None);
        assert_eq!(groups[0].objects.len(), 1);
        assert_eq!(
            groups[0].objects[0].source,
            "${AROS_SOURCE_DIR}/workbench/hidds/serial/serial_stubs.c"
        );
        assert_eq!(
            groups[0].objects[0].output,
            "${AROS_BUILD_DIR}/gen/lib/hidd/serial_stubs.o"
        );
    }

    #[test]
    fn hidd_multi_source_shared_prerequisite_is_rejected() {
        let content = hidd_source("first_stubs second_stubs", "%make_hidd_stubs hidd=serial");
        let fixture = fixture(
            "workbench/hidds/serial",
            &content,
            &["first_stubs.c", "second_stubs.c"],
        );
        let (groups, rejected) = collect_from_snapshot(
            &content,
            &fixture.scope,
            &fixture.dirs,
            &fixture.root,
            &fixture.relative_dir,
            Some(&fixture.states),
            &[],
        );
        assert!(groups.is_empty());
        assert_eq!(rejected.len(), 1);
        assert!(rejected[0].reason.contains("first prerequisite"));
    }

    #[test]
    fn changed_template_and_compile_role_rebindings_fail_closed() {
        let content = hidd_source("serial_stubs", "%make_hidd_stubs hidd=serial");
        let template_fixture = fixture("workbench/hidds/serial", &content, &["serial_stubs.c"]);
        let template_path = template_fixture.root.join("config/make.tmpl");
        fs::write(
            &template_path,
            expected_template().replace("-D__SRCFILENAME__", "-DUNSAFE_SRCFILENAME"),
        )
        .unwrap();
        let (groups, rejected) = collect_from_snapshot(
            &content,
            &template_fixture.scope,
            &template_fixture.dirs,
            &template_fixture.root,
            &template_fixture.relative_dir,
            Some(&template_fixture.states),
            &[],
        );
        assert!(groups.is_empty());
        assert!(rejected[0].reason.contains("template"));
        assert_eq!(rejected[0].owner, "hidd-serial-stubs");
        assert_eq!(rejected[0].line, 13);

        let changed = format!(
            "{SOURCE_CONFIG}TARGET_CC := wrapper\nMODNAME := serial\nSTUBS := serial_stubs\n%make_hidd_stubs hidd=serial\n"
        );
        let changed_fixture = fixture("workbench/hidds/serial", &changed, &["serial_stubs.c"]);
        let (groups, rejected) = collect_from_snapshot(
            &changed,
            &changed_fixture.scope,
            &changed_fixture.dirs,
            &changed_fixture.root,
            &changed_fixture.relative_dir,
            Some(&changed_fixture.states),
            &[],
        );
        assert!(groups.is_empty());
        assert!(rejected[0].reason.contains("TARGET_CC"));
        assert_eq!(rejected[0].owner, "hidd-serial-stubs");

        let shadowed = format!(
            "%define compile_q cmd=unsafe\n{}",
            hidd_source("serial_stubs", "%make_hidd_stubs hidd=serial")
        );
        let shadowed_fixture = fixture("workbench/hidds/serial", &shadowed, &["serial_stubs.c"]);
        let (groups, rejected) = collect_from_snapshot(
            &shadowed,
            &shadowed_fixture.scope,
            &shadowed_fixture.dirs,
            &shadowed_fixture.root,
            &shadowed_fixture.relative_dir,
            Some(&shadowed_fixture.states),
            &[],
        );
        assert!(groups.is_empty());
        assert_eq!(rejected[0].owner, "hidd-serial-stubs");
        assert!(rejected[0]
            .reason
            .contains("locally redefines `%compile_q`"));
    }

    #[test]
    fn ambiguous_conditional_unsafe_and_extra_pattern_recipes_are_refused() {
        let ambiguous = hidd_source("serial_stubs", "%make_hidd_stubs hidd=serial cflags=-O0");
        let ambiguous_fixture = fixture("workbench/hidds/serial", &ambiguous, &["serial_stubs.c"]);
        let (groups, rejected) = collect_from_snapshot(
            &ambiguous,
            &ambiguous_fixture.scope,
            &ambiguous_fixture.dirs,
            &ambiguous_fixture.root,
            &ambiguous_fixture.relative_dir,
            Some(&ambiguous_fixture.states),
            &[],
        );
        assert!(groups.is_empty());
        assert!(rejected[0].reason.contains("exactly one literal"));

        let conditional = format!(
            "{SOURCE_CONFIG}MODNAME := serial\nSTUBS := serial_stubs\nifeq ($(UNKNOWN_PROFILE),yes)\n%make_hidd_stubs hidd=serial\nendif\n"
        );
        let conditional_fixture =
            fixture("workbench/hidds/serial", &conditional, &["serial_stubs.c"]);
        let (groups, rejected) = collect_from_snapshot(
            &conditional,
            &conditional_fixture.scope,
            &conditional_fixture.dirs,
            &conditional_fixture.root,
            &conditional_fixture.relative_dir,
            Some(&conditional_fixture.states),
            &[],
        );
        assert!(groups.is_empty());
        assert!(rejected[0].reason.contains("unknown line state"));

        let content = ordinary_source(&["autoinit-aros"], "-I../escape");
        let unsafe_path_fixture = fixture(REL, &content, &["autoinit-aros.c"]);
        let (groups, rejected) = collect_from_snapshot(
            &content,
            &unsafe_path_fixture.scope,
            &unsafe_path_fixture.dirs,
            &unsafe_path_fixture.root,
            &unsafe_path_fixture.relative_dir,
            Some(&unsafe_path_fixture.states),
            &[archive(&unsafe_path_fixture, &["autoinit-aros"])],
        );
        assert!(groups.is_empty());
        assert!(rejected[0].reason.contains("path"));

        let forged_root = ordinary_source(
            &["autoinit-aros"],
            "-include${AROS_BUILD_DIR}outside/header.h",
        );
        let forged_root_fixture = fixture(REL, &forged_root, &["autoinit-aros.c"]);
        let (groups, rejected) = collect_from_snapshot(
            &forged_root,
            &forged_root_fixture.scope,
            &forged_root_fixture.dirs,
            &forged_root_fixture.root,
            &forged_root_fixture.relative_dir,
            Some(&forged_root_fixture.states),
            &[archive(&forged_root_fixture, &["autoinit-aros"])],
        );
        assert!(groups.is_empty());
        assert!(rejected[0].reason.contains("outside the closed vocabulary"));

        for flag in ["-fplugin=payload", "-march=armv7"] {
            let unsupported = ordinary_source(&["autoinit-aros"], flag);
            let unsupported_fixture = fixture(REL, &unsupported, &["autoinit-aros.c"]);
            let (groups, rejected) = collect_from_snapshot(
                &unsupported,
                &unsupported_fixture.scope,
                &unsupported_fixture.dirs,
                &unsupported_fixture.root,
                &unsupported_fixture.relative_dir,
                Some(&unsupported_fixture.states),
                &[archive(&unsupported_fixture, &["autoinit-aros"])],
            );
            assert!(groups.is_empty(), "unexpectedly accepted {flag}");
            assert!(rejected[0].reason.contains("closed vocabulary"));
        }

        let extra_recipe = ordinary_source(&["autoinit-aros"], "")
            .replace("\t%compile_q\n", "\t%compile_q\n\t@echo another command\n");
        let extra_recipe_fixture = fixture(REL, &extra_recipe, &["autoinit-aros.c"]);
        let (groups, rejected) = collect_from_snapshot(
            &extra_recipe,
            &extra_recipe_fixture.scope,
            &extra_recipe_fixture.dirs,
            &extra_recipe_fixture.root,
            &extra_recipe_fixture.relative_dir,
            Some(&extra_recipe_fixture.states),
            &[archive(&extra_recipe_fixture, &["autoinit-aros"])],
        );
        assert!(groups.is_empty());
        assert!(rejected[0]
            .reason
            .contains("one unconditional `%compile_q`"));
    }

    #[test]
    #[ignore = "requires AROS_P4_SOURCE_ROOT to point at the selected, source-bound P4 checkout"]
    fn actual_p4_six_hidd_and_openurl_projection_probe() {
        use aros_common::{native_build_contract::load_bound_native_build_contract, TargetProfile};
        use std::path::PathBuf;

        let root =
            PathBuf::from(std::env::var_os("AROS_P4_SOURCE_ROOT").expect("set P4 source root"));
        let profiles = TargetProfile::load_from_file(&root.join("aros-targets.toml")).unwrap();
        let profile = profiles
            .iter()
            .find(|profile| profile.name == "esp32p4-d1001")
            .unwrap();
        let binding = load_bound_native_build_contract(
            &root,
            Path::new(profile.native_build_contract.as_deref().unwrap()),
            profile,
        )
        .unwrap();
        let selectors = profile.transpiler.as_ref().unwrap();
        let target = TargetContext {
            cpu: Some(binding.contract.abi.source_cpu),
            platform: Some(profile.platform.clone()),
            family: Some(selectors.family.clone()),
            variant: Some(selectors.variant.clone()),
            toolchain: Some(selectors.toolchain.clone()),
            cpu32: Some(selectors.cpu32.clone()),
            use_mmu: Some(if selectors.use_mmu { "1" } else { "0" }.into()),
            float_abi: profile.float_abi.clone(),
            make_variables: binding.contract.make_variables,
            make_include_bindings: binding.contract.make_include_bindings,
            ..TargetContext::default()
        };
        let mut dirs = DirVars::load(&root);
        dirs.bind_native_target_tool_roles();
        for relative in [
            "workbench/hidds/serial",
            "workbench/hidds/parallel",
            "workbench/hidds/i2c/stubs",
            "workbench/devs/USB/stack/stubs",
            "workbench/devs/USB/classes/MassStorage",
            "workbench/devs/USB/classes/HID",
        ] {
            let relative = Path::new(relative);
            let content = fs::read_to_string(root.join(relative).join("mmakefile.src")).unwrap();
            let scan = crate::local_make_includes::inline_native_make_configuration(
                &content,
                &root,
                &relative.join("mmakefile.src"),
                crate::local_make_includes::LocalMakeIncludeLimits::default(),
                &target.make_include_bindings,
            );
            assert!(
                scan.issues.is_empty(),
                "{}: {:#?}",
                relative.display(),
                scan.issues
            );
            let joined = join_continuations(&scan.expanded);
            let (scope, states) = collect_vars_impl(&joined, Some(&target));
            let (groups, rejected) =
                collect_from_snapshot(&joined, &scope, &dirs, &root, relative, Some(&states), &[]);
            assert!(rejected.is_empty(), "{}: {rejected:#?}", relative.display());
            assert_eq!(groups.len(), 1, "{}", relative.display());
            assert_eq!(groups[0].objects.len(), 1, "{}", relative.display());
            assert_eq!(groups[0].parent.as_deref(), Some("linklibs-hidd-stubs"));
        }

        let relative = Path::new("external/openurl/libopenurl");
        let content = fs::read_to_string(root.join(relative).join("mmakefile.src")).unwrap();
        let scan = crate::local_make_includes::inline_native_make_configuration(
            &content,
            &root,
            &relative.join("mmakefile.src"),
            crate::local_make_includes::LocalMakeIncludeLimits::default(),
            &target.make_include_bindings,
        );
        assert!(scan.issues.is_empty(), "{:#?}", scan.issues);
        let joined = join_continuations(&scan.expanded);
        let (scope, states) = collect_vars_impl(&joined, Some(&target));
        let (archives, archive_rejections) =
            collect_archives(&joined, &scope, &dirs, &root, relative, Some(&states));
        assert!(archive_rejections.is_empty(), "{archive_rejections:#?}");
        assert_eq!(archives.len(), 1, "{archives:#?}");
        let (groups, rejected) = collect_from_snapshot(
            &joined,
            &scope,
            &dirs,
            &root,
            relative,
            Some(&states),
            &archives,
        );
        assert!(rejected.is_empty(), "{rejected:#?}");
        assert_eq!(groups.len(), 1, "{groups:#?}");
        assert_eq!(groups[0].objects.len(), 1);
        assert_eq!(
            groups[0].objects[0].source,
            "${AROS_SOURCE_DIR}/external/openurl/libopenurl/autoinit-aros.c"
        );
    }
}
