[package]
name = "aros-collect"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "aros-collect"
path = "src/main.rs"

[dependencies]
aros-common.workspace = true
anyhow.workspace = true
clap.workspace = true

[dev-dependencies]
tempfile.workspace = true
