//! Reviewed generated CLI-contract snapshot inputs.
//!
//! This test-only registry keeps the public command-family inventory beside
//! the generated documents without expanding the production frontend module.

pub const CLI_CONTRACT_SECTIONS: &[(&str, &str)] = &[
    (
        "board",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../docs-site/src/content/docs/reference/cli-contract/board.md"
        )),
    ),
    (
        "build",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../docs-site/src/content/docs/reference/cli-contract/build.md"
        )),
    ),
    (
        "build-tools",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../docs-site/src/content/docs/reference/cli-contract/build-tools.md"
        )),
    ),
    (
        "ccache",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../docs-site/src/content/docs/reference/cli-contract/ccache.md"
        )),
    ),
    (
        "clean",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../docs-site/src/content/docs/reference/cli-contract/clean.md"
        )),
    ),
    (
        "completions",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../docs-site/src/content/docs/reference/cli-contract/completions.md"
        )),
    ),
    (
        "golden",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../docs-site/src/content/docs/reference/cli-contract/golden.md"
        )),
    ),
    (
        "host-compiler",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../docs-site/src/content/docs/reference/cli-contract/host-compiler.md"
        )),
    ),
    (
        "info",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../docs-site/src/content/docs/reference/cli-contract/info.md"
        )),
    ),
    (
        "install",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../docs-site/src/content/docs/reference/cli-contract/install.md"
        )),
    ),
    (
        "setup",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../docs-site/src/content/docs/reference/cli-contract/setup.md"
        )),
    ),
    (
        "source",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../docs-site/src/content/docs/reference/cli-contract/source.md"
        )),
    ),
    (
        "test",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../docs-site/src/content/docs/reference/cli-contract/test.md"
        )),
    ),
    (
        "toolchain",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../docs-site/src/content/docs/reference/cli-contract/toolchain.md"
        )),
    ),
];
