//! Source-resolved unsigned ESP-IDF partition-table construction.
//!
//! Numeric geometry and the exact CSV identity are caller supplied; no board
//! defaults or device operations are inferred. MD5 is a container checksum,
//! not authentication. Independent binary decoding belongs to `aros-verify`.

use std::collections::HashSet;

use md5::{Digest, Md5};
use serde::Serialize;

use crate::{sha256_bytes, Sha256Digest};

mod native;
mod source;
pub use native::{
    encode_bound_native_partition_table, NativePartitionArtifact, NativePartitionBinding,
};
pub use source::{parse_esp_partition_source, EspPartitionSource};

const TABLE_BYTES: usize = 0xc00;
const SECTOR_BYTES: u64 = 0x1000;
const RECORD_BYTES: usize = 32;

/// Exact resolved source partition; no board names or ranges are inferred.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct EspPartition {
    pub name: String,
    pub kind: u8,
    pub subtype: u8,
    pub offset: u32,
    pub size: u32,
    pub flags: u32,
}

/// Deterministically generated bytes and the source/geometry that produced them.
/// This is not a native build-set receipt or permission to flash a device.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EspPartitionArtifact {
    pub bytes: Vec<u8>,
    pub sha256: Sha256Digest,
    pub source: EspPartitionSource,
    pub table_offset: u32,
    pub flash_bytes: u64,
}

/// Encode the closed explicit-geometry CSV subset as an unsigned 3 KiB table.
///
/// The source is measured and re-parsed at this boundary; a mutable previously
/// resolved list cannot bypass validation. Exactly one MD5 record precedes
/// erased padding, with at least one full end-marker record remaining.
///
/// # Errors
/// Rejects a changed source identity, unsupported CSV syntax, unsafe geometry,
/// and any table that cannot retain its checksum and erased end marker.
pub fn encode_esp_partition_source(
    bytes: &[u8],
    expected_source_sha256: &Sha256Digest,
    table_offset: u32,
    flash_bytes: u64,
) -> Result<EspPartitionArtifact, String> {
    if bytes.len() > 64 * 1024 {
        return Err("source partition CSV exceeds its byte budget".into());
    }
    if &sha256_bytes(bytes) != expected_source_sha256 {
        return Err("partition source SHA-256 differs from the bound source input".into());
    }
    let source = parse_esp_partition_source(bytes, table_offset, flash_bytes)?;
    // The parser's bound already guarantees this. Keep the format capacity
    // explicit so a future parser extension cannot truncate the end marker.
    if (source.partitions.len() + 2) * RECORD_BYTES > TABLE_BYTES {
        return Err("partition table cannot retain its checksum and end marker".into());
    }
    let mut output = Vec::with_capacity(TABLE_BYTES);
    for partition in &source.partitions {
        output.extend_from_slice(&[0xaa, 0x50, partition.kind, partition.subtype]);
        output.extend_from_slice(&partition.offset.to_le_bytes());
        output.extend_from_slice(&partition.size.to_le_bytes());
        let mut label = [0; 16];
        label[..partition.name.len()].copy_from_slice(partition.name.as_bytes());
        output.extend_from_slice(&label);
        output.extend_from_slice(&partition.flags.to_le_bytes());
    }
    let digest = Md5::digest(&output);
    output.extend_from_slice(&[0xeb, 0xeb]);
    output.extend_from_slice(&[0xff; 14]);
    output.extend_from_slice(&digest);
    output.resize(TABLE_BYTES, 0xff);
    Ok(EspPartitionArtifact {
        sha256: sha256_bytes(&output),
        bytes: output,
        source,
        table_offset,
        flash_bytes,
    })
}

fn validate_ranges(
    partitions: &[EspPartition],
    table_start: u64,
    table_end: u64,
    flash_bytes: u64,
) -> Result<(), String> {
    let mut names = HashSet::new();
    for (index, partition) in partitions.iter().enumerate() {
        let start = u64::from(partition.offset);
        let end = start + u64::from(partition.size);
        let alignment = if partition.kind == 0 {
            0x10000
        } else {
            SECTOR_BYTES
        };
        if !names.insert(&partition.name) {
            return Err("duplicate partition label".into());
        }
        if partition.flags & !3 != 0 {
            return Err("unsupported partition flags".into());
        }
        if partition.size == 0 || start % alignment != 0 || end > flash_bytes {
            return Err("partition range is empty, unaligned or exceeds flash capacity".into());
        }
        if partition.kind == 0 && !partition.size.is_multiple_of(SECTOR_BYTES as u32) {
            return Err("unsigned app partition size is not sector aligned".into());
        }
        if start < table_end && table_start < end {
            return Err("partition overlaps the reserved table sector".into());
        }
        if start < table_end {
            return Err("partition lies before the reserved table sector ends".into());
        }
        for previous in &partitions[..index] {
            let previous_start = u64::from(previous.offset);
            let previous_end = previous_start + u64::from(previous.size);
            if start < previous_end && previous_start < end {
                return Err("partition ranges overlap".into());
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fmt::Write as _;

    #[test]
    fn deterministic_records_checksum_padding_and_bound_source() {
        let csv =
            b"first,data,nvs,0x9000,0x3000,\nabcdefghijklmnop,app,ota_0,0x10000,1M,encrypted\n";
        let hash = sha256_bytes(csv);
        let artifact = encode_esp_partition_source(csv, &hash, 0x8000, 2 << 20).unwrap();
        assert_eq!(
            artifact,
            encode_esp_partition_source(csv, &hash, 0x8000, 2 << 20).unwrap()
        );
        assert_eq!(artifact.bytes.len(), TABLE_BYTES);
        assert_eq!(artifact.sha256, sha256_bytes(&artifact.bytes));
        assert_eq!(artifact.source.sha256, hash);
        assert_eq!(&artifact.bytes[..4], &[0xaa, 0x50, 1, 2]);
        assert_eq!(&artifact.bytes[4..8], &0x9000_u32.to_le_bytes());
        assert_eq!(&artifact.bytes[12..28], b"first\0\0\0\0\0\0\0\0\0\0\0");
        assert_eq!(&artifact.bytes[44..60], b"abcdefghijklmnop");
        assert_eq!(&artifact.bytes[60..64], &1_u32.to_le_bytes());
        assert_eq!(&artifact.bytes[64..66], &[0xeb, 0xeb]);
        assert_eq!(&artifact.bytes[66..80], &[0xff; 14]);
        assert_eq!(
            &artifact.bytes[80..96],
            &Md5::digest(&artifact.bytes[..64])[..]
        );
        assert!(artifact.bytes[96..].iter().all(|byte| *byte == 0xff));
        assert!(
            encode_esp_partition_source(csv, &sha256_bytes(b"changed"), 0x8000, 2 << 20)
                .unwrap_err()
                .contains("SHA-256")
        );
        assert!(encode_esp_partition_source(csv, &hash, 0x8001, 2 << 20).is_err());
        assert!(encode_esp_partition_source(csv, &hash, 0x8000, 1 << 20).is_err());
    }

    #[test]
    fn maximum_table_keeps_checksum_and_one_erased_end_record() {
        let mut csv = String::new();
        for index in 0..94 {
            writeln!(csv, "p{index},0x40,0,0x{:x},4K,", 0x9000 + index * 0x1000).unwrap();
        }
        let artifact = encode_esp_partition_source(
            csv.as_bytes(),
            &sha256_bytes(csv.as_bytes()),
            0x8000,
            1 << 20,
        )
        .unwrap();
        assert_eq!(&artifact.bytes[94 * 32..94 * 32 + 2], &[0xeb, 0xeb]);
        assert_eq!(&artifact.bytes[95 * 32..], &[0xff; 32]);
        csv.push_str("extra,0x40,0,0x67000,4K,\n");
        assert!(encode_esp_partition_source(
            csv.as_bytes(),
            &sha256_bytes(csv.as_bytes()),
            0x8000,
            1 << 20
        )
        .unwrap_err()
        .contains("record budget"));
    }
}
