//! Parse AROS module configurations and generate deterministic sources.

mod interfaces;
mod linklib;
mod transaction;
mod varargs;

use aros_common::{
    canonical_source_file, casefold_path_key, measure_regular_file, render_diagnostics,
    requested_diagnostic_format, write_stdout, Diagnostic, DiagnosticCode, DiagnosticContext,
    DiagnosticFormat, DiagnosticSet, DiagnosticStage, LogFormat, LogLevel, Logger,
    ObservabilityPolicy, PortableOutputName, PublicationFailureClass, RecoveryOutcome,
    SourceLocation,
};
use clap::{error::ErrorKind as ClapErrorKind, Parser};
use rayon::prelude::*;
use std::ffi::OsString;
use std::fmt::Write as _;
use std::io::ErrorKind;
use std::io::Write as IoWrite;
use std::path::{Path, PathBuf};
use std::process::ExitCode;
use walkdir::WalkDir;

use transaction::FileTransaction;

fn read_stable_source(path: &Path) -> std::io::Result<String> {
    let (_, bytes) = measure_regular_file(path)?.ok_or_else(|| {
        std::io::Error::new(
            ErrorKind::NotFound,
            format!("source file '{}' does not exist", path.display()),
        )
    })?;
    Ok(match String::from_utf8(bytes) {
        Ok(text) => text,
        Err(error) => error.into_bytes().into_iter().map(char::from).collect(),
    })
}

pub(crate) const GENERATED_BANNER: &str = concat!(
    "/* Auto-generated by AROS genmodule v",
    env!("CARGO_PKG_VERSION"),
    " */"
);

const POLICY: ObservabilityPolicy = ObservabilityPolicy {
    log_schema: "aros-genmodule-log-v1",
    component: "genmodule",
    include_invocation: false,
    observability_code: DiagnosticCode::GenmoduleObservability,
    observability_stage: DiagnosticStage::Observability,
    internal_code: DiagnosticCode::GenmoduleInternal,
    internal_stage: DiagnosticStage::Internal,
    hint: "pass --log-file PATH or set AROS_GENMODULE_LOG_FILE, or disable logging",
};

/// Writes generated output only when its bytes have actually changed.
///
/// Configure-time SDK generation runs before every CMake regeneration. Keeping
/// the timestamp of identical headers prevents all of their consumers from
/// being rebuilt even though neither the source nor the generated ABI changed.
#[cfg(test)]
pub(crate) fn write_if_changed(
    path: impl AsRef<Path>,
    contents: impl AsRef<[u8]>,
) -> std::io::Result<bool> {
    let mut transaction = FileTransaction::for_output_root(path.as_ref())?;
    let changed = transaction.stage_write(path.as_ref(), contents.as_ref())?;
    transaction.commit()?;
    Ok(changed)
}

#[derive(Parser, Debug)]
#[command(
    name = "aros-genmodule",
    author = "AROS Development Team & Fabian Schmieder (@metaneutrons)",
    version,
    about = "Pure Rust replacement for genmodule (.conf parser & SDK proto generator)"
)]
struct Args {
    /// Stable human or machine-readable diagnostics.
    #[arg(long, value_enum, default_value_t = DiagnosticFormat::Human, env = "AROS_GENMODULE_DIAGNOSTIC_FORMAT")]
    diagnostic_format: DiagnosticFormat,

    /// Local logging threshold; logging is disabled by default.
    #[arg(long, value_enum, default_value_t = LogLevel::Off, env = "AROS_GENMODULE_LOG_LEVEL")]
    log_level: LogLevel,

    /// Local log encoding.
    #[arg(long, value_enum, default_value_t = LogFormat::Human, env = "AROS_GENMODULE_LOG_FORMAT")]
    log_format: LogFormat,

    /// Explicit local log destination.
    #[arg(long, env = "AROS_GENMODULE_LOG_FILE")]
    log_file: Option<PathBuf>,

    /// Source directory to scan for .conf files
    #[arg(short, long, default_value = ".")]
    scan_dir: PathBuf,

    /// Target SDK include directory (e.g. build/pc-x86_64/SDK/include).
    ///
    /// This and every optional output must share a writable build root. The
    /// generator journals the complete run at their deepest common parent.
    #[arg(short, long)]
    output_inc: PathBuf,

    /// Architecture directories that apply to the configured target, e.g.
    /// `x86_64-pc all-pc x86_64-all all-native`.
    ///
    /// Without this every `arch/<cpu>-<platform>/` subtree is scanned, so a
    /// module that exists for several architectures under the same name (audio,
    /// trackdisk, bwfm) overwrites the target's own generated headers.
    #[arg(long, value_delimiter = ' ')]
    arch_dirs: Vec<String>,

    /// Root for per-module generated headers (e.g. build/pc-x86_64/gen).
    ///
    /// `<mod>_libdefs.h` is module-private: it carries LIBBASE, LIBBASETYPE and
    /// the module's `cdefprivate` block. Twenty-six .conf stems occur more than
    /// once in the tree, so a flat SDK layout makes them overwrite each other.
    /// The reference build emits this file into the module's own build
    /// directory; mirroring that keeps them apart.
    #[arg(long)]
    output_gen: Option<PathBuf>,

    /// Where to write the list of library bases this tree declares, one per
    /// line, sorted.
    ///
    /// A relocatable AROS module leaves its library bases undefined on purpose:
    /// the loader sets them. `ninja symbol-audit` needs to know which names
    /// those are, or its count conflates "the loader will fill this in" with
    /// "nothing provides this". SysBase alone accounted for 611 of 9268
    /// references.
    #[arg(long)]
    output_libbases: Option<PathBuf>,

    /// Root for the module link library sources (e.g. build/pc-x86_64/linklib).
    ///
    /// One directory per module, holding one C file per stack-call stub plus
    /// the autoinit and getlibbase files. These are what makes a cross-library
    /// call resolve: without them a consumer carries the call as a dangling
    /// external, and because every link here is `ld.lld -r` nothing complains.
    /// `ninja symbol-audit` is what measures the difference.
    #[arg(long)]
    output_linklib: Option<PathBuf>,
}

#[derive(Debug, Default)]
struct ConfModuleOptions(u8);

impl ConfModuleOptions {
    const EXPLICIT_LIB_BASE: u8 = 1 << 0;
    const AUTO_INIT: u8 = 1 << 1;
    const NO_RESIDENT: u8 = 1 << 2;
    const NO_INCLUDES: u8 = 1 << 3;

    const fn contains(&self, flag: u8) -> bool {
        self.0 & flag != 0
    }

    const fn insert(&mut self, flag: u8) {
        self.0 |= flag;
    }
}

#[derive(Debug, Default)]
struct ConfModule {
    name: String,
    /// `basename` from the config, or the module name with its first letter
    /// capitalised (tools/genmodule/config.c:1333).
    ///
    /// This, not the module name, is what every generated symbol is named
    /// after: `GM_UNIQUENAME` expands to `<basename>_ ## n`
    /// (tools/genmodule/writeinclibdefs.c:82), so `kernel_init.c` referring to
    /// GM_UNIQUENAME(FuncTable) means Kernel_FuncTable. Using the module name
    /// here produced `kernel_FuncTable`, which was self-consistent only as long
    /// as nothing else generated the definition.
    base_name: String,
    lib_base: String,
    lib_base_type: String,
    /// `libbasetypeextern` if the config states one; the type is otherwise
    /// derived from the module type by extern_base_type().
    explicit_base_type_extern: Option<String>,
    options: ConfModuleOptions,
    cdef: String,
    /// Contents of `##begin cdefprivate`. The reference generator writes these
    /// lines verbatim into `<mod>_libdefs.h`; they are how a module pulls in the
    /// header that defines its library base struct, so omitting them leaves
    /// `struct <X>Base` incomplete at every use site.
    cdef_private: String,
    functions: Vec<varargs::Function>,
    /// `version <major>.<minor>` from the config section.
    major_version: u32,
    minor_version: u32,
    /// `residentpri`, used for RESIDENTPRI and to derive RESIDENTFLAGS.
    resident_pri: i32,
    /// `date` from the config section. MOD_DATE_STRING is consumed by real code
    /// (rom/exec/taggedopenlibrary.c), so it must be present. Left empty when
    /// the .conf does not state one, rather than stamped with the build date,
    /// which would make output non-reproducible.
    date: String,
    /// Module type (`library`, `device`, `resource`, `hidd`, `handler`, ...).
    /// Not part of the .conf; taken from the sibling mmakefile.src.
    mod_type: String,
    /// Fields the module init code needs to reach through the library base.
    sysbase_field: Option<String>,
    oopbase_field: Option<String>,
    seglist_field: Option<String>,
    /// Interfaces declared in this .conf.
    interfaces: Vec<interfaces::Interface>,
    /// `includename` from the config section; the SDK header base name, which
    /// defaults to the module name.
    include_name: String,
    /// Directory of the .conf, relative to the scan root. Used to give the
    /// module-private headers a unique location.
    rel_dir: PathBuf,
    /// `forcebase` entries. The autoinit file imports __aros_getbase_ for each,
    /// which is what makes a parent open those libraries.
    force_bases: Vec<String>,
    /// `##begin startup` lines, written verbatim ahead of the autoinit banner.
    startup_lines: String,
}

/// Whether a `.conf` below `arch/` applies to the configured target.
///
/// Paths outside `arch/` always apply. Inside it, the directory right below
/// `arch/` must be one of the architecture directories the caller listed; with
/// no list given nothing is filtered, which keeps the tool usable standalone.
fn arch_dir_applies(rel: &Path, arch_dirs: &[String]) -> bool {
    if arch_dirs.is_empty() {
        return true;
    }
    // The UnixIO HIDD is hosted-only code, but its public interface is also
    // included by the native PC and Sam440 serial/parallel drivers. MetaMake's
    // universal includes-generate target publishes it for every architecture;
    // retain that exact API config without admitting unrelated foreign module
    // namespaces that could overwrite the active architecture's headers.
    if rel.starts_with("arch/all-unix/hidd/unixio") {
        return true;
    }
    let mut parts = rel.components().map(|c| c.as_os_str().to_string_lossy());
    if parts.next().as_deref() != Some("arch") {
        return true;
    }
    parts
        .next()
        .is_none_or(|dir| arch_dirs.iter().any(|a| *a == dir))
}

/// Whether the module publishes `proto/`, `clib/` and `defines/` headers.
///
/// Mirrors `tools/genmodule/config.c:711`. Modules without a public API do not
/// export headers, which is also what keeps same-named `.conf` files in
/// different subsystems from overwriting each other's SDK headers.
fn exports_public_headers(module: &ConfModule) -> bool {
    let has_funcs = !module.functions.is_empty();
    let has_cdef = !module.cdef.trim().is_empty();
    match module.mod_type.as_str() {
        "library" | "resource" => true,
        "handler" | "mcc" | "mui" | "mcp" | "usbclass" | "btclass" => has_funcs || has_cdef,
        // A device only exports if it has an API or a non-standard base type.
        "device" => has_funcs || has_cdef || extern_base_type(module) != "struct Device *",
        // class/gadget/image/datatype/hidd need a function list; so does an
        // undescribed module, so one the build description does not cover
        // cannot claim the SDK namespace.
        _ => has_funcs,
    }
}

/// The library base pointer type as seen from *outside* the module.
///
/// Per `tools/genmodule/config.c:1375` this follows the module type, not
/// `libbasetype`: that one is the module's private view. `acpica.conf` declares
/// `libbasetype struct ACPICABase` but is a library, so consumers of
/// `<proto/acpica.h>` must see `struct Library *` -- otherwise their own
/// `struct Library *ACPICABase` collides with the declaration.
///
/// An explicit `libbasetypeextern` always wins.
fn extern_base_type(module: &ConfModule) -> String {
    if let Some(t) = &module.explicit_base_type_extern {
        return format!("{t} *");
    }
    match module.mod_type.as_str() {
        "device" => "struct Device *".to_owned(),
        // APTR is already a pointer; the reference stores it without a star.
        "handler" | "resource" => "APTR ".to_owned(),
        // library, class, mui, mcp, mcc, gadget, image, datatype, usbclass,
        // btclass, hidd -- and anything the build description does not name.
        _ => "struct Library *".to_owned(),
    }
}

/// Splits a config line into key and value at the first run of whitespace.
///
/// Config sections use either spaces or tabs as the separator; 46 `.conf` files
/// in the tree use a tab, so matching on `"key "` silently drops their values
/// and the generated header falls back to defaults.
fn conf_key_value(line: &str) -> Option<(&str, &str)> {
    let line = line.trim();
    let idx = line.find(char::is_whitespace)?;
    let (k, v) = line.split_at(idx);
    let v = v.trim();
    if k.is_empty() || v.is_empty() {
        return None;
    }
    Some((k, v))
}

/// The exact `modname`/`modtype` invocation associated with one `.conf`.
///
/// `genmodule` receives both values on its command line. They cannot in
/// general be reconstructed from the config file stem: Wanderer's private
/// `icon.conf`, for example, is invoked as `Icon mui`, whereas icon.library is
/// invoked as `icon library`.
#[derive(Clone, Debug, Eq, PartialEq)]
struct ModuleDeclaration {
    name: String,
    mod_type: String,
    /// A `confoverride=` declaration reads its API from another config and
    /// applies this file afterwards. The broad scanner has to model the same
    /// pair or it emits a source-local libdefs header with no function list.
    base_config: Option<PathBuf>,
}

fn module_macro_value(block: &str, key: &str) -> Option<String> {
    block
        .split_whitespace()
        .find_map(|token| token.strip_prefix(key))
        .map(|value| value.trim_matches(['"', '\'']).to_owned())
}

fn resolve_make_config_path(
    value: &str,
    mmake_dir: &Path,
    root: &Path,
) -> std::io::Result<Option<PathBuf>> {
    let value = value.trim_matches(['"', '\'']);
    if value.contains("$(") && !value.starts_with("$(SRCDIR)/") {
        return Ok(None);
    }
    if let Some(relative) = value.strip_prefix("$(SRCDIR)/") {
        if relative.contains("$(") {
            // The generator intentionally does not evaluate arbitrary Make
            // variables. An unresolved declaration cannot prove a source path
            // and therefore cannot match a scanned configuration.
            return Ok(None);
        }
        return canonical_source_file(root, Path::new(relative)).map(Some);
    }
    let candidate = mmake_dir.join(value);
    let absolute = if candidate.is_absolute() {
        candidate
    } else {
        std::env::current_dir()?.join(candidate)
    };
    canonical_source_file(root, &absolute).map(Some)
}

/// Reads every genmodule invocation associated with one `.conf` from its
/// sibling mmakefile.src.
///
/// A config is not necessarily a one-to-one module identity. Network drivers
/// use one config for normal and debug modules, while HPET names this file as a
/// `confoverride=` over the shared clocksource config. Returning one preferred
/// declaration silently left the other private header stale.
fn read_module_declarations(
    conf_path: &Path,
    stem: &str,
    root: &Path,
) -> std::io::Result<Vec<ModuleDeclaration>> {
    let Some(mmake_dir) = conf_path.parent() else {
        return Ok(Vec::new());
    };
    let canonical_conf = canonical_source_file(root, conf_path)?;
    let mmakefile = mmake_dir.join("mmakefile.src");
    let content = match read_stable_source(&mmakefile) {
        Ok(content) => content,
        Err(error) if error.kind() == ErrorKind::NotFound => return Ok(Vec::new()),
        Err(error) => return Err(error),
    };
    // Directives span continuation lines, so flatten before matching.
    let flat = content.replace("\\\n", " ");
    let mut fallback_type: Option<String> = None;
    let mut declarations = Vec::new();
    for block in flat.split("%build_module").skip(1) {
        // The next macro begins with '%'; values of interest are all in this
        // one declaration, so never let a later build_module donate its args.
        let head = block.split('%').next().unwrap_or(block);
        let name = module_macro_value(head, "modname=");
        let mod_type = module_macro_value(head, "modtype=");
        let conffile = module_macro_value(head, "conffile=");
        let confoverride = module_macro_value(head, "confoverride=");
        if fallback_type.is_none() {
            fallback_type.clone_from(&mod_type);
        }

        let resolved_config = conffile
            .as_deref()
            .map(|value| resolve_make_config_path(value, mmake_dir, root))
            .transpose()?
            .flatten();
        let resolved_override = confoverride
            .as_deref()
            .map(|value| resolve_make_config_path(value, mmake_dir, root))
            .transpose()?
            .flatten();
        let matches_explicit_config = resolved_config.as_ref() == Some(&canonical_conf);
        let matches_default_config = conffile.is_none()
            && name
                .as_deref()
                .is_some_and(|module_name| module_name == stem);
        let matches_override = resolved_override.as_ref() == Some(&canonical_conf);
        if matches_explicit_config || matches_default_config || matches_override {
            if let (Some(name), Some(mod_type)) = (name, mod_type) {
                let base_config = matches_override.then_some(resolved_config).flatten();
                declarations.push(ModuleDeclaration {
                    name,
                    mod_type,
                    base_config,
                });
            }
        }
    }
    if declarations.is_empty() {
        if let Some(mod_type) = fallback_type {
            declarations.push(ModuleDeclaration {
                name: stem.to_owned(),
                mod_type,
                base_config: None,
            });
        }
    }
    declarations.sort_by(|left, right| {
        left.name
            .cmp(&right.name)
            .then_with(|| left.mod_type.cmp(&right.mod_type))
            .then_with(|| left.base_config.cmp(&right.base_config))
    });
    declarations.dedup();
    Ok(declarations)
}

/// Suffix and separator used to build the module's run-time name.
fn mod_name_string(module: &ConfModule) -> String {
    let suffix = if module.mod_type.is_empty() {
        "library"
    } else {
        module.mod_type.as_str()
    };
    // Handlers are named `<name>-handler`, everything else `<name>.<type>`.
    let sep = if suffix == "handler" { '-' } else { '.' };
    format!("{}{}{}", module.name, sep, suffix)
}

/// The basename used by all public genmodule headers.
///
/// `includename` defaults to the command-line module name in the reference
/// generator.  It is deliberately not normalised: `Icon` and `icon` are
/// distinct header paths on a case-sensitive build host.
fn public_include_name(module: &ConfModule) -> &str {
    if module.include_name.is_empty() {
        &module.name
    } else {
        &module.include_name
    }
}

/// Turns a public header basename into the reference's include-guard token.
///
/// `config.c` uppercases the name and maps every non-alphanumeric byte to an
/// underscore.  Header paths themselves retain the original spelling.
fn header_guard_name(name: &str) -> String {
    name.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() {
                ch.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect()
}

/// RESIDENTFLAGS, following the thresholds in writeinclibdefs.c.
fn resident_flags(module: &ConfModule) -> String {
    let mut flags: Vec<&str> = Vec::new();
    if module.resident_pri >= 105 {
        flags.push("RTF_SINGLETASK");
    } else if module.resident_pri >= -60 {
        flags.push("RTF_COLDSTART");
    } else if module.resident_pri < -120 {
        flags.push("RTF_AFTERDOS");
    }
    if module.options.contains(ConfModuleOptions::AUTO_INIT) {
        flags.push("RTF_AUTOINIT");
    }
    if flags.is_empty() {
        "0".to_owned()
    } else {
        flags.join("|")
    }
}

/// The number of jump-table vectors a module's base needs, following
/// `tools/genmodule/writeinclibdefs.c:20`.
///
/// This is the *highest LVO*, not the number of functions. A `.skip N` line in
/// the function list reserves N vectors without declaring a function, so a list
/// of 59 functions with 12 reserved LVOs occupies 71 slots. `FUNCTIONS_COUNT` is
/// what sizes the allocation -- the generated start code computes
/// `vecsize = FUNCTIONS_COUNT * LIB_VECTSIZE` (`writestart.c:1055`), and a
/// hand-written base allocator does the same -- while `MakeFunctions` walks the
/// function table to its `-1` terminator, which covers every reserved LVO.
/// Counting functions therefore under-allocates by exactly the reserved vectors,
/// and `MakeFunctions` writes below the allocation.
///
/// That was not hypothetical: kernel.resource has 59 functions and 12 reserved
/// LVOs, so its base was allocated 0x60 bytes short, and `MakeFunctions` wrote
/// its lowest 12 vectors over the ROM MemHeader that `krnCreateROMHeader` had
/// just linked into `SysBase->MemList`. `FindMem` then walked into the wreckage.
/// OPEN-POINTS 27g. 48 conf files in the tree use `.skip`.
///
/// The reference takes the last entry of a list it built in LVO order; taking
/// the maximum is the same value there and does not depend on that ordering.
/// An empty list falls back to `firstlvo - 1`, as the reference does.
fn functions_count(module: &ConfModule) -> u32 {
    module
        .functions
        .iter()
        .map(|f| f.lvo)
        .max()
        .unwrap_or_else(|| {
            varargs::first_lvo(
                &module.mod_type,
                module.options.contains(ConfModuleOptions::NO_RESIDENT),
            )
            .saturating_sub(1)
        })
}

/// The reference's default basename: the module name with its first letter
/// capitalised (`tools/genmodule/config.c:1334`).
///
/// This is what makes `LIBBASE` usable inside the module. A library function's
/// last parameter is the typed base, named after the basename -- for layers
/// that is `struct LayersBase *LayersBase`. `LIBBASE` expands to that name, so
/// inside a function it binds to the typed parameter and shadows the
/// `struct Library *` the proto header declares. Lowercasing the first letter
/// breaks the match, and every `LIBBASE->field` access then resolves against
/// `struct Library` instead.
fn default_basename(module_name: &str) -> String {
    let mut chars = module_name.chars();
    chars.next().map_or_else(String::new, |first| {
        first.to_uppercase().collect::<String>() + chars.as_str()
    })
}

fn parse_conf_variant(
    path: &Path,
    root: &Path,
    declaration: Option<&ModuleDeclaration>,
) -> std::io::Result<Option<ConfModule>> {
    let override_content = read_stable_source(path)?;
    let content =
        if let Some(base_config) = declaration.and_then(|value| value.base_config.as_ref()) {
            let mut base = read_stable_source(base_config)?;
            base.push('\n');
            base.push_str(&override_content);
            base
        } else {
            override_content
        };
    let Some(stem) = path.file_stem() else {
        return Ok(None);
    };
    let stem = stem.to_string_lossy().to_string();
    let module_name =
        declaration.map_or_else(|| stem.clone(), |declaration| declaration.name.clone());

    let mut module = ConfModule {
        name: module_name.clone(),
        base_name: default_basename(&module_name),
        lib_base: format!("{}Base", default_basename(&module_name)),
        // Left empty on purpose: the default depends on libbasetypeextern,
        // which may be read later in the config section. Resolved below.
        lib_base_type: String::new(),
        mod_type: declaration.map_or_else(String::new, |declaration| declaration.mod_type.clone()),
        rel_dir: path
            .parent()
            .and_then(|d| d.strip_prefix(root).ok())
            .map_or_else(PathBuf::new, Path::to_path_buf),
        interfaces: interfaces::parse_interfaces(&content),
        ..ConfModule::default()
    };

    // Vector numbering starts below the module's own functions; the standard
    // Open/Close/Expunge vectors occupy the slots before it. Initialised on
    // entering the function list, because the config section that may override
    // the starting point with `options noresident` is read first.
    let mut lvo = 0u32;
    // Running `.version` value; see the branch below.
    let mut pending_version: Option<u32> = None;
    let mut lvo_ready = false;
    let mut section = "";
    // `##begin interface` and `##begin class` nest their own config and
    // methodlist sections; reading those as the module's would let an
    // interface's keys overwrite the module's version, basename and so on.
    let mut nesting = 0usize;
    for line in content.lines() {
        let trimmed = line.trim();
        let directive = trimmed.strip_prefix("##").map(str::trim);
        if directive.is_some_and(|value| {
            value.starts_with("begin interface") || value.starts_with("begin class")
        }) {
            nesting += 1;
            continue;
        }
        if directive.is_some_and(|value| {
            value.starts_with("end interface") || value.starts_with("end class")
        }) {
            nesting = nesting.saturating_sub(1);
            continue;
        }
        if nesting > 0 {
            // Interfaces are parsed separately by the interfaces module.
            continue;
        }
        if directive == Some("begin config") {
            section = "config";
        } else if directive == Some("end config") {
            section = "";
        } else if directive == Some("begin cdef") {
            section = "cdef";
        } else if directive == Some("end cdef") {
            section = "";
        } else if directive == Some("begin startup") {
            section = "startup";
        } else if directive == Some("end startup") {
            section = "";
        } else if directive == Some("begin cdefprivate") {
            section = "cdefprivate";
        } else if directive == Some("end cdefprivate") {
            section = "";
        } else if matches!(
            directive,
            Some("begin functionlist" | "begin cfunctionlist")
        ) {
            section = "functions";
            if !lvo_ready {
                lvo = varargs::first_lvo(
                    &module.mod_type,
                    module.options.contains(ConfModuleOptions::NO_RESIDENT),
                );
                lvo_ready = true;
            }
        } else if matches!(directive, Some("end functionlist" | "end cfunctionlist")) {
            section = "";
        } else if section == "config" {
            let Some((key, val)) = conf_key_value(trimmed) else {
                continue;
            };
            match key {
                "forcebase" => module
                    .force_bases
                    .extend(val.split_whitespace().map(str::to_owned)),
                // The reference derives libbase from basename and lets an
                // explicit `libbase` line override it, in either order
                // (tools/genmodule/config.c:1336).
                "basename" => {
                    module.base_name = val.to_string();
                    if !module
                        .options
                        .contains(ConfModuleOptions::EXPLICIT_LIB_BASE)
                    {
                        module.lib_base = format!("{val}Base");
                    }
                }
                "libbase" => {
                    module.lib_base = val.to_string();
                    module.options.insert(ConfModuleOptions::EXPLICIT_LIB_BASE);
                }
                "libbasetypeextern" => {
                    module.explicit_base_type_extern = Some(val.to_string());
                }
                "libbasetype" => module.lib_base_type = val.to_string(),
                "includename" => module.include_name = val.to_string(),
                "date" => module.date = val.to_string(),
                "version" => {
                    let mut it = val.split('.');
                    if let Some(maj) = it.next().and_then(|x| x.trim().parse::<u32>().ok()) {
                        module.major_version = maj;
                        module.minor_version = it
                            .next()
                            .and_then(|x| x.trim().parse::<u32>().ok())
                            .unwrap_or(0);
                    }
                }
                "residentpri" => {
                    if let Ok(v) = val.parse::<i32>() {
                        module.resident_pri = v;
                    }
                }
                "options" => {
                    for opt in val.split([',', ' ']) {
                        match opt.trim() {
                            "autoinit" => module.options.insert(ConfModuleOptions::AUTO_INIT),
                            "noresident" => {
                                module.options.insert(ConfModuleOptions::NO_RESIDENT);
                            }
                            "noincludes" => {
                                module.options.insert(ConfModuleOptions::NO_INCLUDES);
                            }
                            _ => {}
                        }
                    }
                }
                "sysbase_field" => module.sysbase_field = Some(val.to_string()),
                "oopbase_field" => module.oopbase_field = Some(val.to_string()),
                "seglist_field" => module.seglist_field = Some(val.to_string()),
                _ => {}
            }
        } else if section == "cdef" {
            module.cdef.push_str(line);
            module.cdef.push('\n');
        } else if section == "startup" {
            module.startup_lines.push_str(line);
            module.startup_lines.push('\n');
        } else if section == "cdefprivate" {
            module.cdef_private.push_str(line);
            module.cdef_private.push('\n');
        } else if section == "functions" {
            let code_line = trimmed
                .find('#')
                .map_or(trimmed, |hash_pos| trimmed[..hash_pos].trim());

            // A blank line or `.skip n` advances the vector counter without
            // producing an entry, exactly as the reference parser does. A
            // comment line does not: 867 of them sit inside function lists, and
            // counting them would shift every vector that follows.
            let is_comment = trimmed.starts_with('#');
            if code_line.is_empty() && !is_comment {
                lvo = lvo.saturating_add(1);
            } else if let Some(rest) = code_line.strip_prefix(".skip") {
                if let Ok(n) = rest.split_whitespace().next().unwrap_or("").parse::<u32>() {
                    lvo = lvo.saturating_add(n);
                }
            }

            // `.private` and `.novararg` modify the preceding declaration.
            if code_line == ".private" {
                if let Some(f) = module.functions.last_mut() {
                    f.private = true;
                }
            } else if code_line == ".novararg" {
                if let Some(f) = module.functions.last_mut() {
                    f.novararg = true;
                }
            } else if let Some(rest) = code_line.strip_prefix(".version") {
                // Marks the version a caller of the *following* functions has
                // to open, not of the preceding one: config.c:1811 says so and
                // :1919 applies the running value to each new declaration.
                // writestubs.c turns it into AROS_LIBREQ.
                if let Ok(v) = rest.trim().parse::<u32>() {
                    pending_version = Some(v);
                }
            } else if let Some(rest) = code_line.strip_prefix(".alias") {
                let alias = rest.trim();
                if !alias.is_empty() {
                    if let Some(f) = module.functions.last_mut() {
                        f.aliases.push(alias.to_owned());
                    }
                }
            } else if !code_line.is_empty()
                && !code_line.starts_with('.')
                && !code_line.starts_with('#')
            {
                if let Some(mut f) = varargs::parse_function_line(code_line) {
                    f.lvo = lvo;
                    f.declared_version = pending_version;
                    lvo = lvo.saturating_add(1);
                    // The four standard library vectors are supplied by the
                    // module skeleton, not declared in the public header.
                    let is_standard_vector = matches!(
                        f.name.as_str(),
                        "open"
                            | "close"
                            | "expunge"
                            | "extFunc"
                            | "OpenLib"
                            | "CloseLib"
                            | "ExpungeLib"
                            | "ExtFuncLib"
                    );
                    if !is_standard_vector {
                        module.functions.push(f);
                    }
                }
            }
        }
    }

    // `libbasetype` is the module's private view of its base. The reference
    // takes an explicit declaration first, falls back to libbasetypeextern
    // (config.c:1344), and writes `struct Library` when neither is given
    // (writeinclibdefs.c:13). It is never derived from the module name.
    if module.lib_base_type.is_empty() {
        module.lib_base_type = module
            .explicit_base_type_extern
            .clone()
            .unwrap_or_else(|| "struct Library".to_owned());
    }
    // config.c:1413-1416 defaults `includename` to the command-line module
    // name. Preserve its spelling: header paths are case-sensitive on some
    // supported host filesystems, while case-insensitive hosts are handled by
    // the collision barrier below.
    if module.include_name.is_empty() {
        module.include_name = module.name.clone();
    }

    validate_module_output_names(&module)?;
    Ok(Some(module))
}

fn validate_module_output_names(module: &ConfModule) -> std::io::Result<()> {
    if !module.rel_dir.as_os_str().is_empty() {
        casefold_path_key(&module.rel_dir)?;
    }
    PortableOutputName::new(&format!("{}_libdefs.h", module.name))?;
    if exports_public_headers(module) {
        // Public modules use the module name itself as a link-library
        // directory and the include name as several header stems.
        PortableOutputName::new(&module.name)?;
        PortableOutputName::new(&format!("{}.h", module.include_name))?;
    }
    for interface in &module.interfaces {
        PortableOutputName::new(&format!("{}.h", interface.interface_name))?;
    }
    Ok(())
}

fn parse_conf_variants(path: &Path, root: &Path) -> std::io::Result<Vec<ConfModule>> {
    let Some(stem) = path.file_stem().map(|value| value.to_string_lossy()) else {
        return Ok(Vec::new());
    };
    let declarations = read_module_declarations(path, &stem, root)?;
    if declarations.is_empty() {
        return Ok(parse_conf_variant(path, root, None)?.into_iter().collect());
    }
    declarations
        .iter()
        .map(|declaration| parse_conf_variant(path, root, Some(declaration)))
        .collect::<std::io::Result<Vec<_>>>()
        .map(|modules| modules.into_iter().flatten().collect())
}

#[derive(Debug)]
struct OutputFailure {
    path: PathBuf,
    source: std::io::Error,
}

impl OutputFailure {
    fn new(path: impl Into<PathBuf>, source: std::io::Error) -> Self {
        Self {
            path: path.into(),
            source,
        }
    }
}

fn generate_sdk_headers(
    module: &ConfModule,
    out_inc: &Path,
    out_gen: Option<&Path>,
    publish_public_headers: bool,
    transaction: &mut FileTransaction,
) -> Result<Vec<String>, OutputFailure> {
    let include_name = public_include_name(module);
    let include_upper = header_guard_name(include_name);
    let mod_upper = header_guard_name(&module.name);
    let public = publish_public_headers && exports_public_headers(module);

    let proto_dir = out_inc.join("proto");
    let clib_dir = out_inc.join("clib");
    let defines_dir = out_inc.join("defines");
    // 1. proto/<mod>.h, following tools/genmodule/writeincproto.c.
    //
    // The `#if !defined(<libbase>)` guard matters: a module that defines its
    // own libbase as a macro (rom/exec does this for KernelBase, in 126 files)
    // must not also see an extern declaration of a different type.
    let ptr = extern_base_type(module);
    let base = &module.lib_base;
    let mut proto_content = format!(
        "{GENERATED_BANNER}\n\
         #ifndef PROTO_{include_upper}_H\n\
         #define PROTO_{include_upper}_H\n\n\
         #include <exec/types.h>\n\
         #include <aros/system.h>\n\
         #include <clib/{include_name}_protos.h>\n\
         #include <defines/{include_name}.h>\n\n\
         #if !defined(__NOLIBBASE__) && !defined(__{include_upper}_NOLIBBASE__)\n\
         \x20#if !defined({base})\n"
    );
    if ptr == "struct Library *" {
        let _ = writeln!(proto_content, "  extern {ptr}{base};");
    } else {
        // A non-Library base can still be requested as a plain Library.
        let _ = write!(
            proto_content,
            "  #ifdef __{include_upper}_STDLIBBASE__\n\
             \x20  extern struct Library *{base};\n\
             \x20 #else\n\
             \x20  extern {ptr}{base};\n\
             \x20 #endif\n"
        );
    }
    let _ = write!(
        proto_content,
        " #endif\n\
         \x20#ifndef __aros_getbase_{base}\n\
         \x20 #define __aros_getbase_{base}() ({base})\n\
         \x20#endif\n\
         #endif\n\n\
         #endif /* PROTO_{include_upper}_H */\n"
    );
    if public {
        let path = proto_dir.join(format!("{include_name}.h"));
        transaction
            .stage_write(&path, proto_content.as_bytes())
            .map_err(|error| OutputFailure::new(path, error))?;
    }

    // 2. clib/<mod>_protos.h
    let mut protos = format!(
        "{GENERATED_BANNER}\n\
         #ifndef CLIB_{include_upper}_PROTOS_H\n\
         #define CLIB_{include_upper}_PROTOS_H\n\n\
         #include <exec/types.h>\n\
         #include <aros/system.h>\n\n\
         {}\n\n\
         #ifdef __cplusplus\n\
         extern \"C\" {{\n\
         #endif\n\n",
        module.cdef
    );

    for func in &module.functions {
        if func.private {
            continue;
        }
        let _ = writeln!(protos, "{};", func.signature());
    }

    protos.push_str(
        "\n#ifdef __cplusplus\n\
         }\n\
         #endif\n\n\
         #endif /* CLIB_",
    );
    protos.push_str(&include_upper);
    protos.push_str("_PROTOS_H */\n");

    if public {
        let path = clib_dir.join(format!("{include_name}_protos.h"));
        transaction
            .stage_write(&path, protos.as_bytes())
            .map_err(|error| OutputFailure::new(path, error))?;
    }

    // 3. defines/<mod>.h: the library-call defines and the varargs stubs.
    let defines_cx = varargs::DefinesContext {
        include_name,
        lib_base: &module.lib_base,
        lib_base_type_extern: &extern_base_type(module),
        basename: &module.base_name,
        first_lvo: varargs::first_lvo(
            &module.mod_type,
            module.options.contains(ConfModuleOptions::NO_RESIDENT),
        ),
        major_version: module.major_version,
    };
    let defines = varargs::render_defines(&defines_cx, &module.functions);
    if public {
        let defines_path = defines_dir.join(format!("{include_name}.h"));
        transaction
            .stage_write(&defines_path, defines.text.as_bytes())
            .map_err(|error| OutputFailure::new(defines_path, error))?;
        // Function LVOs, a separate header in the reference too.
        let lvo_path = defines_dir.join(format!("{include_name}_LVO.h"));
        let lvo = varargs::render_lvo(include_name, &module.functions);
        transaction
            .stage_write(&lvo_path, lvo.as_bytes())
            .map_err(|error| OutputFailure::new(lvo_path, error))?;
    }

    // 4. <mod>_libdefs.h, following tools/genmodule/writeinclibdefs.c.
    let mod_name = mod_name_string(module);
    let flags = resident_flags(module);
    let (maj, min) = (module.major_version, module.minor_version);
    let mut libdefs = String::with_capacity(1024);
    for line in [
        GENERATED_BANNER.to_owned(),
        format!("#ifndef _{mod_upper}_LIBDEFS_H"),
        format!("#define _{mod_upper}_LIBDEFS_H"),
        String::new(),
        "#include <exec/types.h>".to_owned(),
        "#include <exec/libraries.h>".to_owned(),
        String::new(),
        format!("#define GM_UNIQUENAME(n) {}_ ## n", module.base_name),
        format!("#define LIBBASE          {}", module.lib_base),
        format!("#define LIBBASETYPE      {}", module.lib_base_type),
        format!("#define LIBBASETYPEPTR   {} *", module.lib_base_type),
        format!("#define MOD_NAME_STRING  \"{mod_name}\""),
        format!("#define MOD_DATE_STRING  \"{}\"", module.date),
        format!("#define MOD_VERS_STRING  \"{maj}.{min}\""),
        format!(
            "#define VERSION_STRING   \"$VER: {mod_name} {maj}.{min}{}\\r\\n\"",
            if module.date.is_empty() {
                String::new()
            } else {
                format!(" ({})", module.date)
            }
        ),
        format!("#define VERSION_NUMBER   {maj}"),
        format!("#define MAJOR_VERSION    {maj}"),
        format!("#define REVISION_NUMBER  {min}"),
        format!("#define MINOR_VERSION    {min}"),
        "#define COPYRIGHT_STRING \"\"".to_owned(),
        "#define LIBEND           GM_UNIQUENAME(End)".to_owned(),
        "#define LIBFUNCTABLE     GM_UNIQUENAME(FuncTable)".to_owned(),
        format!("#define RESIDENTPRI      {}", module.resident_pri),
        format!("#define RESIDENTFLAGS    {flags}"),
        format!("#define FUNCTIONS_COUNT  {}", functions_count(module)),
    ] {
        libdefs.push_str(&line);
        libdefs.push('\n');
    }

    // The cdefprivate block, verbatim. This is what supplies the definition of
    // the library base struct (e.g. `#include <timer_intern.h>` for
    // struct TimerBase), so it has to land here.
    if !module.cdef_private.trim().is_empty() {
        libdefs.push('\n');
        libdefs.push_str(&module.cdef_private);
    }

    // Accessors the module init code reaches through the library base.
    if let Some(f) = &module.sysbase_field {
        let _ = writeln!(
            libdefs,
            "#define GM_SYSBASE_FIELD(lh) (((LIBBASETYPEPTR)lh)->{f})"
        );
    }
    if let Some(f) = &module.oopbase_field {
        let _ = writeln!(
            libdefs,
            "#define GM_OOPBASE_FIELD(lh) (((LIBBASETYPEPTR)lh)->{f})"
        );
    }
    if let Some(f) = &module.seglist_field {
        let _ = writeln!(
            libdefs,
            "#define GM_SEGLIST_FIELD(lh) (((LIBBASETYPEPTR)lh)->{f})"
        );
    }

    let _ = writeln!(libdefs, "\n#endif /* _{mod_upper}_LIBDEFS_H */");
    // Module-private: keep it out of the shared SDK so same-named .conf files
    // in different subsystems cannot overwrite each other.
    let libdefs_dir = out_gen.map_or_else(|| out_inc.to_path_buf(), |g| g.join(&module.rel_dir));
    let libdefs_path = libdefs_dir.join(format!("{}_libdefs.h", module.name));
    transaction
        .stage_write(&libdefs_path, libdefs.as_bytes())
        .map_err(|error| OutputFailure::new(libdefs_path, error))?;

    // 5. interface/<Name>.h for every declared OOP interface.
    for iface in &module.interfaces {
        interfaces::write_interface(iface, out_inc, transaction).map_err(|error| {
            OutputFailure::new(
                out_inc
                    .join("interface")
                    .join(format!("{}.h", iface.interface_name)),
                error,
            )
        })?;
    }

    Ok(defines.unsupported)
}

/// Names whose `proto/` and `clib/` paths have more than one potential owner.
///
/// The reference build runs genmodule through a concrete `<mmake>-includes`
/// target.  That target's dependency closure determines which declaration owns
/// a shared SDK path at that moment.  This broad bootstrap scan has no such
/// closure, so writing both owners would make the resulting headers depend on
/// traversal and thread scheduling.  Keep those public paths absent until the
/// concrete CMake producer materialises the selected declaration.
fn colliding_public_include_names(modules: &[ConfModule]) -> std::collections::HashSet<String> {
    let mut counts: std::collections::HashMap<String, usize> = std::collections::HashMap::new();
    for module in modules {
        if exports_public_headers(module) {
            // Treat the output namespace as case-insensitive here. The
            // bootstrap can run on case-insensitive APFS, while the project
            // still supports case-sensitive hosts where `Icon` and `icon`
            // are distinct. Withholding both is safer than a host-dependent
            // race; a concrete includes target later owns the exact spelling.
            *counts
                .entry(public_include_name(module).to_ascii_lowercase())
                .or_default() += 1;
        }
    }
    counts
        .into_iter()
        .filter_map(|(name, count)| (count > 1).then_some(name))
        .collect()
}

/// Removes bootstrap products whose shared name is ambiguous.
///
/// `BootstrapSDK.cmake` reruns this scanner during every configuration.  A
/// stale header from a previous non-conflicting configuration would otherwise
/// look usable to Ninja even though there is no longer an unambiguous owner.
fn remove_colliding_public_headers(
    module: &ConfModule,
    out_inc: &Path,
    transaction: &mut FileTransaction,
) -> std::io::Result<()> {
    let include_name = public_include_name(module);
    for path in [
        out_inc.join("proto").join(format!("{include_name}.h")),
        out_inc
            .join("clib")
            .join(format!("{include_name}_protos.h")),
    ] {
        transaction.stage_remove(&path)?;
    }

    for path in [
        out_inc.join("defines").join(format!("{include_name}.h")),
        out_inc
            .join("defines")
            .join(format!("{include_name}_LVO.h")),
    ] {
        transaction.stage_remove(&path)?;
    }

    Ok(())
}

fn private_libdefs_path(root: &Path, module: &ConfModule) -> PathBuf {
    root.join(&module.rel_dir)
        .join(format!("{}_libdefs.h", module.name))
}

/// Removes module-private headers that no current config/declaration owns.
///
/// The scanner runs in an existing build tree on every configure. Without a
/// publication cleanup, renamed modules and architecture changes leave valid-
/// looking libdefs behind indefinitely; the former audit then compared those
/// stale files as if they described current declarations.
fn prune_stale_private_libdefs(
    root: &Path,
    modules: &[ConfModule],
    transaction: &mut FileTransaction,
) -> std::io::Result<usize> {
    if !root.exists() {
        return Ok(0);
    }
    let expected: std::collections::HashSet<PathBuf> = modules
        .iter()
        .map(|module| private_libdefs_path(root, module))
        .collect();
    let mut stale = Vec::new();
    for entry in WalkDir::new(root) {
        let entry = entry.map_err(std::io::Error::other)?;
        let path = entry.path();
        let is_libdefs = path
            .file_name()
            .and_then(|name| name.to_str())
            .is_some_and(|name| name.ends_with("_libdefs.h"));
        if is_libdefs
            && (entry.file_type().is_file() || entry.file_type().is_symlink())
            && !expected.contains(path)
        {
            stale.push(path.to_path_buf());
        }
    }
    stale.sort();
    for path in &stale {
        transaction.stage_remove(path)?;
    }
    Ok(stale.len())
}

#[derive(Debug)]
struct GenerationSummary {
    conf_files: usize,
    stale_libdefs: usize,
    collisions: usize,
    linklib_files: usize,
    libbases: Option<usize>,
    recovery: RecoveryOutcome,
}

fn input_diagnostic(
    stage: DiagnosticStage,
    action: &str,
    path: &Path,
    error: &dyn std::fmt::Display,
) -> Diagnostic {
    Diagnostic::error(
        DiagnosticCode::GenmoduleInput,
        stage,
        format!("cannot {action} '{}': {error}", path.display()),
    )
    .with_location(SourceLocation::new(path.display().to_string()))
    .with_hint("ensure the complete AROS source tree is readable and retry")
}

fn publication_diagnostic(action: &str, path: &Path, error: &std::io::Error) -> Diagnostic {
    let hint = match aros_common::publication_failure_class(error) {
        PublicationFailureClass::Conflict => {
            "stop concurrent generators, verify the destination, and rerun the same command"
        }
        PublicationFailureClass::UnsafeTarget => {
            "use portable output names below a real directory without symlink or special-file targets"
        }
        PublicationFailureClass::Unsupported => {
            "run publication on a supported Unix filesystem with no-follow rename and directory-fsync support"
        }
        PublicationFailureClass::RecoveryIncomplete => {
            "preserve the journal and auxiliary files, stop concurrent writers, then rerun the same command to recover"
        }
        PublicationFailureClass::CommitStateUncertain => {
            "do not delete the generated outputs or journal; rerun the identical command once to complete deterministic recovery"
        }
        PublicationFailureClass::Io => {
            "ensure the destination and its parent directory are writable, stable, and have free space"
        }
    };
    Diagnostic::error(
        DiagnosticCode::GenmodulePublication,
        DiagnosticStage::OutputPublication,
        format!("cannot {action} '{}': {error}", path.display()),
    )
    .with_location(SourceLocation::new(path.display().to_string()))
    .with_hint(hint)
    .with_context(DiagnosticContext {
        output: Some(path.display().to_string()),
        ..DiagnosticContext::default()
    })
}

fn remove_report(
    path: &Path,
    description: &str,
    transaction: &mut FileTransaction,
) -> Option<Diagnostic> {
    transaction
        .stage_remove(path)
        .err()
        .map(|error| publication_diagnostic(description, path, &error))
}

fn execute(
    args: &Args,
    logger: &Logger,
    context: &DiagnosticContext,
) -> Result<GenerationSummary, DiagnosticSet> {
    // Build trees are skipped: SDK header staging copies source directories
    // wholesale, so scanning build/ would parse copied .conf files again.
    let skip_dirs = ["build", "target", ".git"];
    let mut conf_files = Vec::new();
    let mut diagnostics = Vec::new();
    let mut output_paths = vec![args.output_inc.as_path()];
    output_paths.extend(args.output_gen.as_deref());
    output_paths.extend(args.output_linklib.as_deref());
    output_paths.extend(args.output_libbases.as_deref());
    let mut transaction = FileTransaction::for_output_paths(&args.output_inc, &output_paths)
        .map_err(|error| {
            let diagnostic = if aros_common::is_rollback_incomplete(&error) {
                rollback_incomplete_diagnostic(&args.output_inc, &error)
            } else {
                publication_diagnostic(
                    "open or recover generated-output transaction",
                    &args.output_inc,
                    &error,
                )
            };
            DiagnosticSet::single(diagnostic)
        })?;
    let recovery = transaction.recovery_outcome();
    if recovery.recovered() {
        if let Err(error) = logger.event(
            LogLevel::Warn,
            "publication.recovery",
            &format!(
                "genmodule recovered predecessor publication state ({})",
                recovery.as_str()
            ),
            context,
        ) {
            let mut stderr = std::io::stderr().lock();
            let _ = writeln!(
                stderr,
                "warning: publication recovery completed ({}) but recovery logging failed: {error}",
                recovery.as_str()
            );
        }
    }
    for entry in WalkDir::new(&args.scan_dir).into_iter().filter_entry(|e| {
        !e.file_type().is_dir()
            || e.depth() == 0
            || !skip_dirs
                .iter()
                .any(|d| e.file_name().to_string_lossy() == *d)
    }) {
        match entry {
            Ok(entry) => {
                let path = entry.path();
                if path.extension().is_some_and(|ext| ext == "conf")
                    && path
                        .parent()
                        .and_then(|directory| directory.strip_prefix(&args.scan_dir).ok())
                        .is_none_or(|relative| arch_dir_applies(relative, &args.arch_dirs))
                {
                    conf_files.push(entry.into_path());
                }
            }
            Err(error) => {
                let path = error.path().unwrap_or(&args.scan_dir);
                diagnostics.push(input_diagnostic(
                    DiagnosticStage::SourceWalk,
                    "walk source path",
                    path,
                    &error,
                ));
            }
        }
    }
    if !diagnostics.is_empty() {
        return Err(DiagnosticSet::new(diagnostics));
    }
    conf_files.sort();

    // Parse first, then write: the collision check needs to know which modules
    // actually claim an SDK namespace, and that follows from the parsed config.
    let parsed: Vec<(&PathBuf, std::io::Result<Vec<ConfModule>>)> = conf_files
        .par_iter()
        .map(|path| (path, parse_conf_variants(path, &args.scan_dir)))
        .collect();
    let mut modules = Vec::new();
    for (path, result) in parsed {
        match result {
            Ok(mut variants) => modules.append(&mut variants),
            Err(error) => {
                diagnostics.push(input_diagnostic(
                    DiagnosticStage::Parsing,
                    "read module configuration",
                    path,
                    &error,
                ));
            }
        }
    }
    if !diagnostics.is_empty() {
        return Err(DiagnosticSet::new(diagnostics));
    }
    modules.sort_by(|left, right| {
        left.rel_dir
            .cmp(&right.rel_dir)
            .then_with(|| left.name.cmp(&right.name))
    });

    let colliding_names = colliding_public_include_names(&modules);

    // Only modules that export public headers can collide there. Module-private
    // headers are written per module directory and cannot.
    let mut by_name: std::collections::HashMap<String, Vec<&ConfModule>> =
        std::collections::HashMap::new();
    for m in &modules {
        if exports_public_headers(m) {
            by_name
                .entry(public_include_name(m).to_ascii_lowercase())
                .or_default()
                .push(m);
        }
    }
    let mut clashes: Vec<String> = by_name
        .into_iter()
        .filter(|(_, v)| v.len() > 1)
        .map(|(name, v)| {
            let where_: Vec<String> = v
                .iter()
                .map(|m| {
                    let t = if m.mod_type.is_empty() {
                        "?".to_owned()
                    } else {
                        m.mod_type.clone()
                    };
                    format!("{} ({t})", m.rel_dir.display())
                })
                .collect();
            format!("{name}: {}", where_.join(", "))
        })
        .collect();

    clashes.sort_unstable();

    let mut linklib_files = 0usize;
    let mut unsupported_varargs = Vec::new();
    for module in &modules {
        let conflicting =
            colliding_names.contains(&public_include_name(module).to_ascii_lowercase());
        match generate_sdk_headers(
            module,
            &args.output_inc,
            args.output_gen.as_deref(),
            !conflicting,
            &mut transaction,
        ) {
            Ok(mut unsupported) => unsupported_varargs.append(&mut unsupported),
            Err(error) => {
                diagnostics.push(publication_diagnostic(
                    &format!("generate headers for {}", module.rel_dir.display()),
                    &error.path,
                    &error.source,
                ));
            }
        }
        if let Some(root) = args.output_linklib.as_deref() {
            match generate_linklib_sources(module, root, &mut transaction) {
                Ok(n) => linklib_files += n,
                Err(error) => diagnostics.push(publication_diagnostic(
                    &format!(
                        "generate link library sources for {}",
                        module.rel_dir.display()
                    ),
                    root,
                    &error,
                )),
            }
        }
    }
    if !diagnostics.is_empty() {
        return Err(DiagnosticSet::new(diagnostics));
    }

    let collision_report = args.output_inc.join("conf-name-collisions.txt");
    if !clashes.is_empty() {
        let contents = format!("{}\n", clashes.join("\n"));
        if let Err(error) = transaction.stage_write(&collision_report, contents.as_bytes()) {
            diagnostics.push(publication_diagnostic(
                "publish collision report",
                &collision_report,
                &error,
            ));
        }
    }

    unsupported_varargs.sort_unstable();
    unsupported_varargs.dedup();
    let unsupported_report = args.output_inc.join("unsupported-varargs.txt");
    if !unsupported_varargs.is_empty() {
        let contents = format!("{}\n", unsupported_varargs.join("\n"));
        if let Err(error) = transaction.stage_write(&unsupported_report, contents.as_bytes()) {
            diagnostics.push(publication_diagnostic(
                "publish unsupported-varargs report",
                &unsupported_report,
                &error,
            ));
        }
    }

    let mut libbases_count = None;
    if let Some(path) = args.output_libbases.as_deref() {
        // Every declared base, including modules whose headers are withheld for
        // a name collision: the base is still real and still left to the loader.
        let mut bases: Vec<&str> = modules.iter().map(|m| m.lib_base.as_str()).collect();
        bases.sort_unstable();
        bases.dedup();
        libbases_count = Some(bases.len());
        let contents = bases.join("\n") + "\n";
        if let Err(error) = transaction.stage_write(path, contents.as_bytes()) {
            diagnostics.push(publication_diagnostic(
                "publish library-base inventory",
                path,
                &error,
            ));
        }
    }

    if !diagnostics.is_empty() {
        return Err(DiagnosticSet::new(diagnostics));
    }

    // Destructive cleanup is the final filesystem phase. No stale product is
    // removed while a new header, report, linklib, or inventory can still
    // fail publication.
    for module in &modules {
        let conflicting =
            colliding_names.contains(&public_include_name(module).to_ascii_lowercase());
        if conflicting {
            if let Err(error) =
                remove_colliding_public_headers(module, &args.output_inc, &mut transaction)
            {
                diagnostics.push(publication_diagnostic(
                    &format!(
                        "remove ambiguous public headers for {}",
                        module.rel_dir.display()
                    ),
                    &args.output_inc,
                    &error,
                ));
            }
        }
    }
    if clashes.is_empty() {
        if let Some(diagnostic) = remove_report(
            &collision_report,
            "remove stale collision report",
            &mut transaction,
        ) {
            diagnostics.push(diagnostic);
        }
    }
    if unsupported_varargs.is_empty() {
        if let Some(diagnostic) = remove_report(
            &unsupported_report,
            "remove stale unsupported-varargs report",
            &mut transaction,
        ) {
            diagnostics.push(diagnostic);
        }
    }
    if !diagnostics.is_empty() {
        return Err(DiagnosticSet::new(diagnostics));
    }

    let stale_libdefs = if let Some(root) = args.output_gen.as_deref() {
        match prune_stale_private_libdefs(root, &modules, &mut transaction) {
            Ok(count) => count,
            Err(error) => {
                return Err(DiagnosticSet::single(publication_diagnostic(
                    "prune stale private libdefs",
                    root,
                    &error,
                )));
            }
        }
    } else {
        0
    };

    let receipt = transaction.commit().map_err(|error| {
        let diagnostic = if aros_common::is_rollback_incomplete(&error) {
            rollback_incomplete_diagnostic(&args.output_inc, &error)
        } else {
            publication_diagnostic(
                "commit generated output transaction",
                &args.output_inc,
                &error,
            )
        };
        DiagnosticSet::single(diagnostic)
    })?;

    Ok(GenerationSummary {
        conf_files: conf_files.len(),
        stale_libdefs,
        collisions: clashes.len(),
        linklib_files,
        libbases: libbases_count,
        recovery: receipt.recovery(),
    })
}

fn rollback_incomplete_diagnostic(path: &Path, error: &std::io::Error) -> Diagnostic {
    Diagnostic::error(
        DiagnosticCode::GenmoduleRollbackIncomplete,
        DiagnosticStage::Publication,
        format!("generated-output rollback/recovery is incomplete: {error}"),
    )
    .with_location(SourceLocation::new(path.display().to_string()))
    .with_hint(
        "preserve the journal and backup files, stop concurrent writers, then rerun the same command to recover",
    )
}

fn print_summary(args: &Args, summary: &GenerationSummary) {
    let mut report = String::new();
    let _ = writeln!(
        report,
        "⚡ aros-genmodule: Processed {} .conf files -> SDK includes in {}",
        summary.conf_files,
        args.output_inc.display()
    );
    if summary.recovery.recovered() {
        let _ = writeln!(
            report,
            "🩹 aros-genmodule: recovered predecessor publication state ({})",
            summary.recovery.as_str()
        );
    }
    if summary.stale_libdefs > 0 {
        if let Some(root) = args.output_gen.as_deref() {
            let _ = writeln!(
                report,
                "🧹 aros-genmodule: removed {} stale private libdefs header(s) from {}",
                summary.stale_libdefs,
                root.display()
            );
        }
    }
    if summary.collisions > 0 {
        let _ = writeln!(
            report,
            "⚠️  {} module name(s) have conflicting public headers; bootstrap output is withheld until a concrete includes target owns it -> {}",
            summary.collisions,
            args.output_inc.join("conf-name-collisions.txt").display()
        );
    }
    if let (Some(path), Some(count)) = (args.output_libbases.as_deref(), summary.libbases) {
        let _ = writeln!(
            report,
            "🏷️  aros-genmodule: {count} library base(s) -> {}",
            path.display()
        );
    }
    if let Some(root) = args.output_linklib.as_deref() {
        let _ = writeln!(
            report,
            "🔗 aros-genmodule: {} link library source(s) in {}",
            summary.linklib_files,
            root.display()
        );
    }
    aros_common::emit_stdout(format_args!("{report}"), false);
}

fn render(diagnostics: &DiagnosticSet, format: DiagnosticFormat) {
    render_diagnostics(diagnostics, format, POLICY);
}

/// Run the generator command using the process arguments.
#[must_use]
pub fn run() -> ExitCode {
    let arguments: Vec<OsString> = std::env::args_os().collect();
    let requested_format =
        requested_diagnostic_format(&arguments, "AROS_GENMODULE_DIAGNOSTIC_FORMAT");
    let args = match Args::try_parse_from(arguments) {
        Ok(args) => args,
        Err(error)
            if matches!(
                error.kind(),
                ClapErrorKind::DisplayHelp | ClapErrorKind::DisplayVersion
            ) =>
        {
            return match write_stdout(&error.to_string()) {
                Ok(()) => ExitCode::SUCCESS,
                Err(output_error) => {
                    render(
                        &DiagnosticSet::single(
                            Diagnostic::error(
                                DiagnosticCode::GenmoduleObservability,
                                DiagnosticStage::Observability,
                                format!("cannot write help/version output: {output_error}"),
                            )
                            .with_hint("verify the stdout destination and retry"),
                        ),
                        requested_format,
                    );
                    ExitCode::FAILURE
                }
            };
        }
        Err(error) => {
            render(
                &DiagnosticSet::single(
                    Diagnostic::error(
                        DiagnosticCode::GenmoduleInvocation,
                        DiagnosticStage::Invocation,
                        error.to_string().trim().to_owned(),
                    )
                    .with_hint("run `aros-genmodule --help` for the complete invocation contract"),
                ),
                requested_format,
            );
            return ExitCode::FAILURE;
        }
    };
    let logger = match Logger::open(
        args.log_level,
        args.log_format,
        args.log_file.clone(),
        "aros-genmodule",
        POLICY,
    ) {
        Ok(logger) => logger,
        Err(error) => {
            render(
                &DiagnosticSet::single(error.into_diagnostic()),
                args.diagnostic_format,
            );
            return ExitCode::FAILURE;
        }
    };
    let context = DiagnosticContext {
        mode: Some("generate".into()),
        output: Some(args.output_inc.display().to_string()),
        ..DiagnosticContext::default()
    };
    if let Err(error) = logger.event(
        LogLevel::Info,
        "invocation.start",
        "genmodule invocation started",
        &context,
    ) {
        render(
            &DiagnosticSet::single(error.into_diagnostic()),
            args.diagnostic_format,
        );
        return ExitCode::FAILURE;
    }

    match execute(&args, &logger, &context) {
        Ok(summary) => {
            if let Err(error) = logger.event(
                LogLevel::Info,
                "invocation.complete",
                "genmodule invocation completed",
                &context,
            ) {
                let mut stderr = std::io::stderr().lock();
                let _ = writeln!(
                    stderr,
                    "warning: generation committed successfully, but completion logging failed: {error}"
                );
            }
            print_summary(&args, &summary);
            if let Some(diagnostic) = aros_common::take_stdout_failure_diagnostic(
                DiagnosticCode::GenmoduleObservability,
                DiagnosticStage::Observability,
            ) {
                let mut diagnostics = vec![diagnostic];
                if let Err(log_error) = logger.diagnostic(&diagnostics[0]) {
                    diagnostics.push(log_error.into_diagnostic());
                }
                render(&DiagnosticSet::new(diagnostics), args.diagnostic_format);
                return ExitCode::FAILURE;
            }
            ExitCode::SUCCESS
        }
        Err(mut failure) => {
            for diagnostic in failure.diagnostics.clone() {
                if let Err(error) = logger.diagnostic(&diagnostic) {
                    failure.diagnostics.push(error.into_diagnostic());
                    break;
                }
            }
            failure = DiagnosticSet::new(failure.diagnostics);
            render(&failure, args.diagnostic_format);
            ExitCode::FAILURE
        }
    }
}

/// Writes one module's link library sources under `<root>/<rel_dir>/<mod>/`.
///
/// The relative directory is kept because 26 .conf stems occur more than once
/// in the tree; a flat layout would make them overwrite each other, the same
/// reason `<mod>_libdefs.h` is placed per module.
///
/// Both the plain and the `rel` flavour are written. The reference generates
/// them from the same config with `is_rel` toggled, and a module built into a
/// relative-library archive needs the second set.
fn generate_linklib_sources(
    module: &ConfModule,
    root: &Path,
    transaction: &mut FileTransaction,
) -> std::io::Result<usize> {
    // A module with no public functions has nothing to stub, and one that
    // exports no headers has no proto/ header for the stubs to include.
    if !exports_public_headers(module) {
        return Ok(0);
    }

    // Unlike the derived header names (for example `con_libdefs.h`), the
    // module name itself is a directory component here. Validate it at the
    // point where it actually becomes an output component. AROS has internal
    // non-exporting modules named `con` and `aux`; rejecting those while
    // parsing would be unnecessarily stricter than the generated tree.
    PortableOutputName::new(&module.name)?;

    let suffix = match module.mod_type.as_str() {
        // config.c:305 and :315 -- both of these are named "<x>.class".
        "usbclass" | "btclass" => "class",
        other => other,
    };
    let facts = linklib::ModuleFacts {
        name: &module.name,
        include_name: &module.include_name,
        lib_base: &module.lib_base,
        lib_base_type_extern: &extern_base_type(module),
        basename: &module.base_name,
        suffix,
        no_includes: module.options.contains(ConfModuleOptions::NO_INCLUDES),
        cdef_private: &module.cdef_private,
        major_version: module.major_version,
        force_bases: &module.force_bases,
        startup_lines: &module.startup_lines,
    };

    let dir = root.join(&module.rel_dir).join(&module.name);
    let mut written = 0usize;
    for is_rel in [false, true] {
        for (name, body) in linklib::sources(&facts, &module.functions, is_rel) {
            PortableOutputName::new(&name)?;
            transaction.stage_write(&dir.join(name), body.as_bytes())?;
            written += 1;
        }
    }
    Ok(written)
}

#[cfg(test)]
mod lib_tests;
