use clap::Parser;
use rayon::prelude::*;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use walkdir::WalkDir;

#[derive(Parser, Debug)]
#[command(
    name = "aros-genmodule",
    author = "AROS Development Team & Fabian Schmieder (@metaneutrons)",
    version = "0.1.0",
    about = "Pure Rust replacement for genmodule (.conf parser & SDK proto generator)"
)]
struct Args {
    /// Source directory to scan for .conf files
    #[arg(short, long, default_value = ".")]
    scan_dir: PathBuf,

    /// Target SDK include directory (e.g. build/pc-x86_64/SDK/include)
    #[arg(short, long)]
    output_inc: PathBuf,
}

#[derive(Debug, Default)]
struct ConfModule {
    name: String,
    lib_base: String,
    lib_base_type: String,
    cdef: String,
    functions: Vec<String>,
}

fn parse_conf(path: &Path) -> Option<ConfModule> {
    let content = fs::read_to_string(path).ok()?;
    let stem = path.file_stem()?.to_string_lossy().to_string();

    let mut module = ConfModule {
        name: stem.clone(),
        lib_base: format!("{stem}Base"),
        lib_base_type: format!("struct {stem}Base"),
        cdef: String::new(),
        functions: Vec::new(),
    };

    let mut section = "";
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed == "##begin config" {
            section = "config";
        } else if trimmed == "##end config" {
            section = "";
        } else if trimmed == "##begin cdef" {
            section = "cdef";
        } else if trimmed == "##end cdef" {
            section = "";
        } else if trimmed == "##begin functionlist" {
            section = "functions";
        } else if trimmed == "##end functionlist" {
            section = "";
        } else if section == "config" {
            if let Some(stripped) = trimmed.strip_prefix("basename ") {
                let base = stripped.trim();
                module.lib_base = format!("{base}Base");
            } else if let Some(stripped) = trimmed.strip_prefix("libbase ") {
                module.lib_base = stripped.trim().to_string();
            } else if let Some(stripped) = trimmed.strip_prefix("libbasetype ") {
                module.lib_base_type = stripped.trim().to_string();
            }
        } else if section == "cdef" {
            module.cdef.push_str(line);
            module.cdef.push('\n');
        } else if section == "functions"
            && !trimmed.is_empty()
            && !trimmed.starts_with('.')
            && !trimmed.starts_with('#')
        {
            if let Some(paren) = trimmed.rfind('(') {
                let sig = trimmed[..paren].trim().to_string();
                if !sig.is_empty() {
                    module.functions.push(sig);
                }
            }
        }
    }

    Some(module)
}

fn generate_sdk_headers(module: &ConfModule, out_inc: &Path) -> std::io::Result<()> {
    let proto_dir = out_inc.join("proto");
    let clib_dir = out_inc.join("clib");
    let defines_dir = out_inc.join("defines");

    fs::create_dir_all(&proto_dir)?;
    fs::create_dir_all(&clib_dir)?;
    fs::create_dir_all(&defines_dir)?;

    let mod_upper = module.name.to_uppercase();
    let mod_lower = module.name.to_lowercase();

    // 1. proto/<mod>.h
    let proto_content = format!(
        "/* Auto-generated by AROS-NG genmodule v0.1.0 */\n\
         #ifndef PROTO_{mod_upper}_H\n\
         #define PROTO_{mod_upper}_H\n\n\
         #include <exec/types.h>\n\
         #include <aros/system.h>\n\
         #include <clib/{mod_lower}_protos.h>\n\
         #include <defines/{mod_lower}.h>\n\n\
         #if !defined(__NOLIBBASE__) && !defined(___{mod_upper}_NOLIBBASE__)\n\
         extern {} *{};\n\
         #endif\n\n\
         #endif /* PROTO_{mod_upper}_H */\n",
        module.lib_base_type, module.lib_base
    );
    fs::write(proto_dir.join(format!("{mod_lower}.h")), proto_content)?;

    // 2. clib/<mod>_protos.h
    let mut protos = format!(
        "/* Auto-generated by AROS-NG genmodule v0.1.0 */\n\
         #ifndef CLIB_{mod_upper}_PROTOS_H\n\
         #define CLIB_{mod_upper}_PROTOS_H\n\n\
         #include <exec/types.h>\n\
         #include <aros/system.h>\n\n\
         {}\n\n\
         #ifdef __cplusplus\n\
         extern \"C\" {{\n\
         #endif\n\n",
        module.cdef
    );

    for func in &module.functions {
        let _ = writeln!(protos, "{func};");
    }

    protos.push_str(
        "\n#ifdef __cplusplus\n\
         }\n\
         #endif\n\n\
         #endif /* CLIB_",
    );
    protos.push_str(&mod_upper);
    protos.push_str("_PROTOS_H */\n");

    fs::write(clib_dir.join(format!("{mod_lower}_protos.h")), protos)?;

    // 3. defines/<mod>.h
    let defines_content = format!(
        "/* Auto-generated by AROS-NG genmodule v0.1.0 */\n\
         #ifndef DEFINES_{mod_upper}_H\n\
         #define DEFINES_{mod_upper}_H\n\n\
         #endif /* DEFINES_{mod_upper}_H */\n"
    );
    fs::write(defines_dir.join(format!("{mod_lower}.h")), defines_content)?;

    // 4. <mod>_libdefs.h (for library/device initialization)
    let libdefs_content = format!(
        "/* Auto-generated by AROS-NG genmodule v0.1.0 */\n\
         #ifndef _{mod_upper}_LIBDEFS_H\n\
         #define _{mod_upper}_LIBDEFS_H\n\n\
         #include <exec/types.h>\n\
         #include <exec/libraries.h>\n\n\
         #define GM_UNIQUENAME(n) {mod_lower}_ ## n\n\
         #define LIBBASE          {}\n\
         #define LIBBASETYPE      {}\n\
         #define LIBBASETYPEPTR   {} *\n\
         #define MOD_NAME_STRING  \"{mod_lower}.library\"\n\
         #define MOD_VERS_STRING  \"51.1\"\n\
         #define VERSION_STRING   \"$VER: {mod_lower}.library 51.1 (2026-08-20)\\r\\n\"\n\
         #define VERSION_NUMBER   51\n\
         #define REVISION_NUMBER  1\n\
         #define RESIDENTPRI      0\n\
         #define RESIDENTFLAGS    0\n\n\
         #endif /* _{mod_upper}_LIBDEFS_H */\n",
        module.lib_base, module.lib_base_type, module.lib_base_type
    );
    fs::write(
        out_inc.join(format!("{mod_lower}_libdefs.h")),
        libdefs_content,
    )?;

    Ok(())
}

fn main() {
    let args = Args::parse();
    let conf_files: Vec<PathBuf> = WalkDir::new(&args.scan_dir)
        .into_iter()
        .filter_map(std::result::Result::ok)
        .filter(|e| e.path().extension().is_some_and(|ext| ext == "conf"))
        .map(walkdir::DirEntry::into_path)
        .collect();

    conf_files.par_iter().for_each(|conf_path| {
        if let Some(module) = parse_conf(conf_path) {
            let _ = generate_sdk_headers(&module, &args.output_inc);
        }
    });

    println!(
        "⚡ aros-genmodule: Processed {} .conf files -> SDK includes in {}",
        conf_files.len(),
        args.output_inc.display()
    );
}
