schema_version = 1

[source]
repository = "metaneutrons/AROS-NX"
commit = "9369cc8f8ba4f7d320945c78788c6e2a6d0d1eab"

[producer]
repository = "metaneutrons/aros-toolchains"
commit = "cae0a595230fb3548bc68f0a2b6d6725b6bc1c91"
workflow = ".github/workflows/toolchain-release.yml"
