cmake_minimum_required(VERSION 3.22)

# Measure a closed role/path list staged by a CMake media producer. The output
# is a build-input inventory, not a boot result or full source provenance.

foreach(_required IN ITEMS ROOT_DIR TARGET_PRESET MODEL TRANSPORT FILE_SPECS MODE)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "media build receipt requires ${_required}")
    endif()
endforeach()
if(NOT MODE STREQUAL "write" AND NOT MODE STREQUAL "verify")
    message(FATAL_ERROR "media build receipt MODE must be write or verify")
endif()
if(NOT IS_ABSOLUTE "${ROOT_DIR}" OR NOT IS_DIRECTORY "${ROOT_DIR}" OR
   IS_SYMLINK "${ROOT_DIR}")
    message(FATAL_ERROR "media build receipt requires a regular absolute root directory")
endif()
if(NOT TARGET_PRESET MATCHES "^[a-z0-9][a-z0-9_-]*$" OR
   NOT MODEL MATCHES "^[a-z0-9][a-z0-9-]*$" OR
   NOT TRANSPORT MATCHES "^[a-z0-9][a-z0-9-]*$")
    message(FATAL_ERROR "media build receipt has an invalid portable identity")
endif()

list(LENGTH FILE_SPECS _file_count)
if(_file_count LESS 1 OR _file_count GREATER 1024)
    message(FATAL_ERROR "media build receipt requires one to 1024 files")
endif()
list(SORT FILE_SPECS)
set(_roles "")
set(_paths "")
set(_json
    "{\"format_version\":1,\"kind\":\"aros-media-inputs\",\"origin\":\"cmake\",\"target_preset\":\"${TARGET_PRESET}\",\"model\":\"${MODEL}\",\"transport\":\"${TRANSPORT}\",\"files\":[")
set(_separator "")
foreach(_spec IN LISTS FILE_SPECS)
    if(NOT _spec MATCHES "^([a-z0-9][a-z0-9-]*)[|](.+)$")
        message(FATAL_ERROR "media build receipt has an invalid role/path specification")
    endif()
    set(_role "${CMAKE_MATCH_1}")
    set(_relative "${CMAKE_MATCH_2}")
    list(FIND _roles "${_role}" _role_index)
    if(NOT _role_index EQUAL -1)
        message(FATAL_ERROR "media build receipt has a duplicate role: ${_role}")
    endif()
    list(APPEND _roles "${_role}")
    string(TOLOWER "${_relative}" _folded)
    list(FIND _paths "${_folded}" _path_index)
    if(NOT _path_index EQUAL -1)
        message(FATAL_ERROR "media build receipt has a duplicate path: ${_relative}")
    endif()
    list(APPEND _paths "${_folded}")

    string(REPLACE "/" ";" _components "${_relative}")
    set(_file "${ROOT_DIR}")
    foreach(_component IN LISTS _components)
        if(NOT _component MATCHES "^[A-Za-z0-9_][A-Za-z0-9_.-]*$")
            message(FATAL_ERROR "media build receipt has an unsafe relative path: ${_relative}")
        endif()
        set(_file "${_file}/${_component}")
        if(IS_SYMLINK "${_file}")
            message(FATAL_ERROR "media build receipt refuses a symlink: ${_relative}")
        endif()
    endforeach()
    if(NOT EXISTS "${_file}" OR IS_DIRECTORY "${_file}")
        message(FATAL_ERROR "media build receipt is missing a regular file: ${_relative}")
    endif()
    # CMake's EXISTS/IS_DIRECTORY pair also accepts FIFOs and sockets. The
    # fixed POSIX test rejects those before file(SIZE)/file(SHA256) can block.
    # Rust revalidates the produced receipt through no-follow descriptors.
    execute_process(COMMAND /bin/sh -c "test -f \"$1\""
        aros-media-file "${_file}" RESULT_VARIABLE _regular_result)
    if(NOT _regular_result EQUAL 0)
        message(FATAL_ERROR "media build receipt refuses a non-regular file: ${_relative}")
    endif()
    file(SIZE "${_file}" _size)
    file(SHA256 "${_file}" _sha)
    string(APPEND _json "${_separator}{\"role\":\"${_role}\",\"path\":\"${_relative}\",\"sha256\":\"${_sha}\",\"size_bytes\":${_size}}")
    set(_separator ",")
endforeach()
string(APPEND _json "]}\n")
string(LENGTH "${_json}" _json_length)
if(_json_length GREATER 1048576)
    message(FATAL_ERROR "media build receipt exceeds its one-megabyte limit")
endif()

set(_receipt "${ROOT_DIR}/media-build-receipt.json")
if(IS_SYMLINK "${_receipt}" OR IS_DIRECTORY "${_receipt}")
    message(FATAL_ERROR "media build receipt output is not a regular file path")
endif()
if(MODE STREQUAL "verify")
    if(NOT EXISTS "${_receipt}")
        message(FATAL_ERROR "media build receipt is missing")
    endif()
    execute_process(COMMAND /bin/sh -c "test -f \"$1\""
        aros-media-receipt "${_receipt}" RESULT_VARIABLE _regular_result)
    if(NOT _regular_result EQUAL 0)
        message(FATAL_ERROR "media build receipt is not a regular file")
    endif()
    file(READ "${_receipt}" _actual LIMIT 1048577)
    if(NOT _actual STREQUAL _json)
        message(FATAL_ERROR "media build receipt differs from measured inputs")
    endif()
else()
    string(RANDOM LENGTH 20 ALPHABET 0123456789abcdef _nonce)
    set(_temporary "${ROOT_DIR}/.media-build-receipt-${_nonce}.tmp")
    if(EXISTS "${_temporary}" OR IS_SYMLINK "${_temporary}")
        message(FATAL_ERROR "media build receipt staging path is occupied")
    endif()
    file(WRITE "${_temporary}" "${_json}")
    file(RENAME "${_temporary}" "${_receipt}")
endif()
