cmake_minimum_required(VERSION 3.22)

# GRUB/QEMU search only the first 8192 file bytes for a Multiboot-1 header.
# Validate the actual linked image, not merely the presence of a source symbol.
if(NOT DEFINED BOOTSTRAP_ELF OR NOT EXISTS "${BOOTSTRAP_ELF}")
    message(FATAL_ERROR "PC bootstrap ELF is missing: ${BOOTSTRAP_ELF}")
endif()
file(READ "${BOOTSTRAP_ELF}" _prefix LIMIT 8192 HEX)
if(NOT _prefix MATCHES "^7f454c460101")
    message(FATAL_ERROR "PC bootstrap is not a little-endian ELF32 image")
endif()

function(_bootstrap_little_endian_u32 bytes output)
    string(SUBSTRING "${bytes}" 0 2 _byte0)
    string(SUBSTRING "${bytes}" 2 2 _byte1)
    string(SUBSTRING "${bytes}" 4 2 _byte2)
    string(SUBSTRING "${bytes}" 6 2 _byte3)
    math(EXPR _value "0x${_byte3}${_byte2}${_byte1}${_byte0}")
    set(${output} "${_value}" PARENT_SCOPE)
endfunction()

string(LENGTH "${_prefix}" _prefix_length)
set(_cursor 0)
set(_valid FALSE)
while(_cursor LESS _prefix_length)
    string(SUBSTRING "${_prefix}" ${_cursor} -1 _remaining)
    string(FIND "${_remaining}" "02b0ad1b" _found)
    if(_found LESS 0)
        break()
    endif()
    math(EXPR _candidate "${_cursor} + ${_found}")
    math(EXPR _offset "${_candidate} / 2")
    math(EXPR _end "${_candidate} + 24")
    math(EXPR _alignment "${_offset} % 4")
    if(_alignment EQUAL 0 AND _end LESS_EQUAL _prefix_length)
        math(EXPR _flags_start "${_candidate} + 8")
        math(EXPR _checksum_start "${_candidate} + 16")
        string(SUBSTRING "${_prefix}" ${_flags_start} 8 _flags_bytes)
        string(SUBSTRING "${_prefix}" ${_checksum_start} 8 _checksum_bytes)
        _bootstrap_little_endian_u32("${_flags_bytes}" _flags)
        _bootstrap_little_endian_u32("${_checksum_bytes}" _checksum)
        math(EXPR _sum "(0x1BADB002 + ${_flags} + ${_checksum}) & 0xffffffff")
        if(_sum EQUAL 0)
            set(_valid TRUE)
            break()
        endif()
    endif()
    math(EXPR _cursor "${_candidate} + 8")
endwhile()

if(NOT _valid)
    message(FATAL_ERROR
        "PC bootstrap has no aligned, checksum-valid Multiboot-1 header "
        "entirely within the first 8192 file bytes")
endif()
message(STATUS "PC bootstrap Multiboot-1 header verified at file offset ${_offset}")
