include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/LiteralObjects.cmake")

# Source-proved C-to-assembly and literal grep/cut/sed header recipe. This
# producer uses only the audited compiler argv, never CMake's ambient flags.
function(aros_generate_assembly_header)
    cmake_parse_arguments(PARSE_ARGV 0 H "" "NAME;AGGREGATE;SOURCE;ASSEMBLY;OUTPUT;TOKEN;HEADER_ROOT" "ARGUMENTS;DEPENDS")
    if(H_UNPARSED_ARGUMENTS OR H_KEYWORDS_MISSING_VALUES)
        message(FATAL_ERROR "Assembly header: invalid or incomplete arguments")
    endif()
    foreach(key NAME AGGREGATE SOURCE ASSEMBLY OUTPUT TOKEN)
        if(NOT DEFINED H_${key} OR "${H_${key}}" STREQUAL "")
            message(FATAL_ERROR "Assembly header: missing ${key}")
        endif()
    endforeach()
    foreach(owner "${H_NAME}" "${H_AGGREGATE}")
        if(NOT owner MATCHES "^[A-Za-z0-9][A-Za-z0-9_-]*$")
            message(FATAL_ERROR "Assembly header: unsafe owner")
        endif()
    endforeach()
    if(H_NAME STREQUAL H_AGGREGATE OR TARGET "${H_NAME}" OR
       TARGET "${H_NAME}-extract" OR TARGET "${H_NAME}-header-check")
        message(FATAL_ERROR "Assembly header: unsafe or duplicate owner")
    endif()
    set(private_targets "${H_NAME}-assembly" "${H_NAME}-assembly-compile"
        "${H_NAME}-assembly-check" "${H_NAME}-extract" "${H_NAME}-header-check")
    get_property(prior_private_targets GLOBAL PROPERTY AROS_ASSEMBLY_HEADER_PRIVATE_TARGETS)
    if(H_AGGREGATE IN_LIST private_targets OR H_AGGREGATE IN_LIST prior_private_targets)
        message(FATAL_ERROR "Assembly header: aggregate collides with a private producer target")
    endif()
    if(NOT H_TOKEN STREQUAL ".ascii" AND NOT H_TOKEN STREQUAL ".asciz")
        message(FATAL_ERROR "Assembly header: token must be .ascii or .asciz")
    endif()
    foreach(dependency IN LISTS H_DEPENDS)
        if(NOT dependency MATCHES "^[A-Za-z0-9][A-Za-z0-9_.+-]*$" OR
           dependency STREQUAL H_NAME OR dependency STREQUAL H_AGGREGATE OR
           dependency IN_LIST private_targets OR dependency IN_LIST prior_private_targets)
            message(FATAL_ERROR "Assembly header: unsafe dependency")
        endif()
    endforeach()
    _aros_literal_reject_control_text("${H_OUTPUT}" "header output")
    if(NOT DEFINED H_HEADER_ROOT)
        set(H_HEADER_ROOT "${AROS_GENINC_DIR}")
    endif()
    _aros_literal_reject_control_text("${H_HEADER_ROOT}" "header root")
    if(NOT IS_ABSOLUTE "${H_OUTPUT}" OR NOT IS_ABSOLUTE "${H_HEADER_ROOT}")
        message(FATAL_ERROR "Assembly header: absolute output and GENINCDIR are required")
    endif()
    cmake_path(ABSOLUTE_PATH AROS_BUILD_DIR NORMALIZE OUTPUT_VARIABLE build_root)
    cmake_path(ABSOLUTE_PATH H_HEADER_ROOT NORMALIZE OUTPUT_VARIABLE header_root)
    cmake_path(IS_PREFIX build_root "${header_root}" NORMALIZE root_inside)
    if(NOT root_inside OR header_root STREQUAL build_root)
        message(FATAL_ERROR "Assembly header: GENINCDIR must be below the build root")
    endif()
    cmake_path(ABSOLUTE_PATH H_OUTPUT NORMALIZE OUTPUT_VARIABLE output)
    cmake_path(IS_PREFIX header_root "${output}" NORMALIZE output_inside)
    cmake_path(GET output FILENAME output_name)
    if(NOT output_inside OR output STREQUAL header_root OR
       NOT output_name MATCHES "^[A-Za-z0-9][A-Za-z0-9_.+-]*\\.h$")
        message(FATAL_ERROR "Assembly header: output must be a .h below GENINCDIR")
    endif()
    _aros_literal_check_path_chain("${output}" "${build_root}" "header output")
    _aros_literal_check_optional_regular("${output}" "header output")
    string(TOLOWER "${output}" folded_output)
    string(SHA256 key "${folded_output}")
    get_property(prior_owner GLOBAL PROPERTY "AROS_ASSEMBLY_HEADER_${key}")
    if(prior_owner)
        message(FATAL_ERROR "Assembly header: duplicate output owned by ${prior_owner}")
    endif()
    set_property(GLOBAL PROPERTY "AROS_ASSEMBLY_HEADER_${key}" "${H_NAME}")

    set(compiler_arguments)
    if(H_ARGUMENTS)
        set(compiler_arguments ARGUMENTS ${H_ARGUMENTS})
    endif()
    aros_compile_literal_object(NAME "${H_NAME}-assembly" SOURCE "${H_SOURCE}"
        OUTPUT "${H_ASSEMBLY}" LANGUAGE C OUTPUT_MODE ASSEMBLY ${compiler_arguments})
    if(H_DEPENDS)
        add_dependencies("${H_NAME}-assembly-compile" ${H_DEPENDS})
    endif()
    cmake_path(ABSOLUTE_PATH H_ASSEMBLY NORMALIZE OUTPUT_VARIABLE assembly)
    set(command_root "${CMAKE_CURRENT_BINARY_DIR}")
    _aros_literal_check_root("${command_root}" "command root")
    set(command_file "${command_root}/CMakeFiles/aros-assembly-header-${key}.cmake")
    _aros_literal_check_path_chain("${command_file}" "${command_root}" "command file")
    _aros_literal_check_optional_regular("${command_file}" "command file")
    set(contents "# Source-proved assembly header extraction.\n")
    foreach(field BUILD_ROOT HEADER_ROOT ASSEMBLY OUTPUT TOKEN)
        if(field STREQUAL "BUILD_ROOT")
            set(value "${build_root}")
        elseif(field STREQUAL "HEADER_ROOT")
            set(value "${header_root}")
        elseif(field STREQUAL "ASSEMBLY")
            set(value "${assembly}")
        elseif(field STREQUAL "OUTPUT")
            set(value "${output}")
        else()
            set(value "${H_TOKEN}")
        endif()
        _aros_literal_append_set(contents "${field}" "${value}")
    endforeach()
    file(MAKE_DIRECTORY "${command_root}/CMakeFiles")
    if(EXISTS "${command_file}")
        file(READ "${command_file}" existing)
    else()
        set(existing "")
    endif()
    if(NOT contents STREQUAL existing)
        file(WRITE "${command_file}" "${contents}")
    endif()
    file(SHA256 "${command_file}" command_sha256)
    set(runner "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/RunAssemblyHeader.cmake")
    add_custom_target("${H_NAME}-header-check"
        COMMAND "${CMAKE_COMMAND}" "-DCOMMAND_FILE=${command_file}"
            "-DCOMMAND_ROOT=${command_root}" "-DCOMMAND_SHA256=${command_sha256}"
            -DVERIFY_ONLY=ON -P "${runner}" VERBATIM)
    add_custom_command(OUTPUT "${output}"
        COMMAND "${CMAKE_COMMAND}" "-DCOMMAND_FILE=${command_file}"
            "-DCOMMAND_ROOT=${command_root}" "-DCOMMAND_SHA256=${command_sha256}"
            -DVERIFY_ONLY=OFF -P "${runner}"
        DEPENDS "${assembly}" "${command_file}" "${runner}" VERBATIM)
    add_custom_target("${H_NAME}-extract" DEPENDS "${output}")
    add_dependencies("${H_NAME}-extract" "${H_NAME}-assembly" "${H_NAME}-header-check")
    add_custom_target("${H_NAME}")
    add_dependencies("${H_NAME}" "${H_NAME}-extract")
    set_property(GLOBAL APPEND PROPERTY AROS_ASSEMBLY_HEADER_PRIVATE_TARGETS ${private_targets})
    if(NOT TARGET "${H_AGGREGATE}")
        add_custom_target("${H_AGGREGATE}")
    endif()
    add_dependencies("${H_AGGREGATE}" "${H_NAME}" ${H_DEPENDS})
endfunction()
