cmake_minimum_required(VERSION 3.24)

function(_copy_header_fail reason)
    if(DEFINED _temporary AND (EXISTS "${_temporary}" OR IS_SYMLINK "${_temporary}")
       AND (NOT IS_DIRECTORY "${_temporary}" OR IS_SYMLINK "${_temporary}"))
        file(REMOVE "${_temporary}")
    endif()
    message(FATAL_ERROR "header copy: ${reason}")
endfunction()

# Revalidate at execution time: configure-time checks cannot prove that a
# source or output was not replaced with a symlink before Ninja runs.
foreach(_required IN ITEMS INPUT OUTPUT INPUT_ROOT OUTPUT_ROOT BINARY_ROOT)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "header copy requires ${_required}")
    endif()
    if(NOT IS_ABSOLUTE "${${_required}}" OR "${${_required}}" MATCHES "[;\r\n\"$]")
        message(FATAL_ERROR "header copy: ${_required} is not a safe absolute path")
    endif()
    cmake_path(NORMAL_PATH ${_required})
endforeach()

function(_copy_header_path label path root)
    cmake_path(IS_PREFIX root "${path}" NORMALIZE _inside)
    if(NOT _inside OR path STREQUAL root OR root STREQUAL "/")
        _copy_header_fail("${label} escapes its declared root")
    endif()
    if(IS_SYMLINK "${root}")
        _copy_header_fail("${label} root is a symlink")
    endif()
    file(RELATIVE_PATH _relative "${root}" "${path}")
    string(REPLACE "/" ";" _components "${_relative}")
    set(_probe "${root}")
    foreach(_component IN LISTS _components)
        set(_probe "${_probe}/${_component}")
        if(IS_SYMLINK "${_probe}")
            _copy_header_fail("${label} crosses a symlink: ${_probe}")
        endif()
    endforeach()
endfunction()

find_program(_regular_test NAMES test PATHS /usr/bin /bin NO_DEFAULT_PATH REQUIRED)
function(_copy_header_regular label path)
    execute_process(COMMAND "${_regular_test}" -f "${path}"
        RESULT_VARIABLE _result OUTPUT_QUIET ERROR_QUIET TIMEOUT 10)
    if(NOT "${_result}" STREQUAL "0")
        _copy_header_fail("${label} is not a regular file: ${path}")
    endif()
endfunction()

if(NOT IS_DIRECTORY "${INPUT_ROOT}" OR NOT IS_DIRECTORY "${BINARY_ROOT}")
    message(FATAL_ERROR "header copy: input or binary root is missing")
endif()
_copy_header_path("input" "${INPUT}" "${INPUT_ROOT}")
_copy_header_path("output root" "${OUTPUT_ROOT}" "${BINARY_ROOT}")
_copy_header_path("output" "${OUTPUT}" "${OUTPUT_ROOT}")
_copy_header_path("output" "${OUTPUT}" "${BINARY_ROOT}")
if(INPUT STREQUAL OUTPUT)
    message(FATAL_ERROR "header copy: input and output must be distinct")
endif()
_copy_header_regular("input" "${INPUT}")
if(EXISTS "${OUTPUT}" OR IS_SYMLINK "${OUTPUT}")
    _copy_header_regular("existing output" "${OUTPUT}")
endif()
file(SIZE "${INPUT}" _input_size)
if(_input_size GREATER 33554432)
    message(FATAL_ERROR "header copy: input exceeds 32 MiB")
endif()

file(SHA256 "${INPUT}" _input_hash)
if(EXISTS "${OUTPUT}")
    file(SHA256 "${OUTPUT}" _output_hash)
    if(_input_hash STREQUAL _output_hash)
        return()
    endif()
endif()
get_filename_component(_parent "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_parent}")
_copy_header_path("output" "${OUTPUT}" "${BINARY_ROOT}")
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef _suffix)
set(_temporary "${OUTPUT}.${_suffix}.tmp")
if(EXISTS "${_temporary}" OR IS_SYMLINK "${_temporary}")
    message(FATAL_ERROR "header copy: temporary file already exists")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy "${INPUT}" "${_temporary}"
    RESULT_VARIABLE _copy_result TIMEOUT 30)
if(NOT "${_copy_result}" STREQUAL "0")
    _copy_header_fail("staging failed")
endif()
_copy_header_path("staging file" "${_temporary}" "${BINARY_ROOT}")
_copy_header_regular("staging file" "${_temporary}")
_copy_header_path("input" "${INPUT}" "${INPUT_ROOT}")
_copy_header_regular("input" "${INPUT}")
file(SHA256 "${INPUT}" _input_after)
file(SHA256 "${_temporary}" _staged_hash)
if(NOT _input_hash STREQUAL _input_after OR NOT _staged_hash STREQUAL _input_hash)
    file(REMOVE "${_temporary}")
    message(FATAL_ERROR "header copy: input changed during staging")
endif()
_copy_header_path("output" "${OUTPUT}" "${BINARY_ROOT}")
_copy_header_path("staging file" "${_temporary}" "${BINARY_ROOT}")
_copy_header_regular("staging file" "${_temporary}")
file(RENAME "${_temporary}" "${OUTPUT}" RESULT _rename_result)
if(NOT "${_rename_result}" STREQUAL "0")
    file(REMOVE "${_temporary}")
    message(FATAL_ERROR "header copy: atomic publication failed: ${_rename_result}")
endif()
