# Run after the public-header barrier, before any external producer. Ninja's
# restat preserves cached archives when timestamps changed but contents did not.
cmake_minimum_required(VERSION 3.22)
foreach(_required SDK_ROOT GEN_ROOT OUTPUT)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "External SDK contract requires ${_required}")
    endif()
endforeach()
set(_inventory "external-sdk-v1\n")
foreach(_root IN ITEMS "${SDK_ROOT}" "${GEN_ROOT}")
    file(GLOB_RECURSE _headers LIST_DIRECTORIES FALSE RELATIVE "${_root}"
        "${_root}/*.h" "${_root}/*.hpp" "${_root}/*.inc")
    list(SORT _headers)
    string(APPEND _inventory "root\n")
    foreach(_header IN LISTS _headers)
        file(SHA256 "${_root}/${_header}" _digest)
        string(APPEND _inventory "${_header} ${_digest}\n")
    endforeach()
endforeach()
string(SHA256 _digest "${_inventory}")
set(_content "external-sdk-v1 ${_digest}\n")
set(_previous "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" _previous)
endif()
if(NOT _previous STREQUAL _content)
    get_filename_component(_parent "${OUTPUT}" DIRECTORY)
    file(MAKE_DIRECTORY "${_parent}")
    file(WRITE "${OUTPUT}" "${_content}")
endif()
