# Closed source-owned host-C header aggregates. No implicit include mirrors.
include_guard(GLOBAL)
include(CMakeParseArguments)
include("${CMAKE_CURRENT_LIST_DIR}/DirectorySetup.cmake")

function(_aros_aggregate_path root path must_exist)
    foreach(_value "${root}" "${path}")
        if(NOT IS_ABSOLUTE "${_value}" OR "${_value}" MATCHES "[;\"$\r\n\\[\\]]" OR
           "${_value}" MATCHES "(^|/)\\.\\.?(/|$)")
            message(FATAL_ERROR "Host header aggregate: unsafe path: ${_value}")
        endif()
    endforeach()
    cmake_path(IS_PREFIX root "${path}" NORMALIZE _inside)
    if(NOT _inside OR path STREQUAL root OR IS_SYMLINK "${root}")
        message(FATAL_ERROR "Host header aggregate: path escapes or aliases root: ${path}")
    endif()
    file(RELATIVE_PATH _relative "${root}" "${path}")
    string(REPLACE "/" ";" _components "${_relative}")
    set(_probe "${root}")
    foreach(_component IN LISTS _components)
        string(APPEND _probe "/${_component}")
        if(IS_SYMLINK "${_probe}")
            message(FATAL_ERROR "Host header aggregate: path crosses symlink: ${_probe}")
        endif()
    endforeach()
    if(EXISTS "${path}")
        find_program(_regular_test NAMES test PATHS /usr/bin /bin NO_DEFAULT_PATH NO_CACHE REQUIRED)
        execute_process(COMMAND "${_regular_test}" -f "${path}" RESULT_VARIABLE _regular_result)
        if(NOT _regular_result STREQUAL "0")
            message(FATAL_ERROR "Host header aggregate: existing path is not a regular file: ${path}")
        endif()
    endif()
    _aros_directory_physical_path("${root}" _root_real)
    if(EXISTS "${path}" AND NOT IS_DIRECTORY "${path}")
        cmake_path(GET path PARENT_PATH _parent)
        _aros_directory_physical_path("${_parent}" _parent_real)
        cmake_path(GET path FILENAME _filename)
        set(_path_real "${_parent_real}/${_filename}")
    else()
        _aros_directory_physical_path("${path}" _path_real)
    endif()
    cmake_path(IS_PREFIX _root_real "${_path_real}" NORMALIZE _physical_inside)
    if(NOT _physical_inside OR (must_exist AND (NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")))
        message(FATAL_ERROR "Host header aggregate: missing or uncontained file: ${path}")
    endif()
endfunction()

function(_aros_aggregate_literal value)
    if("${value}" STREQUAL "" OR NOT "${value}" MATCHES "^[A-Za-z0-9_.,=+:/-]+$")
        message(FATAL_ERROR "Host header aggregate: unsafe literal argument: ${value}")
    endif()
endfunction()

function(_aros_aggregate_recipe recipe content out_hash)
    _aros_aggregate_path("${CMAKE_BINARY_DIR}" "${recipe}" FALSE)
    cmake_path(GET recipe PARENT_PATH _parent)
    file(MAKE_DIRECTORY "${_parent}")
    if(EXISTS "${recipe}")
        file(READ "${recipe}" _old)
    else()
        set(_old "")
    endif()
    if(NOT _old STREQUAL content)
        file(WRITE "${recipe}" "${content}")
    endif()
    file(SHA256 "${recipe}" _hash)
    set(${out_hash} "${_hash}" PARENT_SCOPE)
endfunction()

function(aros_host_header_aggregate)
    cmake_parse_arguments(PARSE_ARGV 0 HA "" "NAME;TOOL;SOURCE" "COMPILE_FLAGS")
    if(HA_UNPARSED_ARGUMENTS OR HA_KEYWORDS_MISSING_VALUES)
        message(FATAL_ERROR "Host header aggregate: malformed declaration")
    endif()
    foreach(_name NAME TOOL)
        if(NOT HA_${_name} MATCHES "^[A-Za-z0-9_+-][A-Za-z0-9_.+-]*$")
            message(FATAL_ERROR "Host header aggregate: invalid ${_name}")
        endif()
    endforeach()
    if(TARGET "${HA_NAME}" OR TARGET "aros-header-aggregate-tool-${HA_TOOL}")
        message(FATAL_ERROR "Host header aggregate: duplicate target/tool ${HA_NAME}")
    endif()
    _aros_aggregate_path("${AROS_SOURCE_DIR}" "${HA_SOURCE}" TRUE)
    foreach(_flag IN LISTS HA_COMPILE_FLAGS)
        _aros_aggregate_literal("${_flag}")
        if(NOT _flag MATCHES "^(-W[A-Za-z0-9_=+-]+|-O[0-3sg]|-std=[A-Za-z0-9_+-]+|-D[A-Za-z_][A-Za-z0-9_]*(=[A-Za-z0-9_+-]+)?)$")
            message(FATAL_ERROR "Host header aggregate: unsupported compiler flag ${_flag}")
        endif()
    endforeach()
    if(NOT AROS_HOST_CC)
        find_program(AROS_HOST_CC NAMES cc clang gcc REQUIRED)
    endif()
    if(NOT IS_ABSOLUTE "${AROS_HOST_CC}" OR NOT EXISTS "${AROS_HOST_CC}" OR
       IS_DIRECTORY "${AROS_HOST_CC}" OR "${AROS_HOST_CC}" MATCHES "[;\"$\r\n\\[\\]]")
        message(FATAL_ERROR "Host header aggregate: unsafe or missing host compiler")
    endif()
    set(_tool "${CMAKE_BINARY_DIR}/hosttools/${HA_TOOL}")
    _aros_aggregate_path("${CMAKE_BINARY_DIR}" "${_tool}" FALSE)
    set(_recipe "${CMAKE_BINARY_DIR}/.aros-host-header-aggregates/${HA_NAME}-tool.cmake")
    set(_body "set(AG_SOURCE_ROOT [==[${AROS_SOURCE_DIR}]==])\nset(AG_SOURCE [==[${HA_SOURCE}]==])\nset(AG_COMPILER [==[${AROS_HOST_CC}]==])\nset(AG_TOOL [==[${_tool}]==])\nset(AG_FLAGS [==[${HA_COMPILE_FLAGS}]==])\n")
    _aros_aggregate_recipe("${_recipe}" "${_body}" _hash)
    set(_validator "aros-header-aggregate-validate-tool-${HA_TOOL}")
    add_custom_target("${_validator}"
        COMMAND "${CMAKE_COMMAND}" "-DAG_RECIPE=${_recipe}" "-DAG_RECIPE_SHA256=${_hash}"
            "-DAG_BINARY_ROOT=${CMAKE_BINARY_DIR}" -DAG_PHASE=validate-compile
            -P "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/RunHostHeaderAggregate.cmake"
        VERBATIM)
    add_custom_command(OUTPUT "${_tool}"
        COMMAND "${CMAKE_COMMAND}" "-DAG_RECIPE=${_recipe}" "-DAG_RECIPE_SHA256=${_hash}"
            "-DAG_BINARY_ROOT=${CMAKE_BINARY_DIR}" -DAG_PHASE=compile
            -P "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/RunHostHeaderAggregate.cmake"
        DEPENDS "${HA_SOURCE}" "${AROS_HOST_CC}" "${_recipe}" "${_validator}"
            "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/RunHostHeaderAggregate.cmake"
            "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/HostHeaderAggregates.cmake"
            "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/DirectorySetup.cmake"
        COMMENT "Building source-owned host header tool ${HA_TOOL}" VERBATIM)
    add_custom_target("aros-header-aggregate-tool-${HA_TOOL}" DEPENDS "${_tool}")
    add_custom_target("${HA_NAME}")
    set_property(TARGET "${HA_NAME}" PROPERTY AROS_HEADER_AGGREGATE_TOOL "${_tool}")
    set_property(TARGET "${HA_NAME}" PROPERTY AROS_HEADER_AGGREGATE_COUNT 0)
endfunction()

function(aros_host_header_aggregate_output)
    cmake_parse_arguments(PARSE_ARGV 0 HO "GENERATED_MIRROR" "NAME;HEADER" "ARGUMENTS")
    if(HO_UNPARSED_ARGUMENTS OR HO_KEYWORDS_MISSING_VALUES OR NOT TARGET "${HO_NAME}" OR
       NOT HO_HEADER MATCHES "^[A-Za-z0-9_./+-]+\\.h$" OR
       HO_HEADER MATCHES "(^|/)\\.\\.?(/|$)" OR HO_HEADER MATCHES "^/")
        message(FATAL_ERROR "Host header aggregate: invalid output declaration")
    endif()
    get_target_property(_tool "${HO_NAME}" AROS_HEADER_AGGREGATE_TOOL)
    if(NOT _tool)
        message(FATAL_ERROR "Host header aggregate: owner is not a checked aggregate")
    endif()
    get_target_property(_count "${HO_NAME}" AROS_HEADER_AGGREGATE_COUNT)
    math(EXPR _count "${_count} + 1")
    if(_count GREATER 4096)
        message(FATAL_ERROR "Host header aggregate: more than 4096 outputs")
    endif()
    set_property(TARGET "${HO_NAME}" PROPERTY AROS_HEADER_AGGREGATE_COUNT "${_count}")
    foreach(_argument IN LISTS HO_ARGUMENTS)
        _aros_aggregate_literal("${_argument}")
    endforeach()
    set(_primary "${AROS_SDK_INCLUDE_DIR}/${HO_HEADER}")
    set(_outputs "${_primary}")
    set(_mirror "")
    if(HO_GENERATED_MIRROR)
        set(_mirror "${AROS_GENINC_DIR}/${HO_HEADER}")
        list(APPEND _outputs "${_mirror}")
    endif()
    get_property(_claimed GLOBAL PROPERTY AROS_HOST_HEADER_AGGREGATE_OUTPUTS)
    foreach(_output IN LISTS _outputs)
        _aros_aggregate_path("${CMAKE_BINARY_DIR}" "${_output}" FALSE)
        if(_output IN_LIST _claimed)
            message(FATAL_ERROR "Host header aggregate: duplicate output ${_output}")
        endif()
        list(APPEND _claimed "${_output}")
    endforeach()
    _aros_aggregate_path("${AROS_SDK_INCLUDE_DIR}" "${_primary}" FALSE)
    if(_mirror)
        _aros_aggregate_path("${AROS_GENINC_DIR}" "${_mirror}" FALSE)
    endif()
    set_property(GLOBAL PROPERTY AROS_HOST_HEADER_AGGREGATE_OUTPUTS "${_claimed}")
    string(SHA256 _id "${HO_NAME}/${HO_HEADER}")
    set(_recipe "${CMAKE_BINARY_DIR}/.aros-host-header-aggregates/${_id}.cmake")
    set(_completion "${_recipe}.complete")
    list(APPEND _outputs "${_completion}")
    set(_body "set(AG_TOOL [==[${_tool}]==])\nset(AG_PRIMARY [==[${_primary}]==])\nset(AG_MIRROR [==[${_mirror}]==])\nset(AG_SDK_ROOT [==[${AROS_SDK_INCLUDE_DIR}]==])\nset(AG_GENINC_ROOT [==[${AROS_GENINC_DIR}]==])\nset(AG_ARGUMENTS [==[${HO_ARGUMENTS}]==])\nset(AG_COMPLETION [==[${_completion}]==])\n")
    _aros_aggregate_recipe("${_recipe}" "${_body}" _hash)
    set(_validator "aros-header-aggregate-validate-output-${_id}")
    add_custom_target("${_validator}"
        COMMAND "${CMAKE_COMMAND}" "-DAG_RECIPE=${_recipe}" "-DAG_RECIPE_SHA256=${_hash}"
            "-DAG_BINARY_ROOT=${CMAKE_BINARY_DIR}" -DAG_PHASE=validate-header
            -P "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/RunHostHeaderAggregate.cmake"
        VERBATIM)
    add_custom_command(OUTPUT ${_outputs}
        COMMAND "${CMAKE_COMMAND}" "-DAG_RECIPE=${_recipe}" "-DAG_RECIPE_SHA256=${_hash}"
            "-DAG_BINARY_ROOT=${CMAKE_BINARY_DIR}" -DAG_PHASE=header
            -P "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/RunHostHeaderAggregate.cmake"
        DEPENDS "${_tool}" "${_recipe}" "${_validator}"
            "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/RunHostHeaderAggregate.cmake"
            "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/HostHeaderAggregates.cmake"
            "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/DirectorySetup.cmake"
        COMMENT "Generating source-owned ${HO_HEADER}" VERBATIM)
    add_custom_target("aros-header-aggregate-output-${_id}" DEPENDS ${_outputs})
    add_dependencies("${HO_NAME}" "aros-header-aggregate-output-${_id}")
endfunction()
