include_guard(GLOBAL)

include(CMakeParseArguments)
include("${CMAKE_CURRENT_LIST_DIR}/Executable.cmake")

function(_aros_host_c_file_generator_reject_unsafe_path label value)
    if("${value}" MATCHES "[;\"$\\\\\r\n]" OR
       "${value}" MATCHES "==\\]")
        message(FATAL_ERROR "host C generator: unsafe ${label}: ${value}")
    endif()
endfunction()

# aros_host_c_file_generator(
#     NAME <target> TOOL_SOURCE <absolute-source-file> TOOL_SHA256 <sha256>
#     OUTPUT <absolute-output-under-build-gen>
#     INPUT_DIRECTORY <absolute-local-cache>
#     INPUT_MANIFEST_JSON <[{filename,sha256,size},...]>
#     [SOURCE_MANIFEST_JSON <[{path,sha256},...]>]
#     [COMPILE_FLAGS <bounded-safe-flags...>]
#     ARGUMENTS <literal-safe-token|@INPUT_DIRECTORY@|@OUTPUT_DIRECTORY@...>)
function(aros_host_c_file_generator)
    set(_raw ${ARGN})
    list(FIND _raw ARGUMENTS _marker)
    if(_marker LESS 0)
        message(FATAL_ERROR "aros_host_c_file_generator requires ARGUMENTS")
    endif()
    list(SUBLIST _raw 0 ${_marker} _decl)
    list(SUBLIST _raw ${_marker} -1 _arguments)
    list(REMOVE_AT _arguments 0)

    set(_one NAME TOOL_SOURCE TOOL_SHA256 OUTPUT INPUT_DIRECTORY INPUT_MANIFEST_JSON SOURCE_MANIFEST_JSON)
    cmake_parse_arguments(HCFG "" "${_one}" "COMPILE_FLAGS" ${_decl})
    if(HCFG_UNPARSED_ARGUMENTS OR HCFG_KEYWORDS_MISSING_VALUES)
        message(FATAL_ERROR "aros_host_c_file_generator received malformed arguments")
    endif()
    foreach(_required NAME TOOL_SOURCE TOOL_SHA256 OUTPUT INPUT_DIRECTORY INPUT_MANIFEST_JSON)
        if(NOT DEFINED HCFG_${_required})
            message(FATAL_ERROR "aros_host_c_file_generator requires ${_required}")
        endif()
    endforeach()
    string(LENGTH "${HCFG_NAME}" _name_length)
    if(NOT HCFG_NAME MATCHES "^[A-Za-z0-9_][A-Za-z0-9_.+-]*$" OR _name_length GREATER 64)
        message(FATAL_ERROR "host C generator: unsafe target name '${HCFG_NAME}'")
    endif()
    if(TARGET "${HCFG_NAME}")
        message(FATAL_ERROR "host C generator target '${HCFG_NAME}' already exists")
    endif()
    if(NOT AROS_HOST_CC OR NOT IS_ABSOLUTE "${AROS_HOST_CC}")
        message(FATAL_ERROR "${HCFG_NAME}: AROS_HOST_CC must be an explicit absolute host compiler path")
    endif()
    _aros_host_c_file_generator_reject_unsafe_path("host compiler path" "${AROS_HOST_CC}")
    aros_path_is_executable("${AROS_HOST_CC}" _cc_ok)
    if(NOT _cc_ok)
        message(FATAL_ERROR "${HCFG_NAME}: AROS_HOST_CC is not executable: ${AROS_HOST_CC}")
    endif()
    find_program(_host_cc_file_test NAMES test PATHS /bin /usr/bin NO_DEFAULT_PATH)
    if(NOT _host_cc_file_test)
        message(FATAL_ERROR "${HCFG_NAME}: cannot verify AROS_HOST_CC file type")
    endif()
    execute_process(COMMAND "${_host_cc_file_test}" -f "${AROS_HOST_CC}"
        RESULT_VARIABLE _host_cc_file_result)
    if(NOT _host_cc_file_result EQUAL 0)
        message(FATAL_ERROR "${HCFG_NAME}: AROS_HOST_CC is not a regular file")
    endif()

    foreach(_var HCFG_TOOL_SOURCE HCFG_OUTPUT HCFG_INPUT_DIRECTORY AROS_HOST_CC)
        _aros_host_c_file_generator_reject_unsafe_path("path" "${${_var}}")
        if(NOT IS_ABSOLUTE "${${_var}}")
            message(FATAL_ERROR "${HCFG_NAME}: ${_var} must be absolute")
        endif()
    endforeach()
    string(LENGTH "${HCFG_TOOL_SHA256}" _tool_hash_length)
    if(NOT _tool_hash_length EQUAL 64 OR NOT HCFG_TOOL_SHA256 MATCHES "^[A-Fa-f0-9]+$")
        message(FATAL_ERROR "${HCFG_NAME}: TOOL_SHA256 must be a 64-digit SHA-256")
    endif()
    string(TOLOWER "${HCFG_TOOL_SHA256}" _tool_sha256)

    if(DEFINED AROS_SOURCE_DIR AND NOT "${AROS_SOURCE_DIR}" STREQUAL "")
        set(_source_root "${AROS_SOURCE_DIR}")
    else()
        set(_source_root "${CMAKE_SOURCE_DIR}")
    endif()
    if(NOT IS_ABSOLUTE "${_source_root}" OR NOT EXISTS "${_source_root}" OR
       NOT IS_DIRECTORY "${_source_root}")
        message(FATAL_ERROR "${HCFG_NAME}: AROS_SOURCE_DIR must identify the source root")
    endif()
    cmake_path(NORMAL_PATH _source_root)
    cmake_path(NORMAL_PATH HCFG_TOOL_SOURCE OUTPUT_VARIABLE _tool_source)
    cmake_path(IS_PREFIX _source_root "${_tool_source}" NORMALIZE _tool_owned)
    if(NOT _tool_owned OR _tool_source STREQUAL _source_root)
        message(FATAL_ERROR "${HCFG_NAME}: TOOL_SOURCE must be a source-root descendant")
    endif()
    _aros_host_c_file_generator_check_tree("${_source_root}" "${_tool_source}" "tool source")
    if(NOT EXISTS "${_tool_source}" OR IS_DIRECTORY "${_tool_source}" OR IS_SYMLINK "${_tool_source}")
        message(FATAL_ERROR "${HCFG_NAME}: TOOL_SOURCE must be a regular non-symlink file")
    endif()
    _aros_host_c_file_generator_require_regular("${_tool_source}" "tool source")
    file(SHA256 "${_tool_source}" _actual_hash)
    string(TOLOWER "${_actual_hash}" _actual_hash)
    if(NOT _actual_hash STREQUAL _tool_sha256)
        message(FATAL_ERROR "${HCFG_NAME}: TOOL_SOURCE hash differs from pinned SHA-256")
    endif()

    cmake_path(NORMAL_PATH HCFG_INPUT_DIRECTORY OUTPUT_VARIABLE _input_dir)
    if(NOT EXISTS "${_input_dir}" OR NOT IS_DIRECTORY "${_input_dir}" OR IS_SYMLINK "${_input_dir}")
        message(FATAL_ERROR "${HCFG_NAME}: INPUT_DIRECTORY must be an existing non-symlink directory")
    endif()
    _aros_host_c_file_generator_check_tree("${_input_dir}" "${_input_dir}" "input directory")
    _aros_host_c_file_generator_validate_manifest("${HCFG_INPUT_MANIFEST_JSON}" INPUT
        "${_input_dir}" "input" _input_names _input_hashes _input_sizes)
    _aros_host_c_file_generator_validate_manifest("${HCFG_SOURCE_MANIFEST_JSON}" SOURCE
        "${_source_root}" "source" _source_names _source_hashes _source_sizes)

    cmake_path(NORMAL_PATH CMAKE_BINARY_DIR OUTPUT_VARIABLE _binary_root)
    set(_gen_root "${_binary_root}/gen")
    cmake_path(NORMAL_PATH _gen_root)
    cmake_path(NORMAL_PATH HCFG_OUTPUT OUTPUT_VARIABLE _output)
    cmake_path(IS_PREFIX _gen_root "${_output}" NORMALIZE _output_owned)
    if(NOT _output_owned OR _output STREQUAL _gen_root)
        message(FATAL_ERROR "${HCFG_NAME}: OUTPUT must be a file below ${_gen_root}")
    endif()
    _aros_host_c_file_generator_reject_unsafe_path("output path" "${_output}")
    set(_internal_root "${_gen_root}/.host-c-file-generator")
    cmake_path(IS_PREFIX _internal_root "${_output}" NORMALIZE _reserved_output)
    if(_reserved_output)
        message(FATAL_ERROR "${HCFG_NAME}: OUTPUT uses the private host-generator directory")
    endif()
    get_filename_component(_output_parent "${_output}" DIRECTORY)
    _aros_host_c_file_generator_check_tree("${_binary_root}" "${_output_parent}" "output parent")
    if(IS_SYMLINK "${_output}" OR IS_DIRECTORY "${_output}")
        message(FATAL_ERROR "${HCFG_NAME}: OUTPUT is symlinked or not a regular file: ${_output}")
    endif()
    if(EXISTS "${_output}")
        _aros_host_c_file_generator_require_regular("${_output}" "existing output")
    endif()

    list(LENGTH HCFG_COMPILE_FLAGS _flag_count)
    if(_flag_count GREATER 32)
        message(FATAL_ERROR "${HCFG_NAME}: more than 32 COMPILE_FLAGS were supplied")
    endif()
    set(_flags "")
    foreach(_flag IN LISTS HCFG_COMPILE_FLAGS)
        string(LENGTH "${_flag}" _flag_length)
        set(_flag_ok FALSE)
        if(_flag STREQUAL "-g" OR _flag MATCHES "^-O[0-3s]$" OR
           _flag MATCHES "^-std=(c89|c90|c99|c11|c17|c18|c23|gnu89|gnu90|gnu99|gnu11|gnu17|gnu18|gnu23)$")
            set(_flag_ok TRUE)
        elseif(_flag MATCHES "^-W(no-)?[A-Za-z0-9][A-Za-z0-9_-]*$")
            set(_flag_ok TRUE)
        endif()
        if(NOT _flag_ok OR _flag_length GREATER 80)
            message(FATAL_ERROR "${HCFG_NAME}: unsafe COMPILE_FLAGS token '${_flag}'")
        endif()
        list(APPEND _flags "${_flag}")
    endforeach()

    set(_arguments_checked "")
    set(_input_placeholder_count 0)
    set(_output_placeholder_count 0)
    foreach(_arg IN LISTS _arguments)
        if(_arg STREQUAL "@INPUT_DIRECTORY@")
            math(EXPR _input_placeholder_count "${_input_placeholder_count} + 1")
        elseif(_arg STREQUAL "@OUTPUT_DIRECTORY@")
            math(EXPR _output_placeholder_count "${_output_placeholder_count} + 1")
        elseif(NOT _arg MATCHES "^[A-Za-z0-9_+-][A-Za-z0-9_.+=:-]*$" OR
               _arg MATCHES "\\.\\.")
            message(FATAL_ERROR "${HCFG_NAME}: unsafe generator argument '${_arg}'")
        endif()
        list(APPEND _arguments_checked "${_arg}")
    endforeach()
    if(NOT _input_placeholder_count EQUAL 1 OR NOT _output_placeholder_count EQUAL 1)
        message(FATAL_ERROR "${HCFG_NAME}: ARGUMENTS must contain both directory placeholders exactly once")
    endif()
    get_filename_component(_output_basename "${_output}" NAME)
    if(NOT _output_basename MATCHES "^[A-Za-z0-9][A-Za-z0-9._+-]*$" OR
       _output_basename MATCHES "\\.\\." OR _output_basename MATCHES "[.]$")
        message(FATAL_ERROR "${HCFG_NAME}: OUTPUT must have a portable basename")
    endif()

    string(TOLOWER "${_output}" _output_casefolded)
    string(SHA256 _output_key "${_output_casefolded}")
    get_property(_owner GLOBAL PROPERTY "AROS_HOST_C_FILE_GENERATOR_OWNER_${_output_key}")
    if(_owner)
        message(FATAL_ERROR "${HCFG_NAME}: OUTPUT is already owned by ${_owner}")
    endif()
    string(SHA256 _name_key "${HCFG_NAME}")
    set(_tool_target "aros-host-cfg-tool-${_name_key}")
    if(TARGET "${_tool_target}")
        message(FATAL_ERROR "${HCFG_NAME}: private host-tool target already exists")
    endif()
    set(_private_dir "${_internal_root}/${_name_key}")
    set(_private_tool "${_private_dir}/host-generator${CMAKE_EXECUTABLE_SUFFIX}")
    set(_runner "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/RunHostCFileGenerator.cmake")

    list(LENGTH _flags _flag_count)
    set(_flag_defs "-DCOMPILE_FLAG_COUNT=${_flag_count}")
    if(_flag_count GREATER 0)
        math(EXPR _last "${_flag_count} - 1")
        foreach(_i RANGE 0 ${_last})
            list(GET _flags ${_i} _value)
            list(APPEND _flag_defs "-DCOMPILE_FLAG_${_i}=${_value}")
        endforeach()
    endif()
    list(LENGTH _arguments_checked _arg_count)
    set(_arg_defs "-DGENERATOR_ARGUMENT_COUNT=${_arg_count}")
    if(_arg_count GREATER 0)
        math(EXPR _last "${_arg_count} - 1")
        foreach(_i RANGE 0 ${_last})
            list(GET _arguments_checked ${_i} _value)
            list(APPEND _arg_defs "-DGENERATOR_ARGUMENT_${_i}=${_value}")
        endforeach()
    endif()
    string(SHA256 _contract_key
        "${HCFG_NAME}|${_source_root}|${_tool_sha256}|${_input_dir}|${_output}|${HCFG_INPUT_MANIFEST_JSON}|${HCFG_SOURCE_MANIFEST_JSON}|${AROS_HOST_CC}|${_flags}|${_arguments_checked}")
    list(LENGTH _source_names _source_count)
    set(_source_defs "-DSOURCE_MANIFEST_COUNT=${_source_count}")
    if(_source_count GREATER 0)
        math(EXPR _last "${_source_count} - 1")
        foreach(_i RANGE 0 ${_last})
            list(GET _source_names ${_i} _path)
            list(GET _source_hashes ${_i} _hash)
            list(APPEND _source_defs "-DSOURCE_MANIFEST_PATH_${_i}=${_path}"
                "-DSOURCE_MANIFEST_SHA256_${_i}=${_hash}")
        endforeach()
    endif()
    list(LENGTH _input_names _input_count)
    set(_input_defs "-DINPUT_COUNT=${_input_count}")
    if(_input_count GREATER 0)
        math(EXPR _last "${_input_count} - 1")
        foreach(_i RANGE 0 ${_last})
            list(GET _input_names ${_i} _name)
            list(GET _input_hashes ${_i} _hash)
            list(GET _input_sizes ${_i} _size)
            list(APPEND _input_defs "-DINPUT_FILENAME_${_i}=${_name}"
                "-DINPUT_SHA256_${_i}=${_hash}" "-DINPUT_SIZE_${_i}=${_size}")
        endforeach()
    endif()

    add_custom_command(OUTPUT "${_private_tool}"
        COMMAND "${CMAKE_COMMAND}" "-DMODE=COMPILE" "-DNAME=${HCFG_NAME}"
            "-DHOST_CC=${AROS_HOST_CC}" "-DTOOL_SOURCE=${_tool_source}"
            "-DTOOL_SHA256=${_tool_sha256}" "-DSOURCE_ROOT=${_source_root}"
            "-DBINARY_ROOT=${_binary_root}" "-DPRIVATE_DIRECTORY=${_private_dir}"
            "-DPRIVATE_TOOL=${_private_tool}" ${_flag_defs} ${_source_defs}
            -P "${_runner}"
        DEPENDS "${_tool_source}" "${_runner}"
        COMMENT "Building private host C generator ${HCFG_NAME}"
        VERBATIM)
    add_custom_target("${_tool_target}" DEPENDS "${_private_tool}")
    add_custom_target("${HCFG_NAME}" ALL
        COMMAND "${CMAKE_COMMAND}" "-DMODE=RUN" "-DNAME=${HCFG_NAME}"
            "-DSOURCE_ROOT=${_source_root}" "-DBINARY_ROOT=${_binary_root}"
            "-DTOOL_SOURCE=${_tool_source}" "-DTOOL_SHA256=${_tool_sha256}"
            "-DTOOL_EXECUTABLE=${_private_tool}" "-DINPUT_DIRECTORY=${_input_dir}"
            "-DCONTRACT_KEY=${_contract_key}"
            ${_input_defs} ${_source_defs} "-DOUTPUT=${_output}"
            "-DOUTPUT_BASENAME=${_output_basename}" "-DPRIVATE_DIRECTORY=${_private_dir}"
            ${_arg_defs} -P "${_runner}"
        BYPRODUCTS "${_output}"
        COMMENT "Running sealed host C generator ${HCFG_NAME}"
        VERBATIM)
    add_dependencies("${HCFG_NAME}" "${_tool_target}")
    set_property(GLOBAL PROPERTY "AROS_HOST_C_FILE_GENERATOR_OWNER_${_output_key}" "${HCFG_NAME}")
    set_property(TARGET "${HCFG_NAME}" PROPERTY AROS_HOST_C_FILE_GENERATOR_OUTPUT "${_output}")
    set_property(TARGET "${HCFG_NAME}" PROPERTY AROS_HOST_C_FILE_GENERATOR_TOOL "${_private_tool}")
endfunction()

function(_aros_host_c_file_generator_check_tree root path label)
    cmake_path(NORMAL_PATH root)
    cmake_path(NORMAL_PATH path)
    cmake_path(IS_PREFIX root "${path}" NORMALIZE _inside)
    if(NOT _inside)
        message(FATAL_ERROR
            "host C generator: ${label} escapes its root: ${path}")
    endif()
    set(_cursor "${path}")
    while(TRUE)
        if(IS_SYMLINK "${_cursor}")
            message(FATAL_ERROR
                "host C generator: ${label} has a symlinked path component: ${_cursor}")
        endif()
        cmake_path(GET _cursor PARENT_PATH _parent)
        if(_parent STREQUAL _cursor)
            break()
        endif()
        set(_cursor "${_parent}")
    endwhile()
    cmake_path(RELATIVE_PATH path BASE_DIRECTORY "${root}"
        OUTPUT_VARIABLE _relative)
    set(_cursor "${root}")
    if(NOT _relative STREQUAL "")
        string(REPLACE "/" ";" _components "${_relative}")
        foreach(_component IN LISTS _components)
            set(_cursor "${_cursor}/${_component}")
        endforeach()
    endif()
endfunction()

function(_aros_host_c_file_generator_require_regular path label)
    if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}" OR IS_SYMLINK "${path}")
        message(FATAL_ERROR "host C generator: ${label} is missing or unsafe: ${path}")
    endif()
    find_program(_regular_file_test NAMES test PATHS /bin /usr/bin NO_DEFAULT_PATH)
    if(NOT _regular_file_test)
        message(FATAL_ERROR "host C generator: cannot verify regular-file type for ${label}")
    endif()
    execute_process(COMMAND "${_regular_file_test}" -f "${path}"
        RESULT_VARIABLE _regular_file_result)
    if(NOT _regular_file_result EQUAL 0)
        message(FATAL_ERROR "host C generator: ${label} is not a regular file: ${path}")
    endif()
endfunction()

function(_aros_host_c_file_generator_validate_manifest json mode root label
        out_paths out_hashes out_sizes)
    if("${json}" STREQUAL "")
        set(json "[]")
    endif()
    string(JSON _kind ERROR_VARIABLE _json_error TYPE "${json}")
    if(NOT _json_error STREQUAL "NOTFOUND" OR NOT _kind STREQUAL "ARRAY")
        message(FATAL_ERROR "host C generator: ${label} manifest must be a JSON array")
    endif()
    string(JSON _count LENGTH "${json}")
    if(mode STREQUAL "INPUT" AND _count GREATER 16)
        message(FATAL_ERROR "host C generator: input manifest has more than 16 entries")
    elseif(mode STREQUAL "SOURCE" AND _count GREATER 128)
        message(FATAL_ERROR "host C generator: source manifest has more than 128 entries")
    endif()

    set(_paths "")
    set(_folded_paths "")
    set(_hashes "")
    set(_sizes "")
    if(_count GREATER 0)
        math(EXPR _last "${_count} - 1")
        foreach(_index RANGE 0 ${_last})
            string(JSON _entry_type ERROR_VARIABLE _entry_error TYPE "${json}" ${_index})
            if(NOT _entry_error STREQUAL "NOTFOUND" OR
               NOT _entry_type STREQUAL "OBJECT")
                message(FATAL_ERROR "host C generator: ${label} entry ${_index} is not an object")
            endif()
            string(JSON _members LENGTH "${json}" ${_index})
            if(mode STREQUAL "INPUT")
                if(NOT _members EQUAL 3)
                    message(FATAL_ERROR
                        "host C generator: input entry ${_index} must contain filename, sha256, and size")
                endif()
                set(_name_key filename)
            else()
                if(NOT _members EQUAL 2)
                    message(FATAL_ERROR
                        "host C generator: source entry ${_index} must contain path and sha256")
                endif()
                set(_name_key path)
            endif()
            string(JSON _name_type ERROR_VARIABLE _name_error TYPE "${json}" ${_index} "${_name_key}")
            string(JSON _hash_type ERROR_VARIABLE _hash_error TYPE "${json}" ${_index} sha256)
            if(NOT _name_error STREQUAL "NOTFOUND" OR
               NOT _hash_error STREQUAL "NOTFOUND" OR
               NOT _name_type STREQUAL "STRING" OR
               NOT _hash_type STREQUAL "STRING")
                message(FATAL_ERROR "host C generator: malformed ${label} entry ${_index}")
            endif()
            string(JSON _name GET "${json}" ${_index} "${_name_key}")
            string(JSON _hash GET "${json}" ${_index} sha256)
            string(TOLOWER "${_hash}" _hash)
            string(LENGTH "${_hash}" _hash_length)
            if(NOT _hash_length EQUAL 64 OR NOT _hash MATCHES "^[0-9a-f]+$")
                message(FATAL_ERROR "host C generator: malformed SHA-256 in ${label} entry ${_index}")
            endif()
            if(mode STREQUAL "INPUT")
                if(NOT _name MATCHES "^[A-Za-z0-9][A-Za-z0-9._+-]*$" OR
                   _name MATCHES "\\.\\." OR _name MATCHES "[.]$")
                    message(FATAL_ERROR "host C generator: nonportable input filename '${_name}'")
                endif()
                string(TOLOWER "${_name}" _folded_name)
                if(_folded_name IN_LIST _folded_paths)
                    message(FATAL_ERROR "host C generator: duplicate case-folded input filename '${_name}'")
                endif()
                list(APPEND _folded_paths "${_folded_name}")
                string(REGEX REPLACE "[.].*$" "" _name_stem "${_folded_name}")
                if(_name_stem MATCHES "^(con|prn|aux|nul|com[1-9]|lpt[1-9])$")
                    message(FATAL_ERROR "host C generator: nonportable input filename '${_name}'")
                endif()
                string(JSON _size_type ERROR_VARIABLE _size_error TYPE "${json}" ${_index} size)
                string(JSON _size GET "${json}" ${_index} size)
                string(LENGTH "${_size}" _size_length)
                if(NOT _size_error STREQUAL "NOTFOUND" OR
                   NOT _size_type STREQUAL "NUMBER" OR
                   NOT _size MATCHES "^[0-9]+$" OR _size_length GREATER 8)
                    message(FATAL_ERROR "host C generator: invalid size for input '${_name}'")
                endif()
                if(_size LESS 1 OR _size GREATER 33554432)
                    message(FATAL_ERROR
                        "host C generator: input '${_name}' exceeds 32 MiB")
                endif()
            else()
                if(NOT _name MATCHES "^[A-Za-z0-9_.+-]+(/[A-Za-z0-9_.+-]+)*$" OR
                   _name MATCHES "(^|/)\\.\\.?(/|$)" OR _name MATCHES "[.]$")
                    message(FATAL_ERROR "host C generator: nonportable source path '${_name}'")
                endif()
                set(_size "")
            endif()
            if(mode STREQUAL "SOURCE")
                string(TOLOWER "${_name}" _folded_path)
                if(_folded_path IN_LIST _folded_paths)
                    message(FATAL_ERROR "host C generator: duplicate ${label} path '${_name}'")
                endif()
                list(APPEND _folded_paths "${_folded_path}")
            endif()
            list(APPEND _paths "${_name}")
            list(APPEND _hashes "${_hash}")
            list(APPEND _sizes "${_size}")

            set(_source "${root}/${_name}")
            cmake_path(NORMAL_PATH _source)
            _aros_host_c_file_generator_check_tree("${root}" "${_source}" "${label} path")
            _aros_host_c_file_generator_require_regular("${_source}" "${label} file '${_name}'")
            file(SIZE "${_source}" _actual_size)
            file(SHA256 "${_source}" _actual_hash)
            string(TOLOWER "${_actual_hash}" _actual_hash)
            if(mode STREQUAL "INPUT" AND NOT _actual_size EQUAL _size)
                message(FATAL_ERROR "host C generator: size mismatch for input '${_name}'")
            endif()
            if(NOT _actual_hash STREQUAL _hash)
                message(FATAL_ERROR "host C generator: SHA-256 mismatch for ${label} file '${_name}'")
            endif()
        endforeach()
    endif()

    set(${out_paths} "${_paths}" PARENT_SCOPE)
    set(${out_hashes} "${_hashes}" PARENT_SCOPE)
    set(${out_sizes} "${_sizes}" PARENT_SCOPE)
endfunction()
