# Source-scoped Make values supplied by the transpiler for a full module KOBJ.
# This records source facts only; it does not resolve config or build inputs.
include_guard(GLOBAL)
include(CMakeParseArguments)

function(_aros_module_kobj_fail _message)
    message(FATAL_ERROR "Source module KOBJ inputs: ${_message}")
endfunction()

function(_aros_module_kobj_require_type _json _expected)
    string(JSON _actual ERROR_VARIABLE _error TYPE "${_json}" ${ARGN})
    if(NOT "${_error}" STREQUAL "NOTFOUND")
        _aros_module_kobj_fail("invalid JSON value at '${ARGN}': ${_error}")
    endif()
    if(NOT "${_actual}" STREQUAL "${_expected}")
        _aros_module_kobj_fail("expected ${_expected} at '${ARGN}', found ${_actual}")
    endif()
endfunction()

function(_aros_module_kobj_assert_keys _json)
    set(_segments ${ARGN})
    list(FIND _segments "--" _separator)
    if(_separator LESS 0)
        _aros_module_kobj_fail("internal schema check omitted its key boundary")
    endif()
    list(SUBLIST _segments 0 ${_separator} _path)
    math(EXPR _expected_start "${_separator} + 1")
    list(SUBLIST _segments ${_expected_start} -1 _expected_keys)

    string(JSON _count ERROR_VARIABLE _error LENGTH "${_json}" ${_path})
    if(NOT "${_error}" STREQUAL "NOTFOUND")
        _aros_module_kobj_fail("cannot enumerate object keys at '${_path}': ${_error}")
    endif()
    list(LENGTH _expected_keys _expected_count)
    if(NOT _count EQUAL _expected_count)
        _aros_module_kobj_fail("missing or unexpected object key at '${_path}'")
    endif()

    set(_seen_keys)
    if(_count GREATER 0)
        math(EXPR _last "${_count} - 1")
        foreach(_index RANGE 0 ${_last})
            string(JSON _key ERROR_VARIABLE _error MEMBER "${_json}" ${_path} ${_index})
            if(NOT "${_error}" STREQUAL "NOTFOUND")
                _aros_module_kobj_fail("cannot read an object key at '${_path}': ${_error}")
            endif()
            if(NOT _key IN_LIST _expected_keys)
                _aros_module_kobj_fail("unexpected object key '${_key}' at '${_path}'")
            endif()
            if(_key IN_LIST _seen_keys)
                _aros_module_kobj_fail("duplicate object key '${_key}' at '${_path}'")
            endif()
            list(APPEND _seen_keys "${_key}")
        endforeach()
    endif()
    foreach(_key IN LISTS _expected_keys)
        if(NOT _key IN_LIST _seen_keys)
            _aros_module_kobj_fail("missing object key '${_key}' at '${_path}'")
        endif()
    endforeach()
endfunction()

function(_aros_module_kobj_get _out _json)
    string(JSON _value ERROR_VARIABLE _error GET "${_json}" ${ARGN})
    if(NOT "${_error}" STREQUAL "NOTFOUND")
        _aros_module_kobj_fail("cannot read JSON value at '${ARGN}': ${_error}")
    endif()
    set(${_out} "${_value}" PARENT_SCOPE)
endfunction()

function(_aros_module_kobj_require_nullable_string _json)
    string(JSON _type ERROR_VARIABLE _error TYPE "${_json}" ${ARGN})
    if(NOT "${_error}" STREQUAL "NOTFOUND")
        _aros_module_kobj_fail("invalid nullable string at '${ARGN}': ${_error}")
    endif()
    if(NOT _type STREQUAL "NULL" AND NOT _type STREQUAL "STRING")
        _aros_module_kobj_fail("expected null or string at '${ARGN}', found ${_type}")
    endif()
endfunction()

function(_aros_module_kobj_assert_cmake_atom _value _label)
    string(FIND "${_value}" ";" _semicolon)
    string(FIND "${_value}" "\n" _newline)
    string(FIND "${_value}" "\r" _carriage_return)
    string(FIND "${_value}" "$" _dollar)
    string(FIND "${_value}" "\\" _backslash)
    if(NOT _semicolon EQUAL -1 OR NOT _newline EQUAL -1 OR
       NOT _carriage_return EQUAL -1 OR NOT _dollar EQUAL -1 OR
       NOT _backslash EQUAL -1)
        _aros_module_kobj_fail("unsafe CMake list representation for ${_label}")
    endif()
endfunction()

function(_aros_module_kobj_validate_relative_path _path _label)
    if("${_path}" STREQUAL "")
        _aros_module_kobj_fail("${_label} must be a nonempty source-relative path")
    endif()
    _aros_module_kobj_assert_cmake_atom("${_path}" "${_label}")
    string(FIND "${_path}" ":" _colon)
    if(NOT _colon EQUAL -1)
        _aros_module_kobj_fail("${_label} must be a source-relative path")
    endif()
    string(REPLACE "/" ";" _components "${_path}")
    foreach(_component IN LISTS _components)
        if(_component STREQUAL "" OR _component STREQUAL "." OR _component STREQUAL "..")
            _aros_module_kobj_fail("${_label} is not a safe source-relative path")
        endif()
    endforeach()
endfunction()

function(_aros_module_kobj_validate_sources _json _field)
    _aros_module_kobj_require_type("${_json}" ARRAY "${_field}" source)
    string(JSON _count ERROR_VARIABLE _error LENGTH "${_json}" "${_field}" source)
    if(NOT "${_error}" STREQUAL "NOTFOUND")
        _aros_module_kobj_fail("cannot read source references for '${_field}': ${_error}")
    endif()
    if(_count GREATER 0)
        math(EXPR _last "${_count} - 1")
        foreach(_index RANGE 0 ${_last})
            _aros_module_kobj_require_type("${_json}" OBJECT "${_field}" source "${_index}")
            _aros_module_kobj_assert_keys("${_json}" "${_field}" source "${_index}" -- path line)
            _aros_module_kobj_require_type("${_json}" STRING "${_field}" source "${_index}" path)
            _aros_module_kobj_get(_path "${_json}" "${_field}" source "${_index}" path)
            _aros_module_kobj_validate_relative_path("${_path}" "source reference path")
            _aros_module_kobj_require_type("${_json}" NUMBER "${_field}" source "${_index}" line)
            _aros_module_kobj_get(_line "${_json}" "${_field}" source "${_index}" line)
            if(NOT "${_line}" MATCHES "^[1-9][0-9]*$")
                _aros_module_kobj_fail("source reference line must be a positive integer")
            endif()
        endforeach()
    endif()
endfunction()

function(_aros_module_kobj_validate_words _json _field)
    _aros_module_kobj_require_type("${_json}" OBJECT "${_field}")
    _aros_module_kobj_require_type("${_json}" STRING "${_field}" state)
    _aros_module_kobj_get(_state "${_json}" "${_field}" state)
    if(_state STREQUAL "known_empty")
        _aros_module_kobj_assert_keys("${_json}" "${_field}" -- state raw source)
        _aros_module_kobj_require_nullable_string("${_json}" "${_field}" raw)
        _aros_module_kobj_validate_sources("${_json}" "${_field}")
    elseif(_state STREQUAL "exact")
        _aros_module_kobj_assert_keys("${_json}" "${_field}" -- state raw words source)
        _aros_module_kobj_require_type("${_json}" STRING "${_field}" raw)
        _aros_module_kobj_require_type("${_json}" ARRAY "${_field}" words)
        string(JSON _word_count ERROR_VARIABLE _error LENGTH "${_json}" "${_field}" words)
        if(NOT "${_error}" STREQUAL "NOTFOUND")
            _aros_module_kobj_fail("cannot read words for '${_field}': ${_error}")
        endif()
        if(_word_count LESS 1)
            _aros_module_kobj_fail("exact words for '${_field}' must be nonempty")
        endif()
        math(EXPR _last "${_word_count} - 1")
        foreach(_index RANGE 0 ${_last})
            _aros_module_kobj_require_type("${_json}" STRING "${_field}" words "${_index}")
            _aros_module_kobj_get(_word "${_json}" "${_field}" words "${_index}")
            if(_word STREQUAL "")
                _aros_module_kobj_fail("exact words for '${_field}' cannot contain an empty CMake list element")
            endif()
            _aros_module_kobj_assert_cmake_atom("${_word}" "word in '${_field}'")
        endforeach()
        _aros_module_kobj_validate_sources("${_json}" "${_field}")
    elseif(_state STREQUAL "unresolved")
        _aros_module_kobj_assert_keys("${_json}" "${_field}" -- state raw reason source)
        _aros_module_kobj_require_nullable_string("${_json}" "${_field}" raw)
        _aros_module_kobj_require_type("${_json}" STRING "${_field}" reason)
        _aros_module_kobj_get(_reason "${_json}" "${_field}" reason)
        if(_reason STREQUAL "")
            _aros_module_kobj_fail("unresolved '${_field}' requires a nonempty reason")
        endif()
        _aros_module_kobj_validate_sources("${_json}" "${_field}")
    else()
        _aros_module_kobj_fail("unknown state '${_state}' for '${_field}'")
    endif()
endfunction()

function(_aros_module_kobj_validate_json _json)
    string(JSON _root_type ERROR_VARIABLE _error TYPE "${_json}")
    if(NOT "${_error}" STREQUAL "NOTFOUND")
        _aros_module_kobj_fail("invalid JSON: ${_error}")
    endif()
    if(NOT _root_type STREQUAL "OBJECT")
        _aros_module_kobj_fail("top-level value must be an object")
    endif()
    set(_root_keys defname declaration_line scoped_declaration_line included_make_opts user_objects defname_libs user_ldflags use_libs kobj_ldflags kernel_kobj_ldscript funcinstr_libs function_instrumentation)
    set(_include_fields included_make_opts)
    string(JSON _configuration_type ERROR_VARIABLE _configuration_error TYPE "${_json}" included_configuration_files)
    if("${_configuration_error}" STREQUAL "NOTFOUND")
        list(APPEND _root_keys included_configuration_files)
        list(APPEND _include_fields included_configuration_files)
    endif()
    _aros_module_kobj_assert_keys("${_json}" -- ${_root_keys})

    _aros_module_kobj_require_type("${_json}" STRING defname)
    _aros_module_kobj_get(_defname "${_json}" defname)
    if(NOT "${_defname}" MATCHES "^[A-Za-z0-9_][A-Za-z0-9_.+-]*$" OR
       _defname STREQUAL "." OR _defname STREQUAL "..")
        _aros_module_kobj_fail("defname must be a nonempty safe identifier")
    endif()

    foreach(_line_field IN ITEMS declaration_line scoped_declaration_line)
        _aros_module_kobj_require_type("${_json}" NUMBER "${_line_field}")
        _aros_module_kobj_get(_line "${_json}" "${_line_field}")
        if(NOT "${_line}" MATCHES "^(0|[1-9][0-9]*)$")
            _aros_module_kobj_fail("${_line_field} must be a zero-based non-negative integer")
        endif()
    endforeach()

    foreach(_include_field IN LISTS _include_fields)
        _aros_module_kobj_require_type("${_json}" ARRAY "${_include_field}")
        string(JSON _include_count ERROR_VARIABLE _error LENGTH "${_json}" "${_include_field}")
        if(NOT "${_error}" STREQUAL "NOTFOUND")
            _aros_module_kobj_fail("cannot read ${_include_field}: ${_error}")
        endif()
        if(_include_count GREATER 0)
            math(EXPR _last "${_include_count} - 1")
            foreach(_index RANGE 0 ${_last})
                _aros_module_kobj_require_type("${_json}" OBJECT "${_include_field}" "${_index}")
                _aros_module_kobj_assert_keys("${_json}" "${_include_field}" "${_index}" -- tag path)
                _aros_module_kobj_require_nullable_string("${_json}" "${_include_field}" "${_index}" tag)
                _aros_module_kobj_require_type("${_json}" STRING "${_include_field}" "${_index}" path)
                _aros_module_kobj_get(_path "${_json}" "${_include_field}" "${_index}" path)
                _aros_module_kobj_validate_relative_path("${_path}" "included source path")
            endforeach()
        endif()
    endforeach()

    foreach(_field IN ITEMS user_objects defname_libs user_ldflags use_libs kobj_ldflags kernel_kobj_ldscript funcinstr_libs function_instrumentation)
        _aros_module_kobj_validate_words("${_json}" "${_field}")
    endforeach()
endfunction()

function(aros_record_module_kobj_inputs)
    cmake_parse_arguments(PARSE_ARGV 0 KMI "" "OWNER;JSON" "")
    if(KMI_UNPARSED_ARGUMENTS OR KMI_KEYWORDS_MISSING_VALUES OR
       NOT "${KMI_OWNER}" MATCHES "^[A-Za-z0-9_.+-]+$" OR
       "${KMI_JSON}" STREQUAL "")
        _aros_module_kobj_fail("expected OWNER <exact target> JSON <serialized KobjScopedInputs>")
    endif()
    # Like source-group registration, this opt-in contract must not impose
    # unused partial-link input restrictions on an ordinary runtime build.
    if(NOT AROS_NATIVE_BUILD_CONTRACT)
        return()
    endif()

    get_property(_macro_recorded GLOBAL PROPERTY "AROS_MODULE_MACRO_${KMI_OWNER}" SET)
    if(NOT _macro_recorded)
        _aros_module_kobj_fail("owner '${KMI_OWNER}' has no registered source module macro")
    endif()
    get_property(_macro_form GLOBAL PROPERTY "AROS_MODULE_MACRO_${KMI_OWNER}")
    if(NOT _macro_form MATCHES "^(full|runtime-only|simple)$")
        _aros_module_kobj_fail("owner '${KMI_OWNER}' has unsupported source module macro form '${_macro_form}'")
    endif()

    get_property(_already_recorded GLOBAL PROPERTY "AROS_MODULE_KOBJ_INPUTS_${KMI_OWNER}" SET)
    if(_already_recorded)
        _aros_module_kobj_fail("duplicate source KOBJ inputs for owner '${KMI_OWNER}'")
    endif()

    _aros_module_kobj_validate_json("${KMI_JSON}")
    set_property(GLOBAL PROPERTY "AROS_MODULE_KOBJ_INPUTS_${KMI_OWNER}" "${KMI_JSON}")
endfunction()

function(aros_get_module_kobj_words _out _owner _field)
    if(ARGC LESS 3 OR ARGC GREATER 3 OR
       NOT "${_out}" MATCHES "^[A-Za-z_][A-Za-z0-9_]*$" OR
       NOT "${_owner}" MATCHES "^[A-Za-z0-9_.+-]+$" OR
       NOT "${_field}" MATCHES "^(user_objects|defname_libs|user_ldflags|use_libs|kobj_ldflags|kernel_kobj_ldscript|funcinstr_libs|function_instrumentation)$")
        _aros_module_kobj_fail("get requires a safe output variable, owner, and one supported field")
    endif()
    get_property(_recorded GLOBAL PROPERTY "AROS_MODULE_KOBJ_INPUTS_${_owner}" SET)
    if(NOT _recorded)
        _aros_module_kobj_fail("owner '${_owner}' has no recorded source KOBJ inputs")
    endif()
    get_property(_json GLOBAL PROPERTY "AROS_MODULE_KOBJ_INPUTS_${_owner}")
    _aros_module_kobj_get(_state "${_json}" "${_field}" state)
    if(_state STREQUAL "unresolved")
        _aros_module_kobj_get(_reason "${_json}" "${_field}" reason)
        _aros_module_kobj_fail("cannot consume unresolved '${_field}' for '${_owner}': ${_reason}")
    elseif(_state STREQUAL "known_empty")
        set(${_out} "" PARENT_SCOPE)
    elseif(_state STREQUAL "exact")
        string(JSON _count ERROR_VARIABLE _error LENGTH "${_json}" "${_field}" words)
        if(NOT "${_error}" STREQUAL "NOTFOUND" OR _count LESS 1)
            _aros_module_kobj_fail("recorded exact '${_field}' for '${_owner}' is malformed")
        endif()
        set(_words)
        math(EXPR _last "${_count} - 1")
        foreach(_index RANGE 0 ${_last})
            _aros_module_kobj_require_type("${_json}" STRING "${_field}" words "${_index}")
            _aros_module_kobj_get(_word "${_json}" "${_field}" words "${_index}")
            if(_word STREQUAL "")
                _aros_module_kobj_fail("recorded exact '${_field}' for '${_owner}' contains an empty word")
            endif()
            _aros_module_kobj_assert_cmake_atom("${_word}" "word in '${_field}'")
            list(APPEND _words "${_word}")
        endforeach()
        set(${_out} "${_words}" PARENT_SCOPE)
    else()
        _aros_module_kobj_fail("recorded '${_field}' for '${_owner}' has unknown state '${_state}'")
    endif()
endfunction()
