# Source-macro-shaped, shell-free GNU KOBJ partial links.
#
# This module is deliberately opt-in. A caller must supply the already-resolved
# source-owned object groups; this module does not read Make outputs or infer
# module membership.

include_guard(GLOBAL)
include(CMakeParseArguments)
include("${CMAKE_CURRENT_LIST_DIR}/NativeCore.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/ModuleMacroContract.cmake")

function(_aros_native_kobj_is_unsafe out_var value)
    set(_unsafe FALSE)
    if("${value}" MATCHES "[;\"$|]" OR "${value}" MATCHES "[\r\n]")
        set(_unsafe TRUE)
    endif()
    string(FIND "${value}" "\\" _backslash)
    if(NOT _backslash EQUAL -1)
        set(_unsafe TRUE)
    endif()
    set(${out_var} "${_unsafe}" PARENT_SCOPE)
endfunction()

function(_aros_native_kobj_valid_owner value label)
    _aros_native_kobj_is_unsafe(_unsafe "${value}")
    if("${value}" STREQUAL "" OR _unsafe OR
       NOT "${value}" MATCHES "^[A-Za-z0-9_.:+-]+$")
        message(FATAL_ERROR "Native KOBJ ${label} is invalid: '${value}'")
    endif()
endfunction()

function(_aros_native_kobj_valid_arg value label)
    _aros_native_kobj_is_unsafe(_unsafe "${value}")
    if("${value}" STREQUAL "" OR _unsafe OR
       NOT "${value}" MATCHES "^[A-Za-z0-9_./,:=+@%+-]+$")
        message(FATAL_ERROR "Native KOBJ ${label} is not a safe literal argument: '${value}'")
    endif()
    if("${value}" STREQUAL "-o" OR "${value}" MATCHES "^-o.+$" OR
       "${value}" MATCHES "^--output($|=)" OR
       "${value}" MATCHES "(^|,)-o(,|$)" OR "${value}" MATCHES "^@")
        message(FATAL_ERROR
            "Native KOBJ ${label} may not replace the helper-owned output or use a response file: '${value}'")
    endif()
endfunction()

function(_aros_native_kobj_check_tool out_var value label)
    _aros_native_kobj_is_unsafe(_unsafe "${value}")
    if(NOT IS_ABSOLUTE "${value}" OR _unsafe OR
       NOT EXISTS "${value}" OR IS_DIRECTORY "${value}")
        message(FATAL_ERROR
            "Native KOBJ ${label} must be an existing absolute tool path: '${value}'")
    endif()
    file(REAL_PATH "${value}" _tool)
    if(NOT EXISTS "${_tool}" OR IS_DIRECTORY "${_tool}")
        message(FATAL_ERROR "Native KOBJ ${label} does not resolve to a file: '${value}'")
    endif()
    set(${out_var} "${_tool}" PARENT_SCOPE)
endfunction()

function(_aros_native_kobj_check_build_directory out_var value label)
    _aros_native_kobj_is_unsafe(_unsafe "${value}")
    if(NOT IS_ABSOLUTE "${value}" OR _unsafe)
        message(FATAL_ERROR
            "Native KOBJ ${label} must be a safe absolute build-tree directory: '${value}'")
    endif()
    cmake_path(ABSOLUTE_PATH value NORMALIZE OUTPUT_VARIABLE _path)
    cmake_path(ABSOLUTE_PATH CMAKE_BINARY_DIR NORMALIZE OUTPUT_VARIABLE _build_root)
    cmake_path(IS_PREFIX _build_root "${_path}" NORMALIZE _inside)
    if(NOT _inside OR _path STREQUAL _build_root)
        message(FATAL_ERROR
            "Native KOBJ ${label} escapes the build tree or names its root: ${_path}")
    endif()
    if(EXISTS "${_path}" AND NOT IS_DIRECTORY "${_path}")
        message(FATAL_ERROR "Native KOBJ ${label} is not a directory: ${_path}")
    endif()

    file(REAL_PATH "${_build_root}" _build_root_real)
    set(_probe "${_path}")
    while(NOT EXISTS "${_probe}" AND NOT IS_SYMLINK "${_probe}")
        get_filename_component(_parent "${_probe}" DIRECTORY)
        if(_parent STREQUAL _probe)
            break()
        endif()
        set(_probe "${_parent}")
    endwhile()
    file(REAL_PATH "${_probe}" _probe_real)
    cmake_path(IS_PREFIX _build_root_real "${_probe_real}" NORMALIZE _physical_inside)
    if(NOT _physical_inside)
        message(FATAL_ERROR
            "Native KOBJ ${label} escapes the physical build tree through a symlink: ${_path}")
    endif()
    set(${out_var} "${_path}" PARENT_SCOPE)
endfunction()

function(_aros_native_kobj_check_input out_path out_dep raw label generated_deps)
    _aros_native_kobj_is_unsafe(_unsafe "${raw}")
    if(NOT IS_ABSOLUTE "${raw}" OR _unsafe)
        message(FATAL_ERROR
            "Native KOBJ ${label} must be an absolute safe input path: '${raw}'")
    endif()
    cmake_path(ABSOLUTE_PATH raw NORMALIZE OUTPUT_VARIABLE _path)
    cmake_path(ABSOLUTE_PATH CMAKE_BINARY_DIR NORMALIZE OUTPUT_VARIABLE _build_root)
    cmake_path(ABSOLUTE_PATH CMAKE_SOURCE_DIR NORMALIZE OUTPUT_VARIABLE _source_root)
    file(REAL_PATH "${_build_root}" _build_root_real)
    file(REAL_PATH "${_source_root}" _source_root_real)

    if(EXISTS "${_path}")
        if(IS_DIRECTORY "${_path}")
            message(FATAL_ERROR "Native KOBJ ${label} names a directory: ${_path}")
        endif()
        file(REAL_PATH "${_path}" _real)
        cmake_path(IS_PREFIX _build_root_real "${_real}" NORMALIZE _in_build)
        cmake_path(IS_PREFIX _source_root_real "${_real}" NORMALIZE _in_source)
        if(NOT _in_build AND NOT _in_source)
            message(FATAL_ERROR
                "Native KOBJ ${label} escapes the source and build trees through a symlink: ${_path}")
        endif()
    else()
        if(NOT _path IN_LIST generated_deps)
            message(FATAL_ERROR
                "Native KOBJ ${label} is missing and is not an exact DEPENDS path: ${_path}")
        endif()
        cmake_path(IS_PREFIX _build_root "${_path}" NORMALIZE _in_build)
        if(NOT _in_build)
            message(FATAL_ERROR
                "Native KOBJ generated ${label} is outside the build tree: ${_path}")
        endif()
        get_source_file_property(_generated "${_path}" GENERATED)
        if(NOT _generated)
            message(FATAL_ERROR
                "Native KOBJ generated ${label} is not marked GENERATED: ${_path}")
        endif()
    endif()

    set(${out_path} "${_path}" PARENT_SCOPE)
    set(${out_dep} "${_path}" PARENT_SCOPE)
endfunction()

function(_aros_native_kobj_reject_output_alias owner input label output stage report)
    if(NOT EXISTS "${input}" OR IS_DIRECTORY "${input}")
        return()
    endif()
    file(REAL_PATH "${input}" _input_real)
    foreach(_output_candidate IN ITEMS "${output}" "${stage}" "${report}")
        if(_output_candidate STREQUAL "")
            continue()
        endif()
        cmake_path(ABSOLUTE_PATH _output_candidate NORMALIZE
            OUTPUT_VARIABLE _output_normalized)
        if(EXISTS "${_output_normalized}")
            file(REAL_PATH "${_output_normalized}" _output_real)
        else()
            set(_output_real "${_output_normalized}")
        endif()
        if(_input_real STREQUAL _output_real)
            message(FATAL_ERROR
                "Native KOBJ ${owner} ${label} resolves to its output/staging path: ${input}")
        endif()
    endforeach()
endfunction()

function(_aros_native_kobj_json_set_string json_var key value)
    string(JSON _json SET "${${json_var}}" "${key}" "\"${value}\"")
    set(${json_var} "${_json}" PARENT_SCOPE)
endfunction()

function(_aros_native_kobj_json_set_array json_var key)
    string(JSON _json SET "${${json_var}}" "${key}" "[]")
    set(_index 0)
    foreach(_value IN LISTS ARGN)
        string(JSON _json SET "${_json}" "${key}" ${_index} "\"${_value}\"")
        math(EXPR _index "${_index} + 1")
    endforeach()
    set(${json_var} "${_json}" PARENT_SCOPE)
endfunction()

function(_aros_native_kobj_resolve_flag_libraries out_var owner)
    set(_resolved "")
    set(_expect_library FALSE)
    foreach(_arg IN LISTS ARGN)
        if(_expect_library)
            set(_library "${_arg}")
            set(_expect_library FALSE)
        elseif(_arg STREQUAL "-l")
            set(_expect_library TRUE)
            continue()
        elseif(_arg MATCHES "^-l(.+)$")
            set(_library "${CMAKE_MATCH_1}")
        else()
            continue()
        endif()
        _aros_native_kobj_valid_owner("${_library}" "${owner} flag library")
        aros_resolve_native_core_linklib(_target "${_library}")
        if(NOT _target IN_LIST _resolved)
            list(APPEND _resolved "${_target}")
        endif()
    endforeach()
    if(_expect_library)
        message(FATAL_ERROR "Native KOBJ ${owner} has a dangling -l flag")
    endif()
    set(${out_var} "${_resolved}" PARENT_SCOPE)
endfunction()

function(_aros_native_kobj_validate_link_flags owner label)
    set(_expect_emulation FALSE)
    foreach(_arg IN LISTS ARGN)
        _aros_native_kobj_valid_arg("${_arg}" "${owner} ${label}")
        if(_expect_emulation)
            if(NOT "${_arg}" MATCHES "^[A-Za-z0-9_.+-]+$")
                message(FATAL_ERROR
                    "Native KOBJ ${owner} ${label} has an unsafe -m emulation: ${_arg}")
            endif()
            set(_expect_emulation FALSE)
            continue()
        endif()
        if(_arg STREQUAL "-m")
            set(_expect_emulation TRUE)
        elseif(_arg MATCHES "^(--allow-multiple-definition|--emit-relocs|--no-undefined|--gc-sections|--warn-common|--fatal-warnings|-static)$" OR
               _arg MATCHES "^--build-id=(none|sha1|uuid|0x[0-9A-Fa-f]+)$")
            continue()
        else()
            message(FATAL_ERROR
                "Native KOBJ ${owner} ${label} uses unsupported linker option: ${_arg}")
        endif()
    endforeach()
    if(_expect_emulation)
        message(FATAL_ERROR "Native KOBJ ${owner} ${label} has -m without an emulation")
    endif()
endfunction()

# aros_add_native_kobj(NAME <target> OWNER <mmake> FORM <full|simple>
#     OUTPUT <absolute-build-path> LINKER <path> COLLECTOR <path>
#     NM <path> OBJCOPY <path> LIBDIR <absolute-build-dir>
#     [START_OBJECTS ...] [ARCH_OBJECTS ...] [ASM_OBJECTS ...]
#     [C_OBJECTS ...] [CXX_OBJECTS ...] [USER_OBJECTS ...]
#     [END_OBJECTS ...] [USELIBS ...] [DEFNAME_LIBS ...]
#     [KOBJ_FLAGS ...] [USER_FLAGS ...] [LDSCRIPT ...] [DEPENDS ...])
#
# `full` group order is START, ARCH, ASM, C, CXX, USER, END. `simple` is ARCH,
# C only; groups that its source macro does not define are rejected. Object
# entries are existing absolute files or `$<TARGET_OBJECTS:object-library>`.
# The source recipe uses `$^`, so repeated object prerequisites are retained
# once at their first position. Library repetitions are intentionally kept.
function(aros_add_native_kobj)
    set(oneValueArgs NAME OWNER FORM OUTPUT LINKER COLLECTOR NM OBJCOPY LIBDIR)
    set(multiValueArgs START_OBJECTS ARCH_OBJECTS ASM_OBJECTS C_OBJECTS
        CXX_OBJECTS USER_OBJECTS END_OBJECTS USELIBS DEFNAME_LIBS KOBJ_FLAGS
        USER_FLAGS LDSCRIPT DEPENDS)
    cmake_parse_arguments(PARSE_ARGV 0 NK "" "${oneValueArgs}" "${multiValueArgs}")
    if(NK_UNPARSED_ARGUMENTS OR NK_KEYWORDS_MISSING_VALUES)
        message(FATAL_ERROR "aros_add_native_kobj received malformed arguments")
    endif()
    foreach(_required IN ITEMS NAME OWNER FORM OUTPUT LINKER COLLECTOR NM OBJCOPY LIBDIR)
        if(NOT NK_${_required})
            message(FATAL_ERROR "aros_add_native_kobj requires ${_required}")
        endif()
    endforeach()
    _aros_native_kobj_valid_owner("${NK_NAME}" "target name")
    _aros_native_kobj_valid_owner("${NK_OWNER}" "owner")
    _aros_native_kobj_is_unsafe(_unsafe_roots "${CMAKE_BINARY_DIR}${CMAKE_SOURCE_DIR}")
    if(_unsafe_roots)
        message(FATAL_ERROR "Native KOBJ source/build roots contain unsupported characters")
    endif()
    if(CMAKE_CONFIGURATION_TYPES)
        message(FATAL_ERROR
            "Native KOBJ ${NK_OWNER} currently requires a single-configuration generator")
    endif()
    if(NOT NK_FORM STREQUAL "full" AND NOT NK_FORM STREQUAL "simple")
        message(FATAL_ERROR "Native KOBJ ${NK_OWNER} FORM must be full or simple")
    endif()
    get_property(_macro_recorded GLOBAL PROPERTY "AROS_MODULE_MACRO_${NK_OWNER}" SET)
    if(NOT _macro_recorded)
        message(FATAL_ERROR
            "Native KOBJ ${NK_OWNER} has no recorded source module-macro fact")
    endif()
    get_property(_macro_form GLOBAL PROPERTY "AROS_MODULE_MACRO_${NK_OWNER}")
    if(NK_FORM STREQUAL "full" AND
       NOT _macro_form MATCHES "^(full|runtime-only)$")
        message(FATAL_ERROR
            "Native KOBJ ${NK_OWNER} requests full form but source contract is ${_macro_form}")
    elseif(NK_FORM STREQUAL "simple" AND NOT _macro_form STREQUAL "simple")
        message(FATAL_ERROR
            "Native KOBJ ${NK_OWNER} requests simple form but source contract is ${_macro_form}")
    endif()
    if(TARGET "${NK_NAME}")
        message(FATAL_ERROR "Native KOBJ target already exists: ${NK_NAME}")
    endif()
    _aros_native_kobj_is_unsafe(_unsafe_output "${NK_OUTPUT}")
    if(NOT IS_ABSOLUTE "${NK_OUTPUT}" OR _unsafe_output)
        message(FATAL_ERROR
            "Native KOBJ ${NK_OWNER} OUTPUT must be a safe absolute build-tree path")
    endif()
    _aros_native_core_check_output(_output "${NK_OUTPUT}" "KOBJ output")
    _aros_native_kobj_check_build_directory(_libdir "${NK_LIBDIR}" "LIBDIR")
    _aros_native_kobj_check_tool(_linker "${NK_LINKER}" "LINKER")
    _aros_native_kobj_check_tool(_collector "${NK_COLLECTOR}" "COLLECTOR")
    _aros_native_kobj_check_tool(_nm "${NK_NM}" "NM")
    _aros_native_kobj_check_tool(_objcopy "${NK_OBJCOPY}" "OBJCOPY")
    set(_runner "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/RunNativeKobj.cmake")
    if(NOT EXISTS "${_runner}" OR IS_DIRECTORY "${_runner}")
        message(FATAL_ERROR "Native KOBJ runtime helper is missing: ${_runner}")
    endif()
    _aros_native_kobj_check_tool(_runner "${_runner}" "runtime helper")

    get_property(_owners GLOBAL PROPERTY AROS_NATIVE_KOBJ_OWNERS)
    get_property(_outputs GLOBAL PROPERTY AROS_NATIVE_KOBJ_OUTPUTS)
    get_property(_stages GLOBAL PROPERTY AROS_NATIVE_KOBJ_STAGES)
    get_property(_reports GLOBAL PROPERTY AROS_NATIVE_KOBJ_REPORTS)
    if(NK_OWNER IN_LIST _owners)
        message(FATAL_ERROR "Native KOBJ owner is declared more than once: ${NK_OWNER}")
    endif()
    if(NK_FORM STREQUAL "simple" AND
       (NK_START_OBJECTS OR NK_ASM_OBJECTS OR NK_CXX_OBJECTS OR
        NK_USER_OBJECTS OR NK_END_OBJECTS OR NK_DEFNAME_LIBS))
        message(FATAL_ERROR
            "Native KOBJ ${NK_OWNER} simple form accepts only ARCH_OBJECTS and C_OBJECTS")
    endif()

    set(_depends "${_linker}" "${_collector}" "${_nm}" "${_objcopy}" "${_runner}")
    set(_generated_dep_paths "")
    set(_static_inputs "")
    set(_file_dependencies "")
    set(_script_inputs "")
    foreach(_dependency IN LISTS NK_DEPENDS)
        if(TARGET "${_dependency}")
            if(NOT _dependency IN_LIST _depends)
                list(APPEND _depends "${_dependency}")
            endif()
            continue()
        endif()
        _aros_native_kobj_is_unsafe(_unsafe_dependency "${_dependency}")
        if(NOT IS_ABSOLUTE "${_dependency}" OR _unsafe_dependency)
            message(FATAL_ERROR
                "Native KOBJ ${NK_OWNER} DEPENDS must name a target or absolute path: '${_dependency}'")
        endif()
        cmake_path(ABSOLUTE_PATH _dependency NORMALIZE OUTPUT_VARIABLE _dependency_path)
        if(NOT _dependency_path STREQUAL _dependency)
            message(FATAL_ERROR
                "Native KOBJ ${NK_OWNER} DEPENDS path must be normalized: '${_dependency}'")
        endif()
        if(NOT EXISTS "${_dependency_path}")
            get_source_file_property(_generated "${_dependency_path}" GENERATED)
            if(NOT _generated)
                message(FATAL_ERROR
                    "Native KOBJ ${NK_OWNER} DEPENDS is missing and not GENERATED: ${_dependency_path}")
            endif()
            list(APPEND _generated_dep_paths "${_dependency_path}")
        endif()
        _aros_native_kobj_check_input(
            _validated_dependency _dependency_dep "${_dependency_path}" "DEPENDS input"
            "${_generated_dep_paths}")
        if(NOT _dependency_path IN_LIST _depends)
            list(APPEND _depends "${_dependency_dep}")
        endif()
        if(NOT _dependency_dep IN_LIST _file_dependencies)
            list(APPEND _file_dependencies "${_dependency_dep}")
        endif()
    endforeach()

    if(NK_FORM STREQUAL "full")
        set(_object_groups START_OBJECTS ARCH_OBJECTS ASM_OBJECTS C_OBJECTS
            CXX_OBJECTS USER_OBJECTS END_OBJECTS)
    else()
        set(_object_groups ARCH_OBJECTS C_OBJECTS)
    endif()
    set(_ordered_objects "")
    set(_object_specs "")
    set(_object_keys "")
    set(_object_file_deps "")
    foreach(_group IN LISTS _object_groups)
        foreach(_entry IN LISTS NK_${_group})
            if(_entry MATCHES "^\\$<TARGET_OBJECTS:([A-Za-z0-9_.:+-]+)>$")
                set(_object_target "${CMAKE_MATCH_1}")
                if(NOT TARGET "${_object_target}")
                    message(FATAL_ERROR
                        "Native KOBJ ${NK_OWNER} ${_group} names missing object library ${_object_target}")
                endif()
                get_target_property(_object_type "${_object_target}" TYPE)
                if(NOT _object_type STREQUAL "OBJECT_LIBRARY")
                    message(FATAL_ERROR
                        "Native KOBJ ${NK_OWNER} ${_group} target ${_object_target} is not an OBJECT_LIBRARY")
                endif()
                set(_object_key "target:${_object_target}")
                if(NOT _object_target IN_LIST _depends)
                    list(APPEND _depends "${_object_target}")
                endif()
                set(_object_file_dep "$<TARGET_OBJECTS:${_object_target}>")
                if(NOT _object_file_dep IN_LIST _object_file_deps)
                    list(APPEND _object_file_deps "${_object_file_dep}")
                endif()
                set(_object_value "${_entry}")
                set(_object_spec "target:${_object_target}")
            else()
                _aros_native_kobj_check_input(
                    _object_value _object_dep "${_entry}" "${_group} input"
                    "${_generated_dep_paths}")
                set(_object_key "path:${_object_value}")
                set(_object_spec "path:${_object_value}")
                if(NOT _object_dep IN_LIST _depends)
                    list(APPEND _depends "${_object_dep}")
                endif()
                if(NOT _object_dep IN_LIST _file_dependencies)
                    list(APPEND _file_dependencies "${_object_dep}")
                endif()
            endif()
            # The source recipes use `$^`, which removes duplicate prerequisites
            # while retaining the first occurrence. Do the same for exact inputs.
            if(_object_key IN_LIST _object_keys)
                continue()
            endif()
            list(APPEND _object_keys "${_object_key}")
            list(APPEND _ordered_objects "${_object_value}")
            list(APPEND _object_specs "${_object_spec}")
        endforeach()
    endforeach()
    if(NOT _ordered_objects)
        message(FATAL_ERROR "Native KOBJ ${NK_OWNER} has no object inputs")
    endif()
    _aros_native_kobj_validate_link_flags("${NK_OWNER}" "KOBJ_FLAGS"
        ${NK_KOBJ_FLAGS})
    _aros_native_kobj_validate_link_flags("${NK_OWNER}" "USER_FLAGS"
        ${NK_USER_FLAGS})
    set(_expect_script_path FALSE)
    set(_script_count 0)
    foreach(_script_arg IN LISTS NK_LDSCRIPT)
        _aros_native_kobj_valid_arg("${_script_arg}" "${NK_OWNER} LDSCRIPT argument")
        if(_expect_script_path)
            set(_script_path "${_script_arg}")
            set(_expect_script_path FALSE)
        elseif(_script_arg STREQUAL "-T")
            set(_expect_script_path TRUE)
            continue()
        elseif(_script_arg MATCHES "^-T(.+)$")
            set(_script_path "${CMAKE_MATCH_1}")
        else()
            message(FATAL_ERROR
                "Native KOBJ ${NK_OWNER} LDSCRIPT accepts only -T and its owned path")
        endif()
        math(EXPR _script_count "${_script_count} + 1")
        if(_script_count GREATER 1)
            message(FATAL_ERROR "Native KOBJ ${NK_OWNER} has multiple linker scripts")
        endif()
        _aros_native_kobj_check_input(
            _script_path_normalized _script_dep "${_script_path}" "linker script"
            "${_generated_dep_paths}")
        if(NOT _script_dep IN_LIST _depends)
            list(APPEND _depends "${_script_dep}")
        endif()
        if(NOT _script_dep IN_LIST _file_dependencies)
            list(APPEND _file_dependencies "${_script_dep}")
        endif()
        if(NOT _script_dep IN_LIST _static_inputs)
            list(APPEND _static_inputs "${_script_dep}")
        endif()
        if(NOT _script_dep IN_LIST _script_inputs)
            list(APPEND _script_inputs "${_script_dep}")
        endif()
    endforeach()
    if(_expect_script_path)
        message(FATAL_ERROR "Native KOBJ ${NK_OWNER} has -T without a script path")
    endif()

    set(_archive_targets "")

    set(_filtered_uselibs "")
    foreach(_library IN LISTS NK_USELIBS)
        _aros_native_kobj_valid_owner("${_library}" "${NK_OWNER} uselib")
        if(_library MATCHES "^(hiddstubs|amiga|arossupport|autoinit|libinit)$")
            continue()
        endif()
        list(APPEND _filtered_uselibs "${_library}")
    endforeach()
    set(_libraries ${_filtered_uselibs}
        dos intuition layers graphics oop utility expansion keymap)
    if(NK_FORM STREQUAL "full")
        foreach(_library IN LISTS NK_DEFNAME_LIBS)
            _aros_native_kobj_valid_owner("${_library}" "${NK_OWNER} DEFNAME library")
            list(APPEND _libraries "${_library}")
        endforeach()
    endif()
    set(_library_args "")
    foreach(_library IN LISTS _libraries)
        aros_resolve_native_core_linklib(_archive_target "${_library}")
        if(NOT _archive_target IN_LIST _depends)
            list(APPEND _depends "${_archive_target}")
        endif()
        if(NOT _archive_target IN_LIST _archive_targets)
            list(APPEND _archive_targets "${_archive_target}")
        endif()
        list(APPEND _library_args "-l${_library}")
    endforeach()

    foreach(_static_input IN LISTS _ordered_objects)
        if(NOT _static_input MATCHES "^\\$<TARGET_OBJECTS:")
            if(_static_input STREQUAL _output)
                message(FATAL_ERROR
                    "Native KOBJ ${NK_OWNER} output collides with an object input")
            endif()
            if(NOT _static_input IN_LIST _static_inputs)
                list(APPEND _static_inputs "${_static_input}")
            endif()
        endif()
    endforeach()
    if(_output IN_LIST _static_inputs)
        message(FATAL_ERROR "Native KOBJ ${NK_OWNER} output collides with a static input")
    endif()
    foreach(_file_dependency IN LISTS _file_dependencies)
        if(_output STREQUAL _file_dependency)
            message(FATAL_ERROR "Native KOBJ ${NK_OWNER} output collides with a file dependency")
        endif()
    endforeach()
    foreach(_object IN LISTS _ordered_objects)
        if(NOT _object MATCHES "^\\$<TARGET_OBJECTS:")
            if(_output STREQUAL _object)
                message(FATAL_ERROR "Native KOBJ ${NK_OWNER} output collides with an object input")
            endif()
        endif()
    endforeach()
    foreach(_tool IN ITEMS _linker _collector _nm _objcopy)
        if("${${_tool}}" STREQUAL "${_output}")
            message(FATAL_ERROR "Native KOBJ ${NK_OWNER} output collides with a tool input")
        endif()
    endforeach()
    if(_output STREQUAL _runner)
        message(FATAL_ERROR "Native KOBJ ${NK_OWNER} output collides with its runner script")
    endif()

    set(_stage "${_output}.native-kobj-stage")
    _aros_native_core_check_output(_stage "${_stage}" "KOBJ staging output")
    set(_report "${_stage}.sets.report")
    _aros_native_core_check_output(_report "${_report}" "KOBJ set report")
    foreach(_input IN LISTS _ordered_objects _file_dependencies)
        if(NOT _input MATCHES "^\\$<TARGET_OBJECTS:")
            _aros_native_kobj_reject_output_alias(
                "${NK_OWNER}" "${_input}" "input"
                "${_output}" "${_stage}" "${_report}")
        endif()
    endforeach()
    foreach(_tool IN ITEMS _linker _collector _nm _objcopy _runner)
        _aros_native_kobj_reject_output_alias(
            "${NK_OWNER}" "${${_tool}}" "tool input"
            "${_output}" "${_stage}" "${_report}")
    endforeach()
    if(_report STREQUAL _output OR _report STREQUAL _stage)
        message(FATAL_ERROR "Native KOBJ ${NK_OWNER} report collides with output/staging path")
    endif()
    if(_output IN_LIST _stages OR _output IN_LIST _outputs OR
       _output IN_LIST _reports OR _stage IN_LIST _stages OR
       _stage IN_LIST _outputs OR _stage IN_LIST _reports OR
       _report IN_LIST _stages OR _report IN_LIST _outputs OR
       _report IN_LIST _reports)
        message(FATAL_ERROR "Native KOBJ ${NK_OWNER} output/staging/report path is already claimed")
    endif()
    if(_stage STREQUAL _output OR _stage IN_LIST _static_inputs OR
       _report IN_LIST _static_inputs)
        message(FATAL_ERROR "Native KOBJ ${NK_OWNER} staging path collides with an input/output")
    endif()
    foreach(_file_dependency IN LISTS _file_dependencies)
        if(_stage STREQUAL _file_dependency)
            message(FATAL_ERROR "Native KOBJ ${NK_OWNER} staging path collides with a file dependency")
        endif()
        if(_report STREQUAL _file_dependency)
            message(FATAL_ERROR "Native KOBJ ${NK_OWNER} report collides with a file dependency")
        endif()
    endforeach()
    foreach(_object IN LISTS _ordered_objects)
        if(NOT _object MATCHES "^\\$<TARGET_OBJECTS:")
            if(_stage STREQUAL _object)
                message(FATAL_ERROR "Native KOBJ ${NK_OWNER} staging path collides with an object input")
            endif()
            if(_report STREQUAL _object)
                message(FATAL_ERROR "Native KOBJ ${NK_OWNER} report collides with an object input")
            endif()
        endif()
    endforeach()
    foreach(_tool IN ITEMS _linker _collector _nm _objcopy)
        if("${${_tool}}" STREQUAL "${_stage}")
            message(FATAL_ERROR "Native KOBJ ${NK_OWNER} staging path collides with a tool input")
        endif()
        if("${${_tool}}" STREQUAL "${_report}")
            message(FATAL_ERROR "Native KOBJ ${NK_OWNER} report collides with a tool input")
        endif()
    endforeach()
    if(_stage STREQUAL _runner)
        message(FATAL_ERROR "Native KOBJ ${NK_OWNER} staging path collides with its runner script")
    endif()

    # Match collect-aros -Ur: it completes set collection, then calls the
    # direct --ld route with raw -r (CollectRelocatable), not driver -r mode.
    set(_link_prefix "-r" ${NK_KOBJ_FLAGS} ${NK_LDSCRIPT})
    set(_link_suffix ${NK_USER_FLAGS} "-L" "${_libdir}" ${_library_args})
    set(_config "{}")
    _aros_native_kobj_json_set_string(_config OWNER "${NK_OWNER}")
    _aros_native_kobj_json_set_string(_config OUTPUT "${_output}")
    _aros_native_kobj_json_set_string(_config STAGE "${_stage}")
    _aros_native_kobj_json_set_string(_config REPORT "${_report}")
    _aros_native_kobj_json_set_string(_config BUILD_ROOT "${CMAKE_BINARY_DIR}")
    _aros_native_kobj_json_set_string(_config SOURCE_ROOT "${CMAKE_SOURCE_DIR}")
    _aros_native_kobj_json_set_string(_config COLLECTOR "${_collector}")
    _aros_native_kobj_json_set_string(_config LINKER "${_linker}")
    _aros_native_kobj_json_set_string(_config NM "${_nm}")
    _aros_native_kobj_json_set_string(_config OBJCOPY "${_objcopy}")
    _aros_native_kobj_json_set_string(_config LIBDIR "${_libdir}")
    _aros_native_kobj_json_set_string(_config RUNNER "${_runner}")
    _aros_native_kobj_json_set_array(_config OBJECT_SPECS ${_object_specs})
    _aros_native_kobj_json_set_array(_config ARCHIVE_TARGETS ${_archive_targets})
    _aros_native_kobj_json_set_array(_config LINK_PREFIX ${_link_prefix})
    _aros_native_kobj_json_set_array(_config LINK_SUFFIX ${_link_suffix})
    _aros_native_kobj_json_set_array(_config STATIC_INPUTS ${_static_inputs})
    _aros_native_kobj_json_set_array(_config SCRIPT_INPUTS ${_script_inputs})
    _aros_native_kobj_json_set_array(_config DEPENDENCY_FILES ${_file_dependencies})
    set(_config_content "${_config}\n")
    string(SHA256 _config_sha "${_config_content}")

    set(_config_dir "${CMAKE_CURRENT_BINARY_DIR}/CMakeFiles")
    if(IS_SYMLINK "${_config_dir}")
        message(FATAL_ERROR "Native KOBJ config directory is a symlink: ${_config_dir}")
    endif()
    file(MAKE_DIRECTORY "${_config_dir}")
    file(REAL_PATH "${CMAKE_BINARY_DIR}" _build_root_real)
    file(REAL_PATH "${_config_dir}" _config_dir_real)
    cmake_path(IS_PREFIX _build_root_real "${_config_dir_real}" NORMALIZE _config_dir_inside)
    if(NOT _config_dir_inside)
        message(FATAL_ERROR "Native KOBJ config directory escapes the build tree")
    endif()
    set(_config_path "${_config_dir}/${NK_NAME}-native-kobj.json")
    if(_output STREQUAL _config_path OR _stage STREQUAL _config_path OR
       _report STREQUAL _config_path)
        message(FATAL_ERROR "Native KOBJ ${NK_OWNER} output/stage/report collides with its sealed config")
    endif()
    if(_config_path STREQUAL _runner OR _config_path IN_LIST _file_dependencies OR
       _config_path IN_LIST _static_inputs OR _config_path IN_LIST _ordered_objects)
        message(FATAL_ERROR "Native KOBJ ${NK_OWNER} sealed config collides with an input")
    endif()
    foreach(_tool IN ITEMS _linker _collector _nm _objcopy)
        if("${${_tool}}" STREQUAL "${_config_path}")
            message(FATAL_ERROR "Native KOBJ ${NK_OWNER} sealed config collides with a tool input")
        endif()
    endforeach()
    foreach(_input IN LISTS _ordered_objects _file_dependencies)
        if(NOT _input MATCHES "^\\$<TARGET_OBJECTS:")
            _aros_native_kobj_reject_output_alias(
                "${NK_OWNER}" "${_input}" "sealed-config input"
                "${_config_path}" "" "")
        endif()
    endforeach()
    foreach(_tool IN ITEMS _linker _collector _nm _objcopy _runner)
        _aros_native_kobj_reject_output_alias(
            "${NK_OWNER}" "${${_tool}}" "sealed-config tool input"
            "${_config_path}" "" "")
    endforeach()
    if(IS_SYMLINK "${_config_path}" OR
       (EXISTS "${_config_path}" AND IS_DIRECTORY "${_config_path}"))
        message(FATAL_ERROR "Native KOBJ config path is not a regular file: ${_config_path}")
    endif()
    if(EXISTS "${_config_path}")
        file(READ "${_config_path}" _old_config)
    else()
        set(_old_config "")
    endif()
    if(NOT _old_config STREQUAL _config_content)
        file(WRITE "${_config_path}" "${_config_content}")
    endif()

    list(LENGTH _object_specs _object_count)
    set(_object_commands "")
    set(_object_index 0)
    foreach(_spec IN LISTS _object_specs)
        if(_spec MATCHES "^target:(.+)$")
            set(_object_target "${CMAKE_MATCH_1}")
            list(APPEND _object_commands
                "-DAROS_NATIVE_KOBJ_OBJECT_${_object_index}=$<JOIN:$<TARGET_OBJECTS:${_object_target}>,|>")
        elseif(_spec MATCHES "^path:(.+)$")
            list(APPEND _object_commands
                "-DAROS_NATIVE_KOBJ_OBJECT_${_object_index}=${CMAKE_MATCH_1}")
        else()
            message(FATAL_ERROR "Native KOBJ ${NK_OWNER} has malformed internal object input")
        endif()
        math(EXPR _object_index "${_object_index} + 1")
    endforeach()
    set(_archive_commands "")
    set(_archive_index 0)
    foreach(_archive_target IN LISTS _archive_targets)
        list(APPEND _archive_commands
            "-DAROS_NATIVE_KOBJ_ARCHIVE_FILE_${_archive_index}=$<TARGET_FILE:${_archive_target}>")
        math(EXPR _archive_index "${_archive_index} + 1")
    endforeach()

    set(_config_args
        "-DAROS_NATIVE_KOBJ_CONFIG=${_config_path}"
        "-DAROS_NATIVE_KOBJ_EXPECTED_SHA256=${_config_sha}"
        "-DAROS_NATIVE_KOBJ_EXPECTED_ROOT=${CMAKE_BINARY_DIR}"
        "-DAROS_NATIVE_KOBJ_OBJECT_COUNT=${_object_count}"
        "-DAROS_NATIVE_KOBJ_ARCHIVE_COUNT=${_archive_index}"
        ${_object_commands} ${_archive_commands})
    set(_validate_target "${NK_NAME}__native_kobj_validate")
    if(TARGET "${_validate_target}")
        message(FATAL_ERROR "Native KOBJ validation target already exists: ${_validate_target}")
    endif()
    add_custom_target("${_validate_target}"
        COMMAND "${CMAKE_COMMAND}" ${_config_args}
            "-DAROS_NATIVE_KOBJ_VALIDATE_ONLY=ON" -P "${_runner}"
        DEPENDS ${_depends} "${_config_path}"
        COMMENT "Validate native KOBJ ${NK_OWNER}"
        VERBATIM)
    add_custom_command(
        OUTPUT "${_output}"
        COMMAND "${CMAKE_COMMAND}" ${_config_args} -P "${_runner}"
        DEPENDS ${_depends} ${_object_file_deps} "${_config_path}"
        COMMENT "Native KOBJ ${NK_OWNER}"
        VERBATIM)
    add_custom_target("${NK_NAME}" DEPENDS "${_output}")
    add_dependencies("${NK_NAME}" "${_validate_target}")
    set_target_properties("${NK_NAME}" PROPERTIES
        AROS_NATIVE_KOBJ_OWNER "${NK_OWNER}"
        AROS_NATIVE_KOBJ_FORM "${NK_FORM}"
        AROS_NATIVE_KOBJ_OUTPUT "${_output}"
        AROS_NATIVE_KOBJ_OBJECTS "${_ordered_objects}"
        AROS_NATIVE_KOBJ_LIBRARIES "${_libraries}")

    list(APPEND _owners "${NK_OWNER}")
    list(APPEND _outputs "${_output}")
    list(APPEND _stages "${_stage}")
    list(APPEND _reports "${_report}")
    set_property(GLOBAL PROPERTY AROS_NATIVE_KOBJ_OWNERS "${_owners}")
    set_property(GLOBAL PROPERTY AROS_NATIVE_KOBJ_OUTPUTS "${_outputs}")
    set_property(GLOBAL PROPERTY AROS_NATIVE_KOBJ_STAGES "${_stages}")
    set_property(GLOBAL PROPERTY AROS_NATIVE_KOBJ_REPORTS "${_reports}")
    # The final core accepts only this helper's registered, collected and
    # localized intermediate, never the runtime ELF or raw object mirrors.
    set_property(GLOBAL PROPERTY "AROS_NATIVE_KOBJ_TARGET_${NK_OWNER}" "${NK_NAME}")
endfunction()
