include_guard(GLOBAL)

# Ordinary quoted-header paths remain target options unless an architecture
# source declares incextra. CMake emits target options before source options;
# that case must defer the ordinary paths so the explicit source path wins.
# The implicit TARGET_PROPERTY context is essential: a source shared by two
# targets must read each consuming target's paths, not another target's list.
function(aros_add_quote_options target)
    cmake_parse_arguments(QUOTE "BEFORE" "" "" ${ARGN})
    get_target_property(_sources "${target}" SOURCES)
    get_target_property(_deferred "${target}" AROS_DEFER_QUOTE_OPTIONS)
    foreach(_source IN LISTS _sources)
        if(_source MATCHES "\\$<")
            continue()
        endif()
        get_source_file_property(_extra "${_source}" AROS_ARCH_QUOTE_INCLUDE)
        if(_extra AND NOT _extra STREQUAL "NOTFOUND")
            set(_deferred TRUE)
        endif()
    endforeach()
    if(NOT _deferred)
        if(QUOTE_BEFORE)
            target_compile_options("${target}" BEFORE PRIVATE
                ${QUOTE_UNPARSED_ARGUMENTS})
        else()
            target_compile_options("${target}" PRIVATE
                ${QUOTE_UNPARSED_ARGUMENTS})
        endif()
        return()
    endif()

    get_target_property(_existing "${target}" COMPILE_OPTIONS)
    get_target_property(_fallback "${target}" AROS_QUOTE_FALLBACK_OPTIONS)
    if(NOT _fallback OR _fallback STREQUAL "_fallback-NOTFOUND")
        set(_fallback "")
    endif()
    set(_retained "")
    if(_existing AND NOT _existing STREQUAL "_existing-NOTFOUND")
        foreach(_option IN LISTS _existing)
            if(_option MATCHES "^-iquote")
                list(APPEND _fallback "${_option}")
            else()
                list(APPEND _retained "${_option}")
            endif()
        endforeach()
    endif()
    if(QUOTE_BEFORE)
        list(PREPEND _fallback ${QUOTE_UNPARSED_ARGUMENTS})
    else()
        list(APPEND _fallback ${QUOTE_UNPARSED_ARGUMENTS})
    endif()
    list(REMOVE_DUPLICATES _fallback)
    set_property(TARGET "${target}" PROPERTY COMPILE_OPTIONS "${_retained}")
    set_property(TARGET "${target}" PROPERTY AROS_DEFER_QUOTE_OPTIONS TRUE)
    set_property(TARGET "${target}" PROPERTY
        AROS_QUOTE_FALLBACK_OPTIONS "${_fallback}")

    set(_fallback_expression "$<TARGET_PROPERTY:AROS_QUOTE_FALLBACK_OPTIONS>")
    foreach(_source IN LISTS _sources)
        if(_source MATCHES "\\$<")
            continue()
        endif()
        get_source_file_property(_options "${_source}" COMPILE_OPTIONS)
        if(NOT _options OR _options STREQUAL "NOTFOUND")
            set(_options "")
        endif()
        list(REMOVE_ITEM _options "${_fallback_expression}")
        get_source_file_property(_extra "${_source}" AROS_ARCH_QUOTE_INCLUDE)
        if(_extra AND NOT _extra STREQUAL "NOTFOUND")
            list(REMOVE_ITEM _options "-iquote${_extra}")
            list(PREPEND _options "-iquote${_extra}")
        endif()
        list(APPEND _options "${_fallback_expression}")
        set_source_files_properties("${_source}" PROPERTIES
            COMPILE_OPTIONS "${_options}")
    endforeach()
endfunction()
