cmake_minimum_required(VERSION 3.22)
include("${CMAKE_CURRENT_LIST_DIR}/LiteralObjects.cmake")

if(NOT DEFINED COMMAND_FILE OR NOT IS_ABSOLUTE "${COMMAND_FILE}" OR
   NOT DEFINED COMMAND_ROOT OR NOT IS_ABSOLUTE "${COMMAND_ROOT}" OR
   NOT DEFINED COMMAND_SHA256 OR NOT COMMAND_SHA256 MATCHES "^[0-9a-f]+$" OR
   NOT DEFINED VERIFY_ONLY OR NOT VERIFY_ONLY MATCHES "^(ON|OFF)$")
    message(FATAL_ERROR "Assembly header runner: invalid command identity")
endif()
string(LENGTH "${COMMAND_SHA256}" digest_length)
if(NOT digest_length EQUAL 64)
    message(FATAL_ERROR "Assembly header runner: invalid command digest")
endif()
_aros_literal_check_root("${COMMAND_ROOT}" "command root")
_aros_literal_check_path_chain("${COMMAND_FILE}" "${COMMAND_ROOT}" "command file")
_aros_literal_assert_regular("${COMMAND_FILE}" "command file" FALSE)
file(SHA256 "${COMMAND_FILE}" actual)
if(NOT actual STREQUAL COMMAND_SHA256)
    message(FATAL_ERROR "Assembly header runner: changed command file")
endif()
include("${COMMAND_FILE}")
foreach(field BUILD_ROOT HEADER_ROOT ASSEMBLY OUTPUT TOKEN)
    if(NOT DEFINED ${field} OR "${${field}}" STREQUAL "")
        message(FATAL_ERROR "Assembly header runner: missing ${field}")
    endif()
    _aros_literal_reject_control_text("${${field}}" "${field}")
endforeach()
_aros_literal_check_root("${BUILD_ROOT}" "build root")
if(NOT TOKEN STREQUAL ".ascii" AND NOT TOKEN STREQUAL ".asciz")
    message(FATAL_ERROR "Assembly header runner: invalid token")
endif()
set(gen_root "${BUILD_ROOT}/gen")
cmake_path(IS_PREFIX BUILD_ROOT "${HEADER_ROOT}" NORMALIZE root_inside)
if(NOT root_inside OR HEADER_ROOT STREQUAL BUILD_ROOT)
    message(FATAL_ERROR "Assembly header runner: header root escapes build root")
endif()
cmake_path(IS_PREFIX HEADER_ROOT "${OUTPUT}" NORMALIZE output_inside)
if(NOT output_inside OR OUTPUT STREQUAL HEADER_ROOT OR
   NOT OUTPUT MATCHES "\\.h$" OR NOT ASSEMBLY MATCHES "\\.s$")
    message(FATAL_ERROR "Assembly header runner: invalid output roles")
endif()
_aros_literal_check_path_chain("${ASSEMBLY}" "${gen_root}" "assembly input")
_aros_literal_check_path_chain("${OUTPUT}" "${BUILD_ROOT}" "header output")
_aros_literal_check_optional_regular("${ASSEMBLY}" "assembly input")
_aros_literal_check_optional_regular("${OUTPUT}" "header output")
if(VERIFY_ONLY)
    return()
endif()
_aros_literal_assert_regular("${ASSEMBLY}" "assembly input" FALSE)
file(SIZE "${ASSEMBLY}" input_size)
if(input_size GREATER 16777216)
    message(FATAL_ERROR "Assembly header runner: assembly input exceeds bound")
endif()
file(STRINGS "${ASSEMBLY}" lines ENCODING UTF-8)
set(header "")
foreach(line IN LISTS lines)
    # The source grep uses a basic regular expression (. is a wildcard).
    # cut selects the first quoted field; sed removes only a final '$'.
    if(line MATCHES "${TOKEN}")
        string(FIND "${line}" "\"" first_quote)
        if(first_quote EQUAL -1)
            message(FATAL_ERROR "Assembly header runner: selected line lacks quoted payload")
        endif()
        math(EXPR start "${first_quote} + 1")
        string(SUBSTRING "${line}" ${start} -1 rest)
        string(FIND "${rest}" "\"" last_quote)
        if(last_quote EQUAL -1)
            message(FATAL_ERROR "Assembly header runner: selected line lacks closing quote")
        endif()
        string(SUBSTRING "${rest}" 0 ${last_quote} payload)
        string(REGEX REPLACE "\\$$" "" payload "${payload}")
        string(APPEND header "${payload}\n")
    endif()
endforeach()
if(header STREQUAL "")
    message(FATAL_ERROR "Assembly header runner: empty extraction for selected token")
endif()
cmake_path(GET OUTPUT PARENT_PATH parent)
file(MAKE_DIRECTORY "${parent}")
_aros_literal_check_path_chain("${OUTPUT}" "${BUILD_ROOT}" "header output")
string(RANDOM LENGTH 20 ALPHABET 0123456789abcdef nonce)
set(temporary "${OUTPUT}.tmp-${nonce}")
_aros_literal_check_path_chain("${temporary}" "${BUILD_ROOT}" "temporary header")
file(WRITE "${temporary}" "${header}")
_aros_literal_assert_regular("${temporary}" "temporary header" FALSE)
_aros_literal_check_optional_regular("${OUTPUT}" "header output")
file(RENAME "${temporary}" "${OUTPUT}")
