cmake_minimum_required(VERSION 3.22)
include("${CMAKE_CURRENT_LIST_DIR}/DirectorySetup.cmake")
if(NOT SETUP_ROOT_COUNT MATCHES "^[345]$")
    message(FATAL_ERROR "Directory setup: requires three to five configured roots")
endif()
set(SETUP_ROOTS "")
math(EXPR _last_root "${SETUP_ROOT_COUNT} - 1")
foreach(_index RANGE 0 ${_last_root})
    list(APPEND SETUP_ROOTS "${SETUP_ROOT_${_index}}")
endforeach()
foreach(_path "${SETUP_DIRECTORY}" "${SETUP_EXPECTED_PHYSICAL}" ${SETUP_ROOTS})
    if(NOT IS_ABSOLUTE "${_path}" OR "${_path}" MATCHES "[;\"\r\n$]" OR
       "${_path}" MATCHES "(^|/)\\.\\.?(/|$)")
        message(FATAL_ERROR "Directory setup: unsafe path: ${_path}")
    endif()
endforeach()
set(_root "")
foreach(_candidate IN LISTS SETUP_ROOTS)
    if(IS_SYMLINK "${_candidate}")
        message(FATAL_ERROR "Directory setup: configured root is a symlink: ${_candidate}")
    endif()
    cmake_path(IS_PREFIX _candidate "${SETUP_DIRECTORY}" NORMALIZE _inside)
    if(_inside AND _root STREQUAL "")
        set(_root "${_candidate}")
    endif()
endforeach()
if(_root STREQUAL "")
    message(FATAL_ERROR "Directory setup: destination escapes configured roots")
endif()
file(RELATIVE_PATH _relative "${_root}" "${SETUP_DIRECTORY}")
set(_probe "${_root}")
if(NOT _relative STREQUAL "")
    string(REPLACE "/" ";" _components "${_relative}")
    foreach(_component IN LISTS _components)
        string(APPEND _probe "/${_component}")
        if(IS_SYMLINK "${_probe}")
            message(FATAL_ERROR "Directory setup: directory path crosses a symlink: ${_probe}")
        endif()
    endforeach()
endif()
_aros_directory_physical_path("${SETUP_DIRECTORY}" _physical)
if(NOT _physical STREQUAL SETUP_EXPECTED_PHYSICAL)
    message(FATAL_ERROR "Directory setup: physical destination changed after configuration")
endif()
file(MAKE_DIRECTORY "${SETUP_DIRECTORY}")
_aros_directory_physical_path("${SETUP_DIRECTORY}" _physical_after)
if(NOT _physical_after STREQUAL SETUP_EXPECTED_PHYSICAL)
    message(FATAL_ERROR "Directory setup: physical destination changed during preparation")
endif()
