# Run one declared host generator without a shell and publish output only after
# successful completion. Paths are rechecked at build time in case a symlink
# was introduced after CMake generation.

foreach(_required HOST_HEADER_PRIMARY HOST_HEADER_SDK HOST_HEADER_BINARY_ROOT
                  HOST_HEADER_GENINC_ROOT HOST_HEADER_SDK_ROOT)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "RunHostHeader: ${_required} is required")
    endif()
    if("${${_required}}" MATCHES "[;\"\r\n$]")
        message(FATAL_ERROR "RunHostHeader: unsafe ${_required} value")
    endif()
endforeach()

function(_aros_check_root _root)
    if(NOT IS_ABSOLUTE "${_root}" OR IS_SYMLINK "${_root}")
        message(FATAL_ERROR "RunHostHeader: configured root is invalid: ${_root}")
    endif()
endfunction()

function(_aros_check_contained_path _root _path _must_exist)
    _aros_check_root("${_root}")
    if(NOT IS_ABSOLUTE "${_path}")
        message(FATAL_ERROR "RunHostHeader: path is not absolute: ${_path}")
    endif()
    cmake_path(NORMAL_PATH _path)
    cmake_path(NORMAL_PATH _root OUTPUT_VARIABLE _normalized_root)
    cmake_path(IS_PREFIX _normalized_root "${_path}" NORMALIZE _inside)
    if(NOT _inside)
        message(FATAL_ERROR "RunHostHeader: path escapes its configured root: ${_path}")
    endif()
    if(_path STREQUAL _normalized_root)
        if(_must_exist AND NOT EXISTS "${_path}")
            message(FATAL_ERROR "RunHostHeader: required root is missing: ${_path}")
        endif()
        return()
    endif()
    file(RELATIVE_PATH _relative "${_normalized_root}" "${_path}")
    string(REPLACE "/" ";" _components "${_relative}")
    set(_probe "${_normalized_root}")
    foreach(_component IN LISTS _components)
        if(_component STREQUAL "" OR _component STREQUAL "." OR _component STREQUAL "..")
            message(FATAL_ERROR "RunHostHeader: unsafe path component in ${_path}")
        endif()
        set(_probe "${_probe}/${_component}")
        if(IS_SYMLINK "${_probe}")
            message(FATAL_ERROR "RunHostHeader: path crosses a symlink: ${_probe}")
        endif()
    endforeach()
    if(_must_exist AND NOT EXISTS "${_path}")
        message(FATAL_ERROR "RunHostHeader: required file or directory is missing: ${_path}")
    endif()
    if(EXISTS "${_path}")
        file(REAL_PATH "${_normalized_root}" _root_real)
        file(REAL_PATH "${_path}" _path_real)
        cmake_path(IS_PREFIX _root_real "${_path_real}" NORMALIZE _physically_inside)
        if(NOT _physically_inside)
            message(FATAL_ERROR "RunHostHeader: path escapes physically: ${_path}")
        endif()
    endif()
endfunction()

_aros_check_contained_path("${HOST_HEADER_BINARY_ROOT}" "${HOST_HEADER_PRIMARY}" FALSE)
_aros_check_contained_path("${HOST_HEADER_BINARY_ROOT}" "${HOST_HEADER_SDK}" FALSE)
_aros_check_contained_path("${HOST_HEADER_GENINC_ROOT}" "${HOST_HEADER_PRIMARY}" FALSE)
_aros_check_contained_path("${HOST_HEADER_SDK_ROOT}" "${HOST_HEADER_SDK}" FALSE)

if(HOST_HEADER_PREPARE_ONLY)
    foreach(_required HOST_HEADER_SETUP_DIRECTORY_ONE HOST_HEADER_SETUP_DIRECTORY_TWO)
        if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
            message(FATAL_ERROR "RunHostHeader: ${_required} is required")
        endif()
        if("${${_required}}" MATCHES "[;\"\r\n$]")
            message(FATAL_ERROR "RunHostHeader: unsafe ${_required} value")
        endif()
    endforeach()

    get_filename_component(_primary_parent "${HOST_HEADER_PRIMARY}" DIRECTORY)
    get_filename_component(_sdk_parent "${HOST_HEADER_SDK}" DIRECTORY)
    set(_declared_setup_directories
        "${HOST_HEADER_SETUP_DIRECTORY_ONE}" "${HOST_HEADER_SETUP_DIRECTORY_TWO}")
    set(_expected_setup_directories "${_primary_parent}" "${_sdk_parent}")
    list(SORT _declared_setup_directories)
    list(SORT _expected_setup_directories)
    if(NOT _declared_setup_directories STREQUAL _expected_setup_directories)
        message(FATAL_ERROR "RunHostHeader: setup directories do not match output parents")
    endif()

    foreach(_directory IN LISTS _declared_setup_directories)
        _aros_check_contained_path("${HOST_HEADER_BINARY_ROOT}" "${_directory}" FALSE)
        if(_directory STREQUAL _primary_parent)
            _aros_check_contained_path("${HOST_HEADER_GENINC_ROOT}" "${_directory}" FALSE)
        elseif(_directory STREQUAL _sdk_parent)
            _aros_check_contained_path("${HOST_HEADER_SDK_ROOT}" "${_directory}" FALSE)
        else()
            message(FATAL_ERROR "RunHostHeader: unknown setup directory: ${_directory}")
        endif()
    endforeach()

    # Validate both destinations before creating either. Repeat the check
    # immediately before each mkdir so a post-configure symlink replacement
    # cannot redirect this build-time setup action outside the build tree.
    foreach(_directory IN LISTS _declared_setup_directories)
        _aros_check_contained_path("${HOST_HEADER_BINARY_ROOT}" "${_directory}" FALSE)
        execute_process(
            COMMAND "${CMAKE_COMMAND}" -E make_directory "${_directory}"
            RESULT_VARIABLE _mkdir_result
            ERROR_VARIABLE _mkdir_error)
        if(NOT _mkdir_result STREQUAL "0")
            message(FATAL_ERROR
                "RunHostHeader: cannot prepare declared directory ${_directory}: ${_mkdir_error}")
        endif()
        _aros_check_contained_path("${HOST_HEADER_BINARY_ROOT}" "${_directory}" TRUE)
    endforeach()
    return()
endif()

foreach(_required HOST_HEADER_TOOL HOST_HEADER_WORKDIR HOST_HEADER_SOURCE_ROOT)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "RunHostHeader: ${_required} is required")
    endif()
    if("${${_required}}" MATCHES "[;\"\r\n$]")
        message(FATAL_ERROR "RunHostHeader: unsafe ${_required} value")
    endif()
endforeach()

_aros_check_contained_path("${HOST_HEADER_SOURCE_ROOT}" "${HOST_HEADER_WORKDIR}" TRUE)
_aros_check_contained_path("${HOST_HEADER_BINARY_ROOT}" "${HOST_HEADER_TOOL}" TRUE)
if(NOT EXISTS "${HOST_HEADER_TOOL}" OR IS_DIRECTORY "${HOST_HEADER_TOOL}")
    message(FATAL_ERROR "RunHostHeader: host generator is missing: ${HOST_HEADER_TOOL}")
endif()
get_filename_component(_primary_parent "${HOST_HEADER_PRIMARY}" DIRECTORY)
get_filename_component(_sdk_parent "${HOST_HEADER_SDK}" DIRECTORY)
if(NOT IS_DIRECTORY "${_primary_parent}" OR NOT IS_DIRECTORY "${_sdk_parent}")
    message(FATAL_ERROR "RunHostHeader: declared setup directories were not prepared")
endif()
if(IS_SYMLINK "${_primary_parent}" OR IS_SYMLINK "${_sdk_parent}")
    message(FATAL_ERROR "RunHostHeader: output parent is a symlink")
endif()

string(RANDOM LENGTH 20 ALPHABET 0123456789abcdef _nonce)
set(_temporary "${HOST_HEADER_PRIMARY}.aros-host-header-${_nonce}.tmp")
execute_process(
    COMMAND "${HOST_HEADER_TOOL}"
    WORKING_DIRECTORY "${HOST_HEADER_WORKDIR}"
    OUTPUT_FILE "${_temporary}"
    RESULT_VARIABLE _result
    ERROR_VARIABLE _error)
if(NOT _result STREQUAL "0")
    message(FATAL_ERROR "RunHostHeader: generator failed (${_result}): ${_error}")
endif()
if(NOT EXISTS "${_temporary}" OR IS_SYMLINK "${_temporary}")
    message(FATAL_ERROR "RunHostHeader: generator did not produce a regular stdout file")
endif()
_aros_check_contained_path("${HOST_HEADER_BINARY_ROOT}" "${HOST_HEADER_PRIMARY}" FALSE)
_aros_check_contained_path("${HOST_HEADER_BINARY_ROOT}" "${HOST_HEADER_SDK}" FALSE)
_aros_check_contained_path("${HOST_HEADER_GENINC_ROOT}" "${HOST_HEADER_PRIMARY}" FALSE)
_aros_check_contained_path("${HOST_HEADER_SDK_ROOT}" "${HOST_HEADER_SDK}" FALSE)
file(RENAME "${_temporary}" "${HOST_HEADER_PRIMARY}" RESULT _rename_result)
if(NOT _rename_result STREQUAL "0")
    message(FATAL_ERROR "RunHostHeader: cannot publish primary header: ${_rename_result}")
endif()
_aros_check_contained_path("${HOST_HEADER_BINARY_ROOT}" "${HOST_HEADER_SDK}" FALSE)
_aros_check_contained_path("${HOST_HEADER_SDK_ROOT}" "${HOST_HEADER_SDK}" FALSE)
file(COPY_FILE "${HOST_HEADER_PRIMARY}" "${HOST_HEADER_SDK}" RESULT _copy_result)
if(NOT _copy_result STREQUAL "0")
    message(FATAL_ERROR "RunHostHeader: cannot publish SDK mirror: ${_copy_result}")
endif()
