cmake_minimum_required(VERSION 3.22)
include("${CMAKE_CURRENT_LIST_DIR}/HostCFileGenerator.cmake")

if(NOT DEFINED MODE OR NOT MODE MATCHES "^(COMPILE|RUN)$")
    message(FATAL_ERROR "RunHostCFileGenerator requires MODE=COMPILE or MODE=RUN")
endif()
foreach(_required NAME SOURCE_ROOT BINARY_ROOT TOOL_SOURCE TOOL_SHA256 PRIVATE_DIRECTORY)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "RunHostCFileGenerator requires ${_required}")
    endif()
endforeach()
if(NOT NAME MATCHES "^[A-Za-z0-9_][A-Za-z0-9_.+-]*$")
    message(FATAL_ERROR "host C generator: invalid target name '${NAME}'")
endif()
foreach(_var SOURCE_ROOT BINARY_ROOT TOOL_SOURCE PRIVATE_DIRECTORY)
    _aros_host_c_file_generator_reject_unsafe_path("${_var}" "${${_var}}")
    if(NOT IS_ABSOLUTE "${${_var}}")
        message(FATAL_ERROR "host C generator: ${_var} must be absolute")
    endif()
    cmake_path(NORMAL_PATH ${_var})
endforeach()

if(NOT DEFINED SOURCE_MANIFEST_COUNT)
    set(SOURCE_MANIFEST_COUNT 0)
endif()
if(NOT SOURCE_MANIFEST_COUNT MATCHES "^[0-9]+$" OR SOURCE_MANIFEST_COUNT GREATER 128)
    message(FATAL_ERROR "${NAME}: invalid source-manifest count")
endif()

function(_aros_hcfg_verify_sources)
    _aros_host_c_file_generator_check_tree("${SOURCE_ROOT}" "${TOOL_SOURCE}" "tool source")
    _aros_host_c_file_generator_require_regular("${TOOL_SOURCE}" "tool source")
    file(SHA256 "${TOOL_SOURCE}" _actual_tool_hash)
    string(TOLOWER "${_actual_tool_hash}" _actual_tool_hash)
    string(TOLOWER "${TOOL_SHA256}" _expected_tool_hash)
    if(NOT _actual_tool_hash STREQUAL _expected_tool_hash)
        message(FATAL_ERROR
            "${NAME}: TOOL_SOURCE changed after configuration; update its pinned contract and rerun CMake")
    endif()
    if(SOURCE_MANIFEST_COUNT GREATER 0)
        math(EXPR _last "${SOURCE_MANIFEST_COUNT} - 1")
        set(_seen "")
        foreach(_index RANGE 0 ${_last})
            set(_path_var "SOURCE_MANIFEST_PATH_${_index}")
            set(_hash_var "SOURCE_MANIFEST_SHA256_${_index}")
            if(NOT DEFINED ${_path_var} OR NOT DEFINED ${_hash_var})
                message(FATAL_ERROR "${NAME}: incomplete source-manifest entry ${_index}")
            endif()
            set(_relative "${${_path_var}}")
            set(_expected "${${_hash_var}}")
            string(LENGTH "${_expected}" _expected_length)
            if(NOT _relative MATCHES "^[A-Za-z0-9_.+-]+(/[A-Za-z0-9_.+-]+)*$" OR
               _relative MATCHES "(^|/)\\.\\.?(/|$)" OR _relative MATCHES "[.]$" OR
               NOT _expected_length EQUAL 64 OR NOT _expected MATCHES "^[0-9a-f]+$")
                message(FATAL_ERROR "${NAME}: malformed source-manifest entry ${_index}")
            endif()
            string(TOLOWER "${_relative}" _folded)
            if(_folded IN_LIST _seen)
                message(FATAL_ERROR "${NAME}: duplicate case-folded source path ${_relative}")
            endif()
            list(APPEND _seen "${_folded}")
            set(_path "${SOURCE_ROOT}/${_relative}")
            cmake_path(NORMAL_PATH _path)
            _aros_host_c_file_generator_check_tree("${SOURCE_ROOT}" "${_path}" "source manifest path")
            _aros_host_c_file_generator_require_regular("${_path}" "source manifest file ${_relative}")
            file(SHA256 "${_path}" _actual)
            string(TOLOWER "${_actual}" _actual)
            string(TOLOWER "${_expected}" _expected)
            if(NOT _actual STREQUAL _expected)
                message(FATAL_ERROR "${NAME}: sealed source file changed: ${_relative}")
            endif()
        endforeach()
    endif()
endfunction()

function(_aros_hcfg_take_lock)
    set(_lock "${PRIVATE_DIRECTORY}/.host-c-file-generator.lock")
    if(IS_SYMLINK "${_lock}" OR IS_DIRECTORY "${_lock}")
        message(FATAL_ERROR "${NAME}: unsafe host-generator lock path")
    endif()
    if(EXISTS "${_lock}")
        _aros_host_c_file_generator_require_regular("${_lock}" "host-generator lock")
    endif()
    file(LOCK "${_lock}" GUARD PROCESS TIMEOUT 60 RESULT_VARIABLE _lock_result)
    if(NOT _lock_result STREQUAL "0")
        message(FATAL_ERROR "${NAME}: cannot acquire host-generator lock: ${_lock_result}")
    endif()
endfunction()

_aros_host_c_file_generator_check_tree("${BINARY_ROOT}" "${PRIVATE_DIRECTORY}" "private generator directory")
file(MAKE_DIRECTORY "${PRIVATE_DIRECTORY}")
_aros_hcfg_take_lock()
_aros_hcfg_verify_sources()

if(MODE STREQUAL "COMPILE")
    foreach(_required HOST_CC PRIVATE_TOOL COMPILE_FLAG_COUNT)
        if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
            message(FATAL_ERROR "${NAME}: COMPILE mode requires ${_required}")
        endif()
    endforeach()
    foreach(_var HOST_CC PRIVATE_TOOL)
        _aros_host_c_file_generator_reject_unsafe_path("${_var}" "${${_var}}")
        if(NOT IS_ABSOLUTE "${${_var}}")
            message(FATAL_ERROR "${NAME}: ${_var} must be absolute")
        endif()
    endforeach()
    if(NOT COMPILE_FLAG_COUNT MATCHES "^[0-9]+$" OR COMPILE_FLAG_COUNT GREATER 32)
        message(FATAL_ERROR "${NAME}: invalid compile-flag count")
    endif()
    aros_path_is_executable("${HOST_CC}" _compiler_ok)
    if(NOT _compiler_ok)
        message(FATAL_ERROR "${NAME}: host compiler is not executable: ${HOST_CC}")
    endif()
    find_program(_host_cc_file_test NAMES test PATHS /bin /usr/bin NO_DEFAULT_PATH)
    if(NOT _host_cc_file_test)
        message(FATAL_ERROR "${NAME}: cannot verify host compiler file type")
    endif()
    execute_process(COMMAND "${_host_cc_file_test}" -f "${HOST_CC}"
        RESULT_VARIABLE _host_cc_file_result)
    if(NOT _host_cc_file_result EQUAL 0)
        message(FATAL_ERROR "${NAME}: host compiler is not a regular file")
    endif()
    set(_gen_root "${BINARY_ROOT}/gen")
    cmake_path(NORMAL_PATH _gen_root)
    cmake_path(IS_PREFIX _gen_root "${PRIVATE_TOOL}" NORMALIZE _tool_owned)
    if(NOT _tool_owned)
        message(FATAL_ERROR "${NAME}: private compiler output escaped the binary gen tree")
    endif()
    get_filename_component(_tool_parent "${PRIVATE_TOOL}" DIRECTORY)
    _aros_host_c_file_generator_check_tree("${BINARY_ROOT}" "${_tool_parent}" "private tool parent")
    file(MAKE_DIRECTORY "${_tool_parent}")
    _aros_host_c_file_generator_check_tree("${BINARY_ROOT}" "${_tool_parent}" "private tool parent")
    set(_candidate "${PRIVATE_TOOL}.candidate")
    if(IS_SYMLINK "${PRIVATE_TOOL}" OR IS_DIRECTORY "${PRIVATE_TOOL}" OR
       IS_SYMLINK "${_candidate}" OR IS_DIRECTORY "${_candidate}")
        message(FATAL_ERROR "${NAME}: compiler output path is symlinked or not a file")
    endif()
    if(EXISTS "${PRIVATE_TOOL}")
        _aros_host_c_file_generator_require_regular("${PRIVATE_TOOL}" "existing private host executable")
    endif()
    if(EXISTS "${_candidate}")
        _aros_host_c_file_generator_require_regular("${_candidate}" "compiler candidate")
    endif()
    file(REMOVE "${_candidate}")
    set(_flags "")
    if(COMPILE_FLAG_COUNT GREATER 0)
        math(EXPR _last "${COMPILE_FLAG_COUNT} - 1")
        foreach(_i RANGE 0 ${_last})
            set(_flag_var "COMPILE_FLAG_${_i}")
            if(NOT DEFINED ${_flag_var})
                message(FATAL_ERROR "${NAME}: missing compile flag ${_i}")
            endif()
            set(_flag "${${_flag_var}}")
            set(_flag_ok FALSE)
            if(_flag STREQUAL "-g" OR _flag MATCHES "^-O[0-3s]$" OR
               _flag MATCHES "^-std=(c89|c90|c99|c11|c17|c18|c23|gnu89|gnu90|gnu99|gnu11|gnu17|gnu18|gnu23)$" OR
               _flag MATCHES "^-W(no-)?[A-Za-z0-9][A-Za-z0-9_-]*$")
                set(_flag_ok TRUE)
            endif()
            if(NOT _flag_ok OR "${_flag}" MATCHES "[;\"$\\\\\r\n]")
                message(FATAL_ERROR "${NAME}: unsafe compile flag '${_flag}'")
            endif()
            list(APPEND _flags "${_flag}")
        endforeach()
    endif()
    execute_process(
        COMMAND "${HOST_CC}" ${_flags} "${TOOL_SOURCE}" -o "${_candidate}"
        WORKING_DIRECTORY "${_tool_parent}"
        RESULT_VARIABLE _compile_result
        OUTPUT_VARIABLE _compile_stdout
        ERROR_VARIABLE _compile_stderr)
    if(NOT "${_compile_result}" STREQUAL "0")
        file(REMOVE "${_candidate}")
        message(FATAL_ERROR
            "${NAME}: host C compiler failed with status ${_compile_result}\n${_compile_stdout}\n${_compile_stderr}")
    endif()
    _aros_host_c_file_generator_require_regular("${_candidate}" "private compiler candidate")
    aros_path_is_executable("${_candidate}" _candidate_executable)
    if(NOT _candidate_executable)
        file(REMOVE "${_candidate}")
        message(FATAL_ERROR "${NAME}: host compiler did not produce an executable")
    endif()
    _aros_hcfg_verify_sources()
    if(IS_SYMLINK "${PRIVATE_TOOL}" OR IS_DIRECTORY "${PRIVATE_TOOL}")
        file(REMOVE "${_candidate}")
        message(FATAL_ERROR "${NAME}: private compiler output became unsafe")
    endif()
    file(RENAME "${_candidate}" "${PRIVATE_TOOL}" RESULT _install_result)
    if(NOT _install_result STREQUAL "0")
        file(REMOVE "${_candidate}")
        message(FATAL_ERROR "${NAME}: cannot install private host executable: ${_install_result}")
    endif()
    file(SHA256 "${PRIVATE_TOOL}" _compiled_tool_hash)
    string(TOLOWER "${_compiled_tool_hash}" _compiled_tool_hash)
    set(_tool_receipt "${PRIVATE_DIRECTORY}/.host-c-file-generator.tool.sha256")
    set(_receipt_candidate "${_tool_receipt}.candidate")
    if(IS_SYMLINK "${_tool_receipt}" OR IS_DIRECTORY "${_tool_receipt}" OR
       IS_SYMLINK "${_receipt_candidate}" OR IS_DIRECTORY "${_receipt_candidate}")
        message(FATAL_ERROR "${NAME}: private tool hash receipt is unsafe")
    endif()
    if(EXISTS "${_tool_receipt}")
        _aros_host_c_file_generator_require_regular("${_tool_receipt}" "existing private tool hash receipt")
    endif()
    if(EXISTS "${_receipt_candidate}")
        _aros_host_c_file_generator_require_regular("${_receipt_candidate}" "tool receipt candidate")
    endif()
    file(WRITE "${_receipt_candidate}" "${_compiled_tool_hash}\n")
    file(RENAME "${_receipt_candidate}" "${_tool_receipt}" RESULT _receipt_result)
    if(NOT _receipt_result STREQUAL "0")
        file(REMOVE "${_receipt_candidate}")
        message(FATAL_ERROR "${NAME}: cannot install private tool hash receipt")
    endif()
    return()
endif()

foreach(_required TOOL_EXECUTABLE INPUT_DIRECTORY INPUT_COUNT OUTPUT OUTPUT_BASENAME
        GENERATOR_ARGUMENT_COUNT CONTRACT_KEY)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "${NAME}: RUN mode requires ${_required}")
    endif()
endforeach()
foreach(_var TOOL_EXECUTABLE INPUT_DIRECTORY OUTPUT)
    _aros_host_c_file_generator_reject_unsafe_path("${_var}" "${${_var}}")
    if(NOT IS_ABSOLUTE "${${_var}}")
        message(FATAL_ERROR "${NAME}: ${_var} must be absolute")
    endif()
    cmake_path(NORMAL_PATH ${_var})
endforeach()
string(LENGTH "${CONTRACT_KEY}" _contract_key_length)
if(NOT _contract_key_length EQUAL 64 OR NOT CONTRACT_KEY MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "${NAME}: malformed generator contract key")
endif()
if(NOT INPUT_COUNT MATCHES "^[0-9]+$" OR INPUT_COUNT GREATER 16 OR
   NOT GENERATOR_ARGUMENT_COUNT MATCHES "^[0-9]+$" OR GENERATOR_ARGUMENT_COUNT GREATER 64)
    message(FATAL_ERROR "${NAME}: invalid input or argument count")
endif()
if(NOT EXISTS "${INPUT_DIRECTORY}" OR NOT IS_DIRECTORY "${INPUT_DIRECTORY}" OR
   IS_SYMLINK "${INPUT_DIRECTORY}")
    message(FATAL_ERROR "${NAME}: input cache is missing or symlinked")
endif()
_aros_host_c_file_generator_check_tree("${INPUT_DIRECTORY}" "${INPUT_DIRECTORY}" "input cache")
_aros_host_c_file_generator_check_tree("${BINARY_ROOT}" "${TOOL_EXECUTABLE}" "private host executable")
_aros_host_c_file_generator_require_regular("${TOOL_EXECUTABLE}" "private host executable")
aros_path_is_executable("${TOOL_EXECUTABLE}" _tool_ok)
if(NOT _tool_ok)
    message(FATAL_ERROR "${NAME}: private host executable is not executable")
endif()
set(_tool_receipt "${PRIVATE_DIRECTORY}/.host-c-file-generator.tool.sha256")
_aros_host_c_file_generator_require_regular("${_tool_receipt}" "private tool hash receipt")
file(READ "${_tool_receipt}" _expected_tool_hash)
string(STRIP "${_expected_tool_hash}" _expected_tool_hash)
string(LENGTH "${_expected_tool_hash}" _receipt_hash_length)
if(NOT _receipt_hash_length EQUAL 64 OR NOT _expected_tool_hash MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "${NAME}: malformed private tool hash receipt")
endif()
file(SHA256 "${TOOL_EXECUTABLE}" _actual_tool_hash)
string(TOLOWER "${_actual_tool_hash}" _actual_tool_hash)
if(NOT _actual_tool_hash STREQUAL _expected_tool_hash)
    message(FATAL_ERROR "${NAME}: private host executable changed after compilation")
endif()

set(_input_names "")
set(_input_hashes "")
set(_input_sizes "")
set(_folded_inputs "")
if(INPUT_COUNT GREATER 0)
    math(EXPR _input_last "${INPUT_COUNT} - 1")
    foreach(_i RANGE 0 ${_input_last})
        set(_name_var "INPUT_FILENAME_${_i}")
        set(_hash_var "INPUT_SHA256_${_i}")
        set(_size_var "INPUT_SIZE_${_i}")
        if(NOT DEFINED ${_name_var} OR NOT DEFINED ${_hash_var} OR NOT DEFINED ${_size_var})
            message(FATAL_ERROR "${NAME}: incomplete input declaration ${_i}")
        endif()
        set(_name "${${_name_var}}")
        set(_hash "${${_hash_var}}")
        set(_size "${${_size_var}}")
        string(LENGTH "${_hash}" _hash_len)
        string(TOLOWER "${_name}" _folded)
        if(NOT _name MATCHES "^[A-Za-z0-9][A-Za-z0-9._+-]*$" OR
           _name MATCHES "\\.\\." OR _name MATCHES "[.]$" OR
           NOT _hash_len EQUAL 64 OR NOT _hash MATCHES "^[0-9a-f]+$" OR
           NOT _size MATCHES "^[0-9]+$" OR _size LESS 1 OR _size GREATER 33554432 OR
           _folded IN_LIST _folded_inputs)
            message(FATAL_ERROR "${NAME}: malformed sealed input declaration ${_i}")
        endif()
        list(APPEND _folded_inputs "${_folded}")
        list(APPEND _input_names "${_name}")
        list(APPEND _input_hashes "${_hash}")
        list(APPEND _input_sizes "${_size}")
        set(_path "${INPUT_DIRECTORY}/${_name}")
        _aros_host_c_file_generator_check_tree("${INPUT_DIRECTORY}" "${_path}" "input file")
        _aros_host_c_file_generator_require_regular("${_path}" "input file ${_name}")
        file(SIZE "${_path}" _actual_size)
        file(SHA256 "${_path}" _actual_hash)
        string(TOLOWER "${_actual_hash}" _actual_hash)
        if(NOT _actual_size EQUAL _size OR NOT _actual_hash STREQUAL _hash)
            message(FATAL_ERROR "${NAME}: cached input changed after configuration: ${_name}")
        endif()
    endforeach()
endif()

set(_gen_root "${BINARY_ROOT}/gen")
cmake_path(NORMAL_PATH _gen_root)
cmake_path(IS_PREFIX _gen_root "${OUTPUT}" NORMALIZE _output_owned)
get_filename_component(_actual_output_basename "${OUTPUT}" NAME)
if(NOT _output_owned OR OUTPUT STREQUAL _gen_root OR
   NOT OUTPUT_BASENAME STREQUAL _actual_output_basename OR
   NOT OUTPUT_BASENAME MATCHES "^[A-Za-z0-9][A-Za-z0-9._+-]*$" OR
   OUTPUT_BASENAME MATCHES "\\.\\." OR OUTPUT_BASENAME MATCHES "[.]$")
    message(FATAL_ERROR "${NAME}: invalid or out-of-tree output declaration")
endif()
get_filename_component(_output_parent "${OUTPUT}" DIRECTORY)
_aros_host_c_file_generator_check_tree("${BINARY_ROOT}" "${_output_parent}" "output parent")
if(IS_SYMLINK "${OUTPUT}" OR IS_DIRECTORY "${OUTPUT}")
    message(FATAL_ERROR "${NAME}: output is symlinked or not regular")
endif()
if(EXISTS "${OUTPUT}")
    _aros_host_c_file_generator_require_regular("${OUTPUT}" "existing output")
endif()

set(_state_file "${PRIVATE_DIRECTORY}/.host-c-file-generator.state")
if(IS_SYMLINK "${_state_file}" OR IS_DIRECTORY "${_state_file}")
    message(FATAL_ERROR "${NAME}: generator state file is unsafe")
endif()
if(EXISTS "${_state_file}")
    _aros_host_c_file_generator_require_regular("${_state_file}" "generator state file")
endif()
if(EXISTS "${OUTPUT}" AND EXISTS "${_state_file}")
    file(READ "${_state_file}" _state)
    string(STRIP "${_state}" _state)
    file(SHA256 "${OUTPUT}" _output_hash)
    string(TOLOWER "${_output_hash}" _output_hash)
    if(_state STREQUAL "${CONTRACT_KEY}|${_output_hash}")
        message(STATUS "${NAME}: verified output is unchanged")
        return()
    endif()
endif()

get_filename_component(_output_parent "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_output_parent}")
_aros_host_c_file_generator_check_tree("${BINARY_ROOT}" "${_output_parent}" "output parent")
set(_stage_root "${PRIVATE_DIRECTORY}/stage")
_aros_host_c_file_generator_check_tree("${BINARY_ROOT}" "${_stage_root}" "staging directory")
file(REMOVE_RECURSE "${_stage_root}")
file(MAKE_DIRECTORY "${_stage_root}/input" "${_stage_root}/output")
_aros_host_c_file_generator_check_tree("${BINARY_ROOT}" "${_stage_root}/input" "staged input directory")
_aros_host_c_file_generator_check_tree("${BINARY_ROOT}" "${_stage_root}/output" "staged output directory")

if(INPUT_COUNT GREATER 0)
    math(EXPR _input_last "${INPUT_COUNT} - 1")
    foreach(_i RANGE 0 ${_input_last})
        set(_name_var "INPUT_FILENAME_${_i}")
        set(_hash_var "INPUT_SHA256_${_i}")
        set(_size_var "INPUT_SIZE_${_i}")
        set(_name "${${_name_var}}")
        set(_hash "${${_hash_var}}")
        set(_size "${${_size_var}}")
        set(_from "${INPUT_DIRECTORY}/${_name}")
        set(_to "${_stage_root}/input/${_name}")
        _aros_host_c_file_generator_require_regular("${_from}" "input file ${_name}")
        file(COPY_FILE "${_from}" "${_to}" RESULT _copy_result)
        if(NOT _copy_result STREQUAL "0")
            file(REMOVE_RECURSE "${_stage_root}")
            message(FATAL_ERROR "${NAME}: cannot stage input ${_name}: ${_copy_result}")
        endif()
        _aros_host_c_file_generator_require_regular("${_to}" "staged input ${_name}")
        file(SIZE "${_to}" _copied_size)
        file(SHA256 "${_to}" _copied_hash)
        string(TOLOWER "${_copied_hash}" _copied_hash)
        if(NOT _copied_size EQUAL _size OR NOT _copied_hash STREQUAL _hash)
            file(REMOVE_RECURSE "${_stage_root}")
            message(FATAL_ERROR "${NAME}: staged input differs from sealed digest: ${_name}")
        endif()
    endforeach()
endif()

set(_args "")
set(_arg_input_count 0)
set(_arg_output_count 0)
if(GENERATOR_ARGUMENT_COUNT GREATER 0)
    math(EXPR _arg_last "${GENERATOR_ARGUMENT_COUNT} - 1")
    foreach(_i RANGE 0 ${_arg_last})
        set(_var "GENERATOR_ARGUMENT_${_i}")
        if(NOT DEFINED ${_var})
            message(FATAL_ERROR "${NAME}: missing generator argument ${_i}")
        endif()
        set(_arg "${${_var}}")
        if(_arg STREQUAL "@INPUT_DIRECTORY@")
            math(EXPR _arg_input_count "${_arg_input_count} + 1")
            list(APPEND _args "${_stage_root}/input")
        elseif(_arg STREQUAL "@OUTPUT_DIRECTORY@")
            math(EXPR _arg_output_count "${_arg_output_count} + 1")
            list(APPEND _args "${_stage_root}/output")
        elseif(_arg MATCHES "^[A-Za-z0-9_+-][A-Za-z0-9_.+=:-]*$" AND
               NOT _arg MATCHES "\\.\\.")
            list(APPEND _args "${_arg}")
        else()
            file(REMOVE_RECURSE "${_stage_root}")
            message(FATAL_ERROR "${NAME}: unsafe generator argument")
        endif()
    endforeach()
endif()
if(NOT _arg_input_count EQUAL 1 OR NOT _arg_output_count EQUAL 1)
    file(REMOVE_RECURSE "${_stage_root}")
    message(FATAL_ERROR "${NAME}: generator arguments must name each stage directory once")
endif()

execute_process(
    COMMAND "${TOOL_EXECUTABLE}" ${_args}
    WORKING_DIRECTORY "${_stage_root}/output"
    RESULT_VARIABLE _generator_result
    OUTPUT_VARIABLE _generator_stdout
    ERROR_VARIABLE _generator_stderr)
if(NOT "${_generator_result}" STREQUAL "0")
    file(REMOVE_RECURSE "${_stage_root}")
    message(FATAL_ERROR
        "${NAME}: host C generator failed with status ${_generator_result}\n${_generator_stdout}\n${_generator_stderr}")
endif()

set(_staged_output "${_stage_root}/output/${OUTPUT_BASENAME}")
_aros_host_c_file_generator_check_tree("${_stage_root}" "${_stage_root}/output" "staged generator output directory")
if(NOT IS_DIRECTORY "${_stage_root}/output")
    file(REMOVE_RECURSE "${_stage_root}")
    message(FATAL_ERROR "${NAME}: generator replaced its output directory")
endif()
if(IS_SYMLINK "${_staged_output}" OR IS_DIRECTORY "${_staged_output}" OR
   NOT EXISTS "${_staged_output}")
    file(REMOVE_RECURSE "${_stage_root}")
    message(FATAL_ERROR "${NAME}: generator did not produce the required regular output")
endif()
_aros_host_c_file_generator_require_regular("${_staged_output}" "staged generator output")
file(GLOB _entries LIST_DIRECTORIES TRUE
    "${_stage_root}/output/*" "${_stage_root}/output/.[!.]*"
    "${_stage_root}/output/..?*")
list(LENGTH _entries _entry_count)
if(NOT _entry_count EQUAL 1 OR NOT _entries STREQUAL _staged_output)
    file(REMOVE_RECURSE "${_stage_root}")
    message(FATAL_ERROR "${NAME}: generator output directory contains unexpected entries")
endif()

set(_candidate "${OUTPUT}.candidate")
if(IS_SYMLINK "${OUTPUT}" OR IS_DIRECTORY "${OUTPUT}" OR
   IS_SYMLINK "${_candidate}" OR IS_DIRECTORY "${_candidate}")
    file(REMOVE_RECURSE "${_stage_root}")
    message(FATAL_ERROR "${NAME}: output or publication candidate became unsafe")
endif()
if(EXISTS "${_candidate}")
    _aros_host_c_file_generator_require_regular("${_candidate}" "existing publication candidate")
endif()
file(REMOVE "${_candidate}")
file(COPY_FILE "${_staged_output}" "${_candidate}" RESULT _copy_result)
if(NOT _copy_result STREQUAL "0")
    file(REMOVE_RECURSE "${_stage_root}")
    message(FATAL_ERROR "${NAME}: cannot stage publication: ${_copy_result}")
endif()
_aros_host_c_file_generator_require_regular("${_candidate}" "publication candidate")
file(SHA256 "${_candidate}" _published_hash)
string(TOLOWER "${_published_hash}" _published_hash)
if(IS_SYMLINK "${OUTPUT}" OR IS_DIRECTORY "${OUTPUT}")
    file(REMOVE "${_candidate}")
    file(REMOVE_RECURSE "${_stage_root}")
    message(FATAL_ERROR "${NAME}: output became unsafe before publication")
endif()
file(RENAME "${_candidate}" "${OUTPUT}" RESULT _rename_result)
if(NOT _rename_result STREQUAL "0")
    file(REMOVE "${_candidate}")
    file(REMOVE_RECURSE "${_stage_root}")
    message(FATAL_ERROR "${NAME}: atomic publication failed: ${_rename_result}")
endif()
set(_state_candidate "${_state_file}.candidate")
if(IS_SYMLINK "${_state_candidate}" OR IS_DIRECTORY "${_state_candidate}")
    file(REMOVE_RECURSE "${_stage_root}")
    message(FATAL_ERROR "${NAME}: state candidate is unsafe")
endif()
if(EXISTS "${_state_candidate}")
    _aros_host_c_file_generator_require_regular("${_state_candidate}" "existing state candidate")
endif()
file(WRITE "${_state_candidate}" "${CONTRACT_KEY}|${_published_hash}\n")
if(IS_SYMLINK "${_state_file}" OR IS_DIRECTORY "${_state_file}")
    file(REMOVE "${_state_candidate}")
    file(REMOVE_RECURSE "${_stage_root}")
    message(FATAL_ERROR "${NAME}: state path became unsafe")
endif()
file(RENAME "${_state_candidate}" "${_state_file}" RESULT _state_result)
if(NOT _state_result STREQUAL "0")
    file(REMOVE "${_state_candidate}")
    file(REMOVE_RECURSE "${_stage_root}")
    message(FATAL_ERROR "${NAME}: cannot update state: ${_state_result}")
endif()
file(REMOVE_RECURSE "${_stage_root}")
message(STATUS "${NAME}: generated ${OUTPUT}")
