cmake_minimum_required(VERSION 3.22)
include("${CMAKE_CURRENT_LIST_DIR}/HostHeaderAggregates.cmake")
if(NOT AG_PHASE STREQUAL "compile" AND NOT AG_PHASE STREQUAL "header" AND
   NOT AG_PHASE STREQUAL "validate-compile" AND NOT AG_PHASE STREQUAL "validate-header")
    message(FATAL_ERROR "Host header aggregate: unknown execution phase")
endif()
_aros_aggregate_path("${AG_BINARY_ROOT}" "${AG_RECIPE}" TRUE)
file(SHA256 "${AG_RECIPE}" _actual_hash)
if(NOT _actual_hash STREQUAL AG_RECIPE_SHA256)
    message(FATAL_ERROR "Host header aggregate: recipe differs from configure-time contract")
endif()
include("${AG_RECIPE}")
_aros_aggregate_path("${AG_BINARY_ROOT}" "${AG_TOOL}" FALSE)
if(AG_PHASE STREQUAL "compile" OR AG_PHASE STREQUAL "validate-compile")
    _aros_aggregate_path("${AG_SOURCE_ROOT}" "${AG_SOURCE}" TRUE)
    if(NOT IS_ABSOLUTE "${AG_COMPILER}" OR NOT EXISTS "${AG_COMPILER}" OR
       IS_DIRECTORY "${AG_COMPILER}")
        message(FATAL_ERROR "Host header aggregate: missing host compiler")
    endif()
    if(AG_PHASE STREQUAL "validate-compile")
        return()
    endif()
    string(RANDOM LENGTH 20 ALPHABET 0123456789abcdef _nonce)
    set(_temporary "${AG_TOOL}.${_nonce}.tmp")
    cmake_path(GET AG_TOOL PARENT_PATH _parent)
    file(MAKE_DIRECTORY "${_parent}")
    execute_process(COMMAND "${AG_COMPILER}" ${AG_FLAGS} -o "${_temporary}" "${AG_SOURCE}"
        RESULT_VARIABLE _result ERROR_VARIABLE _error)
    if(NOT _result STREQUAL "0")
        message(FATAL_ERROR "Host header aggregate: compiler failed (${_result}): ${_error}")
    endif()
    _aros_aggregate_path("${AG_BINARY_ROOT}" "${_temporary}" TRUE)
    _aros_aggregate_path("${AG_BINARY_ROOT}" "${AG_TOOL}" FALSE)
    file(RENAME "${_temporary}" "${AG_TOOL}" RESULT _publish)
else()
    _aros_aggregate_path("${AG_BINARY_ROOT}" "${AG_TOOL}" FALSE)
    set(_outputs "${AG_PRIMARY}")
    if(AG_MIRROR)
        list(APPEND _outputs "${AG_MIRROR}")
    endif()
    foreach(_output IN LISTS _outputs)
        _aros_aggregate_path("${AG_BINARY_ROOT}" "${_output}" FALSE)
    endforeach()
    _aros_aggregate_path("${AG_SDK_ROOT}" "${AG_PRIMARY}" FALSE)
    if(AG_MIRROR)
        _aros_aggregate_path("${AG_GENINC_ROOT}" "${AG_MIRROR}" FALSE)
    endif()
    _aros_aggregate_path("${AG_BINARY_ROOT}" "${AG_COMPLETION}" FALSE)
    if(AG_PHASE STREQUAL "validate-header")
        return()
    endif()
    _aros_aggregate_path("${AG_BINARY_ROOT}" "${AG_TOOL}" TRUE)
    # The completion output is written last. A failed multi-output update
    # therefore cannot become an apparently current result on the next build.
    file(REMOVE "${AG_COMPLETION}")
    string(RANDOM LENGTH 20 ALPHABET 0123456789abcdef _nonce)
    foreach(_output IN LISTS _outputs)
        cmake_path(GET _output PARENT_PATH _parent)
        file(MAKE_DIRECTORY "${_parent}")
    endforeach()
    set(_temporary "${AG_PRIMARY}.${_nonce}.tmp")
    execute_process(COMMAND "${AG_TOOL}" ${AG_ARGUMENTS}
        OUTPUT_FILE "${_temporary}" RESULT_VARIABLE _result ERROR_VARIABLE _error)
    if(NOT _result STREQUAL "0")
        message(FATAL_ERROR "Host header aggregate: generator failed (${_result}): ${_error}")
    endif()
    _aros_aggregate_path("${AG_BINARY_ROOT}" "${_temporary}" TRUE)
    foreach(_output IN LISTS _outputs)
        _aros_aggregate_path("${AG_BINARY_ROOT}" "${_output}" FALSE)
    endforeach()
    if(AG_MIRROR)
        set(_mirror_temporary "${AG_MIRROR}.${_nonce}.tmp")
        _aros_aggregate_path("${AG_BINARY_ROOT}" "${_mirror_temporary}" FALSE)
        file(COPY_FILE "${_temporary}" "${_mirror_temporary}" RESULT _stage)
        if(NOT _stage STREQUAL "0")
            message(FATAL_ERROR "Host header aggregate: cannot stage mirror: ${_stage}")
        endif()
        _aros_aggregate_path("${AG_BINARY_ROOT}" "${_mirror_temporary}" TRUE)
        _aros_aggregate_path("${AG_BINARY_ROOT}" "${AG_MIRROR}" FALSE)
        file(RENAME "${_mirror_temporary}" "${AG_MIRROR}" RESULT _mirror_publish)
        if(NOT _mirror_publish STREQUAL "0")
            message(FATAL_ERROR "Host header aggregate: cannot publish mirror: ${_mirror_publish}")
        endif()
    endif()
    _aros_aggregate_path("${AG_BINARY_ROOT}" "${AG_PRIMARY}" FALSE)
    file(RENAME "${_temporary}" "${AG_PRIMARY}" RESULT _publish)
    if(_publish STREQUAL "0")
        _aros_aggregate_path("${AG_BINARY_ROOT}" "${AG_COMPLETION}" FALSE)
        file(WRITE "${AG_COMPLETION}" "${AG_RECIPE_SHA256}\n")
    endif()
endif()
if(NOT _publish STREQUAL "0")
    message(FATAL_ERROR "Host header aggregate: cannot publish output: ${_publish}")
endif()
