cmake_minimum_required(VERSION 3.22)

function(_aros_literal_runner_assert_regular path label executable)
    find_program(_literal_runner_test_program NAMES test PATHS /usr/bin /bin NO_DEFAULT_PATH NO_CACHE REQUIRED)
    execute_process(COMMAND "${_literal_runner_test_program}" -f "${path}" RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Literal object runner: ${label} is not a regular file: ${path}")
    endif()
    if(executable)
        execute_process(COMMAND "${_literal_runner_test_program}" -x "${path}" RESULT_VARIABLE result)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Literal object runner: ${label} is not executable: ${path}")
        endif()
    endif()
endfunction()

function(_aros_literal_runner_assert_root root label)
    if(NOT IS_ABSOLUTE "${root}" OR NOT IS_DIRECTORY "${root}")
        message(FATAL_ERROR "Literal object runner: ${label} is not an existing directory")
    endif()
    if(IS_SYMLINK "${root}")
        message(FATAL_ERROR "Literal object runner: symlink ${label} refused: ${root}")
    endif()
endfunction()

function(_aros_literal_runner_check_absolute_chain path label)
    set(cursor "${path}")
    while(TRUE)
        if(IS_SYMLINK "${cursor}")
            message(FATAL_ERROR "Literal object runner: symlink ${label} path refused: ${cursor}")
        endif()
        cmake_path(GET cursor PARENT_PATH parent)
        if(parent STREQUAL cursor)
            break()
        endif()
        set(cursor "${parent}")
    endwhile()
endfunction()

function(_aros_literal_runner_check_path path boundary label)
    cmake_path(IS_PREFIX boundary "${path}" NORMALIZE inside)
    if(NOT inside OR path STREQUAL boundary)
        message(FATAL_ERROR "Literal object runner: ${label} escapes its declared root")
    endif()
    set(cursor "${path}")
    while(NOT cursor STREQUAL boundary)
        if(IS_SYMLINK "${cursor}")
            message(FATAL_ERROR "Literal object runner: symlink ${label} path refused: ${cursor}")
        endif()
        if(EXISTS "${cursor}" AND NOT cursor STREQUAL path AND NOT IS_DIRECTORY "${cursor}")
            message(FATAL_ERROR "Literal object runner: non-directory ${label} parent: ${cursor}")
        endif()
        cmake_path(GET cursor PARENT_PATH parent)
        if(parent STREQUAL cursor)
            message(FATAL_ERROR "Literal object runner: invalid ${label} root boundary")
        endif()
        set(cursor "${parent}")
    endwhile()
endfunction()

function(_aros_literal_runner_validate_declared_path raw role)
    if(IS_ABSOLUTE "${raw}")
        set(path "${raw}")
    else()
        cmake_path(ABSOLUTE_PATH raw BASE_DIRECTORY "${SOURCE_DIRECTORY}"
            NORMALIZE OUTPUT_VARIABLE path)
    endif()
    cmake_path(ABSOLUTE_PATH path NORMALIZE OUTPUT_VARIABLE path)
    cmake_path(IS_PREFIX SOURCE_ROOT "${path}" NORMALIZE in_source)
    cmake_path(IS_PREFIX BUILD_ROOT "${path}" NORMALIZE in_build)
    if(NOT in_source AND NOT in_build)
        message(FATAL_ERROR
            "Literal object runner: ${role} path left the declared source/build roots: ${path}")
    endif()
    if(in_source)
        set(boundary "${SOURCE_ROOT}")
    else()
        set(boundary "${BUILD_ROOT}")
    endif()
    if(NOT path STREQUAL boundary)
        _aros_literal_runner_check_path("${path}" "${boundary}" "declared ${role}")
        if(EXISTS "${path}" AND NOT IS_DIRECTORY "${path}")
            message(FATAL_ERROR "Literal object runner: declared ${role} path is not a directory: ${path}")
        endif()
    endif()
endfunction()

function(_aros_literal_runner_optional_regular path label)
    if(IS_SYMLINK "${path}")
        message(FATAL_ERROR "Literal object runner: symlink ${label} refused: ${path}")
    endif()
    if(EXISTS "${path}")
        _aros_literal_runner_assert_regular("${path}" "${label}" FALSE)
    endif()
endfunction()

if(NOT DEFINED COMMAND_FILE OR "${COMMAND_FILE}" STREQUAL "" OR
   NOT DEFINED COMMAND_ROOT OR "${COMMAND_ROOT}" STREQUAL "" OR
   NOT DEFINED VERIFY_ONLY OR NOT VERIFY_ONLY MATCHES "^(ON|OFF)$")
    message(FATAL_ERROR "Literal object runner requires a command file and verify mode")
endif()
if(NOT DEFINED COMMAND_SHA256 OR NOT COMMAND_SHA256 MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "Literal object runner requires a valid command digest")
endif()
string(LENGTH "${COMMAND_SHA256}" command_sha_length)
if(NOT command_sha_length EQUAL 64)
    message(FATAL_ERROR "Literal object runner requires a valid command digest")
endif()
cmake_path(ABSOLUTE_PATH COMMAND_ROOT NORMALIZE OUTPUT_VARIABLE command_root)
cmake_path(ABSOLUTE_PATH COMMAND_FILE NORMALIZE OUTPUT_VARIABLE command_file)
_aros_literal_runner_assert_root("${command_root}" "command root")
_aros_literal_runner_check_path("${command_file}" "${command_root}" "command file")
_aros_literal_runner_assert_regular("${command_file}" "command file" FALSE)
if(IS_SYMLINK "${command_file}")
    message(FATAL_ERROR "Literal object runner refuses a symlink command file")
endif()
file(SHA256 "${command_file}" actual_command_sha256)
if(NOT actual_command_sha256 STREQUAL COMMAND_SHA256)
    message(FATAL_ERROR "Literal object runner refuses a changed command file")
endif()
include("${command_file}")

foreach(key SOURCE SOURCE_ROOT BUILD_ROOT SOURCE_DIRECTORY OUTPUT DEPFILE COMPILER LANGUAGE)
    if(NOT DEFINED ${key} OR "${${key}}" STREQUAL "" OR
       "${${key}}" MATCHES "[;\n\r$]")
        message(FATAL_ERROR "Literal object runner requires one safe ${key}")
    endif()
endforeach()
if(NOT DEFINED ARGUMENTS)
    set(ARGUMENTS)
endif()

_aros_literal_runner_assert_root("${SOURCE_ROOT}" "source root")
_aros_literal_runner_assert_root("${BUILD_ROOT}" "build root")
_aros_literal_runner_check_absolute_chain("${COMPILER}" "compiler driver")
_aros_literal_runner_assert_regular("${COMPILER}" "compiler driver" TRUE)

if(NOT IS_ABSOLUTE "${SOURCE}" OR NOT IS_ABSOLUTE "${OUTPUT}" OR
   NOT IS_ABSOLUTE "${DEPFILE}" OR NOT IS_ABSOLUTE "${COMPILER}" OR
   NOT IS_ABSOLUTE "${SOURCE_DIRECTORY}")
    message(FATAL_ERROR "Literal object runner paths must be absolute")
endif()
cmake_path(ABSOLUTE_PATH SOURCE NORMALIZE OUTPUT_VARIABLE SOURCE)
cmake_path(ABSOLUTE_PATH OUTPUT NORMALIZE OUTPUT_VARIABLE OUTPUT)
cmake_path(ABSOLUTE_PATH DEPFILE NORMALIZE OUTPUT_VARIABLE DEPFILE)
cmake_path(ABSOLUTE_PATH SOURCE_DIRECTORY NORMALIZE OUTPUT_VARIABLE SOURCE_DIRECTORY)
cmake_path(IS_PREFIX SOURCE_ROOT "${SOURCE}" NORMALIZE source_inside)
cmake_path(IS_PREFIX SOURCE_ROOT "${SOURCE_DIRECTORY}" NORMALIZE workdir_inside)
cmake_path(IS_PREFIX BUILD_ROOT "${OUTPUT}" NORMALIZE output_in_build)
cmake_path(IS_PREFIX BUILD_ROOT "${DEPFILE}" NORMALIZE depfile_in_build)
cmake_path(GET SOURCE FILENAME source_name)
cmake_path(GET SOURCE PARENT_PATH source_parent)
cmake_path(GET OUTPUT FILENAME output_name)
set(gen_root "${BUILD_ROOT}/gen")
cmake_path(IS_PREFIX gen_root "${OUTPUT}" NORMALIZE output_in_gen)
if(NOT source_inside OR SOURCE STREQUAL SOURCE_ROOT OR NOT workdir_inside OR
   NOT SOURCE_DIRECTORY STREQUAL source_parent OR
   NOT source_name MATCHES "\.(c|cpp)$" OR
   NOT output_in_build OR NOT output_in_gen OR OUTPUT STREQUAL gen_root OR
   NOT output_name MATCHES "^[A-Za-z0-9][A-Za-z0-9_.+-]*\.o$" OR
   NOT depfile_in_build OR NOT DEPFILE STREQUAL "${OUTPUT}.d")
    message(FATAL_ERROR "Literal object runner received invalid source/output roles")
endif()

_aros_literal_runner_check_path("${SOURCE}" "${SOURCE_ROOT}" "source")
_aros_literal_runner_assert_regular("${SOURCE}" "source" FALSE)
_aros_literal_runner_check_path("${OUTPUT}" "${BUILD_ROOT}" "object output")
_aros_literal_runner_check_path("${DEPFILE}" "${BUILD_ROOT}" "dependency output")
_aros_literal_runner_optional_regular("${OUTPUT}" "object output")
_aros_literal_runner_optional_regular("${DEPFILE}" "dependency output")

set(expect_path_for "")
foreach(argument IN LISTS ARGUMENTS)
    if(NOT expect_path_for STREQUAL "")
        _aros_literal_runner_validate_declared_path("${argument}" "${expect_path_for}")
        set(expect_path_for "")
    elseif(argument STREQUAL "-I" OR argument STREQUAL "-isystem" OR
           argument STREQUAL "-iquote" OR argument STREQUAL "--sysroot" OR
           argument STREQUAL "-isysroot")
        set(expect_path_for "${argument}")
    elseif(argument MATCHES "^-I(.+)$")
        _aros_literal_runner_validate_declared_path("${CMAKE_MATCH_1}" "-I")
    elseif(argument MATCHES "^--sysroot=(.+)$")
        _aros_literal_runner_validate_declared_path("${CMAKE_MATCH_1}" "--sysroot")
    endif()
endforeach()
if(NOT expect_path_for STREQUAL "")
    message(FATAL_ERROR "Literal object runner: ${expect_path_for} is missing its validated path")
endif()

if(VERIFY_ONLY)
    return()
endif()

cmake_path(GET OUTPUT PARENT_PATH output_parent)
file(MAKE_DIRECTORY "${output_parent}")
_aros_literal_runner_check_path("${OUTPUT}" "${BUILD_ROOT}" "object output")
_aros_literal_runner_check_path("${DEPFILE}" "${BUILD_ROOT}" "dependency output")

string(RANDOM LENGTH 20 ALPHABET 0123456789abcdef suffix)
set(temporary_object "${OUTPUT}.literal-${suffix}.tmp")
set(temporary_depfile "${DEPFILE}.literal-${suffix}.tmp")
_aros_literal_runner_check_path("${temporary_object}" "${BUILD_ROOT}" "temporary object")
_aros_literal_runner_check_path("${temporary_depfile}" "${BUILD_ROOT}" "temporary dependency file")
if(EXISTS "${temporary_object}" OR IS_SYMLINK "${temporary_object}" OR
   EXISTS "${temporary_depfile}" OR IS_SYMLINK "${temporary_depfile}")
    message(FATAL_ERROR "Literal object runner found a temporary output collision")
endif()

execute_process(
    COMMAND "${COMPILER}" ${ARGUMENTS}
        -MD -MF "${temporary_depfile}" -MT "${OUTPUT}"
        -c "${SOURCE}" -o "${temporary_object}"
    WORKING_DIRECTORY "${SOURCE_DIRECTORY}"
    RESULT_VARIABLE compiler_result
    OUTPUT_VARIABLE compiler_stdout
    ERROR_VARIABLE compiler_stderr)
if(NOT compiler_result EQUAL 0)
    file(REMOVE "${temporary_object}" "${temporary_depfile}")
    message(FATAL_ERROR
        "Literal object compiler failed (${compiler_result}) for ${SOURCE}\n"
        "${compiler_stdout}${compiler_stderr}")
endif()

_aros_literal_runner_check_path("${temporary_object}" "${BUILD_ROOT}" "temporary object")
_aros_literal_runner_check_path("${temporary_depfile}" "${BUILD_ROOT}" "temporary dependency file")
_aros_literal_runner_assert_regular("${temporary_object}" "compiler output" FALSE)
_aros_literal_runner_assert_regular("${temporary_depfile}" "compiler dependency file" FALSE)
_aros_literal_runner_check_path("${OUTPUT}" "${BUILD_ROOT}" "object output")
_aros_literal_runner_check_path("${DEPFILE}" "${BUILD_ROOT}" "dependency output")

file(RENAME "${temporary_depfile}" "${DEPFILE}" RESULT rename_result)
if(NOT rename_result STREQUAL "0")
    file(REMOVE "${temporary_object}" "${temporary_depfile}")
    message(FATAL_ERROR "Literal object runner could not publish dependency file: ${rename_result}")
endif()
file(RENAME "${temporary_object}" "${OUTPUT}" RESULT rename_result)
if(NOT rename_result STREQUAL "0")
    file(REMOVE "${temporary_object}")
    message(FATAL_ERROR "Literal object runner could not publish object output: ${rename_result}")
endif()
_aros_literal_runner_check_path("${OUTPUT}" "${BUILD_ROOT}" "object output")
_aros_literal_runner_assert_regular("${OUTPUT}" "compiler output" FALSE)
