cmake_minimum_required(VERSION 3.22)

# Package the two ARM pipe-driver archives with one generated ABI table.
# Only closed paths and a verified target llvm-ar/objcopy may reach here.
foreach(_required IN ITEMS GCA_AR GCA_OBJCOPY GCA_NM GCA_GENERATED
        GCA_RAW_VC4 GCA_VC4_OUTPUT GCA_BIND_OBJECTS GCA_VC4_DRM_OBJECTS
        GCA_EXPECTED_MAP_SHA256)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "Mesa 26 GalliumCoreAPI lacks ${_required}")
    endif()
endforeach()
foreach(_input IN ITEMS "${GCA_AR}" "${GCA_OBJCOPY}" "${GCA_NM}"
        "${GCA_RAW_VC4}" "${GCA_GENERATED}/gca_redefs.txt"
        "${GCA_GENERATED}/gca_private.list")
    if(NOT EXISTS "${_input}" OR IS_DIRECTORY "${_input}" OR
       IS_SYMLINK "${_input}")
        message(FATAL_ERROR "Mesa 26 GalliumCoreAPI input is not a regular file: ${_input}")
    endif()
endforeach()
foreach(_tool IN ITEMS AR OBJCOPY NM)
    set(_tool_path_var "GCA_${_tool}")
    set(_tool_sha_var "GCA_${_tool}_SHA256")
    file(SHA256 "${${_tool_path_var}}" _actual_sha)
    if(NOT _actual_sha STREQUAL "${${_tool_sha_var}}")
        message(FATAL_ERROR "Mesa 26 GalliumCoreAPI target ${_tool} changed after configuration")
    endif()
endforeach()
file(SHA256 "${GCA_GENERATED}/gca_redefs.txt" _actual_map_sha)
if(NOT _actual_map_sha STREQUAL GCA_EXPECTED_MAP_SHA256)
    message(FATAL_ERROR "Mesa 26 GalliumCoreAPI import set changed without review")
endif()
if(GCA_RAW_V3D AND
   (NOT EXISTS "${GCA_RAW_V3D}" OR IS_DIRECTORY "${GCA_RAW_V3D}" OR
    IS_SYMLINK "${GCA_RAW_V3D}"))
    message(FATAL_ERROR "Mesa 26 GalliumCoreAPI V3D archive is not regular")
endif()

string(REPLACE "|" ";" _bind_objects "${GCA_BIND_OBJECTS}")
string(REPLACE "|" ";" _vc4_drm_objects "${GCA_VC4_DRM_OBJECTS}")
list(LENGTH _bind_objects _bind_count)
list(LENGTH _vc4_drm_objects _drm_count)
if(NOT _bind_count EQUAL 2 OR NOT _drm_count EQUAL 1)
    message(FATAL_ERROR "Mesa 26 GalliumCoreAPI object count changed")
endif()
foreach(_object IN LISTS _bind_objects _vc4_drm_objects)
    if(NOT EXISTS "${_object}" OR IS_DIRECTORY "${_object}" OR
       IS_SYMLINK "${_object}")
        message(FATAL_ERROR "Mesa 26 GalliumCoreAPI object is not regular: ${_object}")
    endif()
endforeach()

file(READ "${GCA_GENERATED}/gca_private.list" _private_text)
string(REPLACE "\n" ";" _private_objects "${_private_text}")
list(REMOVE_ITEM _private_objects "")
list(LENGTH _private_objects _private_count)
if(NOT _private_count EQUAL 5)
    message(FATAL_ERROR "Mesa 26 GalliumCoreAPI private object count changed")
endif()
file(REAL_PATH "${GCA_GENERATED}/private" _private_root)
foreach(_object IN LISTS _private_objects)
    if(NOT EXISTS "${_object}" OR IS_DIRECTORY "${_object}" OR
       IS_SYMLINK "${_object}")
        message(FATAL_ERROR "Mesa 26 GalliumCoreAPI private object is not regular")
    endif()
    get_filename_component(_parent "${_object}" DIRECTORY)
    file(REAL_PATH "${_parent}" _actual_parent)
    if(NOT _actual_parent STREQUAL _private_root)
        message(FATAL_ERROR "Mesa 26 GalliumCoreAPI private object escaped its output root")
    endif()
endforeach()

function(_gca_run)
    execute_process(COMMAND ${ARGN}
        RESULT_VARIABLE _result OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
    if(NOT _result EQUAL 0)
        message(FATAL_ERROR
            "Mesa 26 GalliumCoreAPI command failed (${_result}): ${_stderr}${_stdout}")
    endif()
endfunction()

set(_rewrite "--redefine-syms=${GCA_GENERATED}/gca_redefs.txt")
set(_transformed "${GCA_GENERATED}/transformed")
file(MAKE_DIRECTORY "${_transformed}")
set(_rewritten_private "")
foreach(_object IN LISTS _private_objects)
    get_filename_component(_name "${_object}" NAME)
    set(_output "${_transformed}/${_name}")
    _gca_run("${GCA_OBJCOPY}" "${_rewrite}" "${_object}" "${_output}")
    list(APPEND _rewritten_private "${_output}")
endforeach()

list(GET _vc4_drm_objects 0 _vc4_drm_object)
set(_rewritten_drm "${_transformed}/aros_drm_vc4.o")
_gca_run("${GCA_OBJCOPY}" "${_rewrite}"
    "${_vc4_drm_object}" "${_rewritten_drm}")

foreach(_driver IN ITEMS vc4 v3d)
    if(_driver STREQUAL "vc4")
        set(_input "${GCA_RAW_VC4}")
        set(_output "${GCA_VC4_OUTPUT}")
    else()
        if(NOT GCA_RAW_V3D)
            continue()
        endif()
        set(_input "${GCA_RAW_V3D}")
        set(_output "${GCA_V3D_OUTPUT}")
    endif()
    get_filename_component(_output_dir "${_output}" DIRECTORY)
    file(MAKE_DIRECTORY "${_output_dir}")
    set(_temporary "${_output}.pending")
    file(REMOVE "${_temporary}")
    _gca_run("${GCA_OBJCOPY}" "${_rewrite}" "${_input}" "${_temporary}")
    set(_members ${_bind_objects} ${_rewritten_private})
    if(_driver STREQUAL "vc4")
        list(APPEND _members "${_rewritten_drm}")
    endif()
    _gca_run("${GCA_AR}" rcsD "${_temporary}" ${_members})
    file(RENAME "${_temporary}" "${_output}")
endforeach()
