# Runtime validation, GNU ld -r, localization, and atomic publication.
# Configuration is JSON data and its digest is checked before parsing.

cmake_minimum_required(VERSION 3.22)

function(_aros_native_kobj_is_unsafe out_var value)
    set(_unsafe FALSE)
    if("${value}" MATCHES "[;\"$|]" OR "${value}" MATCHES "[\r\n]")
        set(_unsafe TRUE)
    endif()
    string(FIND "${value}" "\\" _backslash)
    if(NOT _backslash EQUAL -1)
        set(_unsafe TRUE)
    endif()
    set(${out_var} "${_unsafe}" PARENT_SCOPE)
endfunction()
function(_aros_native_kobj_is_unsafe_encoded out_var value)
    set(_unsafe FALSE)
    if("${value}" MATCHES "[;\"$]" OR "${value}" MATCHES "[\r\n]")
        set(_unsafe TRUE)
    endif()
    string(FIND "${value}" "\\" _backslash)
    if(NOT _backslash EQUAL -1)
        set(_unsafe TRUE)
    endif()
    set(${out_var} "${_unsafe}" PARENT_SCOPE)
endfunction()

foreach(_name IN ITEMS CONFIG EXPECTED_SHA256 EXPECTED_ROOT OBJECT_COUNT ARCHIVE_COUNT)
    if(NOT DEFINED AROS_NATIVE_KOBJ_${_name} OR
       "${AROS_NATIVE_KOBJ_${_name}}" STREQUAL "")
        message(FATAL_ERROR "Native KOBJ runner: missing ${_name}")
    endif()
endforeach()
string(LENGTH "${AROS_NATIVE_KOBJ_EXPECTED_SHA256}" _sha_length)
if(NOT _sha_length EQUAL 64 OR
   NOT AROS_NATIVE_KOBJ_EXPECTED_SHA256 MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "Native KOBJ runner: invalid configuration digest")
endif()
if(NOT AROS_NATIVE_KOBJ_OBJECT_COUNT MATCHES "^[0-9]+$")
    message(FATAL_ERROR "Native KOBJ runner: invalid object count")
endif()
if(NOT AROS_NATIVE_KOBJ_ARCHIVE_COUNT MATCHES "^[0-9]+$")
    message(FATAL_ERROR "Native KOBJ runner: invalid archive count")
endif()

set(_root "${AROS_NATIVE_KOBJ_EXPECTED_ROOT}")
set(_config "${AROS_NATIVE_KOBJ_CONFIG}")
_aros_native_kobj_is_unsafe(_unsafe_root "${_root}")
_aros_native_kobj_is_unsafe(_unsafe_config "${_config}")
if(NOT IS_ABSOLUTE "${_root}" OR _unsafe_root OR
   NOT IS_ABSOLUTE "${_config}" OR _unsafe_config)
    message(FATAL_ERROR "Native KOBJ runner: unsafe configuration path")
endif()
cmake_path(ABSOLUTE_PATH _root NORMALIZE OUTPUT_VARIABLE _root)
cmake_path(ABSOLUTE_PATH _config NORMALIZE OUTPUT_VARIABLE _config)
set(_AROS_NATIVE_KOBJ_CONFIG "${_config}")
cmake_path(IS_PREFIX _root "${_config}" NORMALIZE _config_inside)
if(NOT _config_inside OR "${_config}" STREQUAL "${_root}" OR
   NOT EXISTS "${_config}" OR IS_DIRECTORY "${_config}" OR IS_SYMLINK "${_config}")
    message(FATAL_ERROR "Native KOBJ runner: configuration is outside the build tree")
endif()
file(REAL_PATH "${_root}" _root_real)
set(_walk "${_root}")
cmake_path(RELATIVE_PATH _config BASE_DIRECTORY "${_root}" OUTPUT_VARIABLE _relative)
string(REPLACE "/" ";" _parts "${_relative}")
foreach(_part IN LISTS _parts)
    set(_walk "${_walk}/${_part}")
    if(IS_SYMLINK "${_walk}")
        message(FATAL_ERROR "Native KOBJ runner: configuration path crosses a symlink")
    endif()
endforeach()
file(REAL_PATH "${_config}" _config_real)
cmake_path(IS_PREFIX _root_real "${_config_real}" NORMALIZE _config_real_inside)
if(NOT _config_real_inside)
    message(FATAL_ERROR "Native KOBJ runner: configuration escapes the physical build tree")
endif()
file(READ "${_config}" _json)
string(SHA256 _actual_sha "${_json}")
if(NOT _actual_sha STREQUAL AROS_NATIVE_KOBJ_EXPECTED_SHA256)
    message(FATAL_ERROR "Native KOBJ runner: configuration digest changed after configure")
endif()
string(JSON _json_type ERROR_VARIABLE _json_error TYPE "${_json}")
if(_json_error OR NOT _json_type STREQUAL "OBJECT")
    message(FATAL_ERROR "Native KOBJ runner: configuration JSON is invalid")
endif()

function(_aros_native_kobj_json_string key out_var)
    string(JSON _type ERROR_VARIABLE _error TYPE "${_json}" "${key}")
    if(_error OR NOT _type STREQUAL "STRING")
        message(FATAL_ERROR "Native KOBJ runner: invalid configuration field ${key}")
    endif()
    string(JSON _value ERROR_VARIABLE _error GET "${_json}" "${key}")
    if(_error)
        message(FATAL_ERROR "Native KOBJ runner: unreadable configuration field ${key}")
    endif()
    set(${out_var} "${_value}" PARENT_SCOPE)
endfunction()

function(_aros_native_kobj_json_array key out_var)
    string(JSON _type ERROR_VARIABLE _error TYPE "${_json}" "${key}")
    if(_error OR NOT _type STREQUAL "ARRAY")
        message(FATAL_ERROR "Native KOBJ runner: invalid configuration array ${key}")
    endif()
    string(JSON _length ERROR_VARIABLE _error LENGTH "${_json}" "${key}")
    if(_error)
        message(FATAL_ERROR "Native KOBJ runner: unreadable configuration array ${key}")
    endif()
    set(_values "")
    if(_length GREATER 0)
        math(EXPR _last "${_length} - 1")
        foreach(_index RANGE 0 ${_last})
            string(JSON _item_type ERROR_VARIABLE _error TYPE
                "${_json}" "${key}" ${_index})
            if(_error OR NOT _item_type STREQUAL "STRING")
                message(FATAL_ERROR "Native KOBJ runner: non-string in ${key}")
            endif()
            string(JSON _item ERROR_VARIABLE _error GET
                "${_json}" "${key}" ${_index})
            if(_error)
                message(FATAL_ERROR "Native KOBJ runner: unreadable value in ${key}")
            endif()
            list(APPEND _values "${_item}")
        endforeach()
    endif()
    set(${out_var} "${_values}" PARENT_SCOPE)
endfunction()

foreach(_field IN ITEMS OWNER OUTPUT STAGE REPORT BUILD_ROOT SOURCE_ROOT COLLECTOR
        LINKER NM OBJCOPY LIBDIR RUNNER)
    _aros_native_kobj_json_string("${_field}" "_AROS_NATIVE_KOBJ_${_field}")
endforeach()
foreach(_field IN ITEMS OBJECT_SPECS ARCHIVE_TARGETS LINK_PREFIX LINK_SUFFIX
        STATIC_INPUTS SCRIPT_INPUTS DEPENDENCY_FILES)
    _aros_native_kobj_json_array("${_field}" "_AROS_NATIVE_KOBJ_${_field}")
endforeach()
cmake_path(ABSOLUTE_PATH _AROS_NATIVE_KOBJ_BUILD_ROOT NORMALIZE
    OUTPUT_VARIABLE _AROS_NATIVE_KOBJ_BUILD_ROOT)
cmake_path(ABSOLUTE_PATH _AROS_NATIVE_KOBJ_SOURCE_ROOT NORMALIZE
    OUTPUT_VARIABLE _AROS_NATIVE_KOBJ_SOURCE_ROOT)
if(NOT _AROS_NATIVE_KOBJ_BUILD_ROOT STREQUAL _root OR
   NOT IS_DIRECTORY "${_AROS_NATIVE_KOBJ_BUILD_ROOT}" OR
   NOT IS_DIRECTORY "${_AROS_NATIVE_KOBJ_SOURCE_ROOT}")
    message(FATAL_ERROR "Native KOBJ runner: configured roots do not match invocation")
endif()

set(_AROS_NATIVE_KOBJ_ACTION_STARTED FALSE)
function(_aros_native_kobj_cleanup_stage)
    if(NOT _AROS_NATIVE_KOBJ_ACTION_STARTED OR
       NOT EXISTS "${_AROS_NATIVE_KOBJ_STAGE}" OR
       IS_DIRECTORY "${_AROS_NATIVE_KOBJ_STAGE}" OR
       IS_SYMLINK "${_AROS_NATIVE_KOBJ_STAGE}")
        return()
    endif()
    get_filename_component(_parent "${_AROS_NATIVE_KOBJ_STAGE}" DIRECTORY)
    file(REAL_PATH "${_AROS_NATIVE_KOBJ_BUILD_ROOT}" _build_real)
    file(REAL_PATH "${_parent}" _parent_real)
    cmake_path(IS_PREFIX _build_real "${_parent_real}" NORMALIZE _parent_inside)
    if(_parent_inside)
        file(REMOVE "${_AROS_NATIVE_KOBJ_STAGE}")
    endif()
endfunction()
function(_aros_native_kobj_fail reason)
    _aros_native_kobj_cleanup_stage()
    message(FATAL_ERROR "Native KOBJ ${_AROS_NATIVE_KOBJ_OWNER}: ${reason}")
endfunction()

function(_aros_native_kobj_check_path path root label output_path)
    _aros_native_kobj_is_unsafe(_unsafe "${path}")
    if(NOT IS_ABSOLUTE "${path}" OR _unsafe)
        _aros_native_kobj_fail("unsafe ${label} path: ${path}")
    endif()
    cmake_path(ABSOLUTE_PATH path NORMALIZE OUTPUT_VARIABLE _path)
    cmake_path(ABSOLUTE_PATH root NORMALIZE OUTPUT_VARIABLE _root)
    cmake_path(IS_PREFIX _root "${_path}" NORMALIZE _inside)
    if(NOT _inside OR "${_path}" STREQUAL "${_root}")
        _aros_native_kobj_fail("${label} escapes configured root: ${_path}")
    endif()
    file(REAL_PATH "${_root}" _root_real)
    if(output_path)
        set(_walk "${_root}")
        cmake_path(RELATIVE_PATH _path BASE_DIRECTORY "${_root}" OUTPUT_VARIABLE _relative)
        string(REPLACE "/" ";" _parts "${_relative}")
        foreach(_part IN LISTS _parts)
            set(_walk "${_walk}/${_part}")
            if(IS_SYMLINK "${_walk}")
                _aros_native_kobj_fail("${label} crosses symlinked path ${_walk}")
            endif()
        endforeach()
    endif()
    set(_probe "${_path}")
    while(NOT EXISTS "${_probe}" AND NOT IS_SYMLINK "${_probe}")
        get_filename_component(_parent "${_probe}" DIRECTORY)
        if(_parent STREQUAL _probe)
            break()
        endif()
        set(_probe "${_parent}")
    endwhile()
    file(REAL_PATH "${_probe}" _probe_real)
    cmake_path(IS_PREFIX _root_real "${_probe_real}" NORMALIZE _physical_inside)
    if(NOT _physical_inside)
        _aros_native_kobj_fail("${label} resolves outside configured root: ${_path}")
    endif()
    if(output_path AND IS_SYMLINK "${_path}")
        _aros_native_kobj_fail("${label} is a symlink: ${_path}")
    endif()
    if(IS_SYMLINK "${_path}" AND NOT EXISTS "${_path}")
        _aros_native_kobj_fail("${label} is a dangling symlink: ${_path}")
    endif()
    if(EXISTS "${_path}")
        if(IS_DIRECTORY "${_path}" AND NOT label STREQUAL "LIBDIR")
            _aros_native_kobj_fail("${label} is a directory: ${_path}")
        endif()
        file(REAL_PATH "${_path}" _real)
        cmake_path(IS_PREFIX _root_real "${_real}" NORMALIZE _real_inside)
        if(NOT _real_inside)
            _aros_native_kobj_fail("${label} resolves outside configured root: ${_path}")
        endif()
    endif()
endfunction()
function(_aros_native_kobj_check_regular path label)
    if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
        _aros_native_kobj_fail("${label} is missing or not a file: ${path}")
    endif()
    file(SIZE "${path}" _size)
    if(_size LESS 1)
        _aros_native_kobj_fail("${label} is empty: ${path}")
    endif()
endfunction()
function(_aros_native_kobj_check_tool path label)
    _aros_native_kobj_is_unsafe(_unsafe "${path}")
    if(NOT IS_ABSOLUTE "${path}" OR _unsafe OR
       NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
        _aros_native_kobj_fail("${label} tool is unavailable: ${path}")
    endif()
    file(REAL_PATH "${path}" _real_tool)
    if(NOT _real_tool STREQUAL path)
        _aros_native_kobj_fail("${label} tool changed canonical path: ${path}")
    endif()
endfunction()
function(_aros_native_kobj_reject_output_alias path label)
    file(REAL_PATH "${path}" _input_real)
    foreach(_output_candidate IN ITEMS
            "${_AROS_NATIVE_KOBJ_OUTPUT}" "${_AROS_NATIVE_KOBJ_STAGE}"
            "${_AROS_NATIVE_KOBJ_REPORT}")
        cmake_path(ABSOLUTE_PATH _output_candidate NORMALIZE
            OUTPUT_VARIABLE _output_normalized)
        if(EXISTS "${_output_normalized}")
            file(REAL_PATH "${_output_normalized}" _output_real)
        else()
            set(_output_real "${_output_normalized}")
        endif()
        if(_input_real STREQUAL _output_real)
            _aros_native_kobj_fail(
                "${label} resolves to OUTPUT or STAGE: ${path}")
        endif()
    endforeach()
endfunction()

_aros_native_kobj_check_path("${_AROS_NATIVE_KOBJ_OUTPUT}"
    "${_AROS_NATIVE_KOBJ_BUILD_ROOT}" OUTPUT TRUE)
_aros_native_kobj_check_path("${_AROS_NATIVE_KOBJ_STAGE}"
    "${_AROS_NATIVE_KOBJ_BUILD_ROOT}" STAGE TRUE)
_aros_native_kobj_check_path("${_AROS_NATIVE_KOBJ_REPORT}"
    "${_AROS_NATIVE_KOBJ_BUILD_ROOT}" "set report" TRUE)
if(_AROS_NATIVE_KOBJ_OUTPUT STREQUAL _AROS_NATIVE_KOBJ_STAGE OR
   _AROS_NATIVE_KOBJ_OUTPUT STREQUAL _AROS_NATIVE_KOBJ_REPORT OR
   _AROS_NATIVE_KOBJ_STAGE STREQUAL _AROS_NATIVE_KOBJ_REPORT)
    _aros_native_kobj_fail("OUTPUT, STAGE, and REPORT paths collide")
endif()
_aros_native_kobj_check_path("${_AROS_NATIVE_KOBJ_LIBDIR}"
    "${_AROS_NATIVE_KOBJ_BUILD_ROOT}" LIBDIR FALSE)
if(NOT IS_DIRECTORY "${_AROS_NATIVE_KOBJ_LIBDIR}")
    _aros_native_kobj_fail("LIBDIR is unavailable: ${_AROS_NATIVE_KOBJ_LIBDIR}")
endif()
foreach(_tool IN ITEMS COLLECTOR LINKER NM OBJCOPY)
    _aros_native_kobj_check_tool("${_AROS_NATIVE_KOBJ_${_tool}}" "${_tool}")
    _aros_native_kobj_reject_output_alias(
        "${_AROS_NATIVE_KOBJ_${_tool}}" "${_tool} tool")
endforeach()
foreach(_input IN LISTS _AROS_NATIVE_KOBJ_STATIC_INPUTS)
    cmake_path(IS_PREFIX _AROS_NATIVE_KOBJ_BUILD_ROOT "${_input}"
        NORMALIZE _input_in_build)
    if(_input_in_build)
        set(_input_root "${_AROS_NATIVE_KOBJ_BUILD_ROOT}")
    else()
        set(_input_root "${_AROS_NATIVE_KOBJ_SOURCE_ROOT}")
    endif()
    _aros_native_kobj_check_path("${_input}" "${_input_root}" "static input" FALSE)
    _aros_native_kobj_check_regular("${_input}" "static input")
    _aros_native_kobj_reject_output_alias("${_input}" "static input")
endforeach()
_aros_native_kobj_is_unsafe(_unsafe_runner "${_AROS_NATIVE_KOBJ_RUNNER}")
if(NOT IS_ABSOLUTE "${_AROS_NATIVE_KOBJ_RUNNER}" OR _unsafe_runner OR
   NOT EXISTS "${_AROS_NATIVE_KOBJ_RUNNER}" OR
   IS_DIRECTORY "${_AROS_NATIVE_KOBJ_RUNNER}")
    _aros_native_kobj_fail("runner script is unavailable: ${_AROS_NATIVE_KOBJ_RUNNER}")
endif()
file(REAL_PATH "${_AROS_NATIVE_KOBJ_RUNNER}" _runner_real)
if(NOT _runner_real STREQUAL _AROS_NATIVE_KOBJ_RUNNER)
    _aros_native_kobj_fail("runner script changed canonical path: ${_AROS_NATIVE_KOBJ_RUNNER}")
endif()
_aros_native_kobj_check_regular("${_AROS_NATIVE_KOBJ_RUNNER}" "runner script")
_aros_native_kobj_reject_output_alias(
    "${_AROS_NATIVE_KOBJ_RUNNER}" "runner script")
foreach(_input IN LISTS _AROS_NATIVE_KOBJ_DEPENDENCY_FILES)
    cmake_path(IS_PREFIX _AROS_NATIVE_KOBJ_BUILD_ROOT "${_input}"
        NORMALIZE _dependency_in_build)
    if(_dependency_in_build)
        set(_dependency_root "${_AROS_NATIVE_KOBJ_BUILD_ROOT}")
    else()
        set(_dependency_root "${_AROS_NATIVE_KOBJ_SOURCE_ROOT}")
    endif()
    _aros_native_kobj_check_path(
        "${_input}" "${_dependency_root}" "file dependency" FALSE)
    if(NOT EXISTS "${_input}" OR IS_DIRECTORY "${_input}")
        _aros_native_kobj_fail("file dependency was not materialized: ${_input}")
    endif()
    _aros_native_kobj_reject_output_alias("${_input}" "file dependency")
endforeach()
_aros_native_kobj_check_path(
    "${_AROS_NATIVE_KOBJ_CONFIG}" "${_AROS_NATIVE_KOBJ_BUILD_ROOT}"
    "sealed configuration" FALSE)
_aros_native_kobj_check_regular("${_AROS_NATIVE_KOBJ_CONFIG}" "sealed configuration")
_aros_native_kobj_reject_output_alias(
    "${_AROS_NATIVE_KOBJ_CONFIG}" "sealed configuration")

string(JSON _archive_count LENGTH "${_json}" ARCHIVE_TARGETS)
if(NOT _archive_count EQUAL AROS_NATIVE_KOBJ_ARCHIVE_COUNT)
    _aros_native_kobj_fail("archive target count differs from sealed configuration")
endif()
set(_archive_files "")
if(_archive_count GREATER 0)
    math(EXPR _last_archive "${_archive_count} - 1")
    foreach(_index RANGE 0 ${_last_archive})
        set(_archive_variable "AROS_NATIVE_KOBJ_ARCHIVE_FILE_${_index}")
        if(NOT DEFINED ${_archive_variable})
            _aros_native_kobj_fail("missing resolved archive file ${_index}")
        endif()
        set(_archive_file "${${_archive_variable}}")
        if(NOT IS_ABSOLUTE "${_archive_file}")
            _aros_native_kobj_fail("resolved archive path is not absolute")
        endif()
        _aros_native_kobj_check_path("${_archive_file}"
            "${_AROS_NATIVE_KOBJ_BUILD_ROOT}" "resolved archive" FALSE)
        _aros_native_kobj_check_regular("${_archive_file}" "resolved archive")
        _aros_native_kobj_reject_output_alias("${_archive_file}" "resolved archive")
        if(NOT _archive_file IN_LIST _archive_files)
            list(APPEND _archive_files "${_archive_file}")
        endif()
    endforeach()
endif()
set(_reserved_inputs "${_AROS_NATIVE_KOBJ_COLLECTOR}"
    "${_AROS_NATIVE_KOBJ_LINKER}" "${_AROS_NATIVE_KOBJ_NM}"
    "${_AROS_NATIVE_KOBJ_OBJCOPY}" ${_AROS_NATIVE_KOBJ_STATIC_INPUTS}
    "${_AROS_NATIVE_KOBJ_RUNNER}" "${_AROS_NATIVE_KOBJ_CONFIG}"
    ${_AROS_NATIVE_KOBJ_DEPENDENCY_FILES} ${_archive_files})
set(_reserved_tools_archives "${_AROS_NATIVE_KOBJ_COLLECTOR}"
    "${_AROS_NATIVE_KOBJ_LINKER}" "${_AROS_NATIVE_KOBJ_NM}"
    "${_AROS_NATIVE_KOBJ_OBJCOPY}" "${_AROS_NATIVE_KOBJ_RUNNER}"
    "${_AROS_NATIVE_KOBJ_CONFIG}" ${_archive_files})
if(_AROS_NATIVE_KOBJ_OUTPUT IN_LIST _reserved_inputs OR
   _AROS_NATIVE_KOBJ_STAGE IN_LIST _reserved_inputs OR
   _AROS_NATIVE_KOBJ_REPORT IN_LIST _reserved_inputs)
    _aros_native_kobj_fail("output, stage, or report collides with a tool or link input")
endif()

string(JSON _spec_count LENGTH "${_json}" OBJECT_SPECS)
if(NOT _spec_count EQUAL AROS_NATIVE_KOBJ_OBJECT_COUNT OR _spec_count LESS 1)
    _aros_native_kobj_fail("object count differs from sealed source order")
endif()
set(_objects "")
set(_seen_objects "")
math(EXPR _last_spec "${_spec_count} - 1")
foreach(_index RANGE 0 ${_last_spec})
    set(_object_variable "AROS_NATIVE_KOBJ_OBJECT_${_index}")
    if(NOT DEFINED ${_object_variable})
        _aros_native_kobj_fail("missing indexed object input ${_index}")
    endif()
    set(_raw "${${_object_variable}}")
    string(JSON _spec GET "${_json}" OBJECT_SPECS ${_index})
    if(_spec MATCHES "^path:(.+)$")
        set(_object_path "${CMAKE_MATCH_1}")
        if(NOT _raw STREQUAL _object_path)
            _aros_native_kobj_fail("object ${_index} differs from sealed path")
        endif()
        set(_expanded "${_raw}")
        set(_target_objects FALSE)
    elseif(_spec MATCHES "^target:[A-Za-z0-9_.:+-]+$")
        _aros_native_kobj_is_unsafe_encoded(_unsafe_encoded "${_raw}")
        if(_unsafe_encoded)
            _aros_native_kobj_fail("target object ${_index} has unsafe encoding")
        endif()
        string(REPLACE "|" ";" _expanded "${_raw}")
        set(_target_objects TRUE)
    else()
        _aros_native_kobj_fail("malformed object specification ${_index}")
    endif()
    if(NOT _expanded)
        _aros_native_kobj_fail("object ${_index} expanded to an empty list")
    endif()
    foreach(_object IN LISTS _expanded)
        _aros_native_kobj_is_unsafe(_unsafe_object "${_object}")
        if(NOT IS_ABSOLUTE "${_object}" OR _unsafe_object)
            _aros_native_kobj_fail("unsafe object input path: ${_object}")
        endif()
        cmake_path(ABSOLUTE_PATH _object NORMALIZE OUTPUT_VARIABLE _object)
        if(_target_objects)
            set(_object_root "${_AROS_NATIVE_KOBJ_BUILD_ROOT}")
        else()
            cmake_path(IS_PREFIX _AROS_NATIVE_KOBJ_BUILD_ROOT "${_object}"
                NORMALIZE _object_in_build)
            if(_object_in_build)
                set(_object_root "${_AROS_NATIVE_KOBJ_BUILD_ROOT}")
            else()
                set(_object_root "${_AROS_NATIVE_KOBJ_SOURCE_ROOT}")
            endif()
        endif()
        _aros_native_kobj_check_path("${_object}" "${_object_root}" "object input" FALSE)
        _aros_native_kobj_check_regular("${_object}" "object input")
        _aros_native_kobj_reject_output_alias("${_object}" "object input")
        if(_object STREQUAL _AROS_NATIVE_KOBJ_OUTPUT OR
           _object STREQUAL _AROS_NATIVE_KOBJ_STAGE)
            _aros_native_kobj_fail("object input collides with output or stage")
        endif()
        if(_object IN_LIST _reserved_tools_archives OR
           _object IN_LIST _AROS_NATIVE_KOBJ_SCRIPT_INPUTS)
            _aros_native_kobj_fail("object input collides with a tool, archive, or linker script")
        endif()
        if(NOT _object IN_LIST _seen_objects)
            list(APPEND _seen_objects "${_object}")
            list(APPEND _objects "${_object}")
        endif()
    endforeach()
endforeach()

if(EXISTS "${_AROS_NATIVE_KOBJ_OUTPUT}")
    _aros_native_kobj_check_regular("${_AROS_NATIVE_KOBJ_OUTPUT}" "existing output")
endif()
if(EXISTS "${_AROS_NATIVE_KOBJ_STAGE}" AND IS_DIRECTORY "${_AROS_NATIVE_KOBJ_STAGE}")
    _aros_native_kobj_fail("staging path is a directory")
endif()
if(EXISTS "${_AROS_NATIVE_KOBJ_REPORT}")
    if(IS_DIRECTORY "${_AROS_NATIVE_KOBJ_REPORT}")
        _aros_native_kobj_fail("set report path is a directory")
    endif()
    file(SIZE "${_AROS_NATIVE_KOBJ_REPORT}" _report_size)
    if(_report_size GREATER 0)
        _aros_native_kobj_fail(
            "nonempty skipped-entry report requires review: ${_AROS_NATIVE_KOBJ_REPORT}")
    endif()
endif()
if(AROS_NATIVE_KOBJ_VALIDATE_ONLY)
    return()
endif()

set(_AROS_NATIVE_KOBJ_ACTION_STARTED TRUE)
get_filename_component(_output_dir "${_AROS_NATIVE_KOBJ_OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_output_dir}")
_aros_native_kobj_check_path("${_AROS_NATIVE_KOBJ_OUTPUT}"
    "${_AROS_NATIVE_KOBJ_BUILD_ROOT}" OUTPUT TRUE)
_aros_native_kobj_check_path("${_AROS_NATIVE_KOBJ_STAGE}"
    "${_AROS_NATIVE_KOBJ_BUILD_ROOT}" STAGE TRUE)
if(EXISTS "${_AROS_NATIVE_KOBJ_STAGE}")
    if(IS_DIRECTORY "${_AROS_NATIVE_KOBJ_STAGE}")
        _aros_native_kobj_fail("staging path is a directory")
    endif()
    file(REMOVE "${_AROS_NATIVE_KOBJ_STAGE}")
endif()
if(EXISTS "${_AROS_NATIVE_KOBJ_REPORT}")
    file(REMOVE "${_AROS_NATIVE_KOBJ_REPORT}")
endif()

execute_process(
    COMMAND "${_AROS_NATIVE_KOBJ_COLLECTOR}" --ld "${_AROS_NATIVE_KOBJ_LINKER}"
        --report "${_AROS_NATIVE_KOBJ_REPORT}"
        -- ${_AROS_NATIVE_KOBJ_LINK_PREFIX} -o "${_AROS_NATIVE_KOBJ_STAGE}"
        ${_objects} ${_AROS_NATIVE_KOBJ_LINK_SUFFIX}
    RESULT_VARIABLE _link_result
    TIMEOUT 600
    OUTPUT_VARIABLE _link_stdout
    ERROR_VARIABLE _link_stderr)
if(NOT "${_link_result}" STREQUAL "0")
    _aros_native_kobj_fail("direct relocatable link failed (${_link_result}): ${_link_stdout}${_link_stderr}")
endif()
_aros_native_kobj_check_path("${_AROS_NATIVE_KOBJ_STAGE}"
    "${_AROS_NATIVE_KOBJ_BUILD_ROOT}" "staged output" TRUE)
_aros_native_kobj_check_regular("${_AROS_NATIVE_KOBJ_STAGE}" "direct link output")
_aros_native_kobj_check_path("${_AROS_NATIVE_KOBJ_REPORT}"
    "${_AROS_NATIVE_KOBJ_BUILD_ROOT}" "set report" TRUE)
if(EXISTS "${_AROS_NATIVE_KOBJ_REPORT}")
    if(IS_DIRECTORY "${_AROS_NATIVE_KOBJ_REPORT}")
        _aros_native_kobj_fail("set report path is a directory")
    endif()
    file(SIZE "${_AROS_NATIVE_KOBJ_REPORT}" _report_size)
    if(_report_size GREATER 0)
        _aros_native_kobj_fail(
            "collector reported skipped sets or library requirements; see ${_AROS_NATIVE_KOBJ_REPORT}")
    endif()
    file(REMOVE "${_AROS_NATIVE_KOBJ_REPORT}")
endif()

execute_process(
    COMMAND "${_AROS_NATIVE_KOBJ_COLLECTOR}" --localize-kobj
        "${_AROS_NATIVE_KOBJ_STAGE}" --nm "${_AROS_NATIVE_KOBJ_NM}"
        --objcopy "${_AROS_NATIVE_KOBJ_OBJCOPY}"
    RESULT_VARIABLE _localize_result
    TIMEOUT 600
    OUTPUT_VARIABLE _localize_stdout
    ERROR_VARIABLE _localize_stderr)
if(NOT "${_localize_result}" STREQUAL "0")
    _aros_native_kobj_fail("localization failed (${_localize_result}): ${_localize_stdout}${_localize_stderr}")
endif()
_aros_native_kobj_check_path("${_AROS_NATIVE_KOBJ_STAGE}"
    "${_AROS_NATIVE_KOBJ_BUILD_ROOT}" "localized stage" TRUE)
_aros_native_kobj_check_regular("${_AROS_NATIVE_KOBJ_STAGE}" "localized KOBJ")
_aros_native_kobj_check_path("${_AROS_NATIVE_KOBJ_OUTPUT}"
    "${_AROS_NATIVE_KOBJ_BUILD_ROOT}" OUTPUT TRUE)
file(RENAME "${_AROS_NATIVE_KOBJ_STAGE}" "${_AROS_NATIVE_KOBJ_OUTPUT}"
    RESULT _publish_result)
if(NOT _publish_result STREQUAL "0")
    _aros_native_kobj_fail("atomic publication failed: ${_publish_result}")
endif()
set(_AROS_NATIVE_KOBJ_ACTION_STARTED FALSE)
_aros_native_kobj_check_path("${_AROS_NATIVE_KOBJ_OUTPUT}"
    "${_AROS_NATIVE_KOBJ_BUILD_ROOT}" "published output" TRUE)
_aros_native_kobj_check_regular("${_AROS_NATIVE_KOBJ_OUTPUT}" "published KOBJ")
