cmake_minimum_required(VERSION 3.22)

foreach(_required IN ITEMS SOURCE_ROOT SOURCE_BOUNDARY SOURCE_KIND DESTINATION DESTINATION_KIND
        FD_ROOT BINARY_ROOT RECIPE RECIPE_SHA256 DEPFILE)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "RunSdkFileCopies requires ${_required}")
    endif()
endforeach()
if(NOT DESTINATION_KIND MATCHES "^(fd|lib|bin|man1)$")
    message(FATAL_ERROR "SDK file-copy destination kind must be fd, lib, bin or man1")
endif()
if(DESTINATION_KIND STREQUAL "lib" AND NOT SOURCE_KIND STREQUAL "local")
    message(FATAL_ERROR "Developer library copies require local source inputs")
endif()
if(NOT SOURCE_KIND STREQUAL "local" AND NOT SOURCE_KIND STREQUAL "fetched")
    message(FATAL_ERROR "SDK file-copy source kind must be local or fetched")
endif()
if(SOURCE_KIND STREQUAL "fetched" AND
   (NOT DEFINED FETCH_DESTINATION OR "${FETCH_DESTINATION}" STREQUAL ""))
    message(FATAL_ERROR "fetched SDK file-copy requires FETCH_DESTINATION")
endif()

unset(_sdk_copy_test)
find_program(_sdk_copy_test NAMES test PATHS /usr/bin /bin
    NO_DEFAULT_PATH NO_CACHE REQUIRED)

function(_sdk_file_copy_run)
    foreach(_name IN ITEMS SOURCE_ROOT SOURCE_BOUNDARY DESTINATION FD_ROOT
            BINARY_ROOT RECIPE DEPFILE)
        _sdk_file_copy_normalize_path("${_name}" "${${_name}}" "_${_name}")
    endforeach()
    set(_source_root "${_SOURCE_ROOT}")
    set(_source_boundary "${_SOURCE_BOUNDARY}")
    set(_destination "${_DESTINATION}")
    set(_fd_root "${_FD_ROOT}")
    set(_binary_root "${_BINARY_ROOT}")
    set(_recipe "${_RECIPE}")
    set(_depfile "${_DEPFILE}")
    set(_fetch_destination "")
    if(SOURCE_KIND STREQUAL "fetched")
        _sdk_file_copy_normalize_path(
            "FETCH_DESTINATION" "${FETCH_DESTINATION}" _FETCH_DESTINATION)
        set(_fetch_destination "${_FETCH_DESTINATION}")
        if(NOT _fetch_destination STREQUAL _source_boundary)
            message(FATAL_ERROR "fetched SDK file-copy boundary does not match FETCH_DESTINATION")
        endif()
    endif()
    string(LENGTH "${RECIPE_SHA256}" _recipe_digest_length)
    if(NOT _recipe_digest_length EQUAL 64 OR
       NOT RECIPE_SHA256 MATCHES "^[0-9a-fA-F]+$")
        message(FATAL_ERROR "SDK file-copy recipe digest is malformed")
    endif()

    if(NOT IS_DIRECTORY "${_binary_root}")
        message(FATAL_ERROR "SDK file-copy binary root is missing")
    endif()
    _sdk_file_copy_require_descendant("fd root" "${_fd_root}" "${_binary_root}" FALSE)
    _sdk_file_copy_require_descendant("destination" "${_destination}" "${_fd_root}" TRUE)
    if(NOT DESTINATION_KIND STREQUAL "fd" AND NOT _destination STREQUAL _fd_root)
        message(FATAL_ERROR "Developer file destination must equal its configured root")
    endif()
    if(SOURCE_KIND STREQUAL "fetched")
        _sdk_file_copy_require_descendant(
            "fetch destination" "${_fetch_destination}" "${_binary_root}" FALSE)
        _sdk_file_copy_require_descendant(
            "fetched source" "${_source_root}" "${_fetch_destination}" TRUE)
    else()
        _sdk_file_copy_require_descendant(
            "local source" "${_source_root}" "${_source_boundary}" TRUE)
    endif()
    cmake_path(IS_PREFIX _source_root "${_destination}" NORMALIZE _destination_below_source)
    cmake_path(IS_PREFIX _destination "${_source_root}" NORMALIZE _source_below_destination)
    if(_destination_below_source OR _source_below_destination)
        message(FATAL_ERROR "SDK file-copy source and destination roots overlap")
    endif()

    set(_recipe_root "${_binary_root}/.aros-sdk-file-copies")
    _sdk_file_copy_require_descendant("recipe" "${_recipe}" "${_recipe_root}" FALSE)
    _sdk_file_copy_require_descendant("depfile" "${_depfile}" "${_recipe_root}" FALSE)
    if(_recipe STREQUAL _depfile)
        message(FATAL_ERROR "SDK file-copy recipe and depfile must be distinct")
    endif()

    foreach(_root IN ITEMS _fd_root _destination _recipe_root)
        _sdk_file_copy_check_components("root" "${${_root}}" "${_binary_root}")
    endforeach()
    if(SOURCE_KIND STREQUAL "fetched")
        _sdk_file_copy_check_components(
            "fetch destination" "${_fetch_destination}" "${_binary_root}")
    endif()
    _sdk_file_copy_check_components("source root" "${_source_root}" "${_source_boundary}")
    _sdk_file_copy_check_components("recipe" "${_recipe}" "${_recipe_root}")
    _sdk_file_copy_check_components("depfile" "${_depfile}" "${_recipe_root}")

    if(SOURCE_KIND STREQUAL "fetched")
        if(NOT IS_DIRECTORY "${_fetch_destination}" OR NOT IS_DIRECTORY "${_source_root}")
            message(FATAL_ERROR "fetched SDK file-copy source is missing")
        endif()
        _sdk_file_copy_check_physical_inside(
            "fetch destination" "${_fetch_destination}" "${_binary_root}")
        _sdk_file_copy_check_physical_inside(
            "source root" "${_source_root}" "${_fetch_destination}")
    else()
        if(NOT IS_DIRECTORY "${_source_boundary}" OR NOT IS_DIRECTORY "${_source_root}")
            message(FATAL_ERROR "local SDK file-copy source is missing")
        endif()
        _sdk_file_copy_check_physical_inside(
            "source root" "${_source_root}" "${_source_boundary}")
    endif()
    _sdk_file_copy_check_physical_inside("fd root" "${_fd_root}" "${_binary_root}")
    _sdk_file_copy_check_physical_inside("destination" "${_destination}" "${_binary_root}")

    _sdk_file_copy_require_regular("recipe" "${_recipe}")
    file(SIZE "${_recipe}" _recipe_size)
    if(_recipe_size GREATER 32768)
        message(FATAL_ERROR "SDK file-copy recipe exceeds 32 KiB")
    endif()
    file(SHA256 "${_recipe}" _actual_recipe_sha256)
    if(NOT "${_actual_recipe_sha256}" STREQUAL "${RECIPE_SHA256}")
        message(FATAL_ERROR "SDK file-copy recipe differs from its configure-time contract")
    endif()
    file(READ "${_recipe}" _files_json)
    set(_source_hashes "")
    if(DESTINATION_KIND STREQUAL "lib")
        string(JSON _type ERROR_VARIABLE _json_error TYPE "${_files_json}")
        if(NOT _json_error STREQUAL "NOTFOUND" OR NOT _type STREQUAL "OBJECT")
            message(FATAL_ERROR "Developer library recipe must be a closed JSON object")
        endif()
        string(JSON _field_count LENGTH "${_files_json}")
        if(NOT _field_count EQUAL 2)
            message(FATAL_ERROR "Developer library recipe requires only files and sha256")
        endif()
        string(JSON _hashes_json ERROR_VARIABLE _json_error GET "${_files_json}" sha256)
        if(NOT _json_error STREQUAL "NOTFOUND")
            message(FATAL_ERROR "Developer library recipe lacks source hashes")
        endif()
        string(JSON _names_json ERROR_VARIABLE _json_error GET "${_files_json}" files)
        if(NOT _json_error STREQUAL "NOTFOUND")
            message(FATAL_ERROR "Developer library recipe lacks file names")
        endif()
        string(JSON _hashes_type ERROR_VARIABLE _json_error TYPE "${_hashes_json}")
        if(NOT _json_error STREQUAL "NOTFOUND" OR NOT _hashes_type STREQUAL "ARRAY")
            message(FATAL_ERROR "Developer library hashes must be an array")
        endif()
        string(JSON _hash_count LENGTH "${_hashes_json}")
        string(JSON _name_count ERROR_VARIABLE _json_error LENGTH "${_names_json}")
        if(NOT _json_error STREQUAL "NOTFOUND" OR _hash_count LESS 1 OR
           _hash_count GREATER 128 OR NOT _hash_count EQUAL _name_count)
            message(FATAL_ERROR "Developer library hash/name counts differ")
        endif()
        math(EXPR _last_hash "${_hash_count} - 1")
        foreach(_index RANGE 0 ${_last_hash})
            string(JSON _hash_type TYPE "${_hashes_json}" ${_index})
            string(JSON _hash GET "${_hashes_json}" ${_index})
            string(LENGTH "${_hash}" _hash_length)
            if(NOT _hash_type STREQUAL "STRING" OR NOT _hash_length EQUAL 64 OR
               NOT _hash MATCHES "^[0-9a-f]+$")
                message(FATAL_ERROR "Developer library source hash is malformed")
            endif()
            list(APPEND _source_hashes "${_hash}")
        endforeach()
        set(_files_json "${_names_json}")
    endif()
    _sdk_file_copy_parse_names("${_files_json}" _names)
    _sdk_file_copy_path_exists("${_depfile}" _depfile_exists)
    if(_depfile_exists)
        _sdk_file_copy_require_regular("existing depfile" "${_depfile}")
    endif()

    set(_source_paths "")
    set(_output_paths "")
    set(_source_sizes "")
    set(_total_source_size 0)
    set(_source_index 0)
    foreach(_name IN LISTS _names)
        set(_source "${_source_root}/${_name}")
        set(_output "${_destination}/${_name}")
        _sdk_file_copy_check_components("source file" "${_source}" "${_source_boundary}")
        _sdk_file_copy_require_regular("source file" "${_source}")
        file(SIZE "${_source}" _source_size)
        if(DESTINATION_KIND STREQUAL "lib")
            list(GET _source_hashes ${_source_index} _expected_hash)
            file(SHA256 "${_source}" _actual_hash)
            if(NOT _actual_hash STREQUAL _expected_hash)
                message(FATAL_ERROR "Developer library source differs from its configured hash: ${_name}")
            endif()
        endif()
        if(_source_size GREATER 16777216)
            message(FATAL_ERROR "SDK source file exceeds 16 MiB: ${_source}")
        endif()
        math(EXPR _total_source_size "${_total_source_size} + ${_source_size}")
        if(_total_source_size GREATER 67108864)
            message(FATAL_ERROR "SDK file-copy batch exceeds 64 MiB")
        endif()
        _sdk_file_copy_require_descendant("source file" "${_source}" "${_source_root}" FALSE)
        _sdk_file_copy_require_descendant("output file" "${_output}" "${_destination}" FALSE)
        if(_source STREQUAL _output)
            message(FATAL_ERROR "SDK source and output are identical: ${_name}")
        endif()
        _sdk_file_copy_check_components("output file" "${_output}" "${_binary_root}")
        _sdk_file_copy_path_exists("${_output}" _output_exists)
        if(_output_exists)
            _sdk_file_copy_require_regular("existing output" "${_output}")
            file(SIZE "${_output}" _output_size)
            if(_output_size GREATER 16777216)
                message(FATAL_ERROR "existing SDK output exceeds 16 MiB: ${_output}")
            endif()
        endif()
        list(APPEND _source_paths "${_source}")
        list(APPEND _output_paths "${_output}")
        list(APPEND _source_sizes "${_source_size}")
        math(EXPR _source_index "${_source_index} + 1")
    endforeach()

    # The entire batch is validated before any output or temporary is changed.
    file(MAKE_DIRECTORY "${_destination}")
    _sdk_file_copy_check_components("destination" "${_destination}" "${_binary_root}")
    _sdk_file_copy_check_physical_inside("destination" "${_destination}" "${_binary_root}")
    set(_temporary_paths "")
    string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef _nonce)
    foreach(_name IN LISTS _names)
        set(_temporary "${_destination}/.${_name}.copy-${_nonce}")
        _sdk_file_copy_check_components("temporary output" "${_temporary}" "${_destination}")
        _sdk_file_copy_path_exists("${_temporary}" _temporary_exists)
        if(_temporary_exists)
            message(FATAL_ERROR "SDK temporary output already exists: ${_temporary}")
        endif()
        list(APPEND _temporary_paths "${_temporary}")
    endforeach()

    set(_index 0)
    foreach(_name IN LISTS _names)
        list(GET _source_paths ${_index} _source)
        list(GET _temporary_paths ${_index} _temporary)
        list(GET _source_sizes ${_index} _source_size)
        _sdk_file_copy_check_components("source file" "${_source}" "${_source_boundary}")
        _sdk_file_copy_require_regular("source file" "${_source}")
        file(COPY_FILE "${_source}" "${_temporary}" RESULT _copy_result)
        if(NOT _copy_result STREQUAL "0")
            file(REMOVE ${_temporary_paths})
            message(FATAL_ERROR "cannot stage SDK file ${_name}: ${_copy_result}")
        endif()
        _sdk_file_copy_require_regular("temporary output" "${_temporary}")
        file(SIZE "${_temporary}" _temporary_size)
        if(NOT _temporary_size EQUAL _source_size)
            file(REMOVE ${_temporary_paths})
            message(FATAL_ERROR "staged SDK file size changed: ${_name}")
        endif()
        if(DESTINATION_KIND STREQUAL "lib")
            list(GET _source_hashes ${_index} _expected_hash)
            file(SHA256 "${_temporary}" _temporary_hash)
            if(NOT _temporary_hash STREQUAL _expected_hash)
                file(REMOVE ${_temporary_paths})
                message(FATAL_ERROR "staged Developer library source hash changed: ${_name}")
            endif()
        endif()
        math(EXPR _index "${_index} + 1")
    endforeach()

    # Revalidate all sources and destinations after staging, before publishing
    # any member. This keeps validation failures batch-atomic.
    set(_source_index 0)
    foreach(_source IN LISTS _source_paths)
        _sdk_file_copy_check_components("source file" "${_source}" "${_source_boundary}")
        _sdk_file_copy_require_regular("source file" "${_source}")
        if(DESTINATION_KIND STREQUAL "lib")
            list(GET _source_hashes ${_source_index} _expected_hash)
            file(SHA256 "${_source}" _actual_hash)
            if(NOT _actual_hash STREQUAL _expected_hash)
                file(REMOVE ${_temporary_paths})
                message(FATAL_ERROR "Developer library source hash changed before publication")
            endif()
        endif()
        math(EXPR _source_index "${_source_index} + 1")
    endforeach()
    foreach(_output IN LISTS _output_paths)
        _sdk_file_copy_check_components("output file" "${_output}" "${_binary_root}")
        _sdk_file_copy_path_exists("${_output}" _output_exists)
        if(_output_exists)
            _sdk_file_copy_require_regular("existing output" "${_output}")
        endif()
    endforeach()

    list(GET _output_paths 0 _depfile_target)
    _sdk_file_copy_escape_dep_path("output" "${_depfile_target}" _depfile_target)
    set(_depfile_content "${_depfile_target}:")
    foreach(_source IN LISTS _source_paths)
        _sdk_file_copy_escape_dep_path("input" "${_source}" _depfile_source)
        string(APPEND _depfile_content " ${_depfile_source}")
    endforeach()
    string(APPEND _depfile_content "\n")
    set(_depfile_temporary "${_depfile}.tmp-${_nonce}")
    _sdk_file_copy_check_components("temporary depfile" "${_depfile_temporary}" "${_recipe_root}")
    file(WRITE "${_depfile_temporary}" "${_depfile_content}")
    _sdk_file_copy_require_regular("temporary depfile" "${_depfile_temporary}")
    file(RENAME "${_depfile_temporary}" "${_depfile}" RESULT _depfile_rename_result)
    if(NOT _depfile_rename_result STREQUAL "0")
        file(REMOVE ${_temporary_paths} "${_depfile_temporary}")
        message(FATAL_ERROR "cannot publish SDK file-copy depfile: ${_depfile_rename_result}")
    endif()

    list(LENGTH _output_paths _output_count)
    math(EXPR _last_output "${_output_count} - 1")
    foreach(_index RANGE 0 ${_last_output})
        list(GET _temporary_paths ${_index} _temporary)
        list(GET _output_paths ${_index} _output)
        file(RENAME "${_temporary}" "${_output}" RESULT _rename_result)
        if(NOT _rename_result STREQUAL "0")
            file(REMOVE ${_temporary_paths})
            message(FATAL_ERROR "cannot publish SDK file ${_output}: ${_rename_result}")
        endif()
    endforeach()
endfunction()

function(_sdk_file_copy_normalize_path label raw out)
    if(NOT IS_ABSOLUTE "${raw}" OR "${raw}" MATCHES "[;\"\r\n$`|&*?\[\]]")
        message(FATAL_ERROR "SDK file-copy ${label} is not a safe absolute path")
    endif()
    string(LENGTH "${raw}" _length)
    if(_length GREATER 4096)
        message(FATAL_ERROR "SDK file-copy ${label} exceeds the path length limit")
    endif()
    string(REPLACE "/" ";" _components "${raw}")
    foreach(_component IN LISTS _components)
        if(_component STREQUAL "." OR _component STREQUAL "..")
            message(FATAL_ERROR "SDK file-copy ${label} contains a dot path component")
        endif()
    endforeach()
    set(_normalized "${raw}")
    cmake_path(NORMAL_PATH _normalized OUTPUT_VARIABLE _normalized)
    if(_normalized STREQUAL "/")
        message(FATAL_ERROR "SDK file-copy ${label} cannot be the filesystem root")
    endif()
    set(${out} "${_normalized}" PARENT_SCOPE)
endfunction()

function(_sdk_file_copy_require_descendant label path root allow_equal)
    cmake_path(IS_PREFIX root "${path}" NORMALIZE _inside)
    if(NOT _inside OR (NOT allow_equal AND "${path}" STREQUAL "${root}"))
        message(FATAL_ERROR "SDK file-copy ${label} escapes its declared root")
    endif()
endfunction()

function(_sdk_file_copy_check_components label path root)
    file(RELATIVE_PATH _relative "${root}" "${path}")
    if(_relative MATCHES "(^|/)\\.\\.(/|$)" OR _relative MATCHES "^\\.\\.")
        message(FATAL_ERROR "SDK file-copy ${label} escapes its checked root")
    endif()
    if(_relative STREQUAL "." OR _relative STREQUAL "")
        return()
    endif()
    string(REPLACE "/" ";" _components "${_relative}")
    set(_probe "${root}")
    list(LENGTH _components _count)
    set(_index 0)
    foreach(_component IN LISTS _components)
        if(_component STREQUAL "")
            continue()
        endif()
        math(EXPR _index "${_index} + 1")
        set(_probe "${_probe}/${_component}")
        if(IS_SYMLINK "${_probe}")
            message(FATAL_ERROR "SDK file-copy ${label} crosses a symlink: ${_probe}")
        endif()
        if(EXISTS "${_probe}" AND _index LESS _count AND NOT IS_DIRECTORY "${_probe}")
            message(FATAL_ERROR "SDK file-copy ${label} parent is not a directory: ${_probe}")
        endif()
    endforeach()
endfunction()

function(_sdk_file_copy_check_physical_inside label path root)
    if(NOT IS_DIRECTORY "${root}")
        message(FATAL_ERROR "SDK file-copy ${label} boundary is missing: ${root}")
    endif()
    file(REAL_PATH "${root}" _root_real)
    set(_existing "${path}")
    while(NOT EXISTS "${_existing}")
        if(IS_SYMLINK "${_existing}")
            message(FATAL_ERROR "SDK file-copy ${label} crosses a dangling symlink")
        endif()
        cmake_path(GET _existing PARENT_PATH _parent)
        if(_parent STREQUAL _existing)
            message(FATAL_ERROR "SDK file-copy ${label} has no safe existing ancestor")
        endif()
        set(_existing "${_parent}")
    endwhile()
    file(REAL_PATH "${_existing}" _existing_real)
    cmake_path(IS_PREFIX _root_real "${_existing_real}" NORMALIZE _inside)
    if(NOT _inside)
        message(FATAL_ERROR "SDK file-copy ${label} physically escapes its declared root")
    endif()
endfunction()

function(_sdk_file_copy_path_exists path out)
    execute_process(
        COMMAND "${_sdk_copy_test}" -e "${path}"
        RESULT_VARIABLE _result OUTPUT_QUIET ERROR_QUIET TIMEOUT 10)
    if(_result STREQUAL "0")
        set(${out} TRUE PARENT_SCOPE)
    else()
        set(${out} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(_sdk_file_copy_require_regular label path)
    execute_process(
        COMMAND "${_sdk_copy_test}" -f "${path}"
        RESULT_VARIABLE _result OUTPUT_QUIET ERROR_QUIET TIMEOUT 10)
    if(NOT _result STREQUAL "0")
        message(FATAL_ERROR "SDK file-copy ${label} is not a regular file: ${path}")
    endif()
endfunction()

function(_sdk_file_copy_parse_names json out)
    string(JSON _type ERROR_VARIABLE _json_error TYPE "${json}")
    if(NOT _json_error STREQUAL "NOTFOUND" OR NOT _type STREQUAL "ARRAY")
        message(FATAL_ERROR "SDK file-copy recipe must be a JSON array")
    endif()
    string(JSON _count ERROR_VARIABLE _json_error LENGTH "${json}")
    if(NOT _json_error STREQUAL "NOTFOUND" OR _count LESS 1 OR _count GREATER 128)
        message(FATAL_ERROR "SDK file-copy recipe must contain 1 to 128 names")
    endif()
    set(_names "")
    set(_seen "")
    math(EXPR _last_index "${_count} - 1")
    foreach(_index RANGE 0 ${_last_index})
        string(JSON _item_type ERROR_VARIABLE _json_error TYPE "${json}" ${_index})
        if(NOT _json_error STREQUAL "NOTFOUND" OR NOT _item_type STREQUAL "STRING")
            message(FATAL_ERROR "SDK file-copy recipe item ${_index} must be a string")
        endif()
        string(JSON _name GET "${json}" ${_index})
        string(LENGTH "${_name}" _name_length)
        if(_name_length GREATER 255 OR
           NOT _name MATCHES "^[A-Za-z0-9][A-Za-z0-9_.+-]*$")
            message(FATAL_ERROR "SDK file-copy recipe contains an unsafe basename")
        endif()
        string(TOLOWER "${_name}" _identity)
        if(_identity IN_LIST _seen)
            message(FATAL_ERROR "SDK file-copy recipe contains duplicate basenames")
        endif()
        list(APPEND _seen "${_identity}")
        list(APPEND _names "${_name}")
    endforeach()
    set(${out} "${_names}" PARENT_SCOPE)
endfunction()

function(_sdk_file_copy_escape_dep_path label path out)
    set(_escaped "${path}")
    string(REPLACE "\\" "\\\\" _escaped "${_escaped}")
    string(REPLACE " " "\\ " _escaped "${_escaped}")
    string(REPLACE "#" "\\#" _escaped "${_escaped}")
    string(REPLACE ":" "\\:" _escaped "${_escaped}")
    set(${out} "${_escaped}" PARENT_SCOPE)
endfunction()

_sdk_file_copy_run()
