cmake_minimum_required(VERSION 3.22)

function(_aros_sdk_text_check_components root path label)
    file(RELATIVE_PATH _relative "${root}" "${path}")
    if(_relative MATCHES "(^|/)[.][.]?(/|$)" OR _relative MATCHES "^[.][.]")
        message(FATAL_ERROR "SDK text ${label} escapes its declared root")
    endif()
    string(REPLACE "/" ";" _components "${_relative}")
    set(_probe "${root}")
    list(LENGTH _components _count)
    set(_index 0)
    foreach(_component IN LISTS _components)
        math(EXPR _index "${_index} + 1")
        set(_probe "${_probe}/${_component}")
        if(IS_SYMLINK "${_probe}")
            message(FATAL_ERROR "SDK text ${label} path crosses a symlink: ${_probe}")
        endif()
        if(EXISTS "${_probe}" AND _index LESS _count AND NOT IS_DIRECTORY "${_probe}")
            message(FATAL_ERROR "SDK text ${label} parent is not a directory: ${_probe}")
        endif()
    endforeach()
endfunction()

function(_aros_sdk_text_check_physical_output binary_root output)
    file(REAL_PATH "${binary_root}" _binary_real)
    set(_existing "${output}")
    while(NOT EXISTS "${_existing}")
        cmake_path(GET _existing PARENT_PATH _parent)
        if(_parent STREQUAL _existing)
            message(FATAL_ERROR "SDK text output has no existing binary ancestor")
        endif()
        set(_existing "${_parent}")
    endwhile()
    file(REAL_PATH "${_existing}" _existing_real)
    cmake_path(IS_PREFIX _binary_real "${_existing_real}" NORMALIZE _inside)
    if(NOT _inside)
        message(FATAL_ERROR "SDK text output escapes the physical build directory")
    endif()
endfunction()

function(_aros_sdk_text_validate_operation operation type_out first_out second_out)
    if(operation MATCHES "^REPLACE_FIRST_PER_LINE[|]([^|]+)[|](.*)$")
        set(_type "REPLACE_FIRST_PER_LINE")
        set(_first "${CMAKE_MATCH_1}")
        set(_second "${CMAKE_MATCH_2}")
        if(NOT _first MATCHES "^[A-Za-z0-9_@:/{}$ -]+$")
            message(FATAL_ERROR "Unsafe SDK text literal token")
        endif()
        _aros_sdk_text_validate_replacement("${_second}")
    elseif(operation MATCHES "^REPLACE_ALL[|]([^|]+)[|](.*)$")
        set(_type "REPLACE_ALL")
        set(_first "${CMAKE_MATCH_1}")
        set(_second "${CMAKE_MATCH_2}")
        if(NOT _first MATCHES "^[A-Za-z0-9_@:/{}$ -]+$")
            message(FATAL_ERROR "Unsafe SDK text literal token")
        endif()
        _aros_sdk_text_validate_replacement("${_second}")
    elseif(operation MATCHES "^DELETE_LINE_PREFIX[|]([A-Za-z0-9_.+-]+)$")
        set(_type "DELETE_LINE_PREFIX")
        set(_first "${CMAKE_MATCH_1}")
        set(_second "")
    elseif(operation MATCHES "^REPLACE_LINE[|]([A-Za-z0-9_+-]+=)[|](.*)$")
        set(_type "REPLACE_LINE")
        set(_first "${CMAKE_MATCH_1}")
        set(_second "${CMAKE_MATCH_2}")
        _aros_sdk_text_validate_replacement("${_second}")
    else()
        message(FATAL_ERROR "Unsafe SDK text operation: ${operation}")
    endif()
    set(${type_out} "${_type}" PARENT_SCOPE)
    set(${first_out} "${_first}" PARENT_SCOPE)
    set(${second_out} "${_second}" PARENT_SCOPE)
endfunction()

function(_aros_sdk_text_validate_replacement replacement)
    if("${replacement}" MATCHES "[;|&\\\\\r\n]")
        message(FATAL_ERROR "Unsafe SDK text replacement")
    endif()
    string(REPLACE "\${prefix}" "" _without_prefix "${replacement}")
    string(FIND "${_without_prefix}" "$" _dollar)
    if(NOT _dollar EQUAL -1)
        message(FATAL_ERROR "Unsupported variable in SDK text replacement")
    endif()
endfunction()

function(_aros_sdk_text_transform_lines input mode prefix replacement output_var)
    set(_remaining "${input}")
    set(_output "")
    while(TRUE)
        string(FIND "${_remaining}" "\n" _newline_at)
        if(_newline_at EQUAL -1)
            set(_line "${_remaining}")
            set(_has_newline FALSE)
            set(_remaining "")
        else()
            string(SUBSTRING "${_remaining}" 0 "${_newline_at}" _line)
            math(EXPR _rest_start "${_newline_at} + 1")
            string(SUBSTRING "${_remaining}" "${_rest_start}" -1 _remaining)
            set(_has_newline TRUE)
        endif()

        string(LENGTH "${prefix}" _prefix_length)
        string(LENGTH "${_line}" _line_length)
        set(_matches FALSE)
        if(_line_length GREATER_EQUAL _prefix_length)
            string(SUBSTRING "${_line}" 0 "${_prefix_length}" _line_prefix)
            if(_line_prefix STREQUAL prefix)
                set(_matches TRUE)
            endif()
        endif()

        if(NOT (mode STREQUAL "DELETE" AND _matches))
            if(mode STREQUAL "FIRST")
                string(FIND "${_line}" "${prefix}" _match_at)
                if(NOT _match_at EQUAL -1)
                    string(SUBSTRING "${_line}" 0 ${_match_at} _head)
                    math(EXPR _tail_at "${_match_at} + ${_prefix_length}")
                    string(SUBSTRING "${_line}" ${_tail_at} -1 _tail)
                    string(APPEND _output "${_head}${replacement}${_tail}")
                else()
                    string(APPEND _output "${_line}")
                endif()
            elseif(mode STREQUAL "REPLACE" AND _matches)
                string(APPEND _output "${replacement}")
            else()
                string(APPEND _output "${_line}")
            endif()
            if(_has_newline)
                string(APPEND _output "\n")
            endif()
        endif()
        if(NOT _has_newline OR _remaining STREQUAL "")
            break()
        endif()
    endwhile()
    set(${output_var} "${_output}" PARENT_SCOPE)
endfunction()

function(_aros_sdk_text_verify_declaration)
    if(NOT DEFINED DECLARATION_SOURCE AND NOT DEFINED DECLARATION_SHA256 AND
       NOT DEFINED DECLARATION_SOURCE_ROOT)
        return()
    endif()
    foreach(_required IN ITEMS DECLARATION_SOURCE DECLARATION_SOURCE_ROOT DECLARATION_SHA256)
        if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
            message(FATAL_ERROR "SDK text source binding is incomplete")
        endif()
    endforeach()
    string(LENGTH "${DECLARATION_SHA256}" _digest_length)
    if(NOT _digest_length EQUAL 64 OR NOT DECLARATION_SHA256 MATCHES "^[0-9a-f]+$")
        message(FATAL_ERROR "SDK text declaration digest is invalid")
    endif()
    foreach(_path IN ITEMS DECLARATION_SOURCE DECLARATION_SOURCE_ROOT)
        if(NOT IS_ABSOLUTE "${${_path}}" OR "${${_path}}" MATCHES "[;\"\r\n|&]" OR
           "${${_path}}" MATCHES "(^|/)[.][.]?(/|$)")
            message(FATAL_ERROR "SDK text declaration path is unsafe")
        endif()
    endforeach()
    _aros_sdk_text_check_components("${DECLARATION_SOURCE_ROOT}" "${DECLARATION_SOURCE}" "declaration")
    execute_process(COMMAND "${_regular_file_test}" -f "${DECLARATION_SOURCE}"
        RESULT_VARIABLE _regular_declaration TIMEOUT 10)
    if(NOT "${_regular_declaration}" STREQUAL "0")
        message(FATAL_ERROR "SDK text declaration is not a regular file")
    endif()
    file(REAL_PATH "${DECLARATION_SOURCE_ROOT}" _source_root_real)
    file(REAL_PATH "${DECLARATION_SOURCE}" _source_real)
    cmake_path(IS_PREFIX _source_root_real "${_source_real}" NORMALIZE _inside)
    if(NOT _inside)
        message(FATAL_ERROR "SDK text declaration escapes its source root")
    endif()
    file(SHA256 "${DECLARATION_SOURCE}" _source_digest)
    if(NOT _source_digest STREQUAL DECLARATION_SHA256)
        message(FATAL_ERROR "SDK text source changed after translation")
    endif()
endfunction()

foreach(_required IN ITEMS INPUT OUTPUT INPUT_ROOT OUTPUT_ROOT BINARY_ROOT OPERATIONS)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "RunSdkTextRule requires ${_required}")
    endif()
endforeach()

foreach(_path IN ITEMS INPUT OUTPUT INPUT_ROOT OUTPUT_ROOT BINARY_ROOT)
    if("${${_path}}" MATCHES "[;\"\r\n|&]")
        message(FATAL_ERROR "SDK text ${_path} contains unsupported path characters")
    endif()
    if("${${_path}}" MATCHES "(^|/)[.][.]?(/|$)")
        message(FATAL_ERROR "SDK text ${_path} contains path traversal")
    endif()
endforeach()

cmake_path(ABSOLUTE_PATH INPUT NORMALIZE OUTPUT_VARIABLE _input)
cmake_path(ABSOLUTE_PATH OUTPUT NORMALIZE OUTPUT_VARIABLE _output)
cmake_path(ABSOLUTE_PATH INPUT_ROOT NORMALIZE OUTPUT_VARIABLE _input_root)
cmake_path(ABSOLUTE_PATH OUTPUT_ROOT NORMALIZE OUTPUT_VARIABLE _output_root)
cmake_path(ABSOLUTE_PATH BINARY_ROOT NORMALIZE OUTPUT_VARIABLE _binary_root)
set(_pkgconfig_root "${_output_root}/pkgconfig")

cmake_path(IS_PREFIX _input_root "${_input}" NORMALIZE _input_inside_root)
if(NOT _input_inside_root OR _input STREQUAL _input_root)
    message(FATAL_ERROR "SDK text input is outside its declared fetch root")
endif()
cmake_path(IS_PREFIX _binary_root "${_input_root}" NORMALIZE _input_root_inside_binary)
if(NOT _input_root_inside_binary OR _input_root STREQUAL _binary_root)
    message(FATAL_ERROR "SDK text fetch root escapes the build directory")
endif()
cmake_path(IS_PREFIX _binary_root "${_output_root}" NORMALIZE _output_root_inside_binary)
if(NOT _output_root_inside_binary)
    message(FATAL_ERROR "SDK text output root escapes the build directory")
endif()
cmake_path(IS_PREFIX _pkgconfig_root "${_output}" NORMALIZE _output_inside_pkgconfig)
if(NOT _output_inside_pkgconfig OR _output STREQUAL _pkgconfig_root)
    message(FATAL_ERROR "SDK text output is outside Developer/lib/pkgconfig")
endif()
cmake_path(GET _output FILENAME _output_name)
if(NOT _output_name MATCHES "^[A-Za-z0-9][A-Za-z0-9_.+-]*[.]pc$")
    message(FATAL_ERROR "SDK text output must be one safe `.pc` file")
endif()

if(NOT EXISTS "${_input}" OR IS_DIRECTORY "${_input}" OR IS_SYMLINK "${_input}")
    message(FATAL_ERROR "SDK text input is missing or is not a regular file: ${_input}")
endif()
# EXISTS and IS_DIRECTORY cannot distinguish a FIFO on supported CMake
# versions. Check its type without opening it; a changed fetch leaf must not
# block file(READ). Only the supported Unix system tool locations are allowed.
unset(_regular_file_test)
find_program(_regular_file_test NAMES test PATHS /usr/bin /bin
    NO_DEFAULT_PATH NO_CACHE REQUIRED)
execute_process(COMMAND "${_regular_file_test}" -f "${_input}"
    RESULT_VARIABLE _regular_input_result TIMEOUT 10)
if(NOT "${_regular_input_result}" STREQUAL "0")
    message(FATAL_ERROR "SDK text input is not a regular file: ${_input}")
endif()
_aros_sdk_text_verify_declaration()
if(NOT IS_DIRECTORY "${_input_root}")
    message(FATAL_ERROR "SDK text fetch root is not a directory: ${_input_root}")
endif()
file(REAL_PATH "${_input_root}" _input_root_real)
file(REAL_PATH "${_input}" _input_real)
file(REAL_PATH "${_binary_root}" _binary_root_real)
cmake_path(IS_PREFIX _binary_root_real "${_input_root_real}" NORMALIZE
    _input_root_physically_inside_binary)
if(NOT _input_root_physically_inside_binary)
    message(FATAL_ERROR "SDK text fetch root escapes the physical build directory")
endif()
cmake_path(IS_PREFIX _input_root_real "${_input_real}" NORMALIZE _input_physically_inside)
if(NOT _input_physically_inside)
    message(FATAL_ERROR "SDK text input escapes its fetch root through a symlink")
endif()
_aros_sdk_text_check_components("${_binary_root}" "${_input}" "input")

if(NOT IS_DIRECTORY "${_binary_root}" OR NOT IS_DIRECTORY "${_output_root}")
    message(FATAL_ERROR "SDK text output roots are missing or not directories")
endif()
file(REAL_PATH "${_binary_root}" _binary_root_real)
file(REAL_PATH "${_output_root}" _output_root_real)
cmake_path(IS_PREFIX _binary_root_real "${_output_root_real}" NORMALIZE
    _output_root_physically_inside)
if(NOT _output_root_physically_inside)
    message(FATAL_ERROR "SDK text output root escapes the physical build directory")
endif()
_aros_sdk_text_check_components("${_binary_root}" "${_output}" "output")
_aros_sdk_text_check_physical_output("${_binary_root}" "${_output}")

if(NOT OPERATIONS)
    message(FATAL_ERROR "SDK text rule has no operations")
endif()

# Ordinary file(READ) normalises CRLF to LF. Decode bounded text bytes instead:
# the source sed recipe preserves line endings, including mixed/unterminated
# lines. NUL is not representable by CMake strings and is not SDK text.
file(SIZE "${_input}" _input_size)
if(_input_size GREATER 1048576)
    message(FATAL_ERROR "SDK text input exceeds the 1 MiB text limit")
endif()
file(READ "${_input}" _input_hex HEX)
string(REGEX MATCHALL ".." _input_bytes "${_input_hex}")
set(_content "")
foreach(_byte IN LISTS _input_bytes)
    if(_byte STREQUAL "00")
        message(FATAL_ERROR "SDK text input contains a NUL byte")
    endif()
    math(EXPR _code "0x${_byte}")
    string(ASCII ${_code} _character)
    string(APPEND _content "${_character}")
endforeach()
foreach(_operation IN LISTS OPERATIONS)
    _aros_sdk_text_validate_operation("${_operation}" _type _first _second)
    if(_type STREQUAL "REPLACE_ALL")
        string(REPLACE "${_first}" "${_second}" _next "${_content}")
        set(_content "${_next}")
    elseif(_type STREQUAL "REPLACE_FIRST_PER_LINE")
        _aros_sdk_text_transform_lines("${_content}" "FIRST" "${_first}" "${_second}" _next)
        set(_content "${_next}")
    elseif(_type STREQUAL "DELETE_LINE_PREFIX")
        _aros_sdk_text_transform_lines(
            "${_content}" "DELETE" "${_first}" "" _next)
        set(_content "${_next}")
    elseif(_type STREQUAL "REPLACE_LINE")
        _aros_sdk_text_transform_lines(
            "${_content}" "REPLACE" "${_first}" "${_second}" _next)
        set(_content "${_next}")
    else()
        message(FATAL_ERROR "Unsupported SDK text operation type ${_type}")
    endif()
endforeach()

get_filename_component(_output_directory "${_output}" DIRECTORY)
_aros_sdk_text_verify_declaration()
file(MAKE_DIRECTORY "${_output_directory}")
# Recheck after directory creation to catch path replacement between configure
# and build. The temporary output stays beside the product for an atomic rename.
_aros_sdk_text_check_components("${_binary_root}" "${_output}" "output")
_aros_sdk_text_check_physical_output("${_binary_root}" "${_output}")
if(EXISTS "${_output}" AND (IS_DIRECTORY "${_output}" OR IS_SYMLINK "${_output}"))
    message(FATAL_ERROR "SDK text output is not a replaceable regular file")
endif()
if(EXISTS "${_output}")
    execute_process(COMMAND "${_regular_file_test}" -f "${_output}"
        RESULT_VARIABLE _regular_output_result TIMEOUT 10)
    if(NOT "${_regular_output_result}" STREQUAL "0")
        message(FATAL_ERROR "SDK text output is not a replaceable regular file")
    endif()
endif()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef _temporary_suffix)
set(_temporary "${_output}.tmp-${_temporary_suffix}")
if(EXISTS "${_temporary}" OR IS_SYMLINK "${_temporary}")
    message(FATAL_ERROR "SDK text temporary output already exists")
endif()
file(WRITE "${_temporary}" "${_content}")
file(RENAME "${_temporary}" "${_output}" RESULT _rename_result)
if(NOT _rename_result STREQUAL "0")
    file(REMOVE "${_temporary}")
    message(FATAL_ERROR "Cannot atomically publish SDK text output: ${_rename_result}")
endif()
