cmake_minimum_required(VERSION 3.22)

foreach(_required IN ITEMS INPUT OUTPUT INPUT_ROOT OUTPUT_ROOT
        DEVELOPER_INCLUDE_ROOT GEN_INCLUDE_ROOT SOURCE_GEN_INCLUDE_ROOT
        HOSTTOOLS_ROOT BINARY_ROOT RECIPE DEPFILE)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "RunSourceTextRule requires ${_required}")
    endif()
endforeach()
if(DEFINED MODE AND NOT "${MODE}" STREQUAL "" AND NOT MODE STREQUAL "744")
    message(FATAL_ERROR "source text MODE must be exactly 744 when specified")
endif()

unset(_source_text_test)
find_program(_source_text_test NAMES test PATHS /usr/bin /bin
    NO_DEFAULT_PATH NO_CACHE REQUIRED)

function(_source_text_run)
foreach(_path_name IN ITEMS INPUT OUTPUT INPUT_ROOT OUTPUT_ROOT
        DEVELOPER_INCLUDE_ROOT GEN_INCLUDE_ROOT SOURCE_GEN_INCLUDE_ROOT
        HOSTTOOLS_ROOT BINARY_ROOT RECIPE DEPFILE)
    _source_text_normalize_path("${_path_name}" "${${_path_name}}" "_${_path_name}")
endforeach()
set(_input "${_INPUT}")
set(_output "${_OUTPUT}")
set(_input_root "${_INPUT_ROOT}")
set(_output_root "${_OUTPUT_ROOT}")
set(_developer_root "${_DEVELOPER_INCLUDE_ROOT}")
set(_sdk_root "")
if(DEFINED SDK_INCLUDE_ROOT AND NOT "${SDK_INCLUDE_ROOT}" STREQUAL "")
    _source_text_normalize_path("SDK_INCLUDE_ROOT" "${SDK_INCLUDE_ROOT}" _SDK_INCLUDE_ROOT)
    set(_sdk_root "${_SDK_INCLUDE_ROOT}")
endif()
set(_gen_root "${_GEN_INCLUDE_ROOT}")
set(_source_gen_root "${_SOURCE_GEN_INCLUDE_ROOT}")
set(_hosttools_root "${_HOSTTOOLS_ROOT}")
set(_binary_root "${_BINARY_ROOT}")
set(_recipe "${_RECIPE}")
set(_depfile "${_DEPFILE}")
set(_output_roots _developer_root _gen_root _source_gen_root _hosttools_root)
if(_sdk_root)
    list(APPEND _output_roots _sdk_root)
endif()

if(NOT IS_DIRECTORY "${_binary_root}")
    message(FATAL_ERROR "source text binary root is missing or not a directory")
endif()
_source_text_require_descendant("fetch root" "${_input_root}" "${_binary_root}")
_source_text_require_descendant("input" "${_input}" "${_input_root}")
if(_input STREQUAL _input_root)
    message(FATAL_ERROR "source text input must be a file below its fetch root")
endif()
foreach(_root IN LISTS _output_roots)
    _source_text_require_descendant("configured output root" "${${_root}}" "${_binary_root}")
endforeach()
set(_allowed_output_root FALSE)
foreach(_root IN LISTS _output_roots)
    if(_output_root STREQUAL "${${_root}}")
        set(_allowed_output_root TRUE)
    endif()
endforeach()
if(NOT _allowed_output_root)
    message(FATAL_ERROR "source text output root is not one of the configured roots")
endif()
_source_text_require_descendant("output" "${_output}" "${_output_root}")
if(_output STREQUAL _output_root)
    message(FATAL_ERROR "source text output must be a file below its output root")
endif()
if(_input STREQUAL _output)
    message(FATAL_ERROR "source text input and output are identical")
endif()
if(DEFINED MODE AND NOT "${MODE}" STREQUAL "" AND NOT _output_root STREQUAL _hosttools_root)
    message(FATAL_ERROR "MODE 744 is allowed only for hosttools output")
endif()

set(_private_recipe_root "${_binary_root}/.aros-source-text-rules")
_source_text_require_descendant("private recipe" "${_recipe}" "${_private_recipe_root}")
if(_recipe STREQUAL _private_recipe_root)
    message(FATAL_ERROR "source text recipe must be below its private root")
endif()
_source_text_require_descendant("private depfile" "${_depfile}" "${_private_recipe_root}")
if(_depfile STREQUAL _private_recipe_root OR _depfile STREQUAL _recipe)
    message(FATAL_ERROR "source text depfile must be a distinct file below its private root")
endif()

# Check every component from the build/fetch/output roots. Ancestors outside
# the build tree are not part of the transform's authority boundary.
foreach(_root IN ITEMS _input_root _output_root _private_recipe_root)
    _source_text_check_components("root" "${${_root}}" "${_binary_root}")
endforeach()
foreach(_root IN LISTS _output_roots)
    _source_text_check_components("configured output root" "${${_root}}" "${_binary_root}")
endforeach()
_source_text_check_components("input" "${_input}" "${_input_root}")
_source_text_check_components("output" "${_output}" "${_output_root}")
_source_text_check_components("recipe" "${_recipe}" "${_private_recipe_root}")
_source_text_check_components("depfile" "${_depfile}" "${_private_recipe_root}")
_source_text_check_physical_inside("fetch root" "${_input_root}" "${_binary_root}")
foreach(_root IN LISTS _output_roots)
    _source_text_check_physical_inside("configured output root" "${${_root}}" "${_binary_root}")
endforeach()
_source_text_check_physical_inside("output" "${_output}" "${_binary_root}")

_source_text_require_regular_file("input" "${_input}")
file(SIZE "${_input}" _input_size)
if(_input_size GREATER 33554432)
    message(FATAL_ERROR "source text input exceeds 32 MiB")
endif()
_source_text_require_regular_file("operations recipe" "${_recipe}")
file(SIZE "${_recipe}" _recipe_size)
if(_recipe_size GREATER 1048576)
    message(FATAL_ERROR "source text operations recipe exceeds 1 MiB")
endif()
file(READ "${_recipe}" _operations_json)
_source_text_validate_operations_json("${_operations_json}")
_source_text_path_exists("${_depfile}" _depfile_exists)
if(_depfile_exists)
    _source_text_require_regular_file("existing depfile" "${_depfile}")
endif()

# The regular-file check and size bound precede both reads. HEX form preserves
# arbitrary source bytes, including CRLF and a missing final newline.
file(READ "${_input}" _input_hex HEX)
string(TOLOWER "${_input_hex}" _input_hex)
_source_text_apply_operations("${_input_hex}" "${_operations_json}" _result_hex)
string(LENGTH "${_result_hex}" _result_hex_length)
math(EXPR _result_size "${_result_hex_length} / 2")
if(_result_size GREATER 67108864)
    message(FATAL_ERROR "source text output exceeds 64 MiB")
endif()
_source_text_require_no_nul("transformed output" "${_result_hex}")

# Check existing output types and bounds before replacing it. This command is
# only invoked when Ninja sees a missing/stale output or one of its depfile
# dependencies; publishing even identical bytes refreshes its timestamp.
_source_text_path_exists("${_output}" _output_exists)
if(_output_exists)
    _source_text_require_regular_file("existing output" "${_output}")
    file(SIZE "${_output}" _existing_output_size)
    if(_existing_output_size GREATER 67108864)
        message(FATAL_ERROR "existing source text output exceeds 64 MiB")
    endif()
endif()

string(LENGTH "${_result_hex}" _hex_length)
set(_decoded "")
set(_position 0)
while(_position LESS _hex_length)
    string(SUBSTRING "${_result_hex}" ${_position} 2 _byte_hex)
    math(EXPR _byte "0x${_byte_hex}")
    string(ASCII ${_byte} _character)
    string(APPEND _decoded "${_character}")
    math(EXPR _position "${_position} + 2")
endwhile()

get_filename_component(_output_directory "${_output}" DIRECTORY)
file(MAKE_DIRECTORY "${_output_directory}")
# Repeat checks after directory creation and immediately before publication.
_source_text_check_components("output" "${_output}" "${_output_root}")
_source_text_check_physical_inside("output" "${_output}" "${_binary_root}")
_source_text_path_exists("${_output}" _output_exists)
if(_output_exists)
    _source_text_require_regular_file("existing output" "${_output}")
endif()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef _temporary_suffix)
set(_temporary "${_output}.tmp-${_temporary_suffix}")
set(_depfile_temporary "${_depfile}.tmp-${_temporary_suffix}")
_source_text_check_components("temporary output" "${_temporary}" "${_output_root}")
_source_text_check_components(
    "temporary depfile" "${_depfile_temporary}" "${_private_recipe_root}")
_source_text_path_exists("${_temporary}" _temporary_exists)
_source_text_path_exists("${_depfile_temporary}" _depfile_temporary_exists)
if(_temporary_exists OR _depfile_temporary_exists)
    message(FATAL_ERROR "source text temporary path already exists: ${_temporary}")
endif()
file(WRITE "${_temporary}" "${_decoded}")
if(DEFINED MODE AND NOT "${MODE}" STREQUAL "")
    file(CHMOD "${_temporary}" PERMISSIONS
        OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ WORLD_READ)
endif()
_source_text_require_regular_file("temporary output" "${_temporary}")
_source_text_check_components("output" "${_output}" "${_output_root}")
_source_text_path_exists("${_output}" _output_exists)
if(_output_exists)
    _source_text_require_regular_file("existing output" "${_output}")
endif()
_source_text_escape_dep_path("output" "${_output}" _depfile_output)
_source_text_escape_dep_path("input" "${_input}" _depfile_input)
file(WRITE "${_depfile_temporary}" "${_depfile_output}: ${_depfile_input}\n")
_source_text_require_regular_file("temporary depfile" "${_depfile_temporary}")
file(RENAME "${_depfile_temporary}" "${_depfile}" RESULT _depfile_rename_result)
if(NOT _depfile_rename_result STREQUAL "0")
    file(REMOVE "${_depfile_temporary}" "${_temporary}")
    message(FATAL_ERROR "cannot atomically publish source text depfile: ${_depfile_rename_result}")
endif()
file(RENAME "${_temporary}" "${_output}" RESULT _rename_result)
if(NOT _rename_result STREQUAL "0")
    file(REMOVE "${_temporary}")
    message(FATAL_ERROR "cannot atomically publish source text output: ${_rename_result}")
endif()
endfunction()

function(_source_text_normalize_path label raw out)
    if(NOT IS_ABSOLUTE "${raw}" OR "${raw}" MATCHES "[;\"\r\n$`|&]")
        message(FATAL_ERROR "source text ${label} is not a safe absolute path")
    endif()
    string(LENGTH "${raw}" _length)
    if(_length GREATER 4096)
        message(FATAL_ERROR "source text ${label} exceeds the path length limit")
    endif()
    string(REPLACE "/" ";" _components "${raw}")
    foreach(_component IN LISTS _components)
        if(_component STREQUAL "." OR _component STREQUAL "..")
            message(FATAL_ERROR "source text ${label} contains a dot path component")
        endif()
    endforeach()
    set(_normalized "${raw}")
    cmake_path(NORMAL_PATH _normalized OUTPUT_VARIABLE _normalized)
    if(_normalized STREQUAL "/")
        message(FATAL_ERROR "source text ${label} cannot be the filesystem root")
    endif()
    set(${out} "${_normalized}" PARENT_SCOPE)
endfunction()

function(_source_text_require_descendant label path root)
    cmake_path(IS_PREFIX root "${path}" NORMALIZE _inside)
    if(NOT _inside OR "${path}" STREQUAL "${root}")
        message(FATAL_ERROR "source text ${label} escapes its declared root")
    endif()
endfunction()

function(_source_text_check_components label path root)
    if(IS_SYMLINK "${root}")
        message(FATAL_ERROR "source text ${label} crosses a symlinked root: ${root}")
    endif()
    file(RELATIVE_PATH _relative "${root}" "${path}")
    if(_relative MATCHES "(^|/)\\.\\.(/|$)" OR _relative MATCHES "^\\.\\.")
        message(FATAL_ERROR "source text ${label} escapes its checked root")
    endif()
    if(_relative STREQUAL "." OR _relative STREQUAL "")
        return()
    endif()
    string(REPLACE "/" ";" _components "${_relative}")
    set(_probe "${root}")
    list(LENGTH _components _component_count)
    set(_index 0)
    foreach(_component IN LISTS _components)
        if(_component STREQUAL "")
            continue()
        endif()
        math(EXPR _index "${_index} + 1")
        set(_probe "${_probe}/${_component}")
        if(IS_SYMLINK "${_probe}")
            message(FATAL_ERROR "source text ${label} crosses a symlink: ${_probe}")
        endif()
        if(EXISTS "${_probe}" AND _index LESS _component_count AND
           NOT IS_DIRECTORY "${_probe}")
            message(FATAL_ERROR "source text ${label} parent is not a directory: ${_probe}")
        endif()
    endforeach()
endfunction()

function(_source_text_check_physical_inside label path root)
    file(REAL_PATH "${root}" _root_real)
    set(_existing "${path}")
    while(NOT EXISTS "${_existing}")
        if(IS_SYMLINK "${_existing}")
            message(FATAL_ERROR "source text ${label} crosses a dangling symlink")
        endif()
        cmake_path(GET _existing PARENT_PATH _parent)
        if(_parent STREQUAL _existing)
            message(FATAL_ERROR "source text ${label} has no safe existing ancestor")
        endif()
        set(_existing "${_parent}")
    endwhile()
    file(REAL_PATH "${_existing}" _existing_real)
    cmake_path(IS_PREFIX _root_real "${_existing_real}" NORMALIZE _inside)
    if(NOT _inside)
        message(FATAL_ERROR "source text ${label} physically escapes its declared root")
    endif()
endfunction()

function(_source_text_path_exists path out)
    execute_process(
        COMMAND "${_source_text_test}" -e "${path}"
        RESULT_VARIABLE _result OUTPUT_QUIET ERROR_QUIET TIMEOUT 10)
    if(_result STREQUAL "0")
        set(${out} TRUE PARENT_SCOPE)
    else()
        set(${out} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(_source_text_require_regular_file label path)
    execute_process(
        COMMAND "${_source_text_test}" -f "${path}"
        RESULT_VARIABLE _result OUTPUT_QUIET ERROR_QUIET TIMEOUT 10)
    if(NOT _result STREQUAL "0")
        message(FATAL_ERROR "source text ${label} is not a regular file: ${path}")
    endif()
endfunction()

function(_source_text_validate_operations_json json)
    string(JSON _root_type ERROR_VARIABLE _json_error TYPE "${json}")
    if(NOT _json_error STREQUAL "NOTFOUND" OR NOT _root_type STREQUAL "ARRAY")
        message(FATAL_ERROR "source text operations recipe is not a JSON array")
    endif()
    string(JSON _count ERROR_VARIABLE _json_error LENGTH "${json}")
    if(NOT _json_error STREQUAL "NOTFOUND" OR _count LESS 1 OR _count GREATER 128)
        message(FATAL_ERROR "source text operations count must be 1 to 128")
    endif()
    math(EXPR _last_index "${_count} - 1")
    foreach(_index RANGE 0 ${_last_index})
        string(JSON _type ERROR_VARIABLE _json_error TYPE "${json}" ${_index})
        if(NOT _json_error STREQUAL "NOTFOUND" OR NOT _type STREQUAL "OBJECT")
            message(FATAL_ERROR "source text operation ${_index} is not an object")
        endif()
        string(JSON _members ERROR_VARIABLE _json_error LENGTH "${json}" ${_index})
        if(NOT _json_error STREQUAL "NOTFOUND" OR NOT _members EQUAL 3)
            message(FATAL_ERROR "source text operation ${_index} must have exactly three fields")
        endif()
        foreach(_field IN ITEMS kind token replacement)
            string(JSON _type ERROR_VARIABLE _json_error TYPE "${json}" ${_index} "${_field}")
            if(NOT _json_error STREQUAL "NOTFOUND" OR NOT _type STREQUAL "STRING")
                message(FATAL_ERROR "source text operation ${_index} ${_field} must be a string")
            endif()
        endforeach()
        string(JSON _kind GET "${json}" ${_index} kind)
        string(JSON _token GET "${json}" ${_index} token)
        string(JSON _replacement GET "${json}" ${_index} replacement)
        if(NOT _kind STREQUAL "replace_all" AND
           NOT _kind STREQUAL "replace_whole_line_containing")
            message(FATAL_ERROR "source text operation ${_index} has unsupported kind")
        endif()
        if(_token STREQUAL "")
            message(FATAL_ERROR "source text operation ${_index} has an empty token")
        endif()
        string(LENGTH "${_token}" _token_length)
        string(LENGTH "${_replacement}" _replacement_length)
        if(_token_length GREATER 262144 OR _replacement_length GREATER 262144)
            message(FATAL_ERROR "source text operation ${_index} field exceeds 256 KiB")
        endif()
    endforeach()
endfunction()

function(_source_text_escape_dep_path label path out)
    set(_escaped "${path}")
    string(REPLACE "\\" "\\\\" _escaped "${_escaped}")
    string(REPLACE " " "\\ " _escaped "${_escaped}")
    string(REPLACE "#" "\\#" _escaped "${_escaped}")
    string(REPLACE ":" "\\:" _escaped "${_escaped}")
    set(${out} "${_escaped}" PARENT_SCOPE)
endfunction()

function(_source_text_apply_operations input_hex operations_json out)
    set(_working "${input_hex}")
    string(JSON _operation_count LENGTH "${operations_json}")
    math(EXPR _last_index "${_operation_count} - 1")
    foreach(_index RANGE 0 ${_last_index})
        string(JSON _kind GET "${operations_json}" ${_index} kind)
        string(JSON _token GET "${operations_json}" ${_index} token)
        string(JSON _replacement GET "${operations_json}" ${_index} replacement)
        string(HEX "${_token}" _token_hex)
        string(HEX "${_replacement}" _replacement_hex)
        string(TOLOWER "${_token_hex}" _token_hex)
        string(TOLOWER "${_replacement_hex}" _replacement_hex)
        if(_kind STREQUAL "replace_all")
            _source_text_replace_all_hex(
                "${_working}" "${_token_hex}" "${_replacement_hex}" _next)
        else()
            _source_text_replace_whole_line_hex(
                "${_working}" "${_token_hex}" "${_replacement_hex}" _next)
        endif()
        set(_working "${_next}")
    endforeach()
    set(${out} "${_working}" PARENT_SCOPE)
endfunction()

function(_source_text_replace_all_hex input_hex token_hex replacement_hex out)
    string(LENGTH "${input_hex}" _input_length)
    string(LENGTH "${token_hex}" _token_length)
    string(LENGTH "${replacement_hex}" _replacement_length)
    set(_output "")
    set(_output_length 0)
    set(_copy_cursor 0)
    set(_search_cursor 0)
    set(_limit 134217728)
    while(_search_cursor LESS _input_length)
        _source_text_find_aligned_hex(
            "${input_hex}" "${token_hex}" "${_search_cursor}" _match)
        if(_match EQUAL -1)
            break()
        endif()
        math(EXPR _prefix_length "${_match} - ${_copy_cursor}")
        string(SUBSTRING "${input_hex}" ${_copy_cursor} ${_prefix_length} _prefix)
        string(LENGTH "${_prefix}" _prefix_length)
        math(EXPR _next_length "${_output_length} + ${_prefix_length} + ${_replacement_length}")
        if(_next_length GREATER _limit)
            message(FATAL_ERROR "source text output exceeds 64 MiB during replacement")
        endif()
        string(APPEND _output "${_prefix}${replacement_hex}")
        set(_output_length "${_next_length}")
        math(EXPR _copy_cursor "${_match} + ${_token_length}")
        set(_search_cursor "${_copy_cursor}")
    endwhile()
    math(EXPR _tail_length "${_input_length} - ${_copy_cursor}")
    math(EXPR _next_length "${_output_length} + ${_tail_length}")
    if(_next_length GREATER _limit)
        message(FATAL_ERROR "source text output exceeds 64 MiB during replacement")
    endif()
    string(SUBSTRING "${input_hex}" ${_copy_cursor} ${_tail_length} _tail)
    string(APPEND _output "${_tail}")
    set(${out} "${_output}" PARENT_SCOPE)
endfunction()

function(_source_text_replace_whole_line_hex input_hex token_hex replacement_hex out)
    string(LENGTH "${input_hex}" _input_length)
    string(LENGTH "${token_hex}" _token_length)
    string(LENGTH "${replacement_hex}" _replacement_length)
    set(_output "")
    set(_output_length 0)
    set(_cursor 0)
    set(_limit 134217728)
    while(_cursor LESS _input_length)
        _source_text_find_aligned_hex("${input_hex}" "0a" "${_cursor}" _lf_at)
        set(_has_lf FALSE)
        if(_lf_at EQUAL -1)
            math(EXPR _line_end "${_input_length} - ${_cursor}")
        else()
            set(_has_lf TRUE)
            math(EXPR _line_end "${_lf_at} - ${_cursor}")
        endif()
        string(SUBSTRING "${input_hex}" ${_cursor} ${_line_end} _line)
        set(_terminator "")
        set(_line_ending_crlf FALSE)
        if(_has_lf)
            set(_terminator "0a")
        endif()
        string(LENGTH "${_line}" _line_length)
        if(_line_length GREATER_EQUAL 2)
            math(EXPR _last_byte_offset "${_line_length} - 2")
            string(SUBSTRING "${_line}" ${_last_byte_offset} 2 _last_byte)
            if(_has_lf AND _last_byte STREQUAL "0d")
                string(SUBSTRING "${_line}" 0 ${_last_byte_offset} _line)
                set(_terminator "0d0a")
                set(_line_ending_crlf TRUE)
                math(EXPR _line_length "${_line_length} - 2")
            endif()
        endif()
        _source_text_find_aligned_hex("${_line}" "${token_hex}" 0 _match)
        set(_replace_line FALSE)
        if(NOT _match EQUAL -1)
            set(_replace_line TRUE)
        endif()
        if(_replace_line)
            set(_line_output "${replacement_hex}")
            string(LENGTH "${_line_output}" _line_output_length)
            if(_line_ending_crlf)
                # GNU sed's pattern space contains the CR byte, so replacing
                # the whole matched line consumes it; sed still emits LF.
                set(_output_terminator "0a")
            else()
                set(_output_terminator "${_terminator}")
            endif()
        else()
            set(_line_output "${_line}")
            set(_line_output_length "${_line_length}")
            set(_output_terminator "${_terminator}")
        endif()
        string(LENGTH "${_output_terminator}" _terminator_length)
        math(EXPR _next_length
            "${_output_length} + ${_line_output_length} + ${_terminator_length}")
        if(_next_length GREATER _limit)
            message(FATAL_ERROR "source text output exceeds 64 MiB during line replacement")
        endif()
        string(APPEND _output "${_line_output}${_output_terminator}")
        set(_output_length "${_next_length}")
        if(_has_lf)
            math(EXPR _cursor "${_cursor} + ${_line_end} + 2")
        else()
            set(_cursor "${_input_length}")
        endif()
    endwhile()
    set(${out} "${_output}" PARENT_SCOPE)
endfunction()

function(_source_text_find_aligned_hex input_hex needle_hex start out)
    string(LENGTH "${input_hex}" _input_length)
    set(_search_cursor "${start}")
    while(_search_cursor LESS _input_length)
        string(SUBSTRING "${input_hex}" ${_search_cursor} -1 _search_tail)
        string(FIND "${_search_tail}" "${needle_hex}" _relative_match)
        if(_relative_match EQUAL -1)
            set(${out} -1 PARENT_SCOPE)
            return()
        endif()
        math(EXPR _match "${_search_cursor} + ${_relative_match}")
        math(EXPR _alignment "${_match} % 2")
        if(_alignment EQUAL 0)
            set(${out} "${_match}" PARENT_SCOPE)
            return()
        endif()
        math(EXPR _search_cursor "${_match} + 1")
    endwhile()
    set(${out} -1 PARENT_SCOPE)
endfunction()

function(_source_text_require_no_nul label hex)
    string(LENGTH "${hex}" _length)
    set(_cursor 0)
    while(_cursor LESS _length)
        string(SUBSTRING "${hex}" ${_cursor} -1 _tail)
        string(FIND "${_tail}" "00" _relative_nul)
        if(_relative_nul EQUAL -1)
            break()
        endif()
        math(EXPR _nul_at "${_cursor} + ${_relative_nul}")
        math(EXPR _alignment "${_nul_at} % 2")
        if(_alignment EQUAL 0)
            message(FATAL_ERROR "source text ${label} contains a NUL byte")
        endif()
        math(EXPR _cursor "${_nul_at} + 1")
    endwhile()
endfunction()

_source_text_run()
