cmake_minimum_required(VERSION 3.22)
include("${CMAKE_CURRENT_LIST_DIR}/SfdHeaders.cmake")
if(NOT RECIPE OR NOT RECIPE_SHA256 OR IS_SYMLINK "${RECIPE}" OR
   NOT EXISTS "${RECIPE}" OR IS_DIRECTORY "${RECIPE}")
    message(FATAL_ERROR "SFD runner requires a regular sealed recipe")
endif()
file(SHA256 "${RECIPE}" _recipe_hash)
if(NOT _recipe_hash STREQUAL RECIPE_SHA256)
    message(FATAL_ERROR "SFD recipe changed after configuration")
endif()
include("${RECIPE}")
function(_sfd_validate)
    _aros_genmodule_header_check_output("${RECIPE}" "${SFD_BINARY_ROOT}" "SFD runner")
    _aros_genmodule_header_check_output_root("${SFD_SDK_ROOT}" "${SFD_BINARY_ROOT}" "SFD runner")
    _aros_sfd_regular("${SFD_SOURCE_ROOT}" "${SFD_FILE}" "${SFD_FILE_SHA256}")
    foreach(_proof IN LISTS SFD_TOOL_PROOF)
        string(REPLACE "|" ";" _fields "${_proof}")
        list(GET _fields 0 _input)
        list(GET _fields 1 _hash)
        _aros_sfd_regular("${SFD_SOURCE_ROOT}" "${_input}" "${_hash}")
    endforeach()
    foreach(_job IN LISTS SFD_JOBS)
        string(REPLACE "|" ";" _fields "${_job}")
        list(GET _fields 2 _input)
        list(GET _fields 3 _hash)
        list(GET _fields 4 _output)
        _aros_sfd_regular("${SFD_SOURCE_ROOT}" "${_input}" "${_hash}")
        _aros_genmodule_header_check_output("${SFD_SDK_ROOT}/${_output}" "${SFD_SDK_ROOT}" "SFD runner")
    endforeach()
    _aros_genmodule_header_check_output("${SFD_TOOL}" "${SFD_BINARY_ROOT}" "SFD runner")
    if(EXISTS "${SFD_TOOL}")
        if(IS_DIRECTORY "${SFD_TOOL}" OR IS_SYMLINK "${SFD_TOOL}")
            message(FATAL_ERROR "SFD host compiler is not a regular private file")
        endif()
        file(SHA256 "${SFD_TOOL}" _current_tool_hash)
        if(NOT _current_tool_hash STREQUAL SFD_TOOL_SHA256)
            message(FATAL_ERROR "SFD host compiler identity changed")
        endif()
    endif()
endfunction()
_sfd_validate()
if(CHECK_ONLY)
    return()
endif()
_aros_genmodule_header_check_output("${SFD_TOOL}" "${SFD_BINARY_ROOT}" "SFD runner")
if(NOT EXISTS "${SFD_TOOL}" OR IS_DIRECTORY "${SFD_TOOL}" OR IS_SYMLINK "${SFD_TOOL}")
    message(FATAL_ERROR "SFD runner lacks its private host compiler")
endif()
file(SHA256 "${SFD_TOOL}" _tool_hash)
if(NOT _tool_hash STREQUAL SFD_TOOL_SHA256)
    message(FATAL_ERROR "SFD host compiler identity changed")
endif()
set(_staged "")
string(RANDOM LENGTH 24 ALPHABET 0123456789abcdef _stage_nonce)
set(_stage_root "${SFD_BINARY_ROOT}/.aros-sfd-stage-${_stage_nonce}")
_aros_genmodule_header_check_output("${_stage_root}" "${SFD_BINARY_ROOT}" "SFD runner")
if(EXISTS "${_stage_root}" OR IS_SYMLINK "${_stage_root}")
    message(FATAL_ERROR "SFD private staging path already exists")
endif()
file(MAKE_DIRECTORY "${_stage_root}")
set(_stage_index 0)
foreach(_job IN LISTS SFD_JOBS)
    string(REPLACE "|" ";" _fields "${_job}")
    list(GET _fields 0 _mode)
    list(GET _fields 1 _target)
    list(GET _fields 2 _input)
    list(GET _fields 4 _output)
    set(_destination "${SFD_SDK_ROOT}/${_output}")
    get_filename_component(_parent "${_destination}" DIRECTORY)
    _aros_genmodule_header_check_output("${_destination}" "${SFD_SDK_ROOT}" "SFD runner")
    file(MAKE_DIRECTORY "${_parent}")
    math(EXPR _stage_index "${_stage_index} + 1")
    set(_temporary "${_stage_root}/${_stage_index}.h")
    _aros_genmodule_header_check_output("${_temporary}" "${_stage_root}" "SFD runner")
    if(EXISTS "${_temporary}" OR IS_SYMLINK "${_temporary}")
        message(FATAL_ERROR "SFD header staging output already exists")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env
        --unset=PERL5OPT --unset=PERL5LIB --unset=PERLLIB
        --unset=PERL_UNICODE --unset=PERLIO LC_ALL=C LANG=C
        /usr/bin/perl "${SFD_TOOL}" "--mode=${_mode}"
        "--target=${_target}" "--output=${_temporary}" "${SFD_SOURCE_ROOT}/${_input}"
        RESULT_VARIABLE _result OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
    if(NOT _result EQUAL 0 OR NOT EXISTS "${_temporary}" OR
       IS_DIRECTORY "${_temporary}" OR IS_SYMLINK "${_temporary}")
        foreach(_pair IN LISTS _staged)
            string(REPLACE "|" ";" _previous "${_pair}")
            list(GET _previous 0 _previous_file)
            file(REMOVE "${_previous_file}")
        endforeach()
        if(EXISTS "${_temporary}" AND NOT IS_DIRECTORY "${_temporary}")
            file(REMOVE "${_temporary}")
        endif()
        # This fresh, validated directory belongs exclusively to this invocation.
        file(REMOVE_RECURSE "${_stage_root}")
        message(FATAL_ERROR "SFD header generation failed (${_result}): ${_stdout}${_stderr}")
    endif()
    list(APPEND _staged "${_temporary}|${_destination}")
endforeach()
_sfd_validate()
file(SHA256 "${SFD_TOOL}" _tool_hash_after)
if(NOT _tool_hash_after STREQUAL SFD_TOOL_SHA256)
    message(FATAL_ERROR "SFD host compiler changed during generation")
endif()
foreach(_pair IN LISTS _staged)
    string(REPLACE "|" ";" _fields "${_pair}")
    list(GET _fields 0 _temporary)
    list(GET _fields 1 _destination)
    _aros_genmodule_header_check_output("${_temporary}" "${_stage_root}" "SFD runner")
    _aros_genmodule_header_check_output("${_destination}" "${SFD_SDK_ROOT}" "SFD runner")
    file(RENAME "${_temporary}" "${_destination}")
endforeach()
file(REMOVE_RECURSE "${_stage_root}")
