cmake_minimum_required(VERSION 3.22)
include("${CMAKE_CURRENT_LIST_DIR}/SdkFileCopies.cmake")
_aros_sdk_copy_find_test(_test_program)
foreach(_variable IN ITEMS BINARY_ROOT ASSET_ROOT OUTPUT)
    _aros_sdk_copy_normalize_path("${_variable}" "${${_variable}}" _normalized)
    set(${_variable} "${_normalized}")
endforeach()
_aros_sdk_copy_require_descendant("asset root" "${ASSET_ROOT}" "${BINARY_ROOT}" FALSE)
cmake_path(GET OUTPUT PARENT_PATH _parent)
cmake_path(GET OUTPUT FILENAME _basename)
if(NOT _parent STREQUAL ASSET_ROOT OR NOT _basename MATCHES "^[A-Za-z0-9][A-Za-z0-9_.+-]*$")
    message(FATAL_ERROR "SDK asset output escapes its exact root")
endif()
_aros_sdk_copy_check_components("output" "${OUTPUT}" "${BINARY_ROOT}")
_aros_sdk_copy_check_physical_ancestor("output" "${OUTPUT}" "${BINARY_ROOT}")
_aros_sdk_copy_path_exists("${OUTPUT}" _exists)
if(_exists)
    _aros_sdk_copy_require_regular_file("output" "${OUTPUT}" "${_test_program}")
endif()
file(MAKE_DIRECTORY "${ASSET_ROOT}")
_aros_sdk_copy_check_components("asset root" "${ASSET_ROOT}" "${BINARY_ROOT}")
string(RANDOM LENGTH 24 ALPHABET 0123456789abcdef _nonce)
set(_temporary "${OUTPUT}.tmp-${_nonce}")
_aros_sdk_copy_check_components("temporary output" "${_temporary}" "${BINARY_ROOT}")
if(KIND STREQUAL copy)
    _aros_sdk_copy_normalize_path("input" "${INPUT}" INPUT)
    cmake_path(GET INPUT PARENT_PATH _input_parent)
    if(NOT _input_parent STREQUAL ASSET_ROOT OR INPUT STREQUAL OUTPUT)
        message(FATAL_ERROR "SDK alias input escapes its exact root")
    endif()
    _aros_sdk_copy_check_components("input" "${INPUT}" "${BINARY_ROOT}")
    _aros_sdk_copy_check_physical_ancestor("input" "${INPUT}" "${BINARY_ROOT}")
    _aros_sdk_copy_require_regular_file("input" "${INPUT}" "${_test_program}")
    file(SIZE "${INPUT}" _size)
    if(_size GREATER 16777216)
        message(FATAL_ERROR "SDK alias input exceeds 16 MiB")
    endif()
    file(SHA256 "${INPUT}" _before)
    file(COPY_FILE "${INPUT}" "${_temporary}" RESULT _result)
    if(NOT _result STREQUAL "0")
        message(FATAL_ERROR "SDK alias copy failed: ${_result}")
    endif()
    execute_process(COMMAND "${_test_program}" -x "${INPUT}" RESULT_VARIABLE _executable)
    if(_executable STREQUAL "0")
        file(CHMOD "${_temporary}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
    else()
        file(CHMOD "${_temporary}" PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ)
    endif()
    _aros_sdk_copy_check_components("input before publication" "${INPUT}" "${BINARY_ROOT}")
    _aros_sdk_copy_require_regular_file("input before publication" "${INPUT}" "${_test_program}")
    file(SHA256 "${INPUT}" _after)
    file(SHA256 "${_temporary}" _staged)
    if(NOT _before STREQUAL _after OR NOT _before STREQUAL _staged)
        file(REMOVE "${_temporary}")
        message(FATAL_ERROR "SDK alias input changed during staging")
    endif()
elseif(KIND STREQUAL text)
    string(LENGTH "${TEXT_HEX}" _length)
    math(EXPR _odd "${_length} % 2")
    if(NOT TEXT_HEX MATCHES "^[0-9a-f]+$" OR _length GREATER 1024 OR _odd)
        message(FATAL_ERROR "SDK literal text is not bounded hexadecimal bytes")
    endif()
    set(_text "")
    math(EXPR _last "${_length} - 2")
    foreach(_index RANGE 0 ${_last} 2)
        string(SUBSTRING "${TEXT_HEX}" ${_index} 2 _hex)
        math(EXPR _byte "0x${_hex}")
        if(_byte LESS 32 OR _byte GREATER 126)
            message(FATAL_ERROR "SDK literal text contains a control or non-ASCII byte")
        endif()
        string(ASCII ${_byte} _character)
        string(APPEND _text "${_character}")
    endforeach()
    file(WRITE "${_temporary}" "${_text}\n")
    file(CHMOD "${_temporary}" PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ)
else()
    message(FATAL_ERROR "unknown SDK asset operation")
endif()
_aros_sdk_copy_require_regular_file("temporary output" "${_temporary}" "${_test_program}")
_aros_sdk_copy_check_components("output before publication" "${OUTPUT}" "${BINARY_ROOT}")
_aros_sdk_copy_path_exists("${OUTPUT}" _exists)
if(_exists)
    _aros_sdk_copy_require_regular_file("output before publication" "${OUTPUT}" "${_test_program}")
endif()
file(RENAME "${_temporary}" "${OUTPUT}" RESULT _result)
if(NOT _result STREQUAL "0")
    file(REMOVE "${_temporary}")
    message(FATAL_ERROR "SDK asset publication failed: ${_result}")
endif()
