cmake_minimum_required(VERSION 3.22)
include("${CMAKE_CURRENT_LIST_DIR}/LiteralObjects.cmake")

if(NOT IS_ABSOLUTE "${COMMAND_FILE}" OR NOT IS_ABSOLUTE "${COMMAND_ROOT}" OR
   NOT VERIFY_ONLY MATCHES "^(ON|OFF)$" OR NOT COMMAND_SHA256 MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "Source archive runner: invalid sealed command identity")
endif()
string(LENGTH "${COMMAND_SHA256}" digest_length)
if(NOT digest_length EQUAL 64)
    message(FATAL_ERROR "Source archive runner: invalid command digest")
endif()
_aros_literal_check_root("${COMMAND_ROOT}" "command root")
_aros_literal_check_path_chain("${COMMAND_FILE}" "${COMMAND_ROOT}" "command file")
_aros_literal_assert_regular("${COMMAND_FILE}" "command file" FALSE)
file(SHA256 "${COMMAND_FILE}" actual_digest)
if(NOT actual_digest STREQUAL COMMAND_SHA256)
    message(FATAL_ERROR "Source archive runner: changed command file refused")
endif()
include("${COMMAND_FILE}")
foreach(key OUTPUT BUILD_ROOT AR RANLIB AR_FLAGS)
    _aros_literal_reject_control_text("${${key}}" "archive command")
endforeach()
if(NOT AR_FLAGS STREQUAL "cr" OR NOT OBJECTS OR NOT IS_ABSOLUTE "${OUTPUT}")
    message(FATAL_ERROR "Source archive runner: invalid archive command roles")
endif()
_aros_literal_check_root("${BUILD_ROOT}" "build root")
_aros_literal_check_path_chain("${OUTPUT}" "${BUILD_ROOT}" "archive output")
_aros_literal_check_optional_regular("${OUTPUT}" "archive output")
foreach(tool AR RANLIB)
    _aros_literal_check_absolute_chain("${${tool}}" "archive tool")
    _aros_literal_assert_regular("${${tool}}" "archive tool" TRUE)
endforeach()
foreach(object IN LISTS OBJECTS)
    _aros_literal_reject_control_text("${object}" "archive member")
    _aros_literal_check_path_chain("${object}" "${BUILD_ROOT}/gen" "archive member")
    _aros_literal_check_optional_regular("${object}" "archive member")
    if(NOT VERIFY_ONLY)
        _aros_literal_assert_regular("${object}" "archive member" FALSE)
    endif()
endforeach()
if(VERIFY_ONLY)
    return()
endif()
cmake_path(GET OUTPUT PARENT_PATH output_directory)
file(MAKE_DIRECTORY "${output_directory}")
set(staging "${OUTPUT}.aros-staging")
_aros_literal_check_path_chain("${staging}" "${BUILD_ROOT}" "archive staging")
_aros_literal_check_optional_regular("${staging}" "archive staging")
# Starting a fresh archive prevents removed members surviving an incremental
# rule change. Publication is atomic and never exposes a failed AR/RANLIB run.
file(REMOVE "${staging}")
execute_process(COMMAND "${AR}" "${AR_FLAGS}" "${staging}" ${OBJECTS}
    RESULT_VARIABLE ar_result OUTPUT_VARIABLE ar_stdout ERROR_VARIABLE ar_stderr)
if(NOT ar_result STREQUAL "0")
    message(FATAL_ERROR "Source archive runner: AR failed (${ar_result})\n${ar_stdout}\n${ar_stderr}")
endif()
_aros_literal_check_path_chain("${staging}" "${BUILD_ROOT}" "archive staging")
_aros_literal_assert_regular("${staging}" "archive staging" FALSE)
execute_process(COMMAND "${RANLIB}" "${staging}"
    RESULT_VARIABLE ranlib_result OUTPUT_VARIABLE ranlib_stdout ERROR_VARIABLE ranlib_stderr)
if(NOT ranlib_result STREQUAL "0")
    message(FATAL_ERROR "Source archive runner: RANLIB failed (${ranlib_result})\n${ranlib_stdout}\n${ranlib_stderr}")
endif()
_aros_literal_check_path_chain("${staging}" "${BUILD_ROOT}" "archive staging")
_aros_literal_assert_regular("${staging}" "archive staging" FALSE)
_aros_literal_check_path_chain("${OUTPUT}" "${BUILD_ROOT}" "archive output")
_aros_literal_check_optional_regular("${OUTPUT}" "archive output")
file(RENAME "${staging}" "${OUTPUT}")
