cmake_minimum_required(VERSION 3.22)
include("${CMAKE_CURRENT_LIST_DIR}/SourceValueRules.cmake")

function(_aros_source_value_recheck binary_root recipe recipe_hash source_root input input_hash
        file_relative file_sha output prefs_root)
    _aros_source_value_canonical_root("binary root" "${binary_root}" _root)
    _aros_source_value_check_components("private recipe" "${recipe}" "${_root}")
    _aros_source_value_require_regular_file("private recipe" "${recipe}")
    file(SHA256 "${recipe}" _recipe_hash)
    if(NOT _recipe_hash STREQUAL recipe_hash)
        message(FATAL_ERROR "source value private recipe changed during extraction")
    endif()
    _aros_source_value_validate_source_paths(
        "${source_root}" "${input}" "${file_relative}" "${file_sha}")
    file(SHA256 "${input}" _input_hash)
    if(NOT _input_hash STREQUAL input_hash)
        message(FATAL_ERROR "source value input changed during extraction")
    endif()
    _aros_source_value_check_components("output" "${output}" "${_root}")
    _aros_source_value_check_physical_inside("output" "${output}" "${prefs_root}")
    _aros_source_value_check_existing_output("output" "${output}")
endfunction()

foreach(_required IN ITEMS BINARY_ROOT RECIPE RECIPE_SHA256)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "RunSourceValueRule requires ${_required}")
    endif()
endforeach()
_aros_source_value_validate_sha256("RECIPE_SHA256" "${RECIPE_SHA256}" _expected_recipe_hash)
_aros_source_value_canonical_root("binary root" "${BINARY_ROOT}" _binary_root)

set(_private_root "${_binary_root}/.aros-source-value-rules")
_aros_source_value_validate_absolute_path("private recipe" "${RECIPE}" _recipe)
_aros_source_value_require_descendant("private recipe" "${_recipe}" "${_private_root}")
_aros_source_value_check_components("private recipe" "${_recipe}" "${_binary_root}")
_aros_source_value_require_regular_file("private recipe" "${_recipe}")
file(SIZE "${_recipe}" _recipe_size)
if(_recipe_size GREATER 16384)
    message(FATAL_ERROR "source value private recipe exceeds 16 KiB")
endif()
file(SHA256 "${_recipe}" _actual_recipe_hash)
if(NOT _actual_recipe_hash STREQUAL _expected_recipe_hash)
    message(FATAL_ERROR "source value private recipe changed after configuration")
endif()
file(READ "${_recipe}" _recipe_json)
string(JSON _recipe_type ERROR_VARIABLE _json_error TYPE "${_recipe_json}")
if(NOT _json_error STREQUAL "NOTFOUND" OR NOT _recipe_type STREQUAL "OBJECT")
    message(FATAL_ERROR "source value private recipe is malformed")
endif()
string(JSON _member_count ERROR_VARIABLE _json_error LENGTH "${_recipe_json}")
if(NOT _json_error STREQUAL "NOTFOUND" OR NOT _member_count EQUAL 8)
    message(FATAL_ERROR "source value private recipe has an unexpected field set")
endif()
foreach(_field IN ITEMS version binary_root source_root input output file file_sha256 marker_hex)
    string(JSON _field_type ERROR_VARIABLE _json_error TYPE "${_recipe_json}" "${_field}")
    if(NOT _json_error STREQUAL "NOTFOUND" OR NOT _field_type STREQUAL "STRING")
        message(FATAL_ERROR "source value private recipe field ${_field} is malformed")
    endif()
    string(JSON "_sv_${_field}" GET "${_recipe_json}" "${_field}")
endforeach()
if(NOT _sv_version STREQUAL "1" OR NOT _sv_binary_root STREQUAL _binary_root)
    message(FATAL_ERROR "source value private recipe has a mismatched version or build root")
endif()

_aros_source_value_validate_marker_hex("${_sv_marker_hex}" _marker_hex)
_aros_source_value_validate_source_paths(
    "${_sv_source_root}" "${_sv_input}" "${_sv_file}" "${_sv_file_sha256}")
set(_source_root "${AROS_SOURCE_VALUE_VALIDATED_ROOT}")
set(_input "${AROS_SOURCE_VALUE_VALIDATED_INPUT}")
set(_declaring_file "${AROS_SOURCE_VALUE_VALIDATED_FILE}")
set(_file_sha256 "${AROS_SOURCE_VALUE_VALIDATED_FILE_SHA}")

set(_prefs_root "${_binary_root}/SYS/Prefs")
_aros_source_value_validate_absolute_path("output" "${_sv_output}" _output)
_aros_source_value_require_descendant("output" "${_output}" "${_prefs_root}")
_aros_source_value_check_components("output" "${_output}" "${_binary_root}")
_aros_source_value_path_exists("${_prefs_root}" _prefs_exists)
if(_prefs_exists AND NOT IS_DIRECTORY "${_prefs_root}")
    message(FATAL_ERROR "canonical AROS_PREFS root is not a directory")
endif()
file(MAKE_DIRECTORY "${_prefs_root}")
_aros_source_value_check_components("AROS_PREFS root" "${_prefs_root}" "${_binary_root}")
_aros_source_value_check_physical_inside("output" "${_output}" "${_prefs_root}")
_aros_source_value_check_existing_output("output" "${_output}")

file(SHA256 "${_input}" _input_hash_before)
file(READ "${_input}" _input_hex HEX)
string(TOLOWER "${_input_hex}" _input_hex)
file(SHA256 "${_input}" _input_hash_after_read)
if(NOT _input_hash_before STREQUAL _input_hash_after_read)
    message(FATAL_ERROR "source value input changed while being read")
endif()
_aros_source_value_compute("${_input_hex}" "${_marker_hex}" _result_hex)
string(LENGTH "${_result_hex}" _result_hex_length)
if(_result_hex_length GREATER 67108864)
    message(FATAL_ERROR "source value output exceeds 32 MiB")
endif()

_aros_source_value_path_exists("${_output}" _output_exists)
set(_old_output_hash "")
if(_output_exists)
    _aros_source_value_require_regular_file("existing output" "${_output}")
    file(SIZE "${_output}" _output_size)
    if(_output_size GREATER 33554432)
        message(FATAL_ERROR "existing source value output exceeds 32 MiB")
    endif()
    file(READ "${_output}" _existing_output_hex HEX)
    string(TOLOWER "${_existing_output_hex}" _existing_output_hex)
    if(_existing_output_hex STREQUAL _result_hex)
        _aros_source_value_recheck("${_binary_root}" "${_recipe}" "${_expected_recipe_hash}"
            "${_source_root}" "${_input}" "${_input_hash_before}"
            "${_sv_file}" "${_file_sha256}" "${_output}" "${_prefs_root}")
        return()
    endif()
    file(SHA256 "${_output}" _old_output_hash)
endif()

_aros_source_value_decode_hex("${_result_hex}" _decoded_output)
get_filename_component(_output_parent "${_output}" DIRECTORY)
file(MAKE_DIRECTORY "${_output_parent}")
_aros_source_value_check_components("output" "${_output}" "${_binary_root}")
_aros_source_value_check_physical_inside("output" "${_output}" "${_prefs_root}")
_aros_source_value_check_existing_output("output" "${_output}")

string(RANDOM LENGTH 20 ALPHABET 0123456789abcdef _nonce)
set(_temporary "${_output}.tmp-${_nonce}")
_aros_source_value_check_components("temporary output" "${_temporary}" "${_prefs_root}")
_aros_source_value_path_exists("${_temporary}" _temporary_exists)
if(_temporary_exists OR IS_SYMLINK "${_temporary}")
    message(FATAL_ERROR "source value temporary output already exists")
endif()
file(WRITE "${_temporary}" "${_decoded_output}")
_aros_source_value_require_regular_file("temporary output" "${_temporary}")

_aros_source_value_recheck("${_binary_root}" "${_recipe}" "${_expected_recipe_hash}"
    "${_source_root}" "${_input}" "${_input_hash_before}"
    "${_sv_file}" "${_file_sha256}" "${_output}" "${_prefs_root}")
_aros_source_value_path_exists("${_output}" _output_now_exists)
if(_output_exists)
    if(NOT _output_now_exists)
        file(REMOVE "${_temporary}")
        message(FATAL_ERROR "source value output disappeared during publication")
    endif()
    file(SHA256 "${_output}" _output_hash_before_publish)
    if(NOT _output_hash_before_publish STREQUAL _old_output_hash)
        file(READ "${_output}" _current_output_hex HEX)
        string(TOLOWER "${_current_output_hex}" _current_output_hex)
        if(_current_output_hex STREQUAL _result_hex)
            file(REMOVE "${_temporary}")
            return()
        endif()
        file(REMOVE "${_temporary}")
        message(FATAL_ERROR "source value output changed during publication")
    endif()
elseif(_output_now_exists)
    file(READ "${_output}" _current_output_hex HEX)
    string(TOLOWER "${_current_output_hex}" _current_output_hex)
    if(_current_output_hex STREQUAL _result_hex)
        file(REMOVE "${_temporary}")
        return()
    endif()
    file(REMOVE "${_temporary}")
    message(FATAL_ERROR "source value output appeared during publication")
endif()

file(RENAME "${_temporary}" "${_output}" RESULT _rename_result)
if(NOT _rename_result STREQUAL "0")
    file(REMOVE "${_temporary}")
    message(FATAL_ERROR "cannot atomically publish source value output: ${_rename_result}")
endif()
_aros_source_value_check_existing_output("published output" "${_output}")
file(READ "${_output}" _published_output_hex HEX)
string(TOLOWER "${_published_output_hex}" _published_output_hex)
if(NOT _published_output_hex STREQUAL _result_hex)
    message(FATAL_ERROR "published source value output failed byte verification")
endif()
_aros_source_value_recheck("${_binary_root}" "${_recipe}" "${_expected_recipe_hash}"
    "${_source_root}" "${_input}" "${_input_hash_before}"
    "${_sv_file}" "${_file_sha256}" "${_output}" "${_prefs_root}")
