cmake_minimum_required(VERSION 3.22)

foreach(key BINARY_ROOT SOURCE_ROOT SOURCE_FILE SOURCE_OBJECT INTERMEDIATE OUTPUT LIB_ROOT)
    if(NOT DEFINED ${key} OR "${${key}}" STREQUAL "" OR "${${key}}" MATCHES "[;\n\r]")
        message(FATAL_ERROR "SDK object staging requires one ${key}")
    endif()
    cmake_path(ABSOLUTE_PATH ${key} NORMALIZE OUTPUT_VARIABLE ${key})
endforeach()
if(IS_SYMLINK "${BINARY_ROOT}")
    message(FATAL_ERROR "SDK object staging: symlink build root refused")
endif()
if(NOT IS_DIRECTORY "${BINARY_ROOT}")
    message(FATAL_ERROR "SDK object staging: build root is missing")
endif()
find_program(regular_file_test NAMES test PATHS /usr/bin /bin NO_DEFAULT_PATH NO_CACHE REQUIRED)

cmake_path(IS_PREFIX SOURCE_ROOT "${SOURCE_FILE}" NORMALIZE source_inside)
if(NOT source_inside OR SOURCE_FILE STREQUAL SOURCE_ROOT OR IS_SYMLINK "${SOURCE_ROOT}")
    message(FATAL_ERROR "SDK object staging: source path escapes its source root")
endif()
set(cursor "${SOURCE_FILE}")
while(NOT cursor STREQUAL SOURCE_ROOT)
    if(IS_SYMLINK "${cursor}")
        message(FATAL_ERROR "SDK object staging: symlink source path refused: ${cursor}")
    endif()
    cmake_path(GET cursor PARENT_PATH parent)
    if(parent STREQUAL cursor)
        message(FATAL_ERROR "SDK object staging: invalid source boundary")
    endif()
    set(cursor "${parent}")
endwhile()
execute_process(COMMAND "${regular_file_test}" -f "${SOURCE_FILE}" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "SDK object staging: source is not a regular file")
endif()

function(check_path path regular)
    cmake_path(IS_PREFIX BINARY_ROOT "${path}" NORMALIZE inside)
    if(NOT inside OR path STREQUAL BINARY_ROOT)
        message(FATAL_ERROR "SDK object staging: path escapes its build root")
    endif()
    set(cursor "${path}")
    while(NOT cursor STREQUAL BINARY_ROOT)
        if(IS_SYMLINK "${cursor}")
            message(FATAL_ERROR "SDK object staging: symlink path refused: ${cursor}")
        endif()
        if(NOT cursor STREQUAL path AND EXISTS "${cursor}" AND NOT IS_DIRECTORY "${cursor}")
            message(FATAL_ERROR "SDK object staging: parent is not a directory")
        endif()
        cmake_path(GET cursor PARENT_PATH parent)
        if(parent STREQUAL cursor)
            message(FATAL_ERROR "SDK object staging: invalid path boundary")
        endif()
        set(cursor "${parent}")
    endwhile()
    if(EXISTS "${path}" OR regular)
        execute_process(COMMAND "${regular_file_test}" -f "${path}" RESULT_VARIABLE result)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "SDK object staging: object is not a regular file")
        endif()
    endif()
endfunction()

cmake_path(GET OUTPUT PARENT_PATH output_parent)
cmake_path(GET OUTPUT FILENAME output_name)
cmake_path(GET INTERMEDIATE FILENAME intermediate_name)
set(gen_root "${BINARY_ROOT}/gen")
cmake_path(IS_PREFIX gen_root "${INTERMEDIATE}" NORMALIZE gen_inside)
cmake_path(IS_PREFIX BINARY_ROOT "${LIB_ROOT}" NORMALIZE lib_inside)
if(NOT lib_inside OR LIB_ROOT STREQUAL BINARY_ROOT OR NOT gen_inside OR
   NOT output_parent STREQUAL LIB_ROOT OR NOT output_name STREQUAL intermediate_name OR
   NOT output_name MATCHES "^[A-Za-z0-9][A-Za-z0-9_.+-]*\\.o$" OR
   INTERMEDIATE STREQUAL OUTPUT OR SOURCE_OBJECT STREQUAL INTERMEDIATE OR SOURCE_OBJECT STREQUAL OUTPUT)
    message(FATAL_ERROR "SDK object staging: invalid compile/intermediate/Developer roles")
endif()
if(VERIFY_ONLY)
    check_path("${SOURCE_OBJECT}" FALSE)
    check_path("${INTERMEDIATE}" FALSE)
    check_path("${OUTPUT}" FALSE)
    return()
endif()
check_path("${SOURCE_OBJECT}" TRUE)
check_path("${INTERMEDIATE}" FALSE)
check_path("${OUTPUT}" FALSE)
file(SHA256 "${SOURCE_OBJECT}" source_sha)
cmake_path(GET INTERMEDIATE PARENT_PATH intermediate_parent)
file(MAKE_DIRECTORY "${intermediate_parent}" "${LIB_ROOT}")
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef suffix)
set(intermediate_temp "${INTERMEDIATE}.stage-${suffix}")
set(output_temp "${OUTPUT}.stage-${suffix}")
foreach(temp "${intermediate_temp}" "${output_temp}")
    check_path("${temp}" FALSE)
    if(EXISTS "${temp}")
        message(FATAL_ERROR "SDK object staging: private staging collision")
    endif()
    configure_file("${SOURCE_OBJECT}" "${temp}" COPYONLY)
    check_path("${temp}" TRUE)
    file(SHA256 "${temp}" staged_sha)
    if(NOT staged_sha STREQUAL source_sha)
        message(FATAL_ERROR "SDK object staging: copied bytes differ from compilation output")
    endif()
endforeach()
check_path("${SOURCE_OBJECT}" TRUE)
file(SHA256 "${SOURCE_OBJECT}" source_after)
if(NOT source_after STREQUAL source_sha)
    message(FATAL_ERROR "SDK object staging: compilation output changed during staging")
endif()
check_path("${INTERMEDIATE}" FALSE)
check_path("${OUTPUT}" FALSE)
file(RENAME "${intermediate_temp}" "${INTERMEDIATE}" RESULT result)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "SDK object staging: intermediate publication failed: ${result}")
endif()
file(RENAME "${output_temp}" "${OUTPUT}" RESULT result)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "SDK object staging: Developer publication failed: ${result}")
endif()
