include_guard(GLOBAL)

# MetaMake evaluates a requested root, not every declared product. Distinct
# providers may therefore intentionally publish the same loader-visible name.
# Register before graph attachment and resolve only after the default closure
# is known. Never let declaration order select a runtime provider.
function(aros_register_runtime_module_output target directory name)
    if(NOT TARGET "${target}")
        message(FATAL_ERROR "Runtime output owner is not a target: ${target}")
    endif()
    set(_path "${directory}/${name}")
    cmake_path(NORMAL_PATH _path)
    string(TOLOWER "${_path}" _identity)
    string(SHA256 _key "${_identity}")
    get_property(_owners GLOBAL PROPERTY "AROS_RUNTIME_OUTPUT_OWNERS_${_key}")
    if("${target}" IN_LIST _owners)
        message(FATAL_ERROR "Runtime output owner registered twice: ${target}")
    endif()
    set_property(GLOBAL APPEND PROPERTY "AROS_RUNTIME_OUTPUT_OWNERS_${_key}" "${target}")
    set_property(GLOBAL APPEND PROPERTY AROS_RUNTIME_OUTPUT_KEYS "${_key}")
    set_property(TARGET "${target}" PROPERTY AROS_CANONICAL_RUNTIME_DIRECTORY "${directory}")
    set_property(TARGET "${target}" PROPERTY AROS_CANONICAL_RUNTIME_NAME "${name}")
    get_property(_scheduled GLOBAL PROPERTY AROS_RUNTIME_OUTPUT_FINALIZER_SCHEDULED)
    if(NOT _scheduled)
        set_property(GLOBAL PROPERTY AROS_RUNTIME_OUTPUT_FINALIZER_SCHEDULED TRUE)
        cmake_language(DEFER DIRECTORY "${CMAKE_SOURCE_DIR}"
            CALL aros_finalize_runtime_module_outputs)
    endif()
endfunction()

function(aros_finalize_runtime_module_outputs)
    get_property(_keys GLOBAL PROPERTY AROS_RUNTIME_OUTPUT_KEYS)
    list(REMOVE_DUPLICATES _keys)
    list(SORT _keys)
    get_property(_root_known GLOBAL PROPERTY AROS_METAMAKE_DEFAULT_ROOT SET)
    get_property(_reachable GLOBAL PROPERTY AROS_METAMAKE_REACHABLE_TARGETS)
    foreach(_key IN LISTS _keys)
        get_property(_owners GLOBAL PROPERTY "AROS_RUNTIME_OUTPUT_OWNERS_${_key}")
        list(LENGTH _owners _owner_count)
        if(_owner_count LESS 2)
            continue()
        endif()
        list(SORT _owners)
        set(_active "")
        foreach(_owner IN LISTS _owners)
            if(NOT _root_known OR "${_owner}" IN_LIST _reachable)
                list(APPEND _active "${_owner}")
            endif()
        endforeach()
        list(LENGTH _active _active_count)
        if(_active_count GREATER 1)
            list(GET _owners 0 _first)
            get_property(_directory TARGET "${_first}" PROPERTY AROS_CANONICAL_RUNTIME_DIRECTORY)
            get_property(_name TARGET "${_first}" PROPERTY AROS_CANONICAL_RUNTIME_NAME)
            message(FATAL_ERROR
                "Conflicting runtime module output ${_directory}/${_name}: "
                "selected owners ${_active}")
        endif()
        # Unselected alternatives remain explicitly buildable, but can never
        # overwrite the selected module or create a second Ninja output rule.
        foreach(_owner IN LISTS _owners)
            if("${_owner}" IN_LIST _active)
                continue()
            endif()
            string(SHA256 _private_key "${_key}|${_owner}")
            set_target_properties("${_owner}" PROPERTIES
                RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/gen/manual-modules/${_private_key}")
            set_property(TARGET "${_owner}" PROPERTY AROS_PRIVATE_RUNTIME_ALTERNATIVE TRUE)
        endforeach()
    endforeach()
endfunction()
