cmake_minimum_required(VERSION 3.22)
include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/SdkFileCopies.cmake")

function(_aros_sdk_asset_require_unique_keywords)
    foreach(_keyword IN ITEMS NAME INPUT OUTPUT PRODUCER TEXT_HEX)
        set(_count 0)
        foreach(_index RANGE 0 ${ARGC})
            if("${ARGV${_index}}" STREQUAL "${_keyword}")
                math(EXPR _count "${_count} + 1")
            endif()
        endforeach()
        if(_count GREATER 1)
            message(FATAL_ERROR "SDK asset keyword ${_keyword} is repeated")
        endif()
    endforeach()
endfunction()

function(_aros_sdk_program_actual_output program result)
    get_target_property(_directory "${program}" RUNTIME_OUTPUT_DIRECTORY)
    get_target_property(_name "${program}" OUTPUT_NAME)
    string(TOUPPER "${CMAKE_BUILD_TYPE}" _configuration)
    if(_configuration)
        get_target_property(_configured_directory "${program}" "RUNTIME_OUTPUT_DIRECTORY_${_configuration}")
        get_target_property(_configured_name "${program}" "OUTPUT_NAME_${_configuration}")
        if(NOT _configured_directory STREQUAL "_configured_directory-NOTFOUND")
            set(_directory "${_configured_directory}")
        endif()
        if(NOT _configured_name STREQUAL "_configured_name-NOTFOUND")
            set(_name "${_configured_name}")
        endif()
    endif()
    get_target_property(_runtime_name "${program}" RUNTIME_OUTPUT_NAME)
    if(NOT _runtime_name STREQUAL "_runtime_name-NOTFOUND")
        set(_name "${_runtime_name}")
    endif()
    set(_postfix "")
    if(_configuration)
        get_target_property(_configured_runtime_name "${program}" "RUNTIME_OUTPUT_NAME_${_configuration}")
        get_target_property(_configured_postfix "${program}" "${_configuration}_POSTFIX")
        if(NOT _configured_runtime_name STREQUAL "_configured_runtime_name-NOTFOUND")
            set(_name "${_configured_runtime_name}")
        endif()
        if(NOT _configured_postfix STREQUAL "_configured_postfix-NOTFOUND")
            set(_postfix "${_configured_postfix}")
        endif()
    endif()
    get_target_property(_prefix "${program}" PREFIX)
    get_target_property(_suffix "${program}" SUFFIX)
    if(_prefix STREQUAL "_prefix-NOTFOUND")
        set(_prefix "")
    endif()
    if(_suffix STREQUAL "_suffix-NOTFOUND")
        set(_suffix "${CMAKE_EXECUTABLE_SUFFIX}")
    endif()
    if(NOT _directory OR NOT _name OR CMAKE_CONFIGURATION_TYPES)
        message(FATAL_ERROR "${program}: SDK registration requires one exact executable output")
    endif()
    _aros_sdk_copy_normalize_path("target output" "${_directory}/${_prefix}${_name}${_postfix}${_suffix}" _actual)
    set(${result} "${_actual}" PARENT_SCOPE)
endfunction()

function(_aros_verify_registered_sdk_program_files)
    get_property(_programs GLOBAL PROPERTY AROS_SDK_REGISTERED_PROGRAMS)
    foreach(_program IN LISTS _programs)
        get_target_property(_expected "${_program}" AROS_SDK_REGISTERED_PROGRAM_OUTPUT)
        _aros_sdk_program_actual_output("${_program}" _actual)
        if(NOT _actual STREQUAL _expected OR CMAKE_CONFIGURATION_TYPES)
            message(FATAL_ERROR "${_program}: registered SDK program output changed after registration")
        endif()
    endforeach()
endfunction()

# Programs and SDK-copy products register their exact file paths. An alias
# cannot adopt an arbitrary utility target or a pre-existing file as evidence.
function(_aros_register_sdk_asset_output owner output)
    if(NOT TARGET "${owner}")
        message(FATAL_ERROR "SDK asset producer target is absent: ${owner}")
    endif()
    _aros_sdk_copy_normalize_path("registered SDK output" "${output}" _output)
    string(TOLOWER "${_output}" _identity)
    string(SHA256 _key "${_identity}")
    get_property(_previous GLOBAL PROPERTY "AROS_SDK_ASSET_PRODUCER_${_key}")
    if(_previous AND NOT _previous STREQUAL owner)
        message(FATAL_ERROR "SDK asset ${_output} has competing producers ${_previous} and ${owner}")
    endif()
    set_property(GLOBAL PROPERTY "AROS_SDK_ASSET_PRODUCER_${_key}" "${owner}")
    set_property(TARGET "${owner}" APPEND PROPERTY AROS_SDK_ASSET_OUTPUTS "${_output}")
endfunction()

function(aros_register_sdk_program_file)
    _aros_sdk_asset_require_unique_keywords(${ARGV})
    cmake_parse_arguments(PARSE_ARGV 0 SP "" "NAME;OUTPUT" "")
    if(SP_UNPARSED_ARGUMENTS OR SP_KEYWORDS_MISSING_VALUES OR NOT SP_NAME OR NOT SP_OUTPUT OR
       NOT TARGET "${SP_NAME}")
        message(FATAL_ERROR "SDK program registration requires an existing NAME and OUTPUT")
    endif()
    get_target_property(_type "${SP_NAME}" TYPE)
    if(NOT _type STREQUAL "EXECUTABLE")
        message(FATAL_ERROR "${SP_NAME}: SDK registration requires one exact executable output")
    endif()
    _aros_sdk_copy_normalize_path("SDK bin root" "${AROS_DEVELOPER_BIN_DIR}" _bin)
    _aros_sdk_copy_normalize_path("program output" "${SP_OUTPUT}" _output)
    _aros_sdk_program_actual_output("${SP_NAME}" _actual)
    cmake_path(GET _output PARENT_PATH _parent)
    if(NOT _parent STREQUAL _bin OR NOT _actual STREQUAL _output)
        message(FATAL_ERROR "${SP_NAME}: declared SDK output differs from its executable output")
    endif()
    string(TOLOWER "${_output}" _identity)
    string(SHA256 _key "${_identity}")
    get_property(_previous GLOBAL PROPERTY "AROS_SDK_FILE_COPY_OUTPUT_${_key}")
    if(_previous)
        message(FATAL_ERROR "${SP_NAME}: SDK output ${_output} is already owned by ${_previous}")
    endif()
    set_property(GLOBAL PROPERTY "AROS_SDK_FILE_COPY_OUTPUT_${_key}" "${SP_NAME}")
    _aros_register_sdk_asset_output("${SP_NAME}" "${_output}")
    set_property(TARGET "${SP_NAME}" PROPERTY AROS_SDK_REGISTERED_PROGRAM_OUTPUT "${_output}")
    set_property(GLOBAL APPEND PROPERTY AROS_SDK_REGISTERED_PROGRAMS "${SP_NAME}")
    get_property(_scheduled GLOBAL PROPERTY AROS_SDK_PROGRAM_OUTPUT_GUARD_SCHEDULED)
    if(NOT _scheduled)
        cmake_language(DEFER DIRECTORY "${CMAKE_SOURCE_DIR}" CALL _aros_verify_registered_sdk_program_files)
        set_property(GLOBAL PROPERTY AROS_SDK_PROGRAM_OUTPUT_GUARD_SCHEDULED TRUE)
    endif()
endfunction()

function(aros_sdk_asset_rule)
    _aros_sdk_asset_require_unique_keywords(${ARGV})
    cmake_parse_arguments(PARSE_ARGV 0 SA "" "NAME;INPUT;OUTPUT;PRODUCER;TEXT_HEX" "")
    if(SA_UNPARSED_ARGUMENTS OR SA_KEYWORDS_MISSING_VALUES OR
       NOT SA_NAME MATCHES "^[A-Za-z0-9][A-Za-z0-9_.+-]*$" OR NOT SA_OUTPUT)
        message(FATAL_ERROR "SDK asset rule requires one safe NAME and OUTPUT")
    endif()
    if(SA_INPUT AND SA_PRODUCER AND NOT DEFINED SA_TEXT_HEX)
        set(_kind copy)
        set(_root "${AROS_DEVELOPER_BIN_DIR}")
    elseif(DEFINED SA_TEXT_HEX AND NOT SA_INPUT AND NOT SA_PRODUCER)
        set(_kind text)
        set(_root "${AROS_DEVELOPER_MAN1_DIR}")
        string(LENGTH "${SA_TEXT_HEX}" _length)
        math(EXPR _odd "${_length} % 2")
        if(NOT SA_TEXT_HEX MATCHES "^[0-9a-f]+$" OR _length GREATER 1024 OR _odd)
            message(FATAL_ERROR "${SA_NAME}: SDK text must be bounded hexadecimal bytes")
        endif()
    else()
        message(FATAL_ERROR "${SA_NAME}: SDK asset requires INPUT/PRODUCER or TEXT_HEX, never both")
    endif()
    _aros_sdk_copy_find_test(_test_program)
    _aros_sdk_copy_normalize_path("binary root" "${CMAKE_BINARY_DIR}" _binary)
    _aros_sdk_copy_normalize_path("asset root" "${_root}" _root)
    _aros_sdk_copy_normalize_path("SDK bin root" "${AROS_DEVELOPER_BIN_DIR}" _bin_root)
    _aros_sdk_copy_normalize_path("SDK man root" "${AROS_DEVELOPER_MAN1_DIR}" _man_root)
    cmake_path(IS_PREFIX _bin_root "${_man_root}" NORMALIZE _bin_contains_man)
    cmake_path(IS_PREFIX _man_root "${_bin_root}" NORMALIZE _man_contains_bin)
    if(_bin_contains_man OR _man_contains_bin)
        message(FATAL_ERROR "SDK bin and man roots overlap")
    endif()
    _aros_sdk_copy_normalize_path("asset output" "${SA_OUTPUT}" _output)
    _aros_sdk_copy_require_descendant("asset root" "${_root}" "${_binary}" FALSE)
    cmake_path(GET _output PARENT_PATH _parent)
    cmake_path(GET _output FILENAME _basename)
    if(NOT _parent STREQUAL _root OR NOT _basename MATCHES "^[A-Za-z0-9][A-Za-z0-9_.+-]*$")
        message(FATAL_ERROR "${SA_NAME}: asset output is not one direct file at its configured SDK root")
    endif()
    _aros_sdk_copy_check_components("asset output" "${_output}" "${_binary}")
    _aros_sdk_copy_check_physical_ancestor("asset output" "${_output}" "${_binary}")
    set(_input "")
    set(_dependencies "")
    if(_kind STREQUAL copy)
        _aros_sdk_copy_normalize_path("asset input" "${SA_INPUT}" _input)
        cmake_path(GET _input PARENT_PATH _input_parent)
        if(NOT _input_parent STREQUAL _root OR _input STREQUAL _output OR NOT TARGET "${SA_PRODUCER}")
            message(FATAL_ERROR "${SA_NAME}: alias input must be a distinct SDK bin file with a producer")
        endif()
        string(TOLOWER "${_input}" _input_identity)
        string(SHA256 _input_key "${_input_identity}")
        get_property(_producer GLOBAL PROPERTY "AROS_SDK_ASSET_PRODUCER_${_input_key}")
        get_property(_registered TARGET "${SA_PRODUCER}" PROPERTY AROS_SDK_ASSET_OUTPUTS)
        if(NOT _producer STREQUAL SA_PRODUCER OR NOT _input IN_LIST _registered OR SA_NAME STREQUAL SA_PRODUCER)
            message(FATAL_ERROR "${SA_NAME}: input has no exact registered distinct producer")
        endif()
        set(_dependencies "${_input}" "${SA_PRODUCER}")
    endif()
    string(TOLOWER "${_output}" _identity)
    string(SHA256 _key "${_identity}")
    get_property(_previous GLOBAL PROPERTY "AROS_SDK_FILE_COPY_OUTPUT_${_key}")
    if(_previous)
        message(FATAL_ERROR "${SA_NAME}: SDK output ${_output} is already owned by ${_previous}")
    endif()
    get_property(_aggregate GLOBAL PROPERTY "AROS_SDK_ASSET_AGGREGATE_${SA_NAME}")
    if(TARGET "${SA_NAME}" AND NOT _aggregate)
        message(FATAL_ERROR "${SA_NAME}: SDK aggregate is owned by another capability")
    endif()
    if(NOT TARGET "${SA_NAME}")
        add_custom_target("${SA_NAME}")
        set_property(GLOBAL PROPERTY "AROS_SDK_ASSET_AGGREGATE_${SA_NAME}" TRUE)
    endif()
    set_property(GLOBAL PROPERTY "AROS_SDK_FILE_COPY_OUTPUT_${_key}" "${SA_NAME}")
    set(_runner "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/RunSdkAssetRule.cmake")
    string(SHA256 _operation_hash "${SA_NAME}|${_kind}|${_input}|${_output}|${SA_TEXT_HEX}")
    set(_product "${SA_NAME}--asset-${_operation_hash}")
    add_custom_command(OUTPUT "${_output}"
        COMMAND "${CMAKE_COMMAND}" "-DBINARY_ROOT=${_binary}" "-DASSET_ROOT=${_root}"
            "-DKIND=${_kind}" "-DINPUT=${_input}" "-DOUTPUT=${_output}"
            "-DTEXT_HEX=${SA_TEXT_HEX}" -P "${_runner}"
        DEPENDS "${_runner}" ${_dependencies}
        COMMENT "Producing SDK asset ${_basename}" VERBATIM)
    add_custom_target("${_product}" DEPENDS "${_output}")
    add_dependencies("${SA_NAME}" "${_product}")
    if(_kind STREQUAL copy)
        add_dependencies("${_product}" "${SA_PRODUCER}")
    endif()
    _aros_register_sdk_asset_output("${SA_NAME}" "${_output}")
endfunction()
