cmake_minimum_required(VERSION 3.22)
include_guard(GLOBAL)

# Stage finite literal basenames below Developer/SDK/fd or at an exact
# configured Developer lib, bin or man/man1 root. Library inputs are local
# and hash-bound; fetched inputs retain their unique source producer.
# Files
# are described by a private JSON recipe; paths and source contents are never
# interpolated into shell commands.
function(aros_stage_sdk_files)
    set(_one_value_args NAME SOURCE DESTINATION FETCH)
    cmake_parse_arguments(PARSE_ARGV 0 SF "" "${_one_value_args}" "FILES")
    if(SF_UNPARSED_ARGUMENTS OR SF_KEYWORDS_MISSING_VALUES OR
       NOT SF_NAME OR NOT SF_SOURCE OR NOT SF_DESTINATION OR NOT SF_FILES)
        message(FATAL_ERROR
            "aros_stage_sdk_files requires NAME, SOURCE, DESTINATION, FILES, and optional FETCH")
    endif()
    if(NOT SF_NAME MATCHES "^[A-Za-z0-9][A-Za-z0-9_.+-]*$")
        message(FATAL_ERROR "SDK file-copy NAME must be a safe target name")
    endif()
    string(LENGTH "${SF_NAME}" _name_length)
    if(_name_length GREATER 128)
        message(FATAL_ERROR "SDK file-copy NAME exceeds 128 characters")
    endif()

    # PARSE_ARGV preserves the call's original argument boundaries. Reject a
    # semicolon embedded in a single FILES argument instead of treating it as
    # two basenames after CMake list expansion.
    math(EXPR _last_argument "${ARGC} - 1")
    set(_inside_files FALSE)
    set(_files_keyword_count 0)
    set(_name_keyword_count 0)
    set(_source_keyword_count 0)
    set(_destination_keyword_count 0)
    set(_fetch_keyword_count 0)
    foreach(_argument_index RANGE 0 ${_last_argument})
        set(_argument "${ARGV${_argument_index}}")
        if(_argument STREQUAL "FILES")
            math(EXPR _files_keyword_count "${_files_keyword_count} + 1")
            set(_inside_files TRUE)
        elseif(_argument STREQUAL "NAME")
            math(EXPR _name_keyword_count "${_name_keyword_count} + 1")
            set(_inside_files FALSE)
        elseif(_argument STREQUAL "SOURCE")
            math(EXPR _source_keyword_count "${_source_keyword_count} + 1")
            set(_inside_files FALSE)
        elseif(_argument STREQUAL "DESTINATION")
            math(EXPR _destination_keyword_count "${_destination_keyword_count} + 1")
            set(_inside_files FALSE)
        elseif(_argument STREQUAL "FETCH")
            math(EXPR _fetch_keyword_count "${_fetch_keyword_count} + 1")
            set(_inside_files FALSE)
        elseif(_inside_files)
            if(_argument MATCHES ";")
                message(FATAL_ERROR "SDK file-copy FILES arguments cannot contain semicolons")
            endif()
        endif()
    endforeach()
    if(NOT _files_keyword_count EQUAL 1 OR
       NOT _name_keyword_count EQUAL 1 OR
       NOT _source_keyword_count EQUAL 1 OR
       NOT _destination_keyword_count EQUAL 1 OR
       _fetch_keyword_count GREATER 1)
        message(FATAL_ERROR
            "SDK file-copy requires exactly one NAME, SOURCE, DESTINATION, FILES, and at most one FETCH")
    endif()

    _aros_sdk_copy_find_test(_test_program)
    _aros_sdk_copy_normalize_path("binary root" "${CMAKE_BINARY_DIR}" _binary_root)
    _aros_sdk_copy_normalize_path("source" "${SF_SOURCE}" _source_root)
    _aros_sdk_copy_normalize_path("destination" "${SF_DESTINATION}" _destination)
    set(_destination_kind "fd")
    if(DEFINED AROS_DEVELOPER_LIB_DIR AND NOT "${AROS_DEVELOPER_LIB_DIR}" STREQUAL "")
        _aros_sdk_copy_normalize_path("Developer library root" "${AROS_DEVELOPER_LIB_DIR}" _lib_root)
        if(_destination STREQUAL _lib_root)
            set(_destination_kind "lib")
        endif()
    endif()
    foreach(_kind IN ITEMS bin man1)
        if(_kind STREQUAL "bin")
            set(_root_variable AROS_DEVELOPER_BIN_DIR)
        else()
            set(_root_variable AROS_DEVELOPER_MAN1_DIR)
        endif()
        if(DEFINED ${_root_variable} AND NOT "${${_root_variable}}" STREQUAL "")
            _aros_sdk_copy_normalize_path("Developer ${_kind} root"
                "${${_root_variable}}" _candidate_root)
            if(_destination STREQUAL _candidate_root)
                if(NOT _destination_kind STREQUAL "fd")
                    message(FATAL_ERROR "configured Developer file-copy roots overlap")
                endif()
                set(_destination_kind "${_kind}")
                set(_exact_root "${_candidate_root}")
            endif()
        endif()
    endforeach()
    if(_destination_kind STREQUAL "lib")
        if(SF_FETCH)
            message(FATAL_ERROR "Developer library copies require local source inputs")
        endif()
        set(_fd_root "${_lib_root}")
    elseif(_destination_kind STREQUAL "bin" OR _destination_kind STREQUAL "man1")
        set(_fd_root "${_exact_root}")
    else()
        if(NOT DEFINED AROS_DEVELOPER_FD_DIR OR "${AROS_DEVELOPER_FD_DIR}" STREQUAL "")
            message(FATAL_ERROR "AROS_DEVELOPER_FD_DIR is not configured")
        endif()
        _aros_sdk_copy_normalize_path(
            "Developer/SDK/fd root" "${AROS_DEVELOPER_FD_DIR}" _fd_root)
    endif()
    _aros_sdk_copy_require_descendant("fd root" "${_fd_root}" "${_binary_root}" FALSE)
    _aros_sdk_copy_require_descendant("destination" "${_destination}" "${_fd_root}" TRUE)

    if(SF_FETCH)
        if(NOT SF_FETCH MATCHES "^[A-Za-z0-9][A-Za-z0-9_.+-]*$")
            message(FATAL_ERROR "${SF_NAME}: FETCH must name a safe build target")
        endif()
        if(NOT TARGET "${SF_FETCH}")
            message(FATAL_ERROR "${SF_NAME}: missing SDK file-copy fetch target ${SF_FETCH}")
        endif()
        get_property(_fetch_destination TARGET "${SF_FETCH}"
            PROPERTY AROS_FETCH_DESTINATION)
        get_property(_fetch_stamp TARGET "${SF_FETCH}"
            PROPERTY AROS_FETCH_COMPLETION_STAMP)
        if(NOT _fetch_destination OR NOT _fetch_stamp)
            message(FATAL_ERROR
                "${SF_NAME}: ${SF_FETCH} lacks fetch destination/completion-stamp properties")
        endif()
        _aros_sdk_copy_normalize_path(
            "fetch destination" "${_fetch_destination}" _fetch_destination)
        _aros_sdk_copy_normalize_path("fetch stamp" "${_fetch_stamp}" _fetch_stamp)
        set(_engine_stamp_root "${_binary_root}/CMakeFiles/aros-fetch")
        _aros_sdk_copy_require_descendant(
            "fetch destination" "${_fetch_destination}" "${_binary_root}" FALSE)
        # The completion stamp is CMake state, not payload. It lives either
        # inside the fetch destination or in the engine's own stamp directory
        # (aros_fetch_completion_stamp); anywhere else is refused.
        cmake_path(IS_PREFIX _fetch_destination "${_fetch_stamp}" NORMALIZE
            _stamp_in_destination)
        cmake_path(IS_PREFIX _engine_stamp_root "${_fetch_stamp}" NORMALIZE
            _stamp_in_engine_root)
        if(NOT (_stamp_in_destination OR _stamp_in_engine_root) OR
           "${_fetch_stamp}" STREQUAL "${_fetch_destination}" OR
           "${_fetch_stamp}" STREQUAL "${_engine_stamp_root}")
            message(FATAL_ERROR "SDK file-copy fetch stamp escapes its declared root")
        endif()
        _aros_sdk_copy_require_descendant(
            "fetched source" "${_source_root}" "${_fetch_destination}" TRUE)
        _aros_sdk_copy_check_components(
            "fetch destination" "${_fetch_destination}" "${_binary_root}")
        _aros_sdk_copy_check_physical_ancestor(
            "fetch destination" "${_fetch_destination}" "${_binary_root}")

        get_property(_registered_fetches GLOBAL PROPERTY AROS_FETCH_TARGETS)
        if(NOT _registered_fetches)
            message(FATAL_ERROR
                "${SF_NAME}: cannot prove unique ownership of fetch destination ${_fetch_destination}")
        endif()
        list(REMOVE_DUPLICATES _registered_fetches)
        set(_matching_fetches "")
        foreach(_fetch_candidate IN LISTS _registered_fetches)
            if(TARGET "${_fetch_candidate}")
                get_property(_candidate_destination TARGET "${_fetch_candidate}"
                    PROPERTY AROS_FETCH_DESTINATION)
                if(_candidate_destination)
                    # A fetch rule creates its destination from the build root,
                    # so a relative one (%fetch without destination=, as for
                    # pci.ids) names a directory below it, never an error.
                    if(NOT IS_ABSOLUTE "${_candidate_destination}")
                        cmake_path(ABSOLUTE_PATH _candidate_destination
                            BASE_DIRECTORY "${CMAKE_BINARY_DIR}" NORMALIZE)
                    endif()
                    _aros_sdk_copy_normalize_path(
                        "registered fetch destination" "${_candidate_destination}"
                        _candidate_destination)
                    if(_candidate_destination STREQUAL _fetch_destination)
                        list(APPEND _matching_fetches "${_fetch_candidate}")
                    endif()
                endif()
            endif()
        endforeach()
        list(LENGTH _matching_fetches _matching_fetch_count)
        if(NOT _matching_fetch_count EQUAL 1 OR
           NOT "${_matching_fetches}" STREQUAL "${SF_FETCH}")
            message(FATAL_ERROR
                "${SF_NAME}: fetch destination ${_fetch_destination} must have one registered target, ${SF_FETCH}")
        endif()
        set(_source_kind "fetched")
        set(_source_boundary "${_fetch_destination}")
    else()
        if(NOT DEFINED AROS_SOURCE_DIR OR "${AROS_SOURCE_DIR}" STREQUAL "")
            message(FATAL_ERROR "${SF_NAME}: AROS_SOURCE_DIR is not configured for local SDK files")
        endif()
        _aros_sdk_copy_normalize_path("AROS_SOURCE_DIR" "${AROS_SOURCE_DIR}" _source_boundary)
        _aros_sdk_copy_require_descendant(
            "local source" "${_source_root}" "${_source_boundary}" TRUE)
        set(_source_kind "local")
        set(_fetch_destination "")
        set(_fetch_stamp "")
    endif()

    cmake_path(IS_PREFIX _source_root "${_destination}" NORMALIZE _destination_below_source)
    cmake_path(IS_PREFIX _destination "${_source_root}" NORMALIZE _source_below_destination)
    if(_destination_below_source OR _source_below_destination)
        message(FATAL_ERROR "${SF_NAME}: SDK file-copy source and destination roots overlap")
    endif()

    list(LENGTH SF_FILES _file_count)
    if(_file_count LESS 1 OR _file_count GREATER 128)
        message(FATAL_ERROR "${SF_NAME}: FILES must contain 1 to 128 basenames")
    endif()
    set(_files "${SF_FILES}")
    set(_seen_names "")
    set(_outputs "")
    set(_inputs "")
    set(_recipe_json "[")
    set(_source_hashes_json "[")
    set(_separator "")
    foreach(_file IN LISTS _files)
        string(LENGTH "${_file}" _file_length)
        if(_file_length GREATER 255 OR
           NOT _file MATCHES "^[A-Za-z0-9][A-Za-z0-9_.+-]*$")
            message(FATAL_ERROR "${SF_NAME}: unsafe SDK file basename '${_file}'")
        endif()
        string(TOLOWER "${_file}" _folded_name)
        if(_folded_name IN_LIST _seen_names)
            message(FATAL_ERROR "${SF_NAME}: duplicate SDK file basename '${_file}'")
        endif()
        list(APPEND _seen_names "${_folded_name}")

        _aros_sdk_copy_normalize_path(
            "source file" "${_source_root}/${_file}" _input)
        _aros_sdk_copy_normalize_path(
            "output file" "${_destination}/${_file}" _output)
        _aros_sdk_copy_require_descendant("source file" "${_input}" "${_source_root}" FALSE)
        _aros_sdk_copy_require_descendant("output file" "${_output}" "${_fd_root}" FALSE)
        if(_input STREQUAL _output)
            message(FATAL_ERROR "${SF_NAME}: SDK copy source and destination are identical")
        endif()

        _aros_sdk_copy_check_components("source file" "${_input}" "${_source_boundary}")
        _aros_sdk_copy_check_components("output file" "${_output}" "${_binary_root}")
        if(_source_kind STREQUAL "local")
            _aros_sdk_copy_check_physical_ancestor(
                "source file" "${_input}" "${_source_boundary}")
        else()
            _aros_sdk_copy_check_physical_ancestor(
                "source file" "${_input}" "${_binary_root}")
        endif()
        _aros_sdk_copy_check_physical_ancestor(
            "output file" "${_output}" "${_binary_root}")
        _aros_sdk_copy_path_exists("${_input}" _input_exists)
        if(_source_kind STREQUAL "local" AND NOT _input_exists)
            message(FATAL_ERROR "${SF_NAME}: local SDK file is missing: ${_input}")
        endif()
        if(_input_exists)
            _aros_sdk_copy_require_regular_file("source file" "${_input}" "${_test_program}")
            file(SIZE "${_input}" _input_size)
            if(_input_size GREATER 16777216)
                message(FATAL_ERROR "${SF_NAME}: SDK source file exceeds 16 MiB: ${_input}")
            endif()
        endif()
        _aros_sdk_copy_path_exists("${_output}" _output_exists)
        if(_output_exists)
            _aros_sdk_copy_require_regular_file("existing output" "${_output}" "${_test_program}")
        endif()

        string(TOLOWER "${_output}" _output_identity)
        string(SHA256 _output_key "${_output_identity}")
        get_property(_previous_owner GLOBAL PROPERTY "AROS_SDK_FILE_COPY_OUTPUT_${_output_key}")
        if(_previous_owner)
            message(FATAL_ERROR
                "${SF_NAME}: SDK output ${_output} is already owned by ${_previous_owner}")
        endif()
        set_property(GLOBAL PROPERTY "AROS_SDK_FILE_COPY_OUTPUT_${_output_key}" "${SF_NAME}")
        list(APPEND _inputs "${_input}")
        list(APPEND _outputs "${_output}")
        if(_destination_kind STREQUAL "lib")
            file(SHA256 "${_input}" _source_hash)
            string(APPEND _source_hashes_json "${_separator}\"${_source_hash}\"")
            set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_input}")
        endif()
        string(APPEND _recipe_json "${_separator}\"${_file}\"")
        set(_separator ",")
    endforeach()
    string(APPEND _recipe_json "]")
    if(_destination_kind STREQUAL "lib")
        string(APPEND _source_hashes_json "]")
        set(_recipe_json "{\"files\":${_recipe_json},\"sha256\":${_source_hashes_json}}")
    endif()

    string(SHA256 _aggregate_key "${SF_NAME}")
    get_property(_aggregate_owner GLOBAL PROPERTY "AROS_SDK_FILE_COPY_AGGREGATE_${_aggregate_key}")
    if(TARGET "${SF_NAME}" AND NOT "${_aggregate_owner}" STREQUAL "${SF_NAME}")
        message(FATAL_ERROR "${SF_NAME}: SDK file-copy aggregate target is already declared")
    elseif(NOT TARGET "${SF_NAME}")
        add_custom_target("${SF_NAME}")
        set_property(GLOBAL PROPERTY "AROS_SDK_FILE_COPY_AGGREGATE_${_aggregate_key}" "${SF_NAME}")
    endif()

    set(_recipe_root "${_binary_root}/.aros-sdk-file-copies")
    _aros_sdk_copy_check_components("private recipe root" "${_recipe_root}" "${_binary_root}")
    file(MAKE_DIRECTORY "${_recipe_root}")
    _aros_sdk_copy_check_components("private recipe root" "${_recipe_root}" "${_binary_root}")
    string(SHA256 _batch_hash "${_destination}|${_recipe_json}")
    set(_recipe "${_recipe_root}/${_batch_hash}.json")
    set(_depfile "${_recipe_root}/${_batch_hash}.d")
    _aros_sdk_copy_check_components("private recipe" "${_recipe}" "${_binary_root}")
    _aros_sdk_copy_check_components("private depfile" "${_depfile}" "${_binary_root}")
    _aros_sdk_copy_path_exists("${_recipe}" _recipe_exists)
    if(_recipe_exists)
        _aros_sdk_copy_require_regular_file("private recipe" "${_recipe}" "${_test_program}")
    endif()
    _aros_sdk_copy_path_exists("${_depfile}" _depfile_exists)
    if(_depfile_exists)
        _aros_sdk_copy_require_regular_file("private depfile" "${_depfile}" "${_test_program}")
    endif()
    set(_recipe_content "")
    if(_recipe_exists)
        file(READ "${_recipe}" _recipe_content)
    endif()
    if(NOT _recipe_exists OR NOT _recipe_content STREQUAL _recipe_json)
        file(WRITE "${_recipe}" "${_recipe_json}")
    endif()
    file(SHA256 "${_recipe}" _recipe_sha256)

    set(_runner "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/RunSdkFileCopies.cmake")
    string(SHA256 _product_hash "${_outputs}")
    string(SUBSTRING "${_product_hash}" 0 16 _product_suffix)
    set(_product_target "${SF_NAME}--sdk-files-${_product_suffix}")
    if(TARGET "${_product_target}")
        message(FATAL_ERROR "${SF_NAME}: duplicate SDK copy product target")
    endif()

    set(_command
        "${CMAKE_COMMAND}"
        "-DSOURCE_ROOT=${_source_root}"
        "-DSOURCE_BOUNDARY=${_source_boundary}"
        "-DSOURCE_KIND=${_source_kind}"
        "-DDESTINATION=${_destination}"
        "-DDESTINATION_KIND=${_destination_kind}"
        "-DFD_ROOT=${_fd_root}"
        "-DBINARY_ROOT=${_binary_root}"
        "-DFETCH_DESTINATION=${_fetch_destination}"
        "-DRECIPE=${_recipe}"
        "-DRECIPE_SHA256=${_recipe_sha256}"
        "-DDEPFILE=${_depfile}")
    list(APPEND _command -P "${_runner}")
    set(_dependencies "${_recipe}" "${_runner}")
    if(_fetch_stamp)
        list(APPEND _dependencies "${_fetch_stamp}")
    endif()
    if(_source_kind STREQUAL "local")
        list(APPEND _dependencies ${_inputs})
    else()
        foreach(_input IN LISTS _inputs)
            _aros_sdk_copy_path_exists("${_input}" _input_exists)
            if(_input_exists)
                list(APPEND _dependencies "${_input}")
            endif()
        endforeach()
    endif()
    add_custom_command(
        OUTPUT ${_outputs} "${_depfile}"
        COMMAND ${_command}
        DEPENDS ${_dependencies}
        DEPFILE "${_depfile}"
        COMMENT "Staging SDK files ${_destination}"
        VERBATIM)
    add_custom_target("${_product_target}" DEPENDS ${_outputs})
    if(SF_FETCH)
        add_dependencies("${_product_target}" "${SF_FETCH}")
        add_dependencies("${SF_NAME}" "${SF_FETCH}")
    endif()
    add_dependencies("${SF_NAME}" "${_product_target}")
    if(COMMAND _aros_register_sdk_asset_output)
        foreach(_output IN LISTS _outputs)
            _aros_register_sdk_asset_output("${SF_NAME}" "${_output}")
        endforeach()
    endif()
endfunction()

function(_aros_sdk_copy_normalize_path label raw out)
    if(NOT IS_ABSOLUTE "${raw}" OR "${raw}" MATCHES "[;\"\r\n$`|&*?\[\]]")
        message(FATAL_ERROR "SDK file-copy ${label} is not a safe absolute path")
    endif()
    string(LENGTH "${raw}" _length)
    if(_length GREATER 4096)
        message(FATAL_ERROR "SDK file-copy ${label} exceeds the path length limit")
    endif()
    string(REPLACE "/" ";" _components "${raw}")
    foreach(_component IN LISTS _components)
        if(_component STREQUAL "." OR _component STREQUAL "..")
            message(FATAL_ERROR "SDK file-copy ${label} contains a dot path component")
        endif()
    endforeach()
    set(_normalized "${raw}")
    cmake_path(NORMAL_PATH _normalized OUTPUT_VARIABLE _normalized)
    if(_normalized STREQUAL "/")
        message(FATAL_ERROR "SDK file-copy ${label} cannot be the filesystem root")
    endif()
    set(${out} "${_normalized}" PARENT_SCOPE)
endfunction()

function(_aros_sdk_copy_require_descendant label path root allow_equal)
    cmake_path(IS_PREFIX root "${path}" NORMALIZE _inside)
    if(NOT _inside OR (NOT allow_equal AND "${path}" STREQUAL "${root}"))
        message(FATAL_ERROR "SDK file-copy ${label} escapes its declared root")
    endif()
endfunction()

function(_aros_sdk_copy_check_components label path root)
    file(RELATIVE_PATH _relative "${root}" "${path}")
    if(_relative MATCHES "(^|/)\\.\\.(/|$)" OR _relative MATCHES "^\\.\\.")
        message(FATAL_ERROR "SDK file-copy ${label} escapes its checked root")
    endif()
    if(_relative STREQUAL "." OR _relative STREQUAL "")
        return()
    endif()
    string(REPLACE "/" ";" _components "${_relative}")
    set(_probe "${root}")
    list(LENGTH _components _component_count)
    set(_index 0)
    foreach(_component IN LISTS _components)
        if(_component STREQUAL "")
            continue()
        endif()
        math(EXPR _index "${_index} + 1")
        set(_probe "${_probe}/${_component}")
        if(IS_SYMLINK "${_probe}")
            message(FATAL_ERROR "SDK file-copy ${label} crosses a symlink: ${_probe}")
        endif()
        if(EXISTS "${_probe}" AND _index LESS _component_count AND
           NOT IS_DIRECTORY "${_probe}")
            message(FATAL_ERROR "SDK file-copy ${label} parent is not a directory: ${_probe}")
        endif()
    endforeach()
endfunction()

function(_aros_sdk_copy_check_physical_ancestor label path root)
    if(NOT EXISTS "${root}" OR NOT IS_DIRECTORY "${root}")
        message(FATAL_ERROR "SDK file-copy ${label} boundary is missing: ${root}")
    endif()
    file(REAL_PATH "${root}" _root_real)
    set(_existing "${path}")
    while(NOT EXISTS "${_existing}")
        if(IS_SYMLINK "${_existing}")
            message(FATAL_ERROR "SDK file-copy ${label} crosses a dangling symlink")
        endif()
        cmake_path(GET _existing PARENT_PATH _parent)
        if(_parent STREQUAL _existing)
            message(FATAL_ERROR "SDK file-copy ${label} has no safe existing ancestor")
        endif()
        set(_existing "${_parent}")
    endwhile()
    file(REAL_PATH "${_existing}" _existing_real)
    cmake_path(IS_PREFIX _root_real "${_existing_real}" NORMALIZE _inside)
    if(NOT _inside)
        message(FATAL_ERROR "SDK file-copy ${label} physically escapes its declared root")
    endif()
endfunction()

function(_aros_sdk_copy_path_exists path out)
    execute_process(
        COMMAND "${_test_program}" -e "${path}"
        RESULT_VARIABLE _result OUTPUT_QUIET ERROR_QUIET TIMEOUT 10)
    if(_result STREQUAL "0")
        set(${out} TRUE PARENT_SCOPE)
    else()
        set(${out} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(_aros_sdk_copy_require_regular_file label path test_program)
    execute_process(
        COMMAND "${test_program}" -f "${path}"
        RESULT_VARIABLE _result OUTPUT_QUIET ERROR_QUIET TIMEOUT 10)
    if(NOT _result STREQUAL "0")
        message(FATAL_ERROR "SDK file-copy ${label} is not a regular file: ${path}")
    endif()
endfunction()

function(_aros_sdk_copy_find_test out)
    find_program(_test_program NAMES test PATHS /usr/bin /bin
        NO_DEFAULT_PATH NO_CACHE REQUIRED)
    set(${out} "${_test_program}" PARENT_SCOPE)
endfunction()
