include_guard(GLOBAL)
include(CMakeParseArguments)
include("${CMAKE_CURRENT_LIST_DIR}/GenmoduleHeaderRules.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/SfdcHostTool.cmake")

function(_aros_sfd_regular root relative digest)
    _aros_genmodule_header_validate_relative("${relative}" "SFD input" FALSE)
    if(NOT IS_DIRECTORY "${root}" OR IS_SYMLINK "${root}")
        message(FATAL_ERROR "SFD source root must be a regular directory")
    endif()
    string(REPLACE "/" ";" _parts "${relative}")
    set(_cursor "${root}")
    foreach(_part IN LISTS _parts)
        set(_cursor "${_cursor}/${_part}")
        if(IS_SYMLINK "${_cursor}")
            message(FATAL_ERROR "SFD input crosses symlink: ${relative}")
        endif()
    endforeach()
    if(NOT EXISTS "${_cursor}" OR IS_DIRECTORY "${_cursor}")
        message(FATAL_ERROR "SFD input is not a regular file: ${relative}")
    endif()
    if(NOT "${digest}" STREQUAL "")
        string(LENGTH "${digest}" _length)
        if(NOT _length EQUAL 64 OR NOT digest MATCHES "^[0-9a-f]+$")
            message(FATAL_ERROR "SFD input digest is malformed")
        endif()
        file(SHA256 "${_cursor}" _actual)
        if(NOT _actual STREQUAL digest)
            message(FATAL_ERROR "SFD input changed: ${relative}; rerun translation")
        endif()
    endif()
endfunction()

# Derive the host-tool closure from the original source Make rule. The private
# manifest adapts that proven rule to the existing sealed builder; it is not a
# file added to the AROS source tree. No Make command or source shell is run.
function(_aros_sfd_prepare_tool)
    get_property(_proof GLOBAL PROPERTY AROS_NATIVE_SFDC_INPUT_PROOF)
    if(_proof)
        set(SFD_TOOL_PROOF "${_proof}" PARENT_SCOPE)
        get_property(_hash GLOBAL PROPERTY AROS_NATIVE_SFDC_OUTPUT_SHA256)
        set(SFD_TOOL_SHA256 "${_hash}" PARENT_SCOPE)
        set(AROS_HOST_SFDC "${CMAKE_BINARY_DIR}/hosttools/sfdc" PARENT_SCOPE)
        return()
    endif()
    foreach(_relative tools/sfdc/Makefile tools/sfdc/configure.in)
        _aros_sfd_regular("${AROS_SOURCE_DIR}" "${_relative}" "")
    endforeach()
    # file(STRINGS) splits non-UTF-8 copyright comments into extra records.
    # Read bytes and discard comments before inspecting this closed recipe.
    file(READ "${AROS_SOURCE_DIR}/tools/sfdc/Makefile" _make_bytes)
    string(REGEX REPLACE "#[^\n]*" "" _make_bytes "${_make_bytes}")
    if(_make_bytes MATCHES ";")
        message(FATAL_ERROR "SFD host Make recipe contains an unsupported separator")
    endif()
    string(REPLACE "\n" ";" _lines "${_make_bytes}")
    set(_recipe "")
    foreach(_line IN LISTS _lines)
        string(STRIP "${_line}" _line)
        if(_line STREQUAL "" OR _line MATCHES "^#")
            continue()
        endif()
        string(REGEX REPLACE "[ \t]+" " " _line "${_line}")
        string(APPEND _recipe "${_line}\n")
    endforeach()
    set(_expected [=[include $(TOP)/config/make.cfg
MAIN = main.pl
CLASSES = $(wildcard [A-Z]*.pl)
PODS = SFDCompile.pod
all : $(SFDC)
$(SFDC) : $(MAIN) $(CLASSES) $(PODS)
@cat $^ | $(SED) "s/SFDC_VERSION/$(VERSION)/g" | $(SED) "s/SFDC_DATE/$(DATE)/g" >$@
@$(CHMOD) a+x $@
clean:
@$(RM) -f $(SFDC)
]=])
    if(NOT _recipe STREQUAL _expected)
        message(FATAL_ERROR "SFD host Make recipe is outside the closed concatenation capability")
    endif()
    file(STRINGS "${AROS_SOURCE_DIR}/tools/sfdc/configure.in" _versions REGEX "^VERSION=")
    file(STRINGS "${AROS_SOURCE_DIR}/tools/sfdc/configure.in" _dates REGEX "^DATE=")
    if(NOT _versions STREQUAL "VERSION=1.3" OR NOT _dates STREQUAL "DATE=2004-11-12")
        message(FATAL_ERROR "SFD host identity differs from the audited Perl compiler")
    endif()
    # CMake's Darwin glob case-folding does not reproduce Make's character
    # range on a case-sensitive volume. Filter the actual preserved basenames.
    file(GLOB _classes CONFIGURE_DEPENDS RELATIVE "${AROS_SOURCE_DIR}/tools/sfdc"
        "${AROS_SOURCE_DIR}/tools/sfdc/*")
    list(FILTER _classes INCLUDE REGEX "^[A-Z].*[.]pl$")
    list(SORT _classes)
    list(LENGTH _classes _count)
    if(_count LESS 1 OR _count GREATER 128)
        message(FATAL_ERROR "SFD host class inventory is empty or oversized")
    endif()
    set(_inputs main.pl ${_classes} SFDCompile.pod)
    set(_proof "")
    set(_manifest "")
    set(_content "#!/usr/bin/perl -w\n")
    set(_owned "${CMAKE_BINARY_DIR}/.aros-native-sfdc-source")
    _aros_genmodule_header_check_output("${_owned}/tools/sfdc/sfdc-host.inputs"
        "${CMAKE_BINARY_DIR}" "host-sfdc")
    file(MAKE_DIRECTORY "${_owned}/tools/sfdc")
    foreach(_relative IN LISTS _inputs)
        _aros_sfd_regular("${AROS_SOURCE_DIR}" "tools/sfdc/${_relative}" "")
        file(SHA256 "${AROS_SOURCE_DIR}/tools/sfdc/${_relative}" _hash)
        list(APPEND _proof "tools/sfdc/${_relative}|${_hash}")
        string(APPEND _manifest "${_relative}\n")
        _aros_genmodule_header_check_output("${_owned}/tools/sfdc/${_relative}"
            "${CMAKE_BINARY_DIR}" "host-sfdc")
        file(COPY_FILE "${AROS_SOURCE_DIR}/tools/sfdc/${_relative}"
            "${_owned}/tools/sfdc/${_relative}" ONLY_IF_DIFFERENT)
        file(READ "${AROS_SOURCE_DIR}/tools/sfdc/${_relative}" _part)
        if(_relative STREQUAL "main.pl")
            string(REGEX REPLACE "^#![^\n]*\n" "" _part "${_part}")
        endif()
        string(REPLACE "SFDC_VERSION" "1.3" _part "${_part}")
        string(REPLACE "SFDC_DATE" "2004-11-12" _part "${_part}")
        string(APPEND _content "${_part}")
    endforeach()
    foreach(_relative tools/sfdc/Makefile tools/sfdc/configure.in)
        file(SHA256 "${AROS_SOURCE_DIR}/${_relative}" _hash)
        list(APPEND _proof "${_relative}|${_hash}")
    endforeach()
    file(WRITE "${_owned}/tools/sfdc/sfdc-host.inputs" "${_manifest}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
        "${AROS_SOURCE_DIR}/tools/sfdc/Makefile"
        "${AROS_SOURCE_DIR}/tools/sfdc/configure.in")
    string(SHA256 _output_hash "${_content}")
    if(NOT TARGET host-sfdc)
        set(AROS_SFDC_SOURCE_ROOT "${_owned}")
        aros_build_host_sfdc(PERL /usr/bin/perl)
    else()
        get_property(_registered_hash TARGET host-sfdc PROPERTY AROS_SFDC_OUTPUT_SHA256)
        if(NOT _registered_hash STREQUAL _output_hash)
            message(FATAL_ERROR "SFD host endpoint is not the same registered compiler")
        endif()
    endif()
    set_property(GLOBAL PROPERTY AROS_NATIVE_SFDC_INPUT_PROOF "${_proof}")
    set_property(GLOBAL PROPERTY AROS_NATIVE_SFDC_OUTPUT_SHA256 "${_output_hash}")
    set(SFD_TOOL_PROOF "${_proof}" PARENT_SCOPE)
    set(SFD_TOOL_SHA256 "${_output_hash}" PARENT_SCOPE)
    set(AROS_HOST_SFDC "${CMAKE_BINARY_DIR}/hosttools/sfdc" PARENT_SCOPE)
endfunction()

function(aros_generate_sfd_headers)
    foreach(_keyword NAME FILE FILE_SHA256 JOBS)
        set(_count 0)
        math(EXPR _last "${ARGC} - 1")
        foreach(_index RANGE 0 ${_last})
            if("${ARGV${_index}}" STREQUAL _keyword)
                math(EXPR _count "${_count} + 1")
            endif()
        endforeach()
        if(NOT _count EQUAL 1)
            message(FATAL_ERROR "SFD headers require exactly one ${_keyword}")
        endif()
    endforeach()
    cmake_parse_arguments(PARSE_ARGV 0 SF "" "NAME;FILE;FILE_SHA256" "JOBS")
    if(SF_UNPARSED_ARGUMENTS OR SF_KEYWORDS_MISSING_VALUES OR
       NOT SF_NAME MATCHES "^[A-Za-z0-9][A-Za-z0-9_.+-]*$" OR
       NOT SF_FILE OR NOT SF_FILE_SHA256 OR NOT SF_JOBS OR TARGET "${SF_NAME}")
        message(FATAL_ERROR "SFD headers require unique NAME, FILE, FILE_SHA256 and JOBS")
    endif()
    foreach(_value "${AROS_SOURCE_DIR}" "${CMAKE_BINARY_DIR}" "${AROS_SDK_INCLUDE_DIR}")
        if(NOT IS_ABSOLUTE "${_value}")
            message(FATAL_ERROR "SFD roots must be absolute")
        endif()
        _aros_sfdc_validate_contract_value("SFD root" "${_value}")
    endforeach()
    _aros_sfd_regular("${AROS_SOURCE_DIR}" "${SF_FILE}" "${SF_FILE_SHA256}")
    _aros_genmodule_header_check_output_root("${AROS_SDK_INCLUDE_DIR}"
        "${CMAKE_BINARY_DIR}" "${SF_NAME}")
    _aros_sfd_prepare_tool()
    set(_outputs "")
    set(_inputs "${AROS_SOURCE_DIR}/${SF_FILE}")
    set(_contract "set(SFD_SOURCE_ROOT [==[${AROS_SOURCE_DIR}]==])\nset(SFD_BINARY_ROOT [==[${CMAKE_BINARY_DIR}]==])\nset(SFD_SDK_ROOT [==[${AROS_SDK_INCLUDE_DIR}]==])\nset(SFD_TOOL [==[${AROS_HOST_SFDC}]==])\nset(SFD_TOOL_SHA256 ${SFD_TOOL_SHA256})\nset(SFD_FILE [==[${SF_FILE}]==])\nset(SFD_FILE_SHA256 ${SF_FILE_SHA256})\nset(SFD_JOBS)\nset(SFD_TOOL_PROOF)\n")
    list(LENGTH SF_JOBS _count)
    if(_count GREATER 128)
        message(FATAL_ERROR "SFD header inventory exceeds 128 outputs")
    endif()
    foreach(_job IN LISTS SF_JOBS)
        string(REPLACE "|" ";" _fields "${_job}")
        list(LENGTH _fields _length)
        if(NOT _length EQUAL 5)
            message(FATAL_ERROR "SFD header job must have five fields")
        endif()
        list(GET _fields 0 _mode)
        list(GET _fields 1 _target)
        list(GET _fields 2 _input)
        list(GET _fields 3 _hash)
        list(GET _fields 4 _output)
        if(NOT _mode MATCHES "^(clib|macros|proto)$" OR
           NOT _target MATCHES "^[A-Za-z0-9][A-Za-z0-9_.+-]*$")
            message(FATAL_ERROR "SFD header mode/target is outside its closed capability")
        endif()
        _aros_sfd_regular("${AROS_SOURCE_DIR}" "${_input}" "${_hash}")
        _aros_genmodule_header_validate_relative("${_output}" "SFD output" FALSE)
        if(NOT _input MATCHES "[.]sfd$" OR NOT _output MATCHES "[.]h$")
            message(FATAL_ERROR "SFD input/output must be .sfd/.h")
        endif()
        set(_absolute "${AROS_SDK_INCLUDE_DIR}/${_output}")
        _aros_genmodule_header_check_output("${_absolute}" "${AROS_SDK_INCLUDE_DIR}" "${SF_NAME}")
        string(SHA256 _key "${_absolute}")
        get_property(_owner GLOBAL PROPERTY "AROS_SFD_OUTPUT_${_key}")
        if(_owner OR _absolute IN_LIST _outputs)
            message(FATAL_ERROR "SFD output has duplicate ownership: ${_output}")
        endif()
        set_property(GLOBAL PROPERTY "AROS_SFD_OUTPUT_${_key}" "${SF_NAME}")
        list(APPEND _outputs "${_absolute}")
        list(APPEND _inputs "${AROS_SOURCE_DIR}/${_input}")
        string(APPEND _contract "list(APPEND SFD_JOBS [==[${_job}]==])\n")
    endforeach()
    foreach(_proof IN LISTS SFD_TOOL_PROOF)
        string(APPEND _contract "list(APPEND SFD_TOOL_PROOF [==[${_proof}]==])\n")
    endforeach()
    set(_recipe "${CMAKE_CURRENT_BINARY_DIR}/.aros-sfd-${SF_NAME}.cmake")
    _aros_genmodule_header_check_output("${_recipe}" "${CMAKE_BINARY_DIR}" "${SF_NAME}")
    file(GENERATE OUTPUT "${_recipe}" CONTENT "${_contract}")
    string(SHA256 _recipe_hash "${_contract}")
    set(_runner "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/RunSfdHeaders.cmake")
    add_custom_target("${SF_NAME}-sfd-input-check"
        COMMAND "${CMAKE_COMMAND}" "-DRECIPE=${_recipe}" "-DRECIPE_SHA256=${_recipe_hash}"
            -DCHECK_ONLY=ON -P "${_runner}" VERBATIM)
    # A changed source closure must rebuild its private tool before its identity
    # guard runs. Old-mtime tool tampering still fails: it is not a source change
    # and therefore does not cause the host tool's output rule to run.
    add_dependencies("${SF_NAME}-sfd-input-check" host-sfdc)
    add_custom_command(OUTPUT ${_outputs}
        COMMAND "${CMAKE_COMMAND}" "-DRECIPE=${_recipe}" "-DRECIPE_SHA256=${_recipe_hash}"
            -P "${_runner}"
        DEPENDS "${_recipe}" "${_runner}" ${_inputs} "${AROS_HOST_SFDC}"
            "${SF_NAME}-sfd-input-check" host-sfdc VERBATIM)
    add_custom_target("${SF_NAME}" DEPENDS ${_outputs})
    add_dependencies("${SF_NAME}" "${SF_NAME}-sfd-input-check" host-sfdc)
endfunction()
