include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/LiteralObjects.cmake")

# A source-proven archive rule, with a finite ordered list of registered object
# producers. There is deliberately no filesystem glob or implicit AR flag.
# The caller must have proved the source's target GNU AR/RANLIB command roles.
function(aros_source_archive)
    cmake_parse_arguments(PARSE_ARGV 0 A "" "NAME;OUTPUT;AR_FLAGS" "OBJECTS")
    if(A_UNPARSED_ARGUMENTS OR A_KEYWORDS_MISSING_VALUES OR
       NOT A_NAME MATCHES "^[A-Za-z0-9][A-Za-z0-9_-]*$" OR
       TARGET "${A_NAME}" OR TARGET "${A_NAME}-archive" OR
       NOT A_OBJECTS OR NOT A_AR_FLAGS STREQUAL "cr")
        message(FATAL_ERROR "Source archive: invalid owner, ordered objects or explicit AR flags")
    endif()
    foreach(keyword NAME OUTPUT AR_FLAGS OBJECTS)
        set(count 0)
        foreach(argument IN LISTS ARGN)
            if(argument STREQUAL keyword)
                math(EXPR count "${count}+1")
            endif()
        endforeach()
        if(count GREATER 1)
            message(FATAL_ERROR "Source archive: duplicate keyword ${keyword}")
        endif()
    endforeach()
    if(NOT AROS_NATIVE_BUILD_CONTRACT_VALIDATED OR NOT AROS_TOOLCHAIN STREQUAL "gnu")
        message(FATAL_ERROR "Source archive: validated native GNU contract required")
    endif()
    if(CMAKE_CONFIGURATION_TYPES)
        message(FATAL_ERROR "Source archive: multi-configuration output is not supported")
    endif()
    foreach(key AROS_BUILD_DIR AROS_DEVELOPER_LIB_DIR CMAKE_AR CMAKE_RANLIB)
        if(NOT DEFINED ${key} OR NOT IS_ABSOLUTE "${${key}}")
            message(FATAL_ERROR "Source archive: absolute ${key} required")
        endif()
        _aros_literal_reject_control_text("${${key}}" "archive role")
    endforeach()
    cmake_path(ABSOLUTE_PATH AROS_BUILD_DIR NORMALIZE OUTPUT_VARIABLE build_root)
    cmake_path(ABSOLUTE_PATH AROS_DEVELOPER_LIB_DIR NORMALIZE OUTPUT_VARIABLE lib_root)
    _aros_literal_check_root("${build_root}" "build root")
    _aros_literal_check_path_chain("${lib_root}" "${build_root}" "Developer lib root")
    _aros_literal_reject_control_text("${A_OUTPUT}" "archive output")
    if(NOT IS_ABSOLUTE "${A_OUTPUT}")
        message(FATAL_ERROR "Source archive: output must be absolute")
    endif()
    cmake_path(ABSOLUTE_PATH A_OUTPUT NORMALIZE OUTPUT_VARIABLE output)
    cmake_path(GET output PARENT_PATH output_directory)
    cmake_path(GET output FILENAME output_name)
    if(NOT output_directory STREQUAL lib_root OR
       NOT output_name MATCHES "^lib[A-Za-z0-9][A-Za-z0-9_.+-]*\\.a$")
        message(FATAL_ERROR "Source archive: output must be one named archive in Developer lib")
    endif()
    _aros_literal_check_path_chain("${output}" "${build_root}" "archive output")
    _aros_literal_check_optional_regular("${output}" "archive output")
    foreach(tool CMAKE_AR CMAKE_RANLIB)
        _aros_literal_check_absolute_chain("${${tool}}" "archive tool")
        _aros_literal_assert_regular("${${tool}}" "archive tool" TRUE)
    endforeach()
    set(owners)
    set(objects)
    set(member_names)
    foreach(raw IN LISTS A_OBJECTS)
        _aros_literal_reject_control_text("${raw}" "archive member")
        if(NOT IS_ABSOLUTE "${raw}")
            message(FATAL_ERROR "Source archive: members must be exact absolute producer outputs")
        endif()
        cmake_path(ABSOLUTE_PATH raw NORMALIZE OUTPUT_VARIABLE object)
        _aros_literal_check_path_chain("${object}" "${build_root}/gen" "archive member")
        cmake_path(GET object FILENAME member_name)
        string(TOLOWER "${member_name}" folded_member)
        if(NOT member_name MATCHES "^[A-Za-z0-9][A-Za-z0-9_.+-]*\\.o$" OR
           folded_member IN_LIST member_names)
            message(FATAL_ERROR "Source archive: unsafe or duplicate archive member basename")
        endif()
        string(TOLOWER "${object}" folded_object)
        string(SHA256 key "${folded_object}")
        get_property(owner GLOBAL PROPERTY "AROS_LITERAL_OBJECT_${key}")
        if(NOT owner OR NOT TARGET "${owner}")
            message(FATAL_ERROR "Source archive: member has no registered literal object producer")
        endif()
        get_target_property(compile_targets "${owner}" AROS_LITERAL_OBJECT_COMPILE_TARGETS)
        set(exact FALSE)
        foreach(target IN LISTS compile_targets)
            get_target_property(owned "${target}" AROS_LITERAL_OBJECT_OUTPUT)
            if(owned STREQUAL object)
                set(exact TRUE)
            endif()
        endforeach()
        if(NOT exact)
            message(FATAL_ERROR "Source archive: member is not the producer's exact output")
        endif()
        list(APPEND objects "${object}")
        list(APPEND owners "${owner}")
        list(APPEND member_names "${folded_member}")
    endforeach()
    string(TOLOWER "${output}" folded_output)
    string(SHA256 key "${folded_output}")
    get_property(prior GLOBAL PROPERTY "AROS_LINKLIB_ARCHIVE_OWNER_${key}")
    get_property(prior_file GLOBAL PROPERTY "AROS_SDK_FILE_COPY_OUTPUT_${key}")
    if(prior OR prior_file)
        message(FATAL_ERROR "Source archive: archive already owned by ${prior}")
    endif()
    set_property(GLOBAL PROPERTY "AROS_LINKLIB_ARCHIVE_OWNER_${key}" "${A_NAME}")
    set_property(GLOBAL PROPERTY "AROS_SDK_FILE_COPY_OUTPUT_${key}" "${A_NAME}")
    set(command_root "${CMAKE_CURRENT_BINARY_DIR}")
    set(command_file "${command_root}/CMakeFiles/aros-source-archive-${key}.cmake")
    _aros_literal_check_path_chain("${command_file}" "${command_root}" "command file")
    _aros_literal_check_optional_regular("${command_file}" "command file")
    set(contents "# Sealed source archive command.\n")
    foreach(pair OUTPUT BUILD_ROOT AR RANLIB AR_FLAGS)
        if(pair STREQUAL "OUTPUT")
            set(value "${output}")
        elseif(pair STREQUAL "BUILD_ROOT")
            set(value "${build_root}")
        elseif(pair STREQUAL "AR")
            set(value "${CMAKE_AR}")
        elseif(pair STREQUAL "RANLIB")
            set(value "${CMAKE_RANLIB}")
        else()
            set(value "${A_AR_FLAGS}")
        endif()
        _aros_literal_append_set(contents "${pair}" "${value}")
    endforeach()
    string(APPEND contents "set(OBJECTS\n")
    foreach(object IN LISTS objects)
        string(APPEND contents "    [==[${object}]==]\n")
    endforeach()
    string(APPEND contents ")\n")
    file(MAKE_DIRECTORY "${command_root}/CMakeFiles")
    if(EXISTS "${command_file}")
        file(READ "${command_file}" old_contents)
    endif()
    if(NOT old_contents STREQUAL contents)
        file(WRITE "${command_file}" "${contents}")
    endif()
    file(SHA256 "${command_file}" command_sha256)
    set(runner "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/RunSourceArchive.cmake")
    add_custom_target("${A_NAME}-check"
        COMMAND "${CMAKE_COMMAND}" "-DCOMMAND_FILE=${command_file}"
            "-DCOMMAND_ROOT=${command_root}" "-DCOMMAND_SHA256=${command_sha256}"
            -DVERIFY_ONLY=ON -P "${runner}" VERBATIM)
    add_custom_command(OUTPUT "${output}"
        COMMAND "${CMAKE_COMMAND}" "-DCOMMAND_FILE=${command_file}"
            "-DCOMMAND_ROOT=${command_root}" "-DCOMMAND_SHA256=${command_sha256}"
            -DVERIFY_ONLY=OFF -P "${runner}"
        DEPENDS ${objects} "${CMAKE_AR}" "${CMAKE_RANLIB}" "${runner}" "${command_file}"
        VERBATIM)
    add_custom_target("${A_NAME}" DEPENDS "${output}")
    list(REMOVE_DUPLICATES owners)
    add_dependencies("${A_NAME}" "${A_NAME}-check" ${owners})
    set_property(TARGET "${A_NAME}" PROPERTY AROS_SOURCE_ARCHIVE_OUTPUT "${output}")
    # The workflow is a utility target. Consumers link a typed imported
    # archive at its exact declared output, never the utility target itself.
    add_library("${A_NAME}-archive" STATIC IMPORTED GLOBAL)
    set_target_properties("${A_NAME}-archive" PROPERTIES
        IMPORTED_LOCATION "${output}"
        AROS_SOURCE_ARCHIVE_WORKFLOW "${A_NAME}")
    add_dependencies("${A_NAME}-archive" "${A_NAME}")
endfunction()
