cmake_minimum_required(VERSION 3.22)
include_guard(GLOBAL)

# Register a source-proven, literal-only sed value extraction.  The private
# recipe contains data only; the runner never includes it as CMake code.
function(aros_extract_source_value)
    set(_required NAME INPUT OUTPUT MARKER_HEX FILE FILE_SHA256)
    set(_seen)
    set(_index 0)
    while(_index LESS ARGC)
        set(_argument_variable "ARGV${_index}")
        set(_keyword "${${_argument_variable}}")
        if(NOT _keyword IN_LIST _required)
            message(FATAL_ERROR "aros_extract_source_value: unexpected argument '${_keyword}'")
        endif()
        if(_keyword IN_LIST _seen)
            message(FATAL_ERROR "aros_extract_source_value: duplicate ${_keyword}")
        endif()
        math(EXPR _value_index "${_index} + 1")
        if(_value_index GREATER_EQUAL ARGC)
            message(FATAL_ERROR "aros_extract_source_value: ${_keyword} has no value")
        endif()
        set(_value_variable "ARGV${_value_index}")
        set("_sv_${_keyword}" "${${_value_variable}}")
        list(APPEND _seen "${_keyword}")
        math(EXPR _index "${_index} + 2")
    endwhile()
    foreach(_keyword IN LISTS _required)
        if(NOT _keyword IN_LIST _seen OR "${_sv_${_keyword}}" STREQUAL "")
            message(FATAL_ERROR "aros_extract_source_value requires ${_keyword}")
        endif()
    endforeach()

    if(NOT _sv_NAME MATCHES "^[A-Za-z0-9][A-Za-z0-9_.+-]*$" OR TARGET "${_sv_NAME}")
        message(FATAL_ERROR "source value NAME must be a unique safe target name")
    endif()

    _aros_source_value_validate_sha256("FILE_SHA256" "${_sv_FILE_SHA256}" _expected_file_hash)
    _aros_source_value_validate_marker_hex("${_sv_MARKER_HEX}" _marker_hex)

    if(NOT DEFINED AROS_SOURCE_DIR OR "${AROS_SOURCE_DIR}" STREQUAL "")
        message(FATAL_ERROR "${_sv_NAME}: AROS_SOURCE_DIR is not configured")
    endif()
    _aros_source_value_canonical_root("source root" "${AROS_SOURCE_DIR}" _source_root)
    _aros_source_value_canonical_root("binary root" "${CMAKE_BINARY_DIR}" _binary_root)

    _aros_source_value_validate_absolute_path("input" "${_sv_INPUT}" _input)
    _aros_source_value_require_descendant("input" "${_input}" "${_source_root}")
    _aros_source_value_check_components("input" "${_input}" "${_source_root}")
    _aros_source_value_require_regular_file("input" "${_input}")
    file(REAL_PATH "${_input}" _input_real)
    if(NOT _input_real STREQUAL _input)
        message(FATAL_ERROR "${_sv_NAME}: input is not a canonical source path")
    endif()
    file(SIZE "${_input}" _input_size)
    if(_input_size GREATER 33554432)
        message(FATAL_ERROR "${_sv_NAME}: input exceeds 32 MiB")
    endif()

    _aros_source_value_validate_relative_path("declaring FILE" "${_sv_FILE}" _file_relative)
    set(_declaring_file "${_source_root}/${_file_relative}")
    _aros_source_value_check_components("declaring FILE" "${_declaring_file}" "${_source_root}")
    _aros_source_value_require_regular_file("declaring FILE" "${_declaring_file}")
    file(REAL_PATH "${_declaring_file}" _declaring_file_real)
    if(NOT _declaring_file_real STREQUAL _declaring_file)
        message(FATAL_ERROR "${_sv_NAME}: declaring FILE is not a canonical source path")
    endif()
    file(SHA256 "${_declaring_file}" _actual_file_hash)
    if(NOT _actual_file_hash STREQUAL _expected_file_hash)
        message(FATAL_ERROR "${_sv_NAME}: declaring FILE SHA256 does not match FILE_SHA256")
    endif()

    set(_prefs_root "${_binary_root}/SYS/Prefs")
    _aros_source_value_validate_absolute_path("output" "${_sv_OUTPUT}" _output)
    _aros_source_value_require_descendant("output" "${_output}" "${_prefs_root}")
    _aros_source_value_check_components("output" "${_output}" "${_binary_root}")
    _aros_source_value_path_exists("${_prefs_root}" _prefs_root_exists)
    if(_prefs_root_exists AND NOT IS_DIRECTORY "${_prefs_root}")
        message(FATAL_ERROR "${_sv_NAME}: canonical AROS_PREFS root is not a directory")
    endif()
    file(MAKE_DIRECTORY "${_prefs_root}")
    _aros_source_value_check_components("AROS_PREFS root" "${_prefs_root}" "${_binary_root}")
    _aros_source_value_check_physical_inside("output" "${_output}" "${_prefs_root}")
    _aros_source_value_check_existing_output("output" "${_output}")

    string(SHA256 _output_key "${_output}")
    get_property(_previous_owner GLOBAL PROPERTY "AROS_SOURCE_VALUE_OUTPUT_${_output_key}")
    if(_previous_owner)
        message(FATAL_ERROR
            "${_sv_NAME}: output ${_output} is already owned by ${_previous_owner}")
    endif()

    set(_private_root "${_binary_root}/.aros-source-value-rules")
    _aros_source_value_check_components("private recipe root" "${_private_root}" "${_binary_root}")
    _aros_source_value_path_exists("${_private_root}" _private_root_exists)
    if(_private_root_exists AND NOT IS_DIRECTORY "${_private_root}")
        message(FATAL_ERROR "${_sv_NAME}: private recipe root is not a directory")
    endif()
    file(MAKE_DIRECTORY "${_private_root}")
    _aros_source_value_check_components("private recipe root" "${_private_root}" "${_binary_root}")
    set(_recipe "${_private_root}/${_output_key}.json")

    set(_recipe_json "{}")
    _aros_source_value_json_set_string("${_recipe_json}" version "1" _recipe_json)
    _aros_source_value_json_set_string("${_recipe_json}" binary_root "${_binary_root}" _recipe_json)
    _aros_source_value_json_set_string("${_recipe_json}" source_root "${_source_root}" _recipe_json)
    _aros_source_value_json_set_string("${_recipe_json}" input "${_input}" _recipe_json)
    _aros_source_value_json_set_string("${_recipe_json}" output "${_output}" _recipe_json)
    _aros_source_value_json_set_string("${_recipe_json}" file "${_file_relative}" _recipe_json)
    _aros_source_value_json_set_string("${_recipe_json}" file_sha256 "${_expected_file_hash}" _recipe_json)
    _aros_source_value_json_set_string("${_recipe_json}" marker_hex "${_marker_hex}" _recipe_json)
    string(LENGTH "${_recipe_json}" _recipe_size)
    if(_recipe_size GREATER 16384)
        message(FATAL_ERROR "${_sv_NAME}: private recipe exceeds 16 KiB")
    endif()
    string(SHA256 _recipe_hash "${_recipe_json}")
    _aros_source_value_check_components("private recipe" "${_recipe}" "${_binary_root}")
    _aros_source_value_path_exists("${_recipe}" _recipe_exists)
    if(_recipe_exists)
        _aros_source_value_require_regular_file("private recipe" "${_recipe}")
    endif()
    string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef _recipe_nonce)
    set(_recipe_temporary "${_recipe}.tmp-${_recipe_nonce}")
    _aros_source_value_check_components("temporary private recipe" "${_recipe_temporary}" "${_binary_root}")
    _aros_source_value_path_exists("${_recipe_temporary}" _recipe_temporary_exists)
    if(_recipe_temporary_exists OR IS_SYMLINK "${_recipe_temporary}")
        message(FATAL_ERROR "${_sv_NAME}: private recipe temporary already exists")
    endif()
    file(WRITE "${_recipe_temporary}" "${_recipe_json}")
    _aros_source_value_require_regular_file("temporary private recipe" "${_recipe_temporary}")
    file(RENAME "${_recipe_temporary}" "${_recipe}" RESULT _recipe_rename_result)
    if(NOT _recipe_rename_result STREQUAL "0")
        file(REMOVE "${_recipe_temporary}")
        message(FATAL_ERROR "${_sv_NAME}: cannot atomically publish private recipe: ${_recipe_rename_result}")
    endif()

    set(_runner "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/RunSourceValueRule.cmake")
    if(NOT EXISTS "${_runner}" OR IS_DIRECTORY "${_runner}" OR IS_SYMLINK "${_runner}")
        message(FATAL_ERROR "${_sv_NAME}: source-value runner is missing or not a regular file")
    endif()
    add_custom_target("${_sv_NAME}"
        BYPRODUCTS "${_output}"
        COMMAND "${CMAKE_COMMAND}"
            "-DBINARY_ROOT=${_binary_root}"
            "-DRECIPE=${_recipe}"
            "-DRECIPE_SHA256=${_recipe_hash}"
            -P "${_runner}"
        VERBATIM)
    set_property(GLOBAL PROPERTY "AROS_SOURCE_VALUE_OUTPUT_${_output_key}" "${_sv_NAME}")
endfunction()

function(_aros_source_value_json_set_string json key value out)
    # Public arguments are validated to exclude quote, backslash and control
    # bytes, so this JSON string encoding needs no lossy CMake escape path.
    string(JSON _result SET "${json}" "${key}" "\"${value}\"")
    set(${out} "${_result}" PARENT_SCOPE)
endfunction()

function(_aros_source_value_validate_sha256 label value out)
    string(LENGTH "${value}" _length)
    if(NOT _length EQUAL 64 OR NOT value MATCHES "^[A-Fa-f0-9]+$")
        message(FATAL_ERROR "source value ${label} must be 64 hexadecimal digits")
    endif()
    string(TOLOWER "${value}" _normalized)
    set(${out} "${_normalized}" PARENT_SCOPE)
endfunction()

function(_aros_source_value_validate_marker_hex value out)
    string(LENGTH "${value}" _length)
    math(EXPR _odd_length "${_length} % 2")
    if(_length LESS 2 OR _length GREATER 256 OR _odd_length OR
       NOT value MATCHES "^[A-Fa-f0-9]+$")
        message(FATAL_ERROR "source value MARKER_HEX must encode 1–128 ASCII bytes")
    endif()
    string(TOLOWER "${value}" _hex)
    set(_forbidden_bytes 0 10 13 34 36 38 39 40 41 42 43 46 47 59 60 62 63 91 92 93 94 123 124 125)
    set(_offset 0)
    while(_offset LESS _length)
        string(SUBSTRING "${_hex}" ${_offset} 2 _byte_hex)
        math(EXPR _byte "0x${_byte_hex}")
        if(_byte GREATER 127 OR _byte IN_LIST _forbidden_bytes)
            message(FATAL_ERROR "source value MARKER_HEX contains unsafe BRE/shell bytes")
        endif()
        math(EXPR _offset "${_offset} + 2")
    endwhile()
    set(${out} "${_hex}" PARENT_SCOPE)
endfunction()

function(_aros_source_value_validate_absolute_path label raw out)
    if(NOT IS_ABSOLUTE "${raw}" OR
       "${raw}" MATCHES "[;\"\\$`|&<>\r\n]")
        message(FATAL_ERROR "source value ${label} is not a safe absolute path")
    endif()
    string(LENGTH "${raw}" _length)
    if(_length GREATER 4096)
        message(FATAL_ERROR "source value ${label} exceeds the path length limit")
    endif()
    string(REPLACE "/" ";" _components "${raw}")
    foreach(_component IN LISTS _components)
        if(_component STREQUAL "." OR _component STREQUAL "..")
            message(FATAL_ERROR "source value ${label} contains a dot path component")
        endif()
    endforeach()
    set(_normalized "${raw}")
    cmake_path(NORMAL_PATH _normalized OUTPUT_VARIABLE _normalized)
    if(NOT _normalized STREQUAL raw OR _normalized STREQUAL "/")
        message(FATAL_ERROR "source value ${label} is not a canonical absolute path")
    endif()
    set(${out} "${_normalized}" PARENT_SCOPE)
endfunction()

function(_aros_source_value_canonical_root label raw out)
    _aros_source_value_validate_absolute_path("${label}" "${raw}" _root)
    if(IS_SYMLINK "${_root}" OR NOT IS_DIRECTORY "${_root}")
        message(FATAL_ERROR "source value ${label} is missing, not a directory, or symlinked")
    endif()
    file(REAL_PATH "${_root}" _real_root)
    if(NOT _real_root STREQUAL _root)
        message(FATAL_ERROR "source value ${label} is not canonical")
    endif()
    set(${out} "${_root}" PARENT_SCOPE)
endfunction()

function(_aros_source_value_validate_relative_path label raw out)
    if(IS_ABSOLUTE "${raw}" OR "${raw}" STREQUAL "" OR
       NOT "${raw}" MATCHES "^[A-Za-z0-9_+./-]+$")
        message(FATAL_ERROR "source value ${label} is not a safe relative path")
    endif()
    string(REPLACE "/" ";" _components "${raw}")
    foreach(_component IN LISTS _components)
        if(_component STREQUAL "" OR _component STREQUAL "." OR _component STREQUAL "..")
            message(FATAL_ERROR "source value ${label} contains an unsafe path component")
        endif()
    endforeach()
    set(${out} "${raw}" PARENT_SCOPE)
endfunction()

function(_aros_source_value_require_descendant label path root)
    cmake_path(IS_PREFIX root "${path}" NORMALIZE _inside)
    if(NOT _inside OR "${path}" STREQUAL "${root}")
        message(FATAL_ERROR "source value ${label} escapes its declared root")
    endif()
endfunction()

function(_aros_source_value_check_components label path root)
    if(IS_SYMLINK "${root}")
        message(FATAL_ERROR "source value ${label} crosses a symlinked root")
    endif()
    file(RELATIVE_PATH _relative "${root}" "${path}")
    if(_relative STREQUAL "." OR _relative STREQUAL "")
        return()
    endif()
    string(REPLACE "/" ";" _components "${_relative}")
    foreach(_component IN LISTS _components)
        if(_component STREQUAL "..")
            message(FATAL_ERROR "source value ${label} escapes its checked root")
        endif()
    endforeach()
    set(_probe "${root}")
    list(LENGTH _components _count)
    set(_index 0)
    foreach(_component IN LISTS _components)
        if(_component STREQUAL "")
            continue()
        endif()
        math(EXPR _index "${_index} + 1")
        set(_probe "${_probe}/${_component}")
        if(IS_SYMLINK "${_probe}")
            message(FATAL_ERROR "source value ${label} crosses a symlink: ${_probe}")
        endif()
        if(EXISTS "${_probe}" AND _index LESS _count AND NOT IS_DIRECTORY "${_probe}")
            message(FATAL_ERROR "source value ${label} parent is not a directory")
        endif()
    endforeach()
endfunction()

function(_aros_source_value_check_physical_inside label path root)
    _aros_source_value_require_descendant("${label}" "${path}" "${root}")
    set(_existing "${path}")
    while(NOT EXISTS "${_existing}")
        if(IS_SYMLINK "${_existing}")
            message(FATAL_ERROR "source value ${label} crosses a dangling symlink")
        endif()
        cmake_path(GET _existing PARENT_PATH _parent)
        if(_parent STREQUAL _existing)
            message(FATAL_ERROR "source value ${label} has no safe existing ancestor")
        endif()
        set(_existing "${_parent}")
    endwhile()
    file(REAL_PATH "${root}" _root_real)
    file(REAL_PATH "${_existing}" _existing_real)
    cmake_path(IS_PREFIX _root_real "${_existing_real}" NORMALIZE _inside)
    if(NOT _inside)
        message(FATAL_ERROR "source value ${label} physically escapes its declared root")
    endif()
endfunction()

function(_aros_source_value_path_exists path out)
    execute_process(
        COMMAND "${_AROS_SOURCE_VALUE_TEST}" -e "${path}"
        RESULT_VARIABLE _result OUTPUT_QUIET ERROR_QUIET TIMEOUT 10)
    if(_result STREQUAL "0")
        set(${out} TRUE PARENT_SCOPE)
    else()
        set(${out} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(_aros_source_value_require_regular_file label path)
    execute_process(
        COMMAND "${_AROS_SOURCE_VALUE_TEST}" -f "${path}"
        RESULT_VARIABLE _result OUTPUT_QUIET ERROR_QUIET TIMEOUT 10)
    if(NOT _result STREQUAL "0" OR IS_SYMLINK "${path}")
        message(FATAL_ERROR "source value ${label} is not a regular non-symlink file")
    endif()
endfunction()

function(_aros_source_value_check_existing_output label path)
    _aros_source_value_path_exists("${path}" _exists)
    if(IS_SYMLINK "${path}")
        message(FATAL_ERROR "source value ${label} is a symlink")
    endif()
    if(_exists)
        _aros_source_value_require_regular_file("${label}" "${path}")
    endif()
endfunction()

function(_aros_source_value_validate_source_paths source_root input file file_sha)
    _aros_source_value_canonical_root("source root" "${source_root}" _root)
    _aros_source_value_validate_absolute_path("input" "${input}" _input)
    _aros_source_value_require_descendant("input" "${_input}" "${_root}")
    _aros_source_value_check_components("input" "${_input}" "${_root}")
    _aros_source_value_require_regular_file("input" "${_input}")
    file(REAL_PATH "${_input}" _input_real)
    if(NOT _input_real STREQUAL _input)
        message(FATAL_ERROR "source value input is not canonical")
    endif()
    file(SIZE "${_input}" _input_size)
    if(_input_size GREATER 33554432)
        message(FATAL_ERROR "source value input exceeds 32 MiB")
    endif()
    _aros_source_value_validate_relative_path("declaring FILE" "${file}" _relative_file)
    set(_declaring_file "${_root}/${_relative_file}")
    _aros_source_value_check_components("declaring FILE" "${_declaring_file}" "${_root}")
    _aros_source_value_require_regular_file("declaring FILE" "${_declaring_file}")
    file(REAL_PATH "${_declaring_file}" _file_real)
    if(NOT _file_real STREQUAL _declaring_file)
        message(FATAL_ERROR "source value declaring FILE is not canonical")
    endif()
    file(SIZE "${_declaring_file}" _file_size)
    if(_file_size GREATER 16777216)
        message(FATAL_ERROR "source value declaring FILE exceeds 16 MiB")
    endif()
    _aros_source_value_validate_sha256("FILE_SHA256" "${file_sha}" _expected_hash)
    file(SHA256 "${_declaring_file}" _actual_hash)
    if(NOT _actual_hash STREQUAL _expected_hash)
        message(FATAL_ERROR "source value declaring FILE SHA256 drifted")
    endif()
    set(AROS_SOURCE_VALUE_VALIDATED_ROOT "${_root}" PARENT_SCOPE)
    set(AROS_SOURCE_VALUE_VALIDATED_INPUT "${_input}" PARENT_SCOPE)
    set(AROS_SOURCE_VALUE_VALIDATED_FILE "${_declaring_file}" PARENT_SCOPE)
    set(AROS_SOURCE_VALUE_VALIDATED_FILE_SHA "${_expected_hash}" PARENT_SCOPE)
endfunction()

function(_aros_source_value_find_aligned_hex input_hex needle_hex start out)
    string(LENGTH "${input_hex}" _input_length)
    set(_cursor "${start}")
    while(_cursor LESS _input_length)
        string(SUBSTRING "${input_hex}" ${_cursor} -1 _tail)
        string(FIND "${_tail}" "${needle_hex}" _relative)
        if(_relative EQUAL -1)
            set(${out} -1 PARENT_SCOPE)
            return()
        endif()
        math(EXPR _match "${_cursor} + ${_relative}")
        math(EXPR _alignment "${_match} % 2")
        if(_alignment EQUAL 0)
            set(${out} "${_match}" PARENT_SCOPE)
            return()
        endif()
        math(EXPR _cursor "${_match} + 1")
    endwhile()
    set(${out} -1 PARENT_SCOPE)
endfunction()

function(_aros_source_value_stage_one input_hex marker_hex out)
    string(LENGTH "${input_hex}" _length)
    set(_result "")
    set(_cursor 0)
    while(_cursor LESS _length)
        _aros_source_value_find_aligned_hex("${input_hex}" "0a" "${_cursor}" _lf)
        set(_has_lf FALSE)
        if(_lf EQUAL -1)
            math(EXPR _line_length "${_length} - ${_cursor}")
        else()
            set(_has_lf TRUE)
            math(EXPR _line_length "${_lf} - ${_cursor}")
        endif()
        string(SUBSTRING "${input_hex}" ${_cursor} ${_line_length} _line)
        _aros_source_value_find_aligned_hex("${_line}" "${marker_hex}" 0 _marker)
        if(NOT _marker EQUAL -1)
        string(SUBSTRING "${_line}" 0 ${_marker} _prefix)
            string(LENGTH "${marker_hex}" _marker_hex_LENGTH)
            math(EXPR _after "${_marker} + ${_marker_hex_LENGTH}")
            string(LENGTH "${_line}" _line_hex_length)
            if(_after LESS _line_hex_length)
                string(SUBSTRING "${_line}" ${_after} -1 _suffix)
            else()
                set(_suffix "")
            endif()
            string(APPEND _result "${_prefix}${_suffix}")
            if(_has_lf)
                string(APPEND _result "0a")
            endif()
        endif()
        if(_has_lf)
            math(EXPR _cursor "${_lf} + 2")
        else()
            set(_cursor "${_length}")
        endif()
    endwhile()
    set(${out} "${_result}" PARENT_SCOPE)
endfunction()

function(_aros_source_value_stage_two input_hex out)
    string(LENGTH "${input_hex}" _length)
    set(_result "")
    set(_cursor 0)
    while(_cursor LESS _length)
        _aros_source_value_find_aligned_hex("${input_hex}" "0a" "${_cursor}" _lf)
        set(_has_lf FALSE)
        if(_lf EQUAL -1)
            math(EXPR _line_length "${_length} - ${_cursor}")
        else()
            set(_has_lf TRUE)
            math(EXPR _line_length "${_lf} - ${_cursor}")
        endif()
        string(SUBSTRING "${input_hex}" ${_cursor} ${_line_length} _line)
        set(_trimmed 0)
        while(_trimmed LESS _line_length)
            string(SUBSTRING "${_line}" ${_trimmed} 2 _byte)
            if(NOT _byte STREQUAL "20")
                break()
            endif()
            math(EXPR _trimmed "${_trimmed} + 2")
        endwhile()
        _aros_source_value_find_aligned_hex("${_line}" "20" "${_trimmed}" _space)
        _aros_source_value_find_aligned_hex("${_line}" "2a" "${_trimmed}" _star)
        _aros_source_value_find_aligned_hex("${_line}" "2f" "${_trimmed}" _slash)
        set(_delimiter -1)
        foreach(_candidate IN ITEMS "${_space}" "${_star}" "${_slash}")
            if(NOT _candidate EQUAL -1 AND (_delimiter EQUAL -1 OR _candidate LESS _delimiter))
                set(_delimiter "${_candidate}")
            endif()
        endforeach()
        if(NOT _delimiter EQUAL -1)
            math(EXPR _prefix_length "${_delimiter} - ${_trimmed}")
            string(SUBSTRING "${_line}" ${_trimmed} ${_prefix_length} _prefix)
            string(APPEND _result "${_prefix}")
            if(_has_lf)
                string(APPEND _result "0a")
            endif()
        endif()
        if(_has_lf)
            math(EXPR _cursor "${_lf} + 2")
        else()
            set(_cursor "${_length}")
        endif()
    endwhile()
    set(${out} "${_result}" PARENT_SCOPE)
endfunction()

function(_aros_source_value_compute input_hex marker_hex out)
    _aros_source_value_stage_one("${input_hex}" "${marker_hex}" _stage_one)
    _aros_source_value_stage_two("${_stage_one}" _result)
    set(${out} "${_result}" PARENT_SCOPE)
endfunction()

function(_aros_source_value_decode_hex hex out)
    string(LENGTH "${hex}" _length)
    set(_decoded "")
    set(_offset 0)
    while(_offset LESS _length)
        string(SUBSTRING "${hex}" ${_offset} 2 _byte_hex)
        math(EXPR _byte "0x${_byte_hex}")
        if(_byte EQUAL 0)
            message(FATAL_ERROR "source value output contains an unsupported NUL byte")
        endif()
        string(ASCII ${_byte} _character)
        string(APPEND _decoded "${_character}")
        math(EXPR _offset "${_offset} + 2")
    endwhile()
    set(${out} "${_decoded}" PARENT_SCOPE)
endfunction()

unset(_AROS_SOURCE_VALUE_TEST)
find_program(_AROS_SOURCE_VALUE_TEST NAMES test PATHS /usr/bin /bin NO_DEFAULT_PATH REQUIRED)
