cmake_minimum_required(VERSION 3.22)

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED MATCH_TEXT OR
   NOT DEFINED REPLACEMENT)
    message(FATAL_ERROR
        "TransformHeader.cmake requires INPUT, OUTPUT, MATCH_TEXT and REPLACEMENT")
endif()
if(NOT EXISTS "${INPUT}")
    message(FATAL_ERROR "transform input does not exist: ${INPUT}")
endif()

file(READ "${INPUT}" _content)
string(LENGTH "${_content}" _content_length)
string(LENGTH "${MATCH_TEXT}" _match_length)
set(_cursor 0)
set(_replacements 0)
set(_transformed "")
while(_cursor LESS _content_length)
    string(SUBSTRING "${_content}" "${_cursor}" -1 _tail)
    string(FIND "${_tail}" "${MATCH_TEXT}" _relative_match)
    if(_relative_match LESS 0)
        string(APPEND _transformed "${_tail}")
        set(_cursor "${_content_length}")
        continue()
    endif()

    math(EXPR _absolute_match "${_cursor} + ${_relative_match}")
    set(_at_line_start FALSE)
    if(_absolute_match EQUAL 0)
        set(_at_line_start TRUE)
    else()
        math(EXPR _before_at "${_absolute_match} - 1")
        string(SUBSTRING "${_content}" "${_before_at}" 1 _before)
        if(_before STREQUAL "\n")
            set(_at_line_start TRUE)
        endif()
    endif()

    if(_at_line_start)
        if(_relative_match GREATER 0)
            string(SUBSTRING "${_tail}" 0 "${_relative_match}" _prefix)
            string(APPEND _transformed "${_prefix}")
        endif()
        string(APPEND _transformed "${REPLACEMENT}")
        math(EXPR _cursor "${_absolute_match} + ${_match_length}")
        math(EXPR _replacements "${_replacements} + 1")
    else()
        # Preserve an embedded occurrence and advance beyond it. A global
        # string(REPLACE) would not match the line-anchored sed declaration.
        math(EXPR _chunk_length "${_relative_match} + ${_match_length}")
        string(SUBSTRING "${_tail}" 0 "${_chunk_length}" _chunk)
        string(APPEND _transformed "${_chunk}")
        math(EXPR _cursor "${_cursor} + ${_chunk_length}")
    endif()
endwhile()
if(_replacements EQUAL 0)
    message(FATAL_ERROR
        "transform input ${INPUT} has no line-start occurrence of the declared literal")
endif()

get_filename_component(_output_dir "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_output_dir}")
string(SHA256 _temp_key "${OUTPUT}")
set(_temporary "${OUTPUT}.${_temp_key}.tmp")
file(WRITE "${_temporary}" "${_transformed}")
execute_process(
    COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${_temporary}" "${OUTPUT}"
    COMMAND_ERROR_IS_FATAL ANY)
file(REMOVE "${_temporary}")
