cmake_minimum_required(VERSION 3.22)

if(NOT DEFINED ISO_PATH OR NOT EXISTS "${ISO_PATH}" OR
   IS_DIRECTORY "${ISO_PATH}" OR IS_SYMLINK "${ISO_PATH}")
    message(FATAL_ERROR "boot-iso did not produce a regular ISO file")
endif()
file(SIZE "${ISO_PATH}" _iso_size)
if(_iso_size LESS 65536)
    message(FATAL_ERROR "boot-iso produced a truncated ISO file")
endif()

# ISO9660 volume descriptors start at sector 16. A bootable CD must have an
# El Torito Boot Record whose catalog points to a bootable no-emulation entry.
set(_found FALSE)
foreach(_sector RANGE 16 31)
    math(EXPR _offset "${_sector} * 2048")
    file(READ "${ISO_PATH}" _header OFFSET ${_offset} LIMIT 39 HEX)
    string(TOUPPER "${_header}" _header)
    if(NOT _header MATCHES "^00434430303101")
        continue()
    endif()
    # 'EL TORITO SPECIFICATION' begins at byte 7 of a Boot Record.
    string(FIND "${_header}" "454C20544F5249544F2053504543494649434154494F4E" _id)
    if(NOT _id EQUAL 14)
        continue()
    endif()
    math(EXPR _pointer_offset "${_offset} + 71")
    file(READ "${ISO_PATH}" _pointer OFFSET ${_pointer_offset} LIMIT 4 HEX)
    string(TOUPPER "${_pointer}" _pointer)
    string(LENGTH "${_pointer}" _pointer_length)
    if(_pointer STREQUAL "00000000" OR NOT _pointer_length EQUAL 8 OR
       NOT _pointer MATCHES "^[0-9A-F]+$")
        message(FATAL_ERROR "boot-iso has no valid El Torito catalog pointer")
    endif()
    string(SUBSTRING "${_pointer}" 0 2 _b0)
    string(SUBSTRING "${_pointer}" 2 2 _b1)
    string(SUBSTRING "${_pointer}" 4 2 _b2)
    string(SUBSTRING "${_pointer}" 6 2 _b3)
    math(EXPR _catalog_sector "0x${_b3}${_b2}${_b1}${_b0}")
    math(EXPR _catalog_offset "${_catalog_sector} * 2048")
    math(EXPR _catalog_end "${_catalog_offset} + 64")
    if(_catalog_end GREATER _iso_size)
        message(FATAL_ERROR "boot-iso El Torito catalog is outside the ISO")
    endif()
    file(READ "${ISO_PATH}" _catalog OFFSET ${_catalog_offset} LIMIT 64 HEX)
    string(TOUPPER "${_catalog}" _catalog)
    string(SUBSTRING "${_catalog}" 0 2 _validation_type)
    string(SUBSTRING "${_catalog}" 60 4 _validation_signature)
    string(SUBSTRING "${_catalog}" 64 4 _boot_indicator_and_media)
    if(NOT _validation_type STREQUAL "01" OR
       NOT _validation_signature STREQUAL "55AA" OR
       NOT _boot_indicator_and_media STREQUAL "8800")
        message(FATAL_ERROR "boot-iso lacks a bootable no-emulation El Torito entry")
    endif()
    # Initial/default entry: load count is in 512-byte sectors at bytes 38-39,
    # followed by the boot image ISO LBA at bytes 40-43.
    string(SUBSTRING "${_catalog}" 76 4 _load_count_bytes)
    string(SUBSTRING "${_catalog}" 80 8 _image_lba_bytes)
    if(_load_count_bytes STREQUAL "0000" OR
       _image_lba_bytes STREQUAL "00000000")
        message(FATAL_ERROR "boot-iso has no loadable El Torito boot image")
    endif()
    string(SUBSTRING "${_load_count_bytes}" 0 2 _count_low)
    string(SUBSTRING "${_load_count_bytes}" 2 2 _count_high)
    math(EXPR _load_count "0x${_count_high}${_count_low}")
    string(SUBSTRING "${_image_lba_bytes}" 0 2 _lba0)
    string(SUBSTRING "${_image_lba_bytes}" 2 2 _lba1)
    string(SUBSTRING "${_image_lba_bytes}" 4 2 _lba2)
    string(SUBSTRING "${_image_lba_bytes}" 6 2 _lba3)
    math(EXPR _image_lba "0x${_lba3}${_lba2}${_lba1}${_lba0}")
    math(EXPR _image_offset "${_image_lba} * 2048")
    math(EXPR _image_end "${_image_offset} + ${_load_count} * 512")
    if(_image_offset LESS 65536 OR _image_end GREATER _iso_size)
        message(FATAL_ERROR "boot-iso El Torito boot image is outside the ISO")
    endif()
    file(READ "${ISO_PATH}" _image_start OFFSET ${_image_offset} LIMIT 64 HEX)
    if(_image_start MATCHES "^0+$")
        message(FATAL_ERROR "boot-iso El Torito boot image is empty")
    endif()
    set(_found TRUE)
    break()
endforeach()
if(NOT _found)
    message(FATAL_ERROR "boot-iso lacks an El Torito Boot Record")
endif()
