cmake_minimum_required(VERSION 3.22)

# Check the linked product, not merely the intermediate rewritten archive.
foreach(_required IN ITEMS GCA_PRODUCT GCA_KIND GCA_NM GCA_NM_SHA256
        GCA_MAP GCA_MAP_SHA256)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "Mesa 26 GCA verification lacks ${_required}")
    endif()
endforeach()
if(NOT GCA_KIND STREQUAL "vc4" AND NOT GCA_KIND STREQUAL "v3d" AND
   NOT GCA_KIND STREQUAL "provider")
    message(FATAL_ERROR "Mesa 26 GCA verification has unsupported product kind")
endif()
foreach(_input IN ITEMS "${GCA_PRODUCT}" "${GCA_NM}" "${GCA_MAP}")
    if(NOT EXISTS "${_input}" OR IS_DIRECTORY "${_input}" OR IS_SYMLINK "${_input}")
        message(FATAL_ERROR "Mesa 26 GCA verification input is not regular: ${_input}")
    endif()
endforeach()
file(SHA256 "${GCA_NM}" _nm_sha)
file(SHA256 "${GCA_MAP}" _map_sha)
if(NOT _nm_sha STREQUAL GCA_NM_SHA256 OR
   NOT _map_sha STREQUAL GCA_MAP_SHA256)
    message(FATAL_ERROR "Mesa 26 GCA verifier tool or import map changed")
endif()
execute_process(COMMAND "${GCA_NM}" -g --defined-only "${GCA_PRODUCT}"
    RESULT_VARIABLE _defined_status OUTPUT_VARIABLE _defined ERROR_VARIABLE _defined_error)
execute_process(COMMAND "${GCA_NM}" -u "${GCA_PRODUCT}"
    RESULT_VARIABLE _undefined_status OUTPUT_VARIABLE _undefined ERROR_VARIABLE _undefined_error)
if(NOT "${_defined_status}" STREQUAL "0" OR
   NOT "${_undefined_status}" STREQUAL "0")
    message(FATAL_ERROR "Mesa 26 GCA symbol scan failed: ${_defined_error}${_undefined_error}")
endif()

file(STRINGS "${GCA_MAP}" _imports)
list(LENGTH _imports _slot_count)
if(NOT _slot_count GREATER 0)
    message(FATAL_ERROR "Mesa 26 GCA import map is empty")
endif()
foreach(_line IN LISTS _imports)
    if(NOT _line MATCHES "^([A-Za-z_][A-Za-z0-9_]*) __gca_([A-Za-z_][A-Za-z0-9_]*)$")
        message(FATAL_ERROR "Mesa 26 GCA import map has an invalid entry: ${_line}")
    endif()
    if(NOT CMAKE_MATCH_1 STREQUAL CMAKE_MATCH_2)
        message(FATAL_ERROR "Mesa 26 GCA import map renames the wrong symbol: ${_line}")
    endif()
    if(NOT GCA_KIND STREQUAL "provider")
        string(REGEX REPLACE "^([^ ]+) .*$" "\\1" _symbol "${_line}")
        string(FIND "${_defined}" " __gca_${_symbol}\n" _found)
        if(_found EQUAL -1)
            message(FATAL_ERROR "Mesa 26 GCA trampoline is missing: ${_symbol}")
        endif()
    endif()
endforeach()

if(GCA_KIND STREQUAL "provider")
    set(_required_symbol "gallium_core_get_api")
elseif(GCA_KIND STREQUAL "vc4")
    set(_required_symbol "vc4_screen_create")
else()
    set(_required_symbol "v3d_screen_create")
endif()
string(FIND "${_defined}" " ${_required_symbol}\n" _found)
if(_found EQUAL -1)
    message(FATAL_ERROR "Mesa 26 GCA product lacks ${_required_symbol}")
endif()
if(NOT GCA_KIND STREQUAL "provider")
    string(FIND "${_defined}" " gca_bind\n" _found)
    if(_found EQUAL -1)
        message(FATAL_ERROR "Mesa 26 GCA consumer lacks gca_bind")
    endif()
endif()
string(REPLACE "\n" ";" _undefined_lines "${_undefined}")
foreach(_line IN LISTS _undefined_lines)
    if(_line MATCHES " U (gca_bind|gallium_core_get_api|__gca_[A-Za-z0-9_]+|vc4_screen_create|v3d_screen_create)$")
        message(FATAL_ERROR "Mesa 26 GCA product has an unresolved closure symbol: ${_line}")
    endif()
endforeach()
message(STATUS "Mesa 26 GCA ${GCA_KIND}: ${_slot_count} slots, linked symbols closed")
